import fs from 'node:fs';
import {kimiWebsite,kimiPackages,kimiDocuments} from '../seeds/kimiContent.js';
// Hex literals avoid SQL escaping differences and keep the seed reproducible.
const sql = value => value == null ? 'NULL' : `CONVERT(0x${Buffer.from(typeof value==='object'?JSON.stringify(value):String(value)).toString('hex')} USING utf8mb4) COLLATE utf8mb4_unicode_ci`;
const lines=['-- Kimi Cain standalone life-coaching practice. Seed-only: preserve subsequent edits.',
`INSERT INTO agencies (name,slug,organization_type,is_active,account_owner_user_id,public_availability_enabled,feature_flags,logo_url,color_palette,timezone,portal_url,use_default_password)
 SELECT 'Kimi Cain Life Coaching','kimi','life_coach',1,u.id,1,${sql({practitionerVertical:'life_coach',portalVariant:'employee',publicAvailabilityEnabled:true,discoveryBookingEnabled:true,discoveryBookingRequired:true,discoveryDurationMin:30,discoveryLabel:'Free coaching consultation'})},'/assets/kimi/logo.svg',${sql({primary:'#4e624b',secondary:'#c98d80',accent:'#e2e6d9'})},'America/Denver','kimi',0 FROM users u WHERE u.id=532 AND u.first_name='Kimi' AND u.last_name='Cain' AND NOT EXISTS (SELECT 1 FROM agencies WHERE slug='kimi');`,
`SET @kimi_agency = (SELECT id FROM agencies WHERE slug='kimi' AND organization_type='life_coach' AND account_owner_user_id=532);`,
`INSERT INTO user_agencies (user_id,agency_id,is_active) SELECT 532,@kimi_agency,1 WHERE @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM user_agencies WHERE user_id=532 AND agency_id=@kimi_agency);`,
`INSERT INTO agency_business_types (agency_id,business_type,is_enabled) SELECT @kimi_agency,'coaching',1 WHERE @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM agency_business_types WHERE agency_id=@kimi_agency AND business_type='coaching');`,
`INSERT INTO user_agency_practice_categories (agency_id,user_id,category,is_active,effect) SELECT @kimi_agency,532,'coaching',1,'grant' WHERE @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM user_agency_practice_categories WHERE agency_id=@kimi_agency AND user_id=532 AND category='coaching');`,
`INSERT INTO agency_public_service_types (agency_id,service_type,display_name,intro_blurb,is_enabled,sort_order) SELECT @kimi_agency,'coaching','Life Coaching','A free 30-minute conversation about your goals and coaching options.',1,0 WHERE @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM agency_public_service_types WHERE agency_id=@kimi_agency AND service_type='coaching');`,
`INSERT INTO provider_public_service_enrollments (agency_id,user_id,service_type,is_active) SELECT @kimi_agency,532,'coaching',1 WHERE @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM provider_public_service_enrollments WHERE agency_id=@kimi_agency AND user_id=532 AND service_type='coaching');`
];
for(const [key,label] of [['prospective','Prospective'],['screener','Consultation'],['packet','Enrollment'],['current','Current'],['pending','Pending'],['waitlist','Waitlist'],['inactive','Inactive']])lines.push(`INSERT INTO client_statuses (agency_id,status_key,label,is_active) SELECT @kimi_agency,${sql(key)},${sql(label)},1 WHERE @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM client_statuses WHERE agency_id=@kimi_agency AND status_key=${sql(key)});`);
// Fees intentionally NULL. A provider-discount quote requires a configured hourly rate.
for(const minutes of [30,60,90])lines.push(`INSERT INTO tenant_services (agency_id,business_type,name,description,service_code,default_duration_minutes,allows_individual,allows_group,modality,price_cents,billing_method,is_publicly_bookable,is_staff_bookable,package_eligible,program_eligible,is_active) SELECT @kimi_agency,'coaching','Life coaching — ${minutes} minutes','Individual life coaching; confirm format and price before purchase.','KIMI_COACH_${minutes}',${minutes},1,0,'EITHER',NULL,'self_pay',0,1,1,0,1 WHERE @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM tenant_services WHERE agency_id=@kimi_agency AND service_code='KIMI_COACH_${minutes}');`);
lines.push(`INSERT INTO staff_service_assignments (agency_id,tenant_service_id,user_id,is_active) SELECT @kimi_agency,s.id,532,1 FROM tenant_services s WHERE s.agency_id=@kimi_agency AND s.service_code IN ('KIMI_COACH_30','KIMI_COACH_60','KIMI_COACH_90') AND NOT EXISTS(SELECT 1 FROM staff_service_assignments x WHERE x.agency_id=@kimi_agency AND x.tenant_service_id=s.id AND x.user_id=532);`);
for(const p of kimiPackages){
const dc={sessionMinutes:p.minutes,deliveryMode:'1:1',autoEnrollSubject:false,pricing:{mode:'provider-discount',discountPercent:0,minutes:p.minutes,format:'virtual'},website:{key:p.key,subtitle:p.subtitle,items:p.items,icon:p.icon}};
lines.push(`INSERT INTO booking_packages (agency_id,business_type,name,description,package_type,session_count,price_cents,billing_options_json,policies_json,domain_config_json,allowed_tenant_service_ids_json,consume_on,is_active,is_public)
 SELECT @kimi_agency,'coaching',${sql(p.name)},${sql(p.description)},'prepaid_bundle',${p.sessions},0,${sql({modes:['pay_in_full']})},${sql({cancellationNoticeHours:24,lateCancelPolicy:'free_rebook',noShowPolicy:'free_rebook',expirationDays:null,freeMisses:0,bonusSessions:0})},${sql(dc)},JSON_ARRAY(s.id),'reserve',1,1 FROM tenant_services s WHERE s.agency_id=@kimi_agency AND s.service_code='KIMI_COACH_${p.minutes}' AND NOT EXISTS(SELECT 1 FROM booking_packages WHERE agency_id=@kimi_agency AND name=${sql(p.name)});`);
}
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
for(const [i,d]of kimiDocuments.entries()){
const html=`<article><h1>${esc(d.name)}</h1><p>Kimi Cain Life Coaching · Version 1 · September 14, 2026</p>${d.sections.map(([h,b])=>`<h2>${esc(h)}</h2><p>${esc(b)}</p>`).join('')}<p>Client signature and date are recorded electronically with this document.</p></article>`;
lines.push(`INSERT INTO document_templates (name,description,template_type,html_content,agency_id,created_by_user_id,document_type,document_action_type,is_active,is_required,version) SELECT ${sql(d.name)},'Original coaching-specific agreement. Review with Colorado counsel and update when financial or operational terms change.','html',${sql(html)},@kimi_agency,532,'consent','signature',1,1,1 WHERE @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM document_templates WHERE agency_id=@kimi_agency AND name=${sql(d.name)});`);
lines.push(`SET @kimi_doc_${i} = (SELECT id FROM document_templates WHERE agency_id=@kimi_agency AND name=${sql(d.name)} ORDER BY version DESC,id DESC LIMIT 1);`);
}
const field=(key,label,type='text',required=true,scope='submission',options)=>({key,label,type,required,scope,...(options?{options}: {})});
const base=[field('adult_confirmation','I am 18 or older and am requesting coaching for myself.','checkbox'),field('first_name','First name','text',true,'client'),field('last_name','Last name','text',true,'client'),field('email','Email address','email',true,'client'),field('phone','Phone number','tel',false,'client')];
const prefs=[field('goals','What would you like to work toward?','textarea',false),field('format','Preferred consultation format','select',true,'submission',[{value:'video',label:'Video'},{value:'phone',label:'Phone'},{value:'in-person',label:'In person, if available'}]),field('availability','What days and times usually work for you? Include your time zone.','textarea',false),field('package','Package you would like to discuss','select',false,'submission',[{value:'unsure',label:'Help me choose'},...kimiPackages.map(p=>({value:p.key,label:p.name}))]),field('coaching_scope','I understand this is life coaching, not mental-health treatment. For counseling I will use Next Level Up’s intake.','checkbox')];
for(const full of [false,true]){
 const key=full?'kimi-coaching-enrollment':'kimi-coaching-inquiry';
 const fields=[...base,...prefs,...(full?[field('strengths','What strengths and supports can you build on?','textarea',false),field('progress','How will you know coaching is helping?','textarea',false),field('accountability','What kind of encouragement or accountability works for you?','textarea',false),field('preferences','Anything you would like Kimi to know about your communication or accessibility preferences?','textarea',false)]:[])];
 lines.push(`INSERT INTO intake_links (public_key,title,description,scope_type,form_type,organization_id,is_active,create_client,create_guardian,requires_assignment,allowed_document_template_ids,intake_fields,intake_steps,custom_messages,created_by_user_id)
 SELECT '${key}',${sql(full?'Kimi Cain — Coaching Enrollment':'Kimi Cain — Coaching Consultation Request')},${sql(full?'Your coaching goals and original coaching agreements. This does not enroll you in NLU counseling or authorize a payment.':'Share your contact details and preferences. This is a request, not a confirmed appointment. Please do not include a clinical history.')},'agency',${sql(full?'intake':'public_form')},@kimi_agency,1,${full?1:0},0,1,${full?'JSON_ARRAY(@kimi_doc_0,@kimi_doc_1,@kimi_doc_2)':'JSON_ARRAY()'},${sql(fields)},${full?`JSON_ARRAY(${kimiDocuments.map((_,i)=>`JSON_OBJECT('id','kimi-document-${i}','type','document','templateId',@kimi_doc_${i},'label',${sql(kimiDocuments[i].name)},'visibility','always')`).join(',')})`:'JSON_ARRAY()'},${sql({serviceScope:'coaching',completionTitle:'Thank you for reaching out',completionMessage:'Kimi will review your request and contact you about next steps. No appointment or paid package is confirmed by this form.'})},532 WHERE @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM intake_links WHERE public_key='${key}');`);
}
lines.push(`INSERT INTO public_marketing_pages (slug,title,is_active,page_type,hero_title,hero_subtitle,hero_image_url,branding_json,seo_json) SELECT 'kimi','Kimi Cain Life Coaching',1,'marketing_hub',${sql(kimiWebsite.pages.home.title)},${sql(kimiWebsite.pages.home.body)},'/assets/kimi/portrait.png',${sql({landingTemplate:'kimi',logoUrl:'/assets/kimi/logo.svg',programThemePrimary:'#4e624b',kimiWebsite})},${sql({title:'Kimi Cain | Life Coaching',description:'Personalized life coaching for clarity, confidence, transitions, and meaningful progress. Meet Kimi Cain and book a free consultation.'})} WHERE @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public_marketing_pages WHERE slug='kimi');`);
lines.push(`INSERT INTO public_marketing_page_sources (page_id,source_type,source_id,sort_order,is_active) SELECT p.id,'agency',@kimi_agency,0,1 FROM public_marketing_pages p WHERE p.slug='kimi' AND @kimi_agency IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public_marketing_page_sources WHERE page_id=p.id AND source_type='agency' AND source_id=@kimi_agency);`);
fs.writeFileSync(new URL('../../../database/migrations/1443_kimi_coaching_practice.sql',import.meta.url),lines.join('\n\n')+'\n');
