export default {
  id: 'provider_directory',
  version: 1,
  steps: [
    {
      element: '[data-tour="provdir-title"]',
      popover: {
        title: 'Provider Directory',
        description: 'Search providers by profile fields and build structured filters (optionally generated by AI).',
        side: 'bottom',
        align: 'start'
      }
    },
    {
      element: '[data-tour="provdir-actions"]',
      popover: {
        title: 'Actions',
        description: 'Rebuild index when needed, then run search to fetch matches.',
        side: 'bottom',
        align: 'end'
      }
    },
    {
      element: '[data-tour="provdir-filters"]',
      popover: {
        title: 'Filters',
        description: 'Use free text, agency, bachelor-only, AI filter generation, and structured filters to narrow results.',
        side: 'top',
        align: 'start'
      }
    },
    {
      element: '[data-tour="provdir-results"]',
      popover: {
        title: 'Results',
        description: 'Open a provider’s user profile from the results list.',
        side: 'top',
        align: 'start'
      }
    }
  ]
};

