// @vitest-environment jsdom
import {beforeEach,it,expect,vi} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import Review from '../ProviderUpdateReviewSend.vue';
const m=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),issues:[],amendment:true}));
vi.mock('../../../services/api',()=>({default:m}));
const push={id:2,title:'October provider update',status:'draft',section_config_json:{amendments:true},amendment_plan_json:{mode:'compensation'}};
beforeEach(()=>{vi.clearAllMocks();m.issues=[];m.amendment=true;
 m.get.mockImplementation(async path=>({data:path.includes('eligible-providers')?{providers:[{provider_user_id:465,first_name:'Aunya',last_name:'Albinana',work_email:'a@example.test'},{provider_user_id:466,first_name:'Caitlyn',last_name:'Sears',work_email:'c@example.test'}]}:path==='/provider-update/pushes/2'?{push,recipients:[]}:path.endsWith('/amendment')?{amendment:{id:20,name:'Aunya Albinana',draft:true,html:'<h1>Aunya — $44</h1>',issues:m.issues}}:{sections:m.amendment?[{key:'amendments'}]:[]}}));
 m.post.mockImplementation(async path=>({data:path.endsWith('/preview-link')?{token:'preview_abc',publicUrl:'https://example.test/preview'}:path.endsWith('/send')?{results:[{providerUserId:465,deliveryStatus:'sent'}]}:{taskId:12}}));
});
async function render(){const w=mount(Review,{props:{agencyId:2,pushes:[push]},global:{stubs:{ProviderUpdateTrainingEditor:true}}});await flushPromises();await w.findAll('select')[1].setValue('465');return w;}
async function preview(w){await w.findAll('button').find(b=>b.text().startsWith('Preview ')).trigger('click');await flushPromises();}
it('preview loads the actual agreement without releasing or sending; the send button needs review confirmation',async()=>{const w=await render();await preview(w);expect(w.get('iframe').attributes('srcdoc')).toContain('Aunya — $44');expect(m.post).toHaveBeenCalledTimes(1);expect(w.findAll('button').find(b=>b.text().includes('only')).attributes('disabled')).toBeDefined();w.unmount();});
it('releases only the displayed draft with its exact HTML and sends exactly one provider ID',async()=>{const w=await render();await preview(w);await w.get('input[type=checkbox]').setValue(true);await w.findAll('button').find(b=>b.text().includes('only')).trigger('click');await flushPromises();expect(m.post).toHaveBeenCalledWith('/provider-update/compensation-drafts/20/release',{agencyId:2,pushId:2,expectedHtml:'<h1>Aunya — $44</h1>'});expect(m.post).toHaveBeenCalledWith('/provider-update/pushes/2/send',{agencyId:2,providerUserIds:[465]});expect(w.text()).toContain('Invitation sent to Aunya');w.unmount();});
it('changing people clears both the reviewed agreement and approval',async()=>{const w=await render();await preview(w);await w.get('input[type=checkbox]').setValue(true);await w.findAll('select')[1].setValue('466');expect(w.find('iframe').exists()).toBe(false);expect(w.find('input[type=checkbox]').exists()).toBe(false);expect(m.post).toHaveBeenCalledTimes(1);w.unmount();});
it('blocks sending if amendment review items remain',async()=>{m.issues=['Confirm category'];const w=await render();await preview(w);expect(w.text()).toContain('Confirm category');expect(w.get('input[type=checkbox]').attributes('disabled')).toBeDefined();w.unmount();});
it('does not send when release detects the draft changed since review',async()=>{const w=await render();await preview(w);m.post.mockRejectedValueOnce({response:{data:{error:{message:'The amendment changed. Review again.'}}}});await w.get('input[type=checkbox]').setValue(true);await w.findAll('button').find(b=>b.text().includes('only')).trigger('click');await flushPromises();expect(m.post.mock.calls.some(([url])=>url.endsWith('/send'))).toBe(false);expect(w.text()).toContain('The amendment changed');w.unmount();});
