// @vitest-environment jsdom
import {beforeEach,it,expect,vi} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import Review from '../ProviderUpdateReviewSend.vue';
const m=vi.hoisted(()=>({get:vi.fn(),post:vi.fn(),issues:[],amendment:true,recipients:[]}));
vi.mock('../../../services/api',()=>({default:m}));
const push={id:2,title:'October provider update',status:'draft',section_config_json:{amendments:true},amendment_plan_json:{mode:'compensation'}};
beforeEach(()=>{vi.clearAllMocks();m.issues=[];m.amendment=true;m.recipients=[];
 m.get.mockImplementation(async path=>({data:path.includes('eligible-providers')?{providers:[{provider_user_id:465,first_name:'Aunya',last_name:'Albinana',work_email:'a@example.test'},{provider_user_id:466,first_name:'Caitlyn',last_name:'Sears',work_email:'c@example.test'}]}:path==='/provider-update/pushes/2'?{push,recipients:m.recipients}:path.endsWith('/amendment')?{amendment:{id:20,name:'Aunya Albinana',draft:true,html:'<h1>Aunya — $44</h1>',issues:m.issues}}:{sections:m.amendment?[{key:'amendments'}]:[]}}));
 m.post.mockImplementation(async path=>({data:path.endsWith('/preview-link')?{token:'preview_abc',publicUrl:'https://example.test/preview'}:path.endsWith('/send')?{results:[{providerUserId:465,deliveryStatus:'sent'}]}:{taskId:12}}));
});
async function render(){const w=mount(Review,{props:{agencyId:2,pushes:[push]},global:{stubs:{ProviderUpdateTrainingEditor:true}}});await flushPromises();return w;}
async function preview(w){await w.get('[data-person-id="465"] .row-preview').trigger('click');await flushPromises();}
it('preview loads the actual agreement without releasing or sending; the send button needs review confirmation',async()=>{const w=await render();await preview(w);expect(w.get('iframe').attributes('srcdoc')).toContain('Aunya — $44');expect(m.post).toHaveBeenCalledTimes(1);expect(w.findAll('button').find(b=>b.text().includes('only')).attributes('disabled')).toBeDefined();w.unmount();});
it('releases only the displayed draft with its exact HTML and sends exactly one provider ID',async()=>{const w=await render();await preview(w);await w.get('input[type=checkbox]').setValue(true);await w.findAll('button').find(b=>b.text().includes('only')).trigger('click');await flushPromises();expect(m.post).toHaveBeenCalledWith('/provider-update/compensation-drafts/20/release',{agencyId:2,pushId:2,expectedHtml:'<h1>Aunya — $44</h1>'});expect(m.post).toHaveBeenCalledWith('/provider-update/pushes/2/send',{agencyId:2,providerUserIds:[465]});expect(w.text()).toContain('Invitation sent to Aunya');w.unmount();});
it('changing people clears both the reviewed agreement and approval',async()=>{const w=await render();await preview(w);await w.get('input[type=checkbox]').setValue(true);await w.get('.close-review').trigger('click');await w.get('[data-person-id="466"] .row-preview').trigger('click');await flushPromises();expect(w.get('input[type=checkbox]').element.checked).toBe(false);expect(m.post).toHaveBeenCalledTimes(2);w.unmount();});
it('blocks sending if amendment review items remain',async()=>{m.issues=['Confirm category'];const w=await render();await preview(w);expect(w.text()).toContain('Confirm category');expect(w.get('input[type=checkbox]').attributes('disabled')).toBeDefined();w.unmount();});
it('does not send when release detects the draft changed since review',async()=>{const w=await render();await preview(w);m.post.mockRejectedValueOnce({response:{data:{error:{message:'The amendment changed. Review again.'}}}});await w.get('input[type=checkbox]').setValue(true);await w.findAll('button').find(b=>b.text().includes('only')).trigger('click');await flushPromises();expect(m.post.mock.calls.some(([url])=>url.endsWith('/send'))).toBe(false);expect(w.text()).toContain('The amendment changed');w.unmount();});

it('lists everyone with progress, active time and delivery status beside uninvited staff',async()=>{m.recipients=[{provider_user_id:465,status:'in_progress',sections_completed:3,sections_total:8,active_seconds:754,last_delivery_status:'sent',last_sent_at:'2026-10-09 12:00:00',last_viewed_at:'2026-10-09 12:05:00',timeSummary:{sections:{pin:120,work_hours:634}}}];const w=await render();const row=w.get('[data-person-id="465"]');expect(row.text()).toContain('3 / 8 sections');expect(row.text()).toContain('12m 34s');expect(row.text()).toContain('Sent');expect(row.text()).toContain('Time by section');expect(w.get('[data-person-id="466"]').text()).toContain('Not sent');expect(w.get('[data-person-id="466"]').text()).toContain('0m 0s');w.unmount();});
it('keeps approval on the reviewed row and sends that person directly from the table',async()=>{const w=await render();await preview(w);await w.get('input[type=checkbox]').setValue(true);await w.get('.close-review').trigger('click');expect(w.find('.review-dialog').exists()).toBe(false);expect(w.get('[data-person-id="465"] .row-send').attributes('disabled')).toBeUndefined();expect(w.get('[data-person-id="466"] .row-send').attributes('disabled')).toBeDefined();await w.get('[data-person-id="465"] .row-send').trigger('click');await flushPromises();expect(m.post).toHaveBeenCalledWith('/provider-update/pushes/2/send',{agencyId:2,providerUserIds:[465]});expect(w.get('[data-person-id="465"] .row-send').attributes('disabled')).toBeDefined();w.unmount();});
it('refreshes progress without opening a preview or sending a message',async()=>{const w=await render();m.recipients=[{provider_user_id:466,status:'finalized',sections_completed:8,sections_total:8,active_seconds:3602,last_delivery_status:'pending'}];await w.findAll('button').find(b=>b.text()==='Refresh progress').trigger('click');await flushPromises();const row=w.get('[data-person-id="466"]');expect(row.text()).toContain('Complete');expect(row.text()).toContain('1h 0m 2s');expect(row.text()).toContain('Pending delivery');expect(m.post).not.toHaveBeenCalled();w.unmount();});
