<template>
  <details class="application-preview" open>
    <summary>Preview the applicant’s welcome page</summary>
    <p>Applicants arrive here after choosing <strong>Apply Now</strong> on a job posting, before entering their information. This preview updates as you edit. Empty job fields use agency defaults.</p>
    <p v-if="publicUrl"><a :href="publicUrl" target="_blank" rel="noopener">Open saved application page ↗</a><br /><small>{{ publicUrl }} · Save the job to publish your changes.</small></p>
    <p v-else>The public application link will appear on the job listing after the job and its application link are created.</p>
    <nav aria-label="Preview sections"><button v-for="region in regions" :key="region.id" type="button" @click="showRegion(region.id)">{{ region.label }}</button><button type="button" @click="mobile = !mobile">{{ mobile ? 'Desktop preview' : 'Mobile preview' }}</button></nav>
    <div ref="canvas" class="preview-canvas" :class="{ mobile }">
      <header data-region="header"><small class="region">1 · Header</small><div class="preview-header"><strong>{{ agencyName || 'Your organization' }}</strong><div><strong>{{ page.secureTitle || 'Secure & Confidential' }}</strong><small>{{ page.secureSubtitle || 'Your information is always protected' }}</small></div></div></header>
      <section data-region="hero"><small class="region">2 · Welcome and photo</small><div class="preview-hero" :class="{ 'no-image': !heroUrl }"><div><p v-if="page.eyebrow" class="eyebrow">{{ page.eyebrow }}</p><h2>{{ titleBase }} <span v-if="highlight">{{ highlight }}</span></h2><p v-if="page.lead">{{ page.lead }}</p><p v-if="!hasSections">{{ job.descriptionText }}</p><p>{{ [job.roleType, job.city, job.state, job.scheduleText].filter(Boolean).join(' · ') }}</p></div><figure v-if="heroUrl" :class="frameStyle"><span v-if="frameStyle === 'organic' && page.showLeafAccent !== false" class="leaf" aria-hidden="true">❧</span><img :src="heroUrl" :alt="page.heroImageAlt || job.title || 'Job image'" :style="{ objectPosition: page.heroImagePosition || 'center center' }" /></figure></div></section>
      <section data-region="features"><small class="region">3 · Job highlights — below the welcome area</small><div v-if="page.featureCards.length" class="preview-cards"><article v-for="(card,i) in page.featureCards" :key="i"><img v-if="iconUrl(card.icon)" :src="iconUrl(card.icon)" alt="" /><span v-else aria-hidden="true">{{ emoji[card.icon] || '' }}</span><strong>{{ card.title }}</strong><p>{{ card.body }}</p></article></div><p v-else class="empty">No highlight cards configured. This section will be hidden.</p></section>
      <section data-region="details"><small class="region">4 · Role details — from the job description above</small><JobDescriptionSections v-if="hasSections" :sections="job.descriptionSections" :title="job.title" show-header compact /><p v-else class="empty">Add the role description, responsibilities, qualifications, compensation and benefits above.</p></section>
      <section data-region="start"><small class="region">5 · Start application — opens the application questions</small><div class="preview-start"><h3>{{ page.startHeading || 'Ready to take the next step?' }}</h3><p>{{ page.startSubtitle || 'Click below to start your application. It only takes a few minutes.' }}</p><button type="button" @click="startNotice = true">{{ page.startButtonText || 'Start job application' }} →</button><small>{{ page.startTimeNote || 'Takes 3-5 minutes to begin' }}</small><p v-if="startNotice" role="status">Preview only. On the public page, this button begins the application form.</p></div></section>
      <section data-region="trust"><small class="region">6 · Reassurance — below the start button</small><div v-if="page.trustItems.length" class="preview-cards"><article v-for="(card,i) in page.trustItems" :key="i"><img v-if="iconUrl(card.icon)" :src="iconUrl(card.icon)" alt="" /><span v-else aria-hidden="true">{{ emoji[card.icon] || '' }}</span><strong>{{ card.title }}</strong><p>{{ card.body }}</p></article></div><p v-else class="empty">No reassurance cards configured. This section will be hidden.</p></section>
    </div>
    <small>Section labels are guides for you and are not displayed to applicants.</small>
  </details>
</template>
<script setup>
import { computed, ref, watch, onBeforeUnmount } from 'vue';
import JobDescriptionSections from './JobDescriptionSections.vue';
import { getFeatureIconUrl, getHeroPresetByUrl } from '../../utils/careersAssets';
const props = defineProps({ config: { type:Object, default:()=>({}) }, defaults: { type:Object, default:()=>({}) }, job: { type:Object, default:()=>({}) }, agencyName:String, publicUrl:String, heroFile:Object, assetUrl: { type:Function, default:value=>value } });
const regions = [{id:'header',label:'1 Header'},{id:'hero',label:'2 Welcome & photo'},{id:'features',label:'3 Highlights'},{id:'details',label:'4 Role details'},{id:'start',label:'5 Start button'},{id:'trust',label:'6 Reassurance'}];
const canvas = ref(null), mobile = ref(false), startNotice = ref(false), uploadUrl = ref('');
const cards = value => (Array.isArray(value) ? value : []).filter(c=>c.title?.trim() || c.body?.trim());
const page = computed(()=> {
  const result = {};
  for (const key of ['eyebrow','lead','titleHighlight','heroImageUrl','heroImageAlt','heroImagePosition','heroFrameStyle','secureTitle','secureSubtitle','startHeading','startSubtitle','startButtonText','startTimeNote']) result[key] = String(props.config[key] || props.defaults[key] || '').trim();
  result.showLeafAccent = props.config.showLeafAccent ?? props.defaults.showLeafAccent;
  for (const key of ['featureCards','trustItems']) result[key] = cards(props.config[key]).length ? cards(props.config[key]) : cards(props.defaults[key]);
  return result;
});
const highlight = computed(()=>page.value.titleHighlight || (props.job.city && props.job.title?.toLowerCase().includes(props.job.city.toLowerCase()) ? props.job.city : ''));
const titleBase = computed(()=> { const title = props.job.title || 'Job title'; const end = highlight.value; return end && title.toLowerCase().endsWith(end.toLowerCase()) ? title.slice(0,-end.length).replace(/[\s–—-]+$/, '') || title : title; });
const heroUrl = computed(()=>uploadUrl.value || props.assetUrl(page.value.heroImageUrl));
const frameStyle = computed(()=>page.value.heroFrameStyle || getHeroPresetByUrl(page.value.heroImageUrl)?.frameStyle || 'preframed');
const hasSections = computed(()=>Object.values(props.job.descriptionSections || {}).some(v=>Array.isArray(v) ? v.some(x=>typeof x === 'string' ? x.trim() : x.title || x.items?.length) : String(v || '').trim()));
const emoji = { school:'🏫',office:'🏢',people:'👥',heart:'♡',shield:'🛡',lock:'🔒',handshake:'🤝',star:'☆' };
const iconUrl = name=>getFeatureIconUrl(name);
function showRegion(id) { canvas.value?.querySelector(`[data-region="${id}"]`)?.scrollIntoView({ behavior:'smooth', block:'nearest' }); }
watch(()=>props.heroFile, file=> { if (uploadUrl.value) URL.revokeObjectURL(uploadUrl.value); uploadUrl.value = file ? URL.createObjectURL(file) : ''; }, { immediate:true });
onBeforeUnmount(()=> { if (uploadUrl.value) URL.revokeObjectURL(uploadUrl.value); });
</script>
<style scoped>
.application-preview { padding: 16px; border: 1px solid #b8cfca; border-radius: 10px; margin: 16px 0; background: #f3f8f7; color:#223646; }.application-preview summary { cursor:pointer; font-weight:700; }.application-preview p { line-height:1.5; }.application-preview nav { display:flex; gap:6px; flex-wrap:wrap; margin:12px 0; }.application-preview nav button { border:1px solid #b8cfca; padding:7px 10px; border-radius:6px; background:white; color:#185c48; cursor:pointer; }.preview-canvas { background:white; border:1px solid #dce4e8; border-radius:12px; max-height:640px; overflow:auto; margin:auto; width:100%; }.preview-canvas.mobile { max-width:390px; }.preview-canvas section,.preview-canvas header { padding:18px; border-bottom:1px solid #e7edef; scroll-margin:8px; }.region { display:block; color:#466277; background:#eef3f7; border-radius:4px; padding:5px 8px; margin-bottom:14px; font-size:12px; }.preview-header,.preview-hero { display:flex; justify-content:space-between; gap:20px; align-items:center; }.preview-header small,.preview-start small { display:block; margin-top:5px; }.preview-hero>div { flex:1; }.preview-hero figure { width:42%; margin:0; position:relative; }.preview-hero img { width:100%; display:block; object-fit:cover; aspect-ratio:1; }.preview-hero .preframed img { object-fit:contain; }.preview-hero .organic img { border-radius:45% 55% 36% 64%; }.preview-hero .rounded img { border-radius:20px; }.leaf { position:absolute; right:0; top:-20px; font-size:70px; color:#438860; }.preview-hero h2 { text-align:left; font-size:30px; line-height:1.2; }.preview-hero h2 span { color:#1a8c54; }.eyebrow { color:#1a8c54; font-weight:700; }.preview-cards { display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr)); gap:12px; }.preview-cards article { padding:12px; background:#f4f8f6; border-radius:10px; }.preview-cards img { width:32px; height:32px; object-fit:contain; }.preview-cards strong { display:block; }.preview-start { text-align:center; background:#eff7f2; border-radius:12px; padding:20px; }.preview-start button { background:#1a7454; border:0; color:white; padding:12px 22px; border-radius:8px; cursor:pointer; }.empty { color:#64748b; font-style:italic; }.mobile .preview-hero,.mobile .preview-header { display:block; }.mobile .preview-hero figure { width:100%; }.mobile :deep(.jds-grid) { columns:1; }@media(max-width:600px) { .preview-hero,.preview-header { display:block; }.preview-hero figure { width:100%; } }
</style>
