// Invented records only. These fixtures never query a live organization.
export const agencies=[{id:990001,name:'Redwood Community Care',slug:'redwood-example',portal_url:'redwood-example',organization_type:'agency',feature_flags:{hiringEnabled:true,peopleOpsEnabled:true}},{id:990002,name:'Redwood Learning Center',slug:'redwood-learning-example',portal_url:'redwood-learning-example',organization_type:'agency',feature_flags:{hiringEnabled:true,peopleOpsEnabled:true}}];
const people=[['Avery','Brooks','Care Coordinator'],['Morgan','Reed','Program Specialist'],['Jordan','Lee','Learning Coordinator'],['Sam','Rivera','Team Lead']];
export const employees=people.map(([first_name,last_name,job_title],i)=>({id:990010+i,first_name,last_name,job_title,email:`example-${i+1}@example.com`,work_email:`example-${i+1}@example.com`,hired_at:'2026-09-28',created_at:'2026-09-21',progress_pct:[75,50,100,25][i],task_completed:[6,4,8,2][i],task_total:8,overdue_count:0}));
export const modules=[{id:990101,title:'Welcome to Redwood',description:'Meet your team, understand our mission, and find the resources you need for a confident start.',estimated_time_minutes:20,content_count:4},{id:990102,title:'Working together',description:'Practice clear handoffs, helpful feedback, and everyday team communication.',estimated_time_minutes:30,content_count:6},{id:990103,title:'Your first month',description:'A guided learning path through the people, tools, and routines of your new role.',estimated_time_minutes:45,content_count:5}];
const pipeline=['applied','screening','interview','offered'].map((stage,i)=>({stage,label:['Applied','Screening','Interview','Offer'][i],count:[8,5,3,2][i]}));
const pipelineCandidates=employees.map((e,i)=>({userId:e.id,id:e.id,firstName:e.first_name,lastName:e.last_name,name:`${e.first_name} ${e.last_name}`,email:e.email,agencyId:i<3?990001:990002,agencyName:i<3?agencies[0].name:agencies[1].name,jobTitle:e.job_title,bucket:['newApplicants','inPrehire','awaitingDocuments','readyForOnboarding'][i],tab:i<2?'needs':'progress',stage:['Applied','Pre-hire','Awaiting documents','Ready for onboarding'][i],updatedAt:'2026-10-06T12:00:00Z'}));
const jobs=[{id:990201,title:'Care Coordinator',applicantCount:8,newForMeCount:3},{id:990202,title:'Program Specialist',applicantCount:6,newForMeCount:2},{id:990203,title:'Learning Coordinator',applicantCount:4,newForMeCount:1}];
const checklist={completionPercentage:50,items:[{id:1,item_type:'profile',title:'Complete your profile',description:'Confirm your contact information and role details.',is_completed:true,completed_at:'2026-10-02'},{id:2,item_type:'document',title:'Review the employee handbook',description:'Read the handbook and complete your acknowledgment.',is_completed:true,completed_at:'2026-10-03'},{id:3,item_type:'training',item_id:990101,title:'Welcome to Redwood',description:'Meet the team and learn how we work together.',is_completed:false},{id:4,item_type:'custom',title:'Meet with your team lead',description:'Discuss your first-month goals and questions.',is_completed:false}]};
export function fixture(url){
 if(url==='/hiring/dashboard')return {openJobs:3,totalApplicants:18,pendingReviews:8,upcomingInterviewsCount:2,stageCounts:{offered:2},jobs,pipeline,upcomingInterviews:employees.slice(0,2).map((e,i)=>({id:e.id,candidateUserId:e.id,firstName:e.first_name,lastName:e.last_name,jobTitle:e.job_title,startsAt:`2026-10-09T${i+15}:00:00Z`})),recentApplicants:[]};
 if(url==='/hiring/pipeline-board')return {agencies,counts:{},candidates:pipelineCandidates};
 if(url==='/hiring/onboarding-candidates')return employees;
 if(url==='/on-demand-training/modules')return modules;
 if(url==='/progress')return [{module_id:990101,status:'completed'},{module_id:990102,status:'in_progress'}];
 if(url==='/certificates')return [{id:990301,module_id:990101}];
 if(url.includes('/onboarding-checklist'))return checklist;
 if(url==='/evaluations/period')return {periodYear:2026,periodHalf:'H2'};
 if(url==='/evaluations/roster')return {period:{periodYear:2026,periodHalf:'H2'},employees:employees.map((e,i)=>({userId:e.id,firstName:e.first_name,lastName:e.last_name,email:e.email,jobTitle:e.job_title,rosterStatus:['scheduled','in_progress','submitted','reviewed'][i],cycle:{dueAt:'2026-11-15T12:00:00Z'}}))};
 if(url.startsWith('/public-intake/careers/'))return {agency:{id:990001,name:'Redwood Community Care',officialName:'Redwood Community Care',careersPage:{heroHeadline:'Work that makes a difference.',heroSubheadline:'Grow with purpose.',heroImageUrl:'/assets/plotline/website/photos/reference/people-collaboration.jpg'}},jobs:jobs.map(j=>({...j,city:'Denver',state:'CO',employmentType:'Full-time',descriptionText:'Support our community through thoughtful, collaborative work.',is_active:1,is_featured:true,application_url:'#',created_at:'2026-10-01'}))};
 return [];
}
