import {createApp,h} from 'vue';
import {createPinia} from 'pinia';
import {createRouter,createMemoryHistory} from 'vue-router';
import api from '../../src/services/api.js';
import {useAuthStore} from '../../src/store/auth.js';
import {useAgencyStore} from '../../src/store/agency.js';
import {useBrandingStore} from '../../src/store/branding.js';
import {agencies,fixture} from './fixtures.js';
import '../../src/style.css';
import '../../src/styles/data-surfaces.css';
import '../../src/styles/application-appearance.css';
const views={hiring:()=>import('../../src/views/admin/HiringDashboardView.vue'),onboarding:()=>import('../../src/views/admin/OnboardingAdminView.vue'),learning:()=>import('../../src/views/MyLearningView.vue'),checklist:()=>import('../../src/views/OnboardingChecklistView.vue'),evaluations:()=>import('../../src/components/evaluations/EvaluationRosterPanel.vue'),careers:()=>import('../../src/views/public/PublicCareersView.vue'),organizations:()=>import('../../src/components/admin/opsDashboard/PeopleOpsPipelineCard.vue')};
const screen=new URLSearchParams(location.search).get('screen')||'hiring';
if(!views[screen])throw new Error('Unknown capture screen');
api.get=async url=>({data:fixture(url)});
for(const method of ['post','put','patch','delete'])api[method]=async()=>{throw new Error('Writes are disabled in the capture fixture.');};
const view=(await views[screen]()).default;
const app=createApp({render:()=>h(view,screen==='evaluations'?{agencyId:990001}:{} )});
app.use(createPinia());
const router=createRouter({history:createMemoryHistory(),routes:[{path:'/careers/:agencySlug',component:{}},{path:'/:organizationSlug/:pathMatch(.*)*',component:{}}]});
app.use(router);await router.push(screen==='careers'?'/careers/redwood-example':'/redwood-example/admin/hiring');
if(screen!=='careers')useAuthStore().setAuth(null,{id:990000,role:'admin',first_name:'Taylor',last_name:'Example',agencyId:990001,agencyIds:[990001,990002],capabilities:{canManageHiring:true,canViewTraining:true,canSignDocuments:true}});
const store=useAgencyStore();store.currentAgency=agencies[0];store.userAgencies=agencies;store.agencies=agencies;
useBrandingStore().fetchAgencyTheme=async()=>{};
app.mount('#capture');
window.__plotlineCapture={screen,fixtureOnly:true};
