<template><fieldset v-if="pkg?.domainConfig?.pricing?.mode==='provider-discount'"><legend>Choose your package provider</legend><p>{{ pkg.sessionCount }} sessions · {{ pkg.domainConfig.pricing.discountPercent }}% off the provider’s hourly fee</p><label>Service<select v-model="serviceId"><option value="">Select service</option><option v-for="s in services" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label>Provider<select v-model="providerId"><option value="">Select provider</option><option v-for="p in providers" :key="p.id" :value="p.id">{{p.name}}</option></select></label><p v-if="loading" role="status">Calculating…</p><p v-if="error" role="alert">{{error}}</p><p v-if="quote"><strong>{{money(quote.amountCents)}} total</strong> · {{money(quote.hourlyRateCents)}} per hour after discount</p><p v-else-if="!loading&&!providers.length">A provider and hourly fee must be configured for this service before this package can be purchased.</p></fieldset></template>
<script setup>
import {ref,watch} from 'vue';
import api from '../../services/api';
import {formatMoney as money} from '../../services/unifiedPackages';
const props=defineProps({agencyId:[Number,String],clientId:[Number,String],pkg:Object});const emit=defineEmits(['change']);
const services=ref([]),providers=ref([]),serviceId=ref(''),providerId=ref(''),quote=ref(null),loading=ref(false),error=ref('');let request=0;
async function load(){const token=++request;quote.value=null;emit('change',null);if(!props.agencyId||!props.pkg?.id||props.pkg.domainConfig?.pricing?.mode!=='provider-discount')return;loading.value=true;error.value='';try{const {data}=await api.get(`/tenant-booking/agencies/${props.agencyId}/packages/${props.pkg.id}/price-options`,{params:{clientId:props.clientId,tenantServiceId:serviceId.value||undefined,providerId:providerId.value||undefined}});if(token!==request)return;services.value=data.services;providers.value=data.providers;quote.value=data.quote;if(!serviceId.value&&services.value.length===1){serviceId.value=services.value[0].id;return;}if(data.quote)emit('change',{providerId:Number(providerId.value),tenantServiceId:Number(serviceId.value),quote:data.quote});}catch(e){if(token===request)error.value=e.response?.data?.error?.message||'Could not calculate this package.';}finally{if(token===request)loading.value=false;}}
watch(()=>[props.pkg?.id,props.agencyId,props.clientId],()=>{serviceId.value='';providerId.value='';services.value=[];providers.value=[];load();},{immediate:true});
watch(serviceId,()=>{providerId.value='';load();});watch(providerId,load);
</script>
<style scoped>fieldset{border:1px solid #cbdde3;border-radius:10px;padding:18px;margin:16px 0}label{display:grid;gap:6px;margin:12px 0}select{padding:10px;font:inherit}p{line-height:1.5}</style>
