<template>
  <div class="pl-pricing">
    <div class="pl-grid"><article v-for="offer in offers" :key="offer.title" class="pl-card" :class="{'pl-plan-connected':offer.title==='Connected'}"><p class="pl-eyebrow">{{ offer.title }}</p><h3><strong>{{ money(offer.price) }}</strong> <span>/ month</span></h3><p>{{ offer.description }}</p><p>{{ product.includedEmployees }} active employees included.<br>{{ money(product.additionalEmployeeCents) }} per additional employee / month.</p><router-link class="pl-button" :to="{path:startPath,query:{plan:offer.title.toLowerCase()}}">Explore {{ offer.title.toLowerCase() }} →</router-link><ul><li>Recruiting: branded careers page included</li><li>Applications, interviews &amp; hiring</li><li>Onboarding &amp; employee documents</li><li>Training &amp; learning progress</li><li>People records &amp; evaluations</li></ul></article></div>
    <div class="pl-price-estimator"><div><h3>Find your starting price.</h3><p>One organization. One people operations subscription.</p><label>Active employees<input v-model.number="employees" type="number" min="0" max="100000" step="1"></label><fieldset><legend>Other paid products at the same organization</legend><label v-for="item in products" :key="item.id"><input v-model="selected" type="checkbox" :value="item.id"> {{ item.name }}</label></fieldset></div><div class="pl-quote" aria-live="polite"><span>Estimated monthly Plotline subscription</span><strong>{{ quote ? money(quote.monthlyCents) : '—' }}</strong><span v-if="quote?.discountCents">Includes a {{ money(quote.discountCents) }} monthly bundle credit.</span><p v-if="!quote" role="alert">Enter a whole employee count from 0 to 100,000.</p><p>Applicants and archived employees do not count. Taxes, other product subscriptions, SMS, background checks, and usage-based AI or transcription are separate. Bundle eligibility is confirmed during setup.</p><router-link v-if="quote" class="pl-button" :to="{path:startPath,query:{plan:selected.length>1?'suite':selected.length?'connected':'standalone'}}">Request this plan →</router-link></div></div>
  </div>
</template>
<script setup>
import { computed, ref } from 'vue';
import { PLOTLINE_PRODUCT as product, estimatePlotlinePrice } from '../../config/plotlineProduct';
defineProps({startPath:{type:String,default:'/plottline/start'}});
const employees = ref(25), selected = ref([]);
const products = [{ id: 'auricwell', name: 'AuricWell' }, { id: 'schoolcarebridge', name: 'SchoolCareBridge' }, { id: 'conversa', name: 'Conversa' }];
const money = cents => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(cents / 100);
const offers = [
  { title: 'Standalone', price: product.monthlyBaseCents, description: 'Your branded careers page and recruiting workspace, with onboarding, training, and growth.' },
  { title: 'Connected', price: product.monthlyBaseCents - product.connectedCreditCents, description: 'Add Plotline alongside one other qualifying paid PlotTwistCo product. Save $50 each month.' },
  { title: 'Suite', price: product.monthlyBaseCents - product.suiteCreditCents, description: 'Combine Plotline with two or more qualifying paid products. Save $70 each month.' }
];
const quote = computed(() => { try { return estimatePlotlinePrice({ employees: employees.value, otherPaidProducts: selected.value }); } catch { return null; } });
</script>
<style scoped>
.pl-pricing h3 strong{font-size:42px}.pl-pricing h3>span{font:400 12px "Plotline Inter",sans-serif;letter-spacing:0}.pl-pricing .pl-card{padding:30px 26px;border-color:#e2ddd3;border-radius:18px;background:#fffdf9}.pl-pricing .pl-plan-connected{border:1px solid #be7d5e;background:#f8eee4}.pl-pricing .pl-card .pl-button{width:100%;margin:26px 0 12px}.pl-pricing ul{padding:0;list-style:none;font-size:12px;color:#556352}.pl-pricing li{margin:12px 0;padding-left:22px;position:relative}.pl-pricing li:before{content:"✓";position:absolute;left:0;color:#55745a}.pl-pricing .pl-card>p:nth-of-type(2){min-height:90px}.pl-pricing .pl-card p{font-size:14px}.pl-price-estimator{display:grid;grid-template-columns:1fr 1fr;gap:45px;margin-top:30px;padding:35px;border-radius:20px;background:#ede7df}.pl-price-estimator label{display:block;font-size:13px;margin:10px 0}.pl-price-estimator input[type=number]{display:block;width:150px;border:1px solid #b5c2b8;border-radius:9px;padding:10px;margin-top:8px;color:#0f2d24;background:white}.pl-price-estimator fieldset{padding:15px 0;border:0}.pl-price-estimator legend{font-size:12px;font-weight:600}.pl-quote{display:flex;flex-direction:column;align-items:flex-start;justify-content:center}.pl-quote>strong{font:500 52px 'Plotline Sora',system-ui,sans-serif;letter-spacing:-.05em;margin:8px 0}.pl-quote>span{font-size:12px}.pl-quote p{font-size:12px}@media(max-width:700px){.pl-price-estimator{grid-template-columns:1fr;padding:25px;gap:10px}}
</style>
