import {beforeEach,describe,it,expect,vi} from 'vitest';
const m=vi.hoisted(()=>({execute:vi.fn(),connection:vi.fn(),members:vi.fn(),user:vi.fn(),agency:vi.fn(),affiliations:vi.fn(),access:vi.fn(),invalidate:vi.fn()}));
vi.mock('../../config/database.js',()=>({default:{execute:m.execute,getConnection:m.connection}}));
vi.mock('../../models/User.model.js',()=>({default:{getAgencies:m.members,findById:m.user},invalidateUserAgenciesCache:m.invalidate}));
vi.mock('../../models/Agency.model.js',()=>({default:{findById:m.agency}}));
vi.mock('../../models/OrganizationAffiliation.model.js',()=>({default:{listActiveOrganizationsForAgency:m.affiliations}}));
vi.mock('../../controllers/schoolPortalIntakeLinks.controller.js',()=>({assertSchoolPortalAccess:m.access}));
vi.mock('../../middleware/auth.middleware.js',()=>({authenticate:(_q,_r,n)=>n(),requireSuperAdmin:(q,_r,n)=>q.user.role==='super_admin'?n():n(Error('Forbidden'))}));
import router from '../schoolCareBridgePartners.routes.js';
const partner={agency_id:2,name:'ITSCO',slug:'itsco',logo_url:'/assets/itsco/logo.png',workspace_mode:'connected',settings_json:{description:'School care'},private_note:'secret'};
async function request(path,req={}){const res={json:vi.fn(),status:vi.fn().mockReturnThis()},next=vi.fn();const route=router.stack.find(l=>l.route?.path===path&&l.route.methods[req.method||'get']).route;await route.stack.at(-1).handle({params:{slug:'itsco',agencyId:'2'},body:{},user:{id:20,role:'admin'},...req},res,next);return {res,next};}
beforeEach(()=>{vi.clearAllMocks();m.execute.mockResolvedValue([[partner]]);m.members.mockResolvedValue([{id:2}]);m.affiliations.mockResolvedValue([]);m.access.mockResolvedValue({});});
describe('SchoolCareBridge partners and tenant isolation',()=>{
 it('publishes only explicitly listed active agencies and public-safe fields',async()=>{const {res}=await request('/partners');expect(m.execute.mock.calls[0][0]).toContain('p.public_listed=TRUE');expect(res.json).toHaveBeenCalledWith({partners:[{id:2,name:'ITSCO',slug:'itsco',logoUrl:'/assets/itsco/logo.png',description:'School care'}]});});
 it('listing a logo never grants access to an agency workspace',async()=>{m.members.mockResolvedValue([{id:99}]);const {res,next}=await request('/tenants/:slug');expect(next.mock.calls[0][0].status).toBe(403);expect(res.json).not.toHaveBeenCalled();expect(m.affiliations).not.toHaveBeenCalled();});
 it('rechecks every school using the existing role and ROI access evaluator',async()=>{m.affiliations.mockResolvedValue([{id:12,name:'Ashley',slug:'ashley',organization_type:'school',is_active:1},{id:13,name:'Other',organization_type:'school',is_active:1}]);m.access.mockImplementation(async(_r,id)=>{if(id===13)throw Object.assign(Error('Denied'),{statusCode:403});});m.execute.mockResolvedValueOnce([[partner]]).mockResolvedValueOnce([[]]);const {res}=await request('/tenants/:slug');expect(res.json.mock.calls[0][0].schools.map(s=>s.id)).toEqual([12]);});
 it('fails closed for unexpected school permission errors',async()=>{m.affiliations.mockResolvedValue([{id:12,organization_type:'school',is_active:1}]);m.access.mockRejectedValue(Error('db failure'));const {next,res}=await request('/tenants/:slug');expect(next).toHaveBeenCalled();expect(res.json).not.toHaveBeenCalled();});
 it('disallows provider changes to admin-only concise settings',async()=>{const {next}=await request('/tenants/:slug/settings',{method:'put',user:{id:20,role:'provider'}});expect(next.mock.calls[0][0].status).toBe(403);});
 it('rejects feature and membership injection through settings',async()=>{const {next}=await request('/tenants/:slug/settings',{method:'put',body:{feature_flags:{payrollEnabled:true}}});expect(next.mock.calls[0][0].status).toBe(400);expect(m.execute).toHaveBeenCalledTimes(1);});
 it('does not expose other partners in the authenticated picker',async()=>{m.execute.mockResolvedValue([[partner,{...partner,agency_id:3}]]);const {res}=await request('/my-partners');expect(res.json.mock.calls[0][0].partners.map(p=>p.id)).toEqual([2]);});
 it('requires persisted signed PDFs for both parties to report execution',async()=>{for(const [a,o,expected] of [[0,0,false],[1,0,false],[1,1,true]]){m.execute.mockResolvedValue([[{id:4,agency_id:2,name:'ITSCO',rendered_html:'<p>Issued</p>',terms_json:{},agency_signed:a,operator_signed:o}]]);const {res}=await request('/admin/partners/:agencyId/agreement');expect(res.json.mock.calls[0][0].agreement.fullySigned).toBe(expected);expect(m.execute.mock.calls.at(-1)[0]).toContain('sd.signed_pdf_path IS NOT NULL');}});
 it('refuses to overwrite a changed or issued draft',async()=>{m.execute.mockResolvedValueOnce([[{agency_id:2}]]).mockResolvedValueOnce([{affectedRows:0}]);const {next}=await request('/admin/partners/:agencyId/agreement',{method:'put',body:{revision:1,terms:{trialStart:'2026-10-01',trialEnd:'2027-03-31'}}});expect(next.mock.calls[0][0].status).toBe(409);});
});
