import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import Panel from '../PhoneWorkflowSetup.vue';
import {defaultPhoneWorkflow} from '../../../../../backend/src/services/phoneWorkflow.service.js';
import {previewMainLineReceptionist} from '../../../../../backend/src/services/mainLineReceptionist.service.js';
vi.mock('../../../services/api',()=>({default:{get:vi.fn(),put:vi.fn(),post:vi.fn()}}));
import api from '../../../services/api';
const draft=()=>({config:defaultPhoneWorkflow('ITSCO'),revision:0,tracks:[],readiness:{issues:[],remaining:[]}});
let wrappers=[];
beforeEach(()=>{vi.clearAllMocks();api.get.mockResolvedValue({data:draft()});api.put.mockResolvedValue({data:{...draft(),revision:1}});api.post.mockResolvedValue({data:{simulation:true,callsPlaced:false,steps:[{type:'voicemail',text:'Test support greeting',destination:'Agency support inbox'}]}});});
afterEach(()=>{wrappers.forEach(w=>w.unmount());wrappers=[];});
async function open(){const w=mount(Panel,{props:{agencyId:2}});wrappers.push(w);w.element.open=true;await w.trigger('toggle');await flushPromises();return w;}
it('loads only when opened and keeps support enabled',async()=>{const w=mount(Panel,{props:{agencyId:2}});wrappers.push(w);expect(api.get).not.toHaveBeenCalled();w.element.open=true;await w.trigger('toggle');await flushPromises();expect(w.findAll('fieldset.option')).toHaveLength(10);expect(w.find('fieldset.option input[type=checkbox]').attributes('disabled')).toBeDefined();expect(w.text()).toContain('Preparation mode');});
it('previews without saving or dialing',async()=>{const w=await open();await w.findAll('button').find(b=>b.text()==='Preview without calling').trigger('click');await flushPromises();expect(api.post).toHaveBeenCalledWith('/sms-numbers/agency/2/phone-workflow/preview',expect.objectContaining({digit:'0',hours:'open'}));expect(api.put).not.toHaveBeenCalled();expect(w.text()).toContain('No calls were placed.');});
it('previews the recognized caller greeting and clears it when the scenario changes',async()=>{const w=await open();await w.get('[data-testid="receptionist-scenario"]').setValue('known_appointments');await w.get('[data-testid="receptionist-intent"]').setValue('cancel');api.post.mockResolvedValue({data:previewMainLineReceptionist(defaultPhoneWorkflow('ITSCO'),{scenario:'known_appointments',intent:'cancel'})});await w.findAll('button').find(b=>b.text()==='Preview receptionist').trigger('click');await flushPromises();expect(api.post).toHaveBeenCalledWith('/sms-numbers/agency/2/phone-workflow/preview',expect.objectContaining({mode:'receptionist',scenario:'known_appointments',intent:'cancel'}));expect(w.text()).toContain('Caller hears:');expect(w.text()).toContain('explicit confirmation');expect(api.put).not.toHaveBeenCalled();await w.get('[data-testid="receptionist-scenario"]').setValue('unknown');expect(w.text()).not.toContain('Caller hears:');});
it('saves the revision and makes unchanged live routing explicit',async()=>{const w=await open();await w.get('form').trigger('submit');await flushPromises();expect(api.put).toHaveBeenCalledWith('/sms-numbers/agency/2/phone-workflow',expect.objectContaining({revision:0}));expect(w.text()).toContain('Live carrier routing has not changed');});
it('retains the draft and explains concurrent save conflicts',async()=>{const w=await open();api.put.mockRejectedValue({response:{data:{error:{message:'Reload before saving.'}}}});await w.get('form').trigger('submit');await flushPromises();expect(w.get('[role=alert]').text()).toBe('Reload before saving.');expect(w.get('form').exists()).toBe(true);});
it('removes private destinations immediately when the tenant changes',async()=>{const d=draft();d.config.menu[0].targets=[{label:'Private desk',phone:'+17195550123'}];api.get.mockResolvedValue({data:d});const w=await open();expect(w.findAll('input').map(i=>i.element.value)).toContain('Private desk');api.get.mockReturnValue(new Promise(()=>{}));await w.setProps({agencyId:3});expect(w.findAll('input').map(i=>i.element.value)).not.toContain('Private desk');});

it('shows current public and care numbers separately without activating voice',async()=>{const d=draft();d.lineRoles={publicLines:[{id:8,phoneNumber:'+17195550111'}],careLine:{id:9,phoneNumber:'+17195550222'}};api.get.mockResolvedValue({data:d});const w=await open();expect(w.text()).toContain('Saved public texting number: +17195550111');expect(w.text()).toContain('Selected shared care texting number: +17195550222');expect(w.text()).toContain('audio plus a transcript');expect(w.text()).toContain('transcription are not active yet');api.get.mockReturnValue(new Promise(()=>{}));await w.setProps({agencyId:3});expect(w.text()).not.toContain('+17195550222');});
