import {mount} from '@vue/test-utils';
import {beforeEach,expect,it,vi} from 'vitest';
import ReadAloudControls from '../ReadAloudControls.vue';
let synth;
beforeEach(()=>{synth={getVoices:vi.fn(()=>[{localService:false,lang:'en-US',name:'Cloud'}]),speak:vi.fn(),cancel:vi.fn(),pause:vi.fn(),resume:vi.fn(),addEventListener:vi.fn(),removeEventListener:vi.fn()};Object.defineProperty(window,'speechSynthesis',{configurable:true,value:synth});vi.stubGlobal('SpeechSynthesisUtterance',class{constructor(text){this.text=text;}});});
it('never falls back to a remote voice or reads automatically',()=>{const w=mount(ReadAloudControls,{props:{html:'<p>Private draft</p>'}});expect(w.find('button').attributes('disabled')).toBeDefined();expect(synth.speak).not.toHaveBeenCalled();w.unmount();});
it('reads content without executable/style text and stops on navigation',async()=>{synth.getVoices.mockReturnValue([{localService:true,lang:'en-US'}]);const w=mount(ReadAloudControls,{props:{html:'<style>secretCSS</style><script>bad()</script><h1>October update</h1><p>Review your schedule.</p>'}});await w.vm.$nextTick();await w.find('button').trigger('click');expect(synth.speak).toHaveBeenCalledTimes(1);const u=synth.speak.mock.calls[0][0];expect(u.text).toContain('October update');expect(u.text).not.toMatch(/secretCSS|bad/);await w.setProps({html:'<p>A different update</p>'});expect(synth.cancel).toHaveBeenCalled();const n=synth.speak.mock.calls.length;u.onend();expect(synth.speak).toHaveBeenCalledTimes(n);w.unmount();});
it('pauses and resumes only on request',async()=>{synth.getVoices.mockReturnValue([{localService:true,lang:'en-US'}]);const w=mount(ReadAloudControls,{props:{html:'<p>Read me.</p>'}});await w.vm.$nextTick();await w.find('button').trigger('click');await w.vm.$nextTick();await w.find('button').trigger('click');expect(synth.pause).toHaveBeenCalledOnce();await w.vm.$nextTick();await w.find('button').trigger('click');expect(synth.resume).toHaveBeenCalledOnce();w.unmount();expect(synth.removeEventListener).toHaveBeenCalled();});
it('changes playback speed immediately and ignores cancelled callbacks',async()=>{
 synth.getVoices.mockReturnValue([{localService:true,lang:'en-US'}]);const w=mount(ReadAloudControls,{props:{html:'<p>First sentence. Second sentence.</p>'}});await w.vm.$nextTick();await w.find('button').trigger('click');
 const first=synth.speak.mock.calls[0][0];first.onboundary({charIndex:16});await w.find('select').setValue('1.5');
 expect(synth.speak).toHaveBeenCalledTimes(2);const next=synth.speak.mock.calls[1][0];expect(next.rate).toBe(1.5);expect(next.text).toContain('Second sentence');first.onend();expect(synth.speak).toHaveBeenCalledTimes(2);w.unmount();
});
