import {describe,it,expect,vi,beforeEach} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import {STAFF_COMMUNICATION_REQUESTS} from '../../../../../backend/src/utils/staffCommunicationChoices.js';
import StaffCommunicationChoices from '../StaffCommunicationChoices.vue';
vi.mock('../../../services/api',()=>({default:{get:vi.fn(),put:vi.fn()}}));
const initial={agencyId:2,phone:'+13035550101',disclosureHash:'hash',reviewedAt:null,needsReview:true,activation:[],choices:{notifications:false,messageAlerts:false,polling:false},disclosure:{accessRequests:STAFF_COMMUNICATION_REQUESTS,policyReady:true,brandName:'ITSCO',legalName:'ITSCO, LLC',text:'Optional texts. All choices may be No.',termsUrl:'https://itsco.health/terms',privacyUrl:'https://itsco.health/privacy',programs:[],future:'Forwarding and calling are not available.',choices:[{key:'notifications',label:'Reminders',description:'Meetings and staff updates'},{key:'messageAlerts',label:'Message alerts',description:'Generic alerts'},{key:'polling',label:'Voting',description:'Optional polls'}]}};
describe('staff phone choices',()=>{
 it('defaults every category to No and requires a signature',()=>{const w=mount(StaffCommunicationChoices,{props:{initial,externalSave:true}});expect(w.findAll('input[type=radio]').filter(x=>x.element.checked).map(x=>x.element.value)).toEqual(['false','false','false','false','false']);expect(w.get('button').element.disabled).toBe(true);expect(w.text()).toContain('still read and send');expect(w.text()).toContain('not available');});
 it('allows all No to complete review without enabling any category',async()=>{const w=mount(StaffCommunicationChoices,{props:{initial,externalSave:true}});await w.get('input[autocomplete=name]').setValue('Example Provider');await w.get('input[type=checkbox]').setValue(true);await w.get('form').trigger('submit.prevent');expect(w.emitted('save')[0][0]).toMatchObject({choices:{notifications:false,messageAlerts:false,polling:false},signerName:'Example Provider',acknowledged:true});});
 it('lets a provider choose alerts separately from reminders and voting',async()=>{const w=mount(StaffCommunicationChoices,{props:{initial,externalSave:true}});await w.findAll('input[type=radio]')[7].setValue();await w.get('input[autocomplete=name]').setValue('Example Provider');await w.get('input[type=checkbox]').setValue(true);await w.get('form').trigger('submit.prevent');expect(w.emitted('save')[0][0].choices).toEqual({notifications:false,messageAlerts:true,polling:false});});
 it('makes a pending enrollment visible without claiming delivery is active',()=>{const w=mount(StaffCommunicationChoices,{props:{initial:{...initial,reviewedAt:'2026-10-06T20:00:00Z',activation:[{status:'pending_campaign'}]}}});expect(w.text()).toContain('not active yet');expect(w.text()).not.toContain('categories are enrolled');});
});

it('records forwarding interest separately from SMS consent and disables preview submission',async()=>{const w=mount(StaffCommunicationChoices,{props:{initial,externalSave:true}});await w.findAll('[data-testid=access-request] input[type=radio]')[3].setValue();await w.get('input[autocomplete=name]').setValue('Example Provider');await w.get('input[type=checkbox]').setValue(true);await w.get('form').trigger('submit.prevent');expect(w.emitted('save')[0][0]).toMatchObject({accessRequests:{inAppTexting:false,personalSmsRelay:true},choices:{notifications:false,messageAlerts:false,polling:false}});await w.setProps({readonly:true});await w.get('form').trigger('submit.prevent');expect(w.emitted('save')).toHaveLength(1);});
