<template><main class="billing-desk"><header><div><p class="eyebrow">Family billing</p><h1>Balances, payment setup & collections</h1><p>Review responsibility, record payments, and help families complete their billing setup.</p></div><button :disabled="busy" @click="refresh">Refresh</button></header>
  <p v-if="error" role="alert" class="error">{{ error }}</p><p v-if="message" role="status">{{ message }}</p><p v-if="loading" role="status">Loading the billing desk…</p>
  <nav aria-label="Billing tools"><button v-for="t in tabs" :key="t.key" :aria-pressed="tab===t.key" @click="tab=t.key">{{ t.label }}</button></nav>
  <section v-if="tab==='balances'"><div class="toolbar"><h2>Family balances</h2><button :disabled="busy" @click="post('/sync',{})">Sync session charges & retry fulfillment</button></div><p>Imported session charges keep their original reference. Covered or already-paid charges are excluded.</p>
    <div class="table-wrap"><table><thead><tr><th>Client / source</th><th>Responsible payer</th><th>Unpaid share</th><th>Due</th><th>Status</th><th>Action</th></tr></thead><tbody><tr v-for="r in data.balances" :key="r.allocationId"><td>{{ clientName(r.clientId) }}<small>{{ r.sourceType }} #{{ r.sourceKey }}</small></td><td>{{ r.payerName || 'Unassigned' }}</td><td>{{ money(r.balanceCents) }}</td><td>{{ date(r.dueDate) }}</td><td>{{ r.status }}<small>{{ r.holdReason }}</small><small v-if="r.fulfillmentStatus">Activation: {{ r.fulfillmentStatus }}</small><small v-if="r.fulfillmentError">{{ r.fulfillmentError }}</small></td><td><button @click="select(r)">Manage</button></td></tr></tbody></table></div><p v-if="!data.balances?.length">No family balances yet.</p>
    <section v-if="selected" class="card"><h3>Manage balance {{ selected.receivableId }} · {{ clientName(selected.clientId) }}</h3><p>{{ selected.payerName }} · {{ money(selected.balanceCents) }} remaining</p><label>Reason / payment reference<input v-model="reason" maxlength="2000" /></label><div class="actions"><button :disabled="busy || !reason" @click="review(true,false)">Release after review</button><button :disabled="busy || !reason" @click="review(false,true)">Mark disputed</button><button :disabled="busy || !reason" @click="review(false,false)">Resolve dispute</button></div><label class="check"><input type="checkbox" v-model="insuranceReviewed" /> Insurance patient responsibility has been verified</label>
      <form @submit.prevent="cash"><h4>Record cash received</h4><label>Amount ($)<input v-model="cashAmount" type="number" step="0.01" min="0.01" :max="selected.balanceCents/100" required /></label><label>Date received<input v-model="cashDate" type="date" required /></label><button :disabled="busy || !reason || !selected.payerUserId">Record cash and issue receipt</button></form>
      <details><summary>Assign / split the remaining balance</summary><div v-for="payer in activePayers(selected.clientId)" :key="payer.guardianUserId" class="share"><label>{{ payerName(payer) }} (%)<input type="number" min="0" max="100" step="0.01" v-model="percentages[payer.guardianUserId]" /></label></div><p>Shares must total 100%. Document the authority for this change above.</p><button :disabled="busy || !reason" @click="assignShares">Apply shares</button><label>Future charges<select v-model="ruleKind"><option value="split">Use these percentages</option><option value="alternate">Alternate the selected payers</option><option value="single">One payer</option></select></label><button :disabled="busy || !reason" @click="saveRule">Save future billing rule</button></details>
      <details><summary>Adjust or cancel this balance</summary><p>Refunds must be recorded before reducing the total below net payments. Use the payer percentages above if an unpaid balance will remain.</p><label>Revised total ($)<input v-model="adjustmentAmount" type="number" min="0" step="0.01" /></label><button :disabled="busy || !reason" @click="post(`/balances/${selected.receivableId}/adjust`,{amountCents:Math.round(Number(adjustmentAmount)*100),shares:shares(),reason})">Save audited adjustment</button></details>
      <details><summary>Statement visibility</summary><p>Shared statements show both assigned shares. Card details and clinical records stay private.</p><label>Responsible payer<select v-model="sharingPayer"><option :value="null">Select a payer</option><option v-for="p in activePayers(selected.clientId)" :value="p.guardianUserId" :key="p.guardianUserId">{{ payerName(p) }}</option></select></label><button :disabled="busy || !sharingPayer || !reason" @click="share(true)">Allow shared statements</button><button :disabled="busy || !sharingPayer || !reason" @click="share(false)">Restore private statements</button></details>
      <details><summary>Propose a payment plan</summary><p>The payer must sign before this schedule becomes active.</p><label>Installments<input v-model.number="installmentCount" type="number" min="2" max="24" /></label><label>First due date<input v-model="planDate" type="date" /></label><button :disabled="busy || !planDate || !selected.payerUserId" @click="proposePlan">Propose equal monthly installments</button><button v-if="selected.plan" :disabled="busy" @click="post(`/plans/${selected.plan.id}/cancel`,{})">Cancel existing plan</button></details>
    </section>
  </section>
  <section v-if="tab==='charges'" class="card"><h2>Create a source-linked balance</h2><label>Client<select v-model="newClient"><option :value="null">Select a client</option><option v-for="c in clients" :key="c.id" :value="c.id">{{ c.name }}</option></select></label><label>Source<select v-model="chargeKind"><option value="claim">Insurance claim responsibility</option><option value="package">Package / class</option><option value="event">Event / program registration</option><option value="service">Tutoring, coaching or consulting charge</option></select></label>
    <template v-if="chargeKind==='package'"><label>Package<select v-model="packageId"><option :value="null">Select a package</option><option v-for="p in data.packages" :value="p.id" :key="p.id">{{ p.name }} · {{ money(p.priceCents) }}</option></select></label><label>Purchasing payer<select v-model="newPayer"><option :value="null">Select a responsible payer</option><option v-for="p in activePayers(newClient)" :value="p.guardianUserId" :key="p.guardianUserId">{{ payerName(p) }}</option></select></label><p>Session credits become available after the full balance is paid. Cash and card payments both count.</p></template>
    <template v-else><label>{{ chargeKind==='claim'?'Claim ID':chargeKind==='event'?'Event ID':'Invoice reference' }}<input v-model="sourceId" required /></label><label>Amount ($)<input v-model="newAmount" type="number" min="0" step="0.01" /></label><label v-if="chargeKind==='claim'">Responsibility<select v-model="responsibility"><option value="copay">Copay</option><option value="deductible">Deductible</option><option value="coinsurance">Coinsurance</option><option value="patient_balance">Verified patient balance</option></select></label><label v-else>Service category<select v-model="domain"><option value="tutoring">Tutoring</option><option value="coaching">Coaching</option><option value="consulting">Consulting</option><option value="mental_health">Mental health</option><option value="unknown">Requires classification</option></select></label><label>Verification / published price evidence<textarea v-model="chargeReason" rows="3" /></label></template><button :disabled="busy || !newClient" @click="createCharge">Create balance</button>
  </section>
  <section v-if="tab==='setup'"><section class="card"><h2>Invite an existing family to complete payment setup</h2><label>Guardian account<select v-model="taskGuardian"><option :value="null">Select a guardian</option><option v-for="g in guardians" :value="g.id" :key="g.id">{{ g.name }}</option></select></label><fieldset><legend>Clients included</legend><label class="check" v-for="link in data.links?.filter(l => Number(l.guardianUserId)===Number(taskGuardian))" :key="link.clientId"><input type="checkbox" v-model="taskClients" :value="link.clientId" />{{ clientName(link.clientId) }}</label></fieldset><label class="check"><input type="checkbox" v-model="taskRequireCard" /> Require a verified card (not for Medicaid-covered care)</label><label>Additional organization terms<textarea v-model="waiver" rows="5" placeholder="Use your approved migration or billing terms." /></label><p>The standard authorization is included. This creates a portal task and an email draft for review.</p><button :disabled="busy || !taskGuardian || !taskClients.length" @click="createTask">Create payment task & invitation draft</button></section>
    <article v-for="t in data.tasks" :key="t.id" class="card row"><div><strong>{{ t.title }}</strong><p>{{ guardianName(t.guardianUserId) }} · {{ t.status }} · Due {{ date(t.expiresAt) }}</p></div><button v-if="t.status==='pending'" :disabled="busy" @click="post(`/tasks/${t.id}/cancel`,{})">Cancel task</button></article>
  </section>
  <section v-if="tab==='collections'"><h2>Past-due assigned balances</h2><p>Disputed, held and Medicaid-protected balances are excluded. Active plans use overdue installments.</p><article class="card row" v-for="payer in agingPayers" :key="payer.id"><div><strong>{{ payer.name }}</strong><p>{{ money(payer.total) }} overdue · Oldest {{ payer.days }} days</p></div><button :disabled="busy" @click="post('/notices',{payerUserId:payer.id,kind:'past_due',idempotencyKey:cryptoKey()})">Generate statement draft</button></article><p v-if="!agingPayers.length">No eligible overdue balances.</p><h2>Letters and invitation drafts</h2><article v-for="n in data.notices" :key="n.id" class="card row"><div><strong>{{ guardianName(n.payerUserId) }} · {{ n.kind.replaceAll('_',' ') }}</strong><p>{{ n.status }} · {{ date(n.createdAt) }}</p><p v-if="n.lastError">{{ n.lastError }}</p></div><div class="actions"><button :disabled="busy" @click="download(`/notices/${n.id}.pdf`,`statement-${n.id}.pdf`)">Download / print letter</button><button v-if="['draft','held'].includes(n.status)" :disabled="busy" @click="sendCandidate=n">Review email</button></div></article>
    <section v-if="sendCandidate" class="card"><h3>Send branded notification</h3><p>Recipient: {{ guardianName(sendCandidate.payerUserId) }}</p><p>From: {{ sendCandidate.kind==='payment_setup'?'billing':'collections' }} at this organization’s configured domain.</p><p>{{ sendCandidate.kind==='payment_setup'?'The email asks them to verify a payment method and sign their billing authorization.':'The email says their account statement is ready and asks them to sign in to review it.' }} The button opens their secure portal after login. No balance or clinical details appear in the email.</p><button :disabled="busy" @click="sendNotice">Send this notification</button><button @click="sendCandidate=null">Cancel</button></section>
  </section>
  <section v-if="tab==='receipts'"><h2>Recorded payments</h2><article v-for="r in data.receipts" :key="r.paymentId" class="card"><div class="row"><div><strong>{{ r.receiptNumber }} · {{ money(r.amountCents) }}</strong><p>{{ r.payerName }} · {{ r.method }} · {{ date(r.receivedAt) }}</p><p v-if="r.refundedCents">Refunded {{ money(r.refundedCents) }}</p></div><button @click="download(`/receipts/${r.paymentId}.pdf`,`${r.receiptNumber}.pdf`)">Download receipt</button></div><details><summary>Record / issue refund</summary><label>Amount ($)<input v-model="refundAmounts[r.paymentId]" type="number" min="0.01" :max="r.netPaidCents/100" step="0.01" /></label><label>Reason<input v-model="refundReasons[r.paymentId]" /></label><p>For cash, use this after returning the money. Card refunds are submitted to Stripe. The balance is held for review afterward.</p><button :disabled="busy || !refundReasons[r.paymentId]" @click="refund(r)">Submit refund</button></details></article></section>
  <section v-if="tab==='settings'" class="card"><h2>Tenant billing & collections mailboxes</h2><p>Uses the organization’s configured Workspace domain. Only authorized billing staff may be group members. Review Workspace permissions before provisioning.</p><label class="check"><input type="checkbox" v-model="adoptExisting" /> Adopt existing groups only after verifying all members are authorized billing staff.</label><button :disabled="busy" @click="post('/senders/seed',{})">Initialize sender records</button><button :disabled="busy" @click="post('/senders/provision',{adoptExisting})">Create / verify Workspace groups</button><article v-for="s in data.senders" :key="s.identity_key"><h3>{{ s.email_address }}</h3><p>{{ s.state }} · {{ s.last_error }}</p></article><h2>Scheduled installments</h2><p>Collect only due installments with a current signed automatic-payment authorization.</p><button :disabled="busy" @click="post('/plans/collect-due',{})">Process authorized due installments</button></section>
<section v-if="tab==='clinical'" class="card"><h2>Review guardian clinical access</h2><p>An authorized clinical administrator must verify the legal authority or client consent. Children under 12 may receive full access after rights are verified; age 12 and adulthood trigger review. Billing access alone never grants clinical permissions.</p><label>Client<select v-model="clinicalClient"><option :value="null">Select client</option><option v-for="c in clients" :value="c.id" :key="c.id">{{ c.name }}</option></select></label><label>Guardian<select v-model="clinicalGuardian"><option :value="null">Select guardian</option><option v-for="l in data.links?.filter(l=>Number(l.clientId)===Number(clinicalClient))" :value="l.guardianUserId" :key="l.guardianUserId">{{ payerName(l) }}</option></select></label><label>Access level<select v-model="clinicalLevel"><option value="payer_only">Payer only / no clinical records</option><option value="limited">Limited (no treatment goals or session frequency)</option><option value="full">Full verified clinical access</option></select></label><label>Consent basis<select v-model="clinicalBasis"><option value="payer_only">Payment relationship only</option><option value="legal_representative">Verified legal representative</option><option value="minor_independent_consent">Reviewed minor independent-consent context</option><option value="client_authorization">Client authorization</option></select></label><label class="check"><input v-model="clinicalVerified" type="checkbox" /> I verified the medical rights or client authorization and recorded the supporting evidence below.</label><fieldset v-if="clinicalLevel==='limited'"><legend>Allowed disclosures</legend><label class="check" v-for="scope in ['safety_plan','clinical_documents','clinical_messages']" :key="scope"><input type="checkbox" v-model="clinicalScopes" :value="scope" />{{ scope.replaceAll('_',' ') }}</label></fieldset><label>Next review date<input type="date" v-model="clinicalReview" /></label><label>Documented authority / consent evidence<textarea v-model="clinicalReason" rows="4" /></label><button :disabled="busy || !clinicalClient || !clinicalGuardian || !clinicalReason" @click="saveClinical">Save reviewed disclosure grant</button></section>
</main></template>
<script setup>
import {ref,computed,onMounted,watch} from 'vue';import {useRoute} from 'vue-router';import api from '../../services/api';import {useAgencyStore} from '../../store/agency';
const route=useRoute(),agencyStore=useAgencyStore();const agencyId=computed(()=>Number(route.query.agencyId||agencyStore.currentAgency?.id||agencyStore.selectedAgencyId));
const data=ref({}),tab=ref('balances'),tabs=[{key:'balances',label:'Balances'},{key:'charges',label:'New charge'},{key:'setup',label:'Payment setup'},{key:'collections',label:'Collections'},{key:'receipts',label:'Receipts'},{key:'settings',label:'Sending & plans'},{key:'clinical',label:'Clinical access'}];
const loading=ref(false),busy=ref(false),error=ref(''),message=ref(''),selected=ref(null),reason=ref(''),cashAmount=ref(''),cashDate=ref(new Date().toISOString().slice(0,10)),insuranceReviewed=ref(false),percentages=ref({}),ruleKind=ref('split'),sharingPayer=ref(null),installmentCount=ref(3),planDate=ref(''),newClient=ref(null),chargeKind=ref('claim'),packageId=ref(null),newPayer=ref(null),sourceId=ref(''),newAmount=ref(''),domain=ref('unknown'),responsibility=ref('copay'),chargeReason=ref(''),taskGuardian=ref(null),taskClients=ref([]),taskRequireCard=ref(true),waiver=ref(''),sendCandidate=ref(null),refundAmounts=ref({}),refundReasons=ref({});const adjustmentAmount=ref('');const adoptExisting=ref(false);const clinicalClient=ref(null),clinicalGuardian=ref(null),clinicalLevel=ref('payer_only'),clinicalBasis=ref('payer_only'),clinicalVerified=ref(false),clinicalReview=ref(''),clinicalReason=ref(''),clinicalScopes=ref([]);let cashKey='',refundKeys={};
const cryptoKey=()=>crypto.randomUUID(),money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(Number(n)/100),date=v=>v?new Date(/^\d{4}-\d{2}-\d{2}$/.test(v)?`${v}T12:00:00`:v).toLocaleDateString():'';
const payerName=p=>[p.first_name,p.last_name].filter(Boolean).join(' '),clients=computed(()=>[...new Map((data.value.links||[]).map(l=>[l.clientId,{id:l.clientId,name:l.clientName||`Client ${l.clientId}`}])).values()]),guardians=computed(()=>[...new Map((data.value.links||[]).map(l=>[l.guardianUserId,{id:l.guardianUserId,name:payerName(l)}])).values()]);
const clientName=id=>clients.value.find(c=>Number(c.id)===Number(id))?.name||`Client ${id}`,guardianName=id=>guardians.value.find(g=>Number(g.id)===Number(id))?.name||`Account ${id}`,activePayers=id=>(data.value.links||[]).filter(l=>Number(l.clientId)===Number(id)&&l.payerStatus==='active');
const agingPayers=computed(()=>{const map=new Map();for(const r of data.value.overdue||[]){const p=map.get(r.payerUserId)||{id:r.payerUserId,name:r.payerName,total:0,days:0};p.total+=r.pastDueCents;p.days=Math.max(p.days,r.daysPastDue);map.set(r.payerUserId,p);}return [...map.values()];});
async function refresh(){if(!agencyId.value){error.value='Select an organization to open billing.';return;}loading.value=true;try{data.value=(await api.get('/family-billing/staff/desk',{params:{agencyId:agencyId.value}})).data;if(selected.value)selected.value=data.value.balances.find(r=>r.allocationId===selected.value.allocationId)||null;}catch(e){error.value=e.response?.data?.error?.message||'Billing could not be loaded.';}finally{loading.value=false;}}
async function post(path,payload){if(busy.value)return;busy.value=true;error.value='';message.value='';try{const result=(await api.post(`/family-billing/staff${path}`,{...payload,agencyId:agencyId.value})).data;message.value=(result.refunded===false||result.results?.some(r=>r.ready===false||r.paid===false))?'Some items need review. Check the status and messages.':result.skipped?'Sending is held by email settings.':'Saved.';await refresh();return result;}catch(e){error.value=e.response?.data?.error?.message||'The change could not be completed.';return null;}finally{busy.value=false;}}
function select(row){selected.value=row;reason.value='';cashAmount.value=(row.balanceCents/100).toFixed(2);cashKey=cryptoKey();percentages.value={};insuranceReviewed.value=false;}
const review=(release,disputed)=>post(`/balances/${selected.value.receivableId}/review`,{release,disputed,insuranceReviewed:insuranceReviewed.value,reason:reason.value});
const cash=()=>post(`/allocations/${selected.value.allocationId}/cash`,{payerUserId:selected.value.payerUserId,amountCents:Math.round(Number(cashAmount.value)*100),receivedAt:`${cashDate.value}T12:00:00`,idempotencyKey:cashKey,note:reason.value});
const shares=()=>Object.entries(percentages.value).filter(([,v])=>Number(v)>0).map(([id,v])=>({payerUserId:Number(id),basisPoints:Math.round(Number(v)*100)}));
const assignShares=()=>post(`/balances/${selected.value.receivableId}/shares`,{shares:shares(),reason:reason.value});const saveRule=()=>post(`/clients/${selected.value.clientId}/rule`,{kind:ruleKind.value,shares:shares(),reason:reason.value});const share=active=>post(`/clients/${selected.value.clientId}/sharing`,{guardianUserId:sharingPayer.value,active,reason:reason.value});
function proposePlan(){const count=Number(installmentCount.value);if(!Number.isInteger(count)||count<2||count>24)return;const total=Number(selected.value.balanceCents),base=Math.floor(total/count),start=new Date(`${planDate.value}T12:00:00Z`),day=start.getUTCDate();const installments=Array.from({length:count},(_,i)=>{const d=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+i,1,12));const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return {amountCents:base+(i<total%count?1:0),dueDate:d.toISOString().slice(0,10)};});return post(`/allocations/${selected.value.allocationId}/plan`,{installments});}
async function createCharge(){let path,payload={clientId:newClient.value,amountCents:Math.round(Number(newAmount.value)*100),reason:chargeReason.value};if(chargeKind.value==='claim'){path=`/claims/${sourceId.value}/responsibility`;payload.responsibilityType=responsibility.value;}else if(chargeKind.value==='package'){path='/packages';payload={clientId:newClient.value,packageId:packageId.value,payerUserId:newPayer.value,idempotencyKey:cryptoKey()};}else if(chargeKind.value==='event'){path='/events';Object.assign(payload,{eventId:Number(sourceId.value),serviceDomain:domain.value});}else{path='/balances';Object.assign(payload,{sourceKey:sourceId.value,serviceDomain:domain.value,payload:{reason:chargeReason.value}});}if(await post(path,payload))tab.value='balances';}
const createTask=async()=>{if(await post('/tasks',{guardianUserId:taskGuardian.value,clientIds:taskClients.value,requireCard:taskRequireCard.value,waiverText:waiver.value}))tab.value='collections';};const sendNotice=async()=>{await post(`/notices/${sendCandidate.value.id}/send`,{});sendCandidate.value=null;};
async function download(path,filename){try{const result=await api.get(`/family-billing/staff${path}`,{params:{agencyId:agencyId.value},responseType:'blob'}),url=URL.createObjectURL(result.data),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch{error.value='The document could not be downloaded.';}}
const refund=r=>post(`/payments/${r.paymentId}/refund`,{amountCents:Math.round(Number(refundAmounts.value[r.paymentId])*100),reason:refundReasons.value[r.paymentId],idempotencyKey:refundKeys[r.paymentId]||(refundKeys[r.paymentId]=cryptoKey())});
async function saveClinical(){busy.value=true;error.value='';try{await api.post(`/family-billing/clinical-access/${clinicalClient.value}/${clinicalGuardian.value}`,{agencyId:agencyId.value,accessLevel:clinicalLevel.value,medicalRightsVerified:clinicalVerified.value,consentBasis:clinicalBasis.value,scopes:clinicalScopes.value,reviewDueDate:clinicalReview.value||null,reason:clinicalReason.value});message.value='Clinical access review saved.';}catch(e){error.value=e.response?.data?.error?.message||'Clinical access could not be updated.';}finally{busy.value=false;}}
watch(taskGuardian,()=>{taskClients.value=[];});watch(agencyId,()=>{data.value={};selected.value=null;void refresh();});onMounted(refresh);
</script>
<style scoped>
.billing-desk{max-width:1380px;margin:auto;padding:32px;color:#1b2c43}.billing-desk header,.toolbar,.row{display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap}.eyebrow{color:#416b91;text-transform:uppercase;font-size:12px;letter-spacing:.12em}.billing-desk h1{font-size:30px;margin:8px 0}.billing-desk p{line-height:1.6}.billing-desk nav,.actions{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}.billing-desk button{border:1px solid #bccbdd;border-radius:7px;background:#f4f7fc;color:#17466e;padding:11px 15px;font:inherit;cursor:pointer}.billing-desk button[aria-pressed=true]{background:#16466d;color:white}.billing-desk button:disabled{opacity:.5;cursor:default}.card{background:white;border:1px solid #d9e2ef;border-radius:12px;padding:26px;margin:20px 0}.billing-desk label{display:grid;gap:8px;margin:16px 0;max-width:680px}.billing-desk .check{display:flex;align-items:flex-start}.billing-desk input:not([type=checkbox]),select,textarea{box-sizing:border-box;max-width:100%;min-width:0;padding:11px;border:1px solid #a9bace;border-radius:6px;font:inherit}.billing-desk details{margin:24px 0;border-top:1px solid #e0e7ef;padding-top:20px}.billing-desk summary{cursor:pointer;font-weight:600}.table-wrap{overflow:auto;border:1px solid #d9e2ef;border-radius:10px}.billing-desk table{width:100%;border-collapse:collapse;background:white;text-align:left}.billing-desk th,.billing-desk td{padding:14px;border-bottom:1px solid #e3e9f1;white-space:nowrap}.billing-desk th{background:#edf3fa}.billing-desk small{display:block;color:#5f738c;margin-top:5px}.error{color:#b42318}@media(max-width:680px){.billing-desk{padding:18px 12px}.card{padding:18px}.billing-desk h1{font-size:24px}}
</style>
