<template>
  <main class="scb-program scb-workspace-main">
    <header class="scb-workspace-title"><div><p class="scb-eyebrow">MH4Kidz · Program administration</p><h1>SchoolCareBridge partners</h1><router-link to="/schoolcarebridge/app/operations">Programs, contracts & billing →</router-link><p>Simple agency workspaces, public partner listings and reviewed agreements.</p></div><router-link class="scb-button scb-outline" to="/schoolcarebridge/partners">View public partners →</router-link></header>
    <p v-if="error" role="alert" class="scb-workspace-notice">{{error}}</p><p v-if="notice" role="status" class="scb-workspace-notice">{{notice}}</p>
    <section class="scb-workspace-panel"><div class="scb-workspace-title"><h2>Partner agencies</h2><button class="scb-button" @click="showCreate=!showCreate">{{showCreate?'Close setup':'Add a partner'}}</button></div>
      <div v-if="showCreate" class="scb-program-setup"><form class="scb-form" @submit.prevent="createTenant"><h3>Create a SchoolCareBridge tenant</h3><p>Includes school portals, client rosters, providers and concise settings. Other platform modules stay outside this workspace.</p><label>Agency name<input v-model="tenantForm.name" required maxlength="255"/></label><label>Portal address<input v-model="tenantForm.slug" required pattern="[a-z0-9][a-z0-9-]+" placeholder="your-agency"/></label><label>Agency logo URL<input v-model="tenantForm.logoUrl" placeholder="https://… or /uploads/…"/></label><label>Account administrator<select v-model="tenantForm.adminUserId" required><option value="">Select an existing administrator</option><option v-for="user in administrators" :key="user.id" :value="user.id">{{user.first_name}} {{user.last_name}} · {{user.email}}</option></select></label><small>Create or invite an administrator through existing account management first. This does not send an invitation.</small><button class="scb-button" :disabled="busy">Create scoped tenant</button></form>
      <form class="scb-form" @submit.prevent="connectAgency"><h3>Connect an existing agency</h3><p>Preserves its current features and workspace, as with ITSCO.</p><label>Existing agency<select v-model="existingAgencyId" required><option value="">Choose agency</option><option v-for="agency in agencies" :key="agency.id" :value="agency.id">{{agency.name}}</option></select></label><button class="scb-button scb-outline" :disabled="busy">Connect agency</button></form></div>
      <p v-if="loading" role="status">Loading partners…</p><div v-for="partner in partners" :key="partner.id" class="scb-program-row"><div><strong>{{partner.name}}</strong><small>{{partner.workspaceMode==='standalone'?'SchoolCareBridge-only tenant':'Connected agency · existing workspace retained'}}</small></div><label><input type="checkbox" :checked="partner.publicListed" :disabled="busy" @change="setListing(partner,$event.target.checked)"/> List on Partners</label><router-link :to="schoolCareBridgePartnerPath(partner.slug)">Open workspace</router-link><button class="scb-button scb-outline" @click="selectPartner(partner)">Agreement</button></div><p v-if="!partners.length&&!loading">No partners configured. Apply the SchoolCareBridge partner migration to initialize ITSCO.</p>
    </section>
    <section v-if="selected" class="scb-workspace-panel"><p class="scb-eyebrow">{{selected.name}} × MH4Kidz</p><h2>SchoolCareBridge Partner Agreement</h2><p v-if="agreement" class="scb-agreement-state">{{agreement.fullySigned?'Signed by both parties':agreement.status==='issued'?'Issued — awaiting signatures':'Draft'}} · Revision {{agreement.revision}}</p>
      <form v-if="!agreement||agreement.status==='draft'" class="scb-form" @submit.prevent="saveDraft"><div class="scb-program-dates"><label>Complimentary service starts<input type="date" v-model="terms.trialStart" required/></label><label>Complimentary service ends<input type="date" v-model="terms.trialEnd" required/></label></div><p>Program fee during this period: <strong>$0</strong>. Monthly billing per active school portal is the standard basis after the complimentary period.</p><label>Proposed monthly rate per school (USD)<input v-model="monthlyDollars" type="number" min="0" step="0.01" placeholder="Unset — pricing agreement required"/></label><label>Cancellation notice (days)<input v-model.number="terms.cancellationNoticeDays" type="number" min="0" max="365" required/></label><p>Saving or signing this agreement does not activate charges. Paid service requires a separately agreed rate and activation.</p><button class="scb-button" :disabled="busy">{{agreement?'Save new draft revision':'Create agreement draft'}}</button></form>
      <template v-if="agreement"><details open><summary>Read the agreement</summary><article class="scb-agreement-paper" v-html="agreementHtml"></article></details><button class="scb-button scb-outline" @click="printAgreement">Print / save a copy</button>
        <form v-if="agreement.status==='draft'" class="scb-form scb-workspace-panel" @submit.prevent="issue"><h3>Assign for signatures</h3><p>The exact saved revision will be locked and assigned through the existing document-signing workflow. Each representative signs from their own account.</p><label>{{selected.name}} representative<select v-model="signers.agencySignerId" required><option value="">Choose active agency administrator</option><option v-for="user in candidates.agency" :key="user.id" :value="user.id">{{user.first_name}} {{user.last_name}} · {{user.email}}</option></select></label><label>MH4Kidz representative<select v-model="signers.operatorSignerId" required><option value="">Choose active MH4Kidz administrator</option><option v-for="user in candidates.operator" :key="user.id" :value="user.id">{{user.first_name}} {{user.last_name}} · {{user.email}}</option></select></label><p v-if="!candidates.operator.length">Link MH4Kidz in Platform Billing and assign its authorized administrator before issuing.</p><label class="scb-program-check"><input v-model="reviewed" type="checkbox" required/> I reviewed this saved revision and confirmed both representatives’ authority.</label><button class="scb-button" :disabled="busy||!reviewed||!candidates.operator.length">Lock revision and assign signatures</button></form>
        <div v-else class="scb-program-signatures"><p>{{selected.name}} signature: <strong>{{agreement.agency_signature_status==='completed'?'Complete':'Pending'}}</strong></p><p>MH4Kidz signature: <strong>{{agreement.operator_signature_status==='completed'?'Complete':'Pending'}}</strong></p><p>The issued text is preserved. Later changes require a separate agreement or amendment.</p><router-link v-if="mySigningTask" :to="`/tasks/documents/${mySigningTask}/sign`">Open my signing task →</router-link></div>
      </template>
    </section>
  </main>
</template>
<script setup>
import {computed,onMounted,ref} from 'vue';
import DOMPurify from 'dompurify';
import api from '../../services/api';
import {useAuthStore} from '../../store/auth';
import {schoolCareBridgePartnerPath} from '../../utils/schoolCareBridgeTenant';
import '../../styles/schoolCareBridge.css';
import '../../styles/schoolCareBridgeWorkspace.css';
const auth=useAuthStore(),partners=ref([]),agencies=ref([]),administrators=ref([]),loading=ref(true),busy=ref(false),error=ref(''),notice=ref(''),showCreate=ref(false),selected=ref(null),agreement=ref(null),candidates=ref({agency:[],operator:[]}),reviewed=ref(false),existingAgencyId=ref('');
const defaults={trialStart:'2026-10-01',trialEnd:'2027-03-31',cancellationNoticeDays:30,monthlyRateCents:null};
const terms=ref({...defaults}),monthlyDollars=ref(''),tenantForm=ref({name:'',slug:'',logoUrl:'',adminUserId:''}),signers=ref({agencySignerId:'',operatorSignerId:''});
const agreementHtml=computed(()=>DOMPurify.sanitize(agreement.value?.html||''));
const mySigningTask=computed(()=>Number(agreement.value?.agency_signer_user_id)===Number(auth.user?.id)?agreement.value?.agency_task_id:Number(agreement.value?.operator_signer_user_id)===Number(auth.user?.id)?agreement.value?.operator_task_id:null);
async function action(fn){busy.value=true;error.value='';notice.value='';try{await fn();}catch(e){error.value=e.response?.data?.error?.message||'The request could not be completed.';}finally{busy.value=false;}}
async function load(){loading.value=true;await action(async()=>{const [p,a,u]=await Promise.all([api.get('/schoolcarebridge/admin/partners'),api.get('/agencies'),api.get('/schoolcarebridge/admin/administrators')]);partners.value=p.data.partners;agencies.value=(Array.isArray(a.data)?a.data:[]).filter(a=>a.organization_type==='agency'&&a.is_active);administrators.value=u.data.users;});loading.value=false;}
async function selectPartner(partner){selected.value=partner;agreement.value=null;candidates.value={agency:[],operator:[]};reviewed.value=false;signers.value={agencySignerId:'',operatorSignerId:''};await action(async()=>{const [a,s]=await Promise.all([api.get(`/schoolcarebridge/admin/partners/${partner.id}/agreement`),api.get(`/schoolcarebridge/admin/partners/${partner.id}/signers`)]);agreement.value=a.data.agreement;candidates.value=s.data;terms.value={...defaults,...agreement.value?.terms};monthlyDollars.value=terms.value.monthlyRateCents==null?'':(terms.value.monthlyRateCents/100).toFixed(2);});}
async function createTenant(){await action(async()=>{await api.post('/schoolcarebridge/admin/tenants',{...tenantForm.value,adminUserId:Number(tenantForm.value.adminUserId)});await load();showCreate.value=false;notice.value='SchoolCareBridge tenant created. Public listing remains off until reviewed.';});}
async function connectAgency(){await action(async()=>{await api.put(`/schoolcarebridge/admin/partners/${existingAgencyId.value}`,{publicListed:false});await load();notice.value='Agency connected with its existing workspace preserved.';});}
async function setListing(partner,listed){await action(async()=>{await api.put(`/schoolcarebridge/admin/partners/${partner.id}`,{publicListed:listed});partner.publicListed=listed;notice.value='Partner directory updated.';});}
async function saveDraft(){await action(async()=>{const rate=monthlyDollars.value===''?null:Math.round(Number(monthlyDollars.value)*100);const {data}=await api.put(`/schoolcarebridge/admin/partners/${selected.value.id}/agreement`,{terms:{...terms.value,monthlyRateCents:rate},revision:agreement.value?.revision??null});agreement.value=data.agreement;reviewed.value=false;notice.value='Draft saved. No signatures or charges were created.';});}
async function issue(){await action(async()=>{await api.post(`/schoolcarebridge/admin/agreements/${agreement.value.id}/issue`,{revision:agreement.value.revision,reviewHash:agreement.value.reviewHash,agencySignerId:Number(signers.value.agencySignerId),operatorSignerId:Number(signers.value.operatorSignerId)});await selectPartner(selected.value);notice.value='Agreement locked and assigned to both representatives. No email or financial transaction was sent.';});}
function printAgreement(){window.print();}
onMounted(load);
</script>
<style scoped>
.scb-program{margin:auto}.scb-program-row{display:flex;align-items:center;gap:22px;flex-wrap:wrap;border-top:1px solid #dce6ef;padding:22px 0}.scb-program-row>div{flex:1;min-width:200px}.scb-program-row small{display:block;color:#61778a;margin-top:5px}.scb-program-row label{font-size:13px}.scb-program-setup{display:grid;grid-template-columns:1fr 1fr;gap:35px;background:#f4f8fa;padding:25px;border-radius:12px;margin-bottom:25px}.scb-program-dates{display:grid;grid-template-columns:1fr 1fr;gap:18px}.scb-program-check{display:flex!important;align-items:start;gap:10px!important}.scb-program summary{font-weight:700;cursor:pointer;padding:22px 0}.scb-program-signatures{margin:20px 0}@media(max-width:750px){.scb-program-setup,.scb-program-dates{grid-template-columns:1fr}.scb-program-row{gap:15px}}@media print{.scb-program>header,.scb-program>section:first-of-type,.scb-form,.scb-program-signatures,summary{display:none!important}}
</style>
