<template>
 <section class="call-billing"><button type="button" @click="open=!open;open&&load()">{{ open?'Close billing review':'Review call for billing' }}</button>
 <div v-if="open"><p>Request review of a documented service. This does not charge the client or submit a claim. Ringing, hold time and routine scheduling do not automatically become billable service time.</p><p v-if="error" role="alert">{{ error }}</p><p v-if="loading">Loading…</p>
 <form v-else-if="data" @submit.prevent="save('request_review')"><p><strong>{{ labels[data.status]||data.status }}</strong><span v-if="data.claimId"> · Claim #{{ data.claimId }} ({{ data.claimStatus }})</span></p>
 <fieldset :disabled="saving||!!data.claimId"><label>Actual service time (minutes)<input v-model="form.serviceMinutes" type="number" min="0.1" max="1440" step="0.1" required /></label><label>Service provided<textarea v-model="form.description" minlength="10" maxlength="6000" rows="3" required /></label><label>Why this communication should be reviewed for billing<textarea v-model="form.billingReason" minlength="10" maxlength="6000" rows="3" required /></label><label>Proposed service code (optional)<input v-model="form.serviceCode" maxlength="5" /></label><button type="submit">{{ saving?'Saving…':'Save for billing review' }}</button></fieldset>
 <div v-if="data.canReview&&!data.claimId&&data.status!=='not_requested'" class="review-actions"><label>Existing claim ID<input v-model="claimId" type="number" min="1" /></label><button type="button" :disabled="saving||!claimId" @click="save('attach_claim')">Attach existing claim</button><button type="button" :disabled="saving" @click="save('not_billable')">Mark not billable</button><p>Only a claim that belongs to this client and agency can be linked. “Billed” follows the claim’s actual submission status.</p></div>
 </form></div></section>
</template>
<script setup>
import {ref} from 'vue';import api from '../../services/api';
const props=defineProps({callId:{type:[Number,String],required:true}}),emit=defineEmits(['saved']);
const open=ref(false),data=ref(null),loading=ref(false),saving=ref(false),error=ref(''),claimId=ref(''),form=ref({description:'',billingReason:'',serviceMinutes:'',serviceCode:''});
const labels={not_requested:'No billing review requested',review_requested:'Awaiting billing review',not_billable:'Not billable',claim_linked:'Claim linked — see claim status',billed:'Billed — claim submitted'};
function apply(value){data.value=value;form.value={description:'',billingReason:'',serviceMinutes:'',serviceCode:'',...value.details};}
async function load(){loading.value=true;error.value='';try{apply((await api.get(`/communications/calls/${props.callId}/billing-review`)).data);}catch(e){error.value=e.response?.data?.error?.message||'Unable to load billing review.';}finally{loading.value=false;}}
async function save(action){saving.value=true;error.value='';try{apply((await api.put(`/communications/calls/${props.callId}/billing-review`,{...form.value,action,revision:data.value.revision,claimId:Number(claimId.value)})).data);emit('saved');}catch(e){error.value=e.response?.data?.error?.message||'Unable to save billing review.';}finally{saving.value=false;}}
</script>
<style scoped>.call-billing{padding:14px 0;border-top:1px solid #d3dfe8;margin-top:12px;color:#21394e}.call-billing p{line-height:1.5;color:#435b6d}label{display:block;margin:12px 0}input,textarea{display:block;padding:9px;width:100%;max-width:650px;box-sizing:border-box;border:1px solid #8097a9;border-radius:6px;font:inherit}fieldset{border:0;padding:0}button{padding:9px 13px;margin-right:8px;border:1px solid #335675;background:#fff;color:#21476a;border-radius:6px;cursor:pointer}[role=alert]{color:#a72020}.review-actions{margin-top:20px;border-top:1px solid #d3dfe8}</style>
