// Runs only against a disposable local schema. Processor calls are stubbed; no money moves.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import mysql from 'mysql2/promise';
const password=process.env.SCB_TEST_MYSQL_PASSWORD||'';
const host='127.0.0.1',port=Number(process.env.SCB_TEST_MYSQL_PORT||33479);
const name='scb_test_commerce_20260928';
const admin=mysql.createPool({host,port,user:'root',password,multipleStatements:true});
await admin.query(`DROP DATABASE IF EXISTS ${name}; CREATE DATABASE ${name} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
await admin.query("CREATE USER IF NOT EXISTS 'scb_fixture'@'localhost' IDENTIFIED BY 'local_fixture_only'; GRANT ALL ON scb_test_commerce_20260928.* TO 'scb_fixture'@'localhost'");
Object.assign(process.env,{DB_HOST:host,DB_PORT:String(port),DB_USER:'scb_fixture',DB_PASSWORD:'local_fixture_only',DB_NAME:name,STRIPE_SECRET_KEY:'sk_test_fixture',STRIPE_PUBLISHABLE_KEY:'pk_test_fixture'});
const db=mysql.createPool({host,port,user:'root',password,database:name,multipleStatements:true,timezone:'Z'});
let defaultPool;
try{
 await db.query(readFileSync(process.argv[2]||'/tmp/scb-commerce-schema.sql','utf8'));
 const migration=readFileSync(new URL('../../database/migrations/1506_schoolcarebridge_program_commerce.sql',import.meta.url),'utf8');
 await db.query(migration);await db.query(migration);
 ({default:defaultPool}=await import('../src/config/database.js'));
 const c=await import('../src/services/schoolCareBridgeCommerce.service.js'),p=await import('../src/services/schoolCareBridgePrograms.service.js');
 const {default:Stripe}=await import('../src/services/stripePayments.service.js');
 const {contractDocuments}=await import('../src/services/schoolCareBridgeContractTemplates.js');
 const {hash}=await import('../src/services/schoolCareBridgeCommercialPolicy.js');
 const user={id:1,role:'super_admin'},schoolUser={id:2,role:'school_staff'};
 await db.execute("INSERT INTO agencies(id,name,slug,organization_type,is_active) VALUES(2,'Partner','itsco','agency',1),(3,'MH4Kidz','mh4kidz','agency',1),(4,'School','school','school',1)");
 await db.execute("INSERT INTO users(id,first_name,last_name,email,role,is_active) VALUES(1,'Operator','Admin','op@example.test','super_admin',1),(2,'School','Staff','school@example.test','school_staff',1),(3,'Presenter','One','presenter@example.test','provider',1),(4,'Agency','Admin','agency@example.test','admin',1)");
 await db.execute('INSERT INTO user_agencies (user_id,agency_id,is_active) VALUES (1,3,1),(2,4,1),(3,2,1),(4,2,1)');
 await db.execute('INSERT INTO organization_affiliations (agency_id,organization_id,is_active) VALUES (2,4,1)');
 await db.execute("INSERT INTO provider_school_assignments(provider_user_id,school_organization_id,day_of_week,is_active) VALUES (3,4,'Monday',1),(3,4,'Tuesday',1)");
 await db.execute('INSERT INTO schoolcarebridge_program_config (id,operator_agency_id) VALUES(1,3)');
 await db.execute("INSERT INTO schoolcarebridge_partners(agency_id,workspace_mode,public_listed) VALUES(2,'connected',1)");
 await db.execute('INSERT INTO finance_organizations(agency_id,enabled) VALUES(3,1)');
 await db.execute("INSERT INTO finance_programs(id,agency_id,name) VALUES(1,3,'School workshops')");
 await db.execute("INSERT INTO finance_documents(id,agency_id,name,kind,mime,size_bytes,content_encrypted,sha256) VALUES(1,3,'Executed MSA','contract','application/pdf',100,'fixture',REPEAT('a',64)),(2,3,'Executed BAA','contract','application/pdf',100,'fixture',REPEAT('b',64))");
 let t=await c.terms(db);assert.equal(t.active,false);assert.equal(t.terms.developmentBps,5000);
 await assert.rejects(c.issueUsageInvoice(user,'2027-04',db),/executed agreement/);
 t=await c.saveTerms(user,{revision:t.revision,terms:{...t.terms,rolloutDate:'2026-08-01',effectiveDate:'2026-09-01',operatorAddress:'123 Test St',platformAddress:'456 Test St',operatorNoticeEmail:'op@example.test',platformNoticeEmail:'pt@example.test',governingState:'Colorado',upstreamCoveredEntities:'Synthetic fixture only'}},db);
 await c.activateTerms(user,{revision:t.revision,contractDocumentId:1,baaDocumentId:2,signedTermsReviewed:true,independentApprovalConfirmed:true,reviewHash:hash(contractDocuments(t.terms,t.revision).map(d=>d.html))},db);
 await assert.rejects(c.saveTerms(user,{revision:t.revision,terms:t.terms},db),/Signed terms/);
 await c.captureUsage(user,db);await c.captureUsage(user,db);
 const [[snap]]=await db.execute('SELECT * FROM schoolcarebridge_usage_snapshots WHERE partner_agency_id=2');assert.equal(snap.school_count,1);assert.equal(snap.provider_count,1);assert.equal(snap.admin_count,1);
 const [[snapCount]]=await db.execute('SELECT COUNT(*) n FROM schoolcarebridge_usage_snapshots');assert.equal(snapCount.n,2);
 await assert.rejects(c.issueUsageInvoice(user,'2026-08',db),/incomplete/);
 for(let day=1;day<=31;day++){const date=`2026-08-${String(day).padStart(2,'0')}`;await db.execute('INSERT INTO schoolcarebridge_usage_snapshots (usage_date,partner_agency_id,school_count,provider_count,admin_count,evidence_json) VALUES (?,0,0,0,0,?), (?,2,1,1,1,?)',[date,'{}',date,'{}']);}
 const usageInvoice=await c.issueUsageInvoice(user,'2026-08',db);assert.equal((await c.issueUsageInvoice(user,'2026-08',db)).id,usageInvoice.id);const [[usageTotal]]=await db.execute('SELECT total_cents FROM schoolcarebridge_invoices WHERE id=?',[usageInvoice.id]);assert.equal(Number(usageTotal.total_cents),2000);
 const input={title:'Parent workshop',programType:'original',ownerName:'MH4Kidz',audience:'parents',description:'A synthetic workshop.',deliveryMode:'in_person',regions:['Denver'],presenterName:'Presenter One',presenterUserId:3,presenterBio:'Test',travelAvailable:true,durationMinutes:60,capacity:30,fundingMode:'cash',priceCents:50000,financeProgramId:1,published:true};
 const created=await p.saveProgram(user,null,input,db);assert.equal((await p.publicCatalog(db)).length,1);
 await assert.rejects(p.saveProgram(schoolUser,null,input,db),/administrator/);
 const bookingInput={programId:created.id,schoolId:4,requestKey:'fixture-booking-0001',start:'2030-01-01T10:00:00Z',end:'2030-01-01T11:00:00Z',timezone:'UTC',region:'Denver',location:'School hall',attendance:20,language:'English',fundingRequested:'cash'};
 const b=await p.createBooking(schoolUser,bookingInput,db);const again=await p.createBooking(schoolUser,bookingInput,db);assert.equal(b.id,again.id);
 const quote={revision:1,serviceCents:50000,travelCents:0,schoolCents:50000,expiresDate:'2030-01-01',scope:'One workshop',cancellationTerms:'Full refund 7 days before; reschedule thereafter.',presenterPaymentTerms:'Net 30 after delivery.',financeProgramId:1};
 await p.quoteBooking(user,b.id,quote,db);await p.acceptQuote(schoolUser,b.id,{revision:2,authorizedToBook:true},db);
 await assert.rejects(p.acceptQuote(schoolUser,b.id,{revision:2,authorizedToBook:true},db),/changed/);
 await p.confirmBooking(user,b.id,{revision:3,presenterAvailabilityConfirmed:true},db);
 const [[invoice]]=await db.execute("SELECT * FROM schoolcarebridge_invoices WHERE booking_id=? AND kind='booking'",[b.id]);assert.equal(Number(invoice.total_cents),50000);
 await db.execute("INSERT INTO agency_billing_accounts (agency_id,stripe_connect_account_id,stripe_connect_status) VALUES (3,'acct_mh4','active')");
 let intents=0;const pi={id:'pi_fixture',client_secret:'fixture_secret',status:'requires_payment_method',amount:50000,amount_received:0,currency:'usd',metadata:{source:'schoolcarebridge_invoice',scb_invoice_id:String(invoice.id)}};
 Stripe.createPaymentIntent=async()=>{intents++;return pi;};Stripe.retrievePaymentIntent=async()=>pi;
 await c.startPayment(schoolUser,invoice.id,db);await c.startPayment(schoolUser,invoice.id,db);assert.equal(intents,1);
 await assert.rejects(c.reconcilePayment({...pi,status:'succeeded',amount_received:49999},'acct_mh4',db),/match/);
 await c.reconcilePayment({...pi,status:'succeeded',amount_received:50000},'acct_mh4',db);await c.reconcilePayment({...pi,status:'succeeded',amount_received:50000},'acct_mh4',db);
 const paid=await c.invoiceAccess(schoolUser,invoice.id,{},db);assert.equal(paid.status,'paid');assert.equal(paid.receipt_number,`SCB-R-${invoice.id}`);
 const [[audit]]=await db.execute("SELECT COUNT(*) n FROM schoolcarebridge_commerce_audit WHERE action='payment_verified'");assert.equal(audit.n,1);
 await assert.rejects(c.invoiceAccess({id:999,role:'school_staff'},invoice.id,{},db),/access/);
 const costs=await p.prepareBookingExpenses(user,b.id,{},db);assert.ok(costs.presenter&&costs.platform);assert.deepEqual(await p.prepareBookingExpenses(user,b.id,{},db),costs);
 const conflict=await p.createBooking(schoolUser,{...bookingInput,requestKey:'fixture-booking-0002'},db);await p.quoteBooking(user,conflict.id,quote,db);await p.acceptQuote(schoolUser,conflict.id,{revision:2,authorizedToBook:true},db);await assert.rejects(p.confirmBooking(user,conflict.id,{revision:3,presenterAvailabilityConfirmed:true},db),/overlapping/);
 const funded=await p.createBooking(schoolUser,{...bookingInput,requestKey:'fixture-booking-0003',start:'2030-01-02T10:00:00Z',end:'2030-01-02T11:00:00Z',fundingRequested:'grant'},db);await p.quoteBooking(user,funded.id,{...quote,schoolCents:0,fundingNotes:'Grant requested, not approved'},db);await p.acceptQuote(schoolUser,funded.id,{revision:2,authorizedToBook:true},db);await assert.rejects(p.confirmBooking(user,funded.id,{revision:3,presenterAvailabilityConfirmed:true},db),/Approve the presenter/);
 await db.execute("UPDATE schoolcarebridge_bookings SET requested_start='2026-09-01 10:00:00',requested_end='2026-09-01 11:00:00' WHERE id=?",[b.id]);
 await p.completeBooking(user,b.id,{revision:4,attendance:18,summary:'Synthetic completion'},db);
 const [[platformInvoice]]=await db.execute("SELECT * FROM schoolcarebridge_invoices WHERE booking_id=? AND kind='platform_usage'",[b.id]);assert.equal(Number(platformInvoice.total_cents),5000);await assert.rejects(c.invoiceAccess(schoolUser,platformInvoice.id,{},db),/access/);
 await assert.rejects(c.startPayment(user,platformInvoice.id,db),/approve this booking/);
 await db.execute("UPDATE finance_expenses SET status='approved',approved_by_user_id=4 WHERE id=?",[costs.platform]);
 const platformPi={...pi,id:'pi_platform_fixture',amount:5000,amount_received:5000,status:'succeeded',metadata:{source:'schoolcarebridge_invoice',scb_invoice_id:String(platformInvoice.id)}};Stripe.createPaymentIntent=async()=>platformPi;await c.startPayment(user,platformInvoice.id,db);await c.reconcilePayment(platformPi,null,db);const [[settled]]=await db.execute('SELECT status,payment_reference FROM finance_expenses WHERE id=?',[costs.platform]);assert.equal(settled.status,'paid');assert.equal(settled.payment_reference,platformPi.id);
 Stripe.refundPaymentIntent=async()=>({id:'re_fixture',status:'succeeded'});await c.refundInvoice(user,invoice.id,{reason:'Synthetic full refund'},db);assert.equal((await c.invoiceAccess(schoolUser,invoice.id,{},db)).status,'refunded');
 const {default:router}=await import('../src/routes/schoolCareBridgeCommerce.routes.js');let response,routeError;const route=router.stack.find(l=>l.route?.path==='/operations/workspace').route;await route.stack.at(-1).handle({user},{json:x=>{response=x;}},e=>{routeError=e;});if(routeError)throw routeError;assert.ok(response.canManage);assert.ok(response.programs.length);
 console.log('PASS: repeatable migration; signed-term gate; daily distinct counts; published catalog; duplicate booking; quote revision/acceptance; conflict prevention; school invoice; merchant-bound verified receipt/replay; access isolation; finance obligations; completion/platform fee; refund; full workspace SQL. Processor was stubbed.');
}finally{await db.end();if(defaultPool)await defaultPool.end();await admin.query(`DROP DATABASE IF EXISTS ${name}; DROP USER IF EXISTS 'scb_fixture'@'localhost'`);await admin.end();}
