<template>
  <div class="scb-product-preview" aria-label="Illustrative SchoolCareBridge workspace">
    <div class="scb-preview-bar"><span class="scb-preview-dots">● ● ●</span><span>SchoolCareBridge</span><small>Illustrative preview</small></div>
    <div class="scb-preview-window"><aside><span class="scb-preview-school">{{agency?'Your agency':'Your school'}}</span><span v-for="(label,i) in ['Overview','Providers','Schools','Clients','Forms','Messages']" :key="label" :class="{'is-selected':i===0}">{{label}}</span></aside><div class="scb-preview-content"><p class="scb-preview-eyebrow">{{agency?'YOUR SCHOOL PARTNERSHIPS':'YOUR SCHOOL COMMUNITY'}}</p><h3>A clear place to start.</h3><p>Care teams and school staff, working together.</p><div class="scb-preview-shortcuts"><div v-for="[symbol,label] in [['↗','Providers'],['▦','Schedules'],['≡','Enrollment']]" :key="label"><b>{{symbol}}</b><strong>{{label}}</strong><span>Open workspace</span></div></div><div class="scb-preview-detail"><h4>{{agency?'School partnerships':'Student support'}}</h4><div v-for="label in (agency?['School portals','Provider coordination','Shared communication']:['Enrollment forms','School roster','Care team messages'])" :key="label"><span class="scb-preview-check">✓</span><span>{{label}}</span><small>Role-based access</small></div></div></div></div>
  </div>
</template>
<script setup>defineProps({agency:Boolean});</script>
<style scoped>
.scb-product-preview{border-radius:17px;overflow:hidden;border:1px solid #d6e5ed;background:white;box-shadow:0 24px 60px #13365125;text-align:left;color:#163957}.scb-preview-bar{height:40px;background:#f5f9fc;display:flex;align-items:center;gap:18px;padding:0 16px;font-size:11px;border-bottom:1px solid #e0eaf0}.scb-preview-bar small{margin-left:auto;color:#637e93}.scb-preview-dots{font-size:9px;letter-spacing:3px;color:#82b9c6}.scb-preview-window{display:grid;grid-template-columns:112px 1fr;min-height:335px}.scb-preview-window aside{background:#12334e;color:#cfdfeb;display:flex;flex-direction:column;gap:6px;padding:14px 9px;font-size:10px}.scb-preview-window aside span{padding:9px 7px}.scb-preview-window aside .is-selected{border-radius:5px;background:#285374;color:white}.scb-preview-school{font-weight:700;color:white;margin-bottom:8px}.scb-preview-content{padding:25px;background:#f8fbfe}.scb-preview-content h3{font-size:21px;margin:5px 0}.scb-preview-content>p{font-size:10px;margin:7px 0;color:#637a8e}.scb-preview-content .scb-preview-eyebrow{font-size:8px;letter-spacing:.09em;color:#008991}.scb-preview-shortcuts{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:20px 0}.scb-preview-shortcuts>div{display:grid;gap:7px;background:white;border:1px solid #e0eaf0;border-radius:8px;padding:12px 8px}.scb-preview-shortcuts b{color:#00a49b;font-size:21px}.scb-preview-shortcuts strong{font-size:10px}.scb-preview-shortcuts span{font-size:8px;color:#637a8e}.scb-preview-detail{background:white;border:1px solid #e0eaf0;border-radius:8px;padding:13px}.scb-preview-detail h4{font-size:12px;margin:0 0 10px}.scb-preview-detail>div{display:flex;gap:8px;align-items:center;font-size:9px;border-top:1px solid #eef3f6;padding:9px 0}.scb-preview-detail small{margin-left:auto;font-size:8px;color:#63829a}.scb-preview-check{color:#00a67e}@media(max-width:550px){.scb-preview-window{grid-template-columns:83px 1fr;min-height:280px}.scb-preview-content{padding:15px 10px}.scb-preview-window aside{font-size:8px}.scb-preview-detail small{display:none}.scb-preview-shortcuts{gap:4px}.scb-preview-shortcuts>div{padding:8px 4px}.scb-preview-content h3{font-size:17px}}
</style>
