import {expect,it} from 'vitest';
import {commonAmendmentClauses,handbookSections,renderAmendment} from '../itscoOctober2026Drafts.js';
import {octoberAdminTopics} from '../itscoOctober2026AdminUpdate.js';
it('shows fixed service pay and separately paid H-code admin with escaped employee names',()=>{const html=renderAmendment({employee:{name:'Example <script>x</script>'},schedule:{creditRate:44,hcodeRate:32,indirectRate:22},leaveChoice:'sick'});expect(html).toContain('<strong>$44.00</strong>');expect(html).toContain('<strong>$35.67</strong>');expect(html).not.toContain('<script>');expect(html).not.toContain('$48.40');});
it('keeps sick leave, statutory protection, prospective rates and the 60-day waiver',()=>{const html=commonAmendmentClauses('sick');for(const phrase of ['not a new vacation benefit','actual hours','60 calendar days','December 9','Tier 3','written notice','25 credits'])expect(html).toContain(phrase);});
it('seeds a professional group policy and a handbook accrual ratio',()=>{const sections=handbookSections();expect(sections.find(s=>s.slug==='groups-moratorium-and-approval').bodyHtml).toContain('90853');expect(sections.find(s=>s.slug==='groups-moratorium-and-approval').bodyHtml).toContain('Skill Builders');expect(sections.find(s=>s.slug==='paid-time-off-and-colorado-sick-leave').bodyHtml).toContain('1.20 ÷ 30');});
it('keeps the shortened Admin Update free of PTO and deferred brand sections',()=>{const topics=octoberAdminTopics();expect(topics.some(t=>['schoolcarebridge','auricwell'].includes(t.key))).toBe(false);expect(topics.map(t=>t.body).join(' ')).not.toMatch(/PTO|sick leave/i);expect(topics.find(t=>t.key==='welcome_october').body).not.toContain('when your invitation arrives');});

it('shows the remaining recorded probation without restarting it at the amendment date',()=>{
 const html=renderAmendment({employee:{name:'Eden',originalAgreementDate:'2026-09-12'},schedule:{category:1,level:1,creditRate:24,hcodeRate:24,creditRateProbation:22,hcodeRateProbation:22,ptoRate:22,probationWaived:false,probationStartDate:'2026-09-12',probationEndDate:'2026-12-11'}});
 expect(html).toContain('first non-probation day');expect(html).toContain('2026-12-11');expect(html).toContain('2026-09-12');expect(html).toContain('clinical service credits pay $22.00');expect(html).toContain('Compensation Level 3 is not the trigger');expect(html).toContain('That waiver does not waive the remaining new-hire probation');expect(html).toContain('regular rates after probation ends');
});
