<template><div class="finance-modal" @click.self="$emit('close')"><aside class="finance-dialog expense-dialog" role="dialog" aria-modal="true" aria-labelledby="expense-heading"><header><div><span class="finance-eyebrow">EXPENSE #{{ expense.id }}</span><h2 id="expense-heading">{{ expense.title }}</h2></div><button @click="$emit('close')" aria-label="Close expense">×</button></header><span class="finance-badge" :class="expense.status">{{ label(expense.status) }}</span><p>{{ expense.description }}</p><dl class="finance-details"><div><dt>Amount</dt><dd>{{ money(expense.amount_cents) }}</dd></div><div><dt>Program</dt><dd>{{ data.programs.find(p=>p.id===expense.program_id)?.name }}</dd></div><div><dt>Date</dt><dd>{{ day(expense.expense_date) }}</dd></div><div><dt>Kind</dt><dd>{{ label(expense.kind) }}</dd></div></dl><p v-if="error" role="alert">{{ error }}</p>
<section><header><h3>Supporting documents</h3><button v-if="role!=='viewer'" @click="$emit('upload',expense.id)">Attach evidence</button></header><p v-if="!docs.length">Attach a receipt, invoice, or scholarship award before approval.</p><button v-for="d in docs" :key="d.id" class="link" @click="$emit('download',d)">{{ d.name }}</button></section>
<section v-if="role==='manager'"><h3>Funding allocations</h3><div v-for="(line,i) in splits" :key="i" class="finance-actions"><select v-model="line.allocationId" :disabled="!canCode" aria-label="Funding allocation"><option value="">Select allocation</option><option v-for="a in eligibleAllocations" :key="a.id" :value="a.id">{{ a.name }}</option></select><input v-model="line.amount" type="number" min=".01" step=".01" :disabled="!canCode" aria-label="Allocation dollars" /><button v-if="canCode" @click="splits.splice(i,1)" aria-label="Remove split">×</button></div><div v-if="canCode" class="finance-actions"><button @click="splits.push({allocationId:'',amount:''})">Add split</button><button :disabled="busy" @click="saveFunding">Save funding</button></div></section>
<section v-if="editable"><button @click="editing=!editing">{{ editing?'Close changes':'Amend draft request' }}</button><form v-if="editing" @submit.prevent="saveEdit"><label>Description<input v-model="edit.title" required maxlength="200" /></label><label>Details<textarea v-model="edit.description" maxlength="5000" /></label><label>Amount ($)<input v-model="edit.amount" type="number" min=".01" step=".01" required /></label><label>Expense date<input v-model="edit.expenseDate" type="date" required /></label><label>Reason for amendment<textarea v-model="edit.note" required maxlength="5000" /></label><p>Funding coding will be cleared for another review.</p><button class="primary" :disabled="busy">Save amendment</button></form></section>
<section v-if="actions.length"><h3>Next action</h3><form @submit.prevent="changeStatus"><label>Action<select v-model="action" required><option value="">Choose…</option><option v-for="s in actions" :key="s" :value="s">{{ s==='paid'?'Record completed external payment':label(s) }}</option></select></label><label>Comment visible to the organization<textarea v-model="note" required maxlength="5000" /></label><label v-if="action==='approved'" class="check"><input v-model="restrictionsReviewed" type="checkbox" required /> I checked the receipts, purpose, budget, and fund/grant restrictions.</label><template v-if="action==='paid'"><p class="finance-callout">Record a payment already completed through your bank or accounting system. This app does not send money.</p><label>Payment reference<input v-model="paymentReference" required maxlength="200" /></label><label>Payment date<input v-model="paymentDate" type="date" required /></label><label>QuickBooks reference (optional)<input v-model="quickbooksReference" maxlength="200" /></label><label class="check"><input v-model="paymentConfirmed" type="checkbox" required /> I verified the payment was completed.</label></template><button class="primary" :disabled="busy||!action">Save action</button></form></section>
<section><h3>Request history</h3><ol class="finance-timeline"><li v-for="h in data.history.filter(h=>h.expense_id===expense.id)" :key="h.id"><strong>{{ label(h.to_status) }}</strong><small>{{ day(h.created_at) }}</small><p>{{ h.note }}</p></li></ol></section>
</aside></div></template>
<script setup>
import {ref,computed,onBeforeUnmount} from 'vue';import api from '../../services/api';import {money,day,label,dollarCents} from './financeForms';
const props=defineProps({agencyId:Number,expense:Object,data:Object,role:String,userId:Number});const emit=defineEmits(['close','saved','upload','download']);let active=true;onBeforeUnmount(()=>{active=false;});
const busy=ref(false),error=ref(''),action=ref(''),note=ref(''),restrictionsReviewed=ref(false),paymentConfirmed=ref(false),paymentReference=ref(''),paymentDate=ref(new Date().toISOString().slice(0,10)),quickbooksReference=ref(''),editing=ref(false),edit=ref({title:props.expense.title,description:props.expense.description,amount:Number(props.expense.amount_cents)/100,expenseDate:day(props.expense.expense_date),note:''});
const splits=ref((props.data.splits||[]).filter(s=>s.expense_id===props.expense.id).map(s=>({allocationId:s.allocation_id,amount:Number(s.amount_cents)/100})));
const docs=computed(()=>props.data.documents.filter(d=>d.expense_id===props.expense.id)),canCode=computed(()=>['draft','submitted','in_review','needs_info'].includes(props.expense.status)),editable=computed(()=>['draft','needs_info'].includes(props.expense.status)&&(props.role==='manager'||props.expense.requested_by_user_id===props.userId));
const eligibleAllocations=computed(()=>props.data.allocations?.filter(a=>props.data.budgets.find(b=>b.id===a.budget_id)?.program_id===props.expense.program_id)||[]);
const next={draft:['submitted','void'],submitted:['in_review','needs_info','rejected'],in_review:['needs_info','approved','rejected'],needs_info:['submitted','void'],approved:['scheduled','needs_info','void'],scheduled:['paid','approved']};
const actions=computed(()=>props.role==='manager'?(next[props.expense.status]||[]).filter(s=>s!=='approved'||(props.expense.requested_by_user_id!==props.userId&&props.expense.staff_user_id!==props.userId)):editable.value?['submitted','void']:[]);
async function mutate(method,path,body){busy.value=true;error.value='';try{await api[method](`/finance-operations/${props.agencyId}/expenses/${props.expense.id}${path}`,{revision:props.expense.revision,...body});if(active)emit('saved');}catch(e){if(active)error.value=e.response?.data?.error?.message||'This expense could not be updated';}finally{if(active)busy.value=false;}}
function saveFunding(){try{return mutate('put','/funding',{splits:splits.value.map(s=>({allocationId:Number(s.allocationId),amountCents:dollarCents(s.amount)}))});}catch(e){error.value=e.message;}}
function saveEdit(){try{return mutate('patch','',{...edit.value,amountCents:dollarCents(edit.value.amount)});}catch(e){error.value=e.message;}}
function changeStatus(){return mutate('post','/status',{status:action.value,note:note.value,restrictionsReviewed:restrictionsReviewed.value,paymentConfirmed:paymentConfirmed.value,paymentReference:paymentReference.value,paymentDate:paymentDate.value,quickbooksReference:quickbooksReference.value});}
</script>
