import {beforeEach,describe,it,expect,vi} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import {createRouter,createMemoryHistory} from 'vue-router';
import Intake from '../PtcoBusinessIntake.vue';
import api from '../../../services/api';
vi.mock('../../../services/api',()=>({default:{post:vi.fn()}}));
async function setup(props={}){const router=createRouter({history:createMemoryHistory(),routes:[{path:'/:pathMatch(.*)*',component:{template:'<div/>'}}]});await router.push('/p/ptco/start');return mount(Intake,{props,global:{plugins:[router]}});}
async function review(w){for(const [auto,value] of [['organization','Example Business'],['given-name','Sample'],['family-name','Owner'],['email','owner@example.test'],['tel','5550100']])await w.find(`input[autocomplete="${auto}"]`).setValue(value);const selects=w.findAll('select');await selects[0].setValue('consulting');await selects[1].setValue('established');await w.find('form').trigger('submit');await w.find('textarea').setValue('Organize our business operations.');await w.find('form').trigger('submit');await w.find('input[type="checkbox"]').setValue(true);}
beforeEach(()=>{vi.clearAllMocks();history.replaceState({},'', '/');});
describe('business intake',()=>{
 it('uses the selected path and service, and confirms success only after persistence',async()=>{api.post.mockResolvedValue({data:{id:'reference',status:'submitted'}});const w=await setup({path:'hq',service:'people'});await review(w);expect(w.text()).toContain('People Operations');expect(w.text()).not.toContain('Request received');await w.find('form').trigger('submit');await flushPromises();expect(api.post.mock.calls[0][1]).toMatchObject({businessName:'Example Business',path:'hq',services:['people'],consent:true});expect(w.text()).toContain('Request received');expect(w.text()).toContain('reference');w.unmount();});
 it('keeps entered data and reuses the idempotency key after a failed response',async()=>{api.post.mockRejectedValueOnce({response:{data:{error:{message:'Temporarily unavailable'}}}}).mockResolvedValueOnce({data:{id:'retry',status:'submitted'}});const w=await setup();await review(w);await w.find('form').trigger('submit');await flushPromises();expect(w.text()).toContain('Temporarily unavailable');expect(w.text()).not.toContain('Request received');await w.find('form').trigger('submit');await flushPromises();expect(api.post.mock.calls[0][2].headers['Idempotency-Key']).toBe(api.post.mock.calls[1][2].headers['Idempotency-Key']);expect(w.text()).toContain('Request received');w.unmount();});
 it('does not submit from the website editor preview',async()=>{const w=await setup({preview:true});await review(w);await w.find('form').trigger('submit');expect(api.post).not.toHaveBeenCalled();expect(w.text()).toContain('editor preview');w.unmount();});
 it('removes an invitation from the URL and requires a matching password before activation',async()=>{history.replaceState({},'','/#invite='+'a'.repeat(64));api.post.mockResolvedValueOnce({data:{businessName:'Approved Company',email:'owner@example.test',slug:'approved-company'}}).mockResolvedValueOnce({data:{loginPath:'/approved-company/login',setupPath:'/approved-company/admin/settings'}});const w=await setup();await flushPromises();expect(location.hash).toBe('');expect(w.text()).toContain('Approved Company');const inputs=w.findAll('input[type="password"]');await inputs[0].setValue('long-test-password');await inputs[1].setValue('different-password');await w.find('input[type="checkbox"]').setValue(true);await w.find('form').trigger('submit');expect(api.post).toHaveBeenCalledTimes(1);expect(w.text()).toContain('do not match');await inputs[1].setValue('long-test-password');await w.find('form').trigger('submit');await flushPromises();expect(w.find('a').attributes('href')).toContain('/approved-company/login?redirect=');expect(w.text()).toContain('workspace is ready');w.unmount();});
});
