import {it,expect,vi,beforeEach,afterEach} from 'vitest';import {mount,flushPromises} from '@vue/test-utils';import Welcome from '../../../views/KioskWelcomeView.vue';import {kioskMatches} from '../../../utils/kioskSearch';
vi.mock('vue-router',()=>({useRoute:()=>({params:{locationId:1}})}));vi.mock('../../../services/api',()=>({default:{get:vi.fn(),post:vi.fn()}}));import api from '../../../services/api';
let wrapper;const p={id:7,firstName:'Elizabeth',lastName:'Rosas',agencyId:2,agencyName:'ITSCO',officeBooked:true,currentSlot:{eventId:12,startAt:'2026-09-30 15:00:00'},bookings:[{eventId:12,startAt:'2026-09-30 15:00:00',endAt:'2026-09-30 16:00:00'}]};
beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date('2026-09-30T20:45:00Z'));vi.resetAllMocks();window.scrollTo=vi.fn();api.get.mockImplementation(async url=>({data:url.endsWith('/people')?{people:[p],agencies:[{id:2,name:'ITSCO'}]}:{providers:[p],locationName:'Windchime',timezone:'America/Denver',windowStartAt:'2026-09-30 15:00:00',windowClosesAt:'2026-09-30T21:31:00Z'}}));});
afterEach(()=>{wrapper?.unmount();vi.useRealTimers();document.body.innerHTML='';});
async function open(){wrapper=mount(Welcome,{attachTo:document.body,global:{stubs:{KioskCheckInFlow:true,KioskOfficeBoard:true}}});await flushPromises();await wrapper.get('.welcome-screen').trigger('click');await flushPromises();}
it('has one compact welcome heading and five separate views',async()=>{await open();expect(wrapper.findAll('h1')).toHaveLength(1);expect(wrapper.findAll('.tabs button').map(b=>b.text())).toEqual(['Client check-in','Today’s providers','Programs & events','Office directory','Providers']);expect(wrapper.find('.lobby-header').exists()).toBe(false);expect(wrapper.find('.intro-row .clock').exists()).toBe(true);});
it('brands the lobby AuricWell and keeps provider office numbers in the directory only',async()=>{
 const roomProvider={...p,currentRoomNumber:'204',currentSlot:{...p.currentSlot,roomNumber:'204'},bookings:p.bookings.map(b=>({...b,roomNumber:'204'}))};
 api.get.mockResolvedValue({data:{providers:[roomProvider],locationName:'Windchime'}});
 await open();expect(wrapper.get('.hero').text()).toContain('AuricWell Office');expect(wrapper.text()).not.toContain('Office 204');
 await wrapper.findAll('.tabs button')[1].trigger('click');await flushPromises();await wrapper.get('.choose').trigger('click');
 expect(document.body.textContent).not.toContain('Office 204');expect(document.body.textContent).toContain('3:00 PM');
});
it('uses the current slot directly, while today opens a read-only list',async()=>{await open();await wrapper.get('.choose').trigger('click');expect(wrapper.findComponent({name:'KioskCheckInFlow'}).props('directSlot')).toEqual(p.currentSlot);await wrapper.findAll('.tabs button')[1].trigger('click');await flushPromises();await wrapper.get('.choose').trigger('click');expect(document.body.textContent).toContain('Office hours and bookings for today');expect(wrapper.findComponent({name:'KioskCheckInFlow'}).exists()).toBe(false);});
it('warns at 60 seconds and clears the visit after 10 more seconds',async()=>{await open();await wrapper.get('.search input').setValue('elzbth');await vi.advanceTimersByTimeAsync(60000);expect(document.body.textContent).toContain('All done?');await vi.advanceTimersByTimeAsync(10000);expect(wrapper.find('.welcome-screen').exists()).toBe(true);expect(wrapper.get('.search input').element.value).toBe('');});
it('shows only the organizations in the current result set',async()=>{await open();expect(wrapper.findAll('.filters button').map(b=>b.text())).toEqual(['All organizations','ITSCO']);});
it('supports missing letters, accents, reordered names, and one typo',()=>{expect(kioskMatches('Elizabeth Rosas ITSCO','elzbth')).toBe(true);expect(kioskMatches('José García','garcia jose')).toBe(true);expect(kioskMatches('Elizabeth Rosas','elizabth')).toBe(true);expect(kioskMatches('Elizabeth Rosas','zzzz')).toBe(false);});

it('opens profiles from the name and the daily-details button, and returns completed arrivals to welcome',async()=>{
 await open();await wrapper.get('.profile-link').trigger('click');await flushPromises();expect(document.body.textContent).toContain('About your provider');
 document.querySelector('.dialog-close').click();await flushPromises();await wrapper.findAll('.tabs button')[1].trigger('click');await flushPromises();await wrapper.get('.choose').trigger('click');
 const profileButton=[...document.querySelectorAll('button')].find(b=>b.textContent==='View provider profile');profileButton.click();await flushPromises();expect(document.querySelectorAll('[role=dialog]')).toHaveLength(1);expect(document.body.textContent).toContain('About your provider');
 document.querySelector('.dialog-close').click();await flushPromises();await wrapper.findAll('.tabs button')[0].trigger('click');await flushPromises();await wrapper.get('.choose').trigger('click');wrapper.findComponent({name:'KioskCheckInFlow'}).vm.$emit('checked-in');await flushPromises();expect(wrapper.find('.welcome-screen').exists()).toBe(true);expect(wrapper.find('.thanks').text()).toContain('Thank you');expect(wrapper.findComponent({name:'KioskCheckInFlow'}).exists()).toBe(false);
});
