<template><section class="family-ledger"><header><h3>Invoices &amp; receipts</h3><button @click="load" :disabled="busy">Refresh</button></header><p v-if="error" role="alert">{{ error }}</p><p v-if="message" role="status">{{ message }}</p><p v-if="loading" role="status">Loading billing…</p>
  <div class="ledger-summary" aria-label="Billing summary"><div><span>Assigned &amp; shared balances</span><strong>{{ loading || error ? '—' : money(visibleBalance) }}</strong><small>Includes balances shared with your account</small></div><div><span>Payment plans</span><strong>{{ loading || error ? '—' : balances.filter(r => r.plan).length }}</strong><small>Review schedules and authorization below</small></div><div><span>Payment setup tasks</span><strong>{{ loading || error ? '—' : tasks.filter(t => t.status === 'pending').length }}</strong><small>Complete your card verification and waiver</small></div></div>
  <article v-for="task in tasks.filter(t => t.status === 'pending')" :key="`task-${task.id}`" class="task"><div><strong>{{ task.title }}</strong><p>Due {{ date(task.expiresAt) }}</p></div><router-link :to="{path:'/billing/complete',query:{task:task.id,agencyId}}">Complete payment setup →</router-link></article>
  <article v-for="row in balances" :key="row.allocationId"><div class="row"><div><strong>{{ money(row.balanceCents) }} remaining</strong><p>{{ row.payerName || 'Awaiting payer assignment' }} · {{ row.serviceDomain }} · Due {{ date(row.dueDate) }}</p><p v-if="row.fulfillmentError" role="status">{{ row.fulfillmentError }}</p><small>Balance {{ row.receivableId }} · {{ row.status }}<span v-if="row.holdReason"> · Office review required</span></small></div><button v-if="row.canPay && row.balanceCents > 0" :disabled="busy" @click="selectPayment(row)">Make a payment</button></div>
    <form v-if="selected?.allocationId === row.allocationId" @submit.prevent="pay"><label>Amount for my share ($)<input v-model="amount" type="number" min="0.01" :max="row.balanceCents / 100" step="0.01" required /></label><p>Your assigned card will be used. Another payer’s card is never used.</p><button :disabled="busy">{{ busy ? 'Processing…' : 'Pay with my assigned card' }}</button><button type="button" @click="selected=null" :disabled="busy">Cancel</button></form>
    <details v-if="row.plan"><summary>Payment plan · {{ row.plan.status }}{{ row.plan.autoPay ? ' · Automatic payments' : '' }}</summary><ul><li v-for="i in row.plan.installments" :key="i.id">{{ date(i.dueDate) }} — {{ money(i.balanceCents) }} remaining</li></ul><template v-if="row.canPay && row.plan.status==='proposed'"><p>I agree to these amounts and due dates for my share. Automatic payments, if selected, apply only to this schedule on my selected card. I may revoke automatic payment; unpaid balances remain due.</p><label><input v-model="planAuto[row.plan.id]" type="checkbox" /> Automatically pay installments with my assigned card</label><label>Sign your full name<input v-model="planSignatures[row.plan.id]" maxlength="255" /></label><button :disabled="busy || !planSignatures[row.plan.id]?.trim()" @click="acceptPlan(row.plan)">Accept payment plan</button></template><button v-if="row.canPay" :disabled="busy" @click="cancelPlan(row.plan)">Cancel plan / revoke automatic payments</button></details>
    <details v-if="row.canPay && row.balanceCents>0 && !row.plan"><summary>Request to share this balance</summary><p>The other responsible payer must accept before shares change.</p><label>Other responsible payer<select v-model="splitPayer"><option :value="null">Choose a payer</option><option v-for="payer in peers[row.clientId] || []" :key="payer.userId" :value="payer.userId">{{ payer.name }}</option></select></label><label>My share (%)<input v-model="myPercent" type="number" min="1" max="99" /></label><label>Sign your name<input v-model="splitSignature" maxlength="255" /></label><button :disabled="busy || !splitPayer || !splitSignature.trim()" @click="requestSplit(row)">Propose split</button></details>
  </article>
  <p v-if="!loading && !balances.length">No balances are available to your account for this selection.</p>
  <article v-for="request in splits" :key="`split-${request.id}`"><h4>Shared payment request · Balance {{ request.receivableId }}</h4><p v-for="share in request.shares" :key="share.payerUserId">{{ request.payerNames?.[share.payerUserId] || `Payer ${share.payerUserId}` }}: {{ share.basisPoints / 100 }}%</p><label>Your signature<input v-model="responseSignature" /></label><button :disabled="busy || !responseSignature.trim()" @click="respond(request,true)">Accept my share</button><button :disabled="busy" @click="respond(request,false)">Decline</button></article>
  <section class="receipt-history"><header><div><h3>Payment history</h3><p>Download a receipt for each recorded payment.</p></div><div class="receipt-filters"><label>Search receipts<input v-model="receiptSearch" type="search" placeholder="Receipt number or payer" /></label><label>Date range<select v-model="receiptRange"><option value="all">All dates</option><option value="30">Last 30 days</option><option value="180">Last 6 months</option><option value="365">Last year</option></select></label></div></header><div class="receipt-scroll" tabindex="0" aria-label="Payment receipt history"><table><thead><tr><th scope="col">Receipt</th><th scope="col">Payment date</th><th scope="col">Responsible payer</th><th scope="col">Amount paid</th><th scope="col">Receipt</th></tr></thead><tbody><tr v-for="r in filteredReceipts" :key="r.paymentId"><td><strong>{{ r.receiptNumber || `Payment ${r.paymentId}` }}</strong></td><td>{{ date(r.receivedAt) }}</td><td>{{ r.payerName }}</td><td>{{ money(r.netPaidCents ?? r.amountCents) }}<small v-if="r.refundedCents">{{ money(r.refundedCents) }} refunded</small></td><td><button :disabled="busy" @click="downloadReceipt(r)">Download / print receipt</button></td></tr></tbody></table></div><p v-if="!loading && !filteredReceipts.length">{{ receipts.length ? 'No receipts match these filters.' : 'No payment receipts available.' }}</p></section>
</section></template>
<script setup>
import { computed,ref,watch } from 'vue';import { loadStripe } from '@stripe/stripe-js';import api from '../../services/api';
const props=defineProps({agencyId:[String,Number],clientId:[String,Number]});
const balances=ref([]),tasks=ref([]),receipts=ref([]),splits=ref([]),peers=ref({}),loading=ref(false),busy=ref(false),error=ref(''),message=ref(''),selected=ref(null),amount=ref(''),planVersion=ref(''),planAuto=ref({}),planSignatures=ref({}),splitPayer=ref(null),myPercent=ref(50),splitSignature=ref(''),responseSignature=ref('');let seq=0,requestKey='';
const receiptSearch=ref(''),receiptRange=ref('all');
const visibleBalance=computed(()=>balances.value.reduce((sum,row)=>sum+Math.max(0,Number(row.balanceCents)||0),0));
const filteredReceipts=computed(()=>receipts.value.filter(r=>{const search=receiptSearch.value.trim().toLowerCase();const matches=!search||`${r.receiptNumber||''} ${r.payerName||''}`.toLowerCase().includes(search);return matches&&(receiptRange.value==='all'||new Date(r.receivedAt).getTime()>=Date.now()-Number(receiptRange.value)*86400000);}));
const money=n=>new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(Number(n)/100),date=v=>v?new Date(/^\d{4}-\d{2}-\d{2}$/.test(v)?`${v}T12:00:00`:v).toLocaleDateString():'';
const params=()=>({agencyId:props.agencyId,...(props.clientId?{clientId:props.clientId}:{})});
async function load(){const own=++seq;if(!props.agencyId){loading.value=false;return;}loading.value=true;error.value='';try{const results=await Promise.all(['/balances','/tasks','/receipts','/splits','/payers'].map(path=>api.get(`/family-billing${path}`,{params:params()})));if(own!==seq)return;balances.value=results[0].data.balances;planVersion.value=results[0].data.planTermsVersion;tasks.value=results[1].data.tasks;receipts.value=results[2].data.receipts;splits.value=results[3].data.requests;peers.value=results[4].data.payers;}catch(e){if(own===seq)error.value=e.response?.data?.error?.message||'Billing could not be loaded.';}finally{if(own===seq)loading.value=false;}}
async function action(fn){if(busy.value)return;busy.value=true;error.value='';message.value='';try{await fn();await load();}catch(e){error.value=e.response?.data?.error?.message||e.message||'The update could not be completed.';}finally{busy.value=false;}}
function selectPayment(row){selected.value=row;amount.value=(row.balanceCents/100).toFixed(2);requestKey=crypto.randomUUID();}
const pay=()=>action(async()=>{const row=selected.value,payload={agencyId:props.agencyId,amountCents:Math.round(Number(amount.value)*100),idempotencyKey:requestKey};let result=(await api.post(`/family-billing/allocations/${row.allocationId}/pay`,payload)).data;if(result.requiresAction){const stripe=await loadStripe(result.publishableKey,{stripeAccount:result.connectedAccountId});const confirmed=await stripe.confirmCardPayment(result.clientSecret,{payment_method:result.paymentMethodId});if(confirmed.error)throw new Error(confirmed.error.message);result=(await api.post(`/family-billing/allocations/${row.allocationId}/pay`,payload)).data;}if(!result.paid)throw new Error('Payment is awaiting confirmation.');selected.value=null;message.value='Payment confirmed. Your receipt is available below.';});
const acceptPlan=plan=>action(()=>api.post(`/family-billing/plans/${plan.id}/accept`,{agencyId:props.agencyId,autoPay:!!planAuto.value[plan.id],consent:{accepted:true,version:planVersion.value,signatureName:planSignatures.value[plan.id]}}));
const cancelPlan=plan=>action(()=>api.post(`/family-billing/plans/${plan.id}/cancel`,{agencyId:props.agencyId}));
const requestSplit=row=>action(()=>api.post(`/family-billing/balances/${row.receivableId}/split`,{agencyId:props.agencyId,shares:[{payerUserId:row.payerUserId,basisPoints:Math.round(Number(myPercent.value)*100)},{payerUserId:splitPayer.value,basisPoints:10000-Math.round(Number(myPercent.value)*100)}],consent:{accepted:true,signatureName:splitSignature.value}}));
const respond=(request,accept)=>action(()=>api.post(`/family-billing/splits/${request.id}/respond`,{agencyId:props.agencyId,accept,signatureName:responseSignature.value}));
const downloadReceipt=r=>action(async()=>{const result=await api.get(`/family-billing/receipts/${r.paymentId}.pdf`,{params:params(),responseType:'blob'});const url=URL.createObjectURL(result.data),a=document.createElement('a');a.href=url;a.download=`${r.receiptNumber}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);});
watch(()=>[props.agencyId,props.clientId],()=>{selected.value=null;balances.value=[];receipts.value=[];tasks.value=[];splits.value=[];void load();},{immediate:true});
</script>
<style scoped>
.ledger-summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));background:#fff;border:1px solid #e2eaf4;border-radius:12px;padding:24px;gap:25px;box-shadow:0 3px 14px #193e7310}.ledger-summary>div{display:grid;gap:7px;min-width:0}.ledger-summary>div+div{padding-left:25px;border-left:1px solid #e6edf5}.ledger-summary span{font-size:12px;color:#506682}.ledger-summary strong{font-size:28px;color:#193050;letter-spacing:-.7px}.ledger-summary small{font-size:12px;color:#657790}.receipt-history{background:white;border:1px solid #e2eaf4;border-radius:12px;padding:24px;min-width:0}.receipt-history h3{margin:0;font-size:20px}.receipt-history header p{margin:5px 0;color:#526784;font-size:13px}.receipt-filters{display:flex;gap:14px;flex-wrap:wrap}.receipt-filters label{font-size:12px;margin:0!important}.receipt-filters input,.receipt-filters select{font-size:13px!important;margin-top:4px;width:100%!important}.receipt-scroll{overflow:auto;max-width:100%;margin-top:22px}.receipt-scroll table{border-collapse:collapse;width:100%;font-size:13px;min-width:650px}.receipt-scroll th{text-align:left;background:var(--portal-tint,#f3f7fc);color:#425b7c;font-size:11px;font-weight:600}.receipt-scroll th,.receipt-scroll td{padding:15px 12px;border-bottom:1px solid #e5ecf5}.receipt-scroll td small{display:block;margin-top:3px;color:#6b7689}.receipt-scroll button{font-size:12px!important;white-space:nowrap}.family-ledger .task{border-left:4px solid var(--portal-accent,#2459ad)}
@media(max-width:650px){.ledger-summary{padding:18px;gap:16px;grid-template-columns:1fr}.ledger-summary>div+div{padding-left:0;padding-top:14px;border-left:0;border-top:1px solid #e6edf5}.ledger-summary strong{font-size:24px}.receipt-history{padding:18px}.receipt-filters{width:100%}.receipt-filters label{flex:1;min-width:130px}}

.family-ledger{display:grid;gap:20px;min-width:0}.family-ledger header,.row,.receipt,.task{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.family-ledger article{padding:22px;border:1px solid #d8e1ed;background:white;border-radius:12px}.family-ledger p{line-height:1.5}.family-ledger button,.task a{border:1px solid #b7c8dc;padding:10px 14px;border-radius:7px;background:#f4f8ff;color:#17436f;font:inherit;cursor:pointer}.family-ledger button:disabled{opacity:.5}.family-ledger label{display:block;margin:12px 0}.family-ledger input:not([type=checkbox]),select{display:block;padding:10px;width:100%;max-width:360px;box-sizing:border-box;border:1px solid #aabbd0;border-radius:6px;font:inherit}.family-ledger details{margin-top:20px;border-top:1px solid #e2e8f0;padding-top:14px}.family-ledger form{padding:16px;background:#f1f6fc;margin-top:16px}.family-ledger [role=alert]{color:#ac1a1a}.receipt{border-bottom:1px solid #e2e8f0;padding:16px 0}.task{background:#edf5ff!important}
</style>
