<template>
 <section class="eft-panel" aria-label="Direct deposit enrollment">
  <header><div><h2>EFT / direct deposit</h2><p>EFT sends payer money to your bank. ERA explains the payment. Track both separately.</p></div><button type="button" :disabled="busy" @click="load">Refresh EFT</button></header>
  <p>If deposits already arrive, preserve the existing enrollment. A switch to Claim.MD does not establish a new bank destination.</p>
  <p v-if="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p>
  <div class="table-scroll"><table><thead><tr><th>Payer / group</th><th>EFT status</th><th>Evidence date</th><th>Actions</th></tr></thead><tbody><tr v-for="row in items" :key="row.id"><td>{{ row.payerName }} · {{ row.payerId }}<small>NPI {{ row.providerNpi }}</small></td><td>{{ row.identityCurrent ? labels[row.status] : 'Billing identity changed — review required' }}</td><td>{{ row.evidence.evidenceDate }}</td><td><button type="button" :disabled="busy" @click="edit(row)">{{ row.identityCurrent ? 'Update status' : 'Review current setup' }}</button><button type="button" :disabled="busy" @click="showHistory(row)">History</button><a v-if="row.guide.url" :href="row.guide.url" target="_blank" rel="noopener noreferrer">{{ row.guide.name }} ↗</a></td></tr></tbody></table></div>
  <p v-if="!items.length && !busy">No EFT evidence recorded here. This does not mean direct deposit is inactive.</p><p v-if="hasMore">Showing the most recently updated 200 EFT records.</p>
  <button type="button" :disabled="busy" @click="start">Track a payer’s EFT</button>
  <form v-if="draft" @submit.prevent="save">
   <h3>{{ draft.revision ? 'Update EFT evidence' : 'Record EFT setup' }}</h3>
   <label>Billing office / group<select v-model="draft.officeId" required :disabled="busy || !!draft.revision"><option value="">Select</option><option v-for="office in offices" :key="office.id" :value="office.id">{{ office.name }} · NPI {{ office.practice_npi || 'Missing' }}</option></select></label>
   <p>Offices in this agency sharing a group NPI and tax ID share EFT tracking. Another group or legal entity needs its own verified setup.</p>
   <label>Claims payer ID<input v-model="draft.payerId" required maxlength="32" :disabled="busy || !!draft.revision" /></label>
   <label>Payer name<input v-model="draft.payerName" required maxlength="128" :disabled="busy" /></label>
   <p v-if="draft.payerId.toUpperCase() === 'COCHA'"><a href="https://enrollsafe.payeehub.org/" target="_blank" rel="noopener noreferrer">CCHA EnrollSafe ↗</a> · Keep an existing working enrollment. Complete new EFT enrollment or bank changes only in the payer’s secure portal.</p>
   <p v-else>Confirm the EFT portal with the payer’s provider support. Bank authorization, routing/account numbers and supporting bank documents belong in that secure portal.</p>
   <label>Status<select v-model="draft.status" :disabled="busy"><option v-for="(label,value) in labels" :key="value" :value="value">{{ label }}</option></select></label>
   <label>Payer enrollment scope<select v-model="draft.enrollmentLevel" :disabled="busy"><option value="unknown">Not yet confirmed</option><option value="tin">Entire tax ID (TIN)</option><option value="npi">Selected NPI(s) under the tax ID</option></select></label>
   <label>Evidence source<select v-model="draft.source" :disabled="busy"><option value="staff_report">Agency / staff report</option><option value="payer_portal">Payer portal</option><option value="payer_support">Payer support</option><option value="bank_deposit">Matched bank deposit</option></select></label>
   <label>Evidence date<input v-model="draft.evidenceDate" type="date" required :disabled="busy" /></label>
   <label>Evidence or enrollment reference<textarea v-model="draft.reference" required minlength="5" maxlength="1000" :disabled="busy" placeholder="Enrollment confirmation, payer case number, or payment/trace reference. No bank account numbers, routing numbers, credentials, or patient details." /></label>
   <label v-if="draft.status==='active_verified'"><input v-model="draft.depositMatched" type="checkbox" :disabled="busy" /> I matched an actual bank deposit to this payer’s payment reference for this billing entity.</label>
   <label><input v-model="draft.attested" type="checkbox" :disabled="busy" /> This dated evidence belongs to the selected payer and billing entity.</label>
   <button :disabled="busy || !draft.attested">Save tracking status</button><button type="button" :disabled="busy" @click="draft=null">Cancel</button>
   <p>Saving records evidence only. It does not enroll with the payer, change bank instructions, or post money. ERA receipt alone cannot verify a bank deposit.</p>
  </form>
  <section v-if="history" aria-label="EFT status history"><h3>{{ history.name }} · EFT history</h3><p>Latest 100 changes; earlier evidence is retained.</p><article v-for="item in history.items" :key="item.revision"><strong>{{ labels[item.status] }} · {{ item.evidence.evidenceDate }}</strong><p>{{ item.evidence.reference }}</p><small>Revision {{ item.revision }} · Staff #{{ item.actorUserId }} · {{ item.at }}</small></article></section>
 </section>
</template>
<script setup>
import {ref,watch,onMounted,onBeforeUnmount} from 'vue';import api from '../../services/api.js';
const props=defineProps({agencyId:{type:[String,Number],required:true}}),emit=defineEmits(['updated']);
const labels={unverified:'Not verified',not_started:'Not enrolled',pending:'Enrollment pending',action_required:'Action needed',active_reported:'Direct deposits reported',active_verified:'Bank deposit verified by staff',suspended:'Suspended / stopped'};
const items=ref([]),offices=ref([]),hasMore=ref(false),draft=ref(null),history=ref(null),busy=ref(false),error=ref(''),notice=ref('');let generation=0;
const blank=()=>({officeId:'',payerId:'',payerName:'',status:'unverified',enrollmentLevel:'unknown',source:'staff_report',evidenceDate:new Date().toLocaleDateString('en-CA'),reference:'',attested:false,depositMatched:false,revision:0});
async function load(){const g=++generation;busy.value=true;error.value='';items.value=[];offices.value=[];draft.value=null;history.value=null;try{const {data}=await api.get('/medical-billing/payer-eft',{params:{agencyId:props.agencyId}});if(g===generation){items.value=data.items||[];offices.value=data.offices||[];hasMore.value=!!data.hasMore;}}catch(e){if(g===generation)error.value=e.response?.data?.error?.message||'EFT tracking could not be loaded';}finally{if(g===generation)busy.value=false;}}
function start(){draft.value=blank();history.value=null;notice.value='';}
function edit(row){draft.value={...blank(),officeId:offices.value.find(o=>o.practice_npi===row.providerNpi)?.id||'',payerId:row.payerId,payerName:row.payerName,...(row.identityCurrent?{status:row.status,revision:row.revision,source:row.evidence.source,enrollmentLevel:row.evidence.enrollmentLevel||'unknown',reference:row.evidence.reference}: {})};history.value=null;notice.value='';}
async function save(){const g=generation;busy.value=true;error.value='';try{await api.post('/medical-billing/payer-eft',{...draft.value,agencyId:props.agencyId});if(g===generation){await load();if(g+1===generation){notice.value='EFT evidence saved. Bank instructions and payments were not changed.';emit('updated');}}}catch(e){if(g===generation)error.value=e.response?.data?.error?.message||'EFT evidence could not be saved';}finally{if(g===generation)busy.value=false;}}
async function showHistory(row){const g=generation;busy.value=true;history.value=null;error.value='';try{const {data}=await api.get(`/medical-billing/payer-eft/${row.id}/history`,{params:{agencyId:props.agencyId}});if(g===generation)history.value={name:row.payerName,items:data.items};}catch(e){if(g===generation)error.value='EFT history could not be loaded';}finally{if(g===generation)busy.value=false;}}
watch(()=>draft.value&&[draft.value.officeId,draft.value.payerId,draft.value.payerName,draft.value.status,draft.value.enrollmentLevel,draft.value.source,draft.value.reference,draft.value.evidenceDate],()=>{if(draft.value){draft.value.attested=false;draft.value.depositMatched=false;}});
watch(()=>props.agencyId,()=>{notice.value='';load();});onMounted(load);onBeforeUnmount(()=>{generation++;});
</script>
<style scoped>.eft-panel{background:var(--surface-primary,#fff);border:1px solid var(--border,#dbe3ee);border-radius:12px;padding:20px;margin:18px 0}header{display:flex;justify-content:space-between;gap:16px}h2,h3{margin:0 0 8px}p{line-height:1.5}label{display:block;margin:12px 0}input:not([type=checkbox]),select,textarea{display:block;max-width:100%;min-width:220px;padding:9px;border:1px solid #94a3b8;border-radius:6px}textarea{width:100%;min-height:76px}button{margin:4px;padding:8px 12px;cursor:pointer}table{width:100%;border-collapse:collapse;text-align:left}td,th{padding:10px;border-bottom:1px solid #e2e8f0}small{display:block}.table-scroll{overflow:auto}form,article{border-top:1px solid #cbd5e1;padding-top:14px;margin-top:14px}[role=alert]{color:#b91c1c}[role=status]{color:#166534}</style>
