<template>
  <main class="payment-task" :style="{ '--task-accent': accent }">
    <header v-if="task"><img v-if="task.agency?.logo_url" :src="task.agency.logo_url" alt="" /><div><small>{{ task.agency?.name }}</small><h1>Payment setup</h1></div><span class="private">Private to your account</span></header>
    <p v-if="loading" role="status">Loading your payment task…</p><p v-if="error" role="alert" class="error">{{ error }}</p>
    <section v-if="task?.status === 'completed'" class="complete"><h2>Payment setup complete</h2><p>Your authorization is saved. You can manage your payment method and any separately authorized recurring payments in Billing.</p><router-link :to="`/${task.agency.slug}/guardian?panel=billing`">Return to your portal</router-link></section>
    <div v-else-if="task" class="task-columns"><section class="task-main"><h2>{{ task.title }}</h2><p>Review the clients covered by this authorization, then {{ task.requireCard ? 'verify a card and sign' : 'sign your authorization' }}.</p>
      <div class="client-list"><strong>Applies to</strong><ul><li v-for="id in task.clientIds" :key="id">{{ clients.find(c => Number(c.clientId) === Number(id))?.clientName || `Client ${id}` }}</li></ul></div>
      <section class="step"><h3>1. Review your authorization</h3><p>{{ task.waiver.terms }}</p><p class="waiver" v-if="task.waiver.additionalTerms">{{ task.waiver.additionalTerms }}</p><label class="check"><input type="checkbox" v-model="accepted" /> I accept these terms for the clients listed above.</label><label>Your full name<input v-model="signatureName" autocomplete="name" maxlength="255" /></label><button v-if="!authorized" :disabled="busy || !accepted || !signatureName.trim()" @click="authorize">Accept and continue</button></section>
      <section v-if="authorized && task.requireCard" class="step"><h3>2. Verify your payment method</h3><label v-if="cards.length">Use my saved card<select v-model="cardId"><option :value="null">Choose a card</option><option v-for="card in cards" :value="card.id" :key="card.id">{{ card.card_brand }} ending in {{ card.card_last4 }}</option></select></label><button class="secondary" @click="showCard = !showCard">{{ showCard ? 'Close card form' : 'Add a card securely' }}</button><SecureCardSetup v-if="showCard" :agency-id="task.agencyId" @saved="savedCard" /></section>
      <section v-if="authorized" class="step"><h3>{{ task.requireCard ? '3' : '2' }}. Submit your authorization</h3><p>Submitting stores your signed authorization. Automatic charges require a separate authorization or payment plan.</p><button :disabled="busy || !accepted || !signatureName.trim() || (task.requireCard && !cardId)" @click="complete">{{ busy ? 'Saving…' : 'Sign and complete setup' }}</button></section>
    </section><aside><h3>What happens next?</h3><p>Your billing team can see that this task is complete.</p><p>Your selected card can apply to the clients listed here. Other guardians and clients cannot view its details.</p><p>No payment is taken by completing this task.</p><small>Due {{ new Date(task.expiresAt).toLocaleDateString() }}</small></aside></div>
  </main>
</template>
<script setup>
import { computed,ref,onMounted } from 'vue';
import api from '../../services/api';
import SecureCardSetup from './SecureCardSetup.vue';
const props=defineProps({token:String,taskId:[String,Number],agencyId:[String,Number]});
const task=ref(null),loading=ref(true),error=ref(''),busy=ref(false),accepted=ref(false),signatureName=ref(''),authorized=ref(false),cards=ref([]),clients=ref([]),cardId=ref(null),showCard=ref(false);
const endpoint=()=>props.token?`/family-billing/task-link/${encodeURIComponent(props.token)}`:`/family-billing/tasks/${props.taskId}`;
const accent=computed(()=>{let colors=task.value?.agency?.color_palette;try{if(typeof colors==='string')colors=JSON.parse(colors);}catch{}const color=colors?.primary||colors?.primaryColor;return /^#[\da-f]{6}$/i.test(color||'')?color:'#155dbb';});
const consent=()=>({accepted:accepted.value,waiverAccepted:accepted.value,version:task.value.waiver.version,signatureName:signatureName.value.trim()});
async function refreshCards(){const data=(await api.get('/guardian-billing/overview',{params:{agencyId:task.value.agencyId}})).data;cards.value=data.cards;clients.value=data.clients;}
async function load(){try{task.value=(await api.get(endpoint(),{params:props.agencyId?{agencyId:props.agencyId}:{}})).data;await refreshCards();}catch(e){error.value=e.response?.data?.error?.message||'This payment task is unavailable for your account.';}finally{loading.value=false;}}
async function action(name){busy.value=true;error.value='';try{await api.post(`${endpoint()}/${name}`,{agencyId:task.value.agencyId,consent:consent(),cardId:cardId.value});if(name==='authorize'){authorized.value=true;await refreshCards();}else task.value.status='completed';}catch(e){error.value=e.response?.data?.error?.message||'Your changes could not be saved. Try again.';}finally{busy.value=false;}}
const authorize=()=>action('authorize'),complete=()=>action('complete');async function savedCard(card){cardId.value=card.id;await refreshCards();showCard.value=false;}
onMounted(load);
</script>
<style scoped>
.payment-task{max-width:1160px;margin:auto;padding:32px 24px;color:#18263d;background:#fbfcff;min-height:70vh}.payment-task header{display:flex;align-items:center;gap:18px;border-bottom:1px solid #dee5ef;padding-bottom:24px;margin-bottom:30px}.payment-task header img{width:64px;height:64px;object-fit:contain}.payment-task h1{font-size:26px;margin:4px 0}.private{margin-left:auto;font-size:13px;color:#536780}.task-columns{display:grid;grid-template-columns:minmax(0,1fr) 270px;gap:32px}.task-main{min-width:0}.task-columns aside,.step,.client-list,.complete{border:1px solid #dce4ef;border-radius:12px;background:white;padding:24px;margin-bottom:22px}.task-columns aside{align-self:start;background:#f2f6fc}.payment-task p{line-height:1.65}.payment-task label{display:grid;gap:8px;margin:18px 0}.payment-task .check{display:flex;align-items:flex-start}.payment-task input:not([type=checkbox]),select{box-sizing:border-box;width:100%;min-width:0;border:1px solid #a9b8ce;border-radius:7px;padding:12px;font:inherit}.payment-task button{border:0;border-radius:7px;background:var(--task-accent);color:white;padding:13px 20px;font:inherit;cursor:pointer}.payment-task button:disabled{opacity:.5;cursor:default}.payment-task .secondary{background:#e8eff9;color:#164170;margin:16px 0}.error{color:#a71919}.waiver{white-space:pre-wrap;overflow-wrap:anywhere}@media(max-width:760px){.task-columns{grid-template-columns:minmax(0,1fr)}.payment-task{padding:20px 14px}.private{display:none}.step{padding:18px}}
</style>
