<template>
  <section class="remittances" aria-labelledby="remittance-heading">
    <header><div><p class="eyebrow">ERA → reconciliation → posting</p><h2 id="remittance-heading">Payments for {{ agencyName }}</h2><p>Review payer payments and adjustments. Previously collected copays stay credited to the same visit.</p></div><button :disabled="busy" @click="sync">{{ busy ? 'Working…' : 'Import new ERAs' }}</button></header>
    <p v-if="error" class="notice error" role="alert">{{ error }}</p><p v-if="notice" class="notice" role="status">{{ notice }}</p>
    <div v-if="data" class="summary"><div><span>Insurance payments posted</span><strong>{{ money(data.totals.paidCents) }}</strong><small>Recorded from ERAs · bank verification is separate</small></div><div><span>Non-patient adjustments</span><strong>{{ money(data.totals.adjustmentCents) }}</strong><small>Contractual and other payer adjustments</small></div><div><span>Patient balance reviews</span><strong>{{ data.pendingBalances }}</strong><button v-if="data.pendingBalances" :disabled="busy" @click="retry">Retry resolved items</button></div></div>
    <div class="toolbar"><span>Last import check: {{ data?.lastSyncAt ? new Date(data.lastSyncAt).toLocaleString() : 'Not checked' }}</span><button :disabled="busy" @click="load()">Refresh</button></div>
    <p v-if="data && !data.rows.length" class="empty">No ERAs imported for this agency. Complete its payer ERA enrollment, then import available remittances. Enabling claim transmission does not enroll ERA delivery.</p>
    <div class="table-scroll" v-if="data?.rows.length"><table><thead><tr><th>ERA</th><th>Payer</th><th>Payment date</th><th>Amount</th><th>Claims</th><th>Status</th><th></th></tr></thead><tbody><tr v-for="row in data.rows" :key="row.id"><td>{{ row.eraId }}</td><td>{{ row.payerName }}</td><td>{{ row.paidDate || 'Review date' }}</td><td>{{ money(row.paidCents) }}</td><td>{{ row.claimCount }}</td><td><span class="badge">{{ label(row.status) }}</span></td><td><button :disabled="busy" @click="open(row.id)">Review</button></td></tr></tbody></table></div>
    <nav v-if="data?.nextBefore || before" class="toolbar" aria-label="Remittance pages"><button :disabled="busy || !before" @click="load()">Newest</button><button :disabled="busy || !data.nextBefore" @click="load(data.nextBefore)">Older remittances</button></nav>
    <section v-if="detail" class="detail" aria-labelledby="era-detail-heading">
      <header><div><h3 id="era-detail-heading">{{ detail.payerName }} · ERA {{ detail.eraId }}</h3><p>{{ detail.paidDate }} · {{ money(detail.paidCents) }} · Reference {{ detail.trace || 'Not provided' }}</p></div><button @click="detail = null">Close details</button></header>
      <p v-if="detail.requiresReview || detail.status === 'source_changed'" class="notice error">This remittance requires manual reconciliation before posting. Header difference: {{ money(detail.differenceCents) }}. Review provider-level adjustments, incomplete data or changed source records in Claim.MD.</p>
      <article v-for="item in detail.items" :key="item.id" class="item">
        <header><div><h4>{{ item.patientName || 'Patient not identified' }}</h4><p>Patient account {{ item.pcn || 'Not provided' }} · {{ item.claimId ? `App claim ${item.claimId}` : 'No submitted app claim matched' }} · Payer control {{ item.payerControlNumber || 'Not provided' }}</p></div><span class="badge">{{ item.denied ? 'Denied' : item.reversal ? 'Reversal — review required' : label(item.postingStatus) }}</span></header>
        <dl><div><dt>Billed</dt><dd>{{ money(item.billedCents) }}</dd></div><div><dt>Insurance paid</dt><dd>{{ money(item.paidCents) }}</dd></div><div><dt>Other adjustments</dt><dd>{{ money(item.adjustmentCents - item.responsibilityCents) }}</dd></div><div><dt>Patient responsibility</dt><dd>{{ money(item.responsibilityCents) }}</dd></div></dl>
        <p v-if="item.forwarded" class="notice">Payer forwarded this claim. Review secondary processing before creating a duplicate secondary claim or collecting from the patient.</p>
        <p v-for="blocker in item.blockers" :key="blocker" class="notice error">{{ blocker }}</p>
        <div class="table-scroll"><table><thead><tr><th>Service</th><th>Date</th><th>Units</th><th>Paid</th><th>Adjustment reasons</th></tr></thead><tbody><tr v-for="(line, index) in item.lines" :key="index"><td>{{ line.code }} {{ line.modifiers.filter(Boolean).join(' · ') }}</td><td>{{ line.date }}</td><td>{{ line.units }}</td><td>{{ money(line.paidCents) }}</td><td><span v-for="(a, i) in line.adjustments" :key="i" class="adjustment">{{ a.group }}-{{ a.code }}: {{ money(a.amountCents) }}</span></td></tr></tbody></table></div>
        <p v-if="item.claimAdjustments.length">Claim adjustments: <span v-for="(a, i) in item.claimAdjustments" :key="i" class="adjustment">{{ a.group }}-{{ a.code }} {{ money(a.amountCents) }}</span></p>
        <p class="subtle">PR identifies patient responsibility; CO, OA and PI identify other adjustments. <a href="https://x12.org/codes/claim-adjustment-reason-codes" target="_blank" rel="noopener noreferrer">Look up adjustment reasons ↗</a></p>
        <template v-if="item.postingStatus === 'posted'"><p class="notice">Insurance adjudication posted. Patient balance: {{ label(item.balanceStatus || 'pending') }}.</p><p v-if="item.balanceError" class="notice error">{{ item.balanceError }}</p></template>
        <template v-else>
          <form v-if="!item.claimId" class="match" @submit.prevent="match(item)"><p>Claims from the prior EHR stay unmatched until their history is reconciled. No new patient charge is created.</p><label>Existing submitted app claim ID<input v-model="matches[item.id]" type="number" min="1" required /></label><label>Matching explanation<input v-model="reasons[item.id]" maxlength="2000" required /></label><button :disabled="busy">Match claim</button></form>
          <form v-if="item.claimId && !item.reversal && !item.blockers.length && !detail.requiresReview && detail.status !== 'source_changed'" @submit.prevent="post(item)"><label class="consent"><input v-model="approvals[item.id]" type="checkbox" required /> I reviewed this claim, payer payment, adjustments and patient responsibility.</label><button :disabled="busy || !approvals[item.id]">Post adjudication</button></form>
        </template>
      </article>
    </section>
  </section>
</template>
<script setup>
import { ref, watch, onBeforeUnmount } from 'vue';
import api from '../../services/api';
const props=defineProps({agencyId:{type:Number,required:true},agencyName:{type:String,required:true}});
const data=ref(null),detail=ref(null),error=ref(''),notice=ref(''),busy=ref(false),before=ref(0),matches=ref({}),reasons=ref({}),approvals=ref({});
let generation=0;
const money=cents=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(cents||0)/100);
const label=value=>({review:'Needs review',matched:'Matched — awaiting approval',unmatched:'Needs matching',posted:'Posted',partially_posted:'Partially posted',source_changed:'Source changed — review required',pending:'Pending',completed:'Updated',superseded:'Replaced by final secondary adjudication'}[value]||String(value).replaceAll('_',' '));
async function action(fn){const version=generation;busy.value=true;error.value='';try{await fn(version);}catch(e){if(version===generation)error.value=e.response?.data?.error?.message||'This action could not finish. Refresh to check its status before retrying.';}finally{if(version===generation)busy.value=false;}}
async function refresh(version,cursor=before.value){const result=await api.get('/medical-billing/claimmd/remittances',{params:{agencyId:props.agencyId,...(cursor?{before:cursor}:{})}});if(version===generation){data.value=result.data;before.value=cursor;}}
async function load(cursor=0){return action(v=>refresh(v,cursor));}
async function open(id){return action(async v=>{const r=await api.get(`/medical-billing/claimmd/remittances/${id}`,{params:{agencyId:props.agencyId}});if(v===generation){detail.value=r.data;approvals.value={};}});}
async function sync(){return action(async v=>{const r=await api.post('/medical-billing/claimmd/remittances/sync',{agencyId:props.agencyId},{timeout:180000});if(v!==generation)return;notice.value=`${r.data.imported} ERA(s) imported.${r.data.moreAvailable?' More are available; import again to continue.':''}${r.data.skipped?' Some entries need billing-identity review in Claim.MD.':''}`;await refresh(v,0);});}
async function retry(){return action(async v=>{await api.post('/medical-billing/claimmd/remittances/retry-balances',{agencyId:props.agencyId});if(v===generation){notice.value='Patient balance reviews retried. Unresolved items remain held.';await refresh(v);if(detail.value)await detailRefresh(v);}});}
async function detailRefresh(v){const r=await api.get(`/medical-billing/claimmd/remittances/${detail.value.id}`,{params:{agencyId:props.agencyId}});if(v===generation){detail.value=r.data;approvals.value={};}}
async function match(item){return action(async v=>{await api.post(`/medical-billing/claimmd/remittances/${detail.value.id}/items/${item.id}/match`,{agencyId:props.agencyId,claimId:Number(matches.value[item.id]),reason:reasons.value[item.id]});if(v===generation)await detailRefresh(v);});}
async function post(item){return action(async v=>{await api.post(`/medical-billing/claimmd/remittances/${detail.value.id}/items/${item.id}/post`,{agencyId:props.agencyId,reviewHash:detail.value.reviewHash,approved:approvals.value[item.id]===true});if(v===generation){await refresh(v);await detailRefresh(v);}});}
watch(()=>props.agencyId,()=>{generation++;data.value=null;detail.value=null;notice.value='';matches.value={};reasons.value={};approvals.value={};load();},{immediate:true});
onBeforeUnmount(()=>generation++);
</script>
<style scoped>
.remittances{background:var(--bg-card,#fff);border:1px solid var(--border-color,#dce4ee);border-radius:16px;padding:24px;color:var(--text-primary,#17324d)}header,.toolbar{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}h2,h3,h4{margin:0 0 8px}p{line-height:1.5;margin:8px 0}.eyebrow{font-size:12px;text-transform:uppercase;letter-spacing:.08em}.summary{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin:22px 0}.summary>div{background:var(--bg-secondary,#f4f7fb);border-radius:12px;padding:18px;display:flex;flex-direction:column;gap:8px}.summary strong{font-size:28px}.subtle,small{color:var(--text-secondary,#526477)}button{border:1px solid var(--border-color,#cbd8e5);background:var(--primary-color,#194c72);color:#fff;border-radius:8px;padding:10px 14px;cursor:pointer}button:disabled{opacity:.5;cursor:default}.notice{background:#edf5ff;padding:12px;border-radius:8px}.error{background:#fff1ea;color:#832900}.empty{padding:28px;background:#f5f8fc;border-radius:12px}.table-scroll{overflow:auto;margin:16px 0}table{width:100%;border-collapse:collapse;text-align:left}th,td{padding:12px;border-bottom:1px solid #e2e8f0;vertical-align:top}th{font-size:12px;background:#f4f7fb}.badge{display:inline-block;background:#edf2f7;padding:5px 9px;border-radius:20px;font-size:12px}.detail{margin-top:24px;border-top:2px solid var(--primary-color,#194c72);padding-top:20px}.item{border:1px solid #dce4ee;border-radius:12px;padding:18px;margin-top:18px}dl{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;background:#f7f9fc;padding:16px;border-radius:8px}dt{font-size:12px}dd{margin:8px 0 0;font-weight:700}.adjustment{display:block}.consent{display:flex;align-items:center;gap:8px;margin:14px 0}.match{display:flex;gap:12px;align-items:end;flex-wrap:wrap}.match>p{width:100%}.match label{display:flex;flex-direction:column;gap:6px}input:not([type=checkbox]){border:1px solid #cbd8e5;padding:9px;border-radius:6px}a{color:var(--primary-color,#194c72)}@media(max-width:760px){.summary,dl{grid-template-columns:1fr}.remittances{padding:14px}}
</style>
