const escape = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text = m => m.body_text || m.body || String(m.body_html || '').replace(/<style[\s\S]*?<\/style>|<script[\s\S]*?<\/script>/gi,'').replace(/<br\s*\/?\s*>|<\/p>/gi,'\n').replace(/<[^>]*>/g,'');
const address = value => (Array.isArray(value)?value:value?[value]:[]).map(a=>typeof a==='string'?a:[a.name,a.email?`<${a.email}>`:null].filter(Boolean).join(' ')).join(', ');
export function communicationPrintDocument(title,threads) {
  const content=threads.map(t=>`<article><h2>${escape(t.subject || t.title || 'Conversation')}</h2>${(t.documentation || []).map(d=>`<section><h3>Contact purpose — ${d.completed?'Reviewed':'Saved'}</h3><p>${escape(d.author)} · ${escape(d.createdAt)} · Through message ${escape(d.reviewedThroughId)}</p><pre>${escape(d.purpose)}</pre></section>`).join('')}${(t.messages || []).map(m=>{
    const when=m.sent_at || m.sentAt || m.created_at;
    const date=when?new Date(when):null;
    const from=address(m.from) || [m.author_first_name,m.author_last_name].filter(Boolean).join(' ') || m.direction || '';
    return `<section><dl><dt>From</dt><dd>${escape(from)}</dd><dt>To</dt><dd>${escape(address(m.to) || m.recipientAddress || '')}</dd>${m.cc?.length?`<dt>Cc</dt><dd>${escape(address(m.cc))}</dd>`:''}${m.bcc?.length?`<dt>Bcc</dt><dd>${escape(address(m.bcc))}</dd>`:''}<dt>Date / time (UTC)</dt><dd>${escape(date && Number.isFinite(date.getTime())?date.toISOString():when || 'Not sent')}</dd><dt>Status</dt><dd>${escape(m.send_status || m.deliveryStatus || (m.direction==='inbound'?'received':'sent'))}</dd></dl><pre>${escape(text(m))}</pre>${m.attachments?.length?`<p>Attachments: ${escape(m.attachments.map(a=>a.filename || a.original_filename).join(', '))}</p>`:''}</section>`;
  }).join('')}</article>`).join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>${escape(title)}</title><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:15px system-ui,sans-serif;max-width:850px;margin:24px auto;padding:16px;color:#172b24}section{border-top:1px solid #bbb;padding:12px 0}dl{display:grid;grid-template-columns:120px 1fr;font-size:13px}dt{font-weight:bold}dd{margin:0;overflow-wrap:anywhere}pre{font:inherit;white-space:pre-wrap;overflow-wrap:anywhere}article{margin-bottom:32px}@media print{button{display:none}body{max-width:none;margin:0}h2,dl{break-after:avoid}}</style></head><body><button onclick="window.print()">Print / Save as PDF</button><h1>${escape(title)}</h1><p>Communication record · Generated ${escape(new Date().toISOString())}</p>${content}</body></html>`;
}
