import {publicAppBaseUrl} from './contactReminderToken.service.js';
export const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=value=>Number.isFinite(value)?value.toFixed(1):'—';
export function scoreColor(value){
 if(!Number.isFinite(value))return '#829085';const v=Math.max(0,Math.min(10,value));
 const a=v<5?[188,48,48]:[187,133,14],b=v<5?[187,133,14]:[35,131,61],ratio=(v<5?v:v-5)/5;
 return '#'+a.map((n,i)=>Math.round(n+(b[i]-n)*ratio).toString(16).padStart(2,'0')).join('');
}
function circle(value,label,size=76){return `<table role="presentation" align="center" cellpadding="0" cellspacing="0"><tr><td align="center" valign="middle" width="${size}" height="${size}" style="width:${size}px;height:${size}px;border:5px solid ${scoreColor(value)};border-radius:50%;background:#ffffff;color:#24443d;font-family:Arial,sans-serif;"><strong style="font-size:${size>60?26:19}px;line-height:1.2;">${number(value)}</strong><br><span style="font-size:11px;color:#61715d;">out of 10</span></td></tr><tr><td align="center" style="padding:7px 0 10px;font-size:12px;color:#526352;">${label}</td></tr></table>`;}
function card(label,metric){return `<td width="50%" valign="top" style="padding:10px 6px;"><table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border:1px solid #dce4d9;border-radius:16px;background:#f8faf5;"><tr><td align="center" style="padding:16px 4px 8px;font:600 17px Arial,sans-serif;color:#24443d;">${label}</td></tr><tr><td>${circle(metric.current,'Current')}</td></tr><tr><td><table role="presentation" width="100%"><tr><td width="50%">${circle(metric.previous,'Previous',52)}</td><td width="50%">${circle(metric.average,'Average',52)}</td></tr></table></td></tr></table></td>`;}
export function arrivalEmail(notification,token,feedback=null){
 const base=publicAppBaseUrl(),url=`${base}/api/public/office-arrivals/${token}`,app=feedback?.submissionId?`${base}/office-checkin-responses/${feedback.submissionId}`:`${base}/dashboard?tab=clients&clients=checkins`;
 const context=feedback?`${feedback.serviceType==='tutoring'?'Tutoring':'Therapy / counseling'} · ${feedback.respondentType==='caregiver'?'Guardian / dependent report':feedback.respondentType==='youth_self'?'Youth self-report':'Adult self-report'}`:'';
 const note=feedback?(feedback.completed?'Missing or skipped scores are shown as —.':'Feedback has not been completed yet. Open the responses to see later updates.')+(feedback.linked?' Previous is the last completed score before this visit. Average includes available completed scores through this visit.':' Attach this visit to a confirmed client to enable previous and average comparisons.'):'No questionnaire receipt is available for this arrival.';
 const scoreText=feedback?['connection','progress'].map(key=>`${key==='connection'?'Connection':'Progress'}: current ${number(feedback.metrics[key].current)}/10; previous ${number(feedback.metrics[key].previous)}/10; average ${number(feedback.metrics[key].average)}/10`).join('\n'):'';
 return {subject:'Your client has arrived',text:`${notification.message}\n\n${context}\n${scoreText}\n${note}\n\nView responses (sign-in required): ${app}\nDismiss this arrival or keep future check-ins in-app only: ${url}\nCustom feedback scores, not validated measures. Higher scores are better; distress is reversed.`,html:`<div style="font-family:Arial,sans-serif;color:#24443d;max-width:600px;margin:0 auto;"><h1 style="font-size:26px;">Your client has arrived</h1><p style="line-height:1.6;">${escapeHtml(notification.message)}</p>${feedback?`<p style="font-size:13px;color:#61715d;">${context}</p><table role="presentation" width="100%" cellpadding="0" cellspacing="0"><tr>${card('Connection',feedback.metrics.connection)}${card('Progress',feedback.metrics.progress)}</tr></table>`:''}<p style="font-size:12px;line-height:1.6;color:#61715d;">${note}</p><p><a href="${escapeHtml(app)}" style="display:inline-block;padding:15px 22px;border-radius:10px;background:#315e49;color:#ffffff;text-decoration:none;font-weight:bold;">View this visit’s responses</a></p><p style="font-size:12px;">Sign in with your provider account to view the responses.</p><p style="font-size:11px;color:#61715d;line-height:1.5;">Custom feedback scores, not validated measures. Higher scores move toward green at 10; distress is reversed. Client names and individual answers are not included in this email.</p><p style="font-size:12px;"><a href="${escapeHtml(url)}">Dismiss this arrival</a> · <a href="${escapeHtml(url)}?action=in_app_only">Keep check-ins in-app only</a></p></div>`};
}
