import pool from '../config/database.js';
import StripePaymentsService,{isStripeConfigured,getStripePublishableKey} from './stripePayments.service.js';
import {fail,integer,object,normalizeCommercialTerms,requireCompleteTerms,calendarDate,usageLines,escapeHtml,hash} from './schoolCareBridgeCommercialPolicy.js';
import {contractDocuments} from './schoolCareBridgeContractTemplates.js';

export async function transaction(fn,db=pool){const c=await db.getConnection();try{await c.beginTransaction();const r=await fn(c);await c.commit();return r;}catch(e){await c.rollback();throw e;}finally{c.release();}}
export async function audit(db,user,action,type,id,detail={}){await db.execute('INSERT INTO schoolcarebridge_commerce_audit (actor_user_id,action,object_type,object_id,detail_json) VALUES (?,?,?,?,?)',[user?.id||null,action,type,id||null,JSON.stringify(detail)]);}
export async function operator(db=pool){const [[a]]=await db.execute("SELECT a.id,a.name,a.slug FROM schoolcarebridge_program_config c JOIN agencies a ON a.id=c.operator_agency_id WHERE c.id=1 AND a.slug='mh4kidz' AND a.is_active=1 AND COALESCE(a.is_archived,0)=0");if(!a)throw fail(409,'Connect the active MH4Kidz organization in SchoolCareBridge setup.');return a;}
export async function isOperator(user,db=pool){if(user?.role==='super_admin')return true;if(user?.role!=='admin')return false;const a=await operator(db);const [[m]]=await db.execute('SELECT u.id FROM users u JOIN user_agencies ua ON ua.user_id=u.id WHERE u.id=? AND ua.agency_id=? AND ua.is_active=1 AND u.is_active=1',[user.id,a.id]);return !!m;}
export async function requireOperator(user,db=pool){if(!await isOperator(user,db))throw fail(403,'MH4Kidz program administrator access is required.');return operator(db);}
export async function terms(db=pool,lock=false){const [[r]]=await db.execute(`SELECT * FROM schoolcarebridge_commercial_terms WHERE id=1${lock?' FOR UPDATE':''}`);if(!r)throw fail(409,'SchoolCareBridge commercial setup is unavailable.');return {...r,terms:normalizeCommercialTerms(object(r.terms_json)),active:!!r.activated_at&&r.executed_revision===r.revision};}
export async function saveTerms(user,input,db=pool){if(user.role!=='super_admin')throw fail(403,'Platform administrator required.');const t=normalizeCommercialTerms(input.terms||{});return transaction(async c=>{const r=await terms(c,true);if(r.revision!==Number(input.revision)||r.active)throw fail(409,'Only the current unsigned draft can be edited. Signed terms require a separate amendment.');await c.execute('UPDATE schoolcarebridge_commercial_terms SET terms_json=?,revision=revision+1 WHERE id=1',[JSON.stringify(t)]);await audit(c,user,'terms_draft_saved','terms',1,{revision:r.revision+1});return terms(c);},db);}
export async function activateTerms(user,input,db=pool){if(user.role!=='super_admin')throw fail(403,'Platform administrator required.');return transaction(async c=>{const r=await terms(c,true),a=await operator(c);requireCompleteTerms(r.terms);if(r.active||r.revision!==Number(input.revision)||input.signedTermsReviewed!==true||input.independentApprovalConfirmed!==true)throw fail(409,'Review the current signed terms and independent organizational approval before activation.');const documents=contractDocuments(r.terms,r.revision);if(input.reviewHash!==hash(documents.map(d=>d.html)))throw fail(409,'The reviewed agreement changed. Refresh first.');const ids=[integer(input.contractDocumentId,1),integer(input.baaDocumentId,1)];if(ids[0]===ids[1])throw fail(400,'Attach the executed contract and BAA separately.');for(const id of ids){const [[d]]=await c.execute("SELECT id FROM finance_documents WHERE id=? AND agency_id=? AND kind='contract' AND mime='application/pdf'",[id,a.id]);if(!d)throw fail(400,'Upload both signed PDFs as MH4Kidz finance contract documents first.');}await c.execute('UPDATE schoolcarebridge_commercial_terms SET signed_contract_document_id=?,signed_baa_document_id=?,executed_revision=revision,activated_by_user_id=?,activated_at=NOW() WHERE id=1',[...ids,user.id]);await audit(c,user,'executed_terms_recorded','terms',1,{revision:r.revision,documents:ids,reviewHash:input.reviewHash});return terms(c);},db);}
export async function requireActiveTerms(db=pool){const r=await terms(db);if(!r.active)throw fail(409,'Billing requires the executed platform agreement and BAA to be recorded first.');requireCompleteTerms(r.terms);return r;}

// Capture current facts only; historical gaps are never fabricated from today's membership.
export async function captureUsage(user,db=pool){return transaction(async c=>{
 const today=new Date().toISOString().slice(0,10);await c.execute('SELECT id FROM schoolcarebridge_commercial_terms WHERE id=1 FOR UPDATE');const [[captured]]=await c.execute('SELECT usage_date FROM schoolcarebridge_usage_snapshots WHERE usage_date=? AND partner_agency_id=0',[today]);if(captured)return {date:today,reused:true,moneyMoved:false};const [partners]=await c.execute("SELECT p.agency_id FROM schoolcarebridge_partners p JOIN agencies a ON a.id=p.agency_id WHERE p.is_active=1 AND a.is_active=1 AND COALESCE(a.is_archived,0)=0 ORDER BY p.agency_id");
 for(const p of partners){
  const [schools]=await c.execute("SELECT DISTINCT a.id FROM organization_affiliations oa JOIN agencies a ON a.id=oa.organization_id WHERE oa.agency_id=? AND oa.is_active=1 AND a.organization_type='school' AND a.is_active=1 AND COALESCE(a.is_archived,0)=0 ORDER BY a.id",[p.agency_id]);
  const [providers]=await c.execute("SELECT DISTINCT u.id FROM users u JOIN user_agencies ua ON ua.user_id=u.id JOIN provider_school_assignments psa ON psa.provider_user_id=u.id JOIN organization_affiliations oa ON oa.organization_id=psa.school_organization_id AND oa.agency_id=ua.agency_id JOIN agencies s ON s.id=psa.school_organization_id WHERE ua.agency_id=? AND ua.is_active=1 AND u.is_active=1 AND COALESCE(u.is_archived,0)=0 AND u.role IN ('provider','provider_plus','intern','intern_plus') AND psa.is_active=1 AND oa.is_active=1 AND s.organization_type='school' AND s.is_active=1 AND COALESCE(s.is_archived,0)=0 ORDER BY u.id",[p.agency_id]);
  const [admins]=await c.execute("SELECT DISTINCT u.id FROM users u JOIN user_agencies ua ON ua.user_id=u.id WHERE ua.agency_id=? AND ua.is_active=1 AND u.is_active=1 AND COALESCE(u.is_archived,0)=0 AND u.role='admin' ORDER BY u.id",[p.agency_id]);
  await c.execute('INSERT IGNORE INTO schoolcarebridge_usage_snapshots (usage_date,partner_agency_id,school_count,provider_count,admin_count,evidence_json) VALUES (?,?,?,?,?,?)',[today,p.agency_id,schools.length,providers.length,admins.length,JSON.stringify({schoolIds:schools.map(x=>x.id),providerIds:providers.map(x=>x.id),adminIds:admins.map(x=>x.id),capturedAt:new Date().toISOString()})]);
 }
 // A zero-partner marker proves the collection ran; it is never charged.
 await c.execute('INSERT IGNORE INTO schoolcarebridge_usage_snapshots (usage_date,partner_agency_id,school_count,provider_count,admin_count,evidence_json) VALUES (?,0,0,0,0,?)',[today,JSON.stringify({collectionCompleted:true})]);
 await audit(c,user,'usage_captured','usage',null,{date:today,partners:partners.length});return {date:today,partners:partners.length,moneyMoved:false};
},db);}
export async function usagePreview(month,db=pool){const r=await terms(db);calendarDate(month+'-01');const [snapshots]=await db.execute("SELECT * FROM schoolcarebridge_usage_snapshots WHERE usage_date>=? AND usage_date<DATE_ADD(?,INTERVAL 1 MONTH) ORDER BY usage_date,partner_agency_id",[month+'-01',month+'-01']);const lines=usageLines(snapshots,r.terms,month),missing=[];const end=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5)),0));for(let d=new Date(month+'-01T00:00:00Z');d<=end;d.setUTCDate(d.getUTCDate()+1)){const day=d.toISOString().slice(0,10);if(day>=r.terms.rolloutDate&&!snapshots.some(s=>Number(s.partner_agency_id)===0&&String(s.usage_date instanceof Date?s.usage_date.toISOString():s.usage_date).slice(0,10)===day))missing.push(day);}return {month,lines,totalCents:lines.reduce((n,l)=>n+l.amountCents,0),missingDays:missing,termsRevision:r.revision,active:r.active};}
export async function issueUsageInvoice(user,month,db=pool){if(user.role!=='super_admin')throw fail(403,'Platform administrator required.');return transaction(async c=>{
 const r=await terms(c,true);if(!r.active)throw fail(409,'Record the executed agreement before issuing invoices.');const a=await operator(c),preview=await usagePreview(month,c);
 if(month>=new Date().toISOString().slice(0,7))throw fail(409,'Only a completed service month can be invoiced.');if(preview.missingDays.length)throw fail(409,'Daily usage evidence is incomplete. Reconcile the missing dates before invoicing.');if(!preview.totalCents)throw fail(409,'This month has no billable usage.');
 const [[old]]=await c.execute("SELECT * FROM schoolcarebridge_invoices WHERE kind='platform_usage' AND billing_key=?",[month]);if(old)return old;
 const [created]=await c.execute("INSERT INTO schoolcarebridge_invoices (operator_agency_id,kind,billing_key,debtor_agency_id,terms_revision,lines_json,total_cents,due_date,created_by_user_id) VALUES (?,'platform_usage',?,?,?,?,?,DATE_ADD(CURDATE(),INTERVAL ? DAY),?)",[a.id,month,a.id,r.revision,JSON.stringify(preview.lines),preview.totalCents,r.terms.paymentDueDays,user.id]);await audit(c,user,'invoice_issued','invoice',created.insertId,{month,totalCents:preview.totalCents});return {id:created.insertId};
},db);}
export async function invoiceAccess(user,id,{platformManage=false}={},db=pool){const [[r]]=await db.execute('SELECT i.*,b.requester_user_id FROM schoolcarebridge_invoices i LEFT JOIN schoolcarebridge_bookings b ON b.id=i.booking_id WHERE i.id=?',[integer(id,1)]);if(!r)throw fail(404,'Invoice not found.');const manager=await isOperator(user,db);if(platformManage&&r.kind==='platform_usage'&&user.role!=='super_admin')throw fail(403,'Platform administrator required for a platform invoice adjustment.');if(!manager&&(r.kind==='platform_usage'||Number(r.requester_user_id)!==Number(user.id)))throw fail(403,'You do not have access to this invoice.');return r;}
export function publicInvoice(r){return {id:r.id,kind:r.kind,bookingId:r.booking_id,debtorAgencyId:r.debtor_agency_id,lines:object(r.lines_json),totalCents:Number(r.total_cents),currency:r.currency,status:r.status,issuedAt:r.issued_at,dueDate:r.due_date,receiptNumber:r.receipt_number,paidAt:r.paid_at,refundedCents:Number(r.refunded_cents)};}
async function merchant(invoice,db){if(!isStripeConfigured())throw fail(409,'Card payment is not configured.');if(invoice.kind==='platform_usage')return null;const [[a]]=await db.execute('SELECT stripe_connect_account_id,stripe_connect_status FROM agency_billing_accounts WHERE agency_id=?',[invoice.operator_agency_id]);if(!a?.stripe_connect_account_id||a.stripe_connect_status!=='active')throw fail(409,'MH4Kidz must connect its payment account before collecting program payments.');return a.stripe_connect_account_id;}
export async function startPayment(user,id,db=pool){await invoiceAccess(user,id,{},db);return transaction(async c=>{
 const [[r]]=await c.execute('SELECT * FROM schoolcarebridge_invoices WHERE id=? FOR UPDATE',[id]);if(r.status!=='open')throw fail(409,'This invoice is not awaiting payment.');await requireActiveTerms(c);
 if(r.kind==='platform_usage'&&r.booking_id){const [[cost]]=await c.execute("SELECT e.id FROM schoolcarebridge_bookings b JOIN finance_expenses e ON e.id=b.platform_expense_id AND e.agency_id=b.operator_agency_id WHERE b.id=? AND e.amount_cents=? AND e.status IN ('approved','scheduled')",[r.booking_id,r.total_cents]);if(!cost)throw fail(409,'Prepare and approve this booking’s platform expense in Finance Operations before paying it.');}
 const account=r.stripe_payment_intent_id?r.stripe_account_id:await merchant(r,c);
 let pi;if(r.stripe_payment_intent_id)pi=await StripePaymentsService.retrievePaymentIntent(r.stripe_payment_intent_id,account);else{pi=await StripePaymentsService.createPaymentIntent({amountCents:Number(r.total_cents),currency:r.currency,connectedAccountId:account,description:`SchoolCareBridge invoice SCB-${r.id}`,metadata:{source:'schoolcarebridge_invoice',scb_invoice_id:String(r.id)},idempotencyKey:`scb-invoice-${r.id}`});await c.execute('UPDATE schoolcarebridge_invoices SET stripe_payment_intent_id=?,stripe_account_id=? WHERE id=?',[pi.id,account,r.id]);}
 await audit(c,user,'payment_started','invoice',r.id);return {clientSecret:pi.client_secret,publishableKey:getStripePublishableKey(),connectedAccountId:account,status:pi.status};
},db);}
export function verifyPayment(invoice,pi,account){if(pi.metadata?.source!=='schoolcarebridge_invoice'||String(pi.metadata.scb_invoice_id)!==String(invoice.id)||pi.id!==invoice.stripe_payment_intent_id||(account||null)!==(invoice.stripe_account_id||null)||pi.currency!==invoice.currency||Number(pi.amount)!==Number(invoice.total_cents)||Number(pi.amount_received)!==Number(invoice.total_cents)||pi.status!=='succeeded')throw fail(409,'Payment evidence does not match this invoice.');}
export async function reconcilePayment(pi,account,db=pool){if(pi.metadata?.source!=='schoolcarebridge_invoice')return false;return transaction(async c=>{const [[r]]=await c.execute('SELECT * FROM schoolcarebridge_invoices WHERE id=? FOR UPDATE',[integer(pi.metadata.scb_invoice_id,1)]);if(!r)throw fail(404,'Invoice unavailable for payment reconciliation.');verifyPayment(r,pi,account);if(r.paid_at)return true;if(r.status!=='open')throw fail(409,'A payment arrived for an invoice requiring review.');await c.execute("UPDATE schoolcarebridge_invoices SET status='paid',paid_at=NOW(),receipt_number=? WHERE id=?",[`SCB-R-${r.id}`,r.id]);if(r.kind==='platform_usage'&&r.booking_id){const [[cost]]=await c.execute('SELECT e.* FROM schoolcarebridge_bookings b JOIN finance_expenses e ON e.id=b.platform_expense_id AND e.agency_id=b.operator_agency_id WHERE b.id=? FOR UPDATE',[r.booking_id]);if(cost&&Number(cost.amount_cents)===Number(r.total_cents)&&['approved','scheduled'].includes(cost.status)){await c.execute("UPDATE finance_expenses SET status='paid',payment_reference=?,payment_date=CURDATE(),revision=revision+1 WHERE id=?",[pi.id,cost.id]);await c.execute("INSERT INTO finance_expense_history (agency_id,expense_id,from_status,to_status,note) VALUES (?,?,?,'paid',?)",[r.operator_agency_id,cost.id,cost.status,`Processor-verified SchoolCareBridge invoice SCB-${r.id}`]);await c.execute("INSERT INTO finance_audit (agency_id,action,object_type,object_id,detail_json) VALUES (?,'payment_verified','expense',?,?)",[r.operator_agency_id,cost.id,JSON.stringify({invoiceId:r.id,paymentIntentId:pi.id})]);}else await audit(c,null,'finance_payment_needs_review','invoice',r.id,{reason:'Linked expense changed after payment initiation; processor payment remains recorded.'});}await audit(c,null,'payment_verified','invoice',r.id,{paymentIntentId:pi.id,amountCents:Number(pi.amount_received)});return true;},db);}
export async function refreshPayment(user,id,db=pool){const r=await invoiceAccess(user,id,{},db);if(r.stripe_payment_intent_id){const pi=await StripePaymentsService.retrievePaymentIntent(r.stripe_payment_intent_id,r.stripe_account_id);if(pi.status==='succeeded')await reconcilePayment(pi,r.stripe_account_id,db);}return publicInvoice(await invoiceAccess(user,id,{},db));}
export async function refundInvoice(user,id,input,db=pool){await requireOperator(user,db);await invoiceAccess(user,id,{platformManage:true},db);if(!String(input.reason||'').trim())throw fail(400,'Document the reason for a full refund.');return transaction(async c=>{const [[r]]=await c.execute('SELECT * FROM schoolcarebridge_invoices WHERE id=? FOR UPDATE',[id]);if(!r.paid_at||!r.stripe_payment_intent_id||!['paid','refund_pending','refund_failed','refunded'].includes(r.status))throw fail(409,'Only a verified paid invoice can be refunded.');if(['refunded','refund_pending'].includes(r.status))return publicInvoice(r);const attempt=Number(r.refund_attempt||0)+1;const refund=await StripePaymentsService.refundPaymentIntent({paymentIntentId:r.stripe_payment_intent_id,amountCents:Number(r.total_cents),connectedAccountId:r.stripe_account_id,idempotencyKey:`scb-full-refund-${r.id}-${attempt}`,metadata:{source:'schoolcarebridge_invoice',scb_invoice_id:String(r.id)}});await c.execute('UPDATE schoolcarebridge_invoices SET status=?,refunded_cents=?,refund_attempt=?,stripe_refund_id=? WHERE id=?',[refund.status==='succeeded'?'refunded':['failed','canceled'].includes(refund.status)?'refund_failed':'refund_pending',refund.status==='succeeded'?r.total_cents:0,attempt,refund.id,r.id]);await audit(c,user,'refund_requested','invoice',r.id,{reason:String(input.reason).slice(0,2000),refundId:refund.id,status:refund.status});return {id:r.id,status:refund.status};},db);}
export async function reconcileRefund(refund,account,db=pool){if(refund.metadata?.source!=='schoolcarebridge_invoice')return false;return transaction(async c=>{const [[r]]=await c.execute('SELECT * FROM schoolcarebridge_invoices WHERE id=? FOR UPDATE',[integer(refund.metadata.scb_invoice_id,1)]);if(!r||r.stripe_payment_intent_id!==refund.payment_intent||(r.stripe_account_id||null)!==(account||null)||Number(refund.amount)!==Number(r.total_cents))throw fail(409,'Refund does not match its invoice.');if(r.stripe_refund_id!==refund.id||r.status==='refunded')return true;if(['failed','canceled'].includes(refund.status))await c.execute("UPDATE schoolcarebridge_invoices SET status='refund_failed' WHERE id=?",[r.id]);if(refund.status==='succeeded'){await c.execute("UPDATE schoolcarebridge_invoices SET status='refunded',refunded_cents=total_cents WHERE id=?",[r.id]);await audit(c,null,'refund_verified','invoice',r.id,{refundId:refund.id});}return true;},db);}
export function invoiceHtml(invoice,t){const r=publicInvoice(invoice),e=escapeHtml,money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(c/100);return `<!doctype html><html lang="en"><meta charset="utf-8"><title>SCB-${r.id}</title><style>body{font:15px/1.6 Arial;max-width:760px;margin:40px auto}table{width:100%;border-collapse:collapse}td,th{padding:10px;border-bottom:1px solid #ccc;text-align:left}@page{size:Letter;margin:.8in}</style><h1>${r.receiptNumber?'Payment receipt':'Invoice'} SCB-${r.id}</h1><p>Issuer: ${e(r.kind==='platform_usage'?t.platformLegalName:t.operatorLegalName)}<br>Debtor organization ID: ${r.debtorAgencyId}<br>Status: ${e(r.status)}<br>Issued: ${e(r.issuedAt)} · Due: ${e(r.dueDate)}</p><table><tr><th>Description</th><th>Amount</th></tr>${r.lines.map(l=>`<tr><td>${e(l.description)}${l.unitDays?` · ${l.unitDays} unit-days / ${l.daysInMonth} days · ${money(l.monthlyUnitCents)} standard monthly · ${l.percentageBps/100}%`:''}</td><td>${money(l.amountCents)}</td></tr>`).join('')}</table><h2>Total ${money(r.totalCents)}</h2>${r.receiptNumber?`<p>Receipt ${e(r.receiptNumber)} · Payment verified ${e(r.paidAt)}<br>Payment reference: ${e(invoice.stripe_payment_intent_id)}<br>Refunded: ${money(r.refundedCents)}</p>`:'<p>This invoice is not a payment receipt. Pay through the authenticated SchoolCareBridge app.</p>'}<p>SchoolCareBridge · A program of MH4Kidz</p></html>`;}
