import pool from '../config/database.js';
import {fail,integer,object,bookingAmounts,calendarDate} from './schoolCareBridgeCommercialPolicy.js';
import {operator,requireOperator,isOperator,terms,requireActiveTerms,transaction,audit} from './schoolCareBridgeCommerce.service.js';
import {financeScope} from './finance/policy.js';
import {createExpense,assignExpense} from './finance/expenses.js';
export const programTypes={original:'MH4Kidz Original',partner:'Community Partner',managed:'SchoolCareBridge Managed',sponsored:'MH4Kidz Sponsored'};
const txt=(s,max=200,required=true)=>{const v=String(s||'').trim();if((required&&!v)||v.length>max)throw fail(400,`Enter text of ${required?'1':'0'}–${max} characters.`);return v;};
const choice=(v,values)=>{if(!values.includes(v))throw fail(400,'Choose a supported option.');return v;};
export function normalizeProgram(b){
 const regions=Array.isArray(b.regions)?b.regions.map(x=>txt(x,120)):String(b.regions||'').split(',').map(x=>x.trim()).filter(Boolean);
 if(!regions.length||regions.length>30)throw fail(400,'Specify 1–30 service regions.');
 if(b.registrationClassId&&b.registrationEventId)throw fail(400,'Link a class or an event, not both.');
 const p={title:txt(b.title),program_type:choice(b.programType,Object.keys(programTypes)),owner_name:txt(b.ownerName),audience:choice(b.audience,['students','parents','staff','school_wide']),description:txt(b.description,8000),delivery_mode:choice(b.deliveryMode,['in_person','virtual','both']),regions_json:JSON.stringify(regions),presenter_name:txt(b.presenterName),presenter_user_id:b.presenterUserId?integer(b.presenterUserId,1):null,presenter_bio:txt(b.presenterBio,4000,false),travel_available:b.travelAvailable===true,duration_minutes:integer(b.durationMinutes,15,1440),capacity:integer(b.capacity,1,100000),funding_mode:choice(b.fundingMode,['cash','grant','free','mixed']),price_cents:b.priceCents==null||b.priceCents===''?null:integer(b.priceCents),sponsor_name:txt(b.sponsorName,200,false)||null,finance_program_id:b.financeProgramId?integer(b.financeProgramId,1):null,registration_class_id:b.registrationClassId?integer(b.registrationClassId,1):null,registration_event_id:b.registrationEventId?integer(b.registrationEventId,1):null,published:b.published===true};
 if(p.program_type==='sponsored'&&!p.sponsor_name)throw fail(400,'Identify the sponsor while preserving the actual program owner and presenter.');
 return p;
}
export async function registrationKey(program,db=pool){
 if(!program.registration_class_id&&!program.registration_event_id)return null;
 const isClass=!!program.registration_class_id;
 const [[r]]=await db.execute(isClass?`SELECT il.public_key FROM learning_program_classes c JOIN intake_links il ON il.learning_class_id=c.id AND il.is_active=1 WHERE c.id=? AND c.is_active=1 AND c.status='active' AND c.registration_eligible=1 AND (c.enrollment_opens_at IS NULL OR c.enrollment_opens_at<=NOW()) AND (c.enrollment_closes_at IS NULL OR c.enrollment_closes_at>=NOW()) AND (il.company_event_id IS NULL OR il.company_event_id=0) ORDER BY il.id DESC LIMIT 1`:`SELECT il.public_key FROM company_events c JOIN intake_links il ON il.company_event_id=c.id AND il.is_active=1 WHERE c.id=? AND c.is_active=1 AND c.registration_eligible=1 AND c.public_registration_status IN ('open','waitlist') AND c.ends_at>=NOW() ORDER BY il.id DESC LIMIT 1`,[program.registration_class_id||program.registration_event_id]);
 return r?.public_key||null;
}
export function publicProgram(p){return {id:p.id,title:p.title,programType:p.program_type,typeLabel:programTypes[p.program_type],ownerName:p.owner_name,audience:p.audience,description:p.description,deliveryMode:p.delivery_mode,regions:object(p.regions_json),presenterName:p.presenter_name,presenterBio:p.presenter_bio||'',travelAvailable:!!p.travel_available,durationMinutes:p.duration_minutes,capacity:p.capacity,fundingMode:p.funding_mode,priceCents:p.price_cents==null?null:Number(p.price_cents),sponsorName:p.sponsor_name||null};}
export async function publicCatalog(db=pool){const a=await operator(db),[rows]=await db.execute('SELECT * FROM schoolcarebridge_programs WHERE operator_agency_id=? AND published=1 ORDER BY title,id',[a.id]);const programs=[];for(const p of rows)programs.push({...publicProgram(p),registrationPublicKey:await registrationKey(p,db)});return programs;}
export async function saveProgram(user,id,input,db=pool){const a=await requireOperator(user,db),p=normalizeProgram(input);return transaction(async c=>{
 if(p.finance_program_id){const [[f]]=await c.execute("SELECT id FROM finance_programs WHERE id=? AND agency_id=? AND status='active'",[p.finance_program_id,a.id]);if(!f)throw fail(400,'Select a current MH4Kidz finance program.');}
 if(p.presenter_user_id){const [[u]]=await c.execute('SELECT id FROM users WHERE id=? AND is_active=1',[p.presenter_user_id]);if(!u)throw fail(400,'Select an active presenter account.');}
 // Only an operator-owned or participating partner-owned source may be advertised.
 if(p.registration_class_id||p.registration_event_id){const [[source]]=await c.execute(p.registration_class_id?`SELECT COALESCE(oa.agency_id,lp.organization_id) AS agency_id FROM learning_program_classes lp LEFT JOIN organization_affiliations oa ON oa.organization_id=lp.organization_id AND oa.is_active=1 LEFT JOIN schoolcarebridge_partners sp ON sp.agency_id=oa.agency_id AND sp.is_active=1 WHERE lp.id=? AND (lp.organization_id=? OR oa.agency_id=? OR sp.agency_id IS NOT NULL) ORDER BY (oa.agency_id=?) DESC LIMIT 1`:'SELECT agency_id FROM company_events WHERE id=?',p.registration_class_id?[p.registration_class_id,a.id,a.id,a.id]:[p.registration_event_id]);if(!source)throw fail(400,'Registration source not found.');if(Number(source.agency_id)!==Number(a.id)){const [[partner]]=await c.execute('SELECT agency_id FROM schoolcarebridge_partners WHERE agency_id=? AND is_active=1',[source.agency_id]);if(!partner)throw fail(400,'Registration must belong to MH4Kidz or an active partner.');}if(p.published&&!await registrationKey(p,c))throw fail(409,'The linked registration is not currently open and eligible.');}
 const keys=Object.keys(p);let programId=id;
 if(id){const [r]=await c.execute(`UPDATE schoolcarebridge_programs SET ${keys.map(k=>k+'=?').join(',')},revision=revision+1 WHERE id=? AND operator_agency_id=? AND revision=?`,[...Object.values(p),id,a.id,integer(input.revision,1)]);if(!r.affectedRows)throw fail(409,'Program changed. Refresh before editing.');}
 else {const [r]=await c.execute(`INSERT INTO schoolcarebridge_programs (operator_agency_id,${keys.join(',')}) VALUES (?,${keys.map(()=>'?').join(',')})`,[a.id,...Object.values(p)]);programId=r.insertId;}
 await audit(c,user,'program_saved','program',programId,{published:p.published});return {id:programId};
},db);}
export function bookingWindow(b){
 for(const k of ['start','end'])if(!/^\d{4}-\d{2}-\d{2}T.*(?:Z|[+-]\d{2}:\d{2})$/.test(b[k]||'')||!Number.isFinite(Date.parse(b[k])))throw fail(400,'Include an explicit UTC offset in booking times.');
 const start=new Date(b.start),end=new Date(b.end);if(end<=start||end-start>86400000||start<=new Date())throw fail(400,'Choose a future booking lasting no more than one day.');
 try{new Intl.DateTimeFormat('en-US',{timeZone:b.timezone}).format(start);}catch{throw fail(400,'Choose a valid timezone.');}
 return {start:start.toISOString().slice(0,19).replace('T',' '),end:end.toISOString().slice(0,19).replace('T',' ')};
}
export async function createBooking(user,input,db=pool){const a=await operator(db),window=bookingWindow(input),key=txt(input.requestKey,80);if(!/^[a-zA-Z0-9_-]{12,80}$/.test(key))throw fail(400,'A stable request reference is required.');return transaction(async c=>{
 const [[old]]=await c.execute('SELECT id FROM schoolcarebridge_bookings WHERE requester_user_id=? AND request_key=?',[user.id,key]);if(old)return {id:old.id,reused:true};
 const [[school]]=await c.execute("SELECT id FROM agencies WHERE id=? AND organization_type='school' AND is_active=1 AND COALESCE(is_archived,0)=0",[integer(input.schoolId,1)]);if(!school)throw fail(404,'The school is unavailable.');
 const [[p]]=await c.execute('SELECT * FROM schoolcarebridge_programs WHERE id=? AND operator_agency_id=? AND published=1',[integer(input.programId,1),a.id]);if(!p)throw fail(404,'This program is unavailable.');
 if(integer(input.attendance,1,100000)>p.capacity)throw fail(400,'Attendance exceeds the published capacity. Ask MH4Kidz to arrange a larger session.');
 const region=txt(input.region,120),local=object(p.regions_json).some(r=>r.toLowerCase()===region.toLowerCase());
 if(!local&&p.delivery_mode==='in_person'&&(!p.travel_available||input.travelRequested!==true))throw fail(400,'This presenter requires a travel inquiry for your region.');
 if(input.travelRequested===true&&!p.travel_available)throw fail(400,'Travel is not offered for this program.');
 const [r]=await c.execute('INSERT INTO schoolcarebridge_bookings (program_id,operator_agency_id,requester_user_id,school_agency_id,request_key,requested_start,requested_end,timezone,region,location,attendance,language,accommodations,travel_requested,funding_requested,presenter_user_id) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[p.id,a.id,user.id,integer(input.schoolId,1),key,window.start,window.end,txt(input.timezone,80),region,txt(input.location,500),input.attendance,txt(input.language,120,false),txt(input.accommodations,2000,false),input.travelRequested===true,choice(input.fundingRequested,['cash','grant','partial','free']),p.presenter_user_id]);await audit(c,user,'booking_requested','booking',r.insertId);return {id:r.insertId};
},db);}
export async function bookingAccess(user,id,db=pool){const [[b]]=await db.execute('SELECT b.*,p.title,p.finance_program_id,p.presenter_name,s.name AS school_name FROM schoolcarebridge_bookings b JOIN schoolcarebridge_programs p ON p.id=b.program_id JOIN agencies s ON s.id=b.school_agency_id WHERE b.id=?',[integer(id,1)]);if(!b)throw fail(404,'Booking not found.');if(Number(b.requester_user_id)!==Number(user.id)&&!await isOperator(user,db))throw fail(403,'You do not have access to this booking.');return {...b,quote:object(b.quote_json),completion:object(b.completion_json)};}
export async function quoteBooking(user,id,input,db=pool){await requireOperator(user,db);return transaction(async c=>{const [[b]]=await c.execute('SELECT b.*,p.title,p.presenter_name,p.finance_program_id FROM schoolcarebridge_bookings b JOIN schoolcarebridge_programs p ON p.id=b.program_id WHERE b.id=? FOR UPDATE',[id]);if(!b||!['requested','quoted'].includes(b.status)||b.revision!==Number(input.revision))throw fail(409,'Only the current unaccepted request can be quoted.');const t=await terms(c);if(t.terms.bookingPlatformBps==null||t.terms.bookingOperatorBps==null)throw fail(409,'Configure the proposed program shares first.');const totals=bookingAmounts({...input,platformBps:t.terms.bookingPlatformBps,operatorBps:t.terms.bookingOperatorBps});const expires=calendarDate(input.expiresDate);if(expires<new Date().toISOString().slice(0,10))throw fail(400,'Choose a current or future quote expiry.');const quote={...totals,termsRevision:t.revision,platformBps:t.terms.bookingPlatformBps,operatorBps:t.terms.bookingOperatorBps,title:b.title,presenterName:b.presenter_name,presenterUserId:b.presenter_user_id,financeProgramId:input.financeProgramId?integer(input.financeProgramId,1):b.finance_program_id||null,expiresDate:expires,cancellationTerms:txt(input.cancellationTerms,3000),travelTerms:txt(input.travelTerms,2000,false),presenterPaymentTerms:txt(input.presenterPaymentTerms,2000),fundingNotes:txt(input.fundingNotes,2000,false),scope:txt(input.scope,4000)};if(totals.fundingCents&&!quote.fundingNotes)throw fail(400,'Describe the requested grant or subsidy.');await c.execute("UPDATE schoolcarebridge_bookings SET status='quoted',quote_json=?,quoted_by_user_id=?,quoted_at=NOW(),revision=revision+1 WHERE id=?",[JSON.stringify(quote),user.id,id]);await audit(c,user,'quote_issued','booking',id,{revision:b.revision+1,totals});return {id};},db);}
export async function acceptQuote(user,id,input,db=pool){const visible=await bookingAccess(user,id,db);if(Number(visible.requester_user_id)!==Number(user.id))throw fail(403,'The requesting school representative must accept the quote.');if(input.authorizedToBook!==true)throw fail(400,'Confirm authority to accept this booking for your school.');return transaction(async c=>{const [[b]]=await c.execute('SELECT * FROM schoolcarebridge_bookings WHERE id=? FOR UPDATE',[id]),q=object(b.quote_json);if(b.status!=='quoted'||b.revision!==Number(input.revision)||q.expiresDate<new Date().toISOString().slice(0,10))throw fail(409,'This quote expired or changed. Request an updated quote.');await c.execute("UPDATE schoolcarebridge_bookings SET status='accepted',accepted_by_user_id=?,accepted_at=NOW(),revision=revision+1 WHERE id=?",[user.id,id]);await audit(c,user,'quote_accepted','booking',id,{quoteRevision:b.revision});return {id};},db);}
// Uses the existing finance expense workflow. Never self-approves or marks a payout paid.
export async function prepareBookingExpenses(user,id,input,db=pool){const a=await requireOperator(user,db),b=await bookingAccess(user,id,db);if(!['accepted','confirmed','completed'].includes(b.status))throw fail(409,'Accept the booking quote before preparing its costs.');const scope=await financeScope(user,a.id,{manage:true},db),programId=integer(b.quote.financeProgramId||b.finance_program_id,1);const [[presenterMember]]=b.presenter_user_id?await db.execute('SELECT user_id FROM user_agencies WHERE agency_id=? AND user_id=? AND is_active=1',[a.id,b.presenter_user_id]):[[]];const outputs={};for(const [side,amount] of [['presenter',b.quote.presenterCents],['platform',b.quote.platformCents]]){if(!amount)continue;const result=await createExpense(scope,{requestKey:`scb_booking_${id}_${side}`,programId,title:`SchoolCareBridge ${b.title} — ${side}`,description:`Booking SCB-B-${id}; ${side==='presenter'?b.quote.presenterName:'Plot Twist Co'}; ${b.quote.presenterPaymentTerms}`,kind:'vendor',staffUserId:side==='presenter'?presenterMember?.user_id||null:null,amountCents:amount,expenseDate:String(b.requested_start instanceof Date?b.requested_start.toISOString():b.requested_start).slice(0,10),category:side==='presenter'?'Program delivery':'Platform service'},db);outputs[side]=result.id;
 if(input[side+'AllocationId']){const [[expense]]=await db.execute('SELECT revision,status FROM finance_expenses WHERE id=? AND agency_id=?',[result.id,a.id]);if(['draft','submitted','in_review','needs_info'].includes(expense.status))await assignExpense(scope,result.id,{revision:expense.revision,splits:[{allocationId:integer(input[side+'AllocationId'],1),amountCents:amount}]},db);}
 }
 await db.execute('UPDATE schoolcarebridge_bookings SET presenter_expense_id=?,platform_expense_id=? WHERE id=?',[outputs.presenter||null,outputs.platform||null,id]);await audit(db,user,'finance_costs_prepared','booking',id,outputs);return outputs;
}
export async function confirmBooking(user,id,input,db=pool){const a=await requireOperator(user,db);return transaction(async c=>{
 // Serialize operator bookings so two concurrent confirmations cannot reserve one presenter.
 await c.execute('SELECT id FROM agencies WHERE id=? FOR UPDATE',[a.id]);const [[b]]=await c.execute('SELECT b.*,p.presenter_name,p.finance_program_id FROM schoolcarebridge_bookings b JOIN schoolcarebridge_programs p ON p.id=b.program_id WHERE b.id=? FOR UPDATE',[id]);if(!b||b.status!=='accepted'||b.revision!==Number(input.revision))throw fail(409,'Refresh the accepted booking before confirming.');const q=object(b.quote_json),t=await requireActiveTerms(c);if(q.termsRevision!==t.revision)throw fail(409,'Commercial terms changed; prepare a new booking quote.');if(new Date().toISOString().slice(0,10)<t.terms.rolloutDate)throw fail(409,'Paid program activation begins on the contracted rollout date.');if(input.presenterAvailabilityConfirmed!==true)throw fail(400,'Confirm availability with the presenter, including their outside calendar.');
 const [[conflict]]=await c.execute("SELECT b.id FROM schoolcarebridge_bookings b JOIN schoolcarebridge_programs p ON p.id=b.program_id WHERE b.id<>? AND b.status IN ('confirmed','completed') AND b.requested_start<? AND b.requested_end>? AND ((? IS NOT NULL AND b.presenter_user_id=?) OR (? IS NULL AND p.presenter_name=?)) LIMIT 1",[id,b.requested_end,b.requested_start,b.presenter_user_id,b.presenter_user_id,b.presenter_user_id,b.presenter_name]);if(conflict)throw fail(409,'This presenter already has an overlapping confirmed booking.');
 if(q.fundingCents){for(const [expenseId,amount] of [[b.presenter_expense_id,q.presenterCents],[b.platform_expense_id,q.platformCents]]){if(!amount)continue;const [[cost]]=await c.execute("SELECT id FROM finance_expenses WHERE id=? AND agency_id=? AND amount_cents=? AND status IN ('approved','scheduled','paid')",[expenseId||0,a.id,amount]);if(!cost)throw fail(409,'Approve the presenter and platform costs in Finance Operations before confirming a subsidized booking.');}}
 if(q.schoolCents){await c.execute("INSERT INTO schoolcarebridge_invoices (operator_agency_id,kind,billing_key,debtor_agency_id,booking_id,terms_revision,lines_json,total_cents,due_date,created_by_user_id) VALUES (?,'booking',?,?,?,?,?,?,DATE_ADD(CURDATE(),INTERVAL ? DAY),?)",[a.id,`booking:${id}`,b.school_agency_id,id,t.revision,JSON.stringify([{description:`${q.title} — accepted school contribution (delivery and approved travel)`,amountCents:q.schoolCents}]),q.schoolCents,t.terms.paymentDueDays,user.id]);}
 await c.execute("UPDATE schoolcarebridge_bookings SET status='confirmed',revision=revision+1 WHERE id=?",[id]);await audit(c,user,'booking_confirmed','booking',id,{schoolCents:q.schoolCents});return {id};
},db);}
export async function completeBooking(user,id,input,db=pool){const a=await requireOperator(user,db);return transaction(async c=>{const [[b]]=await c.execute('SELECT * FROM schoolcarebridge_bookings WHERE id=? FOR UPDATE',[id]);if(!b||b.status!=='confirmed'||b.revision!==Number(input.revision))throw fail(409,'Only a current confirmed booking can be completed.');if(new Date(b.requested_end)>new Date())throw fail(409,'The scheduled delivery has not ended.');const q=object(b.quote_json),completion={attendance:integer(input.attendance,0,100000),summary:txt(input.summary,4000),satisfaction:input.satisfaction==null?null:integer(input.satisfaction,1,5),recordedBy:user.id};if(q.platformCents){await c.execute("INSERT INTO schoolcarebridge_invoices (operator_agency_id,kind,billing_key,debtor_agency_id,booking_id,terms_revision,lines_json,total_cents,due_date,created_by_user_id) VALUES (?,'platform_usage',?,?,?,?,?,?,DATE_ADD(CURDATE(),INTERVAL 30 DAY),?)",[a.id,`booking:${id}:platform`,a.id,id,q.termsRevision,JSON.stringify([{description:`Program platform fee — ${q.title}; ${q.platformBps/100}% of ${q.serviceCents/100} USD delivery fee`,amountCents:q.platformCents}]),q.platformCents,user.id]);}await c.execute("UPDATE schoolcarebridge_bookings SET status='completed',completion_json=?,revision=revision+1 WHERE id=?",[JSON.stringify(completion),id]);await audit(c,user,'booking_completed','booking',id,completion);return {id};},db);}
export async function cancelBooking(user,id,input,db=pool){const b=await bookingAccess(user,id,db),manager=await isOperator(user,db);if(!manager&&!['requested','quoted','accepted'].includes(b.status))throw fail(403,'Ask MH4Kidz to apply the accepted cancellation terms.');return transaction(async c=>{const [[current]]=await c.execute('SELECT * FROM schoolcarebridge_bookings WHERE id=? FOR UPDATE',[id]);if(!current||current.revision!==Number(input.revision)||['cancelled','completed'].includes(current.status))throw fail(409,'Booking changed or cannot be cancelled.');const [[invoice]]=await c.execute("SELECT id FROM schoolcarebridge_invoices WHERE booking_id=? AND status NOT IN ('refunded','void') LIMIT 1",[id]);if(invoice)throw fail(409,'Refund or void the booking invoice before closing this booking.');for(const expId of [current.presenter_expense_id,current.platform_expense_id].filter(Boolean)){const [[cost]]=await c.execute("SELECT id FROM finance_expenses WHERE id=? AND status IN ('approved','scheduled')",[expId]);if(cost)throw fail(409,'Resolve committed finance expenses before cancellation.');}await c.execute("UPDATE schoolcarebridge_bookings SET status='cancelled',revision=revision+1 WHERE id=?",[id]);await audit(c,user,'booking_cancelled','booking',id,{reason:txt(input.reason,2000)});return {id};},db);}
