import {base, services, coachingRecord} from './content.mjs';
const url = section => `${base}/${section}`;
const arrow = '<span aria-hidden="true">↗</span>';
const eyebrow = text => `<p class="eyebrow">${text}</p>`;

export function coachingRecordBand() {
 return `<section class="coaching-record wrap" aria-label="Michael’s collegiate coaching experience"><div>${eyebrow('Experience behind the coaching')}<h2>${coachingRecord.title}</h2><p>${coachingRecord.detail}</p></div><dl>${coachingRecord.stats.map(([n,label])=>`<div><dt>${n}</dt><dd>${label}</dd></div>`).join('')}</dl></section>`;
}
export function coachingCards() {
 return `<div class="coaching-grid">${services.filter(s=>s.group==='coaching').map((s,i)=>`<a class="coaching-card" href="${url(s.key)}"><span class="eyebrow">${['I’m a runner','We’re exploring college athletics','I coach a college program'][i]}</span><h3>${s.title}</h3><p>${s.body}</p><span class="text-link">Explore ${s.short.toLowerCase()} ${arrow}</span></a>`).join('')}</div>`;
}
export function coachingHome() {
 return `<section class="section soft"><div class="wrap"><div class="section-heading"><div>${eyebrow('For runners, student-athletes & college coaches')}<h2>Experience on the track.<br><em>Perspective for what’s next.</em></h2></div><p>Seven years leading Division II men’s and women’s cross country and track & field. Three ways to put that experience to work.</p></div>${coachingCards()}</div></section>${coachingRecordBand()}`;
}
export function coachingPage() {
 return `<section class="page-hero wrap">${eyebrow('Running. College fit. Recruiting strategy.')}<h1>Your next chapter.<br>A coach in your corner.</h1><p class="intro">Whether you are finding your stride, exploring college athletics, or building a collegiate program, start with the support that fits your next step.</p></section><section class="wrap">${coachingCards()}</section>${coachingRecordBand()}<section class="section soft"><div class="wrap two-col"><div>${eyebrow('A collegiate coach. A personal approach.')}<h2>Big-picture perspective.<br><em>Practical next steps.</em></h2></div><div><p>I coached at the Division II level for seven years, leading men’s and women’s cross country and track & field. That work connects athlete development, recruiting, team culture, and the decisions that shape a student’s experience.</p><p>Today I bring that perspective to individual runners, student-athletes and families, and college coaches. You do not have to be an elite runner to work with me.</p><a class="button secondary" href="${url('contact')}?package=coaching">Find your starting point ${arrow}</a></div></div></section>`;
}
export function coachingNotes(service) {
 if(service.key==='running-coaching') return `<div class="note"><h3>Coaching that fits the runner.</h3><p>Beginner or experienced, we agree on a realistic goal and a format that fits. Coaching is virtual unless an in-person session is explicitly arranged. For teens, a parent/guardian coordinates and we respect existing school or team training.</p><p>Running coaching is not medical care or rehabilitation. If pain, injury, or a health condition affects training, get appropriate guidance from a qualified health professional before beginning or changing the plan.</p></div>`;
 if(service.key==='college-planning') return `<div class="note"><h3>More than a division label or a roster spot.</h3><p>We compare academic programs, team environment, training expectations, student support, and realistic family cost. Practice asking coaches about their program and describing your interests and athletic experience in your own voice.</p><p>A parent or guardian starts the inquiry for anyone under 18. We agree on adult involvement, student participation, communication, and consent before work begins.</p></div><div class="note"><h3>Good decisions use current information.</h3><p>Confirm admissions requirements, costs, aid, and athletic opportunities directly with each school. Your school counselor and the institution’s athletics compliance office remain important partners. Coaching does not promise admission, a scholarship, eligibility, or a roster spot.</p><ul class="resource-links"><li><a href="https://bigfuture.collegeboard.org/college-search">College Board’s college search ${arrow}</a></li><li><a href="https://collegescorecard.ed.gov/">U.S. Department of Education College Scorecard ${arrow}</a></li><li><a href="https://web3.ncaa.org/ecwr3/">NCAA Eligibility Center ${arrow}</a></li></ul></div>`;
 if(service.key==='college-coach-consulting') return `<div class="note"><h3>Find talent. Build a system around the search.</h3><p>We can map relevant meets and public results, identify relationship-building channels, define evaluation criteria, and organize your authorized prospect information into a useful staff workflow. Custom dashboards or AI-assisted workflow tools can be scoped separately.</p></div><div class="note"><h3>Your program. Your compliance process.</h3><p>Your staff and compliance office approve recruiting calendars, contact practices, data use, and implementation. This service does not contact athletes on your behalf, certify eligibility, represent recruits, or promise commitments.</p><p>Program consulting and family coaching are separate engagements. I do not use private family information as a recruiting list or privately represent both sides of the same recruiting decision. Any potential conflict is discussed before an engagement.</p></div>`;
 return '';
}
