export const base = '/michael';
export const origin = 'https://plottwisthq.com';
export const email = 'michael@plottwistco.com';
export const coachingRecord = {
 title: 'Seven years leading collegiate runners.',
 detail: 'Division II head coach · Men’s & women’s cross country and track & field',
 stats: [['7', 'years as head coach'], ['30+', 'All-Americans'], ['140', 'All-Conference athletes'], ['9', 'Conference Athletes of the Year']]
};
export const pages = {
  '': ['Build what comes next.', 'Consulting and coaching with Michael V. Mendez: private practice growth, AI apps, running coaching, and college decisions. Creator and orchestrator of Plot Twist HQ.'],
  services: ['The right support for your next step.', 'Choose business consulting, private practice growth, running coaching, or college decision support for student-athletes and families.'],
  coaching: ['Your next chapter. A coach in your corner.', 'Running and student-athlete college coaching with Michael V. Mendez: seven years as a Division II head coach in men’s and women’s cross country and track & field.'],
  'running-coaching': ['Find your stride. Build your confidence.', 'Learn to run, build consistency, or pursue a race goal with a former Division II cross country and track & field head coach.'],
  'college-planning': ['Find your fit. In the classroom and on the team.', 'College fit and recruiting-readiness coaching for student-athletes and families, with a former Division II cross country and track & field head coach.'],
  'college-coach-consulting': ['Find the right talent. Build your program.', 'Recruiting strategy and talent-identification consulting for collegiate coaches, drawing on Michael V. Mendez’s seven years as a Division II head coach.'],
  'private-practice': ['Your practice. A stronger foundation.', 'Launch a private practice with a clear offer, client journey, technology plan, and practical operating systems.'],
  'scale-your-practice': ['A thriving practice. Room to grow.', 'Scale your private practice from solo to group, strengthen referrals and operations, and plan new locations or service delivery channels.'],
  'ai-development': ['From “what if” to something that works.', 'AI product strategy and hands-on application development, from workflow discovery to a scoped build and launch.'],
  'business-growth': ['Grow the business beyond you.', 'Build repeatable systems, clearer roles, partnerships, and a measurable plan to scale your service business.'],
  nonprofits: ['Your mission deserves a wider reach.', 'Help your nonprofit expand beyond its doors with a 90-day capacity, partnership, and program expansion engagement.'],
  packages: ['A clear scope. A practical investment.', 'Explore running and college coaching packages alongside private practice launch, AI products, business growth, and nonprofit expansion consulting.'],
  work: ['Built from the work itself.', 'Explore Plot Twist HQ, the working platform created by Michael V. Mendez, and his approach to turning operational problems into useful software.'],
  about: ['A builder. A coach. In your corner.', 'Meet Michael V. Mendez: creator and orchestrator of Plot Twist HQ, seven years as a Division II head coach, and a partner for your next chapter.'],
  contact: ['Tell me what comes next for you.', 'Request a free fit conversation about business consulting, running coaching, or college decisions for your family.'],
  pay: ['Your next step, all in one place.', 'Review your consulting offer and pay securely, or request a proposal for the package that fits your goals.'],
  privacy: ['Your information, treated with care.', 'How Michael V. Mendez Consulting handles website inquiries and payment information.'],
  terms: ['Clear expectations from the start.', 'Consulting scope, payment, scheduling, project ownership, and how engagements work.']
};
export const offers = [
  {key:'recruiting-strategy',group:'recruiting',name:'Recruiting Strategy Sprint',price:150000,period:'4 weeks · 3 working sessions',feeLabel:'starting project fee',audience:'For collegiate coaches building a stronger recruiting process.',body:'Turn your program’s needs into a focused prospecting, evaluation, and outreach strategy.',items:['Program goals, roster needs, and recruiting-process review','Ideal-prospect criteria and a talent-source research map','Evaluation rubric, outreach sequence, and follow-up workflow','90-day recruiting action plan with owners and measures'],result:'A repeatable way to identify promising prospects, prioritize effort, and move the right conversations forward.',limit:'One collegiate program and one recruiting cycle. No purchased prospect list, guaranteed signings, athlete representation, or outreach on your behalf. Staff and compliance approval are required before implementation; custom tools and ongoing research are separate.',sessions:3},
  {key:'running-reset',group:'running',name:'Running Reset Session',price:12500,period:'One 60-minute coaching session',feeLabel:'session fee',audience:'For a runner who wants a clear place to start.',body:'Talk through your experience, goals, and schedule, then identify the next practical step in your running.',items:['Goals and current-routine review','One 60-minute virtual coaching session','A written two-week starter outline','Pacing, consistency, and recovery habits to focus on'],result:'A manageable starting point and a better understanding of how to approach your runs.',limit:'One runner. No ongoing plan updates, medical assessment, injury rehabilitation, or in-person session is included. Parent/guardian coordinates for minors.',sessions:1},
  {key:'running-plan',group:'running',name:'Find Your Stride · 8 Weeks',price:45000,period:'8 weeks · 3 coaching calls',feeLabel:'starting package fee',audience:'For beginners, returning runners, and runners with a goal.',body:'Build a running routine around your life, with a personal plan and regular accountability.',items:['60-minute kickoff and an eight-week running plan','One written check-in and plan review each week','30-minute midpoint and wrap-up calls','A next-phase plan for your routine or race goal'],result:'A repeatable training rhythm, clearer priorities, and support as you put the plan into practice.',limit:'One runner and one agreed goal. Race readiness and session format are confirmed before enrollment. No unlimited messaging, automatic renewal, medical care, or guaranteed finish time.',sessions:3},
  {key:'college-session',group:'college',name:'Student-Athlete Direction Session',price:17500,period:'One 60-minute family session',feeLabel:'session fee',audience:'For a student-athlete or family unsure where to begin.',body:'Make room for the student’s goals and turn a big college question into a few useful next steps.',items:['Brief goals and priorities questionnaire','One 60-minute student/family conversation','An academic, athletic, and personal fit worksheet','Written next steps and questions to research'],result:'A clearer starting point for the college conversation, without the pressure to have every answer.',limit:'One student, with a parent/guardian coordinating if under 18. Does not include a researched school list, application editing, or financial-aid advice.',sessions:1},
  {key:'college-roadmap',group:'college',name:'Student-Athlete College Fit Roadmap',price:90000,period:'6 weeks · 4 working sessions',feeLabel:'starting package fee',audience:'For student-athletes and families exploring college sport.',body:'Compare schools and team environments, prepare to communicate with coaches, and make a thoughtful college decision.',items:['Academic, athletic, personal, and budget priorities','A research shortlist of up to 8 schools with reasons to explore','Athletic profile and coach-outreach preparation','School comparison, visit questions, and decision timeline'],result:'A realistic college search and outreach plan that considers life as both a student and an athlete.',limit:'One student and one planning cycle. Research uses public information and family-provided priorities. Application editing, test prep, financial-aid advising, eligibility certification, and recruiting representation are not included. The student sends their own outreach. No admission, scholarship, or roster guarantees.',sessions:4},
  {key:'scale',name:'Practice Scaling Sprint',price:500000,period:'8 weeks · 6 working sessions',audience:'For established practices ready for their next stage.',body:'Grow beyond a full caseload with an operating model that supports your team and the people you serve.',items:['Practice capacity, referral, and client-flow assessment','Solo-to-group or team-expansion model and role map','One priority intake, scheduling, or billing workflow redesign','90-day growth plan with hiring assumptions and measures'],result:'A practical plan to grow the practice without making you the bottleneck.',limit:'One practice and one growth scenario. Recruiting, payer credentialing, legal review, new-location setup, and implementation are separate.',sessions:6},
  {key:'clarity',name:'Clarity Session',price:25000,period:'One 60-minute session',audience:'One decision. A useful next step.',body:'Work through a specific question before committing to a bigger project.',items:['A brief pre-session questionnaire','One 60-minute working session','A written decision summary and next steps'],result:'Leave with a priority and an action you can take.',limit:'A focused advisory session. Implementation is scoped separately.',sessions:1},
  {key:'practice',name:'Practice Launch Sprint',price:250000,period:'4 weeks · 4 working sessions',audience:'For clinicians and coaches opening a practice.',body:'Connect your offer, client experience, and operations into a realistic launch plan.',items:['Service positioning and pricing worksheet','Inquiry-to-payment client journey','Technology and workflow recommendations','A prioritized launch checklist and handoff'],result:'Know what to launch, what to set up, and in what order.',limit:'One practice and one primary service model. Filing, credentialing, legal review, and software subscriptions are separate.',sessions:4},
  {key:'ai',name:'AI Product Blueprint',price:500000,period:'6 weeks · 6 working sessions',audience:'For a product idea that needs a build plan.',body:'Define a useful first version before investing in custom development.',items:['User and workflow discovery','Product requirements and key screen flows','Architecture, data, and AI review plan','Build phases, priorities, and an implementation estimate'],result:'A blueprint you can use with Michael or another development team.',limit:'One product concept. A production application is a separately scoped build.',sessions:6},
  {key:'growth',name:'Growth Systems Sprint',price:500000,period:'8 weeks · 6 working sessions',audience:'For a business that has outgrown its systems.',body:'Find the operational constraints and design a model your team can repeat.',items:['Capacity and bottleneck assessment','Roles, handoffs, and priority workflow map','One expansion or partnership opportunity plan','90-day execution plan with owners and measures'],result:'A clearer operating model and a plan for the next stage.',limit:'One business unit and one growth priority. Hiring, rollout, and ongoing management are scoped separately.',sessions:6},
  {key:'impact',name:'Impact Expansion Lab',price:750000,period:'90 days · 6 leadership working sessions',audience:'For nonprofits ready to reach beyond their doors.',body:'Translate a strong local program into a responsible expansion plan.',items:['Readiness assessment and up to 3 stakeholder interviews','Repeatable program and delivery model','Partnership map and pilot budget assumptions','Board-ready roadmap, measures, and pilot recommendation'],result:'A decision-ready path to reaching more people without outrunning your capacity.',limit:'One program and one expansion scenario. Grant writing, fundraising, travel, and pilot delivery are separate.',sessions:6}
];
export const services = [
 {key:'college-coach-consulting',group:'coaching',number:'08',title:'Recruit with a clearer strategy.',short:'College coach consulting',tag:'For collegiate coaches & programs',body:'Identify the talent your program needs and build a recruiting process your staff can sustain.',offer:'recruiting-strategy',fit:'Collegiate head coaches, assistants, and program leaders—especially cross country and track & field programs—who want a stronger recruiting strategy and clearer execution.',question:'How do you find the right prospects—and turn research into a repeatable process?',outcomes:['A prospect profile connected to roster needs and program identity','A research strategy across public results, meets, clubs, and coach relationships','A consistent evaluation rubric and prioritized prospect workflow','Clearer outreach, follow-up, staff responsibilities, and progress measures'],detail:'I understand recruiting from the perspective of someone who spent seven years leading a Division II program. We look at what your team needs, where to look for talent, how to assess fit, and how to keep promising conversations from getting lost. The work can include recruiting-market research methods, a staff workflow, and an organized way to use the information you are authorized to hold. Your institution retains its recruiting decisions and compliance responsibilities.'},
 {key:'running-coaching',group:'coaching',number:'06',title:'Run with a plan. Find your stride.',short:'Running coaching',tag:'Running Coaching with Michael · All paces welcome',body:'Learn the basics, build consistency, and work toward a running goal with a coach who helps you put the pieces together.',offer:'running-plan',starter:'running-reset',fit:'Adults starting out, getting back to running, or pursuing a race goal; teen runners with parent/guardian involvement and coordination with their existing team coach.',question:'What would make running feel more doable—and more purposeful?',outcomes:['A goal and running routine matched to your experience and schedule','A better understanding of pacing, consistency, and recovery','A personal plan with regular review and accountability','Confidence about what to work on next'],detail:'I spent seven years as a Division II head coach for men’s and women’s cross country and track & field. My coaching record includes 30+ All-Americans, 140 All-Conference athletes, and nine Conference Athletes of the Year. You do not need to be a collegiate athlete to benefit from that experience. We start with where you are, not where you think you should be. Together we build a practical rhythm, review how it is going, and adjust the plan around your life. This is running education and coaching, not medical diagnosis or injury rehabilitation.'},
 {key:'college-planning',group:'coaching',number:'07',title:'Find your college—and your team.',short:'Student-athlete college fit',tag:'College Fit & Recruiting Readiness',body:'Help your student-athlete find the right academic and athletic environment, prepare for conversations with coaches, and choose a school with clarity.',offer:'college-roadmap',starter:'college-session',fit:'Student-athletes and families beginning or narrowing a college search, especially runners in cross country and track & field. Younger athletes can begin with low-pressure exploration; students outside those sports can discuss fit before enrolling.',question:'Where can your student-athlete thrive—not just make a roster?',outcomes:['A clearer picture of academic, athletic, and personal priorities','A way to compare programs, team culture, support, and family costs','An athletic profile, outreach preparation, and questions for coaches','A manageable school shortlist, visit plan, and decision timeline'],detail:'Having led collegiate cross country and track & field programs, I bring a coach’s perspective to the questions families may not know to ask. We look at academics, training expectations, communication, team culture, support, and realistic cost—not just a division label or a roster spot. We can prepare an athletic profile and thoughtful outreach in the student’s own voice. Club sport, community college, or a different pathway can belong in the conversation too. Admissions, aid, eligibility, and roster decisions remain with the relevant schools and governing bodies.'},
 {key:'scale-your-practice',number:'02',title:'Scale your private practice.',short:'Practice scaling',tag:'From a full caseload to a stronger practice',body:'Grow from solo to group, strengthen your team, and expand access without making you the bottleneck.',offer:'scale',fit:'Established clinicians, group practice owners, and coaches ready to grow an existing practice, team, or delivery model.',question:'How do you grow the practice without everything depending on you?',outcomes:['A realistic solo-to-group or team expansion plan','Clearer referrals, intake, scheduling, and billing handoffs','Hiring and capacity assumptions for the next stage','A 90-day growth roadmap with owners and measures'],detail:'We look at the practice you already have: where clients come from, how quickly they connect with services, how your team works, and what limits your capacity. Together we evaluate one growth scenario — adding practitioners, expanding a service, reaching a new community, or preparing for another location — and define the systems it needs. Implementation and specialized legal or credentialing work are scoped separately.'},
 {key:'private-practice',number:'01',title:'Launch your private practice.',short:'Private practice',tag:'Start with a strong foundation',body:'Shape the offer, client experience, and operating systems behind the practice you want to run.',offer:'practice',fit:'Clinicians, coaches, and independent practitioners preparing to open or simplify a private practice.',question:'What needs to be true before you welcome your first client?',outcomes:['A service offer people understand','A workable inquiry, intake, scheduling, and payment journey','A practical technology stack and launch sequence'],detail:'We work through the business decisions together: who you serve, how the service is delivered, what the client experiences, and which tools keep it running. You leave with an organized launch plan and a clear view of the decisions that need a licensed legal, tax, or clinical professional.'},
 {key:'ai-development',number:'03',title:'Turn an idea into a useful app.',short:'AI & app development',tag:'Build around a real problem',body:'Go from scattered workflows to a focused product, with AI used where it actually helps.',offer:'ai',fit:'Founders and service organizations with a workflow problem, product idea, or tool that needs to become usable.',question:'What should your first version do exceptionally well?',outcomes:['A defined user, problem, and first release','A plan for data, permissions, AI review, and integrations','A scoped path from prototype to launch'],detail:'Start with discovery and a blueprint, or bring an existing specification for review. Hands-on development is available as a separate engagement with milestones, acceptance criteria, deployment, and handoff agreed up front. Hosting, model usage, maintenance, and third-party subscriptions are priced separately.'},
 {key:'business-growth',number:'04',title:'Scale without carrying it all.',short:'Business growth',tag:'Build capacity for what comes next',body:'Create repeatable workflows, clearer ownership, and a growth plan your team can execute.',offer:'growth',fit:'Service businesses and founder-led organizations whose next stage needs more than additional effort.',question:'What has to change for your business to grow beyond you?',outcomes:['A map of capacity limits and operational friction','Repeatable processes with named owners','An expansion plan with a budget, milestones, and measures'],detail:'We examine how the work moves through the business, where it gets stuck, and what the next opportunity would require. That may mean a new service, partnership, delivery channel, or location. The plan connects ambition to staffing, systems, and resources.'},
 {key:'nonprofits',number:'05',title:'Take your mission further.',short:'Nonprofit expansion',tag:'Expand beyond your doors',body:'Turn a successful local program into a model that can reach more people through partners, new channels, and stronger systems.',offer:'impact',fit:'Executive directors, boards, and program leaders with a proven service and an opportunity to expand its reach.',question:'How can more people benefit from the work you already do well?',outcomes:['A repeatable program with clear delivery requirements','Partnership and distribution options that fit your mission','A board-ready pilot plan with capacity and cost assumptions'],detail:'Growth might mean a school partnership, a community-based delivery model, a training program, or a digital extension of your services. We assess readiness, design one expansion scenario, and define a pilot your leadership can evaluate. The engagement supports organizational decisions; funding and impact outcomes are never assumed.'}
];
export const faqs = [
 ['Do you coach runners and help with college decisions too?', 'Yes. Running Coaching with Michael helps people build a running routine and work toward a goal. College Fit & Recruiting Readiness helps student-athletes and families explore academic and athletic options, prepare for coach conversations, and make thoughtful decisions. Each has its own scope and pricing; neither requires a business consulting package.'],
 ['Can my teen work with you?', 'Yes, with a parent or guardian involved. An adult starts the inquiry, and we agree on the scope, participation, communication, and consent before coaching begins. Students help shape their own goals. Please do not submit a child’s name, date of birth, school records, or medical information in the public form.'],
 ['Where should I start?', 'If you know the decision you need to make, choose a Clarity Session. If the project is still taking shape, request a free 20-minute fit conversation. We will discuss the goal, timing, and which kind of support makes sense.'],
 ['Will you build the app, or only advise?', 'Both are available. The AI Product Blueprint defines the product and build plan. Hands-on development is quoted separately after scope, data needs, integrations, and acceptance criteria are understood.'],
 ['Can a nonprofit or board hire you?', 'Yes. The Impact Expansion Lab is designed for nonprofit leadership. You can request a written proposal, a phased scope, or information for your procurement process before making a decision.'],
 ['What happens after I inquire?', 'Michael reviews your goals and follows up by email to arrange a conversation. If there is a fit, you receive a written scope, timeline, and payment terms. Work begins after those are agreed.'],
 ['Is ongoing support available?', 'Yes. Ongoing advisory, implementation, and Plot Twist Co. management support can be scoped around the work and level of involvement you need. They are separate from the fixed packages.'],
 ['Is Plot Twist HQ included?', 'Consulting does not automatically include a software subscription or a management contract. If the platform fits your needs, its access, setup, and costs are discussed separately. You can also use the plan with your existing tools.']
];

services.sort((a,b) => a.number.localeCompare(b.number));
const offerOrder = ['clarity','practice','scale','ai','growth','impact','running-reset','running-plan','college-session','college-roadmap','recruiting-strategy'];
offers.sort((a,b) => offerOrder.indexOf(a.key) - offerOrder.indexOf(b.key));
