export const base = '/michael';
export const origin = 'https://plottwisthq.com';
export const email = 'michael@plottwistco.com';
export const pages = {
  '': ['Build what comes next.', 'Private practice launch and scaling, AI app development, and business and nonprofit growth with Michael V. Mendez, creator of Plot Twist HQ.'],
  services: ['Thoughtful strategy. Useful things built.', 'Explore private practice launch and scaling, AI app development, business scaling, and nonprofit expansion consulting.'],
  'private-practice': ['Your practice. A stronger foundation.', 'Launch a private practice with a clear offer, client journey, technology plan, and practical operating systems.'],
  'scale-your-practice': ['A thriving practice. Room to grow.', 'Scale your private practice from solo to group, strengthen referrals and operations, and plan new locations or service delivery channels.'],
  'ai-development': ['From “what if” to something that works.', 'AI product strategy and hands-on application development, from workflow discovery to a scoped build and launch.'],
  'business-growth': ['Grow the business beyond you.', 'Build repeatable systems, clearer roles, partnerships, and a measurable plan to scale your service business.'],
  nonprofits: ['Your mission deserves a wider reach.', 'Help your nonprofit expand beyond its doors with a 90-day capacity, partnership, and program expansion engagement.'],
  packages: ['A clear scope. A practical investment.', 'Compare consulting packages for private practice launch, AI products, business growth, and nonprofit expansion.'],
  work: ['Built from the work itself.', 'Explore Plot Twist HQ, the working platform created by Michael V. Mendez, and his approach to turning operational problems into useful software.'],
  about: ['A builder in your corner.', 'Meet Michael V. Mendez: creator of Plot Twist HQ and a consultant for people building practices, products, and mission-driven organizations.'],
  contact: ['Tell me what you want to build.', 'Request a free fit conversation with Michael about your practice, AI application, business, or nonprofit.'],
  pay: ['Your next step, all in one place.', 'Review your consulting offer and pay securely, or request a proposal for the package that fits your goals.'],
  privacy: ['Your information, treated with care.', 'How Michael V. Mendez Consulting handles website inquiries and payment information.'],
  terms: ['Clear expectations from the start.', 'Consulting scope, payment, scheduling, project ownership, and how engagements work.']
};
export const offers = [
  {key:'scale',name:'Practice Scaling Sprint',price:500000,period:'8 weeks · 6 working sessions',audience:'For established practices ready for their next stage.',body:'Grow beyond a full caseload with an operating model that supports your team and the people you serve.',items:['Practice capacity, referral, and client-flow assessment','Solo-to-group or team-expansion model and role map','One priority intake, scheduling, or billing workflow redesign','90-day growth plan with hiring assumptions and measures'],result:'A practical plan to grow the practice without making you the bottleneck.',limit:'One practice and one growth scenario. Recruiting, payer credentialing, legal review, new-location setup, and implementation are separate.',sessions:6},
  {key:'clarity',name:'Clarity Session',price:25000,period:'One 60-minute session',audience:'One decision. A useful next step.',body:'Work through a specific question before committing to a bigger project.',items:['A brief pre-session questionnaire','One 60-minute working session','A written decision summary and next steps'],result:'Leave with a priority and an action you can take.',limit:'A focused advisory session. Implementation is scoped separately.',sessions:1},
  {key:'practice',name:'Practice Launch Sprint',price:250000,period:'4 weeks · 4 working sessions',audience:'For clinicians and coaches opening a practice.',body:'Connect your offer, client experience, and operations into a realistic launch plan.',items:['Service positioning and pricing worksheet','Inquiry-to-payment client journey','Technology and workflow recommendations','A prioritized launch checklist and handoff'],result:'Know what to launch, what to set up, and in what order.',limit:'One practice and one primary service model. Filing, credentialing, legal review, and software subscriptions are separate.',sessions:4},
  {key:'ai',name:'AI Product Blueprint',price:500000,period:'6 weeks · 6 working sessions',audience:'For a product idea that needs a build plan.',body:'Define a useful first version before investing in custom development.',items:['User and workflow discovery','Product requirements and key screen flows','Architecture, data, and AI review plan','Build phases, priorities, and an implementation estimate'],result:'A blueprint you can use with Michael or another development team.',limit:'One product concept. A production application is a separately scoped build.',sessions:6},
  {key:'growth',name:'Growth Systems Sprint',price:500000,period:'8 weeks · 6 working sessions',audience:'For a business that has outgrown its systems.',body:'Find the operational constraints and design a model your team can repeat.',items:['Capacity and bottleneck assessment','Roles, handoffs, and priority workflow map','One expansion or partnership opportunity plan','90-day execution plan with owners and measures'],result:'A clearer operating model and a plan for the next stage.',limit:'One business unit and one growth priority. Hiring, rollout, and ongoing management are scoped separately.',sessions:6},
  {key:'impact',name:'Impact Expansion Lab',price:750000,period:'90 days · 6 leadership working sessions',audience:'For nonprofits ready to reach beyond their doors.',body:'Translate a strong local program into a responsible expansion plan.',items:['Readiness assessment and up to 3 stakeholder interviews','Repeatable program and delivery model','Partnership map and pilot budget assumptions','Board-ready roadmap, measures, and pilot recommendation'],result:'A decision-ready path to reaching more people without outrunning your capacity.',limit:'One program and one expansion scenario. Grant writing, fundraising, travel, and pilot delivery are separate.',sessions:6}
];
export const services = [
 {key:'scale-your-practice',number:'02',title:'Scale your private practice.',short:'Practice scaling',tag:'From a full caseload to a stronger practice',body:'Grow from solo to group, strengthen your team, and expand access without making you the bottleneck.',offer:'scale',fit:'Established clinicians, group practice owners, and coaches ready to grow an existing practice, team, or delivery model.',question:'How do you grow the practice without everything depending on you?',outcomes:['A realistic solo-to-group or team expansion plan','Clearer referrals, intake, scheduling, and billing handoffs','Hiring and capacity assumptions for the next stage','A 90-day growth roadmap with owners and measures'],detail:'We look at the practice you already have: where clients come from, how quickly they connect with services, how your team works, and what limits your capacity. Together we evaluate one growth scenario — adding practitioners, expanding a service, reaching a new community, or preparing for another location — and define the systems it needs. Implementation and specialized legal or credentialing work are scoped separately.'},
 {key:'private-practice',number:'01',title:'Launch your private practice.',short:'Private practice',tag:'Start with a strong foundation',body:'Shape the offer, client experience, and operating systems behind the practice you want to run.',offer:'practice',fit:'Clinicians, coaches, and independent practitioners preparing to open or simplify a private practice.',question:'What needs to be true before you welcome your first client?',outcomes:['A service offer people understand','A workable inquiry, intake, scheduling, and payment journey','A practical technology stack and launch sequence'],detail:'We work through the business decisions together: who you serve, how the service is delivered, what the client experiences, and which tools keep it running. You leave with an organized launch plan and a clear view of the decisions that need a licensed legal, tax, or clinical professional.'},
 {key:'ai-development',number:'03',title:'Turn an idea into a useful app.',short:'AI & app development',tag:'Build around a real problem',body:'Go from scattered workflows to a focused product, with AI used where it actually helps.',offer:'ai',fit:'Founders and service organizations with a workflow problem, product idea, or tool that needs to become usable.',question:'What should your first version do exceptionally well?',outcomes:['A defined user, problem, and first release','A plan for data, permissions, AI review, and integrations','A scoped path from prototype to launch'],detail:'Start with discovery and a blueprint, or bring an existing specification for review. Hands-on development is available as a separate engagement with milestones, acceptance criteria, deployment, and handoff agreed up front. Hosting, model usage, maintenance, and third-party subscriptions are priced separately.'},
 {key:'business-growth',number:'04',title:'Scale without carrying it all.',short:'Business growth',tag:'Build capacity for what comes next',body:'Create repeatable workflows, clearer ownership, and a growth plan your team can execute.',offer:'growth',fit:'Service businesses and founder-led organizations whose next stage needs more than additional effort.',question:'What has to change for your business to grow beyond you?',outcomes:['A map of capacity limits and operational friction','Repeatable processes with named owners','An expansion plan with a budget, milestones, and measures'],detail:'We examine how the work moves through the business, where it gets stuck, and what the next opportunity would require. That may mean a new service, partnership, delivery channel, or location. The plan connects ambition to staffing, systems, and resources.'},
 {key:'nonprofits',number:'05',title:'Take your mission further.',short:'Nonprofit expansion',tag:'Expand beyond your doors',body:'Turn a successful local program into a model that can reach more people through partners, new channels, and stronger systems.',offer:'impact',fit:'Executive directors, boards, and program leaders with a proven service and an opportunity to expand its reach.',question:'How can more people benefit from the work you already do well?',outcomes:['A repeatable program with clear delivery requirements','Partnership and distribution options that fit your mission','A board-ready pilot plan with capacity and cost assumptions'],detail:'Growth might mean a school partnership, a community-based delivery model, a training program, or a digital extension of your services. We assess readiness, design one expansion scenario, and define a pilot your leadership can evaluate. The engagement supports organizational decisions; funding and impact outcomes are never assumed.'}
];
export const faqs = [
 ['Where should I start?', 'If you know the decision you need to make, choose a Clarity Session. If the project is still taking shape, request a free 20-minute fit conversation. We will discuss the goal, timing, and which kind of support makes sense.'],
 ['Will you build the app, or only advise?', 'Both are available. The AI Product Blueprint defines the product and build plan. Hands-on development is quoted separately after scope, data needs, integrations, and acceptance criteria are understood.'],
 ['Can a nonprofit or board hire you?', 'Yes. The Impact Expansion Lab is designed for nonprofit leadership. You can request a written proposal, a phased scope, or information for your procurement process before making a decision.'],
 ['What happens after I inquire?', 'Michael reviews your goals and follows up by email to arrange a conversation. If there is a fit, you receive a written scope, timeline, and payment terms. Work begins after those are agreed.'],
 ['Is ongoing support available?', 'Yes. Ongoing advisory, implementation, and Plot Twist Co. management support can be scoped around the work and level of involvement you need. They are separate from the fixed packages.'],
 ['Is Plot Twist HQ included?', 'Consulting does not automatically include a software subscription or a management contract. If the platform fits your needs, its access, setup, and costs are discussed separately. You can also use the plan with your existing tools.']
];

services.sort((a,b) => a.number.localeCompare(b.number));
offers.sort((a,b) => ['clarity','practice','scale','ai','growth','impact'].indexOf(a.key) - ['clarity','practice','scale','ai','growth','impact'].indexOf(b.key));
