import {SUPERVISORY_REVIEW_CONSIDERATION} from './compensationHandbookClarifications.js';
export const PRIOR_TERMS_REPLACEMENT = 'For work and benefits on or after this amendment’s prospective effective date, this amendment replaces all financial, compensation and employee-benefit terms stated in the prior employment agreement. Those matters are governed by this amendment, its individual rate schedule and the Workplace Handbook policies it incorporates. All other terms of the prior agreement and all other agency policies remain in effect. Wages, reimbursements and leave already earned before the change remain protected.';
export const EXTRA_DUTY_PAY_TERMS = 'Separate written compensation agreements for additional duties are permitted under this amendment. The employee and an authorized agency representative may agree to extra-duty compensation in a separate signed writing or an electronic exchange that clearly records both parties’ acceptance, without issuing a new full employment amendment or publishing the individual terms in the Workplace Handbook. The writing must identify the duties, rate or payment amount, payment basis, effective date and duration or end conditions, and be retained with the employee’s compensation records for payroll. Separately documented extra-duty pay arrangements remain in effect unless expressly changed in writing; this amendment’s standard service rates do not replace those distinct arrangements. The separate terms control only the identified additional duties and do not otherwise change the employee’s service rates, benefits or other agreement terms. Record all compensable time and apply applicable minimum-wage and overtime requirements. Changes apply prospectively and do not reduce compensation already earned.';
export const ELECTRONIC_SIGNATURE_NOTICE = 'The employee signs electronically using the signature section at the bottom of this Provider Update. The agency’s authorized representative countersigns electronically. The app records each signature and signing date, and the completed signed copy is retained in the employee’s My Documents for later viewing and download. The prospective effective-date rules above apply.';
export function updateAmendmentExecutionTerms(html) {
 let result=String(html||'')
  .replace('This amendment replaces conflicting compensation and accrual terms in the prior employment agreement for work on or after the agreed effective date. All other nonconflicting agreement terms remain in effect.',PRIOR_TERMS_REPLACEMENT)
  .replace('Other existing vacation/PTO entitlements are unchanged.','Previously earned leave balances remain protected.')
  .replace('Employee signature/date: ____________________. ITSCO authorized representative signature/date: ____________________. Agreed effective date: ____________________.',ELECTRONIC_SIGNATURE_NOTICE);
 result=result.replace(/(<h3>10\. Compensation-level expectations and review<\/h3>)([\s\S]*?)(?=<h3>|$)/,(_,heading,body)=>heading+body+(body.includes(SUPERVISORY_REVIEW_CONSIDERATION)?'':'<p>'+SUPERVISORY_REVIEW_CONSIDERATION+'</p>'));
 result=result.replace(/(<h3>2\. Individual category, level and rates<\/h3>)([\s\S]*?)(?=<h3>|$)/,(_,heading,body)=>heading+body+(body.includes(EXTRA_DUTY_PAY_TERMS)?'':'<p>'+EXTRA_DUTY_PAY_TERMS+'</p>'));
 return result;
}
export function splitFinalSignature(html) {
 const pattern=/<h3>\d+\. Employee acknowledgment and signatures<\/h3>[\s\S]*?(?=<h3>|$)/;
 const match=String(html).match(pattern);
 return {clauses:match?String(html).replace(pattern,''):String(html),signature:match?.[0]||'<h3>Employee acknowledgment and electronic signatures</h3><p>'+ELECTRONIC_SIGNATURE_NOTICE+'</p>'};
}
