import {MEDICAID_GROUP_RATIONALE} from './medicaidGroupRationale.js';
import {RESTRICTED_CODES,restrictedCodeTable,formatHandbookQuantity,CODE_USE_POLICY} from './handbookCodePresentation.js';
import {PAY_RATE_SCOPE} from './payRateLabels.js';
const e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dollars=v=>Number.isFinite(Number(v))?'$'+Number(v).toFixed(2):'See individual schedule';
export const SIMPLE_HANDBOOK_CLAUSE='The Workplace Handbook lists the services ITSCO permits, their pay credits or units, and any services currently paused. Follow those rules and obtain any required approval before providing a service or starting a group. The handbook also explains the minimum-workload policy, leave benefits and eligible expenses. Changes will be communicated before they apply; pay and leave already earned are protected.';
export const SCHOOL_MILEAGE_CLAUSE='While assigned to a school, I am eligible for mileage reimbursement when my travel meets the Workplace Handbook’s “School mileage reimbursement” policy. That policy determines eligible trips, reimbursement rates, documentation and submission requirements. ITSCO may change the policy prospectively with notice; changes do not remove reimbursement already earned or required by law.';
export const TRAINING_LEAVE_CLAUSE='I may earn and request paid training leave for approved professional development under the Workplace Handbook’s Training Leave policy, in the section “Training leave — separate from sick leave,” and its Continuing Education requirements. This earned benefit is separate from sick leave and pays at my applicable sick-leave payment rate. The handbook controls the accrual basis and rate, balance cap, documentation, approval, carryover and use requirements. I may view my balance and submit a request with supporting documentation in My Payroll.';
export const SCHOOL_SUPPORT_PURPOSE='This earned benefit is earmarked to help school-assigned providers cover time lost to weather-related school closures or disruptions and missed client sessions, including client absences or cancellations. It is separate from sick leave and Training PTO, and is paid at the employee’s applicable support-activity rate.';
export const SCHOOL_SUPPORT_CLAUSE='While assigned to a school, I may earn and request school support activity hours under the Workplace Handbook’s “School support activity hours” policy. '+SCHOOL_SUPPORT_PURPOSE+' The handbook controls qualifying accruals, the balance cap, eligibility, requests and payroll approval. I may view my earned balance and request hours for a use date in My Payroll. Hours are deducted only after payroll approves and applies the payment. This benefit does not automatically pay every missed appointment or replace payment for actual work performed.';
export function amendmentBenefitReferences({schoolAssigned}={}) {
 const school=schoolAssigned!==false;
 return '<section class="amendment-benefits"><h3>Benefits and handbook policies</h3><h4>Earned training benefit</h4><p>'+TRAINING_LEAVE_CLAUSE+'</p>'+(school?'<h4>Earned school support benefit — missed sessions</h4><p>'+SCHOOL_SUPPORT_CLAUSE+'</p><h4>School mileage reimbursement</h4><p>'+SCHOOL_MILEAGE_CLAUSE+' Submit eligible travel through My Payroll → Mileage.</p>':'')+'</section>';
}
export const SUPERVISORY_REVIEW_CONSIDERATION='Supervisory reviews, clinical documentation reviews and formal performance evaluations are also considered when determining whether an employee meets the expectations for their compensation level. Findings must be documented, reviewed in context and discussed with the employee.';
export function workloadHandbookSection({rates=[],thresholds={}}={}){
 const min=Number(thresholds.tier1MinWeekly??6);
 const table=[1,2,3].map(category=>{const rows=rates.filter(r=>Number(r.category)===category);const first=rows[0];return `<tr><th>Category ${category}</th><td>${first?dollars(first.credit_rate_probation):'Confirm schedule'} per clinical credit</td><td>${first?dollars(first.hcode_rate_probation):'Confirm schedule'} per H-code direct-hour equivalent</td><td>${category===1?'$18 at Levels 1–2; $20 at Levels 3–5':category===2?'$22':'$24'} per hour</td><td>$18 per hour</td></tr>`}).join('');
 return {slug:'minimum-workload-rates-and-tracking',title:'Minimum-workload rates and tracking',bodyHtml:`<p>The minimum-workload rate is the reduced service rate that applies when an employee is below Tier 1 after applicable grace periods and waivers. It is separate from the employee’s compensation category and level.</p><h2>Current threshold</h2><p>Tier 1 begins at an average of <strong>${min} qualifying service credits per week (${min*2} per two-week pay period)</strong>. The app uses the current period’s qualifying credits and applicable prior-period tier grace to determine the effective benefit tier. Minimum-workload rates apply only when that effective tier remains below Tier 1 and no waiver applies. Indirect or support hours do not automatically count as clinical session credits.</p><h2>Minimum-workload rate schedule</h2><table><thead><tr><th>Category</th><th>Clinical Session Rate</th><th>Direct Care Rate</th><th>Indirect pay</th><th>Support activity pay</th></tr></thead><tbody>${table}</tbody></table><p>These are the current category rates; the employee’s completed individual schedule identifies their applicable rates and authorized services. For Categories 2 and 3, the H-code indirect allowance continues at the applicable indirect rate. Category 1 reports actual indirect time separately.</p><h2>60-day amendment waiver</h2><p>Existing employees receive a 60-calendar-day waiver beginning on their amendment’s prospective effective date. For an October 10, 2026 effective date, the waiver runs through December 8; December 9 is the first possible minimum-workload date. This does not restart probation. A recorded individual waiver also prevents the reduction while effective.</p><h2>What the app tracks</h2><p>Payroll retains the service dates, qualifying credits, current and prior-period tiers, grace status, amendment effective date, waiver end date, any individual waiver, and the category/level rate used. Staff can review their tier and pay calculation in My Payroll and request corrections. A correction to the record must be reviewed before any payroll adjustment is applied. The policy and threshold in effect for the service date govern; future changes require advance notice and preserve earned pay.</p>`};
}
export function codeReferenceSection(rules=[]){
 const rows=kind=>rules.filter(r=>!RESTRICTED_CODES.includes(r.service_code)).filter(r=>kind==='clinical'?/^9\d/.test(r.service_code)&&r.category==='direct':/^H\d/.test(r.service_code)).map(r=>{
  const code=String(r.service_code),paused=['90853'].includes(code),zero=!(Number(r.credit_value)>0);
  const basis=kind==='clinical'?`${formatHandbookQuantity(r.credit_value)} clinical credit per recorded service`:['H0031','H0032'].includes(code)?'Actual service minutes ÷ 60':Number(r.pay_divisor)===4?'Verified units ÷ 4':Number(r.pay_divisor)===60?'Documented minutes ÷ 60':'Individual mapping review required';
  return `<tr><th>${e(code)}</th><td>${e(basis)}</td><td>${paused?'Group moratorium — written exception required':zero?'No automatic credit payment; individual review required':kind==='clinical'?'Listed for eligible clinical services; scope and payer rules apply':'Listed mapping; service, setting and payer approval still required'}</td></tr>`}).join('');
 return {slug:'service-code-approval-and-credit-reference',title:'Service codes: Clinical Session Rate and Direct Care Rate',bodyHtml:`<p>${PAY_RATE_SCOPE}</p><p>Use this reference with your individual pay schedule. A code in a payroll mapping is not permission to perform every service under that code. Services must fit your credentials, supervision, client plan and payer requirements. Unlisted services require written review before use. Group use of any code remains subject to the separate moratorium.</p><h2>Clinical Session Rate — approved 9-series codes and credits</h2><p>Clinical session pay equals assigned clinical credits multiplied by your Clinical Session Rate. A qualifying 90837 earns 1.00 credit; 90834 earns 0.75; 90832 earns 0.50. Credits measure compensation, not actual hours. Codes such as 99414–99416 used for separately recorded supervision/administrative time are not clinical psychotherapy credits merely because they begin with 9.</p><table><thead><tr><th>Code</th><th>Compensation mapping</th><th>Agency status</th></tr></thead><tbody>${rows('clinical')}</tbody></table><h2>Direct Care Rate — approved H-codes and quantities</h2><p>The Colorado Billing &amp; Compensation Appendix explains unit boundaries and indirect allowances. During the external-EHR period, 15-minute-unit services use verified units; encounter-billed H0031/H0032 use actual documented service minutes for employee pay. Billing quantities must still follow the applicable payer’s rules. Other saved mappings below require verification of their billing basis; they do not convert a per-diem or encounter claim into timed claim units.</p><table><thead><tr><th>Code</th><th>Saved employee-pay quantity</th><th>Agency status</th></tr></thead><tbody>${rows('hcode')}</tbody></table>${restrictedCodeTable()}<h2>How quantities are categorized</h2><p><strong>Clinical credit:</strong> a code-specific employee-pay value. <strong>Timed unit:</strong> a payer-defined increment, such as 15 minutes; four approved 15-minute units equal one compensation hour. <strong>Encounter:</strong> one service, regardless of whether employee pay is calculated from documented minutes. <strong>Per diem:</strong> a day-based claim, requiring its own approved pay mapping. <strong>Actual work:</strong> elapsed compensable time recorded for wage and leave reconciliation. These measures must not be substituted for one another.</p>`};
}
export const GROUP_POLICY_HTML=CODE_USE_POLICY+`<h2>Current group moratorium, including 90853</h2><p>New provider-initiated groups are paused practice-wide, including psychotherapy groups billed under 90853 and groups using H-codes. Approved Skill Builders programming may continue within its existing authorization. Other groups require a written exception before advertising, enrolling or scheduling. Coordinate safe continuity of care for existing clients; this policy does not direct abrupt cancellation of care.</p><h2>Submitting a group proposal</h2><p>Staff may propose a group to Michael and Rachel. Include its clinical purpose, participant needs and acuity, payer/RAE coverage, proposed codes, treatment-plan requirements, curriculum, staffing and supervision, schedule, expected attendance, supplies and all preparation, documentation, delivery and cleanup time. Support and billing must confirm eligibility, authorizations and the applicable reimbursement and billing restrictions.</p><h2>Compensation and wage requirements</h2><p>A proposal will not be approved if there is a reasonable likelihood that the compensation plan would fail to pay any employee at least the applicable minimum wage for all compensable work. Include low attendance, cancellations, preparation and follow-up time in the budget. ITSCO must fund any legally required wage or overtime adjustment even if reimbursement is less than expected. An employee cannot agree to waive these protections.</p><p>Compensation different from an employee’s usual rates may be set in an individual written agreement before the work begins. That agreement must state the work, pay method and rates, and comply with applicable minimum wage, overtime, recordkeeping and other employment requirements. Payer denials, delayed payment or low attendance do not cancel wages already earned.</p>`+MEDICAID_GROUP_RATIONALE;
export const SCHOOL_MILEAGE_SECTION={slug:'school-mileage-reimbursement',title:'School mileage reimbursement',bodyHtml:`<p>${SCHOOL_MILEAGE_CLAUSE}</p><p>Record the travel date, assigned school, originating office, eligible route and miles in My Payroll → Mileage. Use the school-travel option and the assigned office; explain any manual-distance correction. Personal commuting is not automatically an eligible business trip. The applicable handbook policy and approved claim determine reimbursable miles.</p><p>The currently saved tier rates are $0.00 per mile at Tier 1, $0.35 at Tier 2 and $0.70 at Tier 3. Payroll reviews eligibility and the applicable tier before applying reimbursement. A zero optional benefit rate does not remove any reimbursement required by law. Staff may request review of a missing route, incorrect distance or eligibility determination.</p>`};
export const TRAINING_LEAVE_SECTION={slug:'training-leave-benefit',title:'Training leave — separate from sick leave',bodyHtml:`<p>Training PTO is paid time earned for approved professional development and training. All hours and service-credit equivalents that qualify for sick-leave accrual also qualify for training accrual, including fee-for-service and salaried employees’ eligible work. The rate is <strong>0.25 training hour per 30 qualifying hours or credits</strong>. Use the same documented qualifying basis as sick leave, including applicable clinical-credit equivalents; do not add an equivalent twice.</p><p>Training PTO is restricted to approved training and may not be converted to general PTO. It pays at the employee’s applicable sick-leave payment rate for the use date. Required employer training remains paid work even if this benefit has no available balance.</p><h2>Tracking, cap and ADP handoff</h2><p>People Operations enters or confirms the current ADP training balance in the app, together with the last completed pay period included in that balance. The app then accrues subsequent eligible periods without counting imported hours again. Staff view their balance and requests in My Payroll. Unused training hours carry forward until used. Accrual pauses at a <strong>20-hour balance cap</strong> and resumes after approved use; a cap does not erase an existing balance.</p><h2>Requesting Training PTO</h2><p>In My Payroll, choose Training PTO, enter the training date and hours, provide a brief description, enter the training cost and upload a receipt, signup confirmation or proof of participation. People Operations may request further participation documentation. ITSCO may deny a request if sufficient documentation is not provided. The balance is deducted only when payroll approves the request and applies its payment. Pending or denied requests do not reduce the earned balance. A separate expense reimbursement requires its own approval; reporting a course cost does not automatically create a second payment.</p><p>See Continuing Education in the Employee Benefits Overview for additional approval and reimbursement requirements. Training leave is separate from protected sick leave and school support activity hours.</p>`};
export const SCHOOL_SUPPORT_SECTION={slug:'school-service-support-time',title:'School support activity hours',bodyHtml:`<p>School-assigned employees earn a separate bank of <strong>support activity hours</strong>. All work hours and service-credit equivalents that qualify for sick-leave accrual count toward this bank while school-assigned, including eligible work outside schools. The rate is <strong>2 support activity hours per 25 qualifying hours or credits</strong>. Use the same documented qualifying basis as sick leave and count each component once. Thirty qualifying hours earn 2.4 support activity hours. The bank is separate from sick leave and Training PTO.</p><h2>Purpose — weather disruptions and missed sessions</h2><p>${SCHOOL_SUPPORT_PURPOSE}</p><p>Payment is limited to earned available hours and the handbook’s request and payroll-approval requirements. It is not an automatic payment for every missed appointment and does not replace wages for work actually performed. Existing earned balances and previously approved uses remain protected.</p><h2>Balance and use</h2><p>The app displays the balance as support activity hours, such as “2 support activity hours” or “10 support activity hours.” Accrual pauses at a <strong>20-hour balance cap</strong> and resumes after approved use. Track earnings by calendar year, January–December, but preserve earned unused balances rather than forfeiting them at year-end. Because use requires a date rather than a qualifying event, the applicable earned-vacation protections apply regardless of the bank’s name.</p><p>In My Payroll, choose Request support activity hours and enter the use date and number of hours. No explanation or receipt is required. Payroll checks the balance, applicable support-activity rate and payment period. Only approval and successful application to payroll deduct the hours. Pending or denied requests do not reduce the earned balance. Pay equals approved hours multiplied by the employee’s applicable support-activity hourly rate.</p><p>The app retains source periods, qualifying hours, accruals, approvals and deductions for audit. The balance will not be sent to ADP as a leave bank; payments still appear in normal payroll, tax and wage records. This benefit replaces future school Medicaid no-show compensation from its configured transition date, while preserving amounts earned under the previous policy. Do not claim both benefits for the same event.</p>`};

export const FUNDING_NEUTRAL_PAY_CLAUSE='Beginning on this amendment’s effective date, I will be compensated at the applicable rates in my individual compensation schedule for the services and duties I perform, regardless of the payment or funding source. This includes insurance, self-pay, grants, iMatter and other externally funded programs or contracts. My compensation is based on the approved service, credits or hours and assigned duties, rather than a percentage of the amount billed, collected or reimbursed. For work covered by this amendment, these terms replace prior funding-specific percentage or revenue-sharing compensation arrangements. Applicable approved differentials and separately stated role or duty rates continue to apply. This change applies prospectively after the required signatures and does not reduce compensation already earned.';
export const FUNDING_NEUTRAL_PAY_SECTION={slug:'compensation-regardless-of-funding-source',title:'Consistent compensation across funding sources',bodyHtml:`<p>${FUNDING_NEUTRAL_PAY_CLAUSE}</p><h2>Rationale</h2><p>Funding arrangements have changed over time, and some external contracts have omitted provider-compensation terms or applied them inconsistently. Using each employee’s agreed service and duty rates provides a consistent basis for compensation across programs. Differences in a program’s reimbursement do not create an automatic increase or decrease in the employee’s rate.</p><p>For example, a covered 1.00-credit clinical service pays the employee’s agreed per-credit rate whether funded by insurance, a grant or iMatter. It is not paid as 50% of a program’s reimbursement under this amendment. Salaried employees remain subject to their salary agreements. Approved supervision, mentoring and other assigned-duty rates remain governed by the employee’s individual schedule. Any separate group-work compensation must be agreed in writing under the group-review policy.</p><p>Payroll must retain the prior arrangement for earlier service dates and apply the new method only from the completed amendment’s prospective effective date. Editing the handbook alone does not change an existing signed agreement or activate a percentage-pay override.</p>`};
export function addFundingNeutralClause(html){
 const text=String(html||'');if(text.includes('Compensation regardless of funding source</h3>'))return text;
 const signature=/<h3>(\d+)\. Employee acknowledgment and signatures<\/h3>/;
 if(signature.test(text))return text.replace(signature,(_,n)=>'<h3>'+n+'. Compensation regardless of funding source</h3><p>'+FUNDING_NEUTRAL_PAY_CLAUSE+'</p><h3>'+(Number(n)+1)+'. Employee acknowledgment and signatures</h3>');
 return text+'<h3>Compensation regardless of funding source</h3><p>'+FUNDING_NEUTRAL_PAY_CLAUSE+'</p>';
}

export const HEALTH_INSURANCE_CLAUSE='If I am eligible for and enroll in agency-sponsored health insurance, the agency contribution is calculated using the employee-only premium and the contribution percentage or amount applicable to my benefit eligibility, as described in the app’s My Benefits → Health Insurance section and the Workplace Handbook. Electing spouse, child or family coverage does not increase the agency contribution. I am responsible for my share of the employee-only premium and the full additional premium for any enrolled dependents. Dependent enrollment remains subject to the health plan’s eligibility and enrollment rules. The governing plan documents and applicable law control coverage and administration.';
export const HEALTH_INSURANCE_SECTION={
 slug:'health-insurance-employee-only-contribution',
 title:'Health Insurance — employee-only employer contribution',
 bodyHtml:'<h2>Basis of the agency contribution</h2><p>For eligible employees enrolled in agency-sponsored health insurance, the agency contribution is based on the premium for employee-only coverage and the contribution percentage or amount applicable to the employee’s benefit eligibility. Enrollment in employee-plus-spouse, employee-plus-child or family coverage does not increase the agency contribution. The agency does not contribute toward the additional cost of dependent coverage.</p><h2>Employee responsibility and dependent enrollment</h2><p>The employee pays the portion of the employee-only premium not covered by the agency contribution, plus the full additional premium for enrolled dependents. Eligible dependents may still enroll when permitted by the plan; this policy limits the agency’s premium contribution and does not exclude dependents from coverage. It does not promise payment of the employee’s full premium.</p><h2>Where to review your benefit</h2><p>Review My Benefits → Health Insurance in the app for enrollment information, the applicable employer contribution and benefit eligibility. People Operations maintains the employee-only premium used to calculate the contribution, separately from any additional dependent premium. Contact People Operations if the displayed premium includes family coverage or differs from the carrier’s employee-only amount.</p><p>The governing plan documents and applicable law control coverage, eligibility, enrollment and administration. Any change affecting an existing contribution arrangement must be applied prospectively with required notice and any required agreement; this handbook update does not itself change payroll deductions or an existing signed agreement.</p>'
};

export function addHealthInsuranceClause(html){
 const text=String(html||'');
 if(text.includes('Health insurance contribution</h3>'))return text;
 const signature=/<h3>(\d+)\. Employee acknowledgment and signatures<\/h3>/;
 if(signature.test(text))return text.replace(signature,(_,n)=>'<h3>'+n+'. Health insurance contribution</h3><p>'+HEALTH_INSURANCE_CLAUSE+'</p><h3>'+(Number(n)+1)+'. Employee acknowledgment and signatures</h3>');
 return text+'<h3>Health insurance contribution</h3><p>'+HEALTH_INSURANCE_CLAUSE+'</p>';
}
