const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const RESTRICTED_CODES = ['90853','H0025','H2014','H2015','H2016','H2017','H2018','H2032'];
export function codeRestriction(code) {
 if(['H0025','H2032'].includes(code))return 'Not currently approved for agency use. Removed from the available service list.';
 if(code==='H2014')return 'Not approved for individual services. Skill Builders only, with express written approval before use.';
 if(code==='90853')return 'Group moratorium — express written approval of an exception required before use.';
 return 'Express written permission required before any use. Any group delivery is subject to the group moratorium; payer and setting eligibility must be verified.';
}
export const CODE_USE_POLICY='<p>Any service delivered or billed as a group, regardless of its code, is subject to the group moratorium and requires express written approval before use. A saved payroll mapping is not permission to provide or bill a service. In particular, H2015, H2016, H2017 and H2018 require express written permission for any utilization. Their listing does not establish eligibility for group delivery; billing must verify current payer, setting and provider requirements. H2014 is permitted only through Skill Builders with express written approval, and is not approved for individual services. H0025 and H2032 are not currently approved.</p>';
export function restrictedCodeTable(){return '<h2>Restricted and currently unapproved services</h2>'+CODE_USE_POLICY+'<table><thead><tr><th>Code</th><th>Agency restriction</th></tr></thead><tbody>'+RESTRICTED_CODES.map(code=>`<tr><th>${code}</th><td>${codeRestriction(code)}</td></tr>`).join('')+'</tbody></table>';}
export function formatHandbookQuantity(value){const n=Number(value);if(!Number.isFinite(n))return 'Review required';if(Math.abs(n-1/60)<1e-8)return '1/60';return new Intl.NumberFormat('en-US',{maximumFractionDigits:4}).format(n);}
export function formatHandbookBasis(value){const raw=String(value||'').replaceAll('_',' ').trim();return raw?raw[0].toUpperCase()+raw.slice(1):'Review required';}
export function codeInventory(rules=[]){return '<h2>Saved code inventory</h2><table><thead><tr><th>Code</th><th>Pay category</th><th>Saved credit value</th><th>Entered basis</th></tr></thead><tbody>'+rules.filter(r=>/^(?:9|H)\d/i.test(r.service_code)&&r.category==='direct'&&Number(r.credit_value)>0&&!RESTRICTED_CODES.includes(r.service_code)).map(r=>`<tr><td>${escape(r.service_code)}</td><td>${/^H\d/i.test(r.service_code)?'Direct Care Rate + applicable indirect pay':'Clinical Session Rate'}</td><td>${formatHandbookQuantity(r.credit_value)}</td><td>${escape(formatHandbookBasis(r.pay_rate_unit))}</td></tr>`).join('')+'</tbody></table>'+restrictedCodeTable();}
export const HANDBOOK_APP_TRANSITION={slug:'october-2026-editor-change-map',title:'Workplace Handbook and update tracker in the app',bodyHtml:'<p>The Workplace Handbook and Handbook Update Tracker will transition into the app. Staff will be able to read the current handbook, review communicated policy changes and see the applicable effective dates in one place.</p><p>The current manual may not yet reflect the changes communicated in this Provider Update. The manual will be updated by Monday, October 12, 2026. Review the Handbook Updates provided here while that update is completed.</p>'};
