/** Handbook-owned compensation terms. Importing/rendering this never activates payroll. */
export const HCODE_HANDBOOK_REFERENCE = 'Your H-code direct rate is applied to the compensation quantity defined for each service in the current, effective Colorado Billing & Compensation Appendix of the Workplace Handbook. That appendix governs unit-based versus actual-minute compensation, code-specific conversions, documentation, and any future EHR transition. Changes apply prospectively after written notice and any required agreement; they do not reduce pay already earned. Payer billing units, compensation equivalents and actual work time are separate records.';

export const HCODE_HANDBOOK_HTML = `<h2>H-code compensation: units, encounters and the EHR transition</h2>
<p><strong>Current method while using the external EHR.</strong> Payroll tabulates the documented services from the external record. Use the employee’s applicable H-code direct rate and the code-specific basis below. A payer encounter is not automatically one hour of employee pay.</p>
<table><thead><tr><th>Service</th><th>Employee compensation basis</th><th>Direct-pay formula</th></tr></thead><tbody>
<tr><td>H0004 and other approved H-codes billed in 15-minute units</td><td>Verified service units. One unit represents 0.25 compensation hour, even when actual service minutes differ.</td><td>Units × 0.25 × applicable H-code direct rate.</td></tr>
<tr><td>H0031 and H0032, when billed per encounter</td><td>Actual documented service minutes, tabulated for payroll. The claim remains an encounter under the applicable payer rule.</td><td>Documented service minutes ÷ 60 × applicable H-code direct rate.</td></tr>
<tr><td>Other H-codes</td><td>The approved code-specific mapping. Do not assume every H-code uses 15-minute units or that one encounter equals an hour.</td><td>Use the dated mapping after billing/payroll verification.</td></tr>
</tbody></table>
<h3>Fifteen-minute unit boundaries</h3>
<p>Where the applicable payer uses Colorado’s published 15-minute midpoint table: 8 through 22 minutes = 1 unit; 23 through 37 minutes = 2 units; 38 through 52 minutes = 3 units; 53 through 67 minutes = 4 units. Thus 23 minutes is two units, not one. Verify the payer, service-date rules, modifiers and authorized scope before billing; this compensation policy does not authorize a claim.</p>
<h3>Automatic indirect allowance</h3>
<p>Categories 2 and 3 receive 10 minutes (10/60 hour) of paid indirect time per compensated H-code direct-hour equivalent, at the applicable indirect rate. Apply the allowance proportionally: one 15-minute compensation unit adds 2.5 indirect minutes; four units add 10 indirect minutes. For encounter-billed H0031/H0032, a 30-minute documented service equals 0.50 direct hour and adds 5 indirect minutes. Category 1 reports actual indirect time separately and receives no automatic allowance. Report additional compensable work without counting the same work twice.</p>
<h3>Worked examples</h3>
<p>At a $32 H-code direct rate and $22 indirect rate: an H0004 service of 8 or 22 minutes earns one unit, or $8.00 direct plus approximately $0.92 indirect; a 23-minute service earns two units, or $16.00 direct plus approximately $1.83 indirect. Four units earn $32.00 direct plus approximately $3.67 indirect. An encounter-billed H0031/H0032 service lasting 30 documented service minutes earns $16.00 direct plus approximately $1.83 indirect. These examples use Category 2’s indirect rate; each employee’s individual rate schedule controls. Retain full precision during calculation and round money at the applicable payroll aggregation step.</p>
<h3>Internal EHR transition</h3>
<p>The proposed transition method is compensation based on actual documented H-code service minutes, while claims continue to use each payer’s required units or encounter basis. The launch of the internal EHR does not itself change compensation. Before any change takes effect, ITSCO will publish the approved method and effective service date in this appendix, provide written notice and obtain any required agreement, and configure payroll to use the appropriate version for each service date. Until then, the current method above remains in effect, including for late-entered services performed under that method.</p>
<h3>Actual work and sick leave</h3>
<p>Track actual direct, indirect and support work separately. Compensation units are not a substitute for actual-hours records. A service below a payer’s billing threshold or a delayed or denied claim does not erase pay for compensable work; report it for the appropriate payroll treatment. Payroll must reconcile minimum wage, overtime and other applicable wage requirements against actual work time. H-code direct compensation equivalents and paid indirect components enter the sick-leave calculation once; do not add the clinical-credit 1.20 multiplier. Reconcile against actual compensable hours and add any sick-leave accrual required by Colorado law.</p>
<p>Reference: <a href="https://hcpf.colorado.gov/bh-policies">Colorado behavioral health time documentation and unit rules</a>. Billing must verify the current payer-specific requirements for the service date.</p>`;

/** Replace only this seeded section, preserving the rest of an edited handbook. */
export function replaceHcodeHandbookSection(html) {
  const pattern = /<h2>H-code (?:category and indirect allowance|compensation: units, encounters and the EHR transition)<\/h2>[\s\S]*?(?=<h2>Actual time, payer units and internal credits<\/h2>)/;
  if (!pattern.test(String(html))) throw new Error('H-code section boundary not found; preserve draft for manual review.');
  return String(html).replace(pattern, HCODE_HANDBOOK_HTML);
}
