import {escapeHtml as e} from './itscoOctober2026Drafts.js';
const p = text => `<p>${text}</p>`;
const link=(url,label)=>`<a href="${url}">${label}</a>`;
const app='https://app.itsco.health';

/** Staff-facing copy, kept separate from compensation and private editor evidence. */
export function octoberAdminTopics({staff=[],schools=[]}={}) {
 const afterMarch = value => value && String(value).slice(0,10)>='2026-04-01' && String(value).slice(0,10)<='2026-10-07';
 const active = staff.filter(s=>s.status==='ACTIVE_EMPLOYEE' && Number(s.agency_active)===1 && !s.terminated_at);
 const arrivals=active.filter(s=>afterMarch(s.provider_start_date || s.hired_at));
 const departures=staff.filter(s=>afterMarch(s.termination_date || s.terminated_at));
 const names = rows => rows.map(s=>e(`${s.first_name} ${s.last_name}`)).join(', ');
 const realSchools=schools.filter(s=>afterMarch(s.linked_at) && ![410,411,412,413,414,415,416].includes(Number(s.id)) && !/test|fake|demo|self serve/i.test(`${s.name} ${s.district_name}`));
 // School affiliations prove onboarding, not the first clinical service date.
 const springs=realSchools.filter(s=>s.district_name==='D11');
 const denver=realSchools.filter(s=>s.district_name==='DPS');
 const schoolNames=rows=>rows.map(s=>e(s.name)).join('; ');
 return [
  {key:'welcome_october',title:'A new season, a clearer place to work',icon:'heart',body:p('A lot has changed since our March update. This issue brings the practical steps together: your provider review, clearer compensation documents, school coordination, clinical tools and the next stages of our technology transition. Some tools are ready to use; planned releases are labeled below.')+p('This Admin Update is part of your personal Provider Update invitation. Continue through the remaining steps here. Review your information, availability, communication preferences, supervision hours and assigned documents. Record the time spent completing required updates through the designated paid support-work process.')},
  {key:'people_since_march',title:'People since March',icon:'people',body:p(`Please welcome the colleagues whose active records show a start or hire date since March: ${names(arrivals) || 'the new colleagues listed in the final release'}. Thank you for bringing your work and care to the team.`)+p(`Our records also show departures since March: ${names(departures) || 'none listed in this draft'}. We appreciate their contributions. Please route questions about coverage or reassigned work to support; use the current app assignments when contacting a care team.`)},
  {key:'schools_since_march',title:'School partnerships and onboarding',icon:'cap',body:p(`Colorado Springs school records added since March include ${schoolNames(springs) || 'the schools listed in the final release'}.`)+p(`Denver school records added since March include ${schoolNames(denver) || 'the schools listed in the final release'}. Additional new school records include Denver Green Southeast, Steele Elementary and Tesla Educational Opportunity School; their regional details are being completed.`)+p('These are school onboarding additions, not a statement that clinical services have started at every site. Check your assigned school, day, room and roster in the app. Confirm actual school availability and identify missing enrollment steps. School-based reminders will ask families to tell us about absences or problems rather than requiring a “yes” confirmation.')},
  {key:'compensation_october',title:'Your compensation amendment · October 10',icon:'chart',body:p('Your individual amendment identifies your category, level and service-credit, H-code, indirect and support activity rates. Review it in this Provider Update with the dated Colorado Billing & Compensation Appendix. Your service rate pays for clinical credit services; H-code work follows its separately stated direct and indirect calculation. Review the new-hire probation rules and the 60-day minimum-workload transition waiver in your personal schedule.')},
  {key:'tasks_my_work',title:'Tasks and My Work · know what needs your attention',icon:'policy',body:p('Tasks is your list of assigned work: open the item to see its instructions, due date, attachments and the action needed to finish it. Signing a document, submitting a request and marking a checklist item complete are different actions. Complete the underlying step before marking work done; if it is blocked, ask for help on the relevant item.')+p('My Work brings together focus items where that view is enabled; some accounts still show the label Checklist. Use the dashboard to see what is due and open the full task list for details. Review school/client actions in the Provider Update as well—each listed client has a specific outstanding step, and access remains limited to your assignments.')+p('Keep client details inside the appropriate authorized record. Avoid copying sensitive information into broad team tasks or announcements. A reminder or to-do is not itself proof that a clinical note, enrollment or signature has been completed.')+p(link(app+'/tasks','Open Tasks'))},
  {key:'notes_workspace',title:'Notes Workspace · library left, writing center, to-dos right',icon:'document',body:p('<strong>Start with the right-side work queue.</strong> It holds the sessions and documentation tasks you intend to work on. Select a queued item to bring its context into the workspace. Where offered, “open next in queue” helps you move through the remaining work without repeatedly searching for each client.')+p('<strong>Use the center to write and review.</strong> Choose the appropriate note tool, verify the client, service date and clinical details, and edit the draft. AI-assisted text needs your review; it does not replace clinical judgment. Save the draft or use the completion action actually available to your account.')+p('<strong>Use the left Note Library to find work again.</strong> Search, filter, group and reopen available drafts and saved notes. The library and to-do queue serve different purposes: deleting a draft does not remove the underlying session from the queue. Remove an unnecessary to-do from the queue itself, only when appropriate.')+p('<strong>Use it now without confusing the record systems.</strong> ITSCO currently has the note-generation tools enabled, while full clinical chart/signing rollout remains staged. Standalone notes may need their reviewed content copied into TherapyNotes under the current workflow. A saved draft or completed review in this tool is not automatically a signed TherapyNotes record. Keep using the designated record system until the transition announcement.')+p(link(app+'/admin/clinical-note-generator','Open Notes Workspace'))},
  {key:'supervision',title:'Supervision hours now have an app record',icon:'cap',body:p('Review your reported starting hours, imported period hours, finalized app credits and recorded total. The Provider Update shows the sources separately so you can identify a gap or duplicate. If something is wrong, submit a correction with an explanation and supporting information. Do not add historical hours again if they are already in the balance.')},
  {key:'availability_profiles',title:'Your weekly availability and shareable profile',icon:'calendar',body:p('The Provider Update shows your weekly schedule. Add available virtual slots and choose whether eligible office time is open for in-person visits, virtual visits, both, or kept private/booked. Existing appointments, meetings and other busy time continue to block public availability. This view does not create meetings or reserve extra office time.')+p('Open your personal public profile link from the updater to see what clients see. You can copy the link or download its QR code to share. Review your photo, biography and top focus areas. Public availability, booking permissions and notification contact hours are separate settings; an open slot does not promise an immediate booking.')},
  {key:'communication_rollout',title:'Calls, texting and team polls · a staged rollout',icon:'chat',body:p('The app includes provider calling and client-texting workflows, alongside staff notifications and polls. Approved campaigns are a step toward launch, not automatic activation for every employee. Request your desired access and select notification preferences in the Provider Update. Support will confirm when your number, routing and account are ready.')+p('Healthcare messaging will be enabled after our Vonage BAA is signed, the covered numbers/services and safeguards are confirmed, and testing is complete. Ordinary SMS still has carrier/device privacy limitations. Keep clinical details in the secure app under the approved workflow; a BAA does not make every personal-phone text secure.')+p('Team polls can use the answer choices supplied in each poll. Results may be shared in the app, with an optional results text. You can decline or stop optional SMS without losing app access. Staff messages, polling consent, client-texting access and future forwarding are separate choices. Phone forwarding, recordings/transcripts and AI answering will be announced only when enabled.')+p('Messages are not monitored continuously and are not a crisis service. In the U.S., call or text 988 for suicide or crisis support; call 911 for an immediate emergency.')+p(link(app+'/itsco/terms#sms','Read ITSCO messaging terms'))},
  {key:'private_virtual_rooms',title:'Coming soon · your private virtual room',icon:'spark',body:p('We are preparing a personal virtual room you can use for appropriate work conversations, supervision and meetings within your role. Access, invitations and privacy controls will be explained before release. It is not yet a substitute for the currently approved telehealth workflow; client use will follow the applicable consent and security requirements.')},
  {key:'therapynotes_transition',title:'Planned TherapyNotes transition · Thanksgiving weekend',icon:'target',body:p('Our target transition weekend is November 26–29, 2026. We will provide the exact cutover instructions, training and support arrangements before that weekend. Continue documenting in the current designated record system until you receive the go-live notice.')+p('Before the move, reconcile your caseload, upcoming appointments, unfinished notes, supervision information and outstanding client actions. We will verify migrated records, permissions, billing workflows and access, with a fallback if a critical workflow is not ready. Do not delete records or assume that saving a draft in the app has migrated or signed it in TherapyNotes.')},
  {key:'google_transition',title:'Moving toward the app · the Google Workspace transition',icon:'gear',body:p('<strong>The direction:</strong> one app for day-to-day work, email access and our shared document library. We plan to retire the separate Google Workspace accounts in stages. No account shutdown date is announced in this update, and staff should keep using their current approved access until their migration is confirmed.')+p('<strong>Email:</strong> the goal is to read, send and organize work email in the app. Before a mailbox moves, we will verify its address, incoming and outgoing delivery, shared/group addresses, aliases, signatures, history and support routing. An app inbox may still depend on Google underneath during the transition; opening email in the app alone does not mean the Google account is ready to close.')+p('<strong>Documents and the Library:</strong> the app’s Library will be the place for shared policies, forms, reference material and other approved documents. We will identify the current version, organize access and migrate the material staff need. Do not delete a Drive file merely because a link appears in the app. Client records, personnel files and general reference documents will keep their appropriate permissions and retention rules.')+p('<strong>Calendar and meetings:</strong> we will verify upcoming events, recurring invitations, supervision links and school schedules before replacing any Google-dependent process. The planned private virtual rooms will have their own rollout instructions. Your existing meeting link remains the one to use until an authorized replacement is provided.')+p('<strong>Sign-in:</strong> many ITSCO roles currently use Google sign-in. We must establish and test replacement app access and recovery before closing those accounts. Your six-digit Quick View code is separate from your main login and cannot replace a required sign-in method by itself.')+p('<strong>Your part:</strong> review your contact information and notification choices, identify documents or shared mailboxes you rely on, and report missing access. Wait for your migration checklist and confirmation before changing addresses or deleting anything. Support will provide a clear cutover notice, a way to get help and a fallback. This plan does not authorize forwarding client information to personal email.')},
  {key:'quick_view',title:'Quick View on your phone',icon:'lightbulb',body:p('Add the app’s Quick View page to your phone home screen so it is easy to open during the workday. On iPhone/iPad, open the page in Safari, use Share and choose Add to Home Screen. On Android, open it in Chrome and use the menu’s Add to Home screen or Install app option. The exact label can vary by browser.')+p('Create your six-digit Quick View code in the Provider Update if you do not have one, or through My Preferences → Privacy & Quick View. Existing codes are not displayed or replaced in the updater. Use your own account and keep the device locked. Contact support for an alternative if you cannot use a personal device; adding a shortcut does not enroll you in SMS.')},
  {key:'terms_links',title:'Terms, privacy and messaging information',icon:'policy',body:'<ul>'+[
   [app+'/itsco/terms','ITSCO terms, including messaging'],[app+'/itsco/privacypolicy','ITSCO privacy policy'],[app+'/itsco/platformhipaa','ITSCO privacy practices notice'],
   [app+'/sms-programs/2/polling/terms','ITSCO staff notifications and polling terms']
  ].map(([u,l])=>`<li>${link(u,l)}</li>`).join('')+'</ul>'+p('Please read the terms for the workspace you use. A terms acknowledgment is not a substitute for choosing SMS preferences or signing your individual compensation amendment. Ask support about a link that does not open or a policy that does not match your agency.')}
 ];
}
