/** October editorial drafts. These functions never activate payroll or send notices. */
export const SEED_KEY = 'itsco-october-2026-compensation-v1';
export const EFFECTIVE_DATE = '2026-10-10';
export const CATEGORY_NAMES = { 1: 'Unlicensed', 2: 'Pre-licensed masters level', 3: 'Licensed professional' };
export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => value != null && Number(value) > 0 ? `$${Number(value).toFixed(2)}` : '[rate to be completed]';
export const allowancePercent = minutes => minutes == null ? '[not set]' : Number(minutes) === 10 ? '16⅔%' : `${Number((Number(minutes) / 60 * 100).toFixed(4))}%`;
const p = text => `<p>${text}</p>`;

export const sources = [
 ['Colorado HFWA guidance (February 2026)', 'https://cdle.colorado.gov/sites/cdle/files/info_%236b_rights_and_obligations_under_hfwa_2.27.2026.pdf'],
 ['Colorado wage and overtime guidance (2026)', 'https://cdle.colorado.gov/sites/cdle/files/info_%231_2026_comps_%26_paycalc_orders_12.18.25.pdf'],
 ['Colorado earned vacation/PTO guidance', 'https://cdle.colorado.gov/sites/cdle/files/info_%233e_payment_of_earned_vacation_upon_separation_of_employment_05.29.2024_accessible.pdf'],
 ['Federal regular-rate guidance', 'https://www.dol.gov/agencies/whd/fact-sheets/56a-regular-rate'],
 ['Colorado behavioral health billing manual and updates', 'https://hcpf.colorado.gov/sbhs-billing-manual'],
 ['Vonage healthcare API requirements', 'https://www.vonage.com/communications-apis/healthcare/hipaa-compliance/']
];

export function amendmentIssues(data) {
 const s = data.schedule || {}, issues = [];
 if (![1,2,3].includes(Number(s.category))) issues.push('Choose the employee’s approved compensation category.');
 if (![1,2,3,4,5].includes(Number(s.level))) issues.push('Choose the employee’s approved compensation level.');
 for (const [key,label] of [['creditRate','Direct clinical credit rate'],['hcodeRate','Integrated service calculation rate'],['indirectRate','Indirect hourly rate'],['supportRate','Support activity hourly rate'],['ptoRate','PTO hourly rate']]) {
  if (s[key] == null || !Number.isFinite(Number(s[key])) || Number(s[key]) <= 0) issues.push(`${label} needs a positive confirmed value.`);
 }
 if (data.employee?.employmentType === 'salaried') issues.push('Salaried employee: confirm scope before replacing any salary terms with a service-credit agreement.');
 if (data.employee?.employmentType === 'intern') issues.push('Confirm paid employment status and authorized service scope for this intern.');
 if (!data.employee?.originalAgreementDate) issues.push('Identify the prior agreement being amended (date or document reference).');
 if (!s.levelDescription) issues.push('Add the approved description for this level; no level criteria were saved in the matrix.');
 if (!data.leaveChoice || data.leaveChoice === 'pending') issues.push('Confirm whether the 1-for-25 benefit is sick leave or general PTO.');
 return issues;
}

export function commonAmendmentClauses(leaveChoice = 'sick') {
 const leave = leaveChoice === 'general_pto'
  ? 'This is general PTO usable for vacation or other personal reasons. Earned balances are not forfeited; earned and determinable unused vacation/PTO is paid at separation as Colorado law requires. The statutory sick-leave floor and protected uses below remain available within the combined program, with separate accounting sufficient to demonstrate compliance.'
  : leaveChoice === 'sick'
   ? 'This benefit is paid sick leave for the qualifying reasons protected by Colorado’s Healthy Families and Workplaces Act (HFWA), not a new vacation benefit. It is available from accrual without a probationary waiting period. Any other existing vacation or general-PTO entitlement remains governed by its existing terms and applicable law.'
   : '[EDITOR: confirm whether this is sick leave or general PTO before issuing. Do not change the character of an existing benefit by relabeling it.]';
 return [
  ['1. Effective date and compensation replacement', 'The proposed effective date is Saturday, October 10, 2026. Once agreed by the parties, this amendment replaces only the conflicting compensation, service-pay, included-indirect, and leave-accrual provisions identified here in the employee’s prior employment agreement and pay addenda for work on or after that date. It does not reduce wages or leave already earned, change an employee’s classification or duties, or replace unrelated contract provisions. If executed after the proposed date, no reduction applies to work already performed; any later prospective effective date must be recorded by the parties.'],
  ['2. Individual compensation schedule', 'The attached individual schedule identifies this employee’s category, level, clinical credit rate, integrated-service calculation rate, indirect rate, support activity rate, PTO rate, and any expressly approved differential. Category, compensation level, and workload/benefit tier are different concepts. No level, credential, tier bonus, probation reduction, or exemption is inferred from a job title alone. Missing fields must be completed before the amendment is issued.'],
  ['3. Clinical credits and exact time', 'A clinical credit is an internal compensation unit, not a representation that exactly 60 minutes were worked or billed. The employee records actual direct service start/end times or exact minutes and all other compensable work. For a qualifying 90837 encounter assigned 1.00 credit in the Colorado appendix, direct service pay is 1.00 × the employee’s clinical credit rate even when the actual qualifying duration differs from 60 minutes. The applicable payer’s requirements determine whether that code may be billed.'],
  ['4. Separately identified included indirect pay', 'In addition to direct credit pay, the app calculates included indirect time using the percentage in the effective, dated Colorado handbook appendix: direct clinical credits × 60 minutes × that percentage. It pays those minutes, at the employee’s indirect hourly rate. The individual schedule shows the initial appendix percentage for reference; it does not freeze that allowance permanently. ITSCO may revise the allowance prospectively after written notice and any agreement required by existing terms, recording the new percentage and service-date effective boundary in the appendix. A handbook edit alone does not activate a payroll change. Fractional credits receive the proportional allowance. This amount is a separate pay component; it is not already absorbed into the direct rate. Actual indirect time must still be recorded. The applicable allowance is retained when ordinary associated work takes less time. AI-assisted documentation does not automatically reduce the allowance; any reduction, including to zero, follows the same prospective process. Required review, corrections and other actual work remain compensable even with a zero allowance. Work already paid through this component is not claimed twice; actual additional compensable indirect work is reported and paid at the applicable rate.'],
  ['5. Integrated and per-minute services', 'For a code expressly designated per-minute in the appendix, direct pay equals actual direct minutes ÷ 60 × the integrated-service calculation rate, with an additional indirect allowance of direct minutes ÷ 60 × the scheduled indirect minutes per direct-hour equivalent, paid at the indirect rate. For a designated unit or encounter service, the appendix supplies its compensation value and corresponding allowance. Billing units, workload credits, and actual minutes are stored separately. A code does not receive both FFS and integrated direct payment for the same work.'],
  ['6. Support work, excess time, and wage protection', 'Required onboarding, training, meetings, administrative-update reading/listening, compensable supervision, and other designated support work are paid at the support activity rate. Record all compensable work, including work beyond an estimate or allowance and time worked outside a scheduled window. Advance approval is requested for foreseeable additional work, but lack of approval, a late note, or payer denial does not forfeit earned wages. Payroll applies applicable minimum wages, overtime, rest-period pay, and regular-rate rules using actual compensable hours. A 14-day review does not average away daily or workweek obligations.'],
  ['7. Leave accrual and payment', `Each 25 qualifying direct clinical credits, or 25 actual direct hours for services paid on a time basis, earn 1 hour of leave, prorated at 0.04 hour per qualifying credit/hour. The same service is counted once. This is leave earned in addition to cash service pay, not a deduction from that pay. Leave is paid at the employee’s stated PTO rate, or a higher rate required by law. ${leave} Independently reconcile the program against HFWA’s required accrual based on all hours worked, including required indirect and support work; add any shortfall rather than treating the direct-credit formula as a cap. Preserve existing balances and any more generous earned rights. HFWA carryover, protected uses, notice, documentation, and payment requirements govern protected leave.`],
  ['8. Colorado appendix and prospective changes', 'The attached, dated Colorado Billing & Compensation Appendix supplies service-code compensation mappings, exact-time documentation, included-indirect calculations, and differential procedures. It is incorporated into this amendment as the operational schedule, subject to law and the individual pay schedule. A later handbook edit cannot retroactively reduce earned pay or silently replace an agreed individual rate. Any compensation reduction or new workload-rate condition requires prospective written notice and any agreement required by the existing contract. Payer billing requirements always govern claims.'],
  ['9. Acknowledgment and signatures', 'The employee acknowledges receipt of the completed individual schedule and the dated appendix, has an opportunity to ask questions, and agrees to these compensation terms without waiving statutory rights. Employee signature/date: ____________________. ITSCO authorized representative signature/date: ____________________. Agreed effective date: ____________________.']
 ].map(([title,body])=>`<h3>${title}</h3>${p(body)}`).join('\n');
}

export function renderAmendment(data) {
 const s=data.schedule || {}, e=data.employee || {}, issues=amendmentIssues(data);
 const rows=[['Employee',e.name],['Role / credential',[e.title,e.credential].filter(Boolean).join(' · ')],['Prior agreement',e.originalAgreementDate || '[date or document reference needed]'],['Proposed effective date','October 10, 2026'],['Category',CATEGORY_NAMES[s.category] ? `${s.category} — ${CATEGORY_NAMES[s.category]}` : '[not assigned]'],['Compensation level',s.level ? `Level ${s.level}` : '[not assigned]'],['Level description',s.levelDescription || '[approved criteria to be added]'],['Direct clinical credit rate',`${money(s.creditRate)} / credit`],['Integrated service calculation rate',`${money(s.hcodeRate)} / direct-hour equivalent`],['Indirect rate',`${money(s.indirectRate)} / hour`],['Support activity rate',`${money(s.supportRate)} / hour`],['PTO pay rate',`${money(s.ptoRate)} / hour, subject to the statutory pay floor`],['Initial handbook indirect allowance',`${allowancePercent(s.autoIndirectMinutes)} of each direct credit/hour equivalent (${s.autoIndirectMinutes ?? '[not set]'} minutes); see the dated appendix and prospective-change clause`],['Leave earned','1 hour per 25 qualifying direct credits/hours; statutory reconciliation applies']];
 const example=s.creditRate>0&&s.indirectRate>0&&s.autoIndirectMinutes!=null ? `<h3>Worked example for this employee</h3><p>One qualifying 90837 service assigned 1.00 credit: ${money(s.creditRate)} direct + ${Number(s.autoIndirectMinutes || 0)} ÷ 60 × ${money(s.indirectRate)} indirect = <strong>${money(Number(s.creditRate)+(Number(s.autoIndirectMinutes || 0)/60)*Number(s.indirectRate))}</strong>, before separately earned differentials or overtime. This earns 0.04 hour of leave; 25 such credits earn 1 hour, paid when used at ${money(s.ptoRate)} or the required higher rate. A 53-minute service records 53 actual direct minutes, not 60 or 72.</p>` : '';
 return `<h1>ITSCO, LLC</h1><h2>Compensation Amendment · October 2026</h2><p><strong>Editable draft — not issued or signed.</strong></p>${issues.length?`<p><strong>Complete before issue:</strong> ${issues.map(escapeHtml).join(' ')}</p>`:''}<table><tbody>${rows.map(([a,b])=>`<tr><th>${escapeHtml(a)}</th><td>${escapeHtml(b)}</td></tr>`).join('')}</tbody></table>${example}${data.commonClausesHtml || commonAmendmentClauses(data.leaveChoice)}${data.additionalTerms ? `<h3>Individual notes for review</h3>${p(escapeHtml(data.additionalTerms))}`:''}`;
}

export function handbookSections({leaveChoice='sick',rates=[],rules=[]}={}) {
 const codeTable=rules.filter(r=>Number(r.show_in_rate_sheet)!==0 && r.category==='direct' && Number(r.credit_value)>0).map(r=>`<tr><td>${escapeHtml(r.service_code)}</td><td>${Number(r.credit_value).toFixed(4).replace(/0+$/,'').replace(/\.$/,'')}</td><td>${escapeHtml(r.pay_rate_unit)}</td><td>${escapeHtml(r.duration_minutes ?? 'Verify code basis')}</td></tr>`).join('');
 const matrix=rates.map(r=>`<tr><td>${r.category}</td><td>${r.level}</td><td>${money(r.credit_rate)}</td><td>${money(r.hcode_rate)}</td><td>${money(r.indirect_rate)}</td><td>${money(r.support_activity_rate)}</td><td>${allowancePercent(r.auto_indirect_minutes_per_hour)}</td></tr>`).join('');
 return [
  {slug:'october-2026-compensation-overview',title:'October 2026 compensation amendment — scope and priorities',bodyHtml:'<h2>Proposed effective date: October 10, 2026</h2>'+p('This draft aligns the handbook with individual compensation amendments. It supersedes the older proposal that absorbed all routine indirect work into the FFS rate. The proposed approach pays a clinical credit amount plus a separately identified indirect allowance whose percentage and effective date are maintained in the handbook appendix. Adoption of this handbook draft does not sign employee amendments or activate payroll settings.')+p('Use this order: applicable law; the executed individual amendment and pay schedule; this dated operational appendix; then other nonconflicting handbook provisions. Record which appendix version each employee receives. Preserve prior versions and earned wages and leave.')+p('Existing contract-library language describing benefits as wholly unvested or denying pay for unapproved/undocumented work must be revised for new agreements: earned wages and earned vacation/PTO remain protected. Required work is recorded and paid; documentation and authorization concerns are handled separately.')},
  {slug:'colorado-billing-compensation-appendix',title:'Colorado Billing & Compensation Appendix — proposed October 10, 2026',bodyHtml:
   '<h2>A. Three different records</h2>'+p('Store (1) actual direct/indirect/support minutes, (2) payer claim units and documented billing code, and (3) internal compensation/workload credits. Never copy an internal credit-equivalent into the actual-time record or submit the automatic indirect allowance as a payer claim.')+
   '<h2>B. Clinical credit services</h2>'+p('Direct compensation = assigned clinical credits × the employee’s credit rate. Added indirect compensation = assigned credits × scheduled indirect minutes ÷ 60 × the employee’s indirect rate. For 90837 the internal mapping is 1.00 credit. The supplied Colorado example uses a 53–74 minute encounter; confirm the applicable HCPF/MCE manual version and payer requirements for the date of service, including extended encounters, credential, supervision, modifier, setting, and telehealth rules. The 74-minute boundary is not a universal CPT rule.')+
   '<h2>C. Integrated services</h2>'+p('For a designated actual-minute service, direct minutes ÷ 60 × integrated rate + direct minutes ÷ 60 × scheduled indirect minutes ÷ 60 × indirect rate. Example: 15 direct minutes at $32 with a 10-minute-per-hour allowance and indirect at $22 = $8.00 direct + $0.92 indirect = $8.92 (rounded to cents). Actual indirect minutes are recorded separately. For a service expressly assigned a fixed encounter/unit value, use that mapping; do not silently round actual-minute compensation up to a claim unit. No blanket “all H-codes” or “all 9-series codes” rule establishes billability or credentials.')+
   '<h2>D. Code-mapping inventory for editing</h2>'+p('These are the app’s saved internal payroll mappings, not a verified payer fee schedule. “Entered basis” and nominal duration must be reconciled for each code before activating the new calculation. Keep claim units separate from payroll entries, especially H0031/H0032/H2016/H2022 and other per-minute mappings. Add-on, zero-credit, missed-appointment, and percentage arrangements need their own explicit rules; absence from this table does not mean required work is unpaid.')+
   '<table><thead><tr><th>Code</th><th>Saved credit value</th><th>Saved entered basis</th><th>Nominal minutes</th></tr></thead><tbody>'+codeTable+'</tbody></table>'+
   '<h2>E. Category and level matrix</h2>'+p('Category 1: unlicensed staff, including qualified bachelors-level, intern, peer and unlicensed masters roles; Category 2: pre-licensed masters-level professionals; Category 3: licensed professionals. Credential and payer scope must be verified independently. Levels 1–5 are compensation assignments, not workload tiers. Detailed advancement criteria are not saved in the current matrix and must be supplied before being represented as established policy. The saved indirect allowance is 16⅔% of each direct credit/hour equivalent for Categories 2 and 3 (exactly 1/6, or 10 minutes), and 0% for Category 1. This is a time allowance, not a percentage of the employee’s direct pay. Preserve the exact fraction in calculations rather than truncating it to 16%. The new agency and employee pay switches remain off until explicitly activated; set the service-date effective boundary to match the signed terms. A software switch does not cancel wages already promised in an effective agreement.')+
   '<table><thead><tr><th>Category</th><th>Level</th><th>Clinical credit</th><th>Integrated calculation</th><th>Indirect/hour</th><th>Support/hour</th><th>Initial indirect allowance</th></tr></thead><tbody>'+matrix+'</tbody></table>'+p('This is the saved new-pay-system matrix. Individual signed schedules and approved exceptions control. A matrix entry does not change anyone’s saved category/level or pay. PTO rates come from each employee’s PTO account, not an assumed equality with the clinical rate.')+
   '<h2>F. Maintaining the indirect percentage</h2>'+p('The handbook maintains the allowance by category/level, percentage, corresponding minutes, appendix version and effective service date. ITSCO may revise it prospectively as workflows change, with written notice before affected work and any agreement required by existing terms. Archive the former schedule and preserve it for earlier services, including late-entered work. Keep the initial schedule in each amendment as a reference. Do not apply an undated current percentage to historical services. The payroll activation switch and service-date calculation must implement the same approved schedule.')+p('AI can reduce drafting time, but providers still perform required review, corrections, coordination and other work. Assess actual time before proposing a smaller allowance. If the percentage becomes zero, required indirect work is still recorded and paid; zero allowance does not mean zero compensation for actual work. No automatic reduction is triggered merely by recording a session or generating a note.')+'<h2>G. Included and additional indirect work</h2>'+p('Routine preparation, ordinary documentation and related follow-up are covered by the added allowance. If actual associated indirect time exceeds the allowance, report the excess; unrelated client coordination and other required work are recorded in their appropriate category. Do not duplicate a payment or omit work. A pay-period comparison can help review trends but cannot remove hours, offset overtime between weeks, or deny compensation because another encounter took less time.')+
   '<h2>H. Billing integrity and school services</h2>'+p('Record the actual service site and accurate place of service. A billing office address is not the school where care occurred. Use school-based reminders that invite notice of absence or problems rather than requiring appointment confirmation. Verify clinical eligibility, consent, credential, supervision, duration, medical necessity and payer-specific code restrictions before billing. A payroll credit, bonus, or workload target never authorizes a claim or changes clinical judgment.')+
   '<h2>I. Minimum workload and differentials — proposed operational rules</h2>'+p('The supplied policy proposed a November 13, 2026 minimum-workload change: 12 workload clinical hours per 14-day period; one 14-day grace period; a prospective rate change only after that grace period; and a Tier 3 exception when Tier 3 occurred in one of the preceding six completed periods. These are proposed terms to reconcile before issue, not active payroll settings. The app also contains a 90-day initiation/probation protection, so dates and eligibility must be resolved in the individual notice before any lower rate is used.')+p('Show each employee’s standard and any expressly applicable lower direct rate separately. Do not reduce indirect/support rates solely because workload changes. Preserve any more favorable agreed protection. The appendix cannot impose a retroactive H2014 penalty or substitute a lower rate after work has already been done. Credential or authorization problems require prospective correction and appropriate clinical/billing review.')+p('Spanish and Denver differentials are paid only on qualifying direct work after documented eligibility. Use the employee’s saved rate matrix and tier, not an invented blanket amount: some saved Spanish schedules differ. Spanish qualification requires a preapproved course or proficiency evidence, successful certificate, verification, and any stated eligibility period. Publish approved course/reimbursement terms before enrollment; required job training and costs remain subject to wage law. A language self-selection alone does not activate a bonus. Denver eligibility follows actual qualifying assignment/service, not residence.')+
   '<h2>J. Version control</h2>'+p('Each released code table must show owner, version, effective date, payer/manual reference, compensation basis and indirect allowance. Archive prior versions; review billing-manual updates separately from compensation changes. Obtain prospective agreement/notice for pay changes as required. This draft does not certify that every saved code is currently billable.')},
  {slug:'paid-time-off-and-colorado-sick-leave',title:'Paid leave — direct-service accrual and Colorado safeguards',bodyHtml:commonAmendmentClauses(leaveChoice).split('<h3>7.')[1]?.split('<h3>8.')[0] ? '<h2>Direct-service leave benefit</h2>'+commonAmendmentClauses(leaveChoice).split('<h3>7.')[1].split('</h3>')[1].split('<h3>8.')[0]+p('HFWA generally requires 1 hour per 30 hours worked, up to 48 hours annually, with up to 48 unused hours carried forward, subject to lawful compliant alternatives and more generous terms. Include compensable indirect, support, training, and overtime hours; apply the law’s exempt-employee rules where relevant. Do not impose the app’s current 10-hour rollover or general 30-day advance-notice setting on protected sick leave. Follow statutory reasons, reasonable notice, permitted documentation, and nonretaliation requirements.')+p('Do not discard existing accrued balances. If the benefit is general PTO usable for vacation, earned vacation/PTO is protected from forfeiture and payable at separation. If a combined bank is selected, track and administer it so HFWA rights are fully available; the title “PTO” does not remove those duties. Leave pay must meet the applicable statutory rate even if the saved PTO rate is lower. The current database contains missing/zero rates that require completion before issue.')+'<h3>Rate-policy option for the editor — not adopted</h3>'+p('Keep currently promised rates for this rollout. For future policy, consider normal earnings per actual working hour instead of automatically equating an hourly sick-leave rate with the highest clinical credit rate. For variable fee-for-service earnings without a separate base rate, Colorado guidance uses a recent earnings lookback when the applicable rate is not known in advance; a known applicable rate or differential must be treated accordingly. Use the required statutory rate and any higher promised entitlement. The support-work rate is not automatically a base rate for all clinical work. Reliable actual-time records are needed; never divide earnings by clinical credits as though they were clock hours.')+p('Illustration only: $2,800 of includable earnings across 70 actual working hours gives $40/hour. This is not a calculation of any employee’s current entitlement. A new formula could produce more or less than a clinical credit rate. Any future change must be stated prospectively and preserve existing commitments and earned rights. No lower rate has been applied in these drafts.') : ''},
  {slug:'timekeeping-support-and-overtime',title:'Actual time, support activities, and payroll corrections',bodyHtml:p('Record actual work daily in the appropriate direct, indirect, or support category, including required administrative updates and work performed beyond scheduled hours. A service credit or a 72-minute planning equivalent is not an actual-time entry. Reconcile auto-paid indirect allowances without double claiming or dropping compensable work.')+p('Pay required support work, permitted compensable travel and additional work at the appropriate disclosed rates. Apply applicable Colorado/local minimum wages and overtime, including daily/consecutive-hour requirements and the workweek regular rate for covered nonexempt staff. Do not average two workweeks together. Required rest periods are paid as applicable. An exemption requires an actual legal basis; licensure or a per-service pay arrangement alone is not enough.')+p('Correct payroll promptly, preserve the original record and audit trail, and provide a way to report missing time without retaliation. Approval rules manage work; they do not erase wages for work the employer suffered or permitted. Unpaid payer claims and documentation concerns are not blanket grounds to withhold employee wages.')},
  {slug:'communications-schoolcarebridge-and-transition',title:'Digital workplace, communications, and transition procedures',bodyHtml:p('ITSCO remains the care provider and employer. SchoolCareBridge is the school coordination program operated by MH4Kidz, with platform maintenance by PlotTwistCo. AuricWell is the clinical workspace/interface; branding does not change the treating organization or access rights. Use only assigned records and authorized workflows.')+p('Staff select notifications and polling preferences separately from client-texting access and any future forwarding. Respect STOP and other consent choices. App/phone availability settings describe contact preferences, not permission to ignore an assigned duty or a guarantee of round-the-clock support. The service is not a crisis channel; communicate the published emergency guidance and route urgent support through the approved process.')+p('Healthcare SMS/voice rollout requires the executed BAA, confirmed covered services/numbers, technical safeguards, consent, and successful testing. Ordinary SMS can appear on carrier networks and personal devices; keep sensitive details in the secure app unless specifically authorized under the approved workflow. No personal-device relay, recording, transcription, or autonomous AI answerer is activated merely by a policy acknowledgment.')+p('The planned TherapyNotes transition is Thanksgiving weekend, November 26–29, 2026. Use the currently designated record system until the go-live notice. Preserve records, permissions, unfinished notes, billing history, appointments, and an operational fallback. Google Workspace retirement is a separate staged plan with no shutdown date announced here. Validate email delivery, migrated documents, calendar/invites, group addresses, retention, and non-Google sign-in before any account is closed.')+p('Quick View may be added to the phone home screen for access; protect the device and six-digit code and use only your own login. Staff who cannot use a personal device must have an alternative access arrangement. Home-screen installation is not consent to SMS, tracking, or PHI forwarding.')},
  {slug:'october-2026-editor-change-map',title:'Editor change map and release checklist',bodyHtml:p('Full prior handbook text was not present in the in-app handbook; only a placeholder existed. The following are section-level replacements/additions, not a claim that every sentence of an external handbook has been reconciled.')+'<ol><li>Replace old direct/indirect or FFS pay definitions with the attached category/level schedule and separately paid indirect allowance.</li><li>Replace “FFS includes all routine admin” wherever it conflicts with the new credit-plus-indirect terms.</li><li>Add the Colorado code table, actual-time/claim-unit/credit separation, service-site rules and version history.</li><li>Revise leave definitions, accrual basis, pay rate, carryover, notice, protected uses and any forfeiture language.</li><li>Revise support work, additional time and payroll correction procedures; remove blanket denial or delay of wages for missing approval/documentation.</li><li>Reconcile workload dates, grace/probation protections, Tier 3 lookback and each differential against app calculations before activation.</li><li>Add communications consent, school coordination, secure workspace and transition procedures.</li><li>Complete missing individual levels, level descriptions, PTO rates and prior-agreement references before issue. Keep salaries and role-specific exceptions separate.</li></ol>'+p('Implementation gaps as of preparation: new-pay-system switch is off; saved indirect allowance is 10 minutes per hour equivalent for Categories 2–3 and zero for Category 1; no 20% increase is proposed; existing FFS calculation does not add the proposed direct-credit indirect component; existing leave math uses a broader paid-time basis; actual-minute entry and applicable overtime/leave reconciliation require acceptance tests before activation. Draft seeding changes none of these payroll settings.')+'<h3>Primary references for the editor</h3><ul>'+sources.map(([a,b])=>`<li><a href="${b}">${a}</a></li>`).join('')+'</ul>'}
 ];
}
