import {categoryRateSchedule,personalRateTable,payTypeDescriptions,categoryDescriptions,conditionalLevelBonus} from './compensationSchedulePresentation.js';
import {addLevelExpectationsToClauses, levelExpectationsHandbookSection} from './compensationLevelExpectations.js';
/** October editorial drafts. These functions never activate payroll or send notices. */
export const SEED_KEY = 'itsco-october-2026-compensation-v1';
export const EFFECTIVE_DATE = '2026-10-10';
export const CATEGORY_NAMES = { 1: 'Unlicensed', 2: 'Pre-licensed masters level', 3: 'Licensed professional' };
export const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money = value => value != null && Number(value) > 0 ? `$${Number(value).toFixed(2)}` : '[rate to be completed]';
export const allowancePercent = minutes => minutes == null ? '[not set]' : Number(minutes) === 10 ? '16⅔%' : `${Number((Number(minutes) / 60 * 100).toFixed(4))}%`;
const p = text => `<p>${text}</p>`;

export const sources = [
 ['Colorado HFWA guidance (February 2026)', 'https://cdle.colorado.gov/sites/cdle/files/info_%236b_rights_and_obligations_under_hfwa_2.27.2026.pdf'],
 ['Colorado wage and overtime guidance (2026)', 'https://cdle.colorado.gov/sites/cdle/files/info_%231_2026_comps_%26_paycalc_orders_12.18.25.pdf'],
 ['Colorado earned vacation/PTO guidance', 'https://cdle.colorado.gov/sites/cdle/files/info_%233e_payment_of_earned_vacation_upon_separation_of_employment_05.29.2024_accessible.pdf'],
 ['Federal regular-rate guidance', 'https://www.dol.gov/agencies/whd/fact-sheets/56a-regular-rate'],
 ['Colorado behavioral health billing manual and updates', 'https://hcpf.colorado.gov/sbhs-billing-manual'],
 ['Vonage healthcare API requirements', 'https://www.vonage.com/communications-apis/healthcare/hipaa-compliance/']
];

export function amendmentIssues(data) {
 const s = data.schedule || {}, issues = [];
 if(data.employee?.employmentType==='salaried' && data.compensationBasis!=='service_credit')return ['Review and approve the salary-specific amendment before issue; existing salary terms remain in effect.'];
 if (![1,2,3].includes(Number(s.category))) issues.push('Choose the employee’s approved compensation category.');
 if (![1,2,3,4,5].includes(Number(s.level))) issues.push('Choose the employee’s approved compensation level.');
 for (const [key,label] of [['creditRate','Direct clinical credit rate'],['hcodeRate','H-code direct rate'],['indirectRate','Indirect hourly rate'],['supportRate','Support activity hourly rate'],['ptoRate','PTO hourly rate']]) {
  if (s[key] == null || !Number.isFinite(Number(s[key])) || Number(s[key]) <= 0) issues.push(`${label} needs a positive confirmed value.`);
 }
 for (const [key,label] of [['creditRateProbation','clinical service credits'],['hcodeRateProbation','H-code direct service'],['indirectRateProbation','indirect work'],['supportRateProbation','support activities']]) if (!(Number(s[key]) > 0)) issues.push(`Confirm the probationary / minimum-workload rate for ${label}.`);
 if (data.employee?.employmentType === 'salaried') issues.push('Salaried employee: confirm scope before replacing any salary terms with a service-credit agreement.');
 if (data.employee?.employmentType === 'intern') issues.push('Confirm paid employment status and authorized service scope for this intern.');
 if (!data.employee?.originalAgreementDate) issues.push('Identify the prior agreement being amended (date or document reference).');
 if (!s.levelDescription) issues.push('Add the approved description for this level; no level criteria were saved in the matrix.');
 if (!data.leaveChoice || data.leaveChoice === 'pending') issues.push('Confirm whether the 1-for-25 benefit is sick leave or general PTO.');
 return issues;
}

export {SERVICE_CREDIT_POLICY_VERSION as SERVICE_POLICY_VERSION} from '../utils/serviceCreditPolicy.js';
export const INITIAL_ADMIN_RATIO = 0.2;
export const GROUP_MORATORIUM_HTML = `<h2>Groups: practice-wide moratorium and review</h2>
<p>ITSCO has paused new provider-initiated groups outside the established Skill Builders program. Do not advertise, enroll participants in, schedule, or begin a new independent group until ITSCO has reviewed and authorized it in writing. Existing services require a coordinated continuity-of-care plan; this policy does not authorize abrupt discharge or cancellation of care.</p>
<p>Skill Builders groups may proceed within their approved program, curriculum, staffing, funding and service scope. Psychotherapy process groups under 90853 remain a possible service, but the availability of a billing code does not authorize a provider to launch a group. Any proposed 90853 group or other exception requires review before it begins. Neither 90849 nor H0025 is an automatic workaround.</p>
<p>For an exception, submit the proposed clinical purpose, participant criteria and acuity, curriculum if applicable, schedule/duration, staffing and safety plan, preparation and follow-up time, supplies and budget. Support and billing must verify each participant’s coverage, payer/RAE requirements, authorizations where applicable, treatment-plan appropriateness and documentation requirements. Management must approve the operational plan, funding and employee compensation before enrollment or advertising.</p>
<p>Payer requirements and reimbursement vary by service, plan and date. Use the current Colorado billing appendix and applicable payer guidance; do not assume that one authorization or group code covers every participant. Track actual preparation, delivery, documentation, setup and cleanup work. Record and pay all compensable work at the applicable disclosed rates, including applicable minimum wage and overtime; payer denial or low attendance does not erase earned wages.</p>
<p>When a needed group is unavailable, coordinate appropriate referrals and support continuity of care. Direct proposals or questions to Michael and Rachel through the app. Potential MH4Kidz grant or program support is a separate funding proposal, not permission to offer an unapproved group or to replace paid employee duties with unpaid volunteer work.</p>`;

export function commonAmendmentClauses(leaveChoice='sick') {
 const leave=leaveChoice==='general_pto'
 ? 'Any expressly agreed general vacation/PTO entitlement retains its applicable vesting, carryover and separation-pay protections.'
 : 'This accrual is paid sick leave under Colorado’s Healthy Families and Workplaces Act (HFWA), not a new vacation benefit. It is available as earned without a probationary waiting period. Other existing vacation/PTO entitlements are unchanged.';
 const clauses=[
 ['1. Effective date and replacement of pay terms','The agreed target effective date is Saturday, October 10, 2026. This amendment replaces conflicting compensation and accrual terms in the prior employment agreement for work on or after the agreed effective date. All other nonconflicting agreement terms remain in effect. No wage or leave already earned is reduced. If both parties complete signing after the target date, new rate conditions apply prospectively no earlier than completion of signing; payroll records that service-date boundary. The original employment Start Date and First Client Seen Date do not change.'],
 ['2. Individual category, level and rates','The individual schedule identifies the employee’s compensation category and level, service-credit rate, H-code direct rate, indirect hourly rate, support activity rate, sick-leave/PTO payment rate, and probation/minimum-workload rates. Category and compensation level are different from workload/benefit tiers. The completed individual schedule controls personal rates; the effective Colorado Billing & Compensation Appendix in the Workplace Handbook supplies service mappings and operating rules. Missing rates and level criteria must be completed before issue.'],
 ['3. Fee-for-service clinical compensation','For designated psychotherapy and other approved clinical credit services, compensation equals the assigned service credits multiplied by the employee’s service-credit rate. A 1.00-credit 90837 encounter pays one service-credit rate; a 0.75-credit service pays 0.75 of that rate. This is service compensation, not an hourly direct payment plus a separately paid 20% indirect supplement. The service rate includes the associated routine administrative component described in the handbook. Actual direct, administrative and support work is still recorded separately for timekeeping and wage compliance. Credits are not clock hours or payer billing units. Required work beyond the covered component must be reported and compensated without duplicate payment for work already covered.'],
 ['4. H-code compensation and automatic indirect pay','H-code services use the H-code direct rate and the compensation units in the effective handbook appendix. For Categories 2 and 3, the initial automatic indirect allowance is 10 minutes per direct-hour equivalent (1/6 hour; 16⅔%), paid in addition at the applicable indirect hourly rate. Category 1 reports actual indirect time separately and receives no automatic indirect allowance. For H0004, four qualifying 15-minute units equal one direct-hour equivalent: pay is 1.00 × H-code direct rate plus (10 ÷ 60) × indirect rate for Category 2 or 3. Payroll records those components separately. Fractional service quantities receive proportional amounts. The same encounter never receives both psychotherapy-credit and H-code direct payment. Actual work, payer claim units and compensation equivalents remain separate records.'],
 ['5. Sick-leave/PTO accrual equivalents and handbook ratio',`The Workplace Handbook maintains the dated sick-leave/PTO accrual ratio for fee-for-service staff, including the administrative-time equivalent associated with each service. Initially, 1.00 clinical credit receives 1.00 direct equivalent hour plus 0.20 administrative equivalent hour toward accrual: 1.20 ÷ 30 = 0.04 hour of sick leave. Therefore 25 credits produce 30 equivalent hours and earn 1 hour of sick leave. A 0.75-credit service earns 0.03 hour. For H-code work, use its paid direct and automatic indirect components once: For Category 2 or 3, 1.00 direct plus 1/6 indirect equals 7/6 accrual hours; (7/6) ÷ 30 is approximately 0.038889 hour of sick leave. Category 1 uses its direct hours plus separately reported paid indirect hours. Do not apply the clinical-credit 1.20 multiplier to H-code hours. Separately worked indirect and support time counts toward the applicable accrual basis. ${leave} Reconcile against all actual compensable hours and add any accrual required by HFWA; the credit formula is not a cap on statutory rights. Leave is paid at the stated PTO rate or a higher rate required by law. Preserve existing balances and applicable carryover and protected-use rights.`],
 ['6. Probation, workload rates and the 60-day transition','New employees begin at the probation rates shown in their individual schedule, which are the same rates used for minimum-workload compensation in each applicable pay category. Probation lasts at most 90 calendar days from the original Start Date, and ends earlier if management ends it manually or the employee reaches Tier 3. Reaching Tier 3 ends probation permanently; a later tier decrease does not restart probation. The minimum-workload reduction is waived for 60 calendar days from this amendment’s prospective effective date so the employee can meet the workload threshold. For an October 10, 2026 effective date, the waiver covers October 10 through December 8; December 9 is the first day it can apply. This waiver concerns minimum workload; it does not create a new probation period for existing employees or waive a new employee’s separate probation. After the waiver, applicable workload conditions and rates are those disclosed in the individual schedule and handbook.'],
 ['7. Support work, actual time and wage protection','Required onboarding, Provider Update reading/listening, training, meetings, compensable supervision and designated support work are paid at the applicable support activity rate. Record all compensable work, including additional work, actual review/correction of AI-generated notes and work outside scheduled hours. An allowance or accrual equivalent is not a cap on time worked. Approval and documentation rules do not forfeit earned wages. Payroll must apply applicable minimum wage, overtime, rest-period and regular-rate protections using actual hours; do not average away daily or workweek obligations.'],
 ['8. Handbook appendix, group policy and prospective changes','The dated Colorado Billing & Compensation Appendix and group moratorium in the Workplace Handbook are incorporated as operating policies. Approved psychotherapy codes use the service-credit pay category; H-codes use the H-code direct category plus the stated automatic indirect allowance. A code’s presence in the pay table does not establish clinical scope, payer billability or authorization to start a group. New independent groups are paused except for approved Skill Builders programming or a written exception following the handbook review process; 90853 is not blanket authorization. The handbook records the accrual ratio and H-code indirect percentage by version and effective service date. Revisions are prospective, with written notice before affected work and any agreement required by existing terms. A handbook edit alone does not activate a payroll setting, reduce an agreed individual rate or change prior earned wages/leave.'],
 ['9. Employee acknowledgment and signatures','I have reviewed my individual category, level, regular and probation/minimum-workload rates, service-credit and H-code calculations, the sick-leave accrual ratio, and the 60-day minimum-workload waiver. I acknowledge the dated handbook appendix and group policy and agree to these prospective terms without waiving statutory rights. Employee signature/date: ____________________. ITSCO authorized representative signature/date: ____________________. Agreed effective date: ____________________.']
 ];
 return addLevelExpectationsToClauses(clauses.map(([title,body])=>`<h3>${title}</h3>${p(body)}`).join('\n'));
}
export function renderAmendment(data) {
 if(data.employee?.employmentType==='salaried' && data.compensationBasis!=='service_credit')return `<h1>ITSCO, LLC</h1><h2>Salary amendment review · October 2026</h2><p><strong>Private draft — not issued or signed.</strong></p><p>Employee: <strong>${escapeHtml(data.employee.name)}</strong></p><p>Your existing salary arrangement remains in effect. You are not being assigned a fee-for-service category or a per-credit rate through this draft.</p>${data.salary?.salary_per_pay_period?`<p>Current recorded salary: <strong>${money(data.salary.salary_per_pay_period)} per pay period</strong>. This is the saved salary record, not a new salary award.</p>`:''}<p>Any proposed change to salary, additional paid duties, or leave terms must be specified in a salary-specific amendment before it is released for signature. This draft does not replace the existing salary agreement.</p>`;

 const s=data.schedule||{},e=data.employee||{},issues=amendmentIssues(data),cat=Number(s.category),bonus=conditionalLevelBonus(s.level);
 const minutes=cat===1?0:Number(s.autoIndirectMinutes??10);
 const rows=[['Employee',e.name],['Role / credential',[e.title,e.credential].filter(Boolean).join(' · ')],['Prior agreement',e.originalAgreementDate||'[date or reference needed]'],['Agreed effective date','October 10, 2026; subject to completed signatures and the prospective boundary below'],['Category',`Category ${s.category||'—'} · ${CATEGORY_NAMES[s.category]||'[not assigned]'}`],['Level',s.level?`Level ${s.level}`:'[not assigned]'],['Level description',s.levelDescription||'[approved criteria needed]'],['Weekly paid indirect-work commitment','4 hours per week; 8 hours total while school-assigned. Actual work is paid separately at the agreed indirect rate.']];
 const details=`<h3>Your pay schedule</h3>${p(categoryDescriptions[cat]||'Confirm the assigned category before release.')}${personalRateTable(s)}${p(`Sick-leave payment rate: ${money(s.ptoRate)} per hour, or a higher rate required by law.`)}${bonus?p(`<strong>Conditional level-chart addition: +${money(bonus)}</strong> to the applicable clinical service-credit rate${cat===1?' or Category 1 H-code rate':''} only when you qualify for Tier 3 based on sessions per pay period. Your eligible clinical rate is ${money(Number(s.creditRate)+bonus)}${cat===1?`, and eligible H-code rate is ${money(Number(s.hcodeRate)+bonus)}`:''}. It is not included in the base rates above and is not guaranteed for periods below Tier 3.`):''}${p(cat===1?'No automatic H-code indirect allowance. Submit your actual indirect work at your indirect hourly rate.':![2,3].includes(cat)?'Your H-code indirect allowance will be shown after your approved category is assigned. Category 1 submits actual indirect time; Categories 2 and 3 receive 10 minutes per direct-hour equivalent.':`H-code indirect allowance: ${minutes} minutes per direct-hour equivalent (${minutes} ÷ 60 hour; ${allowancePercent(minutes)}), paid at your applicable indirect rate. It applies to regular, probationary and minimum-workload H-code work.`)}${p('Clinical-credit sick-leave basis: 1.20 equivalent hours per credit ÷ 30. Twenty-five clinical credits earn one hour of sick leave. H-code hours use direct and paid indirect components once; they do not receive the clinical-credit multiplier.')}${p('Minimum-workload rate waiver: 60 calendar days from your prospective amendment effective date. New-hire probation is a separate condition.')}`;
 const differentials = [['Spanish-language pay differential',s.spanishDifferentialEligible,s.spanishDifferentialRates],['Denver location pay differential',s.denverDifferentialEligible,s.denverDifferentialRates]].filter(([,eligible])=>eligible).map(([label,,rates])=>`<h4>${label}</h4><p>You are marked eligible. ${[1,2,3].map(tier=>`Tier ${tier}: $${Number(rates?.[tier]||0).toFixed(2)}`).join(' · ')} per productive service-hour equivalent, using the applicable workload tier. This is separate from your base rate and the conditional Level 3–5 addition; it does not add time to indirect or support work.</p>`).join('');
 const clinicalExample=Number(s.creditRate)>0?`<p>One qualifying 90837 service assigned 1.00 credit pays <strong>${money(s.creditRate)}</strong> in service pay before eligible bonuses or wage adjustments. A 0.75-credit service pays ${money(Number(s.creditRate)*.75)}. One full credit earns 1.20 ÷ 30 = 0.04 hour of sick leave. The 0.20 administrative equivalent is not an additional cash-pay line.</p>`:'';
 const hExample=Number(s.hcodeRate)>0&&Number(s.indirectRate)>0?`<p>H0004, four qualifying 15-minute units: ${money(s.hcodeRate)} direct${cat===1?' plus separately reported actual indirect time. No automatic indirect supplement is added.':` plus (${minutes} ÷ 60) × ${money(s.indirectRate)} indirect = <strong>${money(Number(s.hcodeRate)+(minutes/60)*Number(s.indirectRate))}</strong>. The direct and indirect components count once toward sick-leave accrual; (1 + ${minutes}/60) ÷ 30 is approximately ${((1+minutes/60)/30).toFixed(6)} hour of sick leave.`}</p>`:'';
 return `<h1>ITSCO, LLC</h1><h2>Compensation Amendment · October 2026</h2><p><strong>Editable draft — not issued or signed.</strong></p>${issues.length?`<p><strong>Complete before issue:</strong> ${issues.map(escapeHtml).join(' ')}</p>`:''}<table><tbody>${rows.map(([a,b])=>`<tr><th>${escapeHtml(a)}</th><td>${escapeHtml(b)}</td></tr>`).join('')}</tbody></table>${details}${differentials}<h3>What each pay type means</h3>${payTypeDescriptions}<h3>Your worked examples</h3>${clinicalExample}${hExample}${data.commonClausesHtml||commonAmendmentClauses(data.leaveChoice)}${data.additionalTerms?`<h3>Individual notes</h3>${p(escapeHtml(data.additionalTerms))}`:''}`;
}
export function handbookSections({leaveChoice='sick',rates=[],rules=[],levels=[]}={}) {
 const clauses=commonAmendmentClauses(leaveChoice);
 const codeRows=rules.filter(r=>r.category==='direct'&&Number(r.credit_value)>0).map(r=>`<tr><td>${escapeHtml(r.service_code)}</td><td>${/^H\d/i.test(r.service_code)?'H-code direct + paid indirect':'Clinical service-credit rate'}</td><td>${escapeHtml(r.credit_value)}</td><td>${escapeHtml(r.pay_rate_unit)}</td></tr>`).join('');

 return [

 {slug:'colorado-billing-compensation-appendix',title:'Colorado Billing & Compensation Appendix',bodyHtml:
 '<h2>Clinical service-credit category</h2>'+p('Approved psychotherapy services, including 90832, 90834 and 90837, use the clinical service-credit rate in the employee’s schedule. Family psychotherapy, psychotherapy add-ons, crisis services and group psychotherapy use their approved code-specific credit values and applicable authorization requirements. The “top” service rate is a category, not a promise of a full credit for every code. A 1.00-credit service pays the full credit rate; a 0.75-credit service pays 75% of that rate. No additional 20% indirect cash line is added to a clinical service-credit encounter.')+
 '<h2>H-code category and indirect allowance</h2>'+p('Approved H-code services use the H-code direct rate, with the code-specific unit or minute conversion in the appendix, plus 10 minutes of automatic indirect time per direct-hour equivalent for Categories 2 and 3, paid at the applicable indirect rate. H0004: four qualifying 15-minute units = 1.00 direct-hour equivalent; automatic indirect = 10/60 hour (one sixth). Category 1 submits actual indirect time separately and receives no automatic add-on. For Categories 2 and 3, 25 H-code direct-hour equivalents add 4⅙ indirect hours, giving 29⅙ hours of accrual basis. This is an employee pay rule, not permission to bill automatic administrative time or to treat all H-codes as four units per hour.')+
 '<h2>Actual time, payer units and internal credits</h2>'+p('Record exact actual direct, indirect and support minutes separately from payer claim units and compensation credits. A qualifying 90837 maps to 1.00 compensation credit even when actual minutes differ from 60. Billing must follow the current payer’s requirements; a 53–74 minute example is not a universal maximum-duration rule. Verify scope, supervision, modifiers, place of service and telehealth rules for each service date. Never use leave-equivalent hours as actual hours worked.')+
 '<h2>Saved code inventory</h2><table><thead><tr><th>Code</th><th>Pay category</th><th>Saved credit value</th><th>Entered basis</th></tr></thead><tbody>'+codeRows+'</tbody></table>'+p('These are saved payroll mappings, not a payer fee schedule or certification of billability. Validate every mapping before activation. Required work remains compensable even if no claim can be submitted.')+

 '<h2>Probation and transition</h2>'+p('Probation is at most 90 calendar days from original start, ends on an earlier manual waiver or achievement of Tier 3, and never restarts after Tier 3. Probation uses the disclosed minimum-workload rate in each pay category. Minimum-workload reductions are waived for 60 calendar days after the amendment’s prospective effective date. An October 10 effective date is protected through December 8; the reduction can first apply December 9. The waiver does not restart or extend probation. Track service dates across every rate boundary.')+
 '<h2>Versioned changes</h2>'+p('Maintain the clinical-credit mappings, H-code indirect percentage and sick-leave ratio in the dated appendix. State the effective service date and provide written notice, plus agreement where required, before affected work. Preserve prior tables and signed schedules for late-entered services. Handbook edits alone do not enable payroll or reduce signed personal rates.')},
 {slug:'category-level-rate-schedule',title:'Category and level rate schedule',bodyHtml:categoryRateSchedule(rates,levels)},
 levelExpectationsHandbookSection(),
 {slug:'paid-time-off-and-colorado-sick-leave',title:'PTO/sick-leave accrual ratio for fee-for-service staff',bodyHtml:
 '<h2>Initial ratio: 20% administrative equivalent</h2>'+p('Clinical credits × 1.20 ÷ 30 = sick-leave hours earned. The direct bucket receives 1.00 equivalent hour per credit and the administrative bucket receives 0.20. Thus 25 credits = 30 equivalent hours = 1 hour of sick leave; 0.75 credit = 0.90 equivalent hour = 0.03 sick-leave hour. The administrative equivalent affects accrual only for psychotherapy credit services and is already included in service pay.')+p('H-code direct hours and automatically paid indirect hours enter the respective accrual buckets once. For Categories 2 and 3, one direct hour + 10/60 indirect hour = 7/6 accrual hours. Category 1 uses separately submitted actual indirect time. Do not apply the clinical-credit 1.20 multiplier to H-code hours. Additional actual paid indirect and support time is included without double counting. Reconcile to all actual hours worked and add any HFWA shortfall.')+p('This remains protected paid sick leave, not a new vacation bank. It accrues without a probation waiting period and is paid at the employee’s stated PTO rate or any higher statutory rate. Preserve existing balances and more generous earned terms. HFWA generally requires at least one hour per 30 hours worked up to 48 annually, with applicable carryover up to 48 hours; protected uses, reasonable notice, permitted documentation and nonretaliation requirements apply. Do not apply a generic 10-hour rollover cap or 30-day notice rule to protected sick leave.')+p('ITSCO may update the ratio prospectively through the dated handbook appendix and corresponding payroll policy version, with notice and any required agreement. Preserve accrued balances and historical service calculations. AI documentation does not change the ratio automatically or remove pay for required review and correction. Actual work remains compensable even with a zero allowance. Any separate vacation/general PTO entitlement retains its existing protections.')},
 {slug:'groups-moratorium-and-approval',title:'Group services: moratorium, Skill Builders and exceptions',bodyHtml:GROUP_MORATORIUM_HTML},
 {slug:'timekeeping-support-and-overtime',title:'Actual time, support activities and corrections',bodyHtml:p('Record all compensable work daily. Provider Update active review time is tracked by session and section and submitted for payroll review at the applicable support activity rate. Paused, hidden and timed-out periods are not automatically credited; report legitimate unrecorded work through a correction request. Actual work beyond an allowance remains compensable.')+p('Clinical credits and automatic indirect equivalents are not substitutes for actual time records. Apply applicable minimum wage, overtime, rest-period and regular-rate rules, including workweek and daily requirements. A late note, missing preapproval or denied claim does not erase earned wages. Handle documentation or approval concerns separately from paying for work performed.')},
 {slug:'communications-schoolcarebridge-and-transition',title:'Digital workplace and transition procedures',bodyHtml:p('Use authorized app records, assigned tasks and secure communication workflows. Respect each person’s notification and texting preferences. Healthcare communications rollout requires the executed BAA for the covered services and the required safeguards, consent and testing; do not assume that signing a BAA makes every ordinary SMS exchange protected.')+p('TherapyNotes transition is planned for Thanksgiving weekend, November 26–29, 2026. Continue using the designated record system until the go-live notice. Google Workspace retirement is staged: verify migrated mail, documents, calendars, permissions and an alternative sign-in before closing accounts. Quick View access requires an individual protected code and secure device.')},
 {slug:'october-2026-editor-change-map',title:'Handbook change tracker — October compensation revision',bodyHtml:'<ul><li>Replace old credit-plus-indirect wording for psychotherapy with the fixed service-credit calculation.</li><li>Use H-code direct-service pay plus 10 minutes of paid indirect time per direct hour for Categories 2 and 3; Category 1 reports indirect time separately.</li><li>Add separate direct/admin accrual equivalents: 1.20 ÷ 30, with no double multiplier on H-code time.</li><li>Replace the previous 90-day rollout waiver with a 60-day minimum-workload waiver; retain separate new-hire probation and early Tier 3 completion.</li><li>Add the group moratorium, Skill Builders exception and written-review procedure.</li><li>Preserve actual-time, statutory leave and earned-pay protections.</li><li>Use Start Date, First Client Seen Date, latest Employment Agreement Date and calculated probation end in lifecycle.</li><li>Add four separately paid indirect-work hours weekly, or eight total while school-assigned, and a dedicated compensation-level review section with one to two formal evaluations per year.</li></ul>'+p('These are editable revisions. Existing signed documents and published handbook versions remain archived. New calculation terms apply only after completed employee/countersigner agreement and explicit payroll enrollment, using a prospective service-date boundary. Complete all missing individual rates, prior agreement references and level criteria before release.')+'<h3>Source references</h3><ul>'+sources.map(([label,url])=>`<li><a href="${url}">${label}</a></li>`).join('')+'</ul>'}
 ];
}
