/**
 * Next Level Up in-office HIPAA Privacy Policy & Notice of Privacy Practices.
 * Used only for NLU office packets (paper + digital packet_hipaa_notice).
 */
export const NLU_OFFICE_HIPAA_NOTICE_HTML = `
  <h2>HIPAA Privacy Policy &amp; Notice of Privacy Practices</h2>
  <p>The Mental Range Collective (including ITSCO, Next Level Up, The Inner Strength Institute, PlotTwistCo, and MH4kidz)</p>
  <p><strong>THIS NOTICE DESCRIBES HOW MEDICAL INFORMATION ABOUT YOU MAY BE USED AND DISCLOSED AND HOW YOU CAN GET ACCESS TO THIS INFORMATION. PLEASE REVIEW IT CAREFULLY.</strong></p>

  <h3>Introduction and Our Legal Duty</h3>
  <p>We understand that information about your mental health and healthcare is personal. We are committed to protecting the privacy of your Protected Health Information (PHI) in accordance with federal and Colorado laws. As a healthcare provider, Next Level Up is required by law to maintain the privacy of your PHI, provide you with this notice of our legal duties and privacy practices, and abide by the terms of this notice.</p>
  <p>This Notice applies to Next Level Up and its authorized healthcare providers, staff, trainees, and business associates who support the delivery of your care. We will notify you promptly if a breach occurs that may compromise the privacy or security of your information, as required by law. We also follow any state laws that provide additional protections beyond federal law.</p>

  <h3>How We May Use and Disclose Your Health Information</h3>
  <p>The following categories describe the ways we use and disclose health information without your written authorization. For each category, we explain what we mean and give some examples. Not every use or disclosure will be listed, but all of our practices fall within these categories and are in accordance with HIPAA and applicable Colorado law.</p>
  <p><strong>Treatment:</strong> We may use and share your health information to provide, coordinate, or manage your care and related services. This includes sharing information, as needed, among our internal team members. For coordination with outside professionals (such as school counselors or primary care physicians), we will always obtain your prior written consent/authorization before sharing clinical details.</p>
  <p><strong>Payment:</strong> We may use and disclose your health information to bill and receive payment for the services we provide. For example, we might share necessary information with your insurance company to obtain authorization for treatment or reimbursement for services. This could include details like your diagnosis, treatment provided, and dates of service so that your insurer will pay for the care. We will only share the minimum necessary information for billing purposes. If you pay for a service or item out-of-pocket in full, you have the right to ask us not to share that information with your health insurer for payment or healthcare operations, and we will honor that request as required by law.</p>
  <p><strong>Health Care Operations:</strong> We may use and disclose your information for our healthcare operations – the administrative, technical, and quality improvement activities that allow us to run our organization and ensure that all clients receive quality care. This includes uses and disclosures necessary for internal management and to monitor the quality of our services. For example, we might use your information to evaluate the performance of our staff, to assess the quality of care you received, or to learn how we can improve our services. We may also combine information about many clients to decide what additional services we should offer, what services are not needed, or to compare our outcomes to other agencies for quality assurance. In doing so, whenever possible, we remove information that identifies specific clients to protect your privacy.</p>

  <h3>Use of Technology and AI Tools in Treatment &amp; Operations</h3>
  <p>As part of our treatment and operations, we use certain secure digital tools – including artificial intelligence (AI) powered tools – to enhance the accuracy and efficiency of our services. We want to be transparent about these tools and how we safeguard your information:</p>
  <p><strong>Clinical Note Documentation (AI-Assisted):</strong> Our clinicians may use secure AI-assisted software to help draft or summarize therapy notes and other clinical documentation. This means we utilize advanced computer programs to transcribe or organize information related to your care. Importantly, we do not include direct identifiers (like your full name or contact details) or unnecessary personal details when using these tools, so the notes are de-identified to the extent possible during drafting. The AI tool helps with the phrasing or structure of the note, but your provider reviews and finalizes all content. Once finalized, the note is entered into your official electronic health record (EHR), which is a secure system. Any temporary data or drafts created in the AI tool are deleted promptly after the note is transferred to our EHR. In this way, we ensure that no protected health information remains in the AI system beyond its immediate use for documentation. All access to the AI documentation tool is encrypted and secure, and only authorized staff can use it.</p>
  <p><strong>Audio Transcription (With Consent):</strong> With your explicit prior consent (or your parent/guardian’s consent for minors), we may occasionally audio-record a therapy session or a spoken clinical summary to ensure accuracy in documentation. For example, a therapist might record a summary of the session to transcribe it later. If we do this, we use a secure transcription process that may involve AI technology to convert speech to text. We will only do this if you have given written consent for that recording. The audio recording is used only to create a written clinical note or summary for your record. Immediately after transcription and verification, the audio file and any transcription data outside of our EHR are permanently deleted. The resulting written document is then stored in your EHR. We take care that even during transcription, the data is handled in a way that protects your identity – for instance, we may use your initials or a coding system during the transcription process rather than your full name, especially if the transcription service is a digital tool. Any AI-based transcription service or vendor we use will be a HIPAA-compliant Business Associate bound by a contract to safeguard your information. We will never retain recordings longer than necessary for transcription, and we will never use recorded sessions for any purpose other than creating your clinical documentation (unless you provide specific authorization for an alternate use).</p>
  <p><strong>Business Associate Agreement:</strong> PlotTwistCo operates as a trusted service provider (business associate) supporting our operations. We maintain a Business Associate Agreement (BAA) requiring them to safeguard your information in accordance with HIPAA. They may only use your information to support care coordination and are not permitted to use it for independent purposes, including marketing or communication. They are also required to maintain strong security practices and prevent any re-identification of de-identified data.</p>
  <p><strong>Care Coordination via PlotTwistCo App:</strong> We utilize a secure care management application provided by PlotTwistCo as part of coordinating and enhancing your services. This tool allows authorized healthcare providers involved in your care to temporarily access and share relevant medical information and care plans in order to support coordinated, continuous treatment. For example, members of your care team (such as a therapist and a case manager) may use this tool to stay aligned on your treatment needs and progress.</p>
  <p><strong>Safeguards:</strong> Any information entered into or viewed through this application is protected with industry-standard encryption and security controls. The PlotTwistCo application does not replace our primary electronic health record (EHR); it is used only as a supplementary coordination tool. Information shared through this system is limited to the minimum necessary and is used on a temporary, need-to-know basis. For example, a summary of goals or a progress update may be shared rather than a full record. Information within the application is routinely synchronized with or transferred to our primary EHR within a short period. Any temporary data stored in the application is deleted or made inaccessible once it is no longer needed.</p>
  <p><strong>Safeguards and Data Privacy in AI Workflows:</strong> Whenever we use any of the above digital or AI-assisted tools, we implement rigorous safeguards to protect your privacy and rights. Encryption: All electronic systems and devices we use (including the AI tools, transcription services, and the PlotTwistCo app) employ encryption in transit and at rest, meaning your information is encoded so that only authorized people can access it. We continuously update our security practices to meet or exceed modern standards and address emerging cybersecurity threats. De-identification: We use de-identified data whenever possible in these workflows. “De-identified” means information that can reasonably identify you (such as your name, contact info, or other direct identifiers) is removed or obscured, in line with HIPAA’s de-identification standards. For example, an AI tool might see “Client X” or initials instead of your name, and might not receive other direct identifiers. According to federal regulations, information that does not identify an individual (and cannot reasonably be used to identify them) is not considered identifiable health information, which is a standard we strive to achieve when using these tools. Furthermore, any vendor or service that assists us with AI or data processing is contractually forbidden from trying to re-identify any de-identified information or using your data for their own purposes. Access Controls: Only authorized members of our workforce or our vetted business associates can access the tools and information, and only as necessary for their job duties. We train our staff on these privacy practices and on how to handle data when using AI, so they understand the importance of not including unnecessary personal details. Consent and Choice: Where your consent is required (such as for audio recordings or certain data sharing), we will obtain it explicitly and in writing. Using these technologies will not override your privacy rights – for instance, if you prefer that we do not use a particular technology in handling your information, you have the right to request a restriction (see “Your Rights” below) and we will accommodate reasonable requests whenever feasible. Transparency: We want you to be fully informed about these practices. Please feel free to ask us any questions about our use of AI or other technology in your care. Our staff are prepared to explain how these tools work to assist in your treatment and operations, and how your information is protected. We believe that being open about these tools is important for maintaining your trust. You will be informed if any significant new technology or AI process will be used with your health information in a way that wasn’t described here, and we will update this notice as needed to reflect changes in our practices.</p>

  <h3>Other Uses and Disclosures Permitted or Required by Law</h3>
  <p>We may use or disclose your PHI in certain other situations without your authorization, as allowed by law or required by law. For example:</p>
  <ul>
    <li><strong>Required by Law:</strong> We will disclose health information about you when required to do so by federal, state, or local law. This includes reporting certain information to authorities as mandated by law. We will only disclose the information specifically required and will do so in compliance with the relevant law.</li>
    <li><strong>Public Health Activities:</strong> We may disclose PHI to public health authorities authorized to receive such information for purposes of preventing or controlling disease, injury, or disability. For example, we might report certain communicable disease information to the Colorado Department of Public Health if required by law, or notify people who may have been exposed to a disease as permitted by law.</li>
    <li><strong>Health Oversight Activities:</strong> We may disclose PHI to governmental or regulatory agencies that oversee healthcare systems or providers, for activities such as audits, inspections, licensure, or disciplinary actions. These oversight activities are necessary for the government to monitor the healthcare system, government programs, and compliance with civil rights laws.</li>
    <li><strong>Reports of Abuse, Neglect or Domestic Violence:</strong> If we believe you are a victim of abuse, neglect, or domestic violence, we may disclose PHI to the appropriate governmental authority authorized to receive such reports, such as a state child protective agency or adult protective services, as required or permitted by law. We will only disclose this information to the extent required by law or if you agree to the disclosure, and we will inform you promptly unless informing you would place you at risk of serious harm or is otherwise not required.</li>
    <li><strong>Legal Proceedings:</strong> We may disclose PHI in response to a court or administrative order, or in response to a subpoena, discovery request, or other lawful process, but only if efforts have been made to notify you or secure a protective order, as required by law. We will always attempt to ensure that only the minimum necessary information is disclosed and that appropriate safeguards are in place.</li>
    <li><strong>Law Enforcement:</strong> We may release PHI to law enforcement officials under certain circumstances – for example, to report certain types of wounds or injuries as required by law, or in response to a valid court order, warrant, or subpoena; to identify or locate a suspect or missing person; or to report a crime in emergency circumstances. Any disclosure to law enforcement will be done strictly in accordance with legal requirements.</li>
    <li><strong>Serious Threats to Health or Safety:</strong> We may use or disclose PHI if necessary to prevent or lessen a serious and imminent threat to your health or safety, or the health or safety of another person or the public. Any disclosure would be to someone able to help prevent the threat (for example, disclosing relevant information to the police or to a potential victim). This includes instances such as if you make a serious threat of violence towards an identifiable person or yourself. In such cases we may have a legal duty under Colorado law to take action, which could include warning the potential victim or notifying law enforcement (often referred to as the duty to warn and protect). We will only share the information necessary to address the threat.</li>
    <li><strong>Specialized Government Functions:</strong> We may disclose PHI for certain specialized government functions, such as for military or veteran activities if you are or were a member of the armed forces, for national security or intelligence activities as required by law, or for the protection of the President and other authorized persons.</li>
    <li><strong>Workers’ Compensation:</strong> We may disclose health information as authorized by and to the extent necessary to comply with laws relating to workers’ compensation or similar programs that provide benefits for work-related injuries or illness.</li>
    <li><strong>Research:</strong> In some cases, we may use or share your information for health research. All research projects are subject to a special approval process. We will either get your explicit consent to use your PHI for research, or we will ensure that your privacy is protected by removing identifiers or through other safe harbors permitted by law. If researchers are given access to your information, they must also agree to keep it confidential.</li>
    <li><strong>Business Associates:</strong> We may share your health information with trusted service providers (referred to as business associates) who perform services on our behalf that require access to Protected Health Information. Examples include billing services, secure data storage providers, and technology platforms that support our operations. Whenever we share information with a business associate, we have a Business Associate Agreement (BAA) in place that requires them to safeguard your information in accordance with HIPAA. These providers may only use your information to perform services for us and are not permitted to use it for their own purposes, including marketing or independent communication. We require all business associates to implement appropriate administrative, technical, and physical safeguards to protect your information and to notify us of any unauthorized use or disclosure.</li>
  </ul>

  <h3>Uses and Disclosures Requiring Your Authorization</h3>
  <p>In general, we will not use or disclose your health information for any purpose not described in this notice unless you give us your written Authorization. If you do provide an authorization, you may revoke it at any time by submitting a written revocation, and we will stop the future use or disclosure of your information for that purpose (except to the extent we have already acted in reliance on your authorization). The following specific uses and disclosures will only be made with your authorization:</p>
  <ul>
    <li><strong>Psychotherapy Notes:</strong> Notes recorded (in any medium) by a mental health professional documenting or analyzing the contents of a private counseling session and that are separated from the rest of your medical record are given special privacy protections. We will not disclose psychotherapy session notes without your written authorization except in limited circumstances (for example, certain legal processes or oversight of the practitioner).</li>
    <li><strong>Marketing:</strong> We will not use or disclose your PHI for marketing purposes unless you give us authorization. “Marketing” means communications about a product or service that encourage recipients to purchase or use the product or service, except for certain permitted communications such as those about our own services or those that involve a promotional gift of nominal value. If we ever seek to send you marketing communications for which HIPAA requires consent, we will obtain your authorization. You have the right to opt out of any such communications at any time.</li>
    <li><strong>Text Messaging and Communication Privacy:</strong> We do not share your phone number, text message content, or SMS opt-in consent with trusted service providers (business associates) for their independent communication or marketing purposes. Any messages you receive will be sent directly from Next Level Up. If you choose to receive information about services or opportunities offered by other organizations, those organizations will only contact you if you provide your information and consent directly to them.</li>
    <li><strong>Sale of PHI:</strong> We will never sell your health information to a third party without your explicit authorization. Selling PHI (exchanging it for direct or indirect remuneration) is generally prohibited by law without consent.</li>
    <li><strong>Other Situations:</strong> Any other use or disclosure of your PHI that is not described in this notice will be made only with your written authorization. For instance, if we want to use your testimonial or story publicly, or share information for purposes outside of treatment, payment, healthcare operations, or the specific exceptions above, we would ask for your written permission.</li>
  </ul>

  <h3>Special Protections for Sensitive Information</h3>
  <p>Certain types of health information may be subject to additional protections under federal or state law. We will follow all applicable laws that provide stricter privacy safeguards than HIPAA. For example:</p>
  <ul>
    <li><strong>Substance Use Disorder Records:</strong> If we have information about you from a federally assisted substance use disorder treatment program, that information is protected by federal law 42 CFR Part 2. In general, we cannot disclose records relating to substance use diagnosis, referral, or treatment without your written consent, even for treatment, payment, or healthcare operations, unless an exception under Part 2 applies. We will not share any Part 2-covered records with others (even other healthcare providers) without your consent, except in a medical emergency or other limited circumstances as permitted by law. Any disclosure of such records you authorize will include a notice that redisclosure is prohibited or limited by law.</li>
    <li><strong>Mental Health Communications:</strong> As noted earlier, Colorado law protects the confidentiality of communications between clients and mental health professionals. We generally will not disclose any communication from your counseling or therapy sessions without your consent, except as required by law (for example, mandatory reporting or safety-related exceptions). This state protection is in addition to HIPAA’s protections, and whenever state law is more protective or restrictive than federal law, we will follow the law that gives you greater privacy.</li>
    <li><strong>HIV/AIDS or Communicable Disease Information:</strong> Colorado law may provide additional protections for information related to HIV/AIDS testing or treatment and certain communicable disease information. If applicable, we will obtain any required consent before sharing such information, except where disclosure is mandated (for instance, to public health authorities).</li>
    <li><strong>Minors’ Health Information:</strong> If you are under 18 and are authorized by law to consent to certain services (for example, outpatient psychotherapy services in Colorado for minors 12 and older in certain situations), those records might be kept confidential from parents or guardians in accordance with Colorado law. We will follow any state laws that permit minors to consent to treatment and that protect the privacy of those treatment records. Generally, parents or legal guardians have the right to access a minor child’s medical information, but there are exceptions when a minor is allowed by law to consent to care on their own or when disclosing information to a parent could be detrimental. We will carefully follow those laws and will clarify with minors and parents what information can be shared.</li>
  </ul>
  <p>If a law (state or federal) ever prohibits or materially limits a use or disclosure of PHI that is permitted under HIPAA, we will follow the more protective law. Conversely, if another law requires us to disclose information that HIPAA would otherwise permit us to refrain from disclosing, we will make the disclosure as required (for example, certain mandatory public health reporting). In each case, we will include in this notice (or otherwise inform you) sufficient detail to understand any special rules that apply to your information.</p>
  <p><strong>Potential Redisclosure:</strong> Please note that when we disclose your health information to outside entities (for example, to a specialist or to a school, or pursuant to your authorization), that information may at times be redisclosed by the recipient and may not be protected by the HIPAA Privacy Rule anymore. For instance, if you instruct us to send a copy of your records to a family member or if records are subpoenaed in a lawsuit, those receiving the information might not be bound by HIPAA. However, many recipients (such as other healthcare providers, health plans, or our business associates) are themselves obligated to protect your information. Even when not required, we will communicate to recipients the importance of keeping your information confidential. In certain cases (such as with substance use treatment records or mental health records under Colorado law), re-disclosure by recipients is strictly limited by law, and we will include required notices to that effect when we send out such information.</p>

  <h3>Your Rights Regarding Your Health Information</h3>
  <p>You have the following rights with respect to the health information we maintain about you:</p>
  <ul>
    <li><strong>Right to Inspect and Copy:</strong> You have the right to see and get copies of your health information that we maintain in your designated record set, including medical and billing records. To inspect or copy your records, you must submit a written request to us (contact information is at the end of this notice). We will provide a copy or a summary of your health information, usually within 30 days of your request, as required by law. We may charge a reasonable, cost-based fee as permitted by law. In certain limited situations (for example, if a healthcare professional determines that releasing the information could endanger you or someone else), we may deny your request to inspect or copy part of your record. If we deny your request, we will provide you with a written denial explaining our reasons and describing any rights you may have to have the denial reviewed. Electronic Records: If your PHI is maintained electronically, you have the right to request an electronic copy of your record, and you may also direct us to transmit a copy directly to another entity or person you designate. We will make reasonable efforts to provide the information in the form or format you request (e.g., PDF or via a secure portal), if it is readily producible in that format.</li>
    <li><strong>Right to Request Amendment:</strong> If you believe that health information we have about you is incorrect or incomplete, you have the right to request that we correct or add to the record. Your request must be in writing and provide a reason for the amendment. We may deny your request if we did not create the information (such as a report from an outside provider), unless the original creator is not available to act on it; or if we believe the record is accurate and complete as is; or if the information is not part of the health information you are permitted to inspect (like psychotherapy notes or information compiled for legal proceedings). If we deny the request, we will give you a written explanation. You have the right to submit a written statement of disagreement, which we will attach to your records. If we grant the request, we will make the correction or addition and inform you when it is done, and we will make reasonable efforts to inform others who have copies of the incorrect information so they can update their records.</li>
    <li><strong>Right to an Accounting of Disclosures:</strong> You have the right to request a list (accounting) of certain disclosures of your PHI that we have made outside of treatment, payment, or healthcare operations. This accounting will not include routine disclosures (like those made to you or for treatment, payment, and operations, or those you authorized), but it will include many disclosures made for public purposes or legal requirements. For example, you can request an accounting of any disclosures we made to state health authorities for reportable diseases, or to law enforcement under certain circumstances. To request this, send us a written request specifying the time period (which can be up to six years prior to the date of your request). If you ask for this list more than once in a 12-month period, we may charge you a reasonable fee for each additional request to cover our costs. We will inform you of the fee in advance and give you a chance to withdraw or modify your request if you do not wish to pay the fee.</li>
    <li><strong>Right to Request Restrictions:</strong> You have the right to request that we limit the uses or disclosures of your health information for treatment, payment, or healthcare operations. You may also request that we limit the information we share with certain individuals involved in your care or payment for your care, like a family member or friend. For example, you might ask that we not disclose information about a particular therapy session to a certain family member. We are not required to agree to most restriction requests. However, if we do agree, we will comply with your request unless the information is needed to provide you emergency treatment or as required by law. One important exception: if you pay for a service out-of-pocket in full and request that we not tell your health insurer about that specific service, we must honor that request (except where we must share information for legal reasons). Otherwise, while we will consider your request, we may politely decline if it would hinder your care or our operations. That said, we recognize that you might have special concerns about the use of technology or other aspects of privacy. For instance, if you prefer that we not use certain AI tools or electronic systems with your information, please let us know. We will weigh any such request seriously and will accommodate it if possible. We want you to feel comfortable with how your information is handled. If we cannot feasibly comply, we will explain why (for example, certain documentation may be integral to our operations or required by law). All requests for restrictions should be made in writing, and we will respond in writing.</li>
    <li><strong>Right to Request Confidential Communications:</strong> You have the right to request that we communicate with you about your health matters in a certain way or at a certain location to further protect your privacy. For example, you can ask that we only contact you at a specific phone number or mailing address, or that we send correspondence in a sealed envelope rather than a postcard, or communicate via email instead of phone. We will accommodate all reasonable requests. You do not need to provide a reason for the request, but your request must specify how or where you wish to be contacted. If costs are associated with an alternative method (for example, mailing to a PO Box), we may require you to assume those costs if they are significant, but typically alternate communications can be arranged at no cost.</li>
    <li><strong>Right to a Paper Copy of This Notice:</strong> You have the right to a paper copy of this notice at any time, even if you have agreed to receive it electronically (for example, via our website or email). You may also download a copy from our website, but if you’d like us to hand or mail you a paper copy, please ask at our office or contact us and we will provide one promptly. This notice is posted prominently at our service locations and on our website.</li>
    <li><strong>Right to Be Notified of a Breach:</strong> If a breach of your unsecured PHI occurs (meaning someone who is not authorized accesses or discloses your information in a way that compromises its privacy or security), we will notify you without unreasonable delay and no later than required by law. Our notification will include a brief description of what happened, the information involved, steps we are taking to investigate and mitigate the harm, and, if applicable, recommendations for you to protect yourself. We take any such incidents very seriously and work hard to prevent them with robust security measures.</li>
    <li><strong>Right to Withdraw Consent or Opt-Out of AI Usage:</strong> We want to make sure you are comfortable with our use of modern tools in your care. You have the right to discuss any concerns about our use of AI or other technology in handling your information. In any case where we rely on your consent to use such a tool (for instance, recording a session for transcription), you have the right to refuse or withdraw that consent at any time. Your decision will not affect your access to care. We will then make alternative arrangements to document or provide services without using the tool you’re not comfortable with. Even where your consent is not necessarily required by law (such as internal AI-assisted note drafting that doesn’t use identifiable info), you still have the right to object or express concerns. We pledge to be transparent and to honor reasonable requests to not use certain technologies with your information, as noted above in “Right to Request Restrictions.”</li>
  </ul>

  <h3>Additional Information and Complaints</h3>
  <p><strong>Changes to This Notice:</strong> We reserve the right to change the terms of this Privacy Policy and Notice of Privacy Practices as laws change or as our practices change. If we make a material change, we will revise this notice to reflect the change. The new notice will be effective for all PHI that we maintain at that time, and we will make the revised notice available upon request, in our offices, and on our website. For instance, as federal or Colorado laws evolve – such as new guidance on the use of artificial intelligence in healthcare – we will update our practices and this notice to remain in full compliance and to keep you informed. The effective date of this notice is noted below, and any updated notice will also have an effective date listed. We encourage you to periodically review our Notice of Privacy Practices to be aware of how we protect your information.</p>
  <p><strong>Questions, Concerns, or Complaints:</strong> If you have any questions about this notice or how we handle your health information, please contact us at the information provided below. We welcome your questions and feedback. If you believe your privacy rights have been violated, you have the right to file a complaint with us or directly with the U.S. Department of Health and Human Services (Office for Civil Rights). You will not be retaliated against or penalized for filing a complaint. To file a complaint with us, you may submit it in writing to our Privacy Officer. We will address all concerns and do our best to resolve any issues. Contact information for filing a complaint with HHS/OCR can be provided by our staff or found on the HHS website.</p>

  <h3>Contact Information</h3>
  <p>Privacy Officer, The Mental Range Collective<br />
  Michael Mendez<br />
  437 Windchime Place<br />
  Colorado Springs, CO, 80919<br />
  833-444-8726<br />
  PO@NextLevelUpLCC.com</p>
  <p>You may contact our Privacy Officer with any questions about this notice or to exercise any of your rights described herein. We are here to help you understand this policy and your rights. If you have questions about the use of AI tools, digital apps, or any other aspect of your privacy, please do not hesitate to reach out. We will gladly explain more and ensure you feel comfortable with how your information is handled.</p>
`.trim();
