import {itscoSuggestedTopicEdits} from './itscoOctober2026SuggestedEdits.js';
import {spanishIntakeProcedure} from './october2026UpdateRevisions.js';
import {defaultSectionConfig} from '../constants/providerUpdateSections.js';
const p=t=>`<p>${t}</p>`;
const scoped=body=>body.replaceAll('https://app.itsco.health/itsco/','https://app.nextleveluplcc.com/nlu/');
export const nluRefreshSections=()=>({...defaultSectionConfig(),spanish_intake:true,amendments:false});
export const nluRefreshAudience={license:{mode:'auto'},client_fall_update:{mode:'auto'},school_availability:{mode:'auto'},supervision_hours:{mode:'auto'}};
export const nluRolloutNote='Draft held for a possible two-week delay. No send date is scheduled. Confirm the rollout date before issuing invitations. NLU pay categories, rates, agreement effective dates, and signed documents remain agency-specific; the amendment section stays off until NLU amendments are ready.';
export function nluRefreshTopics(){
 const shared=(key,icon)=>({key,icon,...itscoSuggestedTopicEdits[key],body:scoped(itscoSuggestedTopicEdits[key].body)});
 return [
 {key:'welcome',title:'Next Level Up · your team update',icon:'heart',body:p('Welcome to your NLU staff update. This administrative update is part of the same invitation as your profile, availability, communication choices and handbook review. Complete each section and continue to the next. You can save progress and return through your invitation.')+p('Required review time is tracked while you are actively using the updater. Timed-out and inactive periods are excluded. Use the Technology help option if your recorded time needs review.')},
 {key:'profile',title:'Your profile, languages and NLU website',icon:'client',body:p('Review your current photo, introduction, displayed role, credentials, gender and session languages. List another language only when you are proficient enough to conduct sessions in it, and indicate proficiency.')+p('Deselect the areas you do not serve. Highlight exactly three top choices in each applicable focus category; other areas you have not excluded can still match a client’s search. Your public profile highlights your top choices.')+p('Review your profile near the end of the update. Open your live page, copy your personal link, or download an NLU-branded QR code. Your saved changes and published availability appear there.')+p('<a href="https://nextleveluplcc.com" target="_blank" rel="noopener">Visit the NLU website ↗</a>')},
 {key:'availability_profiles',title:'Office bookings, recurring availability and waitlists',icon:'calendar',body:p('First review each office reservation. Confirm it or remove an incorrect reservation to release that room. Existing client appointments remain separate.')+p('Choose Open, Waitlist or Closed independently for in-person and virtual clients. Closed profiles remain listed. Open profiles with published availability receive priority; a dashboard reminder appears when openings are missing.')+p('In Set Availability, select reserved office time to offer in-person, virtual or both formats, or keep it private. Click an empty hour to request a room or publish virtual availability. Choose weekly, every other week or every four weeks. Room requests need scheduling review; publishing a virtual opening also sets Virtual to Open. No meetings or one-time openings are created here.')+p('Keep your typical availability current so clients can understand your schedule when joining your waitlist. Contact hours separately control routine notifications.')},
 {key:'communications',title:'Enrollment preferences, notifications and contact hours',icon:'chat',body:p('Answer each applicable Yes/No choice in the updater and review the Communications Use Agreement. In-app client texting means client SMS reaches your app inbox through the shared agency number. Declining client-text alerts lets the client choose whether to ask support to respond. Personal-phone relay, voice and recording features remain subject to agency setup and availability.')+p('Choose eligible email/text alerts for appointment replies, kiosk arrivals, messages, meetings and matching Client Exchange opportunities. Appointment replies can be cancellations only, confirmations only or all replies. Arrival texts identify the appointment time; clinical feedback stays in the app and permitted email workflow.')+p('Client Exchange email and text choices are together. Matching alerts apply only while you are Open for that appointment format; unknown matching information may still qualify. Review the client in the app before requesting them.')+p('You can change Enrollment preferences in Account settings; Notifications is directly below it. Enrollment controls which eligible text channels can be enabled. Most notification types are app-only. Optional in-app types can also be disabled from an individual notification; required types stay on.')+p('Choose contact hours that follow saved availability, Anytime, or your own daily windows. For app-only email, choose immediate personal reminders or reminders after 24 business hours. Enabled kiosk arrival emails are urgent and do not wait for that digest.')+p('NLU uses its own sender, campaign and recorded consent. ITSCO’s voting number and text-assistant enrollment are not NLU enrollment. Features appear only when available for NLU.')},
 shared('tasks_my_work','check'),shared('notes_workspace','document'),shared('supervision','cap'),
 shared('office_kiosk','spark'),shared('business_cards','document'),shared('quick_view','pin'),
 {key:'library_transition',title:'The app, Library and account transitions',icon:'gear',body:p('Use the app’s Tasks, My Work and approved document Library for the work assigned to you. Account settings opens full screen and can be dismissed when finished. Email settings lets you add optional plain text above the company signature.')+p('Prepare your non-SSO password and optional passkey under Security and passwords. Keep using your current approved email and Google sign-in until your own migration is confirmed. This update does not shut down your Google account or set a new email migration date.')+p('NLU’s EHR and email transition dates will be confirmed separately. Continue documentation in the currently designated system until your team receives the confirmed changeover instructions.')},
 {key:'spanish_intake',title:'Spanish-speaking families · intake handoff',icon:'chat',body:spanishIntakeProcedure},
 {key:'school_assignments',title:'School assignments and client follow-up',icon:'cap',body:p('If you have school assignments, review your actual school, days, hours and slots in the updater. School sections appear for assigned staff; use the assigned roster as the source of truth.')+p('Review the specific action beside each assigned client. Confirm returning clients are being seen, set requested dates, or submit a support ticket from that client row when something is incorrect, including duplicate records. The ticket includes the client context.')+p('School reminders identify a school visit and ask the family to report an absence or scheduling concern; they do not require a Yes confirmation. Notifications follow the provider’s enrollment and contact-hour choices.')},
 ];
}
