/** Shared editorial changes; no sending, payroll activation, or signature assignment. */
export const spanishSummary = `<p>Check the parent or guardian’s primary language in their paperwork and profile. For Spanish-speaking families, open <strong>Messages by Conversa → Spanish / Español</strong> and ask the group for parent-intake availability. Support adds the selected Spanish-speaking provider to the client’s authorized care team.</p><p>That provider completes and documents the intake, then supports ongoing parent check-ins and coordination. The assigned provider may attend and should supply a reviewed Note Aid treatment summary in the medical record. See the Workplace Handbook for the full procedure.</p>`;
export const quickViewInstall = `<p><strong>Save Quick View to your home screen:</strong> On iPhone or iPad, open your agency’s Quick View link in Safari, tap Share, then Add to Home Screen. On Android, open it in Chrome, tap ⋮, then Add to home screen or Install app. Open the new icon and use your six-digit code. Keep your device locked and save the code privately in your password manager.</p>`;
export function transitionNotice({itsco=true}={}) {
 return {title:'Moving into the app · TherapyNotes, Google Workspace & Grasshopper',body:
 `<p>We are bringing daily work into one app and retiring these services as each transition is completed.</p>
 <h3>TherapyNotes → our app’s EHR</h3><p>${itsco?'The EHR rollout is planned for <strong>November 26–29, 2026 (Thanksgiving weekend)</strong>. Complete all outstanding notes by <strong>Friday, November 27</strong>.':'Your agency’s EHR transition date will be confirmed separately.'} Training, step-by-step guides and support details will arrive before cutover. Continue using the current record system until the go-live notice.</p>
 <h3>Google Workspace → app email, meetings & Library</h3><p>Your Google work account will close after your migration. Email, documents in the Library, meetings, secure messages and SMS will be available in the app. You can share your calendar with Google. Prepare your app password or passkey now; keep using SSO until your account switches, then use your app sign-in with any required two-factor verification.</p>
 <h3>Grasshopper → app calls & messages</h3><p>Grasshopper will be retired after the phone transition; you will keep your extension. As app calling is enabled, calls will be logged to the client record, with your custom voicemail and contact hours. Assigned clients’ texts to the provider number will route to you in the app, with optional forwarding. Clients receive an automatic reply when your texting is off or they message outside your contact hours.</p>`};
}
export function communicationNotice({itsco=true}={}) {
 return {title:'App messaging, calling & team polls',body:`<p>Use Messages by Conversa for secure team and client messages. Enable the call, text and notification options you want in this Provider Update as they become available. Team polls let you respond from the app or an enabled text campaign.</p><p><strong>After your phone service moves fully into the app, share your confirmed new number with clients and guardians.</strong> Until cutover, continue using your current number and approved communication tools. ${itsco?'The optional staff text assistant uses 719-716-3884; text MENU for its available commands.':'NLU will provide its own confirmed phone and text-assistant details; do not use another agency’s campaign number.'}</p>`};
}
