<template>
  <div class="scb-partner" :class="{'scb-partner-guest':!auth.isAuthenticated}">
    <header class="scb-header"><SchoolCareBridgeBrand/><router-link to="/schoolcarebridge/partners">Our partners</router-link><router-link to="/schoolcarebridge/app/operations">Programs & bookings</router-link><router-link :to="schoolCareBridgePath()">Switch workspace</router-link><button v-if="auth.isAuthenticated" class="scb-button scb-outline" @click="auth.logout()">Sign out</button></header>
    <p v-if="loading" class="scb-status" role="status">Opening your workspace…</p>
    <section v-else-if="error" class="scb-status" role="alert"><h1>We couldn’t open this workspace</h1><p>{{error}}</p><button @click="load">Try again</button></section>
    <main v-else-if="!auth.isAuthenticated" class="scb-partner-signin">
      <div><p class="scb-eyebrow">SchoolCareBridge partner</p><img v-if="partner?.logoUrl" :src="asset(partner.logoUrl)" :alt="partner.name" class="scb-partner-logo"/><h1>{{partner?.name || 'Your agency'}}<br/>SchoolCareBridge</h1><p>Your schools, providers and student support, connected.</p><router-link :to="{path:schoolCareBridgePath(),query:{redirect:signInDestination}}" class="scb-button">Sign in with your email →</router-link></div><img src="/assets/mh4kidz/teamwork.webp" alt="Children working together"/>
    </main>
    <div v-else class="scb-workspace-layout">
      <aside class="scb-workspace-nav"><img v-if="partner?.logoUrl" :src="asset(partner.logoUrl)" :alt="partner.name"/><strong>{{partner?.name}}</strong><span>SchoolCareBridge workspace</span><nav aria-label="SchoolCareBridge workspace"><router-link v-for="item in tabs" :key="item.key" :to="schoolCareBridgePartnerPath(slug,item.key)" :aria-current="section===item.key?'page':undefined">{{item.label}}</router-link></nav><a v-if="partner?.workspaceMode==='connected'" :href="agencyWorkspace">Full agency workspace ↗</a><small>A program of MH4Kidz</small></aside>
      <main class="scb-workspace-main">
        <template v-if="section===''">
          <p class="scb-eyebrow">{{partner?.name}} · School operations</p><h1>Connected to your schools.</h1><p class="scb-workspace-lead">{{partner?.settings?.welcomeMessage || 'A clear view of your school partnerships and the people supporting them.'}}</p>
          <div class="scb-workspace-metrics"><article><strong>{{schools.length}}</strong><span>Accessible school portals</span></article><article><strong>{{providers.length}}</strong><span>Agency providers</span></article><article><strong>{{canManage?'Administrator':'Care team'}}</strong><span>Your workspace access</span></article></div>
          <div class="scb-workspace-actions"><router-link :to="schoolCareBridgePartnerPath(slug,'schools')"><h2>School portals</h2><p>Open a school, coordinate enrollment and find schedules.</p><span>View schools →</span></router-link><router-link :to="schoolCareBridgePartnerPath(slug,'clients')"><h2>Clients</h2><p>Choose a school to view the roster and authorized client records.</p><span>Open a roster →</span></router-link><router-link :to="schoolCareBridgePartnerPath(slug,'providers')"><h2>Providers</h2><p>Find your providers and manage their school assignments.</p><span>View your team →</span></router-link></div>
          <section class="scb-workspace-panel"><h2>Your school community</h2><div class="scb-school-list"><router-link v-for="school in schools.slice(0,6)" :key="school.id" :to="schoolCareBridgePath(school.slug)"><img v-if="school.logoUrl" :src="asset(school.logoUrl)" alt=""/><strong>{{school.name}}</strong><span>Open portal →</span></router-link></div><p v-if="!schools.length">Your school portals will appear here once they are connected and your account has access.</p></section>
        </template>
        <template v-else-if="section==='schools'||section==='clients'"><p class="scb-eyebrow">{{partner?.name}}</p><div class="scb-workspace-title"><h1>{{section==='clients'?'Client rosters':'Your school portals'}}</h1><button v-if="canManage&&section==='schools'" class="scb-button" @click="addingSchool=!addingSchool">{{addingSchool?'Close':'Add a school'}}</button></div><p>{{section==='clients'?'Choose a school to open the roster with your existing role and release-of-information access.':'Each school has its own identity, care partners and familiar tools.'}}</p>
          <form v-if="addingSchool" class="scb-workspace-panel scb-form" @submit.prevent="createSchool"><h2>Add a school portal</h2><label>School name<input v-model="schoolForm.name" required maxlength="255"/></label><label>Portal address<input v-model="schoolForm.slug" required pattern="[a-z0-9][a-z0-9-]+" placeholder="ashley"/></label><p>For an existing school, ask the program administrator to link its current record.</p><button class="scb-button" :disabled="saving">Create school portal</button></form>
          <div class="scb-school-list"><router-link v-for="school in schools" :key="school.id" :to="{path:schoolCareBridgePath(school.slug),query:section==='clients'?{sp:'roster'}:{}}"><img v-if="school.logoUrl" :src="asset(school.logoUrl)" alt=""/><strong>{{school.name}}</strong><span>{{section==='clients'?'View roster':'Open portal'}} →</span></router-link></div><p v-if="!schools.length">No schools are available to your account yet.</p>
        </template>
        <template v-else-if="section==='providers'"><p class="scb-eyebrow">{{partner?.name}}</p><h1>Your provider team</h1><p>Manage school assignments and schedules from each school’s Providers section.</p><div class="scb-provider-grid"><article v-for="provider in providers" :key="provider.id"><span class="scb-avatar">{{provider.first_name?.[0]}}{{provider.last_name?.[0]}}</span><h2>{{provider.first_name}} {{provider.last_name}}</h2><p>{{provider.credential||'Agency provider'}}</p></article></div><p v-if="!providers.length">No active providers are assigned to this agency yet. Your program administrator can help add accounts.</p><h2>School provider assignments</h2><div class="scb-school-list"><router-link v-for="school in schools" :key="school.id" :to="{path:schoolCareBridgePath(school.slug),query:{sp:'providers'}}"><strong>{{school.name}}</strong><span>Providers & schedules →</span></router-link></div></template>
        <template v-else-if="section==='settings'&&canManage"><p class="scb-eyebrow">Agency settings</p><h1>A few details. A familiar workspace.</h1><form class="scb-form scb-workspace-panel" @submit.prevent="saveSettings"><label>Support email<input v-model="settings.supportEmail" type="email"/></label><label>Workspace welcome message<textarea v-model="settings.welcomeMessage" maxlength="600" rows="3"/></label><label>Partner description<textarea v-model="settings.description" maxlength="600" rows="3"/></label><p>Agency logos, account access and additional features are managed with the SchoolCareBridge program team.</p><button class="scb-button" :disabled="saving">Save settings</button></form></template>
        <template v-else-if="section==='agreement'&&canManage"><p class="scb-eyebrow">MH4Kidz × {{partner?.name}}</p><h1>Your SchoolCareBridge agreement</h1><template v-if="agreement"><p class="scb-agreement-state">{{agreement.fullySigned?'Signed by both parties':agreement.status==='draft'?'Draft — not yet issued for signature':'Awaiting signatures'}} · Revision {{agreement.revision}}</p><p v-if="agreement.status==='draft'">The program administrator will assign this agreement to the authorized representatives after review.</p><button class="scb-button scb-outline" @click="printAgreement">Print / save a copy</button><router-link v-if="mySigningTask" class="scb-button" :to="{path:schoolCareBridgePartnerPath(slug,`tasks/documents/${mySigningTask}/sign`),query:{returnTo:schoolCareBridgePartnerPath(slug,'agreement')}}">Review and sign →</router-link><article class="scb-agreement-paper" v-html="agreementHtml"></article></template><p v-else>Your agreement is being prepared by the SchoolCareBridge program team.</p></template>
        <p v-else role="alert">This section is not available to your account.</p>
        <p v-if="notice" role="status" class="scb-workspace-notice">{{notice}}</p>
      </main>
    </div>
  </div>
</template>
<script setup>
import {computed,onMounted,ref,watch} from 'vue';
import {useRoute} from 'vue-router';
import DOMPurify from 'dompurify';
import {useAuthStore} from '../../store/auth';
import api from '../../services/api';
import {toUploadsUrl} from '../../utils/uploadsUrl';
import {schoolCareBridgePath} from '../../utils/schoolCareBridge';
import {schoolCareBridgePartnerPath} from '../../utils/schoolCareBridgeTenant';
import SchoolCareBridgeBrand from '../../components/schoolcarebridge/SchoolCareBridgeBrand.vue';
import '../../styles/schoolCareBridge.css';
import '../../styles/schoolCareBridgeWorkspace.css';
const route=useRoute(),auth=useAuthStore();
const slug=computed(()=>String(route.params.partnerSlug||'')),section=computed(()=>String(route.params.partnerSection||''));
const signInDestination=computed(()=>{const value=route.query.redirect;return typeof value==='string'&&value.startsWith(schoolCareBridgePartnerPath(slug.value)+'/')&&!value.includes('\\')?value:schoolCareBridgePartnerPath(slug.value);});
const partner=ref(null),schools=ref([]),providers=ref([]),canManage=ref(false),agreement=ref(null),loading=ref(true),saving=ref(false),error=ref(''),notice=ref(''),addingSchool=ref(false);
const schoolForm=ref({name:'',slug:''}),settings=ref({supportEmail:'',welcomeMessage:'',description:''});
const asset=value=>value?.startsWith('/assets/')?value:toUploadsUrl(value);
const tabs=computed(()=>[{key:'',label:'Overview'},{key:'schools',label:'School portals'},{key:'clients',label:'Clients'},{key:'providers',label:'Providers'},...(canManage.value?[{key:'settings',label:'Settings'},{key:'agreement',label:'Agreement'}]:[])]);
const agencyWorkspace=computed(()=>`https://plottwisthq.com/${encodeURIComponent(slug.value)}/dashboard`);
const agreementHtml=computed(()=>DOMPurify.sanitize(agreement.value?.html||''));
const mySigningTask=computed(()=>Number(agreement.value?.agency_signer_user_id)===Number(auth.user?.id)?agreement.value?.agency_task_id:Number(agreement.value?.operator_signer_user_id)===Number(auth.user?.id)?agreement.value?.operator_task_id:null);
async function load(){loading.value=true;error.value='';try{if(!auth.isAuthenticated){partner.value=(await api.get(`/schoolcarebridge/partner-brand/${slug.value}`,{skipAuthRedirect:true})).data.partner;return;}const {data}=await api.get(`/schoolcarebridge/tenants/${slug.value}`);partner.value=data.partner;schools.value=data.schools;providers.value=data.providers;canManage.value=data.canManage;settings.value={supportEmail:data.partner.settings?.supportEmail||data.partner.supportEmail||'',welcomeMessage:'',description:'',...data.partner.settings};if(section.value==='agreement'&&canManage.value)agreement.value=(await api.get(`/schoolcarebridge/tenants/${slug.value}/agreement`)).data.agreement;}catch(e){error.value=e.response?.data?.error?.message||'Please try again.';}finally{loading.value=false;}}
async function saveSettings(){saving.value=true;notice.value='';try{const {supportEmail,welcomeMessage,description}=settings.value;await api.put(`/schoolcarebridge/tenants/${slug.value}/settings`,{supportEmail,welcomeMessage,description});notice.value='Settings saved.';}catch(e){notice.value=e.response?.data?.error?.message||'Could not save settings.';}finally{saving.value=false;}}
async function createSchool(){saving.value=true;notice.value='';try{await api.post(`/schoolcarebridge/tenants/${slug.value}/schools`,schoolForm.value);addingSchool.value=false;schoolForm.value={name:'',slug:''};await load();notice.value='School portal created.';}catch(e){notice.value=e.response?.data?.error?.message||'Could not create this school.';}finally{saving.value=false;}}
function printAgreement(){window.print();}
watch(()=>auth.isAuthenticated,load);onMounted(load);
</script>
