<template>
 <div class="scb-site scb-operations"><header class="scb-header"><SchoolCareBridgeBrand/><nav aria-label="Program navigation"><router-link to="/schoolcarebridge/programs">Program catalog</router-link><router-link to="/schoolcarebridge/app">School portal</router-link><router-link v-if="workspace.canManage" :to="`/${workspace.operator?.slug}/finance-operations`">Finance Operations</router-link></nav></header>
 <main class="scb-workspace-main"><header class="scb-workspace-title"><div><p class="scb-eyebrow">A program of MH4Kidz</p><h1>{{workspace.canManage?'Programs & operations':'My school programs'}}</h1><p>Bookings, funding, invoices and verified payment receipts.</p></div><button class="scb-button scb-outline" @click="load" :disabled="busy">Refresh</button></header>
 <p v-if="error" role="alert" class="scb-workspace-notice">{{error}}</p><p v-if="notice" role="status" class="scb-workspace-notice">{{notice}}</p><p v-if="loading" role="status">Loading your workspace…</p>
 <template v-else>
 <nav class="scb-ops-tabs" aria-label="Workspace sections"><button v-for="t in tabs" :key="t" :aria-pressed="tab===t" @click="tab=t">{{t}}</button></nav>
 <section v-if="tab==='Programs'&&workspace.canManage" class="scb-workspace-panel"><div class="scb-workspace-title"><h2>Published programs and drafts</h2><button class="scb-button" @click="editor={}">Add program</button></div><p v-if="!workspace.financeEnabled">MH4Kidz Finance Operations needs setup before grant budgets and presenter expenses can be linked. <button v-if="platformAdmin" @click="enableFinance" :disabled="busy">Enable MH4Kidz finance workspace</button></p><SchoolCareBridgeProgramEditor v-if="editor" :key="editor.id||'new'" :program="editor" :workspace="workspace" :busy="busy" @save="saveProgram" @close="editor=null"/><div v-for="p in workspace.programs" :key="p.id" class="scb-ops-row"><div><strong>{{p.title}}</strong><small>{{p.typeLabel}} · {{p.published?'Published':'Draft'}} · {{p.presenterName}}</small></div><button class="scb-button scb-outline" @click="editor={...p}">Edit</button></div><p v-if="!workspace.programs?.length">No programs have been created. Add a reviewed offering to begin.</p></section>
 <template v-if="tab==='Bookings'">
  <section class="scb-workspace-panel"><h2>Request a school program</h2><form class="scb-form scb-ops-form" @submit.prevent="requestBooking"><div class="scb-ops-grid"><label>Program<select v-model="request.programId" required><option value="">Choose program</option><option v-for="p in catalog" :key="p.id" :value="p.id">{{p.title}} · {{p.presenterName}}</option></select></label><label>Your school<select v-model="request.schoolId" required><option value="">Choose authorized school</option><option v-for="s in schools" :key="s.id" :value="s.id">{{s.name}}</option></select></label><label>Start ({{timezone}})<input v-model="request.startLocal" type="datetime-local" required/></label><label>End ({{timezone}})<input v-model="request.endLocal" type="datetime-local" required/></label><label>Region<input v-model="request.region" required maxlength="120" placeholder="Denver Metro"/></label><label>Location or virtual arrangement<input v-model="request.location" required maxlength="500"/></label><label>Expected attendance<input v-model.number="request.attendance" type="number" min="1" required/></label><label>Language<input v-model="request.language" maxlength="120"/></label><label>Funding request<select v-model="request.fundingRequested"><option value="cash">School will pay</option><option value="grant">Grant funding requested</option><option value="partial">Partial assistance</option><option value="free">No-cost offering requested</option></select></label></div><label>Accessibility and arrangements<textarea v-model="request.accommodations" maxlength="2000" rows="2"/></label><label class="scb-ops-check"><input v-model="request.travelRequested" type="checkbox"/> Ask about travel outside the presenter’s service region</label><p>Do not include student names, health details or other private student records. This request does not reserve a date or authorize a charge.</p><button class="scb-button" :disabled="busy||!schools.length||!catalog.length">Send booking request</button></form></section>
  <section class="scb-workspace-panel"><h2>{{workspace.canManage?'Booking requests':'My bookings'}}</h2><p v-if="!workspace.bookings?.length">Your requests and accepted bookings will appear here.</p><article v-for="b in workspace.bookings" :key="b.id" class="scb-booking"><div class="scb-workspace-title"><div><h3>{{b.title}}</h3><p>{{b.school_name}} · {{when(b.requested_start)}} · {{b.timezone}}</p><strong>{{b.status}} · SCB-B-{{b.id}}</strong></div><button class="scb-button scb-outline" @click="selectBooking(b)">{{selected?.id===b.id?'Close':'Details'}}</button></div><template v-if="selected?.id===b.id"><p>{{b.region}} · {{b.location}} · {{b.attendance}} attendees · {{b.funding_requested}} funding</p><p v-if="b.travel_requested">Travel inquiry requested.</p><p v-if="b.accommodations">Arrangements: {{b.accommodations}}</p><div v-if="b.quote.totalCents!=null" class="scb-quote"><h4>Quote · {{b.quote.presenterName}}</h4><p>{{b.quote.scope}}</p><dl><dt>Delivery fee</dt><dd>{{money(b.quote.serviceCents)}}</dd><dt>Approved travel</dt><dd>{{money(b.quote.travelCents)}}</dd><dt>School contribution</dt><dd>{{money(b.quote.schoolCents)}}</dd><dt>Funding / subsidy</dt><dd>{{money(b.quote.fundingCents)}}</dd><template v-if="workspace.canManage"><dt>Presenter payable</dt><dd>{{money(b.quote.presenterCents)}}</dd><dt>MH4Kidz share</dt><dd>{{money(b.quote.operatorCents)}}</dd><dt>Platform payable</dt><dd>{{money(b.quote.platformCents)}}</dd></template></dl><p>Cancellation: {{b.quote.cancellationTerms}}</p><p>Travel: {{b.quote.travelTerms||'No additional travel agreed.'}}</p><p>Quote expires {{b.quote.expiresDate}}.</p><p v-if="b.quote.fundingNotes">Funding: {{b.quote.fundingNotes}}</p></div>
   <form v-if="workspace.canManage&&['requested','quoted'].includes(b.status)" class="scb-form" @submit.prevent="sendQuote(b)"><h4>Prepare quote</h4><div class="scb-ops-grid"><label>Standard delivery fee (USD)<input v-model="quote.service" type="number" min="0" step="0.01" required/></label><label>Approved travel (USD)<input v-model="quote.travel" type="number" min="0" step="0.01" required/></label><label>School pays (USD)<input v-model="quote.school" type="number" min="0" step="0.01" required/></label><label>Quote expires<input v-model="quote.expiresDate" type="date" required/></label><label>Finance program<select v-model="quote.financeProgramId"><option value="">Choose finance program</option><option v-for="p in workspace.financePrograms" :key="p.id" :value="p.id">{{p.name}}</option></select></label></div><label>Scope and deliverables<textarea v-model="quote.scope" required/></label><label>Cancellation, rescheduling and refund terms<textarea v-model="quote.cancellationTerms" required/></label><label>Travel approval and cap<textarea v-model="quote.travelTerms"/></label><label>Presenter payment terms<input v-model="quote.presenterPaymentTerms" required/></label><label>Grant / subsidy explanation<textarea v-model="quote.fundingNotes"/></label><button class="scb-button" :disabled="busy">Issue quote for school acceptance</button></form>
   <form v-if="b.status==='quoted'&&Number(b.requester_user_id)===Number(auth.user?.id)" class="scb-form" @submit.prevent="bookingAction(b,'accept',{authorizedToBook:authorized})"><label class="scb-ops-check"><input v-model="authorized" type="checkbox" required/> I am authorized to accept this quote and its cancellation terms for my school.</label><button class="scb-button" :disabled="busy">Accept quote</button></form>
   <form v-if="workspace.canManage&&['accepted','confirmed','completed'].includes(b.status)" class="scb-form" @submit.prevent="bookingAction(b,'expenses',funding)"><h4>Finance tracking</h4><p>Create or reopen the presenter and platform expense drafts. Finance managers review funding restrictions and approve costs in Finance Operations.</p><div class="scb-ops-grid"><label>Presenter funding allocation<select v-model="funding.presenterAllocationId"><option value="">Assign later in Finance Operations</option><option v-for="a in workspace.allocations" :key="a.id" :value="a.id">{{a.name}}{{a.grant_id?' · Grant':''}}</option></select></label><label>Platform funding allocation<select v-model="funding.platformAllocationId"><option value="">Assign later in Finance Operations</option><option v-for="a in workspace.allocations" :key="a.id" :value="a.id">{{a.name}}{{a.grant_id?' · Grant':''}}</option></select></label></div><button class="scb-button scb-outline" :disabled="busy||!workspace.financeEnabled">Prepare finance expenses</button><p v-if="b.presenter_expense_id||b.platform_expense_id">Linked expense references: presenter {{b.presenter_expense_id||'—'}}; platform {{b.platform_expense_id||'—'}}. <router-link :to="`/${workspace.operator.slug}/finance-operations`">Open Finance Operations →</router-link></p></form>
   <form v-if="workspace.canManage&&b.status==='accepted'" class="scb-form" @submit.prevent="bookingAction(b,'confirm',{presenterAvailabilityConfirmed:availability})"><label class="scb-ops-check"><input v-model="availability" type="checkbox" required/> Presenter confirmed this date, travel and availability, including their outside calendar.</label><button class="scb-button" :disabled="busy">Confirm booking and issue school invoice</button></form>
   <form v-if="workspace.canManage&&b.status==='confirmed'" class="scb-form" @submit.prevent="bookingAction(b,'complete',completion)"><h4>Record delivery</h4><label>Actual attendance<input v-model.number="completion.attendance" type="number" min="0" required/></label><label>Aggregate completion report<textarea v-model="completion.summary" required placeholder="Describe delivery and outcomes without identifying participants."/></label><label>Satisfaction score (optional, 1–5)<input v-model.number="completion.satisfaction" type="number" min="1" max="5"/></label><button class="scb-button" :disabled="busy">Complete and record platform fee</button></form>
   <p v-if="b.status==='completed'">Completed: {{b.completion.attendance}} participants. {{b.completion.summary}}</p>
   <form v-if="!['completed','cancelled'].includes(b.status)&&(workspace.canManage||['requested','quoted','accepted'].includes(b.status))" class="scb-form" @submit.prevent="bookingAction(b,'cancel',{reason:cancelReason})"><label>Cancellation reason<input v-model="cancelReason" required/></label><button class="scb-button scb-outline" :disabled="busy">Cancel booking</button></form>
  </template></article></section>
 </template>
 <section v-if="tab==='Invoices'" class="scb-workspace-panel"><h2>Invoices & receipts</h2><p>Receipts appear only after payment is verified. Grant approvals and expense drafts do not represent completed payments.</p><SchoolCareBridgePayment v-if="paying" :key="paying.id" :invoice="paying" @paid="paymentDone" @close="paying=null"/><div v-for="i in workspace.invoices" :key="i.id" class="scb-ops-invoice"><div class="scb-ops-row"><div><strong>SCB-{{i.id}} · {{money(i.totalCents)}}</strong><small>{{i.kind==='platform_usage'?'MH4Kidz → Plot Twist Co':'School → MH4Kidz'}} · {{i.status}}{{i.receiptNumber?' · '+i.receiptNumber:''}}</small></div><button class="scb-button scb-outline" @click="download(`/invoices/${i.id}/print`,`SCB-${i.id}.html`)">{{i.receiptNumber?'Receipt / invoice':'Print invoice'}}</button><button v-if="i.status==='open'" class="scb-button" @click="paying=i">Pay in app</button><button class="scb-button scb-outline" @click="refreshInvoice(i)">Check payment</button></div><details v-if="workspace.canManage&&(i.kind==='booking'||platformAdmin)&&['open','paid','refund_failed'].includes(i.status)"><summary>Adjust invoice</summary><form class="scb-form" @submit.prevent="adjustInvoice(i)"><label>Reason<input v-model="adjustReasons[i.id]" required/></label><button class="scb-button scb-outline" :disabled="busy">{{i.status==='open'?'Void unpaid invoice':'Refund full payment'}}</button></form></details></div><p v-if="!workspace.invoices?.length">There are no invoices for your account.</p></section>
 <SchoolCareBridgeContractPanel v-if="tab==='Contracts'&&workspace.commercial" :key="workspace.commercial.revision" :commercial="workspace.commercial" :evidence="workspace.contractEvidence||[]" :platform-admin="platformAdmin" :busy="busy" @save="saveTerms" @download="key=>download(`/contracts/${key}`,`schoolcarebridge-${key}.html`)" @activate="activate"/>
 <section v-if="tab==='Usage'&&workspace.canManage" class="scb-workspace-panel"><h2>Platform usage payable by MH4Kidz</h2><p>School discounts do not reduce these contracted fees. Charges require signed terms, rollout and complete daily usage evidence.</p><form class="scb-form" @submit.prevent="previewUsage"><label>Service month<input v-model="usageMonth" type="month" required/></label><div class="scb-actions"><button class="scb-button scb-outline" :disabled="busy">Preview month</button><button v-if="platformAdmin" type="button" class="scb-button scb-outline" @click="captureUsage" :disabled="busy">Capture today’s usage</button></div></form><template v-if="usage"><p>Proposed total: <strong>{{money(usage.totalCents)}}</strong> · Terms revision {{usage.termsRevision}}</p><p v-if="usage.missingDays.length" role="status">Missing daily evidence: {{usage.missingDays.join(', ')}}. Invoicing is blocked until reconciled.</p><div v-for="l in usage.lines" :key="l.key" class="scb-ops-row"><span>Agency {{l.partnerAgencyId}} · {{l.description}} · {{l.unitDays}} unit-days · {{l.percentageBps/100}}%</span><strong>{{money(l.amountCents)}}</strong></div><button v-if="platformAdmin" class="scb-button" :disabled="busy||!usage.active||!!usage.missingDays.length||!usage.totalCents" @click="issueUsage">Issue reviewed invoice to MH4Kidz</button></template></section>
 </template>
 </main>
 </div>
</template>
<script setup>
import {computed,onMounted,ref} from 'vue';
import {useRoute} from 'vue-router';
import {useAuthStore} from '../../store/auth';
import api from '../../services/api';
import SchoolCareBridgeBrand from '../../components/schoolcarebridge/SchoolCareBridgeBrand.vue';
import SchoolCareBridgeProgramEditor from '../../components/schoolcarebridge/SchoolCareBridgeProgramEditor.vue';
import SchoolCareBridgeContractPanel from '../../components/schoolcarebridge/SchoolCareBridgeContractPanel.vue';
import SchoolCareBridgePayment from '../../components/schoolcarebridge/SchoolCareBridgePayment.vue';
import '../../styles/schoolCareBridge.css';
import '../../styles/schoolCareBridgeWorkspace.css';
import '../../styles/schoolCareBridgeOperations.css';
const auth=useAuthStore(),route=useRoute(),workspace=ref({}),catalog=ref([]),schools=ref([]),loading=ref(true),busy=ref(false),error=ref(''),notice=ref(''),tab=ref('Bookings'),editor=ref(null),selected=ref(null),paying=ref(null),authorized=ref(false),availability=ref(false),cancelReason=ref(''),adjustReasons=ref({}),usage=ref(null),usageMonth=ref(new Date().toISOString().slice(0,7));
const platformAdmin=computed(()=>auth.user?.role==='super_admin'),tabs=computed(()=>workspace.value.canManage?['Programs','Bookings','Invoices','Contracts','Usage']:['Bookings','Invoices']);
const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';
const request=ref({programId:Number(route.query.program)||'',schoolId:'',startLocal:'',endLocal:'',region:'',location:'',attendance:20,language:'English',accommodations:'',travelRequested:false,fundingRequested:'cash',requestKey:crypto.randomUUID()});
const quote=ref({}),funding=ref({presenterAllocationId:'',platformAllocationId:''}),completion=ref({attendance:0,summary:'',satisfaction:null});
const money=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(c||0)/100),when=v=>new Date(v).toLocaleString(),endpoint='/schoolcarebridge/operations';
async function action(fn,message='Saved.'){busy.value=true;error.value='';notice.value='';try{await fn();notice.value=message;}catch(e){error.value=e.response?.data?.error?.message||e.message||'The request could not be completed.';}finally{busy.value=false;}}
async function fetchWorkspace(){workspace.value=(await api.get(endpoint+'/workspace')).data;if(selected.value)selected.value=workspace.value.bookings.find(b=>b.id===selected.value.id)||null;}
async function load(){loading.value=true;await action(async()=>{await fetchWorkspace();const [p,s]=await Promise.all([api.get('/schoolcarebridge/programs'),api.get('/schoolcarebridge/my-schools')]);catalog.value=p.data.programs;schools.value=s.data.schools;},'');loading.value=false;}
async function enableFinance(){await action(async()=>{await api.post('/finance-operations/setup',{agencyId:workspace.value.operator.id});await fetchWorkspace();},'Finance workspace enabled. Add funds, grants and budgets there before allocating program costs.');}
async function saveProgram(p){await action(async()=>{if(p.id)await api.put(endpoint+`/programs/${p.id}`,p);else await api.post(endpoint+'/programs',p);editor.value=null;await fetchWorkspace();catalog.value=(await api.get('/schoolcarebridge/programs')).data.programs;},'Program saved.');}
async function requestBooking(){await action(async()=>{await api.post(endpoint+'/bookings',{...request.value,start:new Date(request.value.startLocal).toISOString(),end:new Date(request.value.endLocal).toISOString(),timezone});request.value.requestKey=crypto.randomUUID();await fetchWorkspace();},'Booking request received. MH4Kidz will review availability, funding and travel.');}
function selectBooking(b){if(selected.value?.id===b.id){selected.value=null;return;}selected.value=b;authorized.value=false;availability.value=false;cancelReason.value='';const q=b.quote||{};quote.value={service:(q.serviceCents||0)/100,travel:(q.travelCents||0)/100,school:(q.schoolCents||0)/100,expiresDate:q.expiresDate||new Date(Date.now()+14*86400000).toISOString().slice(0,10),scope:q.scope||'',cancellationTerms:q.cancellationTerms||'',travelTerms:q.travelTerms||'',presenterPaymentTerms:q.presenterPaymentTerms||'Within 30 days after completed delivery and an approved presenter invoice.',fundingNotes:q.fundingNotes||'',financeProgramId:q.financeProgramId||''};completion.value={attendance:b.attendance,summary:'',satisfaction:null};}
async function bookingAction(b,name,data){await action(async()=>{await api.post(endpoint+`/bookings/${b.id}/${name}`,{revision:b.revision,...data});await fetchWorkspace();},'Booking updated.');}
async function sendQuote(b){await bookingAction(b,'quote',{...quote.value,serviceCents:Math.round(Number(quote.value.service)*100),travelCents:Math.round(Number(quote.value.travel)*100),schoolCents:Math.round(Number(quote.value.school)*100)});}
async function saveTerms(data){await action(async()=>{await api.put(endpoint+'/terms',data);await fetchWorkspace();},'Proposed terms saved. Download the new revision before signing.');}
async function activate(data){await action(async()=>{await api.post(endpoint+'/terms/activate',data);await fetchWorkspace();},'Signed documents recorded. Contractual rollout and billing checks still apply.');}
async function download(path,name){await action(async()=>{const {data}=await api.get(endpoint+path,{responseType:'blob'});const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);},'Downloaded. Open the document and use Print to print or save as PDF.');}
async function refreshInvoice(i){await action(async()=>{await api.post(endpoint+`/invoices/${i.id}/refresh`);await fetchWorkspace();},'Payment status checked.');}
async function adjustInvoice(i){await action(async()=>{await api.post(endpoint+`/invoices/${i.id}/${i.status==='open'?'void':'refund'}`,{reason:adjustReasons.value[i.id]});await fetchWorkspace();},'Invoice adjustment recorded.');}
async function paymentDone(){paying.value=null;await action(fetchWorkspace,'Payment verified. Your receipt is available below.');}
async function previewUsage(){await action(async()=>{usage.value=(await api.get(endpoint+`/usage/${usageMonth.value}`)).data;},'');}
async function captureUsage(){await action(async()=>{await api.post(endpoint+'/usage/capture');},'Today’s usage evidence captured. No invoice was issued.');}
async function issueUsage(){await action(async()=>{await api.post(endpoint+`/usage/${usageMonth.value}/invoice`);await fetchWorkspace();tab.value='Invoices';},'Reviewed platform invoice issued to MH4Kidz.');}
onMounted(load);
</script>
