<template>
 <section v-if="offices.length" class="service-locations its-wrap its-section" aria-label="Where we offer care">
  <div class="its-section-heading"><div><p class="its-eyebrow">Care close to you</p><h2>Find your place to begin.</h2><p>Explore our offices, or connect with a provider virtually.</p></div><router-link class="its-button its-outline" to="/p/itsco/providers?setting=virtual"><Icon name="screen"/>Find virtual care</router-link></div>
  <div class="location-explorer"><div class="location-sidebar"><label>Browse by state<select v-model="state"><option value="">All office locations</option><option v-for="region in regions" :key="region.state">{{region.state}}</option></select></label><button v-for="office in visibleOffices" :key="office.id" :aria-pressed="selected?.id===office.id" @click="selectedId=office.id"><Icon name="pin"/><span><strong>{{office.name}}</strong><small>{{office.city}}, {{office.state}}</small><small>{{office.address}}</small></span></button></div><div v-if="selected" class="location-map"><iframe :key="selected.id" :title="`Map of ${selected.name}`" :src="mapSrc" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><div class="location-map-caption"><div><strong>{{selected.name}}</strong><p>{{selected.address}}</p></div><router-link class="its-button" :to="{path:'/p/itsco/providers',query:{setting:'office',officeId:selected.id}}">See providers →</router-link><a :href="directions" target="_blank" rel="noopener noreferrer">Directions ↗</a></div></div></div>
 </section>
</template>
<script setup>
import {computed,ref,watch} from 'vue';
import Icon from '../rise/RiseIcon.vue';
import {officeRegions} from '../../utils/publicOfficeRegions';
const props=defineProps({offices:{type:Array,default:()=>[]}}),state=ref(''),selectedId=ref(null);
const regions=computed(()=>officeRegions(props.offices));
const visibleOffices=computed(()=>props.offices.filter(o=>!state.value||officeRegions([o])[0]?.state===state.value));
const selected=computed(()=>visibleOffices.value.find(o=>o.id===selectedId.value)||visibleOffices.value[0]);
const query=computed(()=>[selected.value?.name,selected.value?.address].filter(Boolean).join(', '));
const mapSrc=computed(()=>`https://maps.google.com/maps?q=${encodeURIComponent(query.value)}&output=embed`);
const directions=computed(()=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(query.value)}`);
watch(state,()=>{selectedId.value=null;});
</script>
<style scoped>.service-locations svg{width:20px;height:20px;flex-shrink:0}.location-explorer{display:grid;grid-template-columns:290px minmax(0,1fr);border:1px solid #d5e5dc;border-radius:22px;overflow:hidden;background:#f3f8f5;box-shadow:0 8px 28px #1c4e3010}.location-sidebar{padding:22px;display:flex;flex-direction:column;gap:12px;max-height:500px;overflow:auto}.location-sidebar label{display:grid;gap:6px;font-size:12px}.location-sidebar select{padding:10px;background:white;border:1px solid #c8dcd0;border-radius:8px;min-width:0;width:100%;color:#234c3c}.location-sidebar button{display:flex;align-items:start;gap:10px;background:white;border:1px solid #d5e4db;border-radius:14px;padding:14px;text-align:left;color:#20523e;font:inherit}.location-sidebar button[aria-pressed=true]{border-color:#256c4e;box-shadow:0 0 0 1px #256c4e;background:#e6f2e9}.location-sidebar strong,.location-sidebar small{display:block}.location-sidebar small{font-size:11px;margin-top:5px;color:#5b7264}.location-map iframe{width:100%;height:350px;border:0;display:block}.location-map-caption{display:flex;align-items:center;flex-wrap:wrap;gap:14px;padding:20px;background:white}.location-map-caption>div{flex:1}.location-map-caption p{font-size:12px;margin:4px 0}.location-map-caption .its-button{font-size:12px;padding:10px 16px}.location-map-caption>a:last-child{font-size:12px}@media(max-width:700px){.location-explorer{grid-template-columns:1fr}.location-sidebar{max-height:260px;padding:16px;display:grid;grid-template-columns:1fr 1fr}.location-sidebar label{grid-column:1/-1}.location-sidebar button{padding:10px;font-size:12px}.location-map iframe{height:280px}.location-map-caption{padding:16px}}</style>
