<template>
 <section :key="selected?.id || 'directory'" :data-analytics-id="selected ? 'profile-'+selected.id : 'provider-directory'" :data-analytics-label="selected?.displayName || 'Provider directory'" aria-label="ITSCO provider directory">
  <div v-if="selected" class="its-selected-profile">
   <router-link class="its-text-button" :to="{path:'/p/itsco/providers',query:directoryQuery}">← Back to providers</router-link>
   <div class="its-profile-top"><img v-if="selected.photoUrl" :src="selected.photoUrl" :alt="selected.displayName"/><div v-else class="its-avatar">{{initials(selected.displayName)}}</div><div><p class="its-eyebrow">Meet your provider</p><h2>{{selected.displayName}}<span v-if="selected.credential">, {{selected.credential}}</span></h2><p>{{selected.title}}</p><div class="its-tags"><span v-if="selected.credential">{{selected.credential}}</span><button v-for="location in selected.officeLocations||[]" :key="location.id" class="its-office-chip" @click="chooseOffice(location.id)">⌖ {{location.name}}</button><span v-for="f in offeredFormats(selected)" :key="f">{{f}}</span></div><span class="its-status" :class="{'its-waitlist':!isAccepting(selected)}">{{acceptanceLabel(selected)}}</span></div></div>
   <PublicProviderProfileEditor :provider="selected" :agency-id="agencyId" @saved="$emit('refresh')"/>
   <div class="its-profile-body"><div><article class="its-card"><h3>About {{selected.firstName}}</h3><p class="its-full-bio">{{selected.bio || 'Our team can tell you more about this provider and help you find the right support.'}}</p></article><div class="its-two"><article v-for="[label,values] in profileFacets" :key="label" class="its-card"><h3>{{label}}</h3><div v-if="values.length" class="its-tags"><span v-for="v in values" :key="v">{{v}}</span></div><p v-else>Contact our team for details.</p></article></div></div><aside><PublicProviderAvailabilityPanel :provider="selected" agency-slug="itsco" :office-id="officeId" @loaded="profileSchedule=$event"/></aside></div>
  </div>
  <template v-else>
   <div class="its-provider-modes" role="group" aria-label="Provider setting"><button v-for="[value,label] in modes" :key="value" :aria-pressed="mode===value" @click="setMode(value)">{{label}}</button></div>
   <PublicOfficeLocations v-if="mode==='office'" :offices="officeLocations" :model-value="officeId" required @update:model-value="chooseOffice"/>
   <template v-if="!needsOffice">
   <div class="its-provider-filters"><label>Search<input v-model="search" type="search" placeholder="Name, specialty, language…"/></label><label>School<select v-model="school"><option value="">All schools</option><option v-for="s in schools" :key="s.id" :value="String(s.id)">{{s.name}}</option></select></label><label>Client age<select v-model="age"><option value="">All ages</option><option v-for="v in ages" :key="v">{{v}}</option></select></label><label>Specialty<select v-model="specialty"><option value="">All specialties</option><option v-for="v in specialties" :key="v">{{v}}</option></select></label><label>Insurance<select v-model="insurance"><option value="">All insurance</option><option v-for="v in insurances" :key="v">{{v}}</option></select></label><label>New clients<select v-model="accepting"><option value="">Any status</option><option value="yes">Accepting new clients</option><option value="waitlist">Waitlist</option><option value="unavailable">Closed to new clients</option></select></label><label>Openings<select v-model="openings"><option value="">Any availability</option><option value="yes">With openings</option><option value="no">No published openings</option></select></label><label>Provider gender<select v-model="gender"><option value="">Any gender</option><option v-for="v in genders" :key="v">{{v}}</option></select></label></div>
   <div class="its-section-heading"><p role="status"><strong>{{filtered.length}} {{filtered.length===1?'provider':'providers'}}</strong><span v-if="school"> at {{schools.find(s=>String(s.id)===school)?.name}}</span></p><div class="its-inline"><button class="its-text-button" @click="clear">Clear filters</button><label>Sort by <select v-model="sort"><option value="recommended">Availability &amp; setting</option><option value="soonest">Next appointment within availability groups</option><option value="name">Name within availability groups</option></select></label></div></div>
   <p v-if="availabilityLoading" role="status">Checking current appointment availability…</p><p v-else-if="availabilityError" class="its-soft" role="status">{{availabilityError}} <button class="its-text-button" @click="$emit('retry-availability')">Retry availability</button></p>
   <div class="its-provider-grid"><article v-for="p in filtered.slice(0,limit)" :key="p.id" :data-analytics-id="'provider-'+p.id" :data-analytics-label="p.displayName" class="its-provider-card"><div class="its-provider-photo"><img v-if="p.photoUrl" :src="p.photoUrl" :alt="p.displayName" loading="lazy"/><div v-else class="its-avatar">{{initials(p.displayName)}}</div><span class="its-status" :class="{'its-waitlist':!isAccepting(p)}">{{acceptanceLabel(p)}}</span></div><div class="its-provider-copy"><h3>{{p.displayName}}<template v-if="p.credential">, {{p.credential}}</template></h3><p class="its-small">{{p.title}}</p><div class="its-tags"><span v-for="v in uniquePublicFacets([...p.specialties,...p.ageGroups]).slice(0,5)" :key="v">{{v}}</span></div><div class="its-office-buttons" v-if="p.officeLocations?.length"><button v-for="location in p.officeLocations" :key="location.id" class="its-office-chip" @click="chooseOffice(location.id)">⌖ {{location.name}}</button></div><p class="its-provider-bio">{{p.bio}}</p><details v-if="p.insurances.length"><summary>Insurance · {{p.insurances.length}} plans</summary><ul class="its-insurance-list"><li v-for="i in p.insurances" :key="i.name"><img v-if="i.logoUrl" :src="i.logoUrl" alt=""/>{{i.name}}</li></ul></details><p v-if="p.office || officeOpen(p)" class="its-small">In person · {{statusLabel(officeStatus(p))}}</p><p v-if="offeredFormats(p).includes('Virtual')" class="its-small">Virtual · {{statusLabel(statuses(p).virtual)}}</p><p v-if="p.schools.length" class="its-small">Assigned schools · {{statusLabel(schoolStatus(p))}}</p><details v-if="p.schools.length"><summary>School-based · {{p.schools.length}} {{p.schools.length===1?'school':'schools'}}</summary><ul class="its-profile-schools"><li v-for="s in p.schools" :key="s.id"><img v-if="s.logoUrl" :src="s.logoUrl" alt=""/><button class="its-text-button" @click="school=String(s.id)">{{s.name}}</button></li></ul></details><p class="its-availability">{{availabilityText(p)}}</p><div class="its-card-actions"><router-link class="its-button" :to="{path:'/p/itsco/providers',query:{...directoryQuery,provider:String(p.id)}}">View profile</router-link><router-link v-if="p.onlineScheduling && (isAccepting(p)||hasOpenings(p))" class="its-button its-outline" :to="`/itsco/provider/${p.id}?serviceType=counseling${officeId?'&officeId='+officeId:''}`">View times</router-link><router-link v-else class="its-button its-outline" :to="overallProviderStatus(p,props.availability[p.id])==='waitlist'?{path:'/p/itsco/providers',query:{...directoryQuery,provider:String(p.id)}}:'/p/itsco/contact'">{{overallProviderStatus(p,props.availability[p.id])==='waitlist'?'Join waitlist':'Inquire with our team'}}</router-link></div></div></article></div>
   <div v-if="!filtered.length" class="its-soft"><h3>No matching providers.</h3><p>Try fewer filters or ask our team to help you find support.</p><button class="its-button its-outline" @click="clear">Clear filters</button></div><button v-if="filtered.length>limit" class="its-button its-outline its-load-more" @click="limit+=12">Load more providers →</button>
   </template>
  </template>
 </section>
</template>
<script setup>
import {computed,ref,watch} from 'vue';
import {uniquePublicFacets} from '../../utils/publicProviderFacets';
import {providerStatuses,providerPriority,overallProviderStatus,statusLabel} from '../../utils/providerDirectoryStatus';
import {useRoute,useRouter} from 'vue-router';
import PublicOfficeLocations from '../publicServices/PublicOfficeLocations.vue';
import PublicProviderProfileEditor from '../publicServices/PublicProviderProfileEditor.vue';
import PublicProviderAvailabilityPanel from '../publicServices/PublicProviderAvailabilityPanel.vue';
const props=defineProps({providers:{type:Array,default:()=>[]},schools:{type:Array,default:()=>[]},availability:{type:Object,default:()=>({})},availabilityLoading:Boolean,availabilityError:String,agencyId:{type:Number,required:true}});
defineEmits(['refresh','retry-availability']);
const route=useRoute(),router=useRouter(),officeId=ref(''),mode=ref('all'),school=ref(''),search=ref(''),age=ref(''),specialty=ref(''),insurance=ref(''),accepting=ref(''),openings=ref(''),gender=ref(''),sort=ref('recommended'),limit=ref(12),profileSchedule=ref(null);
const modes=[['all','All providers'],['office','In-office providers'],['virtual','Virtual providers'],['school','School-based providers']];
watch(()=>[route.query.officeId,route.query.setting],([id,setting])=>{officeId.value=String(id||'');mode.value=id?'office':['office','virtual','school'].includes(setting)?setting:'all';},{immediate:true});
watch(()=>route.query.school,v=>{school.value=String(v||'');},{immediate:true});
watch(()=>route.query.provider,()=>{profileSchedule.value=null;});
watch([officeId,mode,school,search,age,specialty,insurance,accepting,openings,gender],()=>{limit.value=12;});
const selected=computed(()=>props.providers.find(p=>String(p.id)===String(route.query.provider)));
const officeLocations=computed(()=>[...new Map(props.providers.flatMap(p=>p.officeLocations||[]).map(o=>[o.id,o])).values()].sort((a,b)=>a.name.localeCompare(b.name)));
const needsOffice=computed(()=>mode.value==='office'&&!officeLocations.value.some(o=>String(o.id)===officeId.value));
const directoryQuery=computed(()=>({setting:mode.value,...(school.value?{school:school.value}:{}),...(mode.value==='office'?{officeId:officeId.value||undefined}:{})}));
function setMode(value){mode.value=value;school.value='';if(value!=='office')officeId.value='';router.replace({query:{...route.query,school:undefined,officeId:officeId.value||undefined,setting:value}});}
function chooseOffice(id){mode.value='office';officeId.value=String(id);school.value='';router.replace({path:'/p/itsco/providers',query:{setting:'office',officeId:officeId.value}});}
const values=key=>uniquePublicFacets(props.providers.flatMap(p=>p[key]||[])).sort();
const ages=computed(()=>values('ageGroups')),specialties=computed(()=>values('specialties'));
const genders=computed(()=>[...new Set(props.providers.map(p=>p.details?.gender).filter(Boolean))].sort());
const insurances=computed(()=>[...new Set(props.providers.flatMap(p=>p.insurances.map(i=>i.name)))].sort());
const availability=p=>selected.value?.id===p.id && profileSchedule.value?profileSchedule.value:props.availability[p.id]||{};
const statuses=p=>providerStatuses(p,availability(p),school.value);
const officeOpen=p=>Boolean(availability(p).inPerson?.hasPublishedOpenings);
const officeStatus=p=>statuses(p).office;
const schoolStatus=p=>statuses(p).school;
const currentStatus=p=>school.value?schoolStatus(p):mode.value==='all'?overallProviderStatus(p,availability(p)):statuses(p)[mode.value];
const isAccepting=p=>currentStatus(p)==='accepting';
function offeredFormats(p){const a=availability(p);return [['In person',p.officeLocations?.length||p.office||p.details?.inPersonEnabled||['accepting','waitlist'].includes(p.details?.officeAvailability)||a.inPerson?.hasPublishedOpenings],['Virtual',p.details?.virtualEnabled||['accepting','waitlist'].includes(p.details?.virtualAvailability)||(p.details?.sessionFormats||[]).some(v=>/virtual|telehealth|online/i.test(v))||a.virtual?.hasPublishedOpenings],['School-based',p.schools.length]].filter(([,yes])=>yes).map(([label])=>label);}
function acceptanceLabel(p){return statusLabel(currentStatus(p));}
const hasOpenings=p=>{const a=availability(p);return mode.value==='office'?Boolean(a.inPerson?.hasPublishedOpenings):mode.value==='virtual'?Boolean(a.virtual?.hasPublishedOpenings):mode.value==='school'||school.value?Boolean(school.value?p.schools.find(s=>String(s.id)===school.value)?.hasOpenings:p.schoolOpenings):Boolean(a.hasPublishedOpenings||a.nextAvailableAt||p.schoolOpenings);};
const filtered=computed(()=>props.providers.filter(p=>
 (!needsOffice.value)&&(!officeId.value||mode.value!=='office'||(p.officeLocations||[]).some(o=>String(o.id)===officeId.value))&&
 (mode.value==='all'||(mode.value==='office'?offeredFormats(p).includes('In person'):mode.value==='virtual'?offeredFormats(p).includes('Virtual'):p.schools.length))&&
 (!school.value||p.schools.some(s=>String(s.id)===school.value))&&(!age.value||uniquePublicFacets(p.ageGroups).includes(age.value))&&
 (!specialty.value||p.specialties.includes(specialty.value))&&(!gender.value||p.details?.gender===gender.value)&&
 (!insurance.value||p.insurances.some(i=>i.name===insurance.value))&&(!accepting.value||currentStatus(p)===(accepting.value==='yes'?'accepting':accepting.value))&&
 (!openings.value||(openings.value==='yes'?hasOpenings(p):!hasOpenings(p)&&!props.availabilityLoading&&!props.availabilityError))&&
 (!search.value||[p.displayName,p.title,p.bio,p.credential,...p.specialties,...p.ageGroups,...(p.details?.languages||[]),...p.schools.map(s=>s.name)].join(' ').toLowerCase().includes(search.value.toLowerCase()))
 ).sort((a,b)=>providerPriority(a,availability(a),mode.value,school.value)-providerPriority(b,availability(b),mode.value,school.value)||
 (sort.value!=='name'?String(nextOpening(a)||'9999').localeCompare(String(nextOpening(b)||'9999')):0)||a.displayName.localeCompare(b.displayName)));
const profileFacets=computed(()=>selected.value?[['Specialties',selected.value.specialties],['Client ages',uniquePublicFacets(selected.value.ageGroups)],['Populations served',selected.value.populations],['Therapy approaches',selected.value.modalities],['Languages',selected.value.details?.languages||[]],['Insurance',selected.value.insurances.map(i=>i.name)]]:[]);
function nextOpening(p){const a=availability(p);return mode.value==='office'?a.inPerson?.nextAvailableAt:mode.value==='virtual'?a.virtual?.nextAvailableAt:a.nextAvailableAt||a.inPerson?.nextAvailableAt||a.virtual?.nextAvailableAt;}
function availabilityText(p){const at=nextOpening(p);if(at)return `Next opening: ${new Date(at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'})}`;if(p.schoolOpenings&&!['office','virtual'].includes(mode.value))return 'School openings available · confirm with our team';if(props.availabilityLoading)return 'Checking appointment times…';if(props.availabilityError)return 'Appointment availability could not be checked';return currentStatus(p)==='waitlist'?'Join this provider’s waitlist':currentStatus(p)==='unavailable'?'Closed to new clients · inquire with our team':'Accepting new clients · we’ll work with you directly to find a time';}
function clear(){officeId.value='';router.replace({query:{}});mode.value='all';school.value='';search.value='';age.value='';specialty.value='';insurance.value='';accepting.value='';openings.value='';gender.value='';limit.value=12;}
function initials(name){return name.split(' ').map(s=>s[0]).slice(0,2).join('');}
</script>
<style scoped>
.its-office-buttons{display:flex;gap:6px;flex-wrap:wrap}.its-office-chip{background:#eef6f2;color:#155642;border:1px solid #afc8bb;border-radius:18px;padding:8px 12px;text-align:left;font-size:12px;cursor:pointer}

.its-provider-modes{display:flex;justify-content:center;gap:6px;flex-wrap:wrap;margin-bottom:18px}.its-provider-modes button{border:1px solid #cedfd7;background:#f4f7f6;border-radius:25px;color:#174b40;padding:12px 25px}.its-provider-modes button[aria-pressed=true]{background:#075540;color:white}.its-provider-filters{display:grid;grid-template-columns:1.6fr repeat(3,1fr);gap:14px}.its-provider-filters label{display:grid;gap:6px;font-size:13px;font-weight:600}.its-provider-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.its-provider-card{border:1px solid #dce7e2;border-radius:14px;overflow:hidden;background:white;box-shadow:0 3px 10px #143e2910;display:flex;flex-direction:column}.its-provider-photo{height:210px;position:relative;background:#e7f3ed}.its-provider-photo>img{width:100%;height:100%;object-fit:cover;object-position:center 25%}.its-provider-photo .its-status{position:absolute;bottom:12px;left:12px}.its-provider-copy{padding:14px;flex:1;display:flex;flex-direction:column;gap:8px}.its-provider-copy h3,.its-provider-copy p{margin:0}.its-provider-copy h3{font-size:19px}.its-provider-copy summary{font-size:13px;font-weight:600;cursor:pointer}.its-provider-bio{font-size:13px;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.its-card-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:auto}.its-card-actions .its-button{font-size:12px;padding:10px 12px;flex:1}.its-availability{font-size:12px;font-weight:600;color:#196747}.its-insurance-list,.its-profile-schools{list-style:none;padding:0;font-size:13px}.its-insurance-list li,.its-profile-schools li{display:flex;gap:8px;align-items:center;padding:5px 0}.its-insurance-list img,.its-profile-schools img{width:25px;height:25px;object-fit:contain}.its-profile-top{display:flex;gap:30px;align-items:center;margin:30px 0}.its-profile-top>img,.its-profile-top>.its-avatar{width:180px;height:180px;border-radius:50%;object-fit:cover}.its-profile-body{display:grid;grid-template-columns:2fr 1fr;gap:25px}.its-profile-body .its-card{margin-bottom:20px}.its-full-bio{white-space:pre-line}.its-load-more{display:block;margin:25px auto}.its-profile-body aside{align-self:start}@media(max-width:1200px){.its-provider-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.its-provider-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.its-provider-filters{grid-template-columns:repeat(2,minmax(0,1fr))}.its-profile-body{grid-template-columns:1fr}}@media(max-width:580px){.its-provider-grid{grid-template-columns:1fr}.its-provider-filters{grid-template-columns:1fr}.its-provider-photo{height:270px}.its-profile-top{flex-direction:column;align-items:flex-start}.its-provider-modes button{flex:1;padding:11px;font-size:12px}}

.its-provider-grid { grid-template-columns: repeat(3,minmax(0,1fr)); }
.its-provider-card { display: grid; grid-template-columns: minmax(100px,32%) minmax(0,1fr); align-items: stretch; }
.its-provider-photo { height: auto; min-height: 260px; }
.its-provider-photo > img { position: absolute; inset: 0; object-position: center 20%; }
.its-provider-copy { min-width: 0; overflow-wrap: anywhere; }
.its-provider-photo .its-status { position: absolute; z-index: 1; margin: 0; left: 8px; right: 8px; bottom: 10px; display: inline-block; font-size: 11px; overflow-wrap: anywhere; }
.its-profile-top > img, .its-profile-top > .its-avatar { width: 160px; height: 220px; border-radius: 12px; object-position: center 20%; }
@media(max-width:1250px) { .its-provider-grid { grid-template-columns: repeat(2,minmax(0,1fr)); } }
@media(max-width:750px) { .its-provider-grid { grid-template-columns: 1fr; } .its-provider-photo { height: auto; } }

@media(max-width:900px){.its-profile-body aside{grid-row:1}}
@media(max-width:580px){.its-profile-top{flex-direction:row;gap:14px}.its-profile-top > img,.its-profile-top > .its-avatar{width:100px;height:150px;flex-shrink:0}.its-profile-top > div:last-child{min-width:0;overflow-wrap:anywhere}}
</style>
