<template>
 <section :key="selected?.id || 'directory'" :data-analytics-id="selected ? 'profile-'+selected.id : 'provider-directory'" :data-analytics-label="selected?.displayName || 'Provider directory'" aria-label="ITSCO provider directory">
  <div v-if="selected" class="its-selected-profile">
   <router-link class="its-text-button" :to="{path:'/p/itsco/providers',query:school?{school}: {}}">← Back to providers</router-link>
   <div class="its-profile-top"><img v-if="selected.photoUrl" :src="selected.photoUrl" :alt="selected.displayName"/><div v-else class="its-avatar">{{initials(selected.displayName)}}</div><div><p class="its-eyebrow">Meet your provider</p><h2>{{selected.displayName}}<span v-if="selected.credential">, {{selected.credential}}</span></h2><p>{{selected.title}}</p><span class="its-status" :class="{'its-waitlist':!selected.acceptingNewClients}">{{selected.acceptingNewClients?'Accepting new clients':'Waitlist / contact our team'}}</span></div></div>
   <PublicProviderProfileEditor :provider="selected" :agency-id="agencyId" @saved="$emit('refresh')"/>
   <div class="its-profile-body"><div><article class="its-card"><h3>About {{selected.firstName}}</h3><p class="its-full-bio">{{selected.bio || 'Our team can tell you more about this provider and help you find the right support.'}}</p></article><div class="its-two"><article v-for="[label,values] in profileFacets" :key="label" class="its-card"><h3>{{label}}</h3><div v-if="values.length" class="its-tags"><span v-for="v in values" :key="v">{{v}}</span></div><p v-else>Contact our team for details.</p></article></div></div><aside class="its-soft"><h3>Your next step</h3><p>{{availabilityText(selected)}}</p><router-link v-if="selected.onlineScheduling" class="its-button" :to="`/itsco/provider/${selected.id}?serviceType=counseling`">View availability &amp; full profile →</router-link><router-link v-else class="its-button" to="/itsco/school-referral">Find school enrollment →</router-link><p class="its-small">Selecting an eligible weekly time starts an intake hold. It does not book an appointment. The team confirms your placement.</p><h3 v-if="selected.schools.length">School locations</h3><ul class="its-profile-schools"><li v-for="s in selected.schools" :key="s.id"><img v-if="s.logoUrl" :src="s.logoUrl" alt=""/>{{s.name}}</li></ul><router-link class="its-button its-outline" to="/p/itsco/contact">Ask our team for help →</router-link></aside></div>
  </div>
  <template v-else>
   <div class="its-provider-modes" role="group" aria-label="Provider setting"><button v-for="[value,label] in modes" :key="value" :aria-pressed="mode===value" @click="mode=value">{{label}}</button></div>
   <div class="its-provider-filters"><label>Search<input v-model="search" type="search" placeholder="Name, specialty, language…"/></label><label>School<select v-model="school"><option value="">All schools</option><option v-for="s in schools" :key="s.id" :value="String(s.id)">{{s.name}}</option></select></label><label>Client age<select v-model="age"><option value="">All ages</option><option v-for="v in ages" :key="v">{{v}}</option></select></label><label>Specialty<select v-model="specialty"><option value="">All specialties</option><option v-for="v in specialties" :key="v">{{v}}</option></select></label><label>Insurance<select v-model="insurance"><option value="">All insurance</option><option v-for="v in insurances" :key="v">{{v}}</option></select></label><label>New clients<select v-model="accepting"><option value="">Any status</option><option value="yes">Accepting new clients</option><option value="no">Waitlist</option></select></label><label>Openings<select v-model="openings"><option value="">Any availability</option><option value="yes">With openings</option><option value="no">No published openings</option></select></label></div>
   <div class="its-section-heading"><p role="status"><strong>{{filtered.length}} {{filtered.length===1?'provider':'providers'}}</strong><span v-if="school"> at {{schools.find(s=>String(s.id)===school)?.name}}</span></p><div class="its-inline"><button class="its-text-button" @click="clear">Clear filters</button><label>Sort by <select v-model="sort"><option value="name">Name</option><option value="soonest">Earliest online availability</option></select></label></div></div>
   <p v-if="availabilityLoading" role="status">Checking current appointment availability…</p><p v-else-if="availabilityError" class="its-soft" role="status">{{availabilityError}} <button class="its-text-button" @click="$emit('retry-availability')">Retry availability</button></p>
   <div class="its-provider-grid"><article v-for="p in filtered.slice(0,limit)" :key="p.id" :data-analytics-id="'provider-'+p.id" :data-analytics-label="p.displayName" class="its-provider-card"><div class="its-provider-photo"><img v-if="p.photoUrl" :src="p.photoUrl" :alt="p.displayName" loading="lazy"/><div v-else class="its-avatar">{{initials(p.displayName)}}</div><span class="its-status" :class="{'its-waitlist':!p.acceptingNewClients}">{{p.acceptingNewClients?'Accepting new clients':'Waitlist'}}</span></div><div class="its-provider-copy"><h3>{{p.displayName}}<template v-if="p.credential">, {{p.credential}}</template></h3><p class="its-small">{{p.title}}</p><div class="its-tags"><span v-for="v in [...p.specialties,...p.ageGroups].slice(0,5)" :key="v">{{v}}</span></div><p class="its-provider-bio">{{p.bio}}</p><details v-if="p.insurances.length"><summary>Insurance · {{p.insurances.length}} plans</summary><ul class="its-insurance-list"><li v-for="i in p.insurances" :key="i.name"><img v-if="i.logoUrl" :src="i.logoUrl" alt=""/>{{i.name}}</li></ul></details><p v-if="p.office" class="its-small">⌂ In-office support</p><details v-if="p.schools.length"><summary>School-based · {{p.schools.length}} {{p.schools.length===1?'school':'schools'}}</summary><ul class="its-profile-schools"><li v-for="s in p.schools" :key="s.id"><img v-if="s.logoUrl" :src="s.logoUrl" alt=""/><button class="its-text-button" @click="school=String(s.id)">{{s.name}}</button></li></ul></details><p class="its-availability">{{availabilityText(p)}}</p><div class="its-card-actions"><router-link class="its-button" :to="{path:'/p/itsco/providers',query:{...(school?{school}:{}),provider:String(p.id)}}">View profile</router-link><router-link v-if="p.onlineScheduling && p.acceptingNewClients" class="its-button its-outline" :to="`/itsco/provider/${p.id}?serviceType=counseling`">View times</router-link><router-link v-else class="its-button its-outline" :to="p.schools.length?'/itsco/school-referral':'/p/itsco/contact'">{{p.acceptingNewClients?'Get started':'Ask about waitlist'}}</router-link></div></div></article></div>
   <div v-if="!filtered.length" class="its-soft"><h3>No matching providers.</h3><p>Try fewer filters or ask our team to help you find support.</p><button class="its-button its-outline" @click="clear">Clear filters</button></div><button v-if="filtered.length>limit" class="its-button its-outline its-load-more" @click="limit+=12">Load more providers →</button>
  </template>
 </section>
</template>
<script setup>
import {computed,ref,watch} from 'vue';
import {useRoute} from 'vue-router';
import PublicProviderProfileEditor from '../publicServices/PublicProviderProfileEditor.vue';
const props=defineProps({providers:{type:Array,default:()=>[]},schools:{type:Array,default:()=>[]},availability:{type:Object,default:()=>({})},availabilityLoading:Boolean,availabilityError:String,agencyId:{type:Number,required:true}});
defineEmits(['refresh','retry-availability']);
const route=useRoute(),mode=ref('all'),school=ref(''),search=ref(''),age=ref(''),specialty=ref(''),insurance=ref(''),accepting=ref(''),openings=ref(''),sort=ref('name'),limit=ref(12);
const modes=[['all','All providers'],['office','In-office providers'],['school','School-based providers']];
watch(()=>route.query.school,v=>{school.value=String(v||'');},{immediate:true});
const selected=computed(()=>props.providers.find(p=>String(p.id)===String(route.query.provider)));
const values=key=>[...new Set(props.providers.flatMap(p=>p[key]||[]))].sort();
const ages=computed(()=>values('ageGroups')),specialties=computed(()=>values('specialties'));
const insurances=computed(()=>[...new Set(props.providers.flatMap(p=>p.insurances.map(i=>i.name)))].sort());
const hasOpenings=p=>Boolean(props.availability[p.id]?.hasPublishedOpenings || props.availability[p.id]?.nextAvailableAt || p.schoolOpenings);
const filtered=computed(()=>props.providers.filter(p=>(mode.value==='all'||(mode.value==='office'?p.office:p.schools.length))&&(!school.value||p.schools.some(s=>String(s.id)===school.value))&&(!age.value||p.ageGroups.includes(age.value))&&(!specialty.value||p.specialties.includes(specialty.value))&&(!insurance.value||p.insurances.some(i=>i.name===insurance.value))&&(!accepting.value||p.acceptingNewClients===(accepting.value==='yes'))&&(!openings.value||(openings.value==='yes'?hasOpenings(p):!hasOpenings(p)&&!props.availabilityLoading&&!props.availabilityError))&&(!search.value||[p.displayName,p.title,p.bio,p.credential,...p.specialties,...p.ageGroups,...(p.details?.languages||[]),...p.schools.map(s=>s.name)].join(' ').toLowerCase().includes(search.value.toLowerCase()))).sort((a,b)=>sort.value==='soonest'?(String(props.availability[a.id]?.nextAvailableAt||'9999').localeCompare(String(props.availability[b.id]?.nextAvailableAt||'9999'))||a.displayName.localeCompare(b.displayName)):a.displayName.localeCompare(b.displayName)));
const profileFacets=computed(()=>selected.value?[['Specialties',selected.value.specialties],['Populations served',[...selected.value.ageGroups,...selected.value.populations]],['Therapy approaches',selected.value.modalities],['Languages',selected.value.details?.languages||[]],['Insurance',selected.value.insurances.map(i=>i.name)],['Session formats',selected.value.details?.sessionFormats||[]]]:[]);
function availabilityText(p){const at=props.availability[p.id]?.nextAvailableAt;if(at)return `Next appointment opening: ${new Date(at).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'})}`;if(props.availability[p.id]?.hasPublishedOpenings && !p.acceptingNewClients)return 'Schedule openings exist · contact our team about the waitlist';if(p.schoolOpenings)return 'School openings reported · confirm with our team';if(p.onlineScheduling&&props.availabilityLoading)return 'Checking appointment times…';if(p.onlineScheduling&&props.availabilityError)return 'Online availability could not be checked';return p.onlineScheduling?'No online times currently published':'Contact our team for current school availability';}
function clear(){mode.value='all';school.value='';search.value='';age.value='';specialty.value='';insurance.value='';accepting.value='';openings.value='';limit.value=12;}
function initials(name){return name.split(' ').map(s=>s[0]).slice(0,2).join('');}
</script>
<style scoped>
.its-provider-modes{display:flex;justify-content:center;gap:6px;flex-wrap:wrap;margin-bottom:28px}.its-provider-modes button{border:1px solid #cedfd7;background:#f4f7f6;border-radius:25px;color:#174b40;padding:12px 25px}.its-provider-modes button[aria-pressed=true]{background:#075540;color:white}.its-provider-filters{display:grid;grid-template-columns:1.6fr repeat(3,1fr);gap:14px}.its-provider-filters label{display:grid;gap:6px;font-size:13px;font-weight:600}.its-provider-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px}.its-provider-card{border:1px solid #dce7e2;border-radius:14px;overflow:hidden;background:white;box-shadow:0 3px 10px #143e2910;display:flex;flex-direction:column}.its-provider-photo{height:210px;position:relative;background:#e7f3ed}.its-provider-photo>img{width:100%;height:100%;object-fit:cover;object-position:center 25%}.its-provider-photo .its-status{position:absolute;bottom:12px;left:12px}.its-provider-copy{padding:18px;flex:1;display:flex;flex-direction:column;gap:11px}.its-provider-copy h3,.its-provider-copy p{margin:0}.its-provider-copy h3{font-size:19px}.its-provider-copy summary{font-size:13px;font-weight:600;cursor:pointer}.its-provider-bio{font-size:13px;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.its-card-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:auto}.its-card-actions .its-button{font-size:12px;padding:10px 12px;flex:1}.its-availability{font-size:12px;font-weight:600;color:#196747}.its-insurance-list,.its-profile-schools{list-style:none;padding:0;font-size:13px}.its-insurance-list li,.its-profile-schools li{display:flex;gap:8px;align-items:center;padding:5px 0}.its-insurance-list img,.its-profile-schools img{width:25px;height:25px;object-fit:contain}.its-profile-top{display:flex;gap:30px;align-items:center;margin:30px 0}.its-profile-top>img,.its-profile-top>.its-avatar{width:180px;height:180px;border-radius:50%;object-fit:cover}.its-profile-body{display:grid;grid-template-columns:2fr 1fr;gap:25px}.its-profile-body .its-card{margin-bottom:20px}.its-full-bio{white-space:pre-line}.its-load-more{display:block;margin:25px auto}.its-profile-body aside{align-self:start}@media(max-width:1200px){.its-provider-grid{grid-template-columns:repeat(3,minmax(0,1fr))}}@media(max-width:900px){.its-provider-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.its-provider-filters{grid-template-columns:repeat(2,minmax(0,1fr))}.its-profile-body{grid-template-columns:1fr}}@media(max-width:580px){.its-provider-grid{grid-template-columns:1fr}.its-provider-filters{grid-template-columns:1fr}.its-provider-photo{height:270px}.its-profile-top{flex-direction:column;align-items:flex-start}.its-provider-modes button{flex:1;padding:11px;font-size:12px}}
</style>
