<template>
 <fieldset class="its-admin-settings"><legend>ITSCO website</legend>
  <p>People, credentials, insurance, and schools come from their actual app records. Use this section for the story and district presentation.</p>
  <label v-for="[key,label] in textFields" :key="key">{{label}}<textarea :value="settings[key]||''" rows="3" @input="update(key,$event.target.value)"/></label>
  <details><summary>District presentation and school groups</summary><article v-for="district in districts" :key="district.slug"><h4>{{district.name}}</h4><label v-for="[key,label] in districtFields" :key="key">{{label}}<input :value="settings.districts?.[district.slug]?.[key]||''" @input="updateDistrict(district.slug,key,$event.target.value)"/></label><details><summary>School groups</summary><label v-for="school in district.schools" :key="school.id">{{school.name}}<select :value="settings.districts?.[district.slug]?.schoolLevels?.[school.id]||''" @change="updateLevel(district.slug,school.id,$event.target.value)"><option value="">Use school name</option><option v-for="level in ['Elementary Schools','Middle Schools','High Schools','Other Schools']" :key="level">{{level}}</option></select></label></details></article><p v-if="!districts.length">Districts appear here once active school portal accounts are linked to ITSCO.</p></details>
  <details><summary>Growth milestones</summary><p>Add only confirmed dates and milestones. With no entries, the website shows the stages of your mission without invented dates.</p><article v-for="(m,i) in settings.milestones||[]" :key="i"><label>Year or period<input :value="m.year" maxlength="35" @input="updateMilestone(i,'year',$event.target.value)"/></label><label>Title<input :value="m.title" maxlength="150" @input="updateMilestone(i,'title',$event.target.value)"/></label><label>Story<textarea :value="m.body" rows="3" @input="updateMilestone(i,'body',$event.target.value)"/></label><button type="button" @click="update('milestones',settings.milestones.filter((_,index)=>index!==i))">Remove milestone</button></article><button type="button" @click="update('milestones',[...(settings.milestones||[]),{year:'',title:'',body:''}])">Add milestone</button></details>
  <p><strong>Save the page below</strong> to publish the story and district changes.</p>
  <form @submit.prevent="saveBaseline"><h3>Historical student total</h3><p>Enter the confirmed number of students connected through today, including records already in the app. Saving starts a new baseline now. Each additional student first linked to an ITSCO school after this update adds one; multiple school assignments count once. This measures connections, not completed therapy visits.</p><p>Schools, districts, and team counts always use live records. They do not need a starting number.</p><p v-if="currentTotal!==null">Currently displayed: <strong>{{currentTotal}}</strong></p><label>Confirmed total through today<input v-model="total" type="number" min="0" max="100000000" step="1" required/></label><label class="its-admin-confirm"><input v-model="confirmed" type="checkbox" required/>I have checked this total and want to start a new baseline.</label><button type="submit" :disabled="busy||!confirmed||total===''">{{busy?'Saving…':'Save historical total now'}}</button><p v-if="notice" role="status">{{notice}}</p><p v-if="error" role="alert">{{error}}</p></form>
 </fieldset>
</template>
<script setup>
import {computed,ref,onMounted} from 'vue';
import api from '../../services/api';
const props=defineProps({modelValue:{type:String,default:'{}'}}),emit=defineEmits(['update:modelValue']);
const branding=computed(()=>{try{return JSON.parse(props.modelValue||'{}');}catch{return {};}}),settings=computed(()=>branding.value.itscoWebsite||{});
const districts=ref([]),currentTotal=ref(null),total=ref(''),confirmed=ref(false),busy=ref(false),notice=ref(''),error=ref('');
const textFields=[['story','Our story'],['mission','Our mission'],['vision','Our vision'],['growthStory','Our growth story']];
const districtFields=[['name','Display name'],['logoUrl','District logo URL or /uploads/ path'],['description','Partnership description'],['websiteUrl','District website (HTTPS)']];
function update(key,value){emit('update:modelValue',JSON.stringify({...branding.value,itscoWebsite:{...settings.value,[key]:value}},null,2));}
function updateDistrict(slug,key,value){update('districts',{...settings.value.districts,[slug]:{...settings.value.districts?.[slug],[key]:value}});}
function updateLevel(slug,id,value){updateDistrict(slug,'schoolLevels',{...settings.value.districts?.[slug]?.schoolLevels,[id]:value});}
function updateMilestone(i,key,value){update('milestones',settings.value.milestones.map((m,index)=>index===i?{...m,[key]:value}:m));}
onMounted(async()=>{try{const{data}=await api.get('/public/marketing-pages/itsco/website-data');districts.value=data.districts;currentTotal.value=data.metrics.studentsSupported;}catch{error.value='Publish ITSCO and apply its website migration to load district settings.';}});
async function saveBaseline(){if(busy.value)return;busy.value=true;notice.value='';error.value='';try{const{data}=await api.post('/platform/public-marketing-pages/itsco/impact-baseline',{studentTotal:Number(total.value)});currentTotal.value=data.studentTotal;notice.value='Historical total saved. Future first-time school connections will be added automatically.';confirmed.value=false;}catch(e){error.value=e.response?.data?.error?.message||'Could not save the total.';}finally{busy.value=false;}}
</script>
<style scoped>
.its-admin-settings{border:1px solid #bbd8c7;border-radius:12px;padding:22px;margin-bottom:25px;background:#f6faf8}.its-admin-settings legend{font-size:20px;font-weight:700}.its-admin-settings label{display:grid;gap:7px;margin:13px 0}.its-admin-settings input,.its-admin-settings textarea,.its-admin-settings select{padding:10px;width:100%;box-sizing:border-box;border:1px solid #b9cfc1;border-radius:6px;font:inherit;background:white}.its-admin-settings article,.its-admin-settings form{border-top:1px solid #cbded2;margin-top:20px;padding-top:18px}.its-admin-settings summary{cursor:pointer;font-weight:600;margin-top:18px}.its-admin-settings button{padding:10px 16px;background:#185b46;color:white;border:0;border-radius:7px;cursor:pointer}.its-admin-settings button:disabled{opacity:.5}.its-admin-confirm{display:flex!important;align-items:center}.its-admin-confirm input{width:auto}
</style>
