import express from 'express';
import rateLimit from 'express-rate-limit';
import { authenticate, requireActiveStatus } from '../middleware/auth.middleware.js';
import * as service from '../services/recordsRequests/service.js';
import { fail } from '../services/recordsRequests/policy.js';
const router=express.Router();
router.param('agencyId',(req,res,next,value)=>Number.isSafeInteger(Number(value))&&Number(value)>0?next():next(fail(400,'Choose a valid practice.')));
const run=fn=>(req,res,next)=>Promise.resolve(fn(req,res)).catch(next);
const publicLimit=rateLimit({windowMs:15*60000,limit:20,standardHeaders:true,legacyHeaders:false});
router.use((req,res,next)=>{res.set({'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Robots-Tag':'noindex, nofollow'});if(!['GET','HEAD','OPTIONS'].includes(req.method)&&(!req.is('application/json')||req.get('X-Records-Request')!=='1'||req.get('Sec-Fetch-Site')==='cross-site'))return next(fail(403,'Use the records-request form to make changes.'));next();});
router.get('/practices',run(async(req,res)=>res.json(await service.publicPractices())));
router.post('/public/:agencyId',publicLimit,run(async(req,res)=>res.status(202).json(await service.submit(Number(req.params.agencyId),req.body))));
router.use(authenticate,requireActiveStatus);
router.get('/context',run(async(req,res)=>res.json(await service.context(req.user.id))));
router.get('/practices/:agencyId/options',run(async(req,res)=>res.json(await service.options(req.user.id,Number(req.params.agencyId)))));
router.put('/practices/:agencyId/options',run(async(req,res)=>res.json(await service.saveOptions(req.user.id,Number(req.params.agencyId),req.body))));
router.get('/practices/:agencyId/patients',run(async(req,res)=>res.json(await service.portalPatients(req.user.id,Number(req.params.agencyId)))));
router.get('/practices/:agencyId/mine',run(async(req,res)=>res.json(await service.requests(req.user.id,Number(req.params.agencyId),true))));
router.post('/practices/:agencyId/mine',publicLimit,run(async(req,res)=>res.status(201).json(await service.submit(Number(req.params.agencyId),req.body,req.user.id))));
router.get('/practices/:agencyId/requests',run(async(req,res)=>res.json(await service.requests(req.user.id,Number(req.params.agencyId)))));
router.patch('/practices/:agencyId/requests/:id',run(async(req,res)=>res.json(await service.review(req.user.id,Number(req.params.agencyId),req.params.id,req.body))));
router.put('/practices/:agencyId/requests/:id/assignment',run(async(req,res)=>res.json(await service.assign(req.user.id,Number(req.params.agencyId),req.params.id,req.body))));
export default router;
