import express from 'express';
import multer from 'multer';
import {authenticate,requireActiveStatus} from '../middleware/auth.middleware.js';
import pool from '../config/database.js';
import {financeScope,financeOrganizations,fail,id,csvCell,audit} from '../services/finance/policy.js';
import {operationalReport} from '../services/finance/reports.js';
import {createRecord,workspace,updateRequest,amendAuthority} from '../services/finance/records.js';
import {createExpense,editExpense,assignExpense,transitionExpense} from '../services/finance/expenses.js';
import {uploadDocument,downloadDocument} from '../services/finance/documents.js';
import {settings,saveSettings,setAccess} from '../services/finance/settings.js';
import {financeBankOverview,reconcileBankExpense} from '../services/finance/bank.js';
import {startBankConnection,completeBankConnection,disconnectBankFeed,syncBankFeed} from '../services/bankFeed.service.js';
import {enableFinanceOrganization} from '../services/finance/setup.js';
import {seedFinanceDemo} from '../services/finance/demo.js';
const router=express.Router(),upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1,fields:12}});
router.use(authenticate,requireActiveStatus,(req,res,next)=>{res.set('Cache-Control','no-store');next();});
const wrap=fn=>async(req,res,next)=>{try{await fn(req,res);}catch(e){if(e.code==='ER_DUP_ENTRY')return next(fail(409,'This reference is already recorded; refresh before retrying'));if(e.type?.startsWith('Stripe'))return next(fail(502,'Bank action needs review; check connection status'));next(e);}};
router.get('/organizations',wrap(async(req,res)=>res.json({organizations:await financeOrganizations(req.user)})));
router.post('/demo',wrap(async(req,res)=>{if(req.user.role!=='super_admin')throw fail(403,'Only a platform administrator can create demo organizations');res.json(await seedFinanceDemo({actorUserId:req.user.id}));}));
router.get('/setup-options',wrap(async(req,res)=>{if(req.user.role!=='super_admin')throw fail(403,'Platform administrator required');const [organizations]=await pool.execute('SELECT id,name FROM agencies WHERE is_active=1 ORDER BY name');res.json({organizations});}));
router.post('/setup',wrap(async(req,res)=>{if(req.user.role!=='super_admin')throw fail(403,'Platform administrator required');res.json(await enableFinanceOrganization({agencyId:req.body.agencyId,managerAgencyId:req.body.managerAgencyId,actorUserId:req.user.id}));}));
router.use('/:agencyId',async(req,res,next)=>{try{req.financeScope=await financeScope(req.user,id(req.params.agencyId));next();}catch(e){next(e);}});
// Scope middleware must invoke next explicitly; all later routes use the verified agency.
router.get('/:agencyId/workspace',wrap(async(req,res)=>res.json(await workspace(req.financeScope))));
router.post('/:agencyId/records/:kind',wrap(async(req,res)=>res.status(201).json(await createRecord(req.financeScope,req.params.kind,req.body))));
router.put('/:agencyId/authority/:kind/:id',wrap(async(req,res)=>res.json(await amendAuthority(req.financeScope,req.params.kind,id(req.params.id),req.body))));
router.post('/:agencyId/expenses',wrap(async(req,res)=>res.status(201).json(await createExpense(req.financeScope,req.body))));
router.patch('/:agencyId/expenses/:id',wrap(async(req,res)=>res.json(await editExpense(req.financeScope,id(req.params.id),req.body))));
router.put('/:agencyId/expenses/:id/funding',wrap(async(req,res)=>res.json(await assignExpense(req.financeScope,id(req.params.id),req.body))));
router.post('/:agencyId/expenses/:id/status',wrap(async(req,res)=>res.json(await transitionExpense(req.financeScope,id(req.params.id),req.body))));
router.put('/:agencyId/requests/:id',wrap(async(req,res)=>res.json(await updateRequest(req.financeScope,id(req.params.id),req.body))));
router.post('/:agencyId/documents',upload.single('file'),wrap(async(req,res)=>res.status(201).json(await uploadDocument(req.financeScope,req.body,req.file))));
router.get('/:agencyId/documents/:id',wrap(async(req,res)=>{const doc=await downloadDocument(req.financeScope,id(req.params.id));res.set({'Content-Type':doc.mime,'Content-Disposition':`attachment; filename*=UTF-8''${encodeURIComponent(doc.name)}`,'X-Content-Type-Options':'nosniff'}).send(doc.buffer);}));
router.get('/:agencyId/reports/:kind.csv',wrap(async(req,res)=>{const data=await workspace(req.financeScope),rows=operationalReport(data,req.params.kind);await audit(pool,req.financeScope,'exported',req.params.kind,null);res.set({'Content-Type':'text/csv','Content-Disposition':`attachment; filename="${data.organization.is_demo?'DEMO-':''}finance-${req.params.kind}.csv"`,'X-Content-Type-Options':'nosniff'}).send(rows.map(r=>r.map(csvCell).join(',')).join('\r\n'));}));
router.get('/:agencyId/settings',wrap(async(req,res)=>res.json(await settings(req.financeScope))));
router.put('/:agencyId/settings',wrap(async(req,res)=>res.json(await saveSettings(req.financeScope,req.body))));
router.put('/:agencyId/access',wrap(async(req,res)=>res.json(await setAccess(req.financeScope,req.body))));
router.get('/:agencyId/bank',wrap(async(req,res)=>res.json(await financeBankOverview(req.financeScope,req.query.after?id(req.query.after):0))));
async function bankScope(req,connect=true){const s=req.financeScope;if(s.role!=='manager')throw fail(403,'Finance manager access required');if(connect&&(!s.org.bank_enabled||s.org.is_demo))throw fail(409,'Enable financial-operations bank consent for a real organization first');return s;}
router.post('/:agencyId/bank/session',wrap(async(req,res)=>{const s=await bankScope(req);res.json(await startBankConnection({agencyId:s.agencyId,actorUserId:s.userId,requestKey:req.body.requestKey,ownerAuthorized:req.body.ownerAuthorized,sharedAccount:false,purpose:'finance_operations'}));}));
router.post('/:agencyId/bank/complete',wrap(async(req,res)=>{const s=await bankScope(req);res.json(await completeBankConnection({agencyId:s.agencyId,actorUserId:s.userId,sessionKey:String(req.body.sessionKey||''),purpose:'finance_operations'}));}));
router.post('/:agencyId/bank/:id/disconnect',wrap(async(req,res)=>{const s=await bankScope(req,false);if(s.org.is_demo)throw fail(409,'Demo bank data has no live connection');res.json(await disconnectBankFeed({agencyId:s.agencyId,actorUserId:s.userId,accountId:id(req.params.id)},{purpose:'finance_operations'}));}));
router.post('/:agencyId/bank/:id/sync',wrap(async(req,res)=>{const s=await bankScope(req);res.json(await syncBankFeed(s.agencyId,id(req.params.id),{purpose:'finance_operations'}));}));
router.post('/:agencyId/bank/entries/:id/match',wrap(async(req,res)=>res.json(await reconcileBankExpense(req.financeScope,id(req.params.id),req.body))));
export default router;
