import express from 'express';
import rateLimit from 'express-rate-limit';
import { authenticate, requireActiveStatus, requireSuperAdmin } from '../middleware/auth.middleware.js';
import * as c from '../controllers/providerMyRoom.controller.js';
import { requireClinicalStaffSecurity } from '../middleware/clinicalStaffSecurity.middleware.js';
const router=express.Router();
router.get('/me/plan',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.getMyRoomPlan);
router.put('/plans/:userId',authenticate,requireClinicalStaffSecurity,requireActiveStatus,requireSuperAdmin,c.putMyRoomPlan);
router.get('/me',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.getMyRoomMe);
router.get('/me/lobby',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.getMyRoomLobby);
router.post('/me/video-token',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.getMyRoomHostVideo);
router.post('/me/heartbeat',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.postMyRoomHeartbeat);
router.post('/me/end',authenticate,requireClinicalStaffSecurity,c.endMyRoom);
router.post('/lobby/:lobbyId/admit',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.admitMyRoomLobbyGuest);
router.post('/lobby/:lobbyId/dismiss',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.dismissMyRoomLobbyGuest);
router.get('/:slug/public',c.getMyRoomPublic);
router.post('/:slug/lobby',rateLimit({windowMs:60000,max:6,standardHeaders:true,legacyHeaders:false}),c.joinMyRoomLobby);
router.get('/:slug/lobby/:lobbyId',c.getMyRoomLobbyGuestStatus);
router.post('/:slug/lobby/:lobbyId/video-token',c.getMyRoomGuestVideo);
router.get('/me/history',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.getMyRoomHistory);
router.get('/me/workspace',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.getOfficeWorkspace);
router.post('/me/workspace/download',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.downloadOfficeArtifact);
router.post('/me/history/:generation/artifacts/download',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.downloadOfficeHistoryArtifact);
router.post('/:slug/lobby/:lobbyId/workspace/download',c.downloadOfficeArtifact);
router.post('/me/workspace',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.postOfficeWorkspace);
router.post('/:slug/lobby/:lobbyId/leave',c.leaveMyRoom);
router.get('/:slug/lobby/:lobbyId/workspace',c.getOfficeWorkspace);
router.post('/:slug/lobby/:lobbyId/workspace',c.postOfficeWorkspace);
router.get('/me/history/:generation/artifacts',authenticate,requireClinicalStaffSecurity,requireActiveStatus,c.getOfficeVisitArtifacts);
export default router;
