export const plotlinePages = {
  home: { title: 'People have a journey. Plotline brings it to life.', description: 'Branded careers pages, recruiting, onboarding, training, and people growth in one thoughtful workspace. Meet Plotline by PlotTwistCo.' },
  product: { title: 'One platform. Every next chapter.', description: 'Explore Plotline careers, applicant tracking, interviews, onboarding, learning, people records, and growth.' },
  solutions: { title: 'People operations for real-world organizations.', description: 'Find a connected approach to recruiting, onboarding, training, people management, and multi-organization work.' },
  careers: { title: 'Your careers page. Built into recruiting.', description: 'Build your online recruiting presence with a branded careers page included in every Plotline plan. See live ITSCO and Next Level Up examples, from open roles to applications.' },
  resources: { title: 'A little guidance for what comes next.', description: 'Practical hiring, onboarding, and learning checklists for people-centered teams.' },
  about: { title: 'People make the plot.', description: 'Get to know Plotline, the people operations product by PlotTwistCo.' },
  pricing: { title: 'Simple pricing. Room to grow.', description: 'Plotline starts at $199 per month for 25 active employees. Explore connected product savings and calculate your estimate.' },
  start: { title: 'Let’s build your next chapter.', description: 'Request a Plotline walkthrough or talk with our team about your organization.' }
};

export const plotlineSolutions = [
  { id:'recruiting', icon:'hiring', title:'Recruiting', short:'Recruit', line:'Build your online presence. Welcome your next hire.', body:'Recruiting starts with your branded careers page, included in every plan. Share your story and open roles, welcome applications, and bring candidates through interviews and hiring in one workspace.', points:['Build your recruiting front door with your logo, culture, benefits, and job listings.','Link your careers page from your website and outreach so candidates can apply.','Keep applications, receipts, interview invitations, and candidate feedback together.','Continue into onboarding when your next teammate is hired.'], screen:'hiring', screenTitle:'Hiring dashboard', photo:'feature-recruit.jpg' },
  { id:'onboarding', icon:'onboarding', title:'Onboarding', short:'Onboard', line:'Make the first day feel like a beginning.', body:'Turn the space between “you’re hired” and “I’m ready” into a welcoming, organized experience.', points:['Create a clear path through pre-hire and onboarding tasks.','Keep documents, acknowledgments, and required learning in view.','Help your team follow progress and see what needs attention.'], screen:'onboarding', screenTitle:'Onboarding progress', photo:'feature-onboard.jpg' },
  { id:'training', icon:'training', title:'Training & development', short:'Train', line:'Give potential a place to grow.', body:'Bring learning paths, assigned training, and completion progress into the same people workspace.', points:['Organize modules and learning tracks for your team.','Assign learning that supports each person’s role.','Follow completion and make the next step easier to find.'], screen:'learning', screenTitle:'Employee learning library', photo:'feature-train.jpg' },
  { id:'people', icon:'people', title:'People management', short:'Manage', line:'The person behind the paperwork.', body:'Keep people information, employee documents, and the work of supporting your team connected.', points:['Find the team information you’re authorized to see.','Keep employee documents and relationships organized.','Give each organization a clear identity within its workspace.'], screen:'onboarding', screenTitle:'Employee onboarding roster', photo:'feature-manage.jpg' },
  { id:'growth', icon:'growth', title:'Growth & performance', short:'Grow', line:'Make room for what’s next.', body:'Connect development conversations, evaluations, and learning progress to the people doing the work.', points:['Bring employee evaluations into the people journey.','Connect development needs with learning opportunities.','Build a more consistent rhythm for supporting your team.'], screen:'evaluations', screenTitle:'Employee evaluations', photo:'feature-grow.jpg' },
  { id:'documents', icon:'documents', title:'Documents & readiness', short:'Organize', line:'A little more clarity. A little less chasing.', body:'Keep required documents, acknowledgments, and training tasks visible to the people responsible for them.', points:['Collect documents through established onboarding workflows.','Track outstanding tasks and completed acknowledgments.','Support your organization’s processes with clear records.'], screen:'checklist', screenTitle:'Employee onboarding checklist' },
  { id:'organizations', icon:'multi-entity', title:'Multiple organizations', short:'Connect', line:'A shared platform. Distinct identities.', body:'Move between organizations you’re authorized to support, with the right company context and permissions.', points:['Keep each employer’s name and branding primary.','Switch between your authorized organizations.','Discuss organization-by-organization setup and pricing with our team.'], screen:'organizations', screenTitle:'Multi-organization hiring pipeline' }
];

export const plotlineGuides = [
  { id:'hiring', title:'A more human hiring checklist', label:'Before the first application', intro:'Set your team and your candidates up for a clearer conversation.', steps:['Define the role, essential responsibilities, and evaluation criteria before publishing.','Build your branded careers page with your organization’s story, culture, benefits, and open roles; link it from your website and outreach.','Choose who reviews applications and who owns each next step.','Use consistent interview questions tied to the role.','Acknowledge applications and communicate the next step clearly.','Close the loop with candidates and prepare a thoughtful handoff to onboarding.'] },
  { id:'onboarding', title:'The first 30 days, with intention', label:'From offer to belonging', intro:'Make a new teammate’s arrival an experience someone has thought through.', steps:['Before day one: confirm the start date, contact person, and outstanding documents.','Prepare the accounts, equipment, and information the role requires.','Share a first-week plan and introduce the people who can help.','Assign essential policies and learning in manageable steps.','Schedule a first-week check-in to surface questions early.','At 30 days: review progress together and agree on the next learning goals.'] },
  { id:'learning', title:'Build a learning path that lasts', label:'Beyond the checklist', intro:'Create a useful rhythm for learning, practice, and reflection.', steps:['Start with what someone needs to do confidently in their role.','Separate essential first-week learning from ongoing development.','Give each module a clear purpose and a practical next action.','Assign an owner to keep content accurate and useful.','Review completion alongside questions and real-world practice.','Revisit the path when a role, process, or organization changes.'] }
];

export const plotlineFaqs = [
  ['Is a branded careers page included with recruiting?', 'Yes. Every Plotline plan includes a branded careers page as part of recruiting, with your organization’s story, logo, and open roles. Link it from your website and recruiting outreach so candidates can learn about your team and apply. Applications, interviews, hiring, and onboarding continue in the same people workspace. The careers-page feature has no separate add-on fee; any requested custom implementation work is scoped separately.'],
  ['Can we use Plotline on its own?', 'Yes. Plotline is offered as its own people operations product. Your team can focus on careers, hiring, onboarding, training, and people growth. You do not need to purchase another PlotTwistCo product.'],
  ['What counts as an active employee?', 'The estimate includes 25 active employees per organization, then $4 per additional active employee each month. Applicants and archived employee records do not count. We confirm your employee count and scope before your subscription begins.'],
  ['How do bundle savings work?', 'One other qualifying paid product at the same organization gives a $50 monthly Plotline credit. Two or more give a $70 monthly credit. Qualifying families are AuricWell, SchoolCareBridge, and Conversa. Credits do not stack; the other products are billed separately. Eligibility is confirmed during setup.'],
  ['Will candidates see our organization’s brand?', 'Yes. Your logo, organization name, job information, and communications remain primary. Plotline appears as a subtle software credit on the candidate journey.'],
  ['Is this a payroll or benefits system?', 'Plotline focuses on people operations: careers, hiring, onboarding, learning, people records, and growth. Payroll, benefits administration, background checks, and external services are not included in the published subscription.'],
  ['Can you help with setup or multiple organizations?', 'Yes. Tell us about your organization structure, existing records, and training needs. We will agree on setup, migration, or custom content work separately before starting. Each organization’s subscription and access are confirmed during setup.'],
  ['Does requesting a plan start a subscription?', 'No. Your request starts a conversation. We confirm availability, scope, pricing, and any setup work before activation. No payment is collected through this website.']
];
