/** Default clinical intervention catalog (agency + user pickers). */
export const CLINICAL_INTERVENTION_SEED = [
  'Active Listening',
  'Assertiveness Training',
  'Behavioral Intervention',
  'Boundary Development',
  'CBT',
  'Cognitive Challenging',
  'Cognitive Refocusing',
  'Cognitive Reframing',
  'Cognitive Restructuring',
  'Communication Skills',
  'Community Support',
  'Compliance Issues',
  'Conflict Resolution Strategies',
  'DBT',
  'Emotional Awareness',
  'Empathetic Responses',
  'Exploration of Boundaries',
  'Exploration of Coping Patterns',
  'Exploration of Emotions',
  'Exploration of Relationship Patterns',
  'Exploration of Safety Planning',
  'Exploration of Self Care',
  'Exposure Therapy',
  'Gratitude Practices',
  'Guided Imagery',
  'Interactive Feedback',
  'Interpersonal Resolutions',
  'Journaling',
  'Mindfulness Training',
  'Physical Wellness Planning',
  'Preventative Services',
  'Progressive Muscle Relaxation',
  'Psycho-Education',
  'Rapport Building',
  'Relaxation/Deep Breathing',
  'Review of Treatment Plan/Progress',
  'Role-Play/Behavioral Rehearsal',
  'Skill Development',
  'Social Skills Training',
  'Solution Collaboration',
  'SPT Observational Statements',
  'Structured Problem Solving',
  'Supportive Reflection',
  'Symptom Management',
  'Synergetic Play Therapy',
  'Time Management Training',
  'Unconditional Positive Regard',
  'Visualization techniques'
];
