// Generated by scripts/plans/sync-feature-catalog.mjs. Edit the approved inventory, then regenerate.
export const PLAN_TIERS = Object.freeze([{"id":"basic","name":"Basic"},{"id":"premium","name":"Premium"},{"id":"premium_plus","name":"Premium Plus"}]);
export const PLAN_FEATURES = Object.freeze([
  {
    "key": "ai_note_aid",
    "label": "Documentation Hub",
    "description": "AI assistance for drafting notes; clinician reviews and signs.",
    "category": "Clinical",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "private_office",
    "label": "Private virtual office",
    "description": "Permanent office URL, photo review and individual admission; one guest.",
    "category": "Meetings",
    "minimumTier": "premium",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "individual"
  },
  {
    "key": "multiple_office_guests",
    "label": "Multiple private-office guests",
    "description": "Individually admit additional guests for couples and families.",
    "category": "Meetings",
    "minimumTier": "premium_plus",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "individual"
  },
  {
    "key": "schedule",
    "label": "Calendar and scheduling",
    "description": "Schedule appointments and meetings, recurring dates, availability and reminders.",
    "category": "Scheduling",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "calendar_sync",
    "label": "Google Calendar integration",
    "description": "Calendar invitations and external busy time.",
    "category": "Scheduling",
    "minimumTier": "premium",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "office_booking",
    "label": "Office and room reservations",
    "description": "Physical rooms, office availability and booking.",
    "category": "Scheduling",
    "minimumTier": "premium_plus",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "video_meetings",
    "label": "Scheduled video meetings",
    "description": "Video, square camera tiles, screen sharing and waiting rooms.",
    "category": "Meetings",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "personal_join",
    "label": "Personal meeting invitations",
    "description": "Individual email links and attendance identity.",
    "category": "Meetings",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "recording_transcription",
    "label": "Recording and transcription",
    "description": "Consent-gated session audio transcription.",
    "category": "Meetings",
    "minimumTier": "premium",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "transcript_notes",
    "label": "Notes from session transcripts",
    "description": "Create draft clinical notes using signed-consent session transcripts.",
    "category": "Clinical",
    "minimumTier": "premium",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "meeting_notes",
    "label": "Meeting notes and summaries",
    "description": "Personal notes, summaries and meeting history.",
    "category": "Meetings",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "supervision",
    "label": "Supervision scheduling and history",
    "description": "Supervisor/supervisee sessions, history and tracked attendance.",
    "category": "Supervision",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "supervision_manual",
    "label": "Manual and in-person supervision",
    "description": "Log off-platform supervision with reasons and in-person transcription.",
    "category": "Supervision",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "supervision_agreements",
    "label": "Supervision agreements",
    "description": "Onboarding agreements and supervisor countersignatures.",
    "category": "Supervision",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "client_records",
    "label": "Client charts and records",
    "description": "Practice-scoped client records and treatment information.",
    "category": "Clinical",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "clinical_signing",
    "label": "Clinical documentation and signatures",
    "description": "Structured notes, signing and cosigning.",
    "category": "Clinical",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "intake",
    "label": "Intake and digital forms",
    "description": "Client intake, digital waivers and signatures.",
    "category": "Clinical",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "client_portal",
    "label": "Client and guardian portal",
    "description": "Patient access, appointments and guardian workflows.",
    "category": "Clinical",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "messages",
    "label": "Secure messaging",
    "description": "Practice and client messaging.",
    "category": "Communication",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "payments",
    "label": "Client payments",
    "description": "Balances, invoices and payment workflows.",
    "category": "Billing",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "insurance_claims",
    "label": "Insurance billing and claims",
    "description": "Claims, remittances, fee schedules and payer configuration.",
    "category": "Billing",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "imports",
    "label": "Data import and migration",
    "description": "Reviewed provider, client and historical record import.",
    "category": "Practice",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "practice_reports",
    "label": "Practice reports",
    "description": "Operational and financial reporting.",
    "category": "Practice",
    "minimumTier": "basic",
    "products": [
      "platform",
      "auricwell"
    ],
    "scope": "agency"
  },
  {
    "key": "publicAvailability",
    "label": "Public Provider Finder",
    "description": "External/public provider availability pages and provider finder publishing.",
    "category": "Platform catalog",
    "minimumTier": "premium_plus",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "momentumList",
    "label": "My Work",
    "description": "Momentum Stickies, digest, and focus assistant billed per active employee.",
    "category": "Platform catalog",
    "minimumTier": "basic",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "officeSchedulingPublishing",
    "label": "Shift Programs",
    "description": "Shift-based programs, scheduling workflows, and related operational publishing.",
    "category": "Platform catalog",
    "minimumTier": "basic",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "payrollWorkspace",
    "label": "Payroll workspace",
    "description": "Payroll management tools and related admin workflows.",
    "category": "Platform catalog",
    "minimumTier": "premium",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "onboardingTraining",
    "label": "Onboarding & Training",
    "description": "Onboarding packages, checklist templates, intake forms, and related tenant workflows.",
    "category": "Platform catalog",
    "minimumTier": "premium_plus",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "trainingAiModuleBuilder",
    "label": "Training AI Module Builder",
    "description": "Gemini-assisted training modules from handbook uploads and source documents (Module Manager).",
    "category": "Platform catalog",
    "minimumTier": "premium_plus",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "schoolPortals",
    "label": "School portals & school overview",
    "description": "School overview dashboard, school-scoped portal routes, digital intakes hub, and school staff sign-in for assigned school organizations.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "skillBuildersSchoolProgram",
    "label": "Skill Builders school program",
    "description": "School/program Skill Builders calendar, event portal, skills groups roster, provider hub program events, and related APIs.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "budgetManagementEnabled",
    "label": "Budget Management",
    "description": "Budget planning, fiscal year tracking, expense management, and related finance workflows.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "hiringEnabled",
    "label": "Hiring Process",
    "description": "Applicant tracking, candidate pipelines, and hiring workflow management.",
    "category": "Platform catalog",
    "minimumTier": "premium_plus",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "peopleOpsEnabled",
    "label": "People Operations",
    "description": "Full HR and People Ops suite: On-Demand Training, Training Modules, and Progress tracking.",
    "category": "Platform catalog",
    "minimumTier": "premium_plus",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "aiProviderSearchEnabled",
    "label": "AI Provider Search",
    "description": "Gemini-powered provider search and smart directory filtering.",
    "category": "Platform catalog",
    "minimumTier": "basic",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "presenceEnabled",
    "label": "Presence / Team Board",
    "description": "Presence statuses, team board visibility, and availability signaling for staff.",
    "category": "Platform catalog",
    "minimumTier": "basic",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "emailAppAssistant",
    "label": "Email App Assistant",
    "description": "Reply to app@tenant with office availability, school coverage (privileged), and task creation. SMS replies planned later.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "kudosEnabled",
    "label": "Kudos",
    "description": "Peer recognition, points, and reward-oriented appreciation tools.",
    "category": "Platform catalog",
    "minimumTier": "premium",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "medcancelEnabled",
    "label": "Med Cancel",
    "description": "Medication cancellation claim submissions and related notifications.",
    "category": "Platform catalog",
    "minimumTier": "basic",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "inSchoolSubmissionsEnabled",
    "label": "In-School Submissions",
    "description": "School mileage and other in-school claims submission workflows.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "googleSsoEnabled",
    "label": "Google Workspace SSO",
    "description": "Google sign-in rules and enforced Workspace login for selected roles.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "workspaceProvisioningEnabled",
    "label": "Workspace Provisioning",
    "description": "Provision Google Workspace accounts and related pre-hire automation.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "bookClubEnabled",
    "label": "Book Club",
    "description": "Tenant-wide book club, voting, meetings, and public preview experiences.",
    "category": "Platform catalog",
    "minimumTier": "basic",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "standardsLearningEnabled",
    "label": "Standards-Aligned Learning",
    "description": "Learning standards, goals, and progress tracking workflows.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "groupClassSessionsEnabled",
    "label": "Group Class Sessions",
    "description": "Learning class sessions, moderation tools, and live class telemetry.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "guardianWaiversEnabled",
    "label": "Guardian Waivers",
    "description": "Guardian waivers and kiosk check-in eligibility gating.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "platformSharedMarketingEnabled",
    "label": "Shared Marketing",
    "description": "Inclusion in platform-shared marketing and event promotion surfaces.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "platformPublicRegistrationEnabled",
    "label": "Public Registration Links",
    "description": "Public registration catalogs and marketing enrollment links for this tenant.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "gamesPlatformEnabled",
    "label": "Games Platform",
    "description": "Access to the mental health games platform and enabled game titles.",
    "category": "Platform catalog",
    "minimumTier": "premium_plus",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "focusPackage",
    "label": "Focus Package",
    "description": "Focus Music playlists plus Focus Session (timeline focus mode, quote images, and session audio).",
    "category": "Platform catalog",
    "minimumTier": "premium",
    "products": [
      "platform"
    ],
    "scope": "agency"
  },
  {
    "key": "focusMusic",
    "label": "Focus Music (legacy)",
    "description": "Legacy Focus Music add-on; superseded by Focus Package.",
    "category": "Platform catalog",
    "minimumTier": "premium",
    "products": [
      "platform"
    ],
    "scope": "agency",
    "aliasOf": "focusPackage"
  },
  {
    "key": "summerProgramManagement",
    "label": "Summer program management",
    "description": "Custom project billing for registration, kiosk check-ins, staffing, and operational setup.",
    "category": "Platform catalog",
    "minimumTier": "separate",
    "products": [
      "platform"
    ],
    "scope": "agency"
  }
].map(feature => Object.freeze({ ...feature, products: Object.freeze(feature.products) })));
