<template>
  <div class="business-review">
    <header><div><p class="br-kicker">Plot Twist Co. · Company onboarding</p><h2>Your next partnerships</h2><p>Review business requests, confirm the owner, and invite approved companies into their own workspace.</p></div><button @click="load" :disabled="loading">Refresh</button></header>
    <p class="br-note">A company workspace is a top-level tenant. Schools and programs must be added as affiliated organizations inside an existing tenant. Confirm the business and owner before approving an invitation.</p>
    <div class="br-filters"><label>Find a request<input v-model="query" type="search" placeholder="Business, owner, email…"></label><label>Status<select v-model="status"><option value="">All statuses</option><option v-for="s in ['submitted','approved','activated','declined']" :key="s">{{ s }}</option></select></label><router-link to="/p/ptco/start">Open public business intake →</router-link></div>
    <p v-if="error" role="alert" class="br-error">{{ error }}</p><p v-if="loading" role="status">Loading company requests…</p><p v-else-if="!filtered.length">No requests match this view.</p>
    <div v-else class="br-requests"><article v-for="row in filtered" :key="row.id"><div class="br-request-top"><div><span class="br-status">{{ row.status }}</span><h3>{{ row.businessName }}</h3><p>{{ row.firstName }} {{ row.lastName }} · {{ row.email }} · {{ row.phone }}</p></div><time>{{ new Date(row.createdAt).toLocaleDateString() }}</time></div><dl><dt>Starting point</dt><dd>{{ row.path }} · {{ row.businessType }} · {{ row.stage }}</dd><dt>Services</dt><dd>{{ row.services.join(', ') || 'Discuss best fit' }}</dd><dt>Business goals</dt><dd>{{ row.goals }}</dd></dl>
      <form v-if="['submitted','approved'].includes(row.status)" @submit.prevent="approve(row)"><label>Company workspace URL<input v-model.trim="slugs[row.id]" pattern="[a-z][a-z0-9-]{2,59}" minlength="3" maxlength="60" required placeholder="company-name"></label><label class="br-checkbox"><input v-model="emails[row.id]" type="checkbox">Email the invitation to {{ row.email }}</label><div class="br-actions"><button class="br-primary" :disabled="busy===row.id">{{ busy===row.id?'Working…':row.status==='approved'?'Replace invitation':'Approve & create invitation' }}</button><button type="button" :disabled="busy===row.id" @click="decline(row)">Decline request</button></div><small v-if="row.status==='approved'">Creating a replacement invalidates the previous invitation.</small></form>
      <div v-if="invitations[row.id]" class="br-invitation"><p>{{ emailMessage(invitations[row.id].emailStatus) }}</p><p>This invitation expires in 7 days. Share it only with the approved owner.</p><button @click="copy(row.id)">{{ copied===row.id?'Copied':'Copy owner invitation' }}</button></div>
      <router-link v-if="row.status==='activated'" :to="`/${row.approvedSlug}/admin/settings?category=general&item=company-profile&agencyId=${row.agencyId}`">Open company workspace →</router-link>
      <small class="br-ref">Reference {{ row.id }}</small>
    </article></div><small>Showing the most recent 200 requests. Business contact information is available only to platform administrators.</small>
  </div>
</template>
<script setup>
import {computed,onMounted,reactive,ref} from 'vue';
import api from '../../services/api';
const rows=ref([]),loading=ref(false),error=ref(''),busy=ref(''),query=ref(''),status=ref(''),slugs=reactive({}),emails=reactive({}),invitations=reactive({}),copied=ref('');
const filtered=computed(()=>rows.value.filter(r=>(!status.value||r.status===status.value)&&`${r.businessName} ${r.firstName} ${r.lastName} ${r.email}`.toLowerCase().includes(query.value.trim().toLowerCase())));
async function load(){loading.value=true;error.value='';try{rows.value=(await api.get('/platform/business-onboarding')).data.requests;for(const r of rows.value){slugs[r.id]??=r.approvedSlug||r.businessName.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60);emails[r.id]??=false;}}catch(e){error.value=e.response?.data?.error?.message||'Could not load company requests.';}finally{loading.value=false;}}
async function approve(row){busy.value=row.id;error.value='';try{invitations[row.id]=(await api.post(`/platform/business-onboarding/${row.id}/approve`,{slug:slugs[row.id],sendEmail:emails[row.id]})).data;await load();}catch(e){error.value=e.response?.data?.error?.message||'The invitation could not be created.';}finally{busy.value='';}}
async function decline(row){busy.value=row.id;error.value='';try{await api.post(`/platform/business-onboarding/${row.id}/decline`);delete invitations[row.id];await load();}catch(e){error.value=e.response?.data?.error?.message||'The request could not be updated.';}finally{busy.value='';}}
async function copy(id){try{await navigator.clipboard.writeText(invitations[id].activationUrl);copied.value=id;}catch{error.value='Your browser could not copy the invitation. Allow clipboard access and try again.';}}
function emailMessage(s){return ({pending_approval:'Invitation email is queued for administrator approval. It has not been sent yet.',sent:'Invitation email sent.',failed:'Invitation created, but email delivery failed. Copy the invitation or create a replacement to retry.',not_sent:'The email service did not send this invitation. You can copy it for the approved owner.',redirected:'Email was redirected by a test/demo policy. The owner has not received it.',not_requested:'Invitation created. No email was sent.'})[s]||'Check delivery before sharing access.';}
onMounted(load);
</script>
<style scoped>
.business-review{padding:20px;color:var(--text-primary,#202737)}header{display:flex;justify-content:space-between;gap:24px;align-items:start}h2{font-size:30px;margin:6px 0 10px}p{color:var(--text-secondary,#647084);line-height:1.6}.br-kicker{font-size:11px;font-weight:750;text-transform:uppercase;letter-spacing:.1em;color:#941426}.br-note{padding:18px 22px;border:1px solid var(--border,#ddd);border-radius:10px;background:var(--bg-secondary,#f7f8fc);font-size:14px}.br-filters{display:flex;gap:20px;align-items:end;margin:24px 0}.br-filters>label:first-child{flex:1}label{display:block;font-size:13px;font-weight:600}input:not([type=checkbox]),select{display:block;width:100%;margin-top:7px;border:1px solid var(--border,#ddd);border-radius:7px;padding:11px;background:var(--bg,#fff);color:inherit}button{border:1px solid var(--border,#ddd);border-radius:7px;padding:10px 18px;background:var(--bg,#fff);color:inherit;cursor:pointer;min-height:42px}button:disabled{opacity:.55;cursor:wait}.br-primary{background:#841124;color:white;border-color:#841124}.br-requests{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:24px}.br-requests article{border:1px solid var(--border,#ddd);border-radius:12px;padding:24px;min-width:0}.br-request-top{display:flex;justify-content:space-between;align-items:start;gap:20px}.br-request-top h3{font-size:22px;margin:10px 0 5px}.br-request-top p{font-size:13px;overflow-wrap:anywhere}.br-request-top time{font-size:12px;white-space:nowrap;color:var(--text-secondary,#647084)}.br-status{display:inline-block;padding:4px 9px;font-size:11px;border-radius:20px;background:#f2e9eb;color:#821526;text-transform:uppercase;font-weight:700}dl{display:grid;grid-template-columns:100px 1fr;gap:12px;font-size:14px}dt{font-weight:650}dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere}.br-checkbox{display:flex;gap:10px;align-items:center;margin:14px 0}.br-checkbox input{width:18px;height:18px}.br-actions{display:flex;gap:10px;margin-bottom:10px}.br-invitation{padding:16px;margin:20px 0;background:var(--bg-secondary,#f7f8fc);border-radius:8px}.br-invitation p{font-size:13px;margin:0 0 8px}.br-ref{display:block;margin-top:20px;color:var(--text-secondary,#647084);overflow-wrap:anywhere}.br-error{border:1px solid #d89da7;background:#fff2f3;color:#8b1526;padding:15px;border-radius:8px}:is(button,input,select,a):focus-visible{outline:3px solid #a52238;outline-offset:3px}@media(max-width:1100px){.br-requests{grid-template-columns:1fr}}@media(max-width:650px){.business-review{padding:10px}.br-filters,header{flex-direction:column;align-items:stretch}.br-request-top{display:block}dl{grid-template-columns:1fr;gap:6px}dd{margin-bottom:10px}}
</style>
