<template>
  <div class="company-workspace">
    <p v-if="loading" role="status">Loading company workspace…</p><p v-else-if="error" role="alert">{{ error }}</p>
    <div v-else-if="!company" class="cw-empty"><h2>Choose your company</h2><p>Select a company workspace in the tenant picker above to begin setup.</p></div>
    <div v-else-if="!isRootTenant(company)" class="cw-empty"><span class="cw-badge">{{ organizationKindLabel(company) }}</span><h2>{{ company.name }}</h2><p>This organization is affiliated with a company. Company branding, services, billing, and team access belong to the parent tenant. Select that company in the tenant picker to manage its workspace.</p></div>
    <template v-else>
      <header class="cw-header"><div><span class="cw-badge">Company workspace</span><h2>{{ company.name }}</h2><p>Your identity, your team, your next chapter.</p></div><span class="cw-address">/{{ company.portal_url || company.slug }}</span></header>
      <nav class="cw-view-nav" aria-label="Company setup views"><button :aria-pressed="!details" @click="details=false">Setup overview</button><button :aria-pressed="details" @click="details=true">Business details & preferences</button></nav>
      <section v-show="!details" class="cw-overview"><div class="cw-intro"><div><p class="cw-kicker">Start here</p><h3>A clear path to your workspace</h3><p>Work through these steps with your team. Each opens the settings that control your company.</p></div><label>Find a setup area<input v-model="query" type="search" placeholder="Brand, team, billing, schools…"></label></div>
        <div class="cw-grid"><button v-for="(item,i) in filteredSteps" :key="item.id" @click="open(item)"><span class="cw-step">{{ item.number }}</span><div><h4>{{ item.title }}</h4><p>{{ item.body }}</p><span class="cw-open">{{ item.id==='identity'?'Edit business details':'Open settings' }} →</span></div></button></div><p v-if="!filteredSteps.length">No setup areas match your search.</p>
        <aside class="cw-affiliation"><h3>Company or affiliated organization?</h3><p><strong>This company</strong> owns its workspace, billing, branding, and administrator access. <strong>Schools and programs</strong> are connected organizations with their own information and permissions. Adding an affiliation does not create another tenant or grant access automatically.</p><button @click="open({category:'platform',item:'tenant-ws-org-directory'})">Manage affiliated organizations →</button></aside>
      </section>
      <AgencyManagement v-if="hasOpenedDetails" v-show="details" :key="company.id" :embedded-org-id="company.id" :embedded-tab="embeddedTab" workspace-mode />
    </template>
  </div>
</template>
<script setup>
import {computed,ref,watch} from 'vue';
import {useRoute,useRouter} from 'vue-router';
import {useAgencyStore} from '../../store/agency';
import api from '../../services/api';
import AgencyManagement from './AgencyManagement.vue';
import {isRootTenant,organizationKindLabel} from '../../navigation/organizationKinds';
const props=defineProps({embeddedOrgId:{type:[Number,String],default:null},embeddedTab:{type:String,default:'general'},scopedAgencyId:{type:[Number,String],default:null}});
const store=useAgencyStore(),route=useRoute(),router=useRouter(),company=ref(null),loading=ref(false),error=ref(''),query=ref(''),details=ref(!!route.query.agencyTab);
const hasOpenedDetails=ref(details.value);watch(details,value=>{if(value)hasOpenedDetails.value=true;});
const id=computed(()=>Number(props.embeddedOrgId||props.scopedAgencyId||store.currentAgency?.id)||null);
let request=0;
watch(id,async value=>{const current=++request;company.value=null;error.value='';loading.value=false;if(!value)return;loading.value=true;try{const {data}=await api.get(`/agencies/${value}`);if(current===request)company.value=data.agency||data;}catch{if(current===request)error.value='We could not load this company. Please reopen its settings.';}finally{if(current===request)loading.value=false;}},{immediate:true});
const steps=[{number:1,id:'identity',title:'Your business identity',body:'Name, contact information, address, branding, and workspace preferences.'},{number:2,id:'services',title:'Your services & booking',body:'Choose counseling, tutoring, coaching, or consulting and define what clients can book.',category:'general',item:'booking-service-types'},{number:3,id:'features',title:'Your tools & features',body:'Review the capabilities available to your company and choose what to enable.',category:'general',item:'tenant-features'},{number:4,id:'team',title:'Your team & access',body:'Assign administrators and roles so the right people have the right access.',category:'general',item:'team-roles'},{number:5,id:'billing',title:'Your company billing',body:'Review your platform billing, payment setup, and account responsibilities.',category:'general',item:'billing'},{number:6,id:'affiliations',title:'Schools & affiliated organizations',body:'Manage partner schools and programs separately from your company workspace.',category:'platform',item:'tenant-ws-org-directory'}];
const filteredSteps=computed(()=>steps.filter(s=>`${s.title} ${s.body}`.toLowerCase().includes(query.value.trim().toLowerCase())));
function open(item){if(item.id==='identity'){details.value=true;return;}router.push({path:route.path,query:{category:item.category,item:item.item,agencyId:company.value.id}});}
</script>
<style scoped>
.company-workspace{color:var(--text-primary,#202737);min-width:0}.cw-header{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:30px;background:linear-gradient(120deg,var(--bg-secondary,#f7f5f3),var(--bg,#fff));border:1px solid var(--border,#e4e6ec);border-radius:14px}.cw-header h2{font-size:30px;letter-spacing:-.03em;margin:10px 0 6px}.cw-header p{margin:0;color:var(--text-secondary,#647084)}.cw-badge,.cw-kicker{font-size:11px;font-weight:750;letter-spacing:.1em;text-transform:uppercase;color:var(--primary,#8c1020)}.cw-address{font-size:13px;padding:10px 15px;border-radius:8px;border:1px solid var(--border,#ddd);overflow-wrap:anywhere}.cw-view-nav{display:flex;gap:10px;border-bottom:1px solid var(--border,#ddd);margin:22px 0}.cw-view-nav button{padding:14px 18px;border:0;border-bottom:3px solid transparent;background:transparent;color:inherit;font-weight:650;cursor:pointer}.cw-view-nav button[aria-pressed=true]{border-color:var(--primary,#8c1020);color:var(--primary,#8c1020)}.cw-intro{display:flex;align-items:center;justify-content:space-between;gap:24px;margin:28px 0}.cw-intro h3{font-size:24px;margin:5px 0 10px}.cw-intro p{max-width:650px;color:var(--text-secondary,#647084)}.cw-intro label{font-size:12px;min-width:220px}.cw-intro input{display:block;width:100%;padding:12px;border:1px solid var(--border,#ddd);border-radius:8px;margin-top:7px;background:var(--bg,#fff);color:inherit}.cw-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.cw-grid button{display:flex;align-items:flex-start;gap:18px;text-align:left;background:var(--bg,#fff);color:inherit;border:1px solid var(--border,#ddd);border-radius:12px;padding:24px;cursor:pointer}.cw-grid button:hover{border-color:var(--primary,#8c1020);box-shadow:0 5px 24px #1421380a}.cw-step{display:grid;place-items:center;flex-shrink:0;background:var(--bg-secondary,#f3f4f8);border-radius:50%;height:35px;width:35px;font-weight:700}.cw-grid h4{margin:4px 0 10px;font-size:17px}.cw-grid p{font-size:14px;line-height:1.6;color:var(--text-secondary,#647084);margin:0 0 20px}.cw-open{font-size:13px;font-weight:650;color:var(--primary,#8c1020)}.cw-affiliation{padding:26px;border:1px solid var(--border,#ddd);border-radius:12px;margin-top:24px;background:var(--bg-secondary,#f8f9fc)}.cw-affiliation h3{margin-top:0}.cw-affiliation p{max-width:1000px;line-height:1.7;font-size:14px}.cw-affiliation button{background:transparent;border:0;color:var(--primary,#8c1020);padding:0;cursor:pointer;font-weight:650}.cw-empty{padding:40px;max-width:800px}.company-workspace :is(button,input):focus-visible{outline:3px solid var(--primary,#8c1020);outline-offset:4px}@media(max-width:1100px){.cw-grid{grid-template-columns:1fr 1fr}.cw-intro{display:block}}@media(max-width:650px){.cw-grid{grid-template-columns:1fr}.cw-header{padding:22px;align-items:start;flex-direction:column}.cw-view-nav button{padding:12px;font-size:13px}}
</style>
