<template><section class="secondary-claim"><h3>Secondary insurance</h3><button type="button" :disabled="busy" @click="load">Prepare / update secondary draft</button><p v-if="error" role="alert">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p>
 <form v-if="lines.length" @submit.prevent="save"><p>Use the primary ERA/EOB. Include all services, payments and adjustments, including denied lines. This creates or updates the linked secondary draft; it does not submit a claim or post money.</p>
 <label>Primary payer claim/control number <input v-model="control" maxlength="100" required /></label><label>ERA/EOB reference <input v-model="reference" maxlength="2000" required /></label><label>Payment / adjudication date <input v-model="paymentDate" type="date" required /></label>
 <article v-for="(line,i) in lines" :key="i"><h4>Line {{ i+1 }} · {{ line.procedure_code }} · {{ line.units }} unit(s) · billed ${{ (line.charge_cents/100).toFixed(2) }}</h4><label>Primary paid ($) <input v-model="line.paid" type="number" min="0" step="0.01" required /></label>
 <div v-for="(adj,j) in line.adjustments" :key="j"><label>Adjustment (e.g. CO45, PR1) <input v-model="adj.code" maxlength="6" required /></label><label>Amount ($) <input v-model="adj.amount" type="number" min="0" step="0.01" required /></label><button type="button" @click="line.adjustments.splice(j,1)">Remove</button></div><button type="button" :disabled="line.adjustments.length>=8" @click="line.adjustments.push({code:'',amount:''})">Add adjustment</button></article>
 <label><input v-model="crossover" type="checkbox" /> I checked the primary ERA/EOB and payer status: this claim has not already been forwarded to or submitted to the secondary payer.</label>
 <label><input v-model="attested" type="checkbox" /> I verified primary adjudication, payer order and any payer waiting period. These entries match the ERA/EOB.</label>
 <button :disabled="busy || !crossover || !attested">Save secondary draft for review</button></form>
 </section></template>
<script setup>
import {ref,watch,onBeforeUnmount} from 'vue';import api from '../../services/api.js';
const props=defineProps({agencyId:[Number,String],claimId:[Number,String]});const emit=defineEmits(['created']);
const lines=ref([]),control=ref(''),reference=ref(''),paymentDate=ref(''),crossover=ref(false),attested=ref(false),busy=ref(false),error=ref(''),notice=ref('');let generation=0;
function reset(){generation++;lines.value=[];control.value='';reference.value='';paymentDate.value='';crossover.value=false;attested.value=false;busy.value=false;error.value='';notice.value='';}
async function load(){const g=++generation;busy.value=true;error.value='';lines.value=[];try{const {data}=await api.get(`/medical-billing/claimmd/claims/${props.claimId}/draft`,{params:{agencyId:props.agencyId}});if(g!==generation)return;if(data.claim.parent_claim_id)throw new Error(`This is already secondary. Use primary claim #${data.claim.parent_claim_id} to review its adjudication.`);lines.value=data.lines.map(l=>({...l,paid:'0.00',adjustments:[]}));}catch(e){if(g===generation)error.value=e.response?.data?.error?.message||e.message;}finally{if(g===generation)busy.value=false;}}
function cents(value){if(!/^\d+(\.\d{1,2})?$/.test(String(value)))throw new Error('Enter dollar amounts with no more than two decimal places');return Math.round(Number(value)*100);}
async function save(){const g=generation;busy.value=true;error.value='';try{const adjudication={primaryClaimControlNumber:control.value,reference:reference.value,paymentDate:paymentDate.value,crossoverConfirmedAbsent:crossover.value,attested:attested.value,lines:lines.value.map(l=>({paidCents:cents(l.paid),adjustments:l.adjustments.map(a=>({code:a.code.trim().toUpperCase(),amountCents:cents(a.amount)}))}))};const {data}=await api.post(`/medical-billing/claims/${props.claimId}/secondary`,{agencyId:props.agencyId,adjudication});if(g===generation){notice.value=`Secondary claim #${data.claimId} saved. Review and approve it separately before transmission.`;lines.value=[];emit('created',data.claimId);}}catch(e){if(g===generation)error.value=e.response?.data?.error?.message||e.message;}finally{if(g===generation)busy.value=false;}}
watch([lines,control,reference,paymentDate],()=>{attested.value=false;},{deep:true});watch(()=>[props.agencyId,props.claimId],reset);onBeforeUnmount(()=>{generation++;});
</script>
<style scoped>.secondary-claim{padding:14px;border:1px solid #cbd5e1;margin:15px 0;border-radius:8px}label{display:block;margin:10px 0}article{padding:10px;border-bottom:1px solid #cbd5e1}button{margin:5px;padding:8px}[role=alert]{color:#b91c1c}</style>
