// Generated from backend/src/constants/providerClinicalTaxonomy.js.
// Canonical provider profile choices. Age-only labels belong exclusively to Client Ages.
export const SPECIALTIES = Object.freeze([
  "ADHD",
  "Anger Management",
  "Anxiety",
  "Autism Spectrum / Autism Support",
  "Behavioral Concerns",
  "Bipolar Disorder",
  "Body Image",
  "Bullying",
  "Caregiver Stress",
  "Chronic Illness",
  "Chronic Pain",
  "Communication Difficulties",
  "Conduct / Oppositional Behaviors",
  "Depression",
  "Developmental Disabilities",
  "Divorce / Separation",
  "Domestic Violence / Relationship Violence",
  "Eating Concerns / Disordered Eating",
  "Emotional Regulation",
  "Family Conflict",
  "Gender Identity",
  "Grief & Loss",
  "Identity Development",
  "Impulse Control",
  "Infertility / Pregnancy Loss",
  "Intellectual & Developmental Disabilities",
  "Learning Difficulties",
  "Life Transitions",
  "Men’s Mental Health",
  "Neurodivergence",
  "Obsessive-Compulsive Disorder (OCD)",
  "Parenting",
  "Peer Relationships",
  "Perinatal / Postpartum Mental Health",
  "Personality Disorders",
  "Phobias / Fears",
  "Relationship Concerns",
  "School Avoidance",
  "School / Academic Concerns",
  "Self-Esteem",
  "Self-Harm",
  "Sexual Abuse / Sexual Trauma",
  "Sleep Concerns",
  "Social Skills",
  "Sports Performance / Athlete Mental Health",
  "Stress",
  "Substance Use",
  "Suicidal Ideation",
  "Trauma / PTSD",
  "Women’s Mental Health",
  "Workplace / Career Stress",
  "Adjustment to School",
  "Academic Stress",
  "Attendance / School Refusal",
  "Emotional & Behavioral Difficulties",
  "Executive Functioning",
  "Friendship / Peer Difficulties",
  "Parent-Child Relationships",
  "Play-Based Concerns",
  "Social-Emotional Skill Development",
  "Transition to Adulthood"
]);
export const POPULATIONS = Object.freeze([
  "Individuals",
  "Couples",
  "Families",
  "Groups",
  "Parents / Caregivers",
  "College Students",
  "Students",
  "Educators / School Staff",
  "Healthcare Professionals",
  "First Responders",
  "Military Members",
  "Veterans",
  "Athletes",
  "Student Athletes",
  "Men",
  "Women",
  "LGBTQ+ Clients",
  "Transgender / Gender-Diverse Clients",
  "Neurodivergent Clients",
  "Individuals with Developmental Disabilities",
  "Individuals with Intellectual Disabilities",
  "Individuals with Chronic Illness",
  "Individuals with Disabilities",
  "Survivors of Trauma",
  "Survivors of Abuse",
  "Adoptive Families",
  "Foster Families",
  "Blended Families",
  "Single-Parent Families",
  "New Parents",
  "Immigrant / Refugee Communities",
  "Multicultural / Racially Diverse Communities"
]);
export const CLIENT_AGES = Object.freeze([
  "Toddler (0-5)",
  "Children (6-10)",
  "Preteen (11-13)",
  "Teen (14-18)",
  "Young Adults (18-25)",
  "Adults (18+)",
  "Seniors (65+)"
]);
export const THERAPY_APPROACHES = Object.freeze([
  "Acceptance and Commitment (ACT)",
  "Adlerian",
  "AEDP",
  "Applied Behavioral Analysis (ABA)",
  "Art Therapy",
  "Attachment-Based",
  "Biofeedback",
  "Brainspotting",
  "Christian Counseling",
  "Clinical Supervision",
  "Coaching",
  "Cognitive Behavioral Therapy (CBT)",
  "CPT",
  "Compassion Focused",
  "Culturally Sensitive",
  "Dance Movement Therapy",
  "Dialectical Behavior Therapy (DBT)",
  "Eclectic",
  "EMDR",
  "Emotionally Focused",
  "Energy Psychology",
  "Existential",
  "Experiential Therapy",
  "Exposure Response Prevention (ERP)",
  "Family/Marital",
  "Family Systems",
  "Feminist",
  "Forensic Psychology",
  "Gestalt",
  "Gottman Method",
  "Humanistic",
  "Hypnotherapy",
  "Integrative",
  "IFS",
  "Interpersonal",
  "Intervention",
  "Jungian",
  "Mindfulness-Based (MBCT)",
  "Motivational Interviewing",
  "Multicultural",
  "Music Therapy",
  "Narrative",
  "Neuro-Linguistic (NLP)",
  "Neurofeedback",
  "Parent-Child Interaction (PCIT)",
  "Person-Centered",
  "Play Therapy",
  "Positive Psychology",
  "Prolonged Exposure Therapy",
  "Psychoanalytic",
  "Psychobiological Approach Couple Therapy",
  "Psychodynamic",
  "Psychological Testing and Evaluation",
  "REBT",
  "Reality Therapy",
  "Relational",
  "Sandplay",
  "Schema Therapy",
  "Solution Focused Brief (SFBT)",
  "Somatic",
  "Strength-Based",
  "Structural Family Therapy",
  "Transpersonal",
  "Trauma Focused",
  "Synergetic Play Therapy",
  "Trauma-informed care"
]);
