import { CONVERSA_ICON_URL } from './conversa';
import { PLOTLINE_WEBSITE_URL } from '../utils/plotline';

export const ptcoProducts=[
 {id:'plottwisthq',name:'Plot Twist HQ',audience:'The broader management suite',logo:'/assets/ptco/logo-flat.webp',description:'Connect client care with the work of running your organization.',features:['Clinical workflows, scheduling and billing','People operations, onboarding and payroll workflows','Programs, public websites and business operations'],context:'For organizations that need their business and service workflows together.'},
 {id:'plotline',name:'Plotline',audience:'People operations, from first application to what’s next',logo:'/assets/plotline/website/brand/logos/plotline-primary-transparent.webp',description:'Bring company-branded careers, hiring, onboarding, training, and people growth into one thoughtful workspace.',features:['Careers pages, applications and interview workflows','Onboarding, employee documents and learning','Employee evaluations and multi-organization hiring'],context:'The people operations product within Workforce Operations. Available on its own or alongside eligible PlotTwistCo products, with monthly plans and bundle savings.',url:PLOTLINE_WEBSITE_URL,demo:PLOTLINE_WEBSITE_URL+'/product',demoLabel:'See actual product screens'},
 {id:'auricwell',name:'AuricWell',audience:'The focused EHR',logo:'/auricwell/mark.svg',description:'A clean clinical workspace for therapy practices, built on the shared clinical services.',features:['Practice Notes, AI drafting and supervision','Clients, guardians, scheduling and billing','New-practice setup or a reviewed EHR transition'],context:'Focused on EHR work. Practice launch remains subject to workflow and integration readiness.',url:'https://plottwisthq.com/auricwell',demo:'https://plottwisthq.com/auricwell/demo',demoLabel:'Try the actual EHR workspace'},
 {id:'conversa',name:'Conversa',audience:'Communications across the platform',logo:CONVERSA_ICON_URL,description:'Every conversation, clearly connected. Messages by Conversa is the shared communication interface throughout the app, including AuricWell and Plot Twist HQ.',features:['Email, internal messages, chat, threads and channels','Secure messages, tickets, calls, voicemail and SMS','Team texts, polls, sender identities and delivery history'],context:'Secure client and guardian conversations have a distinct experience, shared authorized access, activity logging and medical-record tracking. Email and text notifications never contain the secure message.',route:'/p/ptco/conversa',actionLabel:'Explore Conversa'},
 {id:'schoolcarebridge',name:'SchoolCareBridge',audience:'School and agency coordination',logo:'/assets/schoolcarebridge/logo.png',description:'Bring schools and care teams together around enrollment, providers and student support.',features:['Working school portals and provider profiles','School schedules, student rosters and enrollment','Care-team messages and agency school overviews'],context:'A Plot Twist Co. product. MH4Kidz operates the program; affiliated agencies provide care.',url:'https://mh4kidz.org/schoolcarebridge',demo:'https://mh4kidz.org/schoolcarebridge/demo',demoLabel:'Try the actual school portal'},
 {id:'fundthred',name:'FundThred',audience:'Finance operations for mission-driven organizations',logo:'/assets/fundthred/wordmark.svg',description:'Follow the thread of every dollar. Connect funding, budgets, approvals, spending, and proof.',features:['Grants, program budgets and funding allocations','Expense requests, approvals and recorded payments','Supporting documents and operational reports'],context:'A dedicated nonprofit finance workspace, connected to PlotTwistHQ. Start with FundThred and discuss bundles for people operations, communications, and more.',url:'https://plottwisthq.com/fundthred',demo:'https://plottwisthq.com/fundthred/product',demoLabel:'Explore FundThred'},
 {id:'sstc',name:'Summit Stats Team Challenge',audience:'Fitness clubs & community groups',logo:'/assets/sstc/logo.png',description:'Bring your group together around fitness, shared progress, and friendly team competition.',features:['Clubs, seasons, teams, and workout logging','Configurable scoring, leaderboards, and weekly challenges','Club communication, activity review, and recognition'],context:'A web application for tracking fitness groups and competitions. New clubs can use the existing three-month free trial; no credit card required.',url:'https://summitstatstc.com',demo:'https://summitstatstc.com/tour',demoLabel:'Explore the illustrated product walkthrough'}
];
