/** Built-in TISI page designs. Published contentPages can override copy and image fields. */
const asset = name => `/assets/tisi/${name}.webp`;
const card = (title, body, iconKey = 'mind') => ({ title, body, iconKey });
const men = [card('Anxiety & Stress', 'Work through worry, pressure, and overwhelm.'), card('Depression & Motivation', 'Find support when energy, connection, or hope feel out of reach.', 'chart'), card('Relationships & Communication', 'Build healthier connections at home and in your community.', 'pair'), card('Life Transitions', 'Navigate changes in work, family, and everyday life.', 'peak'), card('Identity & Purpose', 'Explore what matters to you and the life you want to build.', 'person'), card('Trauma & Recovery', 'A supportive space to work through difficult experiences.', 'shield')];
const boys = [card('Anxiety & Worry', 'Support for anxious thoughts, overthinking, and big what-ifs.'), card('Mood & Emotional Support', 'Work through frustration, mood changes, and emotional ups and downs.', 'heart'), card('Confidence & Self-Esteem', 'Build self-belief and a more balanced view of yourself.', 'dumbbell'), card('School Stress & Focus', 'Develop tools for academic pressure and everyday routines.', 'grad'), card('Social Skills & Friendships', 'Practice communication and navigate social challenges.', 'pair'), card('Behavior & Coping Skills', 'Learn ways to manage emotions and respond to challenges.', 'brain'), card('Family & Parent Support', 'Collaborate on positive change at home.', 'person'), card('Life Changes & Adjustment', 'Support through family changes, new schools, and growing up.', 'peak')];
const athletes = [card('Performance Anxiety', 'Manage pre-game nerves, competition anxiety, and performance pressure.'), card('Confidence & Mindset', 'Build self-belief and a more supportive inner voice.', 'brain'), card('Stress & Burnout', 'Find room for rest, recovery, and balance.', 'plant'), card('Injury Recovery Support', 'Navigate the emotional challenges of injury and returning to sport.', 'shield'), card('Identity Beyond Sport', 'Explore who you are beyond athletic performance.', 'person'), card('Team & Relationship Challenges', 'Work on communication with teammates, coaches, and family.', 'pair'), card('Focus & Motivation', 'Set meaningful goals and strengthen concentration.', 'chart'), card('Life Balance', 'Make space for school, training, relationships, and personal growth.', 'heart')];
const sharedFaq = [
  ['How do I get started?', 'Complete the online intake using Get Started. Share what you are looking for, and the team can follow up about fit and next steps.'],
  ['Can I ask about the right service for me?', 'Yes. Use the intake to describe your needs and questions. The team will discuss available services before care begins.']
];
export const tisiAudiencePages = {
  men: { audience: 'Men', eyebrow: 'Men’s mental health services', title: 'Real support for real life.', subtitle: 'Support for men navigating pressure, relationships, identity, and change. Make space for a healthier, more fulfilling future.', heroImageUrl: asset('men-hero'), portraitImageUrl: asset('men-support'), bannerImageUrl: asset('mountain-banner'), sectionTitle: 'Support for what matters most.', sectionBody: 'Life can be demanding. Find a space to talk openly, work through challenges, and build practical tools for everyday life.', cards: men, pillars: ['Built for real life', 'A supportive space', 'Practical tools', 'A stronger you'], bannerTitle: 'You don’t have to do this alone.', faq: sharedFaq },
  boys: { audience: 'Boys', eyebrow: 'Boys’ mental health services', title: 'Stronger kids. Brighter tomorrows.', subtitle: 'A space for boys to be themselves, build confidence, and develop tools for the challenges of growing up.', heroImageUrl: asset('boys-hero'), portraitImageUrl: asset('boys-portrait'), bannerImageUrl: asset('boys-banner'), sectionTitle: 'Mental health that meets them where they are.', sectionBody: 'School, friendships, family, and change can bring big feelings. Support is tailored to each child’s needs and stage of development.', cards: boys, pillars: ['Build confidence', 'Healthy relationships', 'Manage big emotions', 'Discover potential'], bannerTitle: 'Real support. Real growth.', faq: [...sharedFaq, ['How are parents involved?', 'Parent involvement depends on the child’s needs, consent, and applicable privacy requirements. Your care team will discuss how you can support your child.']] },
  athletes: { audience: 'Athletes', eyebrow: 'Mental health support for athletes', title: 'Stronger minds. Better performance.', subtitle: 'Mental health support for athletes on and off the field, court, track, pool, or gym. Build skills for sport and life beyond it.', heroImageUrl: asset('athletes-hero'), portraitImageUrl: asset('athlete-portrait'), bannerImageUrl: asset('athlete-banner'), sectionTitle: 'More than a better game.', sectionBody: 'Athletic life brings unique pressures. Explore support for confidence, relationships, recovery, and a balanced identity beyond performance.', cards: athletes, pillars: ['Build confidence', 'Handle pressure', 'Recover from setbacks', 'Perform with purpose'], bannerTitle: 'Mental strength matters on and off the field.', faq: [...sharedFaq, ['Is support only for performance concerns?', 'You can seek support for emotional well-being, relationships, life changes, or challenges outside sport as well as performance concerns.']] }
};
for (const [slug, source] of Object.entries({ 'mens-services': 'men', 'boys-services': 'boys', 'athlete-services': 'athletes' })) {
  tisiAudiencePages[slug] = { ...tisiAudiencePages[source], title: `Explore ${source === 'men' ? 'men’s' : source === 'boys' ? 'boys’' : 'athlete'} services.`, heroImageUrl: asset(source === 'athletes' ? 'athlete-services' : source === 'boys' ? 'boys-portrait' : 'men-hero') };
}
export const tisiSports = ['Soccer', 'Basketball', 'Volleyball', 'Track & Field', 'Football', 'Swimming', 'And more'].map((label, i) => ({ label, image: asset(['soccer', 'basketball', 'volleyball', 'track-field', 'football', 'swimming', 'climbing'][i]) }));
export const isTisiAudiencePage = slug => Object.hasOwn(tisiAudiencePages, slug);
