-- Migration 1091: Canonical billing report ingest (clients, encounters, revenue/AR source)

CREATE TABLE IF NOT EXISTS billing_report_uploads (
  id INT NOT NULL AUTO_INCREMENT,
  agency_id INT NOT NULL,
  uploaded_by_user_id INT NULL,
  original_filename VARCHAR(255) NULL,
  storage_path VARCHAR(700) NULL,
  status ENUM('queued','processing','completed','failed') NOT NULL DEFAULT 'queued',
  report_label VARCHAR(255) NULL,
  rows_parsed INT NOT NULL DEFAULT 0,
  lines_inserted INT NOT NULL DEFAULT 0,
  lines_updated INT NOT NULL DEFAULT 0,
  clients_created INT NOT NULL DEFAULT 0,
  clients_matched INT NOT NULL DEFAULT 0,
  encounters_created INT NOT NULL DEFAULT 0,
  unmatched_providers_json JSON NULL,
  error_message TEXT NULL,
  result_summary_json JSON NULL,
  min_service_date DATE NULL,
  max_service_date DATE NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMP NULL,
  PRIMARY KEY (id),
  KEY idx_bru_agency_created (agency_id, created_at),
  KEY idx_bru_status (status),
  CONSTRAINT fk_bru_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
  CONSTRAINT fk_bru_uploaded_by FOREIGN KEY (uploaded_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS billing_report_lines (
  id BIGINT NOT NULL AUTO_INCREMENT,
  agency_id INT NOT NULL,
  upload_id INT NOT NULL,
  line_fingerprint CHAR(64) NOT NULL,
  service_date DATE NULL,
  service_code VARCHAR(32) NULL,
  place_of_service CHAR(8) NULL,
  row_type VARCHAR(128) NULL,
  diagnosis_text VARCHAR(500) NULL,
  primary_payer_name VARCHAR(255) NULL,
  secondary_payer_name VARCHAR(255) NULL,
  insurance_status VARCHAR(128) NULL,
  clinician_name_normalized VARCHAR(255) NULL,
  provider_user_id INT NULL,

  patient_name_ciphertext_b64 TEXT NULL,
  patient_name_iv_b64 VARCHAR(64) NULL,
  patient_name_auth_tag_b64 VARCHAR(64) NULL,
  patient_name_key_id VARCHAR(64) NULL,
  patient_dob_ciphertext_b64 TEXT NULL,
  patient_dob_iv_b64 VARCHAR(64) NULL,
  patient_dob_auth_tag_b64 VARCHAR(64) NULL,
  patient_dob_key_id VARCHAR(64) NULL,
  member_id_ciphertext_b64 TEXT NULL,
  member_id_iv_b64 VARCHAR(64) NULL,
  member_id_auth_tag_b64 VARCHAR(64) NULL,
  member_id_key_id VARCHAR(64) NULL,

  patient_name_hash CHAR(64) NULL,
  patient_dob_hash CHAR(64) NULL,
  member_id_hash CHAR(64) NULL,

  charge_rate DECIMAL(12,2) NOT NULL DEFAULT 0,
  patient_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  patient_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  insurance_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  insurance_amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0,
  insurance_outstanding DECIMAL(12,2) NOT NULL DEFAULT 0,

  client_id INT NULL,
  billing_encounter_id BIGINT NULL,
  resolved_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  UNIQUE KEY uniq_brl_agency_fingerprint (agency_id, line_fingerprint),
  KEY idx_brl_upload (upload_id),
  KEY idx_brl_agency_service_date (agency_id, service_date),
  KEY idx_brl_client (client_id),
  KEY idx_brl_provider (provider_user_id),
  KEY idx_brl_name_dob (agency_id, patient_name_hash, patient_dob_hash),
  KEY idx_brl_member (agency_id, member_id_hash),
  CONSTRAINT fk_brl_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
  CONSTRAINT fk_brl_upload FOREIGN KEY (upload_id) REFERENCES billing_report_uploads(id) ON DELETE CASCADE,
  CONSTRAINT fk_brl_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE SET NULL,
  CONSTRAINT fk_brl_provider FOREIGN KEY (provider_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS billing_encounters (
  id BIGINT NOT NULL AUTO_INCREMENT,
  agency_id INT NOT NULL,
  client_id INT NOT NULL,
  provider_user_id INT NULL,
  billing_line_id BIGINT NOT NULL,
  service_date DATE NOT NULL,
  service_code VARCHAR(32) NULL,
  place_of_service CHAR(8) NULL,
  diagnosis_text VARCHAR(500) NULL,
  row_type VARCHAR(128) NULL,
  charge_rate DECIMAL(12,2) NOT NULL DEFAULT 0,
  patient_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  patient_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  insurance_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  insurance_amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0,
  insurance_outstanding DECIMAL(12,2) NOT NULL DEFAULT 0,
  documentation_text LONGTEXT NULL,
  source VARCHAR(32) NOT NULL DEFAULT 'billing_import',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_be_billing_line (billing_line_id),
  KEY idx_be_client_date (client_id, service_date),
  KEY idx_be_agency_date (agency_id, service_date),
  KEY idx_be_provider_date (provider_user_id, service_date),
  CONSTRAINT fk_be_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
  CONSTRAINT fk_be_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE,
  CONSTRAINT fk_be_provider FOREIGN KEY (provider_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_be_line FOREIGN KEY (billing_line_id) REFERENCES billing_report_lines(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS client_billing_identities (
  id BIGINT NOT NULL AUTO_INCREMENT,
  agency_id INT NOT NULL,
  client_id INT NOT NULL,
  patient_name_hash CHAR(64) NULL,
  patient_dob_hash CHAR(64) NULL,
  member_id_hash CHAR(64) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_cbi_agency_client (agency_id, client_id),
  KEY idx_cbi_name_dob (agency_id, patient_name_hash, patient_dob_hash),
  KEY idx_cbi_member (agency_id, member_id_hash),
  CONSTRAINT fk_cbi_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
  CONSTRAINT fk_cbi_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Independent insurance outstanding on receivables rows (projected from canonical billing)
ALTER TABLE agency_receivables_report_rows
  ADD COLUMN insurance_amount DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER patient_outstanding_amount,
  ADD COLUMN insurance_amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER insurance_amount,
  ADD COLUMN insurance_outstanding_amount DECIMAL(12,2) NOT NULL DEFAULT 0 AFTER insurance_amount_paid,
  ADD COLUMN billing_line_id BIGINT NULL AFTER insurance_outstanding_amount,
  ADD KEY idx_arr_rows_insurance_outstanding (agency_id, insurance_outstanding_amount),
  ADD KEY idx_arr_rows_billing_line (billing_line_id);
