-- Migration 1274: client renewals public hub + admin push
CREATE TABLE client_renewals (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  agency_id INT NOT NULL,
  client_id INT NOT NULL,
  organization_id INT NULL,
  school_name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  public_token VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  status ENUM('draft','sent','in_progress','completed','opted_out','cancelled') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  option_verify_contact TINYINT(1) NOT NULL DEFAULT 0,
  option_smart_roi TINYINT(1) NOT NULL DEFAULT 0,
  option_smart_disclosure TINYINT(1) NOT NULL DEFAULT 0,
  option_full_packet TINYINT(1) NOT NULL DEFAULT 0,
  packet_mode ENUM('school','office') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  recommend_smart_roi TINYINT(1) NOT NULL DEFAULT 0,
  recommend_smart_disclosure TINYINT(1) NOT NULL DEFAULT 0,
  verify_contact_done TINYINT(1) NOT NULL DEFAULT 0,
  smart_roi_done TINYINT(1) NOT NULL DEFAULT 0,
  smart_disclosure_done TINYINT(1) NOT NULL DEFAULT 0,
  full_packet_done TINYINT(1) NOT NULL DEFAULT 0,
  roi_signing_public_key VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  disclosure_public_key VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  packet_public_key VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  created_by_user_id INT NULL,
  sent_at DATETIME NULL,
  completed_at DATETIME NULL,
  opted_out_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_client_renewal_token (public_token),
  KEY idx_client_renewal_client (client_id, agency_id),
  KEY idx_client_renewal_status (status, agency_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
