-- Additive program operations. Nothing here issues an invoice or enables collection.
CREATE TABLE IF NOT EXISTS schoolcarebridge_commercial_terms (
 id INT PRIMARY KEY,
 terms_json JSON NOT NULL,
 revision INT NOT NULL DEFAULT 1,
 signed_contract_document_id INT NULL,
 signed_baa_document_id INT NULL,
 executed_revision INT NULL,
 activated_by_user_id INT NULL,
 activated_at DATETIME NULL,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
INSERT IGNORE INTO schoolcarebridge_commercial_terms (id,terms_json) VALUES (1,JSON_OBJECT(
 'rolloutDate','2027-03-31','developmentEndDate','2028-03-30',
 'developmentBps',5000,'ongoingBps',2500,'schoolMonthlyCents',2500,
 'providerMonthlyCents',1000,'adminMonthlyCents',500,
 'bookingPlatformBps',1000,'bookingOperatorBps',2000,'paymentDueDays',30,
 'operatorLegalName','MH4Kidz','platformLegalName','Plot Twist Co',
 'operatorAddress','','platformAddress','','operatorNoticeEmail','','platformNoticeEmail','',
 'governingState','','operatorHipaaRole','business_associate',
 'upstreamCoveredEntities','','effectiveDate',''));
CREATE TABLE IF NOT EXISTS schoolcarebridge_programs (
 id INT AUTO_INCREMENT PRIMARY KEY,
 operator_agency_id INT NOT NULL,
 title VARCHAR(200) NOT NULL,
 program_type ENUM('original','partner','managed','sponsored') NOT NULL,
 owner_name VARCHAR(200) NOT NULL,
 audience ENUM('students','parents','staff','school_wide') NOT NULL,
 description TEXT NOT NULL,
 delivery_mode ENUM('in_person','virtual','both') NOT NULL DEFAULT 'both',
 regions_json JSON NOT NULL,
 presenter_name VARCHAR(200) NOT NULL,
 presenter_user_id INT NULL,
 presenter_bio TEXT NULL,
 travel_available TINYINT(1) NOT NULL DEFAULT 0,
 duration_minutes INT NOT NULL DEFAULT 60,
 capacity INT NOT NULL DEFAULT 30,
 funding_mode ENUM('cash','grant','free','mixed') NOT NULL DEFAULT 'cash',
 price_cents INT NULL,
 sponsor_name VARCHAR(200) NULL,
 finance_program_id INT NULL,
 registration_class_id INT NULL,
 registration_event_id INT NULL,
 published TINYINT(1) NOT NULL DEFAULT 0,
 revision INT NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(operator_agency_id,published)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS schoolcarebridge_bookings (
 id INT AUTO_INCREMENT PRIMARY KEY,
 program_id INT NOT NULL,
 operator_agency_id INT NOT NULL,
 requester_user_id INT NOT NULL,
 school_agency_id INT NOT NULL,
 request_key VARCHAR(80) NOT NULL,
 requested_start DATETIME NOT NULL,
 requested_end DATETIME NOT NULL,
 timezone VARCHAR(80) NOT NULL,
 region VARCHAR(120) NOT NULL,
 location VARCHAR(500) NOT NULL,
 attendance INT NOT NULL,
 language VARCHAR(120) NULL,
 accommodations TEXT NULL,
 travel_requested TINYINT(1) NOT NULL DEFAULT 0,
 funding_requested ENUM('cash','grant','partial','free') NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'requested',
 quote_json JSON NULL,
 quoted_by_user_id INT NULL,
 quoted_at DATETIME NULL,
 accepted_by_user_id INT NULL,
 accepted_at DATETIME NULL,
 presenter_user_id INT NULL,
 finance_expense_id INT NULL,
 presenter_expense_id INT NULL,
 platform_expense_id INT NULL,
 completion_json JSON NULL,
 revision INT NOT NULL DEFAULT 1,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 UNIQUE KEY(requester_user_id,request_key),INDEX(operator_agency_id,status),INDEX(presenter_user_id,requested_start)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS schoolcarebridge_invoices (
 id INT AUTO_INCREMENT PRIMARY KEY,
 operator_agency_id INT NOT NULL,
 kind ENUM('platform_usage','booking') NOT NULL,
 billing_key VARCHAR(120) NOT NULL,
 debtor_agency_id INT NOT NULL,
 booking_id INT NULL,
 terms_revision INT NOT NULL,
 lines_json JSON NOT NULL,
 total_cents BIGINT NOT NULL,
 currency CHAR(3) NOT NULL DEFAULT 'usd',
 status VARCHAR(24) NOT NULL DEFAULT 'open',
 issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 due_date DATE NOT NULL,
 stripe_account_id VARCHAR(100) NULL,
 stripe_payment_intent_id VARCHAR(100) NULL,
 receipt_number VARCHAR(80) NULL,
 paid_at DATETIME NULL,
 refunded_cents BIGINT NOT NULL DEFAULT 0,
 refund_attempt INT NOT NULL DEFAULT 0,
 stripe_refund_id VARCHAR(100) NULL,
 created_by_user_id INT NOT NULL,
 UNIQUE KEY(kind,billing_key),UNIQUE KEY(stripe_payment_intent_id),UNIQUE KEY(receipt_number),INDEX(debtor_agency_id,status)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS schoolcarebridge_usage_snapshots (
 usage_date DATE NOT NULL,partner_agency_id INT NOT NULL,
 school_count INT NOT NULL,provider_count INT NOT NULL,admin_count INT NOT NULL,
 evidence_json JSON NOT NULL,
 PRIMARY KEY(usage_date,partner_agency_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS schoolcarebridge_commerce_audit (
 id BIGINT AUTO_INCREMENT PRIMARY KEY,actor_user_id INT NULL,
 action VARCHAR(80) NOT NULL,object_type VARCHAR(40) NOT NULL,object_id INT NULL,
 detail_json JSON NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;
