ALTER TABLE office_booking_requests MODIFY COLUMN request_type ENUM(
  'PROVIDER_REQUEST','ADMIN_OVERRIDE','DELETE_EVENT','DROP_ASSIGNMENT','MOVE_ASSIGNMENT','MOVE_OCCURRENCE'
) NOT NULL DEFAULT 'PROVIDER_REQUEST';
