-- Additional scoped offers for Michael's existing managed consultant tenant.
-- Preserve prior package prices and all merchant/payment account settings.
SET @michael_agency_id := (SELECT id FROM agencies WHERE slug='michael' AND organization_type='consultant' LIMIT 1);
SET @michael_owner_id := (SELECT u.id FROM users u JOIN agencies a ON a.account_owner_user_id=u.id WHERE a.id=@michael_agency_id AND LOWER(u.first_name)='michael' AND LOWER(u.last_name)='mendez' LIMIT 1);

INSERT INTO practitioner_session_packages
 (agency_id,name,description,session_count,price_cents,payment_mode_default,pay_in_full_price_cents,allowed_payment_modes_json,missed_session_policy_json,is_active,sort_order,created_by_user_id)
 SELECT @michael_agency_id,'Running Reset Session','One 60-minute coaching session. Talk through your experience, goals, and schedule, then identify the next practical step in your running. Includes: Goals and current-routine review; One 60-minute virtual coaching session; A written two-week starter outline; Pacing, consistency, and recovery habits to focus on. One runner. No ongoing plan updates, medical assessment, injury rehabilitation, or in-person session is included. Parent/guardian coordinates for minors.',1,12500,'PAY_IN_FULL',12500,
 JSON_ARRAY('PAY_IN_FULL'),JSON_OBJECT('type','custom','freeRebooks',0,'feeCents',0,'note','Review the written engagement terms before purchase. Guardian participation and consent are confirmed before coaching a minor.'),1,6,@michael_owner_id
 WHERE @michael_agency_id IS NOT NULL AND @michael_owner_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM practitioner_session_packages WHERE agency_id=@michael_agency_id AND name='Running Reset Session');
INSERT INTO booking_packages
 (agency_id,business_type,name,description,package_type,session_count,price_cents,domain_config_json,allowed_tenant_service_ids_json,consume_on,is_active,is_public)
 SELECT @michael_agency_id,'consulting','Running Reset Session','One 60-minute coaching session. Talk through your experience, goals, and schedule, then identify the next practical step in your running. Includes: Goals and current-routine review; One 60-minute virtual coaching session; A written two-week starter outline; Pacing, consistency, and recovery habits to focus on. One runner. No ongoing plan updates, medical assessment, injury rehabilitation, or in-person session is included. Parent/guardian coordinates for minors.','prepaid_bundle',1,12500,
 JSON_OBJECT('website',JSON_OBJECT('key','running-reset','group','running','scope','One runner. No ongoing plan updates, medical assessment, injury rehabilitation, or in-person session is included. Parent/guardian coordinates for minors.')),JSON_ARRAY(),'complete',1,1
 WHERE @michael_agency_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM booking_packages WHERE agency_id=@michael_agency_id AND name='Running Reset Session');

INSERT INTO practitioner_session_packages
 (agency_id,name,description,session_count,price_cents,payment_mode_default,pay_in_full_price_cents,allowed_payment_modes_json,missed_session_policy_json,is_active,sort_order,created_by_user_id)
 SELECT @michael_agency_id,'Find Your Stride · 8 Weeks','8 weeks · 3 coaching calls. Build a running routine around your life, with a personal plan and regular accountability. Includes: 60-minute kickoff and an eight-week running plan; One written check-in and plan review each week; 30-minute midpoint and wrap-up calls; A next-phase plan for your routine or race goal. One runner and one agreed goal. Race readiness and session format are confirmed before enrollment. No unlimited messaging, automatic renewal, medical care, or guaranteed finish time.',3,45000,'PAY_IN_FULL',45000,
 JSON_ARRAY('PAY_IN_FULL'),JSON_OBJECT('type','custom','freeRebooks',0,'feeCents',0,'note','Review the written engagement terms before purchase. Guardian participation and consent are confirmed before coaching a minor.'),1,7,@michael_owner_id
 WHERE @michael_agency_id IS NOT NULL AND @michael_owner_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM practitioner_session_packages WHERE agency_id=@michael_agency_id AND name='Find Your Stride · 8 Weeks');
INSERT INTO booking_packages
 (agency_id,business_type,name,description,package_type,session_count,price_cents,domain_config_json,allowed_tenant_service_ids_json,consume_on,is_active,is_public)
 SELECT @michael_agency_id,'consulting','Find Your Stride · 8 Weeks','8 weeks · 3 coaching calls. Build a running routine around your life, with a personal plan and regular accountability. Includes: 60-minute kickoff and an eight-week running plan; One written check-in and plan review each week; 30-minute midpoint and wrap-up calls; A next-phase plan for your routine or race goal. One runner and one agreed goal. Race readiness and session format are confirmed before enrollment. No unlimited messaging, automatic renewal, medical care, or guaranteed finish time.','consulting_project',3,45000,
 JSON_OBJECT('website',JSON_OBJECT('key','running-plan','group','running','scope','One runner and one agreed goal. Race readiness and session format are confirmed before enrollment. No unlimited messaging, automatic renewal, medical care, or guaranteed finish time.')),JSON_ARRAY(),'complete',1,1
 WHERE @michael_agency_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM booking_packages WHERE agency_id=@michael_agency_id AND name='Find Your Stride · 8 Weeks');

INSERT INTO practitioner_session_packages
 (agency_id,name,description,session_count,price_cents,payment_mode_default,pay_in_full_price_cents,allowed_payment_modes_json,missed_session_policy_json,is_active,sort_order,created_by_user_id)
 SELECT @michael_agency_id,'Student-Athlete Direction Session','One 60-minute family session. Make room for the student’s goals and turn a big college question into a few useful next steps. Includes: Brief goals and priorities questionnaire; One 60-minute student/family conversation; An academic, athletic, and personal fit worksheet; Written next steps and questions to research. One student, with a parent/guardian coordinating if under 18. Does not include a researched school list, application editing, or financial-aid advice.',1,17500,'PAY_IN_FULL',17500,
 JSON_ARRAY('PAY_IN_FULL'),JSON_OBJECT('type','custom','freeRebooks',0,'feeCents',0,'note','Review the written engagement terms before purchase. Guardian participation and consent are confirmed before coaching a minor.'),1,8,@michael_owner_id
 WHERE @michael_agency_id IS NOT NULL AND @michael_owner_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM practitioner_session_packages WHERE agency_id=@michael_agency_id AND name='Student-Athlete Direction Session');
INSERT INTO booking_packages
 (agency_id,business_type,name,description,package_type,session_count,price_cents,domain_config_json,allowed_tenant_service_ids_json,consume_on,is_active,is_public)
 SELECT @michael_agency_id,'consulting','Student-Athlete Direction Session','One 60-minute family session. Make room for the student’s goals and turn a big college question into a few useful next steps. Includes: Brief goals and priorities questionnaire; One 60-minute student/family conversation; An academic, athletic, and personal fit worksheet; Written next steps and questions to research. One student, with a parent/guardian coordinating if under 18. Does not include a researched school list, application editing, or financial-aid advice.','prepaid_bundle',1,17500,
 JSON_OBJECT('website',JSON_OBJECT('key','college-session','group','college','scope','One student, with a parent/guardian coordinating if under 18. Does not include a researched school list, application editing, or financial-aid advice.')),JSON_ARRAY(),'complete',1,1
 WHERE @michael_agency_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM booking_packages WHERE agency_id=@michael_agency_id AND name='Student-Athlete Direction Session');

INSERT INTO practitioner_session_packages
 (agency_id,name,description,session_count,price_cents,payment_mode_default,pay_in_full_price_cents,allowed_payment_modes_json,missed_session_policy_json,is_active,sort_order,created_by_user_id)
 SELECT @michael_agency_id,'Student-Athlete College Fit Roadmap','6 weeks · 4 working sessions. Compare schools and team environments, prepare to communicate with coaches, and make a thoughtful college decision. Includes: Academic, athletic, personal, and budget priorities; A research shortlist of up to 8 schools with reasons to explore; Athletic profile and coach-outreach preparation; School comparison, visit questions, and decision timeline. One student and one planning cycle. Research uses public information and family-provided priorities. Application editing, test prep, financial-aid advising, eligibility certification, and recruiting representation are not included. The student sends their own outreach. No admission, scholarship, or roster guarantees.',4,90000,'PAY_IN_FULL',90000,
 JSON_ARRAY('PAY_IN_FULL'),JSON_OBJECT('type','custom','freeRebooks',0,'feeCents',0,'note','Review the written engagement terms before purchase. Guardian participation and consent are confirmed before coaching a minor.'),1,9,@michael_owner_id
 WHERE @michael_agency_id IS NOT NULL AND @michael_owner_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM practitioner_session_packages WHERE agency_id=@michael_agency_id AND name='Student-Athlete College Fit Roadmap');
INSERT INTO booking_packages
 (agency_id,business_type,name,description,package_type,session_count,price_cents,domain_config_json,allowed_tenant_service_ids_json,consume_on,is_active,is_public)
 SELECT @michael_agency_id,'consulting','Student-Athlete College Fit Roadmap','6 weeks · 4 working sessions. Compare schools and team environments, prepare to communicate with coaches, and make a thoughtful college decision. Includes: Academic, athletic, personal, and budget priorities; A research shortlist of up to 8 schools with reasons to explore; Athletic profile and coach-outreach preparation; School comparison, visit questions, and decision timeline. One student and one planning cycle. Research uses public information and family-provided priorities. Application editing, test prep, financial-aid advising, eligibility certification, and recruiting representation are not included. The student sends their own outreach. No admission, scholarship, or roster guarantees.','consulting_project',4,90000,
 JSON_OBJECT('website',JSON_OBJECT('key','college-roadmap','group','college','scope','One student and one planning cycle. Research uses public information and family-provided priorities. Application editing, test prep, financial-aid advising, eligibility certification, and recruiting representation are not included. The student sends their own outreach. No admission, scholarship, or roster guarantees.')),JSON_ARRAY(),'complete',1,1
 WHERE @michael_agency_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM booking_packages WHERE agency_id=@michael_agency_id AND name='Student-Athlete College Fit Roadmap');

INSERT INTO practitioner_session_packages
 (agency_id,name,description,session_count,price_cents,payment_mode_default,pay_in_full_price_cents,allowed_payment_modes_json,missed_session_policy_json,is_active,sort_order,created_by_user_id)
 SELECT @michael_agency_id,'Recruiting Strategy Sprint','4 weeks · 3 working sessions. Turn your program’s needs into a focused prospecting, evaluation, and outreach strategy. Includes: Program goals, roster needs, and recruiting-process review; Ideal-prospect criteria and a talent-source research map; Evaluation rubric, outreach sequence, and follow-up workflow; 90-day recruiting action plan with owners and measures. One collegiate program and one recruiting cycle. No purchased prospect list, guaranteed signings, athlete representation, or outreach on your behalf. Staff and compliance approval are required before implementation; custom tools and ongoing research are separate.',3,150000,'PAY_IN_FULL',150000,
 JSON_ARRAY('PAY_IN_FULL'),JSON_OBJECT('type','custom','freeRebooks',0,'feeCents',0,'note','Review the written engagement terms before purchase. Guardian participation and consent are confirmed before coaching a minor.'),1,10,@michael_owner_id
 WHERE @michael_agency_id IS NOT NULL AND @michael_owner_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM practitioner_session_packages WHERE agency_id=@michael_agency_id AND name='Recruiting Strategy Sprint');
INSERT INTO booking_packages
 (agency_id,business_type,name,description,package_type,session_count,price_cents,domain_config_json,allowed_tenant_service_ids_json,consume_on,is_active,is_public)
 SELECT @michael_agency_id,'consulting','Recruiting Strategy Sprint','4 weeks · 3 working sessions. Turn your program’s needs into a focused prospecting, evaluation, and outreach strategy. Includes: Program goals, roster needs, and recruiting-process review; Ideal-prospect criteria and a talent-source research map; Evaluation rubric, outreach sequence, and follow-up workflow; 90-day recruiting action plan with owners and measures. One collegiate program and one recruiting cycle. No purchased prospect list, guaranteed signings, athlete representation, or outreach on your behalf. Staff and compliance approval are required before implementation; custom tools and ongoing research are separate.','consulting_project',3,150000,
 JSON_OBJECT('website',JSON_OBJECT('key','recruiting-strategy','group','recruiting','scope','One collegiate program and one recruiting cycle. No purchased prospect list, guaranteed signings, athlete representation, or outreach on your behalf. Staff and compliance approval are required before implementation; custom tools and ongoing research are separate.')),JSON_ARRAY(),'complete',1,1
 WHERE @michael_agency_id IS NOT NULL
 AND NOT EXISTS (SELECT 1 FROM booking_packages WHERE agency_id=@michael_agency_id AND name='Recruiting Strategy Sprint');
UPDATE public_website_support_sites SET industries_json=JSON_ARRAY('Consulting · Private practice launch & scaling','AI & app development','Business & nonprofit growth','Running coaching','Student-athlete college guidance','Collegiate recruiting strategy') WHERE slug='michael' AND support_agency_id=@michael_agency_id;
