-- Migration: Company Card Expense submissions (tracking; not reimbursements)

CREATE TABLE IF NOT EXISTS payroll_company_card_expenses (
  id INT NOT NULL AUTO_INCREMENT,
  agency_id INT NOT NULL,
  user_id INT NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'submitted',
  expense_date DATE NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  vendor VARCHAR(255) NULL,
  purpose VARCHAR(255) NULL,
  notes TEXT NOT NULL,
  receipt_file_path VARCHAR(255) NULL,
  receipt_original_name VARCHAR(255) NULL,
  receipt_mime_type VARCHAR(128) NULL,
  receipt_size_bytes INT NULL,
  attestation TINYINT(1) NOT NULL DEFAULT 0,
  suggested_payroll_period_id INT NULL,
  target_payroll_period_id INT NULL,
  applied_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
  approved_by_user_id INT NULL,
  approved_at TIMESTAMP NULL,
  rejected_by_user_id INT NULL,
  rejected_at TIMESTAMP NULL,
  rejection_reason VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  CONSTRAINT fk_company_card_expenses_agency_id FOREIGN KEY (agency_id) REFERENCES agencies (id) ON DELETE CASCADE,
  CONSTRAINT fk_company_card_expenses_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
  CONSTRAINT fk_company_card_expenses_suggested_period_id FOREIGN KEY (suggested_payroll_period_id) REFERENCES payroll_periods (id) ON DELETE SET NULL,
  CONSTRAINT fk_company_card_expenses_target_period_id FOREIGN KEY (target_payroll_period_id) REFERENCES payroll_periods (id) ON DELETE SET NULL,
  CONSTRAINT fk_company_card_expenses_approved_by_user_id FOREIGN KEY (approved_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
  CONSTRAINT fk_company_card_expenses_rejected_by_user_id FOREIGN KEY (rejected_by_user_id) REFERENCES users (id) ON DELETE SET NULL,
  INDEX idx_company_card_expenses_agency_user (agency_id, user_id),
  INDEX idx_company_card_expenses_status (status),
  INDEX idx_company_card_expenses_suggested_period (suggested_payroll_period_id),
  INDEX idx_company_card_expenses_target_period (target_payroll_period_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

