CREATE TABLE IF NOT EXISTS provider_schedule_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  agency_id BIGINT UNSIGNED NOT NULL,
  provider_id BIGINT UNSIGNED NOT NULL,
  kind VARCHAR(32) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description TEXT NULL,
  reason_code VARCHAR(64) NULL,
  is_private TINYINT(1) NOT NULL DEFAULT 0,
  all_day TINYINT(1) NOT NULL DEFAULT 0,
  start_at DATETIME NULL,
  end_at DATETIME NULL,
  start_date DATE NULL,
  end_date DATE NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  google_event_id VARCHAR(255) NULL,
  google_html_link TEXT NULL,
  created_by_user_id BIGINT UNSIGNED NULL,
  updated_by_user_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_pse_provider_window (provider_id, agency_id, start_at, end_at),
  KEY idx_pse_provider_all_day (provider_id, agency_id, start_date, end_date),
  KEY idx_pse_status (status),
  CONSTRAINT fk_pse_agency FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE CASCADE,
  CONSTRAINT fk_pse_provider FOREIGN KEY (provider_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_pse_created_by FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_pse_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
