-- Migration 850: Restore all standing assignments and create booking plans for
-- every provider whose slots were forfeited because the EHR auto-book feature
-- never ran.
--
-- ROOT CAUSE:
--   When the platform launched (Feb 2026), providers were assigned to rooms but
--   the EHR (Therapy Notes) auto-book flow — which was supposed to confirm those
--   assignments into real booking plans — never fired.  After 42+ days in
--   ASSIGNED_AVAILABLE limbo, the auto-forfeit watchdog swept them all out.
--   This left 375 assignments across 32 providers / 14 rooms with no booking plan
--   and is_active = FALSE.
--
-- WHAT THIS DOES:
--   Step A — Re-activate every standing assignment that was forfeited on or before
--             May 31 2026 AND never had any booking plan created.
--   Step B — Create a confirmed booking plan (1-year window, booking_origin='user')
--             for each re-activated assignment that still has no plan.
--   Step C — Update any existing future ASSIGNED_AVAILABLE events for those
--             assignments to ASSIGNED_BOOKED, skipping slots already occupied by
--             another booked provider (conflict guard).
--             NOTE: Most future events don't exist yet and will be generated by
--             the materializer on the next schedule page load.
--
-- CONFLICT HANDLING:
--   Step C has a LEFT JOIN anti-join guard: if another provider already has an
--   ASSIGNED_BOOKED event in the same room at the same time, that slot is skipped.
--   Any remaining slot conflicts can be resolved via /admin/booking-conflict-resolver.

-- ── Step A: Re-activate all forfeited assignments that never had a booking plan ─
UPDATE office_standing_assignments osa
SET
  osa.is_active                  = TRUE,
  osa.last_two_week_confirmed_at = NOW(),
  osa.last_forfeit_warning_at    = NULL,
  osa.updated_at                 = CURRENT_TIMESTAMP
WHERE osa.is_active   = FALSE
  AND osa.updated_at <= '2026-05-31 23:59:59'
  AND NOT EXISTS (
    SELECT 1 FROM office_booking_plans bp
    WHERE bp.standing_assignment_id = osa.id
  );

-- ── Step B: Create booking plans for every re-activated assignment ─────────────
INSERT INTO office_booking_plans (
  standing_assignment_id,
  booked_frequency,
  booking_start_date,
  active_until_date,
  booked_occurrence_count,
  last_confirmed_at,
  is_active,
  created_by_user_id,
  booking_origin,
  user_booking_confirmed_at,
  created_at,
  updated_at
)
SELECT
  osa.id,
  osa.assigned_frequency,
  CURDATE(),
  DATE_ADD(CURDATE(), INTERVAL 1 YEAR),
  NULL,
  NOW(),
  1,
  1,
  'user',
  NOW(),
  NOW(),
  NOW()
FROM office_standing_assignments osa
WHERE osa.is_active = TRUE
  AND NOT EXISTS (
    SELECT 1 FROM office_booking_plans bp
    WHERE bp.standing_assignment_id = osa.id
      AND bp.is_active = TRUE
  )
  AND EXISTS (
    SELECT 1 FROM office_standing_assignments osa2
    WHERE osa2.id = osa.id
      AND osa2.updated_at >= DATE_SUB(NOW(), INTERVAL 5 MINUTE)
  );

-- ── Step C: Update any existing future AVAILABLE events → BOOKED ──────────────
UPDATE office_events oe
JOIN office_standing_assignments osa
  ON  osa.id        = oe.standing_assignment_id
  AND osa.is_active = TRUE
JOIN office_booking_plans bp
  ON  bp.standing_assignment_id = osa.id
  AND bp.is_active              = TRUE
LEFT JOIN office_events conflict
  ON  conflict.room_id    = oe.room_id
  AND conflict.start_at   = oe.start_at
  AND conflict.id        <> oe.id
  AND conflict.slot_state = 'ASSIGNED_BOOKED'
  AND (conflict.status IS NULL OR UPPER(conflict.status) NOT IN ('CANCELLED', 'RELEASED'))
SET
  oe.slot_state         = 'ASSIGNED_BOOKED',
  oe.status             = 'BOOKED',
  oe.booked_provider_id = osa.provider_id,
  oe.booking_plan_id    = bp.id,
  oe.updated_at         = CURRENT_TIMESTAMP
WHERE oe.start_at    >= NOW()
  AND oe.slot_state   = 'ASSIGNED_AVAILABLE'
  AND (oe.status = 'RELEASED' OR oe.status IS NULL)
  AND oe.booking_plan_id IS NULL
  AND conflict.id IS NULL;
