// Snapshot this entire agreement inside the signed evidence; never reconstruct old signatures from current policy.
export function staffCommunicationAgreement(brandName) {
  return {
    version: '2026-10-08.1',
    title: 'Communications Use Agreement & Acknowledgment',
    communityStandardsUrl: '/community-standards',
    sections: [
      { title: 'Shared agency number and routing', body: `I understand that ${brandName}'s business phone numbers are shared agency resources, not my personal or exclusive numbers. The app and Conversa route client texts using client assignments and authorized care-team access. Text messages do not carry a telephone extension. When voice service is enabled, calls and voicemail are routed using the agency's assigned extensions and routing settings. More than one assigned provider may have access to a shared client conversation. Unmatched or ambiguous communications may be reviewed by authorized support staff.` },
      { title: 'Community Standards and automatic replies', body: 'I will communicate respectfully, protect confidential information, and use agency communications only for authorized work. Threats, harassment, discriminatory language, sexual content directed at others, and abusive or obscene language are not acceptable. Questions, complaints and disagreement are welcome. I will not send passwords, payment-card details or unnecessary sensitive information. Text conversations receive an automatic communication notice, subject to delivery and opt-out restrictions; out-of-office and support replies explain availability. An automated acknowledgment does not mean a staff member has read the message. Community Standards apply to texts, calls, voicemail, chat and email.' },
      { title: 'Agency access, storage and client records', body: 'I understand that authorized agency personnel may access and review business communications for client care, supervision, quality assurance, security and other permitted operations. Text messages and associated communication records concerning a client are stored with or linked to that client’s record. Business communications are not a private channel between me and the sender. Access remains limited to authorized personnel with a legitimate work purpose.' },
      { title: 'Calls, recordings and voicemail', body: 'Communications may be stored and, where lawfully enabled, recorded or transcribed for care coordination, quality assurance and other permitted purposes. Before recording a call, the system must provide appropriate notice and obtain any required participant consent; my signature does not replace that consent. When voicemail service is enabled, voicemail audio and an available transcript will appear together in Messages → Calls/Voicemails, linked to the appropriate client when identified. Transcription can be delayed, unavailable or inaccurate; I will listen to the audio when needed and will not treat a transcript as a verified clinical note. Signing this agreement does not activate voice, recording, transcription or personal-phone forwarding.' },
      { title: 'Retention', body: 'Routine call-log metadata is retained for up to three years under the agency retention schedule. Client-linked communications, voicemail, recordings incorporated into a client record, and records subject to a legal or preservation hold may be retained longer under the applicable record-retention requirements. This is not a promise that every record or recording will be deleted after three years. Signed copies of this agreement are retained separately from routine call-log cleanup.' },
      { title: 'Coverage, response and support escalation', body: 'I am responsible for monitoring my assigned inbox during my agreed availability, keeping availability current, and following agency response and coverage procedures. Unanswered or unread communications, absences, changes in assignment, or the end of employment may trigger routing or escalation to authorized support staff under the agency’s configured coverage rules and applicable client choices. Support alerts should direct staff to the secure app; client content must not be forwarded to personal SMS unless the separately approved safeguards and permissions are in place. Escalation supports continuity of care and does not guarantee an immediate response or continuous monitoring.' },
      { title: 'Privacy, safety and personal-phone choices', body: 'Standard SMS is not end-to-end encrypted. I will use the secure app for sensitive information and follow the agency’s approved healthcare communication procedures. This service is not for crises or emergencies: call or text 988 for suicide or emotional distress, and call 911 for immediate danger or a medical emergency. Personal-phone notifications remain optional and may be declined or changed without giving up app access. This acknowledgment does not enroll clients, grant new access, waive statutory or privacy rights, or authorize recording without required notice and consent.' },
      { title: 'Electronic signature and my copy', body: 'By entering my name and selecting the acknowledgment, I electronically sign this Communications Use Agreement and the separate communication choices shown here. I understand the shared-number, agency-access, retention and coverage arrangements described above. I can view and download my signed copy in My Account → Documents → Communications agreements.' }
    ]
  };
}
