import {it,expect} from 'vitest';
import {formatEncounterDate,noteActionLabel,formatPlaceOfService} from '../clientEncounterUtils.js';
import {appointmentOfficeId,officesForAgency,defaultAppointmentServiceLocation} from '../appointmentOfficeSelection.js';
import {dayScheduleEntries} from '../providerDaySchedule.js';
it('preserves date-only October 1 and labels a planned note accurately',()=>{expect(formatEncounterDate('2026-10-01')).toBe(new Date(2026,9,1,12).toLocaleDateString());expect(formatEncounterDate('2026-10-01T00:00:00.000Z')).toBe(new Date(2026,9,1,12).toLocaleDateString());expect(noteActionLabel({note_status:'planned'})).toBe('Prepare note');expect(formatPlaceOfService('10')).toContain('Telehealth');});
it('uses the editor office rather than the toolbar scope and isolates agency options',()=>{expect(appointmentOfficeId(8,3)).toBe(8);expect(appointmentOfficeId(0,-1)).toBe(0);expect(officesForAgency([{id:1,agencyIds:[377]},{id:2,agency_id:4},{id:3}],377).map(x=>x.id)).toEqual([1]);});
it('never substitutes a different office or physical POS for telehealth',()=>{const rows=[{id:1,placeOfService:'11',billingOfficeLocationId:3},{id:2,placeOfService:'11',billingOfficeLocationId:8},{id:3,placeOfService:'10'}];expect(defaultAppointmentServiceLocation(rows,'IN_PERSON',8)?.id).toBe(2);expect(defaultAppointmentServiceLocation(rows,'IN_PERSON',9)).toBeNull();expect(defaultAppointmentServiceLocation(rows.slice(0,2),'TELEHEALTH',8)).toBeNull();});
it('shows every event in a provider day with explicit types and Mountain times',()=>{
 const summary={scheduleEvents:[{id:1,startAt:'2026-10-01T21:00:00Z',endAt:'2026-10-01T22:00:00Z',title:'Synthetic session',serviceCode:'90837'},{id:2,startAt:'2026-10-01T21:30:00Z',endAt:'2026-10-01T22:00:00Z',kind:'TEAM_MEETING',title:'Team'}],officeEvents:[{id:3,startAt:'2026-10-01T21:00:00Z',endAt:'2026-10-01T22:00:00Z',slotState:'ASSIGNED_AVAILABLE'}]};
 const items=dayScheduleEntries(summary,'2026-10-01');expect(items).toHaveLength(3);expect(items[0].hour).toBe(15);expect(items.map(i=>i.type)).toEqual(expect.arrayContaining(['Session','Team meeting','Office opening']));expect(items[0].timeLabel).toContain('3:00');
});
it('keeps busy-only views free of titles, service codes and external identities',()=>{const summary={detailLevel:'typed',scheduleEvents:[{title:'PRIVATE',startAt:'2026-10-01T21:00:00Z',endAt:'2026-10-01T22:00:00Z'}],busyBlocks:[{startAt:'2026-10-01T21:00:00Z',endAt:'2026-10-01T22:00:00Z',title:'PRIVATE',activityType:'session',serviceCode:'PRIVATE'}]};const items=dayScheduleEntries(summary,'2026-10-01','America/Denver','typed');expect(JSON.stringify(items)).not.toContain('PRIVATE');expect(items[0].title).toBe('Session');});
it('assigns late evening UTC instants to the actual Colorado service day',()=>{const summary={scheduleEvents:[{id:1,startAt:'2026-10-02T02:00:00Z',endAt:'2026-10-02T03:00:00Z'}]};expect(dayScheduleEntries(summary,'2026-10-01')[0].hour).toBe(20);expect(dayScheduleEntries(summary,'2026-10-02')).toHaveLength(0);});
