import { describe, expect, it } from 'vitest';
import { cardPrintPositions, cardSheetPlan, normalizePrintSettings, printSettingsDefaults, printableCardsHtml } from '../businessCardPrint';
import { cardQrUrl } from '../businessCardBack';
import { cardSvg, organizationCardDefaults, resolveCard } from '../businessCards';
describe('saved tenant card printing',()=>{
 it('moves only the first row down and retains extra lower bleed for ITSCO',()=>{const settings=printSettingsDefaults({slug:'itsco'});expect(settings).toMatchObject({topRowOffsetY:.0625,bleed:.0625,bottomBleed:.09375});const positions=cardPrintPositions(settings);expect(positions[0].y).toBe(.9375);expect(positions[3].y).toBe(4.25);expect(positions[6].y).toBe(7.625);expect(printSettingsDefaults({slug:'other'}).topRowOffsetY).toBe(0);});
 it('reflects back positions for long-edge duplex and applies separate back calibration',()=>{const settings={offsetX:.025,offsetY:.01,topRowOffsetY:.05,backOffsetX:.01,backOffsetY:.02};const fronts=cardPrintPositions(settings),backs=cardPrintPositions(settings,true);for(let i=0;i<9;i++){expect(backs[i].x).toBeCloseTo(8.5-fronts[i].x-2.5+.01);expect(backs[i].y).toBeCloseTo(fronts[i].y+.02);}});
 it('pairs each employee front with the agency back without interleaving employees',()=>{const cards=[{name:'Sam',website:'example.org'},{name:'Alex',website:'example.org'}];expect(cardSheetPlan(cards,{side:'both'}).map(s=>[s.name,s.face])).toEqual([['Sam','front'],['Sam','back'],['Alex','front'],['Alex','back']]);const html=printableCardsHtml(cards,{side:'both'});const doc=new DOMParser().parseFromString(html,'text/html');expect(doc.querySelectorAll('.sheet')).toHaveLength(4);expect(doc.querySelectorAll('.card')).toHaveLength(36);});
 it('keeps the agency QR destination even when an employee overrides the front website',()=>{const card=resolveCard({name:'Sam',website:'https://personal.example/'},organizationCardDefaults({website_url:'https://agency.example/'}));expect(card.website).toBe('https://personal.example/');expect(cardQrUrl(card)).toBe('https://agency.example/');});
 it('does not substitute an employee website when the agency has no QR destination',()=>{const card=resolveCard({name:'Sam',website:'https://personal.example/'},organizationCardDefaults({}));expect(()=>cardQrUrl(card)).toThrow();expect(()=>cardSheetPlan([card],{side:'front'})).not.toThrow();});
 it('uses white text only for the requested tenant and preserves trim with asymmetric bleed',()=>{const itsco=organizationCardDefaults({slug:'itsco'}),other=organizationCardDefaults({slug:'other'});expect(itsco.primaryText).toBe('#ffffff');expect(other.primaryText).toBe('auto');const svg=cardSvg({...itsco,name:'Sam',address:'Office'},{},.0625,.09375);expect(svg).toContain('viewBox="-18.75 -18.75 787.5 796.875"');expect(svg).toContain('fill="#ffffff">Sam');});
 it('blocks missing or unsafe QR destinations only when backs are requested',()=>{expect(()=>cardSheetPlan([{name:'Sam'}],{side:'front'})).not.toThrow();expect(()=>cardSheetPlan([{name:'Sam'}],{side:'back'})).toThrow();for(const website of ['javascript:alert(1)','https://user:pass@example.org'])expect(()=>cardQrUrl({website})).toThrow();});
 it('rejects out-of-page combined offsets and invalid bleed settings',()=>{expect(()=>normalizePrintSettings({bleed:-1})).toThrow();expect(()=>normalizePrintSettings({topRowOffsetY:NaN})).toThrow();expect(()=>cardPrintPositions({offsetX:.125,backOffsetX:-.125,bleed:.125},true)).toThrow();});
});
