import {describe,it,expect,vi,beforeEach,afterEach} from 'vitest';
import {anonymousWebsiteVisitor,websiteSource,analyticsCsv,createWebsiteTracker} from '../publicWebsiteAnalytics';
let visibility;
class IntersectionMock{constructor(callback){visibility=callback;}observe(){}unobserve(){}disconnect(){}}
function start(){const emit=vi.fn(),onTargets=vi.fn();const tracker=createWebsiteTracker({document,window,pagePath:'/p/itsco/providers',canTrack:()=>true,emit,onTargets});return{emit,onTargets,tracker};}
beforeEach(()=>{vi.useFakeTimers();window.IntersectionObserver=IntersectionMock;document.body.innerHTML='<div class="itsco-site"><h1>Providers</h1><section data-analytics-id="directory"><h2>Meet our team</h2><article data-analytics-id="provider-42"><h3>Public Provider</h3><a href="/itsco/provider/42?secret=never-send">View profile</a></article><form><label>Search<input type="search" value="private search text"></label><label>Insurance<select><option>Private choice</option></select></label><input type="email" value="private@example.test"><textarea>Private message</textarea><button>Send message</button></form><section class="public-profile-editor"><h3>Private edits</h3><button>Save secret</button></section></section></div>';});
afterEach(()=>{vi.useRealTimers();document.body.innerHTML='';});
describe('public website analytics privacy and identity',()=>{
 it('records public actions and generic search/filter usage without inputs, queries or private editor activity',()=>{const {emit,tracker}=start();document.querySelector('a').dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true}));document.querySelector('input[type=search]').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('select').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('.public-profile-editor button').click();expect(emit.mock.calls.map(([e])=>e.kind)).toEqual(['page_view','profile_open','search','filter_use']);const data=JSON.stringify(emit.mock.calls);for(const secret of ['private search text','private@example.test','Private choice','Private message','secret=','Save secret'])expect(data).not.toContain(secret);expect(emit.mock.calls.at(-1)[0].label).toBe('Insurance');tracker.stop();});
 it('keeps explicit provider identity through filtering and translation',()=>{const {emit,tracker}=start();const card=document.querySelector('article');const link=card.querySelector('a');link.click();const first=emit.mock.calls.at(-1)[0].targetKey;card.querySelector('h3').textContent='Proveedor';card.parentElement.prepend(Object.assign(document.createElement('article'),{innerHTML:'<h3>Another</h3>'}));link.textContent='Ver perfil';link.click();expect(emit.mock.calls.at(-1)[0].targetKey).toBe(first);expect(first).toContain('provider-42');tracker.stop();});
 it('requires sustained visible area exposure and stops all event collection on disposal',()=>{const{emit,tracker}=start();const el=document.querySelector('article');const entry={target:el,isIntersecting:true,intersectionRatio:.6,intersectionRect:{height:200}};visibility([entry]);vi.advanceTimersByTime(600);visibility([{...entry,isIntersecting:false,intersectionRatio:0}]);vi.advanceTimersByTime(1000);expect(emit.mock.calls.some(([e])=>e.kind==='section_view')).toBe(false);visibility([entry]);vi.advanceTimersByTime(1000);expect(emit.mock.calls.filter(([e])=>e.kind==='section_view')).toHaveLength(1);visibility([entry]);vi.advanceTimersByTime(1000);expect(emit.mock.calls.filter(([e])=>e.kind==='section_view')).toHaveLength(1);tracker.stop();document.querySelector('a').click();expect(emit.mock.calls).toHaveLength(2);});
 it('uses expiring browser identifiers and tolerates disabled storage',()=>{const storage={getItem:vi.fn(),setItem:vi.fn()};const crypto={randomUUID:()=> '12345678-1234-1234-1234-123456789abc'};const id=anonymousWebsiteVisitor(storage,crypto,100);expect(storage.setItem).toHaveBeenCalled();storage.getItem.mockReturnValue(JSON.stringify({id,expires:200}));expect(anonymousWebsiteVisitor(storage,crypto,150)).toBe(id);const blocked={getItem(){throw Error();},setItem(){throw Error();}};expect(anonymousWebsiteVisitor(blocked,crypto)).toBe(id);});
 it('exports a real CSV with spreadsheet formula protection and groups referrers without URLs',()=>{const csv=analyticsCsv([{pagePath:'/p/itsco',label:' =HYPERLINK("bad")',kind:'click',count:2,visitors:1,lastSeen:'2026-09-12'}]);expect(csv).toContain("' =HYPERLINK");expect(csv).toContain('""bad""');expect(websiteSource('https://www.google.com/search?q=private','https://app.test')).toBe('search');expect(websiteSource('https://app.test/private?token=abc','https://app.test')).toBe('internal');});
});
