import {afterEach,beforeEach,expect,it,vi} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import Desk from '../WebsiteChatDesk.vue';
import api from '../../../services/api';
vi.mock('../../../services/api',()=>({default:{get:vi.fn(),post:vi.fn()}}));
let wrapper,rows,threads;
const detail=id=>({messages:threads[id],quickReplies:[{label:'Get started',body:'Welcome. https://www.itsco.health/join/itsco/counseling'}],pageLinks:[{label:'Services',url:'https://www.itsco.health/services'}],viewers:[{userId:1,name:'Staff One',memberNumber:1,viewing:true,typing:true}],topics:[{id:'billing',label:'Billing'}],canReply:true});
beforeEach(()=>{vi.useFakeTimers();localStorage.clear();rows=[{id:'visitor-a',name:'ITSCO',color:'#165c4f',lastMessageId:1,lastVisitorMessageId:1,pagePath:'/services',visitorMessages:1},{id:'visitor-b',name:'NLU',color:'#234567',lastMessageId:2,lastVisitorMessageId:2,pagePath:'/tutoring',visitorMessages:1}];threads={'visitor-a':[{id:1,sender:'visitor',body:'Question'}],'visitor-b':[{id:2,sender:'visitor',body:'Another question'}]};api.post.mockImplementation(async url=>({data:url.endsWith('/referral')?{url:'https://www.itsco.health/live-chat-support?ref=test'}:detail(url.includes('visitor-b')?'visitor-b':'visitor-a')}));api.get.mockImplementation(async url=>({data:url==='/website-chat/sessions'?{sessions:rows}:url==='/website-chat/team'?{team:[{userId:1,name:'Staff One'}]}:detail(url.split('/').at(-1))}));});
afterEach(()=>{wrapper?.unmount();vi.useRealTimers();vi.clearAllMocks();});
async function render(){wrapper=mount(Desk,{global:{stubs:{teleport:true}}});await flushPromises();}
async function select(index=0){await wrapper.findAll('.visitor-toast button')[index].trigger('click');await flushPromises();}
it('shows page, initiation reminder, viewer names, quick replies and manual sends',async()=>{await render();expect(wrapper.text()).toContain('They cannot chat with you');expect(wrapper.text()).toContain('/services');await select();expect(wrapper.text()).toContain('Staff One (Support team member 1) · typing');await wrapper.find('[aria-label="Quick replies"]').setValue('Welcome. https://www.itsco.health/join/itsco/counseling');expect(api.post.mock.calls.filter(([url])=>url.endsWith('/messages'))).toHaveLength(0);await wrapper.find('form').trigger('submit');await flushPromises();expect(api.post).toHaveBeenCalledWith('/website-chat/sessions/visitor-a/messages',expect.objectContaining({body:expect.stringContaining('/join/itsco')}),expect.anything());});
it('closing returns the conversation to available chats without deleting it',async()=>{await render();await select();await wrapper.findAll('button').find(b=>b.text()==='Close chat').trigger('click');await flushPromises();expect(wrapper.findAll('.visitor-toast')).toHaveLength(2);expect(wrapper.find('textarea').exists()).toBe(false);expect(api.post).toHaveBeenCalledWith('/website-chat/sessions/visitor-a/close',{},expect.anything());await select();expect(wrapper.find('textarea').exists()).toBe(true);});
it('preserves separate drafts and alerts on another open chat',async()=>{await render();await select();await wrapper.find('textarea').setValue('Draft A');await select(1);await wrapper.find('textarea').setValue('Draft B');threads['visitor-a'].push({id:3,sender:'visitor',body:'Hello again'});rows[0].lastVisitorMessageId=3;await vi.advanceTimersByTimeAsync(8000);expect(wrapper.find('.visitor-toast').text()).toContain('Message waiting');await select();expect(wrapper.find('textarea').element.value).toBe('Draft A');});
it('requires confirmation to flag standards and can insert a ticket invitation',async()=>{await render();threads['visitor-a'].push({id:3,sender:'staff',body:'Welcome'});await select();await wrapper.findAll('button').find(b=>b.text()==='Flag Community Standards').trigger('click');expect(api.post.mock.calls.some(([url])=>url.endsWith('/standards'))).toBe(false);await wrapper.findAll('button').find(b=>b.text()==='Confirm flag & notify visitor').trigger('click');await flushPromises();expect(api.post).toHaveBeenCalledWith('/website-chat/sessions/visitor-a/standards',{confirmed:true},expect.anything());await wrapper.findAll('button').find(b=>b.text()==='Insert support ticket invitation').trigger('click');await flushPromises();expect(wrapper.find('textarea').element.value).toContain('/live-chat-support?ref=test');});
it('provides a team availability page',async()=>{await render();await wrapper.findAll('button').find(b=>b.text()==='Team availability').trigger('click');await flushPromises();expect(wrapper.text()).toContain('Staff One');});

it('clicking the selected visitor collapses and reopens the chat with its draft intact',async()=>{await render();await select();await wrapper.find('textarea').setValue('Unsent reply');await select();expect(wrapper.find('textarea').exists()).toBe(false);expect(wrapper.find('.visitor-toast button').attributes('aria-expanded')).toBe('false');expect(api.post.mock.calls.some(([url])=>url.endsWith('/close'))).toBe(false);threads['visitor-a'].push({id:3,sender:'visitor',body:'Still here'});rows[0].lastVisitorMessageId=3;await vi.advanceTimersByTimeAsync(8000);expect(wrapper.find('textarea').exists()).toBe(false);expect(wrapper.find('.visitor-toast').text()).toContain('Message waiting');await select();expect(wrapper.find('textarea').element.value).toBe('Unsent reply');expect(wrapper.find('.visitor-toast button').attributes('aria-expanded')).toBe('true');});
