<template><div class="edit-backdrop"><section role="dialog" aria-modal="true" :aria-label="action==='delete'?'Remove opening':'Move opening'" class="edit-card"><h3>{{action==='delete'?'Remove opening':'Move opening'}}</h3><label v-if="row.kind==='weekly'">Occurrence date<input type="date" v-model="occurrenceDate"/></label><p v-else>{{new Date(row.startAt).toLocaleString(undefined,{timeZone})}}</p><fieldset v-if="recurring"><legend>Apply this change to</legend><label><input type="radio" v-model="scope" value="single"/> This occurrence only</label><label><input type="radio" v-model="scope" value="future"/> This and all future occurrences</label></fieldset><p v-if="scope==='future'">Past occurrences stay unchanged. Future openings follow the new day and time at the same interval.</p><template v-if="action==='move'"><label>New date<input type="date" v-model="startDate"/></label><label>Start<input type="time" v-model="startTime"/></label><label>End<input type="time" v-model="endTime"/></label><p v-if="row.kind!=='weekly'">The target times must already have available office reservations. If any are missing, nothing will move.</p></template><fieldset v-if="action==='move'"><legend>Care types</legend><label v-for="type in ['INDIVIDUAL','COUPLES','FAMILY']" :key="type"><input type="checkbox" v-model="careTypes" :value="type"/> {{type}}</label></fieldset><p>Existing appointments and held selections stay protected.</p><p v-if="error" role="alert">{{error}}</p><footer><button :disabled="busy" @click="$emit('close')">Cancel</button><button :disabled="busy" @click="save">{{busy?'Saving…':action==='delete'?'Remove opening':'Save change'}}</button></footer></section></div></template>
<script setup>
import {computed,ref} from 'vue';
import api from '../../services/api';
import {availabilityOccursOn} from '../../utils/availabilityRecurrence';
const props=defineProps({row:{type:Object,required:true},action:{type:String,required:true},providerId:Number,timeZone:{type:String,default:'America/Denver'}}),emit=defineEmits(['close','saved']);
const local=(date,options)=>new Intl.DateTimeFormat('en-CA',{timeZone:props.timeZone,...options}).format(new Date(date));
const today=local(new Date(),{year:'numeric',month:'2-digit',day:'2-digit'});
function firstDate(){if(props.row.startAt)return local(props.row.startAt,{year:'numeric',month:'2-digit',day:'2-digit'});for(let n=0;n<400;n++){const d=new Date(today+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+n);const ymd=d.toISOString().slice(0,10);if(d.toLocaleDateString('en-US',{weekday:'long',timeZone:'UTC'})===props.row.dayOfWeek&&availabilityOccursOn(props.row,ymd))return ymd;}return props.row.startDate||today;}
const careTypes=ref(props.row.careTypes||['INDIVIDUAL','COUPLES','FAMILY']);
const occurrenceDate=ref(firstDate()),startDate=ref(occurrenceDate.value),scope=ref('single'),busy=ref(false),error=ref('');
const recurring=computed(()=>props.row.frequency!=='ONCE'&&(props.row.kind==='weekly'||props.row.seriesId));
const clock=value=>local(value,{hourCycle:'h23',hour:'2-digit',minute:'2-digit'});
const startTime=ref(props.row.startTime||clock(props.row.startAt)),endTime=ref(props.row.endTime||clock(props.row.endAt));
async function save(){busy.value=true;error.value='';try{const url=`/availability/providers/${props.providerId}/publications/${props.row.kind}/${props.row.id}`,payload={agencyId:props.row.agencyId,scope:recurring.value?scope.value:'single',occurrenceDate:occurrenceDate.value,startDate:startDate.value,startTime:startTime.value,endTime:endTime.value,careTypes:careTypes.value};if(props.action==='delete')await api.delete(url,{params:payload});else await api.patch(url,payload);emit('saved');}catch(e){error.value=e.response?.data?.error?.message||'Could not update the opening.';}finally{busy.value=false;}}
</script>
<style scoped>.edit-backdrop{position:fixed;inset:0;z-index:10000;background:#102c2877;display:grid;place-items:center;padding:20px}.edit-card{background:white;color:#173e36;border-radius:16px;padding:24px;width:min(460px,100%);max-height:85vh;overflow:auto;box-shadow:0 10px 40px #0003}.edit-card label{display:flex;gap:10px;align-items:center;margin:12px 0}.edit-card input[type=date],.edit-card input[type=time]{padding:8px;font:inherit;min-width:0}.edit-card footer{display:flex;justify-content:flex-end;gap:12px}.edit-card button{padding:10px;border-radius:8px;border:1px solid #abc;cursor:pointer}.edit-card [role=alert]{color:#a21c28}</style>
