<template>
 <article ref="element" class="provider-row" :aria-label="name">
  <div class="identity"><img v-if="person.profilePhotoUrl&&!photoFailed" :src="person.profilePhotoUrl" alt="" loading="lazy" @error="photoFailed=true"/><span v-else class="avatar" aria-hidden="true">{{initials}}</span><div><h3>{{name}}</h3><p>{{person.title||'Provider'}}</p><router-link :to="profileLink">View profile</router-link></div></div>
  <div class="preferences"><p class="mobile-label">Availability preferences</p><div v-if="draft" class="toggles"><label v-for="[key,label] in choices" :key="key"><input v-model="draft[key]" type="checkbox" :disabled="!canEdit||saving" :aria-label="`${name}: ${label}`"/>{{label}}</label></div><span v-else>Settings unavailable</span><div class="row-feedback"><template v-if="dirty"><button :disabled="saving" @click="save">{{saving?'Saving…':'Save changes'}}</button><button class="text-button" :disabled="saving" @click="reset">Undo</button></template><span v-else-if="notice" role="status">{{notice}}</span><small v-if="error" role="alert">{{error}}</small></div></div>
  <div class="details"><p class="mobile-label">Offices &amp; online requests</p><p>{{officeNames||'No assigned office'}}</p><p v-if="onlineServices.length"><span class="online-dot"/> Online: {{onlineServices.map(s=>s.displayName).join(', ')}}</p><p v-else class="muted">Online time requests off</p><button v-if="canEdit" class="text-button" @click="$emit('manage','preferences')">All preferences</button></div>
  <div class="opening"><p class="mobile-label">Next opening this week</p><template v-if="summary?.error"><p>Could not check openings</p><button class="text-button" @click="$emit('retry')">Retry check</button></template><template v-else-if="!summary"><p class="muted">{{checking?'Checking openings…':'Scroll to check openings'}}</p></template><template v-else><strong v-if="firstSlot">{{date(firstSlot.startAt)}}</strong><p v-if="firstSlot">{{time(firstSlot.startAt)}} · {{firstSlot.format==='VIRTUAL'?'Virtual':firstSlot.buildingName||'In person'}}</p><p v-else>{{summary.calendarWarnings?.length?'Availability not confirmed':'No posted openings this week'}}</p><small v-if="summary.calendarWarnings?.length" class="check-warning">Calendar check incomplete</small></template><button class="text-button" @click="$emit('manage','openings')">Manage availability</button></div>
 </article>
</template>
<script setup>
import {computed,nextTick,onMounted,onBeforeUnmount,ref,watch} from 'vue';
import api from '../../services/api';
const props=defineProps({person:{type:Object,required:true},agencyId:Number,summary:Object,checking:Boolean,canEdit:Boolean,profileLink:Object});
const emit=defineEmits(['visible','saved','manage','retry']);
const element=ref(null),photoFailed=ref(false),draft=ref(null),saving=ref(false),error=ref(''),notice=ref('');
const choices=[['seesClients','Sees clients'],['acceptingNewClients','New clients'],['waitlistEnabled','Waitlist'],['inPerson','In person'],['virtual','Virtual'],['school','School-based']];
const name=computed(()=>[props.person.first_name,props.person.last_name].filter(Boolean).join(' '));
const initials=computed(()=>name.value.split(' ').map(s=>s[0]).slice(0,2).join(''));
const dirty=computed(()=>JSON.stringify(draft.value)!==JSON.stringify(props.person.preferences||null));
const onlineServices=computed(()=>(props.person.services||[]).filter(s=>s.offered&&s.onlineScheduling));
const officeNames=computed(()=>(props.person.offices||[]).filter(o=>props.person.preferences?.officeIds==null||props.person.preferences.officeIds.includes(Number(o.id))).map(o=>o.name).join(', '));
const firstSlot=computed(()=>[...(props.summary?.virtualSlots||[]).map(s=>({...s,format:'VIRTUAL'})),...(props.summary?.inPersonSlots||[]).map(s=>({...s,format:'IN_PERSON'}))].filter(s=>Date.parse(s.startAt)>Date.now()).sort((a,b)=>Date.parse(a.startAt)-Date.parse(b.startAt))[0]);
const date=s=>new Date(s).toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:props.summary?.timeZone||'America/Denver'});
const time=s=>new Date(s).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit',timeZone:props.summary?.timeZone||'America/Denver'});
function reset(){draft.value=props.person.preferences?JSON.parse(JSON.stringify(props.person.preferences)):null;error.value='';notice.value='';}
watch(()=>[props.person.id,props.person.preferences,props.agencyId],reset,{immediate:true});
async function save(){saving.value=true;error.value='';notice.value='';try{const {data}=await api.put(`/availability/providers/${props.person.id}/public-settings`,{agencyId:props.agencyId,...draft.value,applyToAll:false},{skipGlobalLoading:true});emit('saved',data);await nextTick();notice.value=data.checkError||'Saved';}catch(e){error.value=e.response?.data?.error?.message||'Could not save. Your changes are still here.';}finally{saving.value=false;}}
let observer;
onMounted(()=>{if(typeof IntersectionObserver==='undefined'){emit('visible');return;}observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){emit('visible');observer.disconnect();}},{rootMargin:'160px'});observer.observe(element.value);});
onBeforeUnmount(()=>observer?.disconnect());
</script>
<style scoped>
.provider-row{display:grid;grid-template-columns:minmax(180px,1.05fr) minmax(240px,1.4fr) minmax(170px,1fr) minmax(170px,1fr);gap:22px;padding:22px 20px;border-bottom:1px solid #e0e8e4;background:white;color:#203e36;align-items:start}.provider-row:hover{background:#fbfdfc}.identity{display:flex;gap:12px;align-items:center;min-width:0}.identity img,.avatar{width:52px;height:62px;object-fit:cover;border-radius:10px;flex:none}.avatar{display:grid;place-items:center;background:#e8f1ed;color:#376651;font-weight:700;font-size:18px}.provider-row h3{margin:0 0 4px;font-size:16px;line-height:1.35;color:inherit}.provider-row p{font-size:13px;margin:3px 0;line-height:1.45}.identity p,.muted{color:#64776e}.provider-row a,.text-button{color:#176448;font-size:12px;text-decoration:none;font-weight:600}.toggles{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px 10px}.toggles label{display:flex;align-items:center;gap:6px;font-size:12px;white-space:nowrap;cursor:pointer}.toggles input{accent-color:#176448;width:16px;height:16px;margin:0;flex:none}.row-feedback{display:flex;align-items:center;gap:10px;flex-wrap:wrap;font-size:12px;color:#176448;margin-top:10px}.row-feedback button{font:inherit;padding:6px 10px;border:1px solid #a9c7b8;border-radius:6px;background:#f0f7f3;color:#176448;cursor:pointer}.provider-row .text-button{background:none;border:0;padding:6px 0;cursor:pointer;text-align:left}.online-dot{display:inline-block;width:6px;height:6px;border-radius:50%;background:#2c936c;margin-right:4px}.opening strong{font-size:14px}.check-warning{color:#916020;font-size:11px;display:block}.row-feedback [role=alert]{color:#a11d2a}.mobile-label{display:none}.provider-row button:disabled{opacity:.6}.provider-row :focus-visible{outline:3px solid #c99718;outline-offset:3px}
@media(max-width:1100px){.provider-row{grid-template-columns:1fr 1.3fr;gap:16px}.mobile-label{display:block!important;text-transform:uppercase;letter-spacing:.05em;font-size:10px!important;color:#72877a;margin-bottom:9px!important}.identity{align-self:center}.details,.opening{padding-top:10px;border-top:1px solid #e6ede9}}
@media(max-width:600px){.provider-row{grid-template-columns:1fr;padding:20px 16px}.toggles{grid-template-columns:repeat(3,1fr)}.identity img,.avatar{width:48px;height:54px}.preferences{padding-top:4px}.provider-row .identity h3{font-size:17px}}
</style>
