<template>
 <section class="workspace" aria-label="Openings and preferences">
  <header><h2>Openings &amp; preferences</h2><p>Find a provider’s next opening, manage their preferences, and coordinate client placement.</p></header>
  <details class="explanation"><summary>How published availability works</summary><p>Accepting new clients controls whether this provider is taking referrals. Published hours specify when they can meet. Online time requests let visitors select a preferred time; your team still confirms placement.</p><p>Appointments, school commitments, pending requests, and connected calendar busy times remove openings. An office reservation can support an opening when explicitly published. School enrollment is managed separately.</p><p>Choose this occurrence or this and all future occurrences when removing or moving an opening. Future changes keep the existing repeat interval. Office reservations and existing appointments stay in place.</p></details>
  <AvailabilityAssistantSearch :agency-id="agencyId" :providers="providers" :can-edit-preferences="canPreferences" @manage="openResult"/>
  <div class="toolbar"><label>Find a provider<input v-model="search" type="search" placeholder="Search by name"/></label><label>Show<select v-model="statusFilter"><option value="">All providers</option><option value="accepting">Accepting new clients</option><option value="inPerson">In person</option><option value="virtual">Virtual</option><option value="waitlistEnabled">Waitlist enabled</option><option value="closed">Not accepting new clients</option></select></label><label>Week containing<input v-model="week" type="date"/></label><button @click="refresh">Refresh openings</button><span class="provider-count">{{filtered.length}} providers · scroll to view all</span></div>
  <p v-if="error" role="alert">{{error}}</p><p v-if="loading" role="status">Loading providers…</p>
  <p class="roster-hint">Update choices in each row, then save that provider. All preferences includes services, online time requests, assigned offices, and schedule sharing.</p>
  <div class="roster"><div class="roster-heading" aria-hidden="true"><span>Provider</span><span>Availability preferences</span><span>Offices &amp; online requests</span><span>Next opening this week</span></div>
   <ProviderAvailabilityRow v-for="person in filtered" :key="String(agencyId)+':'+person.id" :person="person" :agency-id="agencyId" :summary="summaries[person.id]" :checking="checkingIds.has(person.id)" :can-edit="canPreferences" :profile-link="profileLink(person)" @visible="observeProvider(person)" @retry="requestSummary(person,true)" @saved="savedRow(person,$event)" @manage="open(person,$event)"/>
   <p v-if="!loading&&!filtered.length" class="empty-roster">No providers match these filters.</p>
  </div>
  <dialog ref="dialog" @close="close" @cancel.prevent="close"><template v-if="selected"><header class="modal-header"><div><h2>{{name(selected)}}</h2><p>Availability and preferences for this agency</p></div><button @click="close" aria-label="Close provider availability">Close</button></header>
   <div class="toolbar"><button v-for="t in tabs" :key="t.id" :aria-pressed="tab===t.id" @click="tab=t.id">{{t.label}}</button><router-link :to="scheduleLink">Open schedule / book session →</router-link></div>
   <p v-if="detailError" role="alert">{{detailError}}</p><p v-if="notice" role="status">{{notice}}</p>
   <div v-if="tab==='openings'"><p v-if="detailLoading">Checking this week’s openings…</p><template v-else-if="detail"><p v-for="warning in detail.calendarWarnings||[]" :key="warning" class="conflict">{{warning}}</p><p>Week of {{detail.weekStart}} · {{detail.timeZone}} · New-client openings after calendar conflicts</p><div class="day-grid"><article v-for="group in groups" :key="group.date"><h3>{{date(group.startAt,detail.timeZone)}}</h3><p v-for="(slot,i) in group.slots" :key="i">{{time(slot.startAt,detail.timeZone)}}–{{time(slot.endAt,detail.timeZone)}} · {{slot.format==='VIRTUAL'?'Virtual':slot.buildingName||'In person'}}</p></article></div><p v-if="!groups.length">No openings this week. Check preferences, published hours, and conflicts below.</p><h3>Why published time is unavailable</h3><p v-if="!detail.diagnostics?.length">No conflicts were found within published new-client windows. If hours are missing, check the publication’s new-client setting, selected schedule, and office assignment.</p><article v-for="(item,i) in detail.diagnostics||[]" :key="i" class="conflict"><strong>{{date(item.startAt,detail.timeZone)}} · {{time(item.startAt,detail.timeZone)}}–{{time(item.endAt,detail.timeZone)}}</strong><p>{{item.format==='VIRTUAL'?'Virtual':item.buildingName||'In person'}} · {{item.reasons.join('; ')}}</p><small>A partial conflict may leave other times in this window available.</small></article></template></div>
   <ProviderAvailabilitySettings v-if="tab==='preferences'" :key="selected.id" :provider-id="Number(selected.id)" :agency-id="agencyId" @updated="updated"/>
   <div v-if="tab==='hours' && detail"><p>Remove the publication to hide its openings. This preserves reservations and appointments.</p><p v-if="detail.scheduleAgencyId!==agencyId">Weekly hours come from agency #{{detail.scheduleAgencyId}}. Changes affect every agency reusing that schedule.</p><h3>Virtual availability windows</h3><div v-for="row in detail.weekly" :key="row.id" class="publication"><span>{{row.dayOfWeek}} · {{row.startTime}}–{{row.endTime}} · {{row.frequency}}<br/><small>{{row.availableForIntake?'New clients':'Current clients only'}}</small></span><button :disabled="busy||!detail.canEditSource" @click="publicationEdit={row:{...row,kind:'weekly',agencyId:detail.scheduleAgencyId},action:'move'}">Move opening</button><button :disabled="busy||!detail.canEditSource" @click="remove({...row,kind:'weekly',agencyId:detail.scheduleAgencyId})">Remove availability window</button></div><p v-if="!detail.weekly.length">No weekly virtual hours published.</p>
    <details v-if="detail.canEditSource"><summary>Add or edit virtual hours</summary><VirtualWorkingHoursEditor :key="hoursVersion" :agency-id="Number(detail.scheduleAgencyId)" :provider-id="Number(selected.id)" @updated="updated"/></details>
    <h3>Dated and office-linked openings</h3><div v-for="row in detail.publications" :key="row.kind+row.id" class="publication"><span>{{date(row.startAt,detail.timeZone)}} · {{time(row.startAt,detail.timeZone)}}–{{time(row.endAt,detail.timeZone)}} · {{row.kind==='virtual'?'Virtual':'In person'}}<br/><small>{{row.availableForIntake?'New clients':'Current clients only'}}{{row.buildingId?' · Office #'+row.buildingId:''}}</small></span><button :disabled="busy||!row.canEdit" @click="publicationEdit={row,action:'move'}">Move opening</button><button :disabled="busy||!row.canEdit" @click="remove(row)">Remove opening</button></div><p v-if="!detail.publications.length">No upcoming dated openings published.</p><router-link :to="scheduleLink">Add office availability or select multiple schedule slots →</router-link>
   </div>
   <div v-if="tab==='clients'"><h3>Assign a client to {{name(selected)}}</h3><form class="toolbar" @submit.prevent="searchClients"><label>Find a client<input v-model="clientSearch" type="search" required minlength="2" placeholder="Name or initials"/></label><button :disabled="busy">Search</button></form><div v-for="client in clients" :key="client.id" class="publication"><span>{{client.full_name||[client.first_name,client.last_name].filter(Boolean).join(' ')||client.initials||('Client #'+client.id)}}<br/><small>{{client.provider_id?'Already assigned — review before changing':'Unassigned'}}</small></span><router-link v-if="client.organization_id||client.provider_id" :to="clientLink(client)">Review assignment →</router-link><button v-else :disabled="busy" @click="assign(client)">Assign to {{name(selected)}}</button></div><p v-if="clientSearched&&!clients.length">No matching clients found.</p><p>School and existing assignments open the client record so you can review service days and the current care team. Assigning a client starts the existing onboarding workflow; book the appointment from the schedule.</p></div>
  <AvailabilityPublicationEdit v-if="publicationEdit" :row="publicationEdit.row" :action="publicationEdit.action" :provider-id="Number(selected.id)" :time-zone="detail?.timeZone" @close="publicationEdit=null" @saved="publicationEdit=null;updated()"/>
  </template></dialog>
 </section>
</template>
<script setup>
import {computed,nextTick,ref,watch} from 'vue';
import {useRoute} from 'vue-router';
import {useAuthStore} from '../../store/auth';
import api from '../../services/api';
import ProviderAvailabilityRow from './ProviderAvailabilityRow.vue';
import AvailabilityPublicationEdit from './AvailabilityPublicationEdit.vue';
import ProviderAvailabilitySettings from './ProviderAvailabilitySettings.vue';
import AvailabilityAssistantSearch from './AvailabilityAssistantSearch.vue';
import VirtualWorkingHoursEditor from './VirtualWorkingHoursEditor.vue';
import {availabilityDayGroups} from '../../utils/availabilityDayGroups';
const props=defineProps({agencyId:{type:Number,required:true}});
const auth=useAuthStore(),route=useRoute();
const providers=ref([]),search=ref(''),statusFilter=ref(''),week=ref(new Date().toLocaleDateString('en-CA',{timeZone:'America/Denver'})),summaries=ref({}),loading=ref(false),error=ref('');
const publicationEdit=ref(null);
const selected=ref(null),dialog=ref(null),detail=ref(null),detailLoading=ref(false),detailError=ref(''),tab=ref('openings'),busy=ref(false),notice=ref(''),hoursVersion=ref(0);
const clientSearch=ref(''),clients=ref([]),clientSearched=ref(false);
const name=p=>[p.first_name,p.last_name].filter(Boolean).join(' ');
const prefix=computed(()=>route.params.organizationSlug?`/${route.params.organizationSlug}`:'');
const scheduleLink=computed(()=>({path:`${prefix.value}/admin/users/${selected.value?.id}`,query:{agencyId:props.agencyId,tab:'schedule_availability'}}));
const clientLink=c=>({path:`${prefix.value}/admin/clients/${c.id}`,query:{agencyId:props.agencyId}});
const profileLink=p=>({path:`${prefix.value}/admin/users/${p.id}`,query:{agencyId:props.agencyId,section:'service-availability'}});
const canPreferences=computed(()=>['super_admin','admin','support','staff'].includes(auth.user?.role));
const tabs=computed(()=>[{id:'openings',label:'Openings & conflicts'},...(canPreferences.value?[{id:'preferences',label:'Preferences'},{id:'clients',label:'Assign clients'}]:[]),{id:'hours',label:'Add / remove hours'}]);
const filtered=computed(()=>providers.value.filter(p=>name(p).toLowerCase().includes(search.value.trim().toLowerCase())&&(!statusFilter.value||(statusFilter.value==='closed'?!p.preferences?.acceptingNewClients:statusFilter.value==='accepting'?p.preferences?.seesClients&&p.preferences?.acceptingNewClients:p.preferences?.[statusFilter.value]))));
const slots=data=>[...(data?.virtualSlots||[]).map(s=>({...s,format:'VIRTUAL'})),...(data?.inPersonSlots||[]).map(s=>({...s,format:'IN_PERSON'}))].filter(s=>Date.parse(s.startAt)>Date.now()).sort((a,b)=>Date.parse(a.startAt)-Date.parse(b.startAt));
const groups=computed(()=>availabilityDayGroups(slots(detail.value),detail.value?.timeZone));
const date=(s,tz='America/Denver')=>new Date(s).toLocaleDateString(undefined,{weekday:'long',month:'short',day:'numeric',timeZone:tz});
const time=(s,tz='America/Denver')=>new Date(s).toLocaleTimeString(undefined,{hour:'numeric',minute:'2-digit',timeZone:tz});
let generation=0,detailGeneration=0,summaryGeneration=0;
function close(){publicationEdit.value=null;++detailGeneration;dialog.value?.close();selected.value=null;detail.value=null;clients.value=[];clientSearched.value=false;}
async function refresh(){const g=++generation;resetSummaries();observedIds.clear();close();providers.value=[];loading.value=true;error.value='';summaries.value={};try{const {data}=await api.get('/availability/admin/providers',{params:{agencyId:props.agencyId,includePreferences:true},skipGlobalLoading:true});if(g===generation){providers.value=data;}}catch(e){if(g===generation)error.value='Could not load providers.';}finally{if(g===generation)loading.value=false;}}
const checkingIds=ref(new Set()),observedIds=new Set();
let queue=[],running=0;
const pendingRefresh=new Map();
function observeProvider(person){observedIds.add(person.id);requestSummary(person);}
function requestSummary(person,force=false){if(force&&checkingIds.value.has(person.id)){pendingRefresh.set(person.id,person);return;}if(!/^\d{4}-\d{2}-\d{2}$/.test(week.value)||checkingIds.value.has(person.id)||(!force&&summaries.value[person.id]))return;checkingIds.value=new Set([...checkingIds.value,person.id]);queue.push({person,g:summaryGeneration,agencyId:props.agencyId,weekStart:week.value});drainSummaries();}
async function drainSummaries(){while(running<3&&queue.length){const task=queue.shift();running++;(async()=>{try{const {data}=await api.get(`/availability/providers/${task.person.id}/week`,{params:{agencyId:task.agencyId,weekStart:task.weekStart,intakeOnly:true},skipGlobalLoading:true});if(task.g===summaryGeneration)summaries.value[task.person.id]=data;}catch(e){if(task.g===summaryGeneration)summaries.value[task.person.id]={error:true};}finally{if(task.g===summaryGeneration){const next=new Set(checkingIds.value);next.delete(task.person.id);checkingIds.value=next;const refreshPerson=pendingRefresh.get(task.person.id);if(refreshPerson){pendingRefresh.delete(task.person.id);requestSummary(refreshPerson,true);}}running--;drainSummaries();}})();}}
function resetSummaries(){++summaryGeneration;queue=[];pendingRefresh.clear();summaries.value={};checkingIds.value=new Set();}
async function savedRow(person,data){person.preferences=data.preferences;await requestSummary(person,true);}
function openResult({providerId,tab:destination='openings'}){const person=providers.value.find(p=>Number(p.id)===Number(providerId));if(person)open(person,destination);}
async function loadDetail(){if(!selected.value)return;const g=++detailGeneration;detailLoading.value=true;detailError.value='';try{const {data}=await api.get(`/availability/providers/${selected.value.id}/workspace`,{params:{agencyId:props.agencyId,weekStart:week.value},skipGlobalLoading:true});if(g===detailGeneration){detail.value=data;summaries.value[selected.value.id]=data;}}catch(e){if(g===detailGeneration)detailError.value=e.response?.data?.error?.message||'Could not check availability.';}finally{if(g===detailGeneration)detailLoading.value=false;}}
async function open(p,destination='openings'){selected.value=p;detail.value=null;tab.value=destination;notice.value='';await nextTick();dialog.value?.showModal();loadDetail();}
async function updated(data){hoursVersion.value++;if(data?.preferences)selected.value.preferences=data.preferences;if(data?.services)selected.value.services=data.services;await loadDetail();}
function remove(row){publicationEdit.value={row,action:'delete'};}
async function searchClients(){const g=detailGeneration;busy.value=true;detailError.value='';clients.value=[];try{const{data}=await api.get('/clients',{params:{agency_id:props.agencyId,search:clientSearch.value,page:1,per_page:30},skipGlobalLoading:true});if(g===detailGeneration){clients.value=(Array.isArray(data)?data:data.items||[]).slice(0,30);clientSearched.value=true;}}catch(e){if(g===detailGeneration)detailError.value='Could not search clients.';}finally{busy.value=false;}}
async function assign(client){if(!window.confirm(`Assign this client to ${name(selected.value)} and start their existing onboarding workflow?`))return;busy.value=true;detailError.value='';try{await api.put(`/clients/${client.id}/provider`,{provider_id:Number(selected.value.id)});notice.value='Client assigned. Their onboarding workflow has been updated.';await searchClients();}catch(e){detailError.value=e.response?.data?.error?.message||'Could not assign client.';}finally{busy.value=false;}}
watch(()=>props.agencyId,refresh,{immediate:true});watch(week,()=>{resetSummaries();for(const p of filtered.value)if(observedIds.has(p.id))requestSummary(p);});
</script>
<style scoped>
.workspace{color:#173e36}.workspace h2,.workspace h3{color:inherit}.workspace p{line-height:1.55}.toolbar{display:flex;flex-wrap:wrap;align-items:end;gap:12px;margin:18px 0}.toolbar label{display:grid;gap:6px}.workspace input{padding:10px;border:1px solid #bdcec7;border-radius:8px;font:inherit}.workspace button,.workspace a{font:inherit;color:#155c47}.workspace button{padding:10px 14px;border:1px solid #b4cfc1;border-radius:8px;background:white;cursor:pointer}.workspace button[aria-pressed=true]{background:#155c47;color:white}.workspace button:disabled{opacity:.5;cursor:default}.day-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}.day-grid article{padding:18px;border:1px solid #d0dfd8;border-radius:12px;background:#f7fbf9}.providers article{display:flex;flex-direction:column;align-items:start}.providers h3{margin:0}.providers button{margin-top:16px}.providers small{margin-top:auto}.explanation{padding:16px;border:1px solid #c8dbd2;border-radius:10px;background:#f0f7f3}.workspace summary{cursor:pointer;font-weight:600}.workspace dialog{width:min(980px,calc(100vw - 32px));max-height:90vh;box-sizing:border-box;overflow:auto;border:1px solid #bdcec7;border-radius:16px;padding:24px;color:#173e36;background:#fff}.workspace dialog::backdrop{background:#142c286b}.modal-header{display:flex;align-items:start;justify-content:space-between;gap:16px}.modal-header h2{margin:0}.publication{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:14px 0;border-bottom:1px solid #d7e2dc}.conflict{padding:14px;margin:12px 0;background:#fff8e8;border:1px solid #e5d5ae;border-radius:8px}.conflict p{margin:6px 0}.workspace :focus-visible{outline:3px solid #c99718;outline-offset:3px}.workspace [role=alert]{color:#a51e27}@media(max-width:600px){.publication{align-items:start;flex-direction:column}.workspace dialog{padding:16px}.toolbar>*{max-width:100%}.day-grid{grid-template-columns:1fr}}
.roster{border:1px solid #d4e1d9;border-radius:12px;overflow:hidden}.roster-heading{display:grid;grid-template-columns:minmax(180px,1.05fr) minmax(240px,1.4fr) minmax(170px,1fr) minmax(170px,1fr);gap:22px;padding:13px 20px;background:#edf4f0;text-transform:uppercase;font-size:10px;letter-spacing:.07em;font-weight:700;color:#567064}.provider-count{margin-left:auto;font-size:12px;color:#6a7d71;align-self:center}.roster-hint{font-size:12px;color:#667c6e;margin-bottom:14px}.empty-roster{padding:24px}.toolbar select{padding:10px;border:1px solid #bdcec7;border-radius:8px;background:white;font:inherit;color:inherit}@media(max-width:1100px){.roster-heading{display:none}}
</style>
