<template>
 <section class="availability-settings" aria-label="New client availability">
  <h3>New client availability</h3><p>Set new-client preferences for this agency. Published hours determine the times shown; existing appointments stay protected.</p>
  <p v-if="loading" role="status">Loading availability settings…</p>
  <template v-else-if="loaded"><p><strong>{{context.agencyName||'Selected agency'}}</strong></p><div class="choices">
   <label v-if="context.canApplyToAll&&context.agencies?.length>1"><input v-model="applyToAll" type="checkbox" :disabled="busy"/> Apply these settings and this schedule to all my agencies</label>
   <label>Schedule to display<select v-model.number="preferences.scheduleAgencyId" :disabled="busy"><option v-for="a in context.agencies||[]" :key="a.id" :value="Number(a.id)">{{a.name}}{{Number(a.id)===agencyId?' (this agency)':''}}</option></select></label>
   <small class="full-width">Use this agency’s schedule or reuse published hours from another agency.</small><div class="choice-group"><h4>Client availability</h4><label><input v-model="preferences.seesClients" type="checkbox" :disabled="busy"/> Sees clients for this agency</label><label><input v-model="preferences.acceptingNewClients" type="checkbox" :disabled="busy"/> Accepting new clients</label><label><input v-model="preferences.waitlistEnabled" type="checkbox" :disabled="busy"/> Accept waitlist requests</label><small>To keep a waitlist while closed to new clients, turn off “Accepting new clients,” leave “Accept waitlist requests” on, and choose the formats you offer.</small></div><div class="choice-group"><h4>Appointment formats</h4><label><input v-model="preferences.inPerson" type="checkbox" :disabled="busy"/> Offer in-person appointments</label><label><input v-model="preferences.virtual" type="checkbox" :disabled="busy"/> Offer virtual appointments</label><label><input v-model="preferences.school" type="checkbox" :disabled="busy"/> Offer assigned school-based services</label></div>
   <fieldset v-if="preferences.inPerson"><legend>In-person offices for {{context.agencyName||'this agency'}}</legend><label><input type="checkbox" :checked="preferences.officeIds===null" @change="preferences.officeIds=$event.target.checked?null:[]"/> All assigned offices in this agency</label><template v-if="preferences.officeIds!==null"><label v-for="office in context.offices||[]" :key="office.id"><input v-model="preferences.officeIds" type="checkbox" :value="office.id"/>{{office.name}} · {{office.city}}</label></template><small v-if="!context.offices?.length">Assign an office before publishing in-person openings.</small></fieldset>
   </div>
   <div class="actions"><button type="button" :disabled="busy" @click="save">{{busy?'Working…':'Save availability'}}</button><button type="button" :disabled="busy" @click="check">Check published openings</button><router-link :to="schedulePath">Add or edit openings →</router-link></div>
   <p v-if="checkedAt">Openings last checked {{new Date(checkedAt).toLocaleString()}}.</p>
   <article v-for="reminder in reminders" :key="reminder.format" class="warning"><strong>No {{reminder.format==='IN_PERSON'?'in-person':'virtual'}} new-client openings published in the next four schedule weeks.</strong><p><router-link :to="schedulePath">Add {{reminder.format==='IN_PERSON'?'in-person':'virtual'}} openings →</router-link> or update your choices above.</p><p v-if="reminder.snoozed">Reminder snoozed until {{new Date(reminder.snoozedUntil).toLocaleDateString()}}. This warning remains here until resolved.</p><button v-else type="button" :disabled="busy" @click="snooze(reminder.format)">Snooze reminder for 7 days</button></article>
  </template><p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p>
 </section>
 <ProviderServiceOfferings :provider-id="providerId" :agency-id="agencyId" @updated="$emit('updated', {kind: 'services', ...$event})" />
</template>
<script setup>
import {computed,ref,watch} from 'vue';
import {useRoute} from 'vue-router';
import {useAuthStore} from '../../store/auth';
import ProviderServiceOfferings from './ProviderServiceOfferings.vue';
import api from '../../services/api';
const props=defineProps({providerId:{type:Number,required:true},agencyId:{type:Number,required:true}});
const emit=defineEmits(['updated']);
const route=useRoute(),auth=useAuthStore();
const context=ref({}),applyToAll=ref(false);
const preferences=ref({acceptingNewClients:false,inPerson:false,virtual:false}),reminders=ref([]),checkedAt=ref(null),loading=ref(false),loaded=ref(false),busy=ref(false),error=ref(''),notice=ref('');
const endpoint=computed(()=>`/availability/providers/${props.providerId}/public-settings`);
const schedulePath=computed(()=>{const prefix=route?.params?.organizationSlug?`/${route.params.organizationSlug}`:'';return Number(auth.user?.id)===props.providerId?{path:`${prefix}/dashboard`,query:{tab:'my_schedule'}}:{path:`${prefix}/admin/users/${props.providerId}`,query:{agencyId:props.agencyId,tab:'schedule_availability'}};});
function apply(data){preferences.value={school:true,officeIds:null,scheduleAgencyId:props.agencyId,...data.preferences};if(data.agencies)context.value=data;reminders.value=data.reminders||[];checkedAt.value=data.checkedAt;}
let generation=0;
watch(()=>[props.providerId,props.agencyId],async()=>{const id=++generation;loaded.value=false;applyToAll.value=false;error.value='';if(!props.providerId||!props.agencyId)return;loading.value=true;try{const{data}=await api.get(endpoint.value,{params:{agencyId:props.agencyId},skipGlobalLoading:true});if(id===generation){apply(data);loaded.value=true;}}catch(e){if(id===generation)error.value=e.response?.data?.error?.message||'Could not load availability settings.';}finally{if(id===generation)loading.value=false;}},{immediate:true});
async function action(kind,body={}){busy.value=true;error.value='';notice.value='';const id=generation;try{const config={skipGlobalLoading:true};const {data}=kind==='save'?await api.put(endpoint.value,{agencyId:props.agencyId,...preferences.value,applyToAll:applyToAll.value},config):await api.post(`${endpoint.value}/${kind}`,{agencyId:props.agencyId,...body},config);if(id!==generation)return;apply(data);notice.value=data.checkError||(kind==='save'?'Availability saved.':kind==='snooze'?'Reminder snoozed for seven days.':'Published openings checked.');emit('updated', {kind, ...data});}catch(e){if(id===generation)error.value=e.response?.data?.error?.message||'Could not update availability. Please try again.';}finally{busy.value=false;}}
const save=()=>action('save'),check=()=>action('check'),snooze=format=>action('snooze',{format});
</script>
<style scoped>
.availability-settings{margin:18px 0;padding:20px;border:1px solid #c3d5ce;border-radius:12px;background:#fff;color:#203e36}.availability-settings h3{color:#203e36;font-size:21px}.choices{display:grid;grid-template-columns:1fr 1fr;gap:18px}.choices>label,.choices>.full-width,.choices>fieldset{grid-column:1/-1}.choice-group{display:grid;align-content:start;gap:14px;border:1px solid #dce6e0;background:#f8fbf9;padding:18px;border-radius:10px}.choice-group h4{margin:0 0 4px;font-size:14px;color:#2c5040}.choice-group small{font-size:12px;line-height:1.5;color:#698071}.choices label{display:flex;align-items:center;gap:10px}.choices input{width:17px;height:17px;accent-color:#176448;flex:none}.choices select{padding:10px;max-width:100%;font:inherit}.choices fieldset{display:grid;gap:12px;border:1px solid #c3d5ce;padding:16px}.actions{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin:18px 0}.availability-settings button{padding:10px 14px;border:1px solid #53796b;border-radius:6px;background:#f0f7f4;color:#173d30;font:inherit;cursor:pointer}.availability-settings a{color:#145e48;text-decoration:underline}.warning{background:#fff7df;border:1px solid #ddbb6e;border-radius:8px;padding:16px;margin:12px 0}.availability-settings p{line-height:1.5}.availability-settings button:disabled{opacity:.6}
@media(max-width:650px){.choices{grid-template-columns:1fr}.availability-settings{padding:16px}.choices label{font-size:13px}.choices select{min-width:0}}
</style>
