<template>
 <dialog ref="dialog" class="directory-launcher" @close="$emit('close')"><button class="close" aria-label="Close provider onboarding" @click="dialog.close()">✕</button><h2>Provider onboarding</h2><p>Create directory profiles with account access and an approval process. These links do not start hiring or employee onboarding.</p><p v-if="error" role="alert">{{ error }}</p><p v-if="loading">Loading directories…</p>
  <template v-else><label>Directory<select v-model="selected"><option value="">Choose a directory</option><option v-for="p in portals" :key="p.slug" :value="p.slug">{{ p.name }}</option></select></label>
   <section v-if="portal"><h3>{{ portal.name }}</h3><p><strong>New provider enrollment</strong></p><a :href="`${portal.url}/join`" target="_blank" rel="noopener">{{ portal.url }}/join ↗</a><p>Providers create their own username and password, build a profile and submit it for tenant-admin approval.</p><div class="actions"><button class="btn btn-primary" :disabled="loading" @click="openAdmin">Open review dashboard</button><DirectoryShare :url="portal.url" :name="portal.name" :directory-slug="portal.slug" /></div><p class="hint">To use the directory’s own login dropdown later, set a directory password in the review dashboard. Only administrators of the owning tenant can activate an admin account.</p></section>
   <details v-if="agencyId"><summary>Create another directory for the selected agency</summary><form @submit.prevent="create"><label>Directory name<input v-model="draft.name" required maxlength="255" /></label><label>URL name<input v-model="draft.slug" pattern="[a-z][a-z0-9\-]{2,60}" placeholder="your-provider-directory" required /></label><p>Public link: https://plottwisthq.com/provider-directory/{{ draft.slug || 'your-provider-directory' }}</p><button class="btn btn-secondary" :disabled="loading">Create directory</button></form></details>
  </template>
 </dialog>
</template>
<script setup>
import {ref,computed,onMounted} from 'vue';import {useRouter} from 'vue-router';import api from '../../services/api';import {rememberSession} from '../../services/providerDirectory';import DirectoryShare from './DirectoryShare.vue';
const props=defineProps({agencyId:[String,Number]});defineEmits(['close']);const router=useRouter(),dialog=ref(null),portals=ref([]),selected=ref(''),loading=ref(false),error=ref(''),draft=ref({name:'',slug:''});const portal=computed(()=>portals.value.find(p=>p.slug===selected.value));
async function load(){loading.value=true;try{portals.value=(await api.get('/provider-directories/manage')).data;selected.value=portals.value.find(p=>p.agencyId===Number(props.agencyId))?.slug||portals.value[0]?.slug||'';}catch(e){error.value=e.response?.data?.error?.message||'Could not load directories.';}finally{loading.value=false;}}
async function openAdmin(){loading.value=true;error.value='';try{const {data}=await api.post(`/provider-directories/${selected.value}/admin-session`);rememberSession(selected.value,data.token);const path=selected.value==='latinx'?'/latinx':`/provider-directory/${selected.value}`;dialog.value.close();router.push(`${path}/dashboard`);}catch(e){error.value=e.response?.data?.error?.message||'Could not open the review dashboard.';}finally{loading.value=false;}}
async function create(){loading.value=true;error.value='';try{await api.post('/provider-directories/manage',{...draft.value,agencyId:Number(props.agencyId)});await load();selected.value=draft.value.slug;}catch(e){error.value=e.response?.data?.error?.message||'Could not create directory.';}finally{loading.value=false;}}
onMounted(()=>{dialog.value.showModal();load();});
</script>
<style scoped>
.directory-launcher{width:min(740px,94vw);max-height:90dvh;border:1px solid #ddd;border-radius:16px;padding:30px;color:#302337}.directory-launcher::backdrop{background:#21162c88}.directory-launcher p{line-height:1.7}.directory-launcher label{display:grid;gap:8px;margin:18px 0}.directory-launcher input,.directory-launcher select{padding:12px;border:1px solid #d8cddd;border-radius:8px}.directory-launcher section{padding:20px;background:#faf8fb;border-radius:12px;margin:20px 0}.directory-launcher a{overflow-wrap:anywhere}.close{float:right}.actions{display:flex;gap:12px;flex-wrap:wrap}.hint{font-size:13px}.directory-launcher summary{cursor:pointer}
</style>
