import {mount,flushPromises} from '@vue/test-utils';import {beforeEach,it,expect,vi} from 'vitest';
import Panel from '../PayerEftPanel.vue';import api from '../../../services/api.js';
vi.mock('../../../services/api.js',()=>({default:{get:vi.fn(),post:vi.fn()}}));
const record={id:1,officeId:8,payerId:'COCHA',payerName:'CCHA',providerNpi:'1306688650',status:'active_reported',revision:1,identityCurrent:true,evidence:{source:'staff_report',reference:'Existing deposits reported',evidenceDate:'2026-09-25'},guide:{name:'CCHA / EnrollSafe',url:'https://enrollsafe.payeehub.org/'}};
beforeEach(()=>{vi.clearAllMocks();api.get.mockResolvedValue({data:{items:[record],offices:[{id:8,name:'Windchime',practice_npi:'1306688650'}]}});api.post.mockResolvedValue({data:{}});});
it('separates reported EFT from ERA and does not collect bank account fields',async()=>{const w=mount(Panel,{props:{agencyId:377}});await flushPromises();expect(w.text()).toContain('Direct deposits reported');expect(w.text()).toContain('ERA explains the payment');expect(w.find('a').attributes('href')).toBe('https://enrollsafe.payeehub.org/');expect(w.findAll('input').length).toBe(0);w.unmount();});
it('requires fresh attestation and saves tracking under the selected agency',async()=>{const w=mount(Panel,{props:{agencyId:377}});await flushPromises();await w.findAll('button').find(b=>b.text()==='Update status').trigger('click');expect(w.find('form button').attributes('disabled')).toBeDefined();await w.find('input[type=checkbox]').setValue(true);await w.find('form').trigger('submit');await flushPromises();expect(api.post).toHaveBeenCalledWith('/medical-billing/payer-eft',expect.objectContaining({agencyId:377,payerId:'COCHA',revision:1,status:'active_reported',attested:true}));expect(w.text()).toContain('Bank instructions and payments were not changed');w.unmount();});
it('does not display verification when the enrollment belongs to an old billing identity',async()=>{api.get.mockResolvedValue({data:{items:[{...record,status:'active_verified',identityCurrent:false}],offices:[]}});const w=mount(Panel,{props:{agencyId:377}});await flushPromises();expect(w.text()).toContain('Billing identity changed');expect(w.text()).not.toContain('Bank deposit verified by staff');w.unmount();});
it('discards a prior tenant response after scope changes',async()=>{let old;api.get.mockImplementationOnce(()=>new Promise(resolve=>{old=resolve;})).mockResolvedValue({data:{items:[],offices:[]}});const w=mount(Panel,{props:{agencyId:377}});await w.setProps({agencyId:2});await flushPromises();old({data:{items:[record],offices:[]}});await flushPromises();expect(w.text()).not.toContain('Direct deposits reported');w.unmount();});
