<template>
  <section class="ft-lead-form" aria-label="Request a FundThred conversation">
    <div v-if="submitted" ref="success" role="status" tabindex="-1"><FundThredIcon name="approvals"/><h2>Your next step is in motion.</h2><p>We received your request and will follow up at <strong>{{ form.email }}</strong>.</p><p class="ft-small">Reference: {{ submitted }}</p><p>No subscription has started and no payment has been collected.</p><router-link class="ft-button" to="/fundthred/product">Explore FundThred →</router-link></div>
    <form v-else @submit.prevent="submit"><h2>Tell us about your mission.</h2><p>We’ll help you find the right starting point.</p><div class="ft-form-grid"><label class="ft-form-full">Organization name<input v-model.trim="form.businessName" autocomplete="organization" maxlength="200" required></label><label>First name<input v-model.trim="form.firstName" autocomplete="given-name" maxlength="100" required></label><label>Last name<input v-model.trim="form.lastName" autocomplete="family-name" maxlength="100" required></label><label>Work email<input v-model.trim="form.email" type="email" autocomplete="email" maxlength="254" required></label><label>Phone<input v-model.trim="form.phone" type="tel" autocomplete="tel" maxlength="40" required></label><label>Organization stage<select v-model="form.stage"><option value="established">Established</option><option value="expanding">Growing</option><option value="launching">Preparing to launch</option><option value="idea">Exploring an idea</option></select></label><label>Interested in<select v-model="plan"><option value="demo">A FundThred demo</option><option v-for="item in fundthredPlans" :key="item.id" :value="item.id">{{ item.name }}</option></select></label><label class="ft-form-full">What would help your team?<textarea v-model.trim="form.goals" rows="4" maxlength="650" required placeholder="Your programs, funding sources, organization count, and what you would like to make easier."/><small>Please leave out donor payment details and confidential records.</small></label></div><fieldset><legend>Other products to discuss (optional)</legend><label v-for="product in fundthredBundles" :key="product.id" class="ft-form-check"><input v-model="bundles" type="checkbox" :value="product.id">{{ product.name }}</label></fieldset><div class="ft-form-trap" aria-hidden="true"><label>Leave empty<input v-model="form.websiteTrap" tabindex="-1" autocomplete="off"></label></div><label class="ft-form-check ft-form-consent"><input v-model="form.consent" type="checkbox" required><span>I agree that Plot Twist Co. may contact me about this request. <a href="/privacypolicy" target="_blank" rel="noopener">Privacy policy</a></span></label><p v-if="error" class="ft-form-error" role="alert">{{ error }}</p><button class="ft-button" :disabled="busy">{{ busy?'Sending…':'Let’s talk about your mission →' }}</button></form>
  </section>
</template>
<script setup>
import {ref,reactive,nextTick} from 'vue';
import {useRoute} from 'vue-router';
import {fundthredPlans,fundthredBundles} from '../../config/fundthredProduct';
import FundThredIcon from './FundThredIcon.vue';
const route=useRoute(),plan=ref(fundthredPlans.some(p=>p.id===route.query.plan)?route.query.plan:'demo');
const interval=route.query.interval==='annual'?'annual':'monthly';
const bundles=ref(String(route.query.bundle||'').split(',').filter(id=>fundthredBundles.some(product=>product.id===id)));
const form=reactive({businessName:'',firstName:'',lastName:'',email:'',phone:'',businessType:'other',stage:'established',goals:'',consent:false,websiteTrap:''});
const busy=ref(false),error=ref(''),submitted=ref(''),success=ref(null);let submissionKey='',lastPayload='';
async function submit(){
  if(busy.value)return;busy.value=true;error.value='';
  const services=[...new Set(['operations',...fundthredBundles.filter(product=>bundles.value.includes(product.id)).map(product=>product.service)])];
  const payload=JSON.stringify({...form,path:'hq',services,goals:`FundThred · ${plan.value} · ${interval} · Bundle: ${bundles.value.join(', ')||'standalone'}\n${form.goals}`});
  if(payload!==lastPayload){submissionKey=crypto.randomUUID();lastPayload=payload;}
  try{const response=await fetch('/api/public/marketing-pages/ptco/business/requests',{method:'POST',credentials:'omit',headers:{'Content-Type':'application/json','Idempotency-Key':submissionKey},body:payload});const data=await response.json();if(!response.ok||!data.id)throw Error(data.error?.message||'We could not confirm your request. Please try again.');submitted.value=data.id;await nextTick();success.value?.focus();}catch(e){error.value=e instanceof TypeError?'We could not connect. Your request has not been confirmed. Please try again.':e.message;}finally{busy.value=false;}
}
</script>
<style scoped>
.ft-lead-form{background:#fff;border:1px solid #dce8ee;border-radius:18px;padding:34px;box-shadow:0 10px 40px #17394c08}.ft-lead-form h2{font-size:25px}.ft-lead-form p{font-size:13px}.ft-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:19px}.ft-form-full{grid-column:1/-1}.ft-lead-form label{font-size:12px;font-weight:600;display:grid;gap:7px}.ft-lead-form input:not([type=checkbox]),.ft-lead-form select,.ft-lead-form textarea{background:#fbfdfe;color:#12324a;padding:12px;border:1px solid #c6d5df;border-radius:7px;width:100%;min-width:0;font-size:14px}.ft-lead-form small{font-size:10px;font-weight:400;color:#62788b}.ft-lead-form fieldset{border:0;padding:0;margin:24px 0}.ft-lead-form legend{font-size:12px;margin-bottom:10px;font-weight:600}.ft-lead-form .ft-form-check{display:flex;align-items:start;gap:9px;font-weight:400;margin:10px 0;line-height:1.6}.ft-form-check input{margin-top:4px;accent-color:#16876e}.ft-form-trap{position:absolute;left:-9999px}.ft-lead-form .ft-form-consent{margin:24px 0}.ft-form-error{color:#a83c3c!important}.ft-lead-form [role=status]{overflow-wrap:anywhere}@media(max-width:600px){.ft-form-grid{grid-template-columns:1fr}.ft-lead-form{padding:24px}}
</style>
