<template><div class="ft-surface ft-login-shell"><header class="ft-wrap"><router-link to="/fundthred" aria-label="FundThred home"><FundThredBrand/></router-link><nav aria-label="FundThred sign in navigation"><router-link to="/fundthred/product">Explore FundThred</router-link><button @click="$emit('security')">Security</button><a href="https://plottwisthq.com/login">PlotTwistHQ ↗</a></nav></header><main class="ft-wrap"><section class="ft-login-intro"><p class="ft-eyebrow">Your mission, in view</p><h1>Follow the thread<br>of <em>every dollar.</em></h1><p>Welcome to FundThred. Bring your funding, budgets, requests, and proof together in one financial workspace.</p><div><FundThredIcon name="funds"/><FundThredIcon name="budgets" tone="purple"/><FundThredIcon name="expenses" tone="blue"/><FundThredIcon name="documents" tone="amber"/><FundThredIcon name="reports"/></div><p class="ft-small">Use your existing account. Your organization’s finance permissions determine what you can open.</p></section><section class="ft-login-auth" aria-label="Sign in to FundThred"><slot/></section></main><footer class="ft-wrap"><span>FundThred by Plot Twist Co.</span><nav aria-label="Policies"><router-link to="/privacypolicy">Privacy</router-link><router-link to="/terms">Terms</router-link><router-link to="/fundthred/start">Contact</router-link></nav></footer></div></template>
<script setup>
import FundThredBrand from './FundThredBrand.vue';
import FundThredIcon from './FundThredIcon.vue';
import '../../styles/fundthred.css';
defineEmits(['security']);
</script>
<style scoped>
.ft-login-shell{display:block!important;min-height:100vh!important;padding:0!important;background:radial-gradient(ellipse at 0 30%,#e9f6f1,transparent 50%),radial-gradient(ellipse at 95% 60%,#e8f3fc,transparent 50%),#fbfdfd!important;color:#0a203e!important}.ft-login-shell>header{display:flex;align-items:center;justify-content:space-between;gap:30px;min-height:110px}.ft-login-shell nav{display:flex;gap:25px;align-items:center;font-size:12px}.ft-login-shell nav a{text-decoration:none}.ft-login-shell nav button{border:0;background:none;color:#173f55;font-size:12px}.ft-login-shell>main{display:grid;grid-template-columns:1fr 1fr;gap:90px;align-items:center;min-height:650px;padding-block:45px}.ft-login-intro h1{font-size:clamp(40px,4.2vw,60px)}.ft-login-intro>p:not(.ft-eyebrow){max-width:480px}.ft-login-intro>div{display:flex;gap:18px;margin:35px 0}.ft-login-shell>footer{display:flex;justify-content:space-between;gap:25px;padding-block:35px;font-size:12px;border-top:1px solid #dce8ed;color:#62798c}.ft-login-auth{min-width:0}.ft-login-auth :deep(.login-container){width:100%!important;max-width:500px!important;margin:0 auto!important;display:block!important;background:transparent!important;padding:0!important;min-height:0!important}.ft-login-auth :deep(.login-card){background:#fff!important;border:1px solid #d9e5ec!important;border-radius:18px!important;box-shadow:0 14px 55px #214d6210!important;padding:35px!important;color:#12364b!important;width:100%!important;max-width:none!important;backdrop-filter:none!important}.ft-login-auth :deep(.hq-cardhead){text-align:center;margin-bottom:24px}.ft-login-auth :deep(.hq-cardhead p){color:#506987}.ft-login-auth :deep(input:not([type=checkbox])),.ft-login-auth :deep(select){background:#f9fcfd!important;color:#17364b!important;border-color:#b9cdd9!important}.ft-login-auth :deep(.btn-primary){background:#12364b!important;color:#fff!important;border-color:#12364b!important}.ft-login-auth :deep(.form-group label){color:#15374e!important}.ft-login-auth :deep(.help-link){color:#157b78!important}.ft-login-auth :deep(.hq-powered){font-size:11px;text-align:center;color:#58788c}.ft-login-auth :deep(.app-preview-toggle-group){display:none}@media(max-width:900px){.ft-login-shell>main{gap:35px}.ft-login-intro h1{font-size:40px}}@media(max-width:650px){.ft-login-shell>header{min-height:95px;align-items:center}.ft-login-shell>header nav{gap:10px;font-size:10px}.ft-login-shell>header nav>a:first-child{display:none}.ft-login-shell>header .ft-brand{width:150px}.ft-login-shell>main{grid-template-columns:1fr;min-height:0;gap:30px;padding-block:25px 45px}.ft-login-intro h1{font-size:37px}.ft-login-intro>div{display:none}.ft-login-intro>p:last-child{display:none}.ft-login-auth :deep(.login-card){padding:25px!important}.ft-login-shell>footer{flex-wrap:wrap}.ft-login-intro>p{font-size:14px}}
</style>
<style scoped>
.ft-login-auth :deep(.hq-cardhead h2){color:#0d203d!important;font-size:24px;letter-spacing:-.035em;margin:12px 0 10px}.ft-login-auth :deep(.login-card){font-family:FundThred,Arial,sans-serif!important}.ft-login-auth :deep(.remember-row){display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px;margin:16px 0}.ft-login-auth :deep(.remember-me){font-size:12px;gap:8px}.ft-login-auth :deep(.remember-me input){accent-color:#087d76}.ft-login-auth :deep(.remember-row .help-link){font-size:12px}.ft-login-auth :deep(.password-toggle-btn){color:#087d76!important}.ft-login-auth :deep(.hq-divider){display:flex;align-items:center;gap:14px;margin:22px 0;font-size:10px;letter-spacing:.1em;color:#617588}.ft-login-auth :deep(.hq-divider:before),.ft-login-auth :deep(.hq-divider:after){content:'';height:1px;background:#e0e8ed;flex:1}.ft-login-auth :deep(.hq-google){display:flex;align-items:center;justify-content:center;gap:12px;width:100%;min-height:46px;border:1px solid #c8d9e3;border-radius:8px;background:#fff;color:#12364b;font:inherit;font-size:13px;margin-bottom:20px;cursor:pointer}.ft-login-auth :deep(.hq-google:hover){background:#f1f7fa}.ft-login-auth :deep(.help-links){text-align:center;font-size:12px}.ft-login-auth :deep(.btn-primary){min-height:46px}.ft-login-auth :deep(.hq-cardhead p){font-size:13px}
</style>
