<template>
  <div class="ft-pricing">
    <div class="ft-billing-toggle" role="group" aria-label="Billing period"><button :aria-pressed="interval==='monthly'" @click="interval='monthly'">Monthly</button><button :aria-pressed="interval==='annual'" @click="interval='annual'">Annual <span>Save about 20%</span></button></div>
    <div class="ft-plans"><article v-for="plan in fundthredPlans" :key="plan.id" :class="{'ft-plan--featured':plan.featured}"><span v-if="plan.featured" class="ft-plan-ribbon">Room to grow</span><h2>{{ plan.name }}</h2><p>{{ plan.description }}</p><div class="ft-plan-price"><strong>{{ plan.monthlyCents===null?'Let’s talk':money(fundthredEstimate(plan.id,interval).monthlyEquivalentCents,interval==='annual') }}</strong><span v-if="plan.monthlyCents!==null"> /month</span></div><p class="ft-plan-period">{{ plan.monthlyCents===null?'Tailored pricing':interval==='annual'?`${money(plan.annualCents)} billed annually`:'Billed monthly' }}</p><router-link class="ft-button" :class="{'ft-button--outline':plan.id==='custom'}" :to="requestLocation(plan.id)">{{ plan.id==='custom'?'Talk to our team':'Get started' }} <span aria-hidden="true">→</span></router-link><ul><li v-for="feature in plan.features" :key="feature"><span aria-hidden="true">✓</span>{{ feature }}</li></ul></article></div>
    <p class="ft-note">Estimates in USD. Setup, integrations, payment processing, and optional products are scoped separately. Your plan and price are confirmed before activation.</p>
    <section id="bundles" class="ft-bundle-builder"><div><p class="ft-eyebrow">Connect more of your work</p><h2>Your mission.<br><em>Your combination.</em></h2><p>Start with FundThred. Add the products your organization needs and bring them together in PlotTwistHQ.</p><p class="ft-small">Bundle pricing is quoted with your organization’s setup. Selecting products here does not change access or start a subscription.</p></div><div><fieldset><legend>Include in my bundle conversation</legend><label v-for="product in fundthredBundles" :key="product.id"><input v-model="selected" type="checkbox" :value="product.id"><span><strong>{{ product.name }}</strong><small>{{ product.description }}</small></span></label></fieldset><router-link class="ft-button" :to="requestLocation('custom')">Discuss {{ selected.length?'my bundle':'bundle options' }} →</router-link></div></section>
  </div>
</template>
<script setup>
import {ref} from 'vue';
import {fundthredPlans,fundthredBundles,fundthredEstimate} from '../../config/fundthredProduct';
const interval=ref('monthly'),selected=ref([]);
const money=(cents,decimals=false)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:decimals?2:0}).format(cents/100);
const requestLocation=plan=>({path:'/fundthred/start',query:{plan,interval:interval.value,...(selected.value.length?{bundle:selected.value.join(',')}:{})}});
</script>
<style scoped>
.ft-billing-toggle{display:flex;width:max-content;max-width:100%;padding:5px;border:1px solid #e3ecf1;box-shadow:0 2px 9px #17394c0b;border-radius:30px;background:white;margin:0 auto 48px;gap:4px}.ft-billing-toggle button{padding:9px 27px;border:0;border-radius:22px;background:none;color:#0a203e;font-size:13px;min-height:44px}.ft-billing-toggle button[aria-pressed=true]{background:#102b45;color:#fff}.ft-billing-toggle span{font-size:10px;color:#167763;background:#e3f4ed;padding:3px 6px;border-radius:5px;margin-left:8px}.ft-plans{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:22px}.ft-plans article{border:1px solid #e2eaf0;padding:30px 25px;border-radius:16px;box-shadow:0 5px 25px #25485c06;background:#fff;position:relative;display:flex;flex-direction:column}.ft-plans article.ft-plan--featured{border-color:#159d91;background:linear-gradient(150deg,#effaf7,#fff)}.ft-plan-ribbon{position:absolute;inset:-25px -1px auto;background:#078c84;border-radius:13px 13px 0 0;padding:5px;color:#fff;text-align:center;font-size:11px;height:28px}.ft-plans h2{font-size:23px;margin:0 0 8px}.ft-plans p{font-size:13px;min-height:64px;margin:0 0 18px}.ft-plan-price{margin-top:8px;white-space:nowrap}.ft-plan-price strong{font-size:39px;letter-spacing:-2px;line-height:1.3}.ft-plan-price>span{font-size:12px;color:#58718a}.ft-plans .ft-plan-period{font-size:11px;min-height:0;margin:0 0 18px}.ft-plans .ft-button{width:100%;font-size:12px;padding-inline:12px;margin-bottom:12px}.ft-plans ul{list-style:none;padding:20px 0 0;margin:8px 0 0;border-top:1px solid #deeaec}.ft-plans li{font-size:12px;display:flex;align-items:start;gap:10px;margin-bottom:13px;color:#48617d;line-height:1.6}.ft-plans li span{color:#168366;font-weight:700}.ft-pricing>.ft-note{margin-top:22px}.ft-bundle-builder{display:grid;grid-template-columns:1fr 1fr;gap:70px;margin-top:65px;background:#f2f8fa;border:1px solid #e3edf2;border-radius:20px;padding:42px}.ft-bundle-builder p{font-size:14px}.ft-bundle-builder fieldset{border:0;padding:0;margin:0 0 23px}.ft-bundle-builder legend{font-size:13px;font-weight:600;margin-bottom:15px}.ft-bundle-builder label{display:flex;gap:12px;align-items:start;padding:11px 0;cursor:pointer}.ft-bundle-builder label input{margin-top:6px;accent-color:#12846f;width:17px;height:17px}.ft-bundle-builder label strong{font-size:14px}.ft-bundle-builder label small{display:block;color:#566f83;font-size:12px}@media(max-width:1000px){.ft-plans{grid-template-columns:repeat(2,minmax(0,1fr));gap:40px 22px}.ft-bundle-builder{gap:30px;padding:28px}}@media(max-width:600px){.ft-plans{grid-template-columns:1fr;gap:38px}.ft-plans p{min-height:0}.ft-billing-toggle button{padding-inline:17px}.ft-bundle-builder{grid-template-columns:1fr;padding:24px;margin-top:40px}.ft-plan-price strong{font-size:39px}}
</style>
