<template><ol class="ft-flow" aria-label="From funding to impact"><li v-for="step in steps" :key="step.area"><button v-if="interactive" @click="$emit('navigate',step.area)"><FundThredIcon :name="step.icon" :tone="step.tone"/><strong>{{ step.title }}</strong><small>{{ step.body }}</small></button><div v-else><FundThredIcon :name="step.icon" :tone="step.tone"/><strong>{{ step.title }}</strong><small>{{ step.body }}</small></div></li></ol></template>
<script setup>
import FundThredIcon from './FundThredIcon.vue';
defineProps({ interactive: Boolean });
defineEmits(['navigate']);
const steps=[{area:'funds',icon:'funds',tone:'green',title:'Funding received',body:'Grants & donations'},{area:'budgets',icon:'budgets',tone:'blue',title:'Budget assigned',body:'A purpose for each dollar'},{area:'expenses',icon:'expenses',tone:'purple',title:'Request submitted',body:'Details & supporting proof'},{area:'approvals',icon:'approvals',tone:'amber',title:'Reviewed & approved',body:'A clear decision'},{area:'payments',icon:'payments',tone:'green',title:'Payment recorded',body:'Spending in context'},{area:'documents',icon:'documents',tone:'blue',title:'Proof attached',body:'Receipts & agreements'},{area:'reports',icon:'reports',tone:'purple',title:'Reported for impact',body:'A connected story'}];
</script>
<style scoped>
.ft-flow{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:16px;padding:0;margin:25px 0;list-style:none}.ft-flow li{position:relative;min-width:0}.ft-flow li:not(:last-child):after{content:'→';position:absolute;right:-14px;top:13px;color:#80a7cf}.ft-flow li>div,.ft-flow li>button{display:flex;flex-direction:column;align-items:center;gap:10px;text-align:center;width:100%;background:none;border:0;padding:0;font:inherit;color:inherit}.ft-flow li>button{cursor:pointer}.ft-flow strong{font-size:12px;line-height:1.5}.ft-flow small{font-size:10px!important;line-height:1.5;color:#58718a!important}.ft-flow .ft-icon{border-radius:50%;width:49px;height:49px;box-shadow:0 0 0 5px #ffffff90}.ft-flow button:hover .ft-icon{transform:translateY(-3px)}@media(max-width:720px){.ft-flow{grid-template-columns:repeat(4,minmax(0,1fr));gap:20px 12px}.ft-flow li:after{display:none}}@media(max-width:420px){.ft-flow{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(prefers-reduced-motion:reduce){.ft-flow button:hover .ft-icon{transform:none}}
</style>
