<template><section class="checkin-inbox"><header><div><h2>Check-in submissions</h2><p>Client arrivals and visit questionnaires, organized by appointment. Attach unmatched submissions to a client and session when they are ready.</p></div><button @click="load">Refresh</button></header><p v-if="error" role="alert">{{ error }}</p><p v-if="loading">Loading check-ins…</p><p v-else-if="!rows.length">No check-ins yet. New arrivals for your appointments will appear here.</p>
<article v-for="row in rows" :key="row.id"><button class="visit" @click="select(row)"><strong>{{ when(row.scheduled_start_at,row.timezone) }}</strong><span>{{ row.location_name }} · {{ row.forms_json.respondentType==='caregiver'?'Parent / caregiver response':'Self response' }}</span><span>{{ row.client_id ? `Attached: ${clientLabel(row)}` : 'Needs client attachment' }} · {{ row.completed_at ? 'Forms submitted' : row.forms_json.forms.length ? 'Forms not submitted' : 'Arrival recorded' }}</span></button>
<div v-if="selected?.id===row.id" class="details"><p v-if="row.forms_unavailable">Some configured forms could not be presented for this respondent.</p><div v-for="form in row.forms_json.forms" :key="form.id"><h3>{{ form.title }}</h3><dl><template v-for="field in form.fields" :key="field.id"><dt>{{ field.label }}</dt><dd>{{ answer(row,form,field) }}</dd></template></dl></div>
<p>Attach these responses to an existing client. The original responses and appointment remain preserved.</p><label>Find a client on your caseload<input v-model="query" placeholder="Name, initials, or client code" @input="search" /></label><select v-model="clientId" aria-label="Client to attach" @change="loadSessions"><option value="">Choose a client</option><option v-for="client in clients" :key="client.id" :value="client.id">{{ clientLabel(client) }}</option></select>
<label>Session (optional)<select v-model="sessionId"><option value="">Attach to client only</option><option v-for="session in sessions" :key="session.id" :value="session.id">{{ when(session.scheduled_start_at,row.timezone) }}</option></select></label><button :disabled="!clientId || saving" @click="attach">{{ saving?'Attaching…':'Attach to client / session' }}</button><router-link :to="createClientTo">Create a client first</router-link><button @click="selected=null">Close details</button>
</div></article></section></template>
<script setup>
import { ref,onMounted,onUnmounted } from 'vue';
import api from '../../services/api';
defineProps({createClientTo:{type:[String,Object],required:true}});
const rows=ref([]),loading=ref(false),error=ref(''),selected=ref(null),query=ref(''),clients=ref([]),clientId=ref(''),sessions=ref([]),sessionId=ref(''),saving=ref(false);
let searchTimer,version=0,disposed=false;
const clientLabel=c=>c.full_name || c.initials || c.identifier_code || `Client ${c.client_id || c.id}`;
const when=(value,tz)=>value?new Date(/[zZ]|[+-]\d\d:\d\d$/.test(value)?value:String(value).replace(' ','T')+'Z').toLocaleString('en-US',{timeZone:tz || 'America/Denver',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'Unscheduled';
const answer=(row,form,field)=>{const v=row.answers_json?.[form.id]?.[field.id];return v==null?'Not submitted':Array.isArray(v)?v.join(', '):typeof v==='boolean'?(v?'Yes':'No'):String(v);};
async function load(){loading.value=true;error.value='';try{const {data}=await api.get('/kiosk/client-checkins');if(!disposed)rows.value=data.submissions || [];}catch{error.value='Check-in submissions could not load.';}finally{loading.value=false;}}
function select(row){version++;clearTimeout(searchTimer);selected.value=selected.value?.id===row.id?null:row;query.value='';clients.value=[];clientId.value='';sessionId.value='';sessions.value=[];error.value='';}
function search(){const request=++version;clearTimeout(searchTimer);clients.value=[];clientId.value='';sessionId.value='';sessions.value=[];if(query.value.trim().length<2)return;const id=selected.value.id,q=query.value;searchTimer=setTimeout(async()=>{try{const {data}=await api.get(`/kiosk/client-checkins/${id}/clients`,{params:{q}});if(request===version&&!disposed)clients.value=data.clients || [];}catch{if(request===version)error.value='Client search could not load.';}},250);}
async function loadSessions(){const request=++version;sessions.value=[];sessionId.value='';if(!clientId.value)return;try{const {data}=await api.get(`/kiosk/client-checkins/${selected.value.id}/sessions`,{params:{clientId:clientId.value}});if(request===version&&!disposed)sessions.value=data.sessions || [];}catch{error.value='Sessions could not load. You can still attach to the client.';}}
async function attach(){saving.value=true;error.value='';try{await api.patch(`/kiosk/client-checkins/${selected.value.id}/attachment`,{clientId:clientId.value,sessionId:sessionId.value || null});selected.value=null;await load();}catch(e){error.value=e.response?.data?.error?.message || 'Attachment could not be saved.';}finally{saving.value=false;}}
onMounted(load);onUnmounted(()=>{disposed=true;version++;clearTimeout(searchTimer);});
</script>
<style scoped>.checkin-inbox{padding:24px}header{display:flex;justify-content:space-between;gap:20px}p{line-height:1.6}article{border:1px solid #d5dfd6;border-radius:14px;margin:14px 0;overflow:hidden}.visit{display:grid;gap:8px;width:100%;text-align:left;border:0;background:#f3f6ef;padding:20px}.visit strong{font-size:18px}.visit span{font-size:13px}.details{padding:20px}label{display:grid;gap:8px;margin:16px 0}input,select,button{font:inherit;padding:12px;border:1px solid #b9caba;border-radius:8px}button{cursor:pointer}button:disabled{opacity:.5}select{max-width:100%}dt{font-weight:600;margin-top:12px}dd{margin:6px 0;white-space:pre-wrap}a{display:inline-block;margin:15px}</style>
