<template><section class="feedback-trends"><header><div><h3>Check-in feedback over time</h3><p>Connection, current challenges, and reported progress · Higher scores move toward green at 10.</p></div><button @click="load">Refresh</button></header>
 <p v-if="error" role="alert">{{error}}</p><p v-if="loading">Loading feedback…</p><p v-else-if="!visits.length">No check-in visits are attached yet. Go to Clients → Recurring check-ins to review and attach them.</p>
 <template v-else><div class="controls"><label>Service<select v-model="service"><option v-for="s in services" :key="s" :value="s">{{s==='tutoring'?'Tutoring':'Therapy / counseling'}}</option></select></label><label>Respondent<select v-model="respondent"><option v-for="r in respondents" :key="r" :value="r">{{respondentLabel(r)}}</option></select></label></div>
  <p class="method">Custom feedback scores, not validated clinical measures. Each score is an average from 0–10; distress is reversed so less distress raises the score. A total requires all six answers. Skipped, unanswered, and “not applicable” responses are not scored. Self and dependent reports are shown separately.</p>
  <div class="charts"><article v-for="metric in metrics" :key="metric.key"><h4>{{metric.label}}</h4><strong class="latest" :style="{color:scoreColor(latest(metric.key))}">{{latest(metric.key)==null?'—':latest(metric.key).toFixed(1)}}<small> / 10</small></strong>
   <svg viewBox="0 0 600 220" role="img" :aria-label="`${metric.label} scores over time, from zero in red to ten in green`"><defs><linearGradient :id="`${chartId}-${metric.key}`" x1="0" y1="180" x2="0" y2="20" gradientUnits="userSpaceOnUse"><stop offset="0%" stop-color="#bc3030"/><stop offset="50%" stop-color="#bb850e"/><stop offset="100%" stop-color="#23833d"/></linearGradient></defs>
    <g v-for="n in [0,5,10]" :key="n"><line x1="42" x2="578" :y1="y(n)" :y2="y(n)" stroke="#dce4dc"/><text x="13" :y="y(n)+4" fill="#526352" font-size="13">{{n}}</text></g>
    <polyline v-if="points(metric.key).length>1" :points="points(metric.key).map(p=>`${p.x},${p.y}`).join(' ')" fill="none" :stroke="`url(#${chartId}-${metric.key})`" stroke-width="3"/>
    <circle v-for="p in points(metric.key)" :key="p.id" :cx="p.x" :cy="p.y" r="6" :fill="scoreColor(p.value)"><title>{{date(p.date)}} · {{p.value.toFixed(1)}} / 10</title></circle>
    <text x="42" y="210" font-size="12" fill="#526352">{{filtered.length?date(filtered[0].scheduledStartAt):''}}</text><text x="578" y="210" text-anchor="end" font-size="12" fill="#526352">{{filtered.length>1?date(filtered.at(-1).scheduledStartAt):''}}</text>
   </svg><p v-if="!points(metric.key).length">No complete scores yet.</p>
  </article></div>
  <div class="legend"><span>0 · Lower reported experience</span><div/><span>10 · Stronger reported experience</span></div>
  <details v-for="visit in [...filtered].reverse()" :key="visit.id"><summary>{{date(visit.scheduledStartAt,true)}} · <strong :style="{color:scoreColor(visit.score.total)}">{{visit.score.total==null?(visit.score.expected?`Incomplete · ${visit.score.answered}/${visit.score.expected} answered`:'Questionnaire responses'):`${visit.score.total.toFixed(1)} / 10 total`}}</strong></summary><p>{{visit.location}} · {{respondentLabel(visit.respondentType)}}</p><div v-for="form in visit.forms" :key="form.id"><h4>{{form.title}}</h4><p v-if="visit.skippedFormIds.includes(form.id)">Skipped</p><dl v-else><template v-for="q in form.fields" :key="q.id"><dt>{{q.label}}</dt><dd>{{answer(visit,form,q)}}</dd></template></dl></div></details>
 </template></section></template>
<script setup>
import {ref,computed,watch,onUnmounted} from 'vue';import api from '../../services/api';
const props=defineProps({clientId:{type:[Number,String],required:true}});const visits=ref([]),loading=ref(false),error=ref(''),service=ref('counseling'),respondent=ref('adult_self');let version=0;const chartId=`feedback-${crypto.randomUUID()}`;
const metrics=[{key:'total',label:'Overall feedback'},{key:'connection',label:'Connection with provider'},{key:'progress',label:'Challenges & progress'}];
const services=computed(()=>[...new Set(visits.value.map(v=>v.serviceType))]);const respondents=computed(()=>[...new Set(visits.value.filter(v=>v.serviceType===service.value).map(v=>v.respondentType))]);
const filtered=computed(()=>visits.value.filter(v=>v.serviceType===service.value&&v.respondentType===respondent.value));
const respondentLabel=r=>r==='caregiver'?'Dependent / caregiver':r==='youth_self'?'Self · Under 18':'Self · Adult';
const instant=v=>new Date(/[zZ]|[+-]\d\d:\d\d$/.test(v)?v:String(v).replace(' ','T')+'Z');
const date=(v,time=false)=>instant(v).toLocaleString('en-US',{timeZone:filtered.value[0]?.timezone||'America/Denver',month:'short',day:'numeric',year:'numeric',...(time?{hour:'numeric',minute:'2-digit'}:{})});
const y=value=>180-value*16;
function scoreColor(value){if(value==null)return '#657565';const hue=value<=5?value*8:40+(value-5)*17;return `hsl(${hue} 65% 36%)`;}
function points(key){const rows=filtered.value;if(!rows.length)return [];const start=+instant(rows[0].scheduledStartAt),range=+instant(rows.at(-1).scheduledStartAt)-start;return rows.filter(r=>r.score[key]!=null).map(r=>({id:r.id,date:r.scheduledStartAt,value:r.score[key],x:range?42+(+instant(r.scheduledStartAt)-start)/range*536:310,y:y(r.score[key])}));}
function latest(key){return [...filtered.value].reverse().find(v=>v.score[key]!=null)?.score[key]??null;}
function answer(v,f,q){const raw=v.answers?.[f.id]?.[q.id];return raw==null?'Not answered':q.options?.find(o=>o.value===raw)?.label||String(raw);}
async function load(){const request=++version;visits.value=[];loading.value=true;error.value='';try{const {data}=await api.get(`/kiosk/client-feedback/${props.clientId}`);if(request!==version)return;visits.value=data.visits||[];if(!services.value.includes(service.value))service.value=services.value[0]||'counseling';}catch{if(request===version)error.value='Feedback is unavailable. Only the assigned provider can view these attached check-ins.';}finally{if(request===version)loading.value=false;}}
watch(respondents,list=>{if(!list.includes(respondent.value))respondent.value=list[0]||'adult_self';});watch(()=>props.clientId,load,{immediate:true});onUnmounted(()=>{version++;visits.value=[];});
</script>
<style scoped>.feedback-trends{padding:20px;border:1px solid #dae4d9;border-radius:16px;margin-bottom:28px;background:#fbfcf8;color:#264539}header{display:flex;justify-content:space-between;gap:18px}h3{margin:0}p{line-height:1.6}.controls{display:flex;gap:18px;flex-wrap:wrap}label{display:grid;gap:6px}select,button{font:inherit;padding:10px;border:1px solid #c7d7c5;border-radius:8px;background:white;color:inherit}.method{font-size:12px;color:#61715d}.charts{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:15px}.charts article{padding:15px;border:1px solid #dce4dc;border-radius:12px;background:white}.charts h4{margin:0 0 12px}.latest{font-size:29px}.latest small{font-size:14px;font-weight:400;color:#61715d}svg{display:block;width:100%;margin-top:12px}.legend{display:flex;align-items:center;gap:12px;font-size:11px;margin:18px 0}.legend div{flex:1;height:8px;border-radius:5px;background:linear-gradient(90deg,#bc3030,#bb850e,#23833d)}details{border-top:1px solid #dce4dc;padding:14px 0}summary{cursor:pointer}dt{font-weight:600;margin-top:12px}dd{margin:7px 0} @media(max-width:1050px){.charts{grid-template-columns:1fr}.charts svg{max-height:220px}.legend{flex-wrap:wrap}}</style>
