<template><section class="checkin-inbox">
 <header><div><h2>Recurring check-ins</h2><p>Visits collect by provider, office, weekday, and appointment time. Review who each visit belongs to before attaching it to a client.</p></div><button @click="load">Refresh</button></header>
 <p v-if="error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><p v-if="loading">Loading check-ins…</p><p v-else-if="!rows.length">No check-ins yet. New arrivals will appear here in groups such as Tuesday · 4:00 PM.</p><p v-if="truncated">Showing the latest 2,000 visits.</p>
 <article v-for="group in groups" :key="group.key"><button class="visit" @click="openGroup(group)"><strong>{{group.label}}</strong><span>{{group.rows[0].location_name}} · {{group.rows.length}} {{group.rows.length===1?'visit':'visits'}} · {{group.rows.filter(r=>!r.client_id).length}} awaiting attachment</span><span>View dates, feedback, and client attachments</span></button>
 <div v-if="activeGroup===group.key" class="details">
  <p>A recurring time is a filing group, not proof of identity. Self and dependent responses remain labeled separately. Future anonymous visits will still need review.</p>
  <button @click="checkedIds=group.rows.filter(r=>!r.client_id).slice(0,200).map(r=>r.id)">Select unattached visits</button><button @click="checkedIds=[]">Clear selection</button>
  <section v-for="row in group.rows" :key="row.id" class="dated-visit">
   <label class="check"><input v-model="checkedIds" type="checkbox" :value="row.id" :disabled="!!row.client_id"/><strong>{{when(row.scheduled_start_at,row.timezone)}}</strong></label>
   <p>{{row.forms_json.respondentType==='caregiver'?'Dependent / caregiver response':row.forms_json.respondentType==='youth_self'?'Self response · Under 18':'Self response'}} · {{row.client_id?`Attached: ${clientLabel(row)}`:'Not attached to a client'}} · {{formStatus(row)}}</p>
   <button @click="selected=selected?.id===row.id?null:row">{{selected?.id===row.id?'Hide':'View'}} responses / session</button>
   <div v-if="selected?.id===row.id"><p v-if="row.forms_unavailable">Some configured forms were unavailable.</p><div v-for="form in row.forms_json.forms" :key="form.id"><h3>{{form.title}}</h3><p v-if="form.validated===false">Service feedback · No validated score</p><p v-if="row.skipped_form_ids?.includes(form.id)">Skipped by respondent</p><dl v-else><template v-for="field in form.fields" :key="field.id"><dt>{{field.label}}</dt><dd>{{answer(row,form,field)}}</dd></template></dl></div>
    <p>To attach this visit individually or link it to a session, choose a client below.</p>
   </div>
  </section>
  <div class="attachment"><h3>Attach reviewed visits</h3><p>{{checkedIds.length}} selected. Original dates, wording, and responses are preserved.</p>
   <label>Find a client on your caseload<input v-model="query" placeholder="Name, initials, or client code" @input="search(group.rows[0])"/></label><select v-model="clientId" aria-label="Client to attach" @change="loadSessions(group.rows[0])"><option value="">Choose a client</option><option v-for="client in clients" :key="client.id" :value="client.id">{{clientLabel(client)}}</option></select>
   <button :disabled="!clientId||!checkedIds.length||saving" @click="attachGroup">{{saving?'Saving…':'Attach selected visits to client'}}</button>
   <template v-if="selected"><label>Session for {{when(selected.scheduled_start_at,selected.timezone)}} (optional)<select v-model="sessionId"><option value="">Client only</option><option v-for="s in sessions" :key="s.id" :value="s.id">{{when(s.scheduled_start_at,selected.timezone)}}</option></select></label><button :disabled="!clientId||saving" @click="attachOne">Attach this individual visit / session</button></template>
   <button v-if="!createOpen" @click="createOpen=true">Create a new client from this group</button>
   <form v-else @submit.prevent="createClient(group)"><h3>New client · {{group.label}}</h3><p>The selected visit history carries this office, weekday, and time into the client record. Complete the client’s remaining intake afterward.</p><label>Client’s full name<input v-model="newName" required maxlength="200" autocomplete="off"/></label><label>Initials<input v-model="newInitials" required maxlength="12" autocomplete="off"/></label><label class="check"><input v-model="reviewed" type="checkbox" required/>I reviewed the selected dates and confirmed these visits belong to this person.</label><button :disabled="saving||!checkedIds.length||!reviewed">Create client & attach selected visits</button><button type="button" @click="createOpen=false">Cancel</button></form>
   <router-link :to="createClientTo">Open full client onboarding</router-link>
  </div>
 </div></article></section></template>
<script setup>
import {ref,computed,onMounted,onUnmounted} from 'vue';import api from '../../services/api';import {useAuthStore} from '../../store/auth';
defineProps({createClientTo:{type:[String,Object],required:true}});const auth=useAuthStore();
const rows=ref([]),loading=ref(false),truncated=ref(false),error=ref(''),notice=ref(''),activeGroup=ref(''),selected=ref(null),checkedIds=ref([]),query=ref(''),clients=ref([]),clientId=ref(''),sessions=ref([]),sessionId=ref(''),saving=ref(false),createOpen=ref(false),newName=ref(''),newInitials=ref(''),reviewed=ref(false);
let searchTimer,version=0,disposed=false;
const groups=computed(()=>{const map=new Map();for(const row of rows.value){const s=row.series||{key:String(row.id),label:'Appointment'};if(!map.has(s.key))map.set(s.key,{...s,rows:[]});map.get(s.key).rows.push(row);}return [...map.values()];});
const clientLabel=c=>c.full_name||c.initials||c.identifier_code||`Client ${c.client_id||c.id}`;
const when=(v,tz)=>v?new Date(/[zZ]|[+-]\d\d:\d\d$/.test(v)?v:String(v).replace(' ','T')+'Z').toLocaleString('en-US',{timeZone:tz||'America/Denver',month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'}):'Unscheduled';
function answer(row,form,field){const v=row.answers_json?.[form.id]?.[field.id];return v==null?'Not answered':Array.isArray(v)?v.map(x=>field.options?.find(o=>o.value===x)?.label||x).join(', '):typeof v==='boolean'?(v?'Yes':'No'):field.options?.find(o=>o.value===v)?.label||String(v);}
function formStatus(row){if(!row.completed_at)return row.forms_json.forms.length?'Feedback not completed':'Arrival recorded';return row.skipped_form_ids?.length===row.forms_json.forms.length?'Questionnaires skipped':'Feedback saved';}
async function load(){loading.value=true;try{const {data}=await api.get('/kiosk/client-checkins');if(!disposed){rows.value=data.submissions||[];truncated.value=!!data.truncated;}}catch{error.value='Check-ins could not load.';}finally{loading.value=false;}}
function openGroup(group){version++;clearTimeout(searchTimer);activeGroup.value=activeGroup.value===group.key?'':group.key;selected.value=null;checkedIds.value=[];query.value='';clients.value=[];clientId.value='';sessions.value=[];sessionId.value='';createOpen.value=false;newName.value='';newInitials.value='';reviewed.value=false;error.value='';notice.value='';}
function search(row){const request=++version;clearTimeout(searchTimer);clients.value=[];clientId.value='';sessionId.value='';sessions.value=[];if(query.value.trim().length<2)return;const q=query.value;searchTimer=setTimeout(async()=>{try{const {data}=await api.get(`/kiosk/client-checkins/${row.id}/clients`,{params:{q}});if(request===version&&!disposed)clients.value=data.clients||[];}catch{if(request===version)error.value='Client search could not load.';}},250);}
async function loadSessions(row){const request=++version;sessions.value=[];sessionId.value='';if(!clientId.value)return;try{const {data}=await api.get(`/kiosk/client-checkins/${row.id}/sessions`,{params:{clientId:clientId.value}});if(request===version&&!disposed)sessions.value=data.sessions||[];}catch{error.value='Sessions could not load. You can still attach to the client.';}}
async function saveGroup(){await api.patch('/kiosk/client-checkins/series-attachment',{ids:checkedIds.value,clientId:Number(clientId.value)});notice.value=`${checkedIds.value.length} visits attached to the client.`;checkedIds.value=[];await load();}
async function attachGroup(){saving.value=true;error.value='';try{await saveGroup();}catch(e){error.value=e.response?.data?.error?.message||'Attachment could not be saved.';}finally{saving.value=false;}}
async function attachOne(){saving.value=true;error.value='';try{await api.patch(`/kiosk/client-checkins/${selected.value.id}/attachment`,{clientId:Number(clientId.value),sessionId:sessionId.value||null});selected.value=null;checkedIds.value=[];await load();}catch(e){error.value=e.response?.data?.error?.message||'Attachment could not be saved.';}finally{saving.value=false;}}
async function createClient(group){if(saving.value)return;saving.value=true;error.value='';try{const agency=group.rows[0].agency_id;const selectedVisits=group.rows.filter(row=>checkedIds.value.includes(row.id));const tutoring=selectedVisits.length>0&&selectedVisits.every(row=>row.forms_json?.serviceType==='tutoring');const {data}=await api.post('/clients',{organization_id:agency,agency_id:agency,serviceType:tutoring?'tutoring':'counseling',client_type:tutoring?'learning':'clinical',provider_id:auth.user.id,full_name:newName.value.trim(),initials:newInitials.value.trim(),submission_date:new Date().toISOString().slice(0,10),document_status:'NONE',source:'MANUAL'});const client=data.client||data;if(!client.id)throw Error('Missing client');clients.value=[client];clientId.value=client.id;createOpen.value=false;notice.value='Client created. Attaching the selected visits…';try{await saveGroup();}catch{error.value='The client was created, but the visits were not attached. Use Attach selected visits to retry; do not create another client.';}}catch(e){error.value=e.response?.data?.error?.message||'The client could not be created.';}finally{saving.value=false;}}
onMounted(load);onUnmounted(()=>{disposed=true;version++;clearTimeout(searchTimer);});
</script>
<style scoped>.checkin-inbox{padding:24px}header{display:flex;justify-content:space-between;gap:20px}p{line-height:1.6}article{border:1px solid #d5dfd6;border-radius:14px;margin:14px 0;overflow:hidden}.visit{display:grid;gap:8px;width:100%;text-align:left;border:0;background:#f3f6ef;padding:20px}.visit strong{font-size:20px}.visit span{font-size:13px}.details{padding:20px}.dated-visit{padding:18px 0;border-bottom:1px solid #d5dfd6}.dated-visit p{font-size:13px}.attachment{margin-top:25px;padding:20px;background:#f5f7f3;border-radius:12px}label{display:grid;gap:8px;margin:16px 0}.check{display:flex;align-items:center}.check input{width:20px;height:20px}input,select,button{font:inherit;padding:12px;border:1px solid #b9caba;border-radius:8px}button{cursor:pointer;margin:4px}button:disabled{opacity:.5}select{max-width:100%}dt{font-weight:600;margin-top:12px}dd{margin:6px 0;white-space:pre-wrap}a{display:inline-block;margin:15px}</style>
