<template><Teleport to="body"><div class="kiosk-shade" @keydown="keys"><section ref="panel" class="kiosk-dialog" role="dialog" aria-modal="true" :aria-label="title" tabindex="-1"><header><h2>{{title}}</h2><button class="dialog-close" aria-label="Close and return" @click="$emit('close')"><X :size="22"/></button></header><slot/></section></div></Teleport></template>
<script setup>
import {ref,onMounted,onUnmounted} from 'vue';import {X} from '@lucide/vue';defineProps({title:String});const emit=defineEmits(['close']);const panel=ref(null);let previous;
onMounted(()=>{previous=document.activeElement;panel.value?.focus();});onUnmounted(()=>previous?.focus?.());
function keys(e){if(e.key==='Escape')emit('close');if(e.key!=='Tab')return;const els=[...panel.value.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]')];if(!els.length){e.preventDefault();return;}if(e.shiftKey&&[els[0],panel.value].includes(document.activeElement)){e.preventDefault();els.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0].focus();}}
</script>
<style>
.kiosk-shade{position:fixed;inset:0;z-index:20000;background:#152f29a6;backdrop-filter:blur(5px);display:flex;align-items:center;justify-content:center;padding:22px}.kiosk-dialog{width:min(650px,100%);max-height:90dvh;overflow:auto;padding:28px;background:#fffef9;color:#24443d;border-radius:24px;box-shadow:0 20px 80px #0003;font-family:'Avenir Next',system-ui,sans-serif;box-sizing:border-box}.kiosk-dialog>header{display:flex;gap:16px;align-items:start;justify-content:space-between;margin-bottom:18px}.kiosk-dialog h2{font-size:25px;letter-spacing:-.5px;margin:0}.dialog-close{display:grid;place-items:center;flex-shrink:0;border:1px solid #d5dfcf;border-radius:50%;width:44px;height:44px;background:none;color:inherit;cursor:pointer}.kiosk-dialog p{line-height:1.65}.kiosk-dialog button:focus-visible,.kiosk-dialog input:focus-visible,.kiosk-dialog select:focus-visible,.kiosk-dialog textarea:focus-visible{outline:3px solid #b78432;outline-offset:3px}
</style>
