<template><KioskDialog title="Let’s help you find your appointment" @close="!saving && $emit('close')"><p>The kiosk is still being updated and improved. Your provider may still be at the office, even if your appointment isn’t listed.</p><p>Your message stays in the secure app. Your company’s support team and the provider you choose will receive it.</p><form @submit.prevent="send"><label>Company<select v-model="agencyId" required @change="providerId='' "><option value="">Choose your company</option><option v-for="a in agencies" :key="a.id" :value="String(a.id)">{{a.name}}</option></select></label><label>Who are you here to see?<select v-model="providerId" required :disabled="!agencyId"><option value="">Choose your provider</option><option v-for="p in providerOptions" :key="p.id" :value="String(p.id)">{{p.firstName}} {{p.lastName}}</option></select></label><label>How can we help?<textarea v-model="message" required maxlength="4000" rows="4" placeholder="For example: I’m here for my appointment, but I don’t see my provider."/></label><p class="support-note">Include a way for the team to reach you if needed. For urgent help, please ask the office team directly.</p><p v-if="error" role="alert">{{error}}</p><button class="support-send" :disabled="saving">{{saving?'Sending securely…':'Send secure message · Copy my provider'}}</button></form></KioskDialog></template>
<script setup>
import {computed,ref} from 'vue';import api from '../../services/api';import KioskDialog from './KioskDialog.vue';
const props=defineProps({locationId:[String,Number],people:Array,agencies:Array});const emit=defineEmits(['close','sent','busy']);
const agencyId=ref(''),providerId=ref(''),message=ref(''),saving=ref(false),error=ref('');const key=crypto.randomUUID();
const providerOptions=computed(()=>(props.people||[]).filter(p=>String(p.agencyId)===agencyId.value));
async function send(){if(saving.value)return;saving.value=true;emit('busy',true);error.value='';try{const {data}=await api.post(`/public/office-lobby/${props.locationId}/support`,{agencyId:Number(agencyId.value),providerId:Number(providerId.value),message:message.value,requestKey:key},{skipGlobalLoading:true});if(!data.ok)throw Error();message.value='';emit('sent');}catch(e){error.value=e.response?.data?.error?.message||'Your message could not be sent. Please try again or ask staff for help.';}finally{saving.value=false;emit('busy',false);}}
</script>
<style scoped>label{display:block;font-size:14px;font-weight:600;margin:18px 0}input,select,textarea{display:block;box-sizing:border-box;width:100%;font:inherit;padding:13px;border:1px solid #cbd8c5;border-radius:10px;background:white;margin-top:7px;color:#24443d}.support-note{font-size:12px;color:#6e7f6d}.support-send{width:100%;padding:15px;border:0;border-radius:12px;background:#315e49;color:white;font:inherit;cursor:pointer}</style>
