import { AURICWELL_MARK_URL, AURICWELL_PREVIEW_URL } from '../../constants/auricwellBrand.js';
import { CONVERSA_ASSET_REVISION } from '../../constants/conversa.js';
import { conversaFeature } from '../../conversa/website/feature.mjs';
import { homeStory, productStory } from './story.mjs';
import { faqSection } from './compare.mjs';
// Public content is rendered at build time. No clinical stores, cookies or API calls.
export const pages = {
  '': ['Less repeat work. More time for care.', 'AI-assisted documentation, treatment progress, supervision, client and guardian access, and connected practice workflows for therapy teams.'],
  product: ['The work of care, connected.', 'Explore guided AI documentation, treatment-goal history, supervision, guardian access, enrollment and connected care workflows in AuricWell.'],
  security: ['Trust starts with clear boundaries.', 'Learn how the AuricWell preview scopes practice records, identifies administrators and separates public information from clinical work.'],
  about: ['Built around the work you do.', 'AuricWell is a focused EHR experience for therapy practices, starting with Colorado therapy workflows.'],
  contact: ['Let’s talk about your practice.', 'Discuss AuricWell, your therapy practice and what you need from an EHR.']
};
const paths = {
 calendar: '<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18"/>',
 note: '<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9zM14 3v6h6M8 13h8M8 17h6"/>',
 people: '<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5"/>',
 shield: '<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z"/><path d="m8 12 3 3 5-6"/>',
 money: '<circle cx="12" cy="12" r="9"/><path d="M15 8h-4a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4H9m3-10v2m0 8v2"/>',
 arrows: '<path d="M4 7h15m-4-4 4 4-4 4M20 17H5m4-4-4 4 4 4"/>',
 home: '<path d="m3 10 9-7 9 7M5 9v12h5v-7h4v7h5V9"/>',
 check: '<path d="m5 12 4 4L19 6"/>',
 arrow: '<path d="M4 12h16m-6-6 6 6-6 6"/>',
 lock: '<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 4v3"/>',
 message: '<path d="M21 15a3 3 0 0 1-3 3H8l-5 3V6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3zM7 8h10M7 12h7"/>'
};
const icon = (key) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[key] || paths.note}</svg>`;
const esc = (s) => String(s).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const brand = `<span class="brand"><span class="brand-image"><img src="${AURICWELL_MARK_URL}" alt="" width="48" height="48"></span><span>AuricWell</span></span>`;
const feature = (i, title, text, gold = false) => `<article class="feature"><span class="icon ${gold ? 'gold' : ''}">${icon(i)}</span><h3>${title}</h3><p>${text}</p></article>`;
const pill = (text) => `<span class="pill">${icon('check')}${text}</span>`;
function preview() {
 return `<figure class="app-screenshot"><a href="/auricwell/examples/practice-notes.png" target="_blank" rel="noopener" aria-label="View the actual Practice Notes screen at full size"><img src="/auricwell/examples/practice-notes.png" alt="Actual Practice Notes workspace with its Note Library, note-writing area and Work queue, populated with synthetic records." width="1440" height="1000" fetchpriority="high"></a><figcaption>Actual Practice Notes screen · Synthetic example records · <a href="/auricwell/examples/practice-notes.png" target="_blank" rel="noopener">View full size ↗</a></figcaption></figure>`;
}

export function renderWebsite(section = '', { base = '', email = '' } = {}) {
 const found = Object.hasOwn(pages, section), page = found ? pages[section] : ['Page not found.', 'This page is not available.'];
 const url = (path = '') => `${base}/${path}`.replace(/\/$/, '') || '/';
 const link = (path, label, cls = 'button') => `<a class="${cls}" href="${url(path)}">${label}${icon('arrow')}</a>`;
 const hero = (eyebrow, title, text, visual = '', actions = true) => `<section class="hero ${visual?'split':''}"><div class="hero-copy"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${text}</p>${actions?`<div class="actions">${link('contact','Talk with us')}${link('demo','Try the working demo','button secondary')}</div>`:''}</div>${visual}</section>`;
 const nav = [['','Home'],['product','Product'],['security','Security'],['about','About'],['contact','Contact']].map(([p,label])=>`<a href="${url(p)}" ${section===p?'aria-current="page"':''}>${label}</a>`).join('');
 const availability = `<aside class="availability"><span class="status-dot"></span><div><strong>Explore the workflow. Plan your rollout.</strong><p>Explore the AuricWell administrator preview and the capabilities of our shared care platform. Feature access depends on your practice’s plan, configuration and rollout readiness.</p></div>${link('product#availability','See availability','text-link')}</aside>`;
 let content = '';
 if (section === '') content = homeStory({hero,feature,link,pill,preview,availability});
 if (section === 'product') content = productStory({hero,feature,link,preview});
 if (['','product'].includes(section)) {
   const demoSection = `<section class="section tinted" id="working-demo"><div class="section-heading"><div><p class="eyebrow">TAKE A LOOK AROUND</p><h2>A fictional practice.<br> The actual workspace.</h2></div><p>Try the same calendar, charts, provider directory, Practice Notes and billing components used in our app. Explore at your own pace—no account needed.</p></div><div data-actual-example="workspace"><p><a href="${url('demo')}">Open the working AuricWell demo →</a></p></div></section>`;
   const heroEnd = content.indexOf('</section>') + '</section>'.length;
   content = content.slice(0,heroEnd) + demoSection + content.slice(heroEnd);
 }
 if (['', 'product'].includes(section)) content += conversaFeature({product:'auricwell'});
 if (section === 'security') content = `${hero('SECURITY & PRACTICE ACCESS','Trust starts with<br> <em>clear boundaries.</em>','Clinical work belongs in an authorized practice workspace. Here is how the current preview handles access, and what remains part of launch readiness.',`<div class="security-visual"><span class="icon large gold">${icon('shield')}</span><h2>The right context<br> for every record.</h2><div>${pill('Identified administrator')}${pill('Selected practice')}${pill('Server-checked access')}</div></div>`,false)}<section class="section"><div class="features security-features">${feature('people','Practice boundaries','The backend checks the selected practice and record ownership. Matching names do not automatically combine charts from different practices.')}${feature('lock','Visible identity','The preview requires an active superadmin account. It shows the actual administrator and attributes saved draft changes to that person.')}${feature('note','A limited preview','Raw uploads, clinical signing and financial changes are blocked in the preview while the complete workflows are validated.',true)}</div></section><section class="section tinted"><p class="eyebrow">BEFORE A CUSTOMER LAUNCH</p><h2>Readiness is more than a login.</h2><div class="two-columns"><article><h3>Accounts and permissions</h3><p>Separate AuricWell credentials, staff authenticator MFA, recovery codes and patient access controls remain part of the launch plan. The current administrator preview uses the existing PlotTwist HQ account.</p></article><article><h3>Agreements and processing</h3><p>Practice agreements, the BAA and applicable vendor arrangements need review before production use. AI and transcription must be enabled only for configured services with applicable agreements and consent controls.</p></article></div></section><section class="section narrow"><p class="eyebrow">LET’S BE SPECIFIC</p><h2>Questions about your requirements?</h2><p>Talk with us about access, documentation, agreements and your practice’s review process. We do not present a product design or this website as a security certification.</p>${link('contact','Discuss your requirements','text-link')}</section>`;
 if (section === 'about') content = `${hero('WHY AURICWELL','Built around<br> the work <em>you do.</em>','Therapy is personal. The software around it should make room for attention, judgment and a practice’s everyday rhythm.',`<div class="about-visual"><span class="eyebrow">OUR APPROACH</span><p>Keep care<br> at the center.</p><span class="about-rule"></span><span>Make the work around it clearer.</span></div>`,false)}<section class="section"><div class="features">${feature('note','Depth where it matters','Preserve the clinical writing tools and workflows that work. Refine the interface around them.')}${feature('people','A focused experience','Give therapy teams a workspace centered on EHR needs, with practice names and consistent AuricWell presentation.')}${feature('arrows','A considered rollout','Validate the full practice workflow before a replacement launch. Preview access is one step in that process.',true)}</div></section><section class="section tinted"><div class="two-columns"><div><p class="eyebrow">STARTING WITH COLORADO THERAPY</p><h2>Specific needs.<br> Thoughtful defaults.</h2></div><div><p>Our initial focus is Colorado therapy practices, from solo owners to clinical teams. Clinical credentials, practice permissions and billing identities are distinct parts of the workflow.</p><p>State and payer requirements need explicit configuration. We are building toward a focused EHR that can expand without making every practice navigate a broader business suite.</p>${link('product','See the product direction','text-link')}</div></div></section>${availability}`;
 if (section === 'contact') content = `${hero('LET’S START A CONVERSATION','Let’s talk about<br> <em>your practice.</em>','Tell us how your team works and what you need from your EHR. We can discuss the current preview, your priorities and the path toward a practice rollout.','',false)}<section class="contact-layout"><article class="contact-card"><span class="icon gold">${icon('message')}</span><h2>A good place to begin.</h2><p>Share your practice name, your role, approximate team size and whether you are starting fresh or moving from another EHR.</p><p>Please leave patient details and clinical records out of website inquiries.</p>${email?`<a class="button" href="mailto:${esc(email)}?subject=AuricWell%20practice%20inquiry">Email the AuricWell team ${icon('arrow')}</a><p class="email-address">${esc(email)}</p><small>Opens your email application. Nothing is submitted through this website.</small>`:`<p>Public demo booking is not open yet. Existing administrators can explore the workspace using their authorized account.</p>${link('app/login','Open the preview')}`}</article><div class="contact-steps"><p class="eyebrow">WHAT WE CAN TALK THROUGH</p>${[['01','Your everyday workflow','Documentation, supervision and the practical work of your team.'],['02','Your starting point','A new practice or the records and history you need to bring with you.'],['03','Your rollout requirements','Agreements, integrations, training and the workflows that must be ready.']].map(([n,t,d])=>`<article><span class="number">${n}</span><div><h3>${t}</h3><p>${d}</p></div></article>`).join('')}</div></section>${faqSection()}`;
 if (!found) content = hero('AURICWELL','Page not found.','The page may have moved. Return to the website to find your way.', '', false) + `<div class="actions">${link('','Return home')}</div>`;
 const canonical = `https://plottwisthq.com/auricwell${section ? `/${section}` : ''}`;
 return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><link rel="stylesheet" href="/assets/conversa/feature.css?v=${CONVERSA_ASSET_REVISION}"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(found && !section?'AuricWell | A focused EHR for therapy practices':`${page[0]} | AuricWell`)}</title><meta name="description" content="${esc(page[1])}">${!found?'<meta name="robots" content="noindex">':''}<link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="website"><meta property="og:site_name" content="AuricWell"><meta property="og:title" content="${esc(page[0])}"><meta property="og:description" content="${esc(page[1])}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="https://plottwisthq.com${AURICWELL_PREVIEW_URL}"><meta name="theme-color" content="#ffffff"><link rel="icon" type="image/svg+xml" href="${AURICWELL_MARK_URL}"><link rel="stylesheet" href="/auricwell/website.css">${['','product'].includes(section) ? '<link rel="stylesheet" href="/auricwell/website-demo.css">' : ''}</head><body><a href="#main" class="skip-link">Skip to content</a><header class="site-header"><div class="header-inner"><a href="${url()}" aria-label="AuricWell home">${brand}</a><nav class="desktop-nav" aria-label="Main navigation">${nav}</nav><a class="button sign-in" href="${url('app/login')}">Sign in ${icon('arrow')}</a><details class="mobile-menu"><summary aria-label="Open navigation">Menu</summary><nav aria-label="Mobile navigation">${nav}</nav></details></div></header><main id="main">${content}${found&&section!=='contact'?`<section class="cta"><div><p class="eyebrow">A LITTLE MORE CLARITY. A LITTLE MORE SPACE.</p><h2>Make room for what matters.</h2></div>${link('contact','Let’s talk about your practice','button white')}</section>`:''}</main><footer class="site-footer"><a href="https://plottwisthq.com/records-request">Request my records</a><div><a href="${url()}" aria-label="AuricWell home">${brand}</a><p>Thoughtful tools for the work of care.</p><p>A <a href="https://plottwistco.com/products#auricwell">Plot Twist Co. product</a>.</p></div><nav aria-label="Footer navigation">${nav}<a href="${url('product#compare')}">Compare EHRs</a><a href="${url('product#faq')}">FAQs</a></nav><div class="footer-bottom"><small>© ${new Date().getUTCFullYear()} AuricWell</small><small>Starting with Colorado therapy practices · Currently in preview</small></div></footer>${['','product'].includes(section) ? '<script type="module" src="/auricwell/website-demo.js"></script>' : ''}</body></html>`;
}
