// Public content is rendered at build time. No clinical stores, cookies or API calls.
export const pages = {
  '': ['A little more room for care.', 'A focused EHR for therapy practices. Explore AuricWell’s approach to clinical documentation, practice workflows and thoughtful onboarding.'],
  product: ['The work of care, connected.', 'Explore AuricWell’s clinical workspace, shared Note Aid, practice records and billing preview, with a clear view of what is coming next.'],
  security: ['Trust starts with clear boundaries.', 'Learn how the AuricWell preview scopes practice records, identifies administrators and separates public information from clinical work.'],
  about: ['Built around the work you do.', 'AuricWell is a focused EHR experience for therapy practices, starting with Colorado therapy workflows.'],
  contact: ['Let’s talk about your practice.', 'Discuss AuricWell, your therapy practice and what you need from an EHR.']
};
const paths = {
 calendar: '<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M7 3v4m10-4v4M3 11h18"/>',
 note: '<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9zM14 3v6h6M8 13h8M8 17h6"/>',
 people: '<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m2 4a5 5 0 0 1 3 5"/>',
 shield: '<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z"/><path d="m8 12 3 3 5-6"/>',
 money: '<circle cx="12" cy="12" r="9"/><path d="M15 8h-4a2 2 0 0 0 0 4h2a2 2 0 0 1 0 4H9m3-10v2m0 8v2"/>',
 arrows: '<path d="M4 7h15m-4-4 4 4-4 4M20 17H5m4-4-4 4 4 4"/>',
 home: '<path d="m3 10 9-7 9 7M5 9v12h5v-7h4v7h5V9"/>',
 check: '<path d="m5 12 4 4L19 6"/>',
 arrow: '<path d="M4 12h16m-6-6 6 6-6 6"/>',
 lock: '<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 4v3"/>',
 message: '<path d="M21 15a3 3 0 0 1-3 3H8l-5 3V6a3 3 0 0 1 3-3h12a3 3 0 0 1 3 3zM7 8h10M7 12h7"/>'
};
const icon = (key) => `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[key] || paths.note}</svg>`;
const esc = (s) => String(s).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
const brand = '<span class="brand"><span class="brand-image"><img src="/auricwell/logo.png" alt="" width="136" height="52"></span><span>AuricWell</span></span>';
const feature = (i, title, text, gold = false) => `<article class="feature"><span class="icon ${gold ? 'gold' : ''}">${icon(i)}</span><h3>${title}</h3><p>${text}</p></article>`;
const pill = (text) => `<span class="pill">${icon('check')}${text}</span>`;
function preview() {
 return `<figure class="preview"><div class="preview-top"><span class="preview-brand">AuricWell<span class="gold-dot"></span></span><span>Example practice</span><span class="avatar">AW</span></div><div class="preview-body"><div class="preview-sidebar" aria-hidden="true">${[['home','Home'],['calendar','Schedule'],['people','Clients'],['note','Note Aid'],['money','Billing']].map(([i,n])=>`<span class="${n==='Note Aid'?'selected':''}">${icon(i)}${n}</span>`).join('')}<span class="sidebar-bottom">Space for better care.</span></div><div class="preview-main"><div class="preview-heading"><div><small>DOCUMENTATION</small><h3>A clear place to start.</h3></div><span class="preview-tag">Draft</span></div><div class="note-preview"><div class="drafts"><strong>Your drafts <span>2</span></strong><div class="draft active">Progress note<small>Today · Individual therapy</small></div><div class="draft">Treatment plan<small>Ready to continue</small></div></div><div class="sample-note"><span class="mini-label">PROGRESS NOTE</span><h4>Care in your own words.</h4><p>Session focus</p><div class="text-line"></div><div class="text-line"></div><div class="text-line short"></div><p>Interventions &amp; response</p><div class="text-line"></div><div class="text-line short"></div><div class="review-label">${icon('check')} Clinician review comes first</div></div></div><div class="preview-bottom">Your drafts. Your clinical judgment.<span>Note Aid</span></div></div></div><figcaption>Illustrative workspace · Sample content only</figcaption></figure>`;
}
export function renderWebsite(section = '', { base = '', email = '' } = {}) {
 const found = Object.hasOwn(pages, section), page = found ? pages[section] : ['Page not found.', 'This page is not available.'];
 const url = (path = '') => `${base}/${path}`.replace(/\/$/, '') || '/';
 const link = (path, label, cls = 'button') => `<a class="${cls}" href="${url(path)}">${label}${icon('arrow')}</a>`;
 const hero = (eyebrow, title, text, visual = '', actions = true) => `<section class="hero ${visual?'split':''}"><div class="hero-copy"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1><p class="lead">${text}</p>${actions?`<div class="actions">${link('contact','Talk with us')}${link('product','Explore AuricWell','button secondary')}</div>`:''}</div>${visual}</section>`;
 const nav = [['','Home'],['product','Product'],['security','Security'],['about','About'],['contact','Contact']].map(([p,label])=>`<a href="${url(p)}" ${section===p?'aria-current="page"':''}>${label}</a>`).join('');
 const availability = `<aside class="availability"><span class="status-dot"></span><div><strong>A focused preview, with more ahead.</strong><p>Today, authorized administrators can explore existing practice records, Note Aid drafts and billing views. New-practice setup, migration, patient access and live transactions are still in development.</p></div>${link('product#availability','See availability','text-link')}</aside>`;
 let content = '';
 if (section === '') content = `${hero('BUILT FOR THERAPY PRACTICES','A little more<br> room for <em>care.</em>','A calmer place for the work around therapy. AuricWell brings a focused clinical workspace to the people who care for others.',preview())}<div class="proof-row">${pill('Therapy comes first')}${pill('Clear, focused workflows')}${pill('Your practice, connected')}</div><section class="section"><div class="section-heading"><p class="eyebrow">LESS FRICTION. MORE FOCUS.</p><h2>The essentials,<br> with room to breathe.</h2><p>From preparing for a session to picking up a draft, your workspace should help you find the next step.</p></div><div class="features">${feature('calendar','A view of your day','Review upcoming appointments alongside the clients and providers in your practice.')}${feature('note','Notes that stay yours','Work with Note Aid and existing drafts while keeping your clinical judgment at the center.')}${feature('money','A clearer financial picture','Review existing billing, claim and remittance information in your practice workspace.',true)}</div></section><section class="path-section"><div><p class="eyebrow">YOUR PRACTICE. YOUR STARTING POINT.</p><h2>A fresh start.<br> Or a thoughtful move.</h2><p>Two different beginnings deserve two different onboarding paths. Both are part of the roadmap.</p>${link('product#onboarding','Explore the approach','text-link')}</div><div class="path-card"><span class="number">01</span><h3>Starting a practice</h3><p>Set up your team, services and forms. No historical records or migration files should stand in your way.</p><span class="quiet-tag">Planned onboarding</span></div><div class="path-card"><span class="number gold-text">02</span><h3>Moving from TherapyNotes</h3><p>A guided path for reviewed staff, payer and billing exports, with historical documents and reconciliation.</p><span class="quiet-tag">Planned migration</span></div></section>${availability}`;
 if (section === 'product') content = `${hero('THE AURICWELL WORKSPACE','The work of care,<br> <em>connected.</em>','Clients, documentation and practice information deserve a place that feels organized. AuricWell starts with the clinical tools you already use.',preview())}<section class="section"><div class="section-heading"><p class="eyebrow">AT THE CENTER: YOUR CLINICAL WORK</p><h2>Your notes.<br> Your way of thinking.</h2><p>Note Aid remains the writing workspace: drafts on the left, the work queue and supervision view on the right. Open a note and both sides collapse so you can focus.</p></div><div class="features">${feature('note','Continue where you left off','Open and save existing drafts, with your own authorship preserved.')}${feature('people','One practice at a time','Clients, providers and documentation are scoped to the practice you opened.')}${feature('shield','A clinician’s decision','Assistance supports writing. It does not establish credentials, replace review or approve claims.',true)}</div></section><section class="section tinted" id="availability"><p class="eyebrow">PRODUCT AVAILABILITY</p><h2>A clear view of where we are.</h2><p class="section-intro">AuricWell is currently an administrator preview, not yet a replacement for a practice’s complete EHR workflow.</p><div class="availability-grid"><article><span class="quiet-tag">Available in the preview</span><h3>Explore existing practice work</h3><ul><li>Client charts and historical note views</li><li>Upcoming appointment and provider directories</li><li>Shared Note Aid drafts and editing</li><li>Billing, claim and remittance views</li><li>Visible superadmin identity and practice scope</li></ul></article><article><span class="quiet-tag gold-tag">In development</span><h3>Complete the care workflow</h3><ul><li>Practice onboarding and reviewed imports</li><li>Customer sign-in and authenticator MFA</li><li>Scheduling changes, signing and live billing</li><li>Patient and guardian forms, messages and video</li><li>Practice agreements and cutover reconciliation</li></ul></article></div></section><section class="section" id="onboarding"><p class="eyebrow">TWO PATHS INTO AURICWELL</p><h2>Begin from where you are.</h2><div class="two-columns"><article><h3>Start a new practice</h3><p>The planned setup covers legal identity, locations, providers, services, fees, payer configuration and agreements. New practices will not need historical data or migration completion.</p></article><article><h3>Move from TherapyNotes</h3><p>The planned migration uses exports you download yourself, with mapping, review and reconciliation. Provider lists, payers, billing reports and clinical PDFs each receive their own review steps. Direct TherapyNotes integration is outside the current scope.</p></article></div></section>`;
 if (section === 'security') content = `${hero('SECURITY & PRACTICE ACCESS','Trust starts with<br> <em>clear boundaries.</em>','Clinical work belongs in an authorized practice workspace. Here is how the current preview handles access, and what remains part of launch readiness.',`<div class="security-visual"><span class="icon large gold">${icon('shield')}</span><h2>The right context<br> for every record.</h2><div>${pill('Identified administrator')}${pill('Selected practice')}${pill('Server-checked access')}</div></div>`,false)}<section class="section"><div class="features security-features">${feature('people','Practice boundaries','The backend checks the selected practice and record ownership. Matching names do not automatically combine charts from different practices.')}${feature('lock','Visible identity','The preview requires an active superadmin account. It shows the actual administrator and attributes saved draft changes to that person.')}${feature('note','A limited preview','Raw uploads, clinical signing and financial changes are blocked in the preview while the complete workflows are validated.',true)}</div></section><section class="section tinted"><p class="eyebrow">BEFORE A CUSTOMER LAUNCH</p><h2>Readiness is more than a login.</h2><div class="two-columns"><article><h3>Accounts and permissions</h3><p>Separate AuricWell credentials, staff authenticator MFA, recovery codes and patient access controls remain part of the launch plan. The current administrator preview uses the existing PlotTwist HQ account.</p></article><article><h3>Agreements and processing</h3><p>Practice agreements, the BAA and applicable vendor arrangements need review before production use. AI and transcription must be enabled only for configured services with applicable agreements and consent controls.</p></article></div></section><section class="section narrow"><p class="eyebrow">LET’S BE SPECIFIC</p><h2>Questions about your requirements?</h2><p>Talk with us about access, documentation, agreements and your practice’s review process. We do not present a product design or this website as a security certification.</p>${link('contact','Discuss your requirements','text-link')}</section>`;
 if (section === 'about') content = `${hero('WHY AURICWELL','Built around<br> the work <em>you do.</em>','Therapy is personal. The software around it should make room for attention, judgment and a practice’s everyday rhythm.',`<div class="about-visual"><span class="eyebrow">OUR APPROACH</span><p>Keep care<br> at the center.</p><span class="about-rule"></span><span>Make the work around it clearer.</span></div>`,false)}<section class="section"><div class="features">${feature('note','Depth where it matters','Preserve the clinical writing tools and workflows that work. Refine the interface around them.')}${feature('people','A focused experience','Give therapy teams a workspace centered on EHR needs, with practice names and consistent AuricWell presentation.')}${feature('arrows','A considered rollout','Validate the full practice workflow before a replacement launch. Preview access is one step in that process.',true)}</div></section><section class="section tinted"><div class="two-columns"><div><p class="eyebrow">STARTING WITH COLORADO THERAPY</p><h2>Specific needs.<br> Thoughtful defaults.</h2></div><div><p>Our initial focus is Colorado therapy practices, from solo owners to clinical teams. Clinical credentials, practice permissions and billing identities are distinct parts of the workflow.</p><p>State and payer requirements need explicit configuration. We are building toward a focused EHR that can expand without making every practice navigate a broader business suite.</p>${link('product','See the product direction','text-link')}</div></div></section>${availability}`;
 if (section === 'contact') content = `${hero('LET’S START A CONVERSATION','Let’s talk about<br> <em>your practice.</em>','Tell us how your team works and what you need from your EHR. We can discuss the current preview, your priorities and the path toward a practice rollout.','',false)}<section class="contact-layout"><article class="contact-card"><span class="icon gold">${icon('message')}</span><h2>A good place to begin.</h2><p>Share your practice name, your role, approximate team size and whether you are starting fresh or moving from another EHR.</p><p>Please leave patient details and clinical records out of website inquiries.</p>${email?`<a class="button" href="mailto:${esc(email)}?subject=AuricWell%20practice%20inquiry">Email the AuricWell team ${icon('arrow')}</a><p class="email-address">${esc(email)}</p><small>Opens your email application. Nothing is submitted through this website.</small>`:`<p>Public demo booking is not open yet. Existing administrators can explore the workspace using their authorized account.</p>${link('app/login','Open the preview')}`}</article><div class="contact-steps"><p class="eyebrow">WHAT WE CAN TALK THROUGH</p>${[['01','Your everyday workflow','Documentation, supervision and the practical work of your team.'],['02','Your starting point','A new practice or the records and history you need to bring with you.'],['03','Your rollout requirements','Agreements, integrations, training and the workflows that must be ready.']].map(([n,t,d])=>`<article><span class="number">${n}</span><div><h3>${t}</h3><p>${d}</p></div></article>`).join('')}</div></section><section class="section narrow"><p class="eyebrow">COMMON QUESTIONS</p><h2>A few helpful answers.</h2>${[['Can I use AuricWell for a new practice?','New-practice onboarding is part of the plan and will not require migration files. The current release is an administrator preview of existing practice records.'],['Can I move from TherapyNotes?','Guided migration is planned using exports you download yourself. Staff, payer, billing and clinical document imports will require review and reconciliation before cutover.'],['Is pricing available?','Commercial terms will be configured before contracting. This website does not publish a price or require payment details.'],['Is AuricWell my care provider?','No. Your treating practice provides care. AuricWell provides the software experience.']].map(([q,a])=>`<details class="faq"><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</section>`;
 if (!found) content = hero('AURICWELL','Page not found.','The page may have moved. Return to the website to find your way.', '', false) + `<div class="actions">${link('','Return home')}</div>`;
 const canonical = `https://plottwisthq.com/auricwell${section ? `/${section}` : ''}`;
 return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(found && !section?'AuricWell | A focused EHR for therapy practices':`${page[0]} | AuricWell`)}</title><meta name="description" content="${esc(page[1])}">${!found?'<meta name="robots" content="noindex">':''}<link rel="canonical" href="${esc(canonical)}"><meta property="og:type" content="website"><meta property="og:site_name" content="AuricWell"><meta property="og:title" content="${esc(page[0])}"><meta property="og:description" content="${esc(page[1])}"><meta property="og:url" content="${esc(canonical)}"><meta property="og:image" content="https://plottwisthq.com/auricwell/logo.png"><meta name="theme-color" content="#ffffff"><link rel="icon" href="/auricwell/logo.png"><link rel="stylesheet" href="/auricwell/website.css"></head><body><a href="#main" class="skip-link">Skip to content</a><header class="site-header"><div class="header-inner"><a href="${url()}" aria-label="AuricWell home">${brand}</a><nav class="desktop-nav" aria-label="Main navigation">${nav}</nav><a class="button sign-in" href="${url('app/login')}">Sign in ${icon('arrow')}</a><details class="mobile-menu"><summary aria-label="Open navigation">Menu</summary><nav aria-label="Mobile navigation">${nav}</nav></details></div></header><main id="main">${content}${found&&section!=='contact'?`<section class="cta"><div><p class="eyebrow">A LITTLE MORE CLARITY. A LITTLE MORE SPACE.</p><h2>Make room for what matters.</h2></div>${link('contact','Let’s talk about your practice','button white')}</section>`:''}</main><footer class="site-footer"><div><a href="${url()}" aria-label="AuricWell home">${brand}</a><p>Thoughtful tools for the work of care.</p></div><nav aria-label="Footer navigation">${nav}</nav><div class="footer-bottom"><small>© ${new Date().getUTCFullYear()} AuricWell</small><small>Starting with Colorado therapy practices · Currently in preview</small></div></footer></body></html>`;
}
