import { PLAN_FEATURES, PLAN_TIERS } from '../../config/productPlanCatalog.js';

export function providerExample() {
 return `<section class="section provider-example tinted" id="provider-example"><div class="section-heading"><div><p class="eyebrow">THE PROVIDER FINDER, AS IT APPEARS IN THE APP</p><h2>Real availability controls.<br> A familiar first step.</h2></div><p>Explore the same provider cards used in the app: care focus, in-person or virtual availability, published openings and time requests. These examples use synthetic providers.</p></div><div data-actual-example="providers"><p>Loading the app’s provider cards…</p></div><noscript><p>Enable JavaScript to try the actual provider-card component with synthetic data. No appointment is created.</p></noscript></section>`;
}

function planSection() {
  const keys = ['ai_note_aid','client_records','clinical_signing','intake','client_portal','insurance_claims','video_meetings','supervision','recording_transcription','transcript_notes','calendar_sync','private_office','office_booking','multiple_office_guests'];
  const selected = PLAN_FEATURES.filter(f => f.products.includes('auricwell') && keys.includes(f.key));
  return `<section class="section" id="plans"><p class="eyebrow">AI DOCUMENTATION INCLUDED AS STANDARD</p><h2>One clinical foundation.<br> Room to add more.</h2><p class="section-intro">Core documentation, client records, intake and guardian access sit together. Premium adds transcription and a private virtual office; Premium Plus adds room reservations and multiple individually admitted office guests.</p><div class="plan-grid">${PLAN_TIERS.map((tier,i)=>`<article class="plan-card"><span class="number">0${i+1}</span><h3>${tier.name}</h3><p>${i===0?'The core clinical workflow.':i===1?'Everything in Basic, plus:':'Everything in Premium, plus:'}</p><ul>${selected.filter(f=>f.minimumTier===tier.id).map(f=>`<li>${f.label}</li>`).join('')}</ul></article>`).join('')}</div><p class="feature-note">Plan assignments follow the approved feature catalog. Shared features are assigned at practice level; private virtual offices are assigned to individual providers. Availability also depends on practice setup and rollout. Commercial terms are confirmed before contracting.</p></section>`;
}

function progressExample() {
 return `<div data-actual-example="goals"><p>Loading the app’s treatment-objective controls…</p></div>`;
}

export function homeStory({hero, feature, link, pill, preview, availability}) {
 return `${hero('AN EHR THAT CONNECTS THE WORK OF THERAPY','Less repeat work.<br> <em>More time for care.</em>','AI-assisted notes, guided documentation, treatment progress and supervision in one connected clinical workflow. Built to help providers move through their day and supervisors focus their attention.',preview())}
 <div class="proof-row">${pill('AI built into documentation')}${pill('Progress carried across visits')}${pill('A clearer supervision workflow')}</div>
 <section class="section"><div class="section-heading"><div><p class="eyebrow">INTELLIGENCE IN THE EVERYDAY DETAILS</p><h2>More than a place<br> to store a note.</h2></div><p>The value is in what connects: client check-ins inform the visit, treatment goals inform documentation, and the same clinical record supports review and billing.</p></div><div class="features">${feature('note','A faster path through a note','Start with guided steps, AI drafting and treatment context. Review the result in Practice Notes, with your drafts and work queue close at hand.')}${feature('people','Supervision with context','Bring the note, outstanding work and review status together. Direct attention to the items that need it, with signatures governed by the document and practice workflow.')}${feature('money','Safeguards before submission','Connect service details, documentation and claim readiness. Surface missing requirements before the next step instead of relying on a second manual checklist.',true)}</div>${link('product#documentation','Explore the clinical workflow','text-link')}</section>
 <section class="section tinted"><div class="section-heading"><div><p class="eyebrow">BEFORE, DURING AND AFTER THE VISIT</p><h2>A connected experience<br> for the whole care team.</h2></div><p>Client and guardian access, enrollment, check-in and virtual care belong alongside the clinical work they support.</p></div><div class="features">${feature('people','Clients and multiple guardians','Separate guardian relationships and access to the clients they are authorized to support. Keep families connected to forms, appointments and practice communications.')}${feature('calendar','Arrival, with useful context','Office kiosk check-in alerts the provider. Connection and progress feedback can make the next conversation more informed.')}${feature('message','A more personal virtual visit','Private virtual offices, waiting-room music and interactive session tools are part of the wider connected care experience.',true)}</div>${link('product#care-experience','Explore the care experience','text-link')}</section>
 ${providerExample()}
 <section class="path-section"><div><p class="eyebrow">YOUR PRACTICE. YOUR STARTING POINT.</p><h2>A fresh start.<br> Or a thoughtful transition.</h2><p>Start a new practice or plan a move from your current EHR. We review what your practice needs to bring across.</p>${link('product#onboarding','Explore the approach','text-link')}</div><div class="path-card"><span class="number">01</span><h3>Starting a practice</h3><p>Build around your providers, services, forms and clinical standards. No historical migration files should stand in your way.</p></div><div class="path-card"><span class="number gold-text">02</span><h3>Transitioning from your current EHR</h3><p>Review export formats, staff and payer records, billing history and clinical documents, then agree on a migration and reconciliation plan.</p><span class="quiet-tag">Import compatibility reviewed first</span></div></section>${availability}`;
}

export function productStory({hero, feature, link, preview}) {
 return `${hero('ONE CONNECTED CLINICAL WORKFLOW','Built to move<br> <em>care forward.</em>','Less re-entering. Less searching. More of the context providers and supervisors need, carried from enrollment through the visit, the note and the next review.',preview())}
 <nav class="product-jump" aria-label="Product sections"><a href="#documentation">Documentation</a><a href="#progress">Treatment progress</a><a href="#care-experience">Care experience</a><a href="#provider-example">Availability example</a><a href="#plans">Plans</a></nav>
 <section class="section" id="documentation"><div class="section-heading"><div><p class="eyebrow">PRACTICE NOTES · AI AT THE POINT OF WORK</p><h2>Go from a session<br> to a structured draft.</h2></div><p>AI assistance is built into the documentation workflow. Use clinical context and, where enabled with signed acknowledgement, session transcription to support a draft. The clinician reviews the content before signing.</p></div>
 <figure class="app-screenshot editor-screenshot"><a href="/auricwell/examples/note-editor.png" target="_blank" rel="noopener" aria-label="View the actual guided note editor at full size"><img src="/auricwell/examples/note-editor.png" alt="Actual Practice Notes editor after choosing an individual psychotherapy aid, showing service details and guided documentation controls with synthetic initials." loading="lazy" width="1392" height="1030"></a><figcaption>Actual guided note editor · Synthetic example data · <a href="/auricwell/examples/note-editor.png" target="_blank" rel="noopener">View full size ↗</a></figcaption></figure>
 <ol class="workflow-steps"><li><span>01</span><h3>Set the context</h3><p>Confirm the client, service, timing and treatment focus.</p></li><li><span>02</span><h3>Work through the sections</h3><p>Guided prompts organize interventions, response, progress and next steps.</p></li><li><span>03</span><h3>Generate and review</h3><p>Use AI to support the narrative, then check and edit the clinical content.</p></li><li><span>04</span><h3>Resolve what remains</h3><p>Complete the review, signature and billing requirements that apply.</p></li></ol>
 <div class="features">${feature('shield','Requirements in the workflow','Step-by-step documentation and content review help address configured audit and billing-manual requirements. Timing, service and claim checks support accuracy; they do not guarantee payment or an error-free note.')}${feature('note','Amend without losing history','Add addenda, corrections and late entries to signed notes while retaining the original. Corrections return to the appropriate review workflow.')}${feature('people','Supervision without the chase','Review-only workflows can avoid a separate supervisor cosign where configured. Documents and amendments that require approval remain in the supervision queue.',true)}</div>
 </section>
 <section class="section tinted" id="progress"><div class="story-split"><div><p class="eyebrow">A TREATMENT PLAN THAT STAYS IN THE CONVERSATION</p><h2>Your standards.<br> Your goals. A visible history.</h2><p>Configurable treatment-plan sections, goals, objectives and rating scales support the way your practice documents care. Carry that context into notes and retain historical objective ratings across visits.</p><p>At check-in, ask about connection with the provider and perceived treatment progress. Compare the latest response with earlier feedback, alongside the clinical goal history.</p><p class="feature-note">Custom feedback supports the conversation. It is distinct from a validated outcome measure and from the clinician’s assessment.</p></div>${progressExample()}</div></section>
 <section class="section" id="care-experience"><p class="eyebrow">CARE STARTS BEFORE THE NOTE</p><h2>Give every part of the visit<br> a place to connect.</h2><div class="features feature-grid-six">
 ${feature('people','Client and guardian access','Support clients and multiple guardians with distinct account relationships. Access follows authorization for each client, rather than giving every guardian the same unrestricted view.')}
 ${feature('note','Enrollment that fits your practice','Configurable enrollment links bring intake questions, digital forms and signed acknowledgements together. Shape the starting experience around the information your practice needs.')}
 ${feature('calendar','Kiosk check-in and arrival alerts','Let clients check in at the office and notify their provider that they have arrived. Include relevant check-in feedback so the visit can start with context.',true)}
 ${feature('message','Your own virtual office','A permanent provider office link and individual guest admission create a familiar place to meet. Premium supports one guest; Premium Plus supports additional individually admitted guests.')}
 ${feature('people','A more engaging virtual session','Waiting-room experiences include optional music. Shared session tools include games and whiteboard activities, with availability depending on the session type and enabled integrations.')}
 ${feature('lock','Transcription with acknowledgement','In-person and virtual transcription workflows use the applicable signed acknowledgements and recording controls. Turn authorized transcripts into summaries and draft documentation.',true)}
 </div><p class="feature-note">These capabilities span the shared care platform. Their availability in an AuricWell practice depends on the configured workflow, integrations and rollout; a private office guest is not automatically connected to a client chart.</p></section>
 ${providerExample()}${planSection()}
 <section class="section tinted" id="availability"><p class="eyebrow">FROM SHARED CAPABILITIES TO YOUR PRACTICE</p><h2>Plan the rollout around<br> the way you work.</h2><div class="two-columns"><article><h3>A clinical foundation already in use</h3><p>AuricWell uses the same underlying clinical records, documentation and billing services as the broader platform. The focused EHR experience brings those workflows together with AuricWell presentation.</p></article><article><h3>Confirm your practice’s readiness</h3><p>The administrator preview is not a full customer launch. Confirm enabled features, credentials, agreements, integrations and the complete patient-to-payment workflow before cutover. A plan assignment alone does not activate an integration.</p>${link('contact','Walk through your requirements','text-link')}</article></div></section>
 <section class="section" id="onboarding"><p class="eyebrow">TWO PATHS INTO AURICWELL</p><h2>Begin from where you are.</h2><div class="two-columns"><article><h3>Start a new practice</h3><p>Configure your team, locations, services, fees, forms and agreements. New-practice setup is designed to stand on its own without historical records or a migration requirement.</p></article><article><h3>Transition from your current EHR</h3><p>Start with an export review. Staff, client and payer records, clinical documents, billing history and opening balances need mapping, review and reconciliation. Supported files and the cutover approach are confirmed for your current system; automatic integration with every EHR is not assumed.</p></article></div></section>`;
}
