// Original website and coaching intake copy, based on the owner's supplied mockups.
// Seed once; later edits live in the marketing editor, document templates and package catalog.
export const kimiPackages = [
 {key:'clarity',name:'Clarity Session',subtitle:'One-session support',sessions:1,minutes:90,icon:'leaf',description:'A focused, one-time coaching session for immediate support, reflection, and direction.',items:['Clarify what matters most','Create an action plan you can use now','Email follow-up with key takeaways']},
 {key:'momentum',name:'Momentum Package',subtitle:'Short-term support',sessions:3,minutes:60,icon:'sun',description:'Build consistency, confidence, and forward movement with a short-term coaching package.',items:['Personalized goals and action steps','Accountability between sessions','Tools and practices for everyday progress']},
 {key:'transformation',name:'Transformation Package',subtitle:'Deeper, ongoing support',sessions:6,minutes:60,icon:'mountain',description:'A comprehensive coaching experience for growth, accountability, and lasting change.',items:['Personalized plan and milestone tracking','Email support between sessions','Mindset and habit-building strategies','Tools and resources for lasting change']},
 {key:'accountability',name:'Accountability Check-In',subtitle:'Light-touch support',sessions:1,minutes:30,icon:'heart',description:'Ongoing encouragement to help you stay on track and keep making progress.',items:['A quick reset and momentum boost','Accountability and encouragement','Flexible support as needed']}
];
export const kimiWebsite = {
 version:1, practiceName:'Kimi Cain Life Coaching', providerName:'Kimi Cain', credential:'Certified Life Coach',
 portraitUrl:'/assets/kimi/portrait.png', squareUrl:'/assets/kimi/kimi-square.png', mountainUrl:'/assets/kimi/mountains.png',
 pages:{
 home:{eyebrow:'Your next chapter starts here',title:'More Clarity.\nBrighter Days.',subtitle:'Real connection. Meaningful progress.',body:'You don’t have to figure it out alone. I’m Kimi Cain, a certified life coach helping adults navigate change, rediscover their strengths, and move toward a life that feels meaningful and aligned.'},
 about:{eyebrow:'About Kimi Cain',title:'People First.\nProgress Always.',subtitle:'Your story matters. So does your next step.',body:'I believe in the power of people — their resilience, their potential, and their ability to create meaningful change. My purpose is to walk alongside you as you gain clarity, build confidence, and move toward the life you want.'},
 services:{eyebrow:'Support for your season',title:'Services & Support',subtitle:'Helping you move forward with clarity and confidence.',body:'Explore life coaching, flexible coaching packages, and counseling services through Next Level Up. Together, we can talk about the support that fits your goals.'},
 packages:{eyebrow:'Coaching packages',title:'Choose Your\nNext Step.',subtitle:'The level of support that fits your season.',body:'Coaching for clarity, confidence, life transitions, mindset, and personal growth. Start with one conversation or make room for a longer journey.'},
 counseling:{eyebrow:'Counseling through Next Level Up',title:'A Safe Space\nfor Real Change.',subtitle:'Support. Clarity. Progress.',body:'Kimi also provides counseling through Next Level Up as an unlicensed master’s-level provider working under licensed supervision. Mental-health counseling and psychotherapy use NLU’s clinical intake, consent, scheduling, and billing process.'},
 resources:{eyebrow:'Small steps, practical tools',title:'Make Room\nfor What Matters.',subtitle:'A little reflection. A clearer starting point.',body:'Use these simple prompts to prepare for coaching and explore what you want from your next chapter.'},
 contact:{eyebrow:'Let’s connect',title:'You Talk.\nI Listen.',subtitle:'Start with a conversation.',body:'Have a question about life coaching or a package? Share a little about what you’re looking for. For counseling, please contact Next Level Up directly.'},
 consultation:{eyebrow:'Take the first step',title:'Book a Free\nConsultation',subtitle:'No pressure. A real conversation.',body:'Let’s connect. This free, 30-minute consultation is a chance to talk about your goals, ask questions, and see if we’re a good fit.'},
 enroll:{eyebrow:'Your coaching journey',title:'A Thoughtful\nBeginning.',subtitle:'Your goals. Your pace. Your next chapter.',body:'Tell Kimi what you want to work toward, how you like to be supported, and what would make coaching useful for you. Review the coaching agreements before beginning.'},
 privacy:{eyebrow:'Your information',title:'Privacy &\nCommunication',subtitle:'Clear expectations from the beginning.',body:'Learn how information is used in Kimi’s coaching practice and how coaching records are kept separate from Next Level Up’s counseling services.'},
 terms:{eyebrow:'Working together',title:'Coaching\nAgreements',subtitle:'Understand your options before you begin.',body:'Coaching is a voluntary partnership focused on goals, choices, and practical action. Read the scope and expectations below, and ask questions at any time.'}
 },
 story:{title:'My Story',eyebrow:'Real experience. Real understanding.',paragraphs:[
 'I’m Kimi Cain, a certified life coach. My passion is people — helping adults navigate life’s challenges, discover their strengths, and create lasting, positive change.',
 'I bring professional training and real-life experience to my work. Life isn’t always easy, and change can feel overwhelming. I offer a compassionate, down-to-earth approach, meeting you where you are and helping you move forward with practical tools, support, and accountability.',
 'I also work with Next Level Up in learning services and supervised counseling. Those services are provided through NLU, with their own enrollment, records, and service agreements.'
 ]},
 approach:'I combine a person-centered, strengths-based approach with practical strategies to help you gain clarity, build confidence, and take meaningful action. Whether you are working through a transition or seeking more balance, we begin with what matters to you.',
 motivation:'Everyone deserves to feel heard, valued, and empowered. My goal is to offer a welcoming, nonjudgmental space where you can reflect, explore possibilities, and grow.',
 values:[{icon:'heart',title:'Real Connection',body:'A welcoming conversation where your perspective matters.'},{icon:'leaf',title:'Meaningful Progress',body:'Goals and steps that fit your life and values.'},{icon:'mountain',title:'Practical Support',body:'Tools you can use outside our sessions.'},{icon:'sun',title:'A Brighter Tomorrow',body:'Encouragement as you build your next chapter.'}],
 services:[{icon:'leaf',title:'Life Coaching',body:'Personalized coaching for clarity, goals, transitions, confidence, mindset, and personal growth.',path:'consultation',label:'Explore coaching'},{icon:'heart',title:'Counseling Support',body:'Mental-health counseling through Next Level Up, where Kimi works as an unlicensed master’s-level provider under licensed supervision.',path:'counseling',label:'Counseling through NLU'},{icon:'calendar',title:'Coaching Packages',body:'Flexible coaching experiences, from a single focused session to ongoing support and accountability.',path:'packages',label:'Explore packages'}],
 resources:[{title:'What would you like to change?',intro:'Make a little space to notice what matters.',items:['What is working well in your life right now?','Where do you feel stuck or ready for something different?','What would a useful next step look like?']},{title:'Turn a goal into a small step',intro:'Choose an action you can realistically try.',items:['Name one goal in your own words.','Choose one small action for the coming week.','Decide when you will do it and what support could help.','Notice what you learn, and adjust your next step.']},{title:'Prepare for your consultation',intro:'You don’t need to have every answer.',items:['Bring one or two goals or questions.','Think about the support and accountability you prefer.','Ask about session options, fees, and scheduling.','Consider whether coaching or mental-health treatment fits your needs.']}],
 faqs:[{question:'How is coaching different from counseling?',answer:'Coaching focuses on goals, choices, habits, and practical action. It does not diagnose or treat mental-health conditions and is not psychotherapy. Counseling with Kimi is offered separately through Next Level Up under licensed supervision.'},{question:'Can I use insurance for coaching?',answer:'Kimi’s independent coaching is self-pay. Coaching packages are not billed as counseling or to Medicaid. NLU can explain benefits and eligibility for its separate counseling services.'},{question:'Which package should I choose?',answer:'The Clarity Session offers a focused starting point. Momentum provides three sessions to build consistency, Transformation offers six sessions for ongoing work, and Accountability Check-In is a shorter reset. A free consultation can help you decide.'},{question:'Are appointments virtual or in person?',answer:'Discuss video, phone, or local in-person preferences with Kimi. Only available appointment times and confirmed formats can be scheduled.'},{question:'Do I have to commit after the consultation?',answer:'No. The 30-minute consultation is free, and there is no obligation to purchase a session or package.'}],
 counselingPayment:'Kimi accepts Medicaid through Next Level Up. Cash/self-pay counseling is $100 per hour. NLU confirms benefits, eligibility, and appointment availability before counseling begins. Independent life coaching has separate pricing and is not billed to Medicaid.',
 counselingAreas:[{title:'Anxiety & Stress',body:'Explore concerns, coping skills, and ways to manage overwhelm.'},{title:'Life Transitions',body:'Support through changes in work, relationships, and life circumstances.'},{title:'Self-Esteem & Confidence',body:'Work toward a stronger sense of self and a more balanced perspective.'},{title:'Relationships',body:'Explore patterns, boundaries, and communication.'},{title:'Emotional Support',body:'A clinical space to process difficult feelings and experiences.'}],
 counselingSteps:[{title:'Connect with NLU',body:'Begin NLU’s counseling intake and discuss your needs, preferences, and interest in working with Kimi.'},{title:'Assessment and a plan',body:'The clinical team reviews fit, provider qualifications, supervision, and a plan for treatment.'},{title:'Ongoing counseling',body:'Sessions focus on the treatment goals developed with your provider. Availability and insurance eligibility are confirmed through NLU.'},{title:'Review progress',body:'Your provider reviews how support is working and adjusts the plan with you.'}],
 closing:{title:'Support Is Within Reach',body:'Let’s take the next step — together.'},
 scope:'Life coaching supports personal goals and growth. It does not diagnose or treat mental-health conditions and is not counseling, psychotherapy, medical care, or emergency support. Counseling is provided separately through Next Level Up.',
 privacy:[{title:'Information you choose to share',body:'Contact details, coaching goals, appointment preferences, and signed coaching documents are used to respond to your request and support your coaching relationship. Please avoid sending detailed clinical histories, payment-card numbers, or Social Security numbers in inquiry forms.'},{title:'Separate practice records',body:'Coaching information is kept in Kimi’s practice workspace. A link to Next Level Up does not transfer your coaching intake or enroll you in counseling. Any requested exchange of records between practices requires a separate authorization unless disclosure is otherwise required by law.'},{title:'Communications and limits',body:'Coaching communications are treated as private, but coaching does not automatically carry the legal confidentiality privileges of psychotherapy. Disclosure may be necessary when required by law or valid legal process, or to address a serious safety concern. Online and ordinary email communications carry privacy risks.'},{title:'Your choices',body:'Use the contact page to ask about your information, correct contact details, or change communication preferences. No coaching session will be recorded without a separate, specific agreement. You can decline a topic or end coaching.'}],
 terms:[{title:'A voluntary coaching partnership',body:'You choose your goals and remain responsible for your decisions. You may ask questions, decline an activity, request a different approach, or stop coaching. Results depend on many factors and are not guaranteed. These terms do not waive your legal rights.'},{title:'Fees and packages',body:'The consultation is free for 30 minutes. Before any paid session or package, you receive the price, number and length of sessions, format, included support, and applicable cancellation, refund, and expiration terms in writing. An inquiry or enrollment form alone does not authorize a charge.'},{title:'Scheduling and cancellation',body:'Please give as much notice as possible if you need to reschedule. No cancellation penalty, package expiration, or nonrefundable purchase is imposed by submitting these forms. Any later paid agreement must state its terms before you accept it.'},{title:'When a different service is needed',body:'Coaching is not crisis care or mental-health treatment. If those services better fit your needs, discuss an appropriate referral. In the U.S., call or text 988 for crisis support; call 911 for immediate danger. Website forms are not monitored for emergencies.'}]
};

export const kimiDocuments = [
 {key:'coaching-agreement',name:'Kimi Cain — Coaching Agreement and Informed Participation',sections:[
 ['Our coaching relationship','You are requesting coaching from Kimi Cain Life Coaching. Coaching is a collaborative, voluntary process to clarify your values, identify goals, explore options, and put practical actions into use. You direct your goals and may decline a question or activity. Services are currently designed for adults age 18 and older.'],
 ['Scope and qualifications','Kimi is a certified life coach. A coaching certification is not a Colorado license to practice a mental-health profession. In this practice she serves you as a coach; coaching does not include diagnosis, psychotherapy, mental-health treatment, medical advice, or crisis intervention. Her separate learning and supervised counseling work is provided through Next Level Up and requires NLU’s own intake and agreements.'],
 ['Your choices and responsibilities','You remain responsible for your decisions and for seeking appropriate medical, legal, financial, or mental-health advice when needed. Coaching is not a replacement for those services. You may pause or end coaching, ask questions, decline an activity, or request a referral. No outcome or particular result is guaranteed. This agreement does not release the practice from liability or require you to waive legal rights.'],
 ['Sessions and support','The free consultation lasts 30 minutes and carries no obligation to buy. Paid sessions and packages are discussed before you purchase. The written offer must identify the coach, format, session count, duration, price, included between-session support, scheduling arrangements, and any cancellation, refund, or expiration terms. This enrollment is not a purchase or permission to charge a payment method.'],
 ['Limits and referral','If your needs are outside coaching, Kimi may recommend another service or pause coaching while discussing alternatives. Referral to NLU is optional and is not a promise of insurance coverage or acceptance. No record transfer is authorized by this agreement. For a crisis in the U.S., call or text 988; for immediate danger call 911. Coaching forms, email, and messages are not emergency services.'],
 ['Acknowledgment','By signing, I confirm that I am at least 18, have read this coaching agreement, understand the difference between coaching and treatment, and voluntarily request coaching. I may ask questions before proceeding.']
 ]},
 {key:'coaching-privacy',name:'Kimi Cain — Coaching Privacy and Virtual Session Agreement',sections:[
 ['Use of information','The practice uses your contact information, goals, scheduling preferences, coaching notes, and agreements to communicate with you and provide coaching. Practice staff and service providers may access information as needed to operate the service. The coaching workspace is separate from NLU counseling records.'],
 ['Privacy and disclosure','Kimi treats coaching conversations as private. Coaching does not automatically have the same legal privilege or health-record protections as psychotherapy. Information may need to be disclosed as required by applicable law, a valid court order or other enforceable legal process, or to address a serious risk of harm. Only information appropriate to the circumstance should be shared. A separate authorization is needed for an optional exchange of information with NLU, an employer, a family member, or another provider.'],
 ['Video, phone, and written communication','You may discuss video, phone, or local in-person preferences. Use a private location and a secure device for remote sessions. Technology may fail or expose information despite reasonable precautions. If a session disconnects, use your agreed contact method to arrange a continuation or reschedule; do not drive during a session. Ordinary email and text may not be secure and are best used for scheduling. Avoid sensitive details in website inquiries.'],
 ['Recordings and optional sharing','This agreement does not authorize audio/video recording, AI transcription of sessions, marketing use, a testimonial, or sharing records with another organization. Any such request requires a separate, specific choice. Declining optional sharing does not by itself prevent coaching.'],
 ['Questions and changes','Contact the practice through its contact page or your agreed communication method to correct details, ask about access or retention of information, or change how you prefer to be contacted. There is no promise that all records can be deleted immediately when retention is legally required.'],
 ['Acknowledgment','By signing, I acknowledge these privacy limits and virtual-session considerations. I can discuss another format and ask questions before participating.']
 ]},
 {key:'coaching-fees',name:'Kimi Cain — Coaching Fees, Packages and Cancellation Acknowledgment',sections:[
 ['Before you purchase','Your free consultation is 30 minutes. The Clarity Session is one 90-minute session; Momentum includes three 60-minute sessions; Transformation includes six 60-minute sessions; Accountability Check-In is one 30-minute session. These are starting offerings and the current written quote controls the package you choose.'],
 ['Clear pricing','Paid prices have not been agreed by completing enrollment. Any provider hourly rate, package discount, tax if applicable, payment schedule, format, session duration, and total must be presented before purchase. Coaching is self-pay and will not be submitted as counseling to Medicaid or an insurer.'],
 ['Cancellation and unused sessions','Please contact Kimi promptly if you cannot attend. This acknowledgment creates no cancellation fee, forfeiture, package expiration, automatic renewal, or nonrefundable commitment. If a later paid offer includes these terms or a refund calculation for unused sessions, they must be provided in writing before acceptance. If Kimi cancels, arrange another time or discuss a refund for the undelivered service.'],
 ['Changes and stopping','You may stop coaching. Ask about unused paid sessions under the terms you actually accepted. A later catalog price or policy change does not by itself change the package agreement already accepted. No payment details are collected by this document.'],
 ['Acknowledgment','I understand that I can review and accept or decline a separate paid offer. My signature here does not authorize a charge or commit me to a paid package.']
 ]}
];
