<template><main class="visit-responses"><router-link :to="inbox">← Recurring check-ins</router-link><header><h1>This visit’s feedback</h1><button @click="load">Refresh</button></header><p v-if="error" role="alert">{{error}}</p><p v-else-if="loading">Loading responses…</p><template v-else-if="visit"><p>{{date(visit.scheduledStartAt)}} · {{visit.location}}</p><p>{{visit.serviceType==='tutoring'?'Tutoring':'Therapy / counseling'}} · {{visit.respondentType==='caregiver'?'Guardian / dependent report':visit.respondentType==='youth_self'?'Youth self-report':'Adult self-report'}}</p><p v-if="!visit.completedAt" class="notice">Feedback hasn’t been submitted yet. Refresh to check for updates.</p><div class="scores"><section v-for="metric in metrics" :key="metric.key"><h2>{{metric.label}}</h2><div class="circle" :style="{borderColor:color(visit.score[metric.key])}"><strong>{{visit.score[metric.key]==null?'—':visit.score[metric.key].toFixed(1)}}</strong><small>out of 10</small></div></section></div><p class="note">Custom feedback, not validated measures. Distress is reversed so higher scores indicate a more positive report. Missing scores are not zero.</p><article v-for="form in visit.forms" :key="form.id"><h2>{{form.title}}</h2><p v-if="visit.skippedFormIds.includes(form.id)">Skipped by respondent</p><dl v-else><template v-for="q in form.fields" :key="q.id"><dt>{{q.label}}</dt><dd>{{answer(form,q)}}</dd></template></dl></article></template></main></template>
<script setup>
import {ref,computed,watch,onUnmounted} from 'vue';import {useRoute} from 'vue-router';import api from '../../services/api';
const route=useRoute(),visit=ref(null),loading=ref(false),error=ref('');let generation=0;
const inbox=computed(()=>({path:route.params.organizationSlug?`/${route.params.organizationSlug}/dashboard`:'/dashboard',query:{tab:'clients',clients:'checkins'}}));
const metrics=[{key:'connection',label:'Connection'},{key:'progress',label:'Progress'}];
const color=v=>v==null?'#829085':`hsl(${v<=5?v*8:40+(v-5)*17} 65% 36%)`;
const date=value=>new Date(/[zZ]|[+-]\d\d:\d\d$/.test(value)?value:String(value).replace(' ','T')+'Z').toLocaleString('en-US',{timeZone:visit.value?.timezone||'America/Denver',dateStyle:'full',timeStyle:'short'});
function answer(form,q){const value=visit.value.answers?.[form.id]?.[q.id];if(value==null)return 'Not answered';const label=v=>q.options?.find(o=>o.value===v)?.label||String(v);return Array.isArray(value)?value.map(label).join(', '):typeof value==='boolean'?(value?'Yes':'No'):label(value);}
async function load(){const current=++generation;visit.value=null;error.value='';loading.value=true;try{const {data}=await api.get(`/kiosk/client-checkins/${encodeURIComponent(route.params.submissionId)}/responses`,{skipGlobalLoading:true});if(current===generation)visit.value=data.visit;}catch{if(current===generation)error.value='This check-in is unavailable. Sign in with the provider account that received the arrival.';}finally{if(current===generation)loading.value=false;}}
watch(()=>route.params.submissionId,load,{immediate:true});onUnmounted(()=>{generation++;visit.value=null;});
</script>
<style scoped>.visit-responses{max-width:850px;margin:30px auto;padding:24px;color:var(--text-primary,#24443d)}header{display:flex;justify-content:space-between;align-items:center;gap:16px}h1{font-size:28px}h2{font-size:20px}button{font:inherit;padding:10px 16px;border:1px solid #c8d9c3;background:transparent;color:inherit;border-radius:9px;cursor:pointer}.scores{display:flex;gap:30px;flex-wrap:wrap}.scores section{text-align:center}.circle{width:95px;height:95px;border:7px solid;border-radius:50%;display:flex;flex-direction:column;align-items:center;justify-content:center}.circle strong{font-size:30px}.circle small,.note{font-size:12px}.note,p{line-height:1.6}article{border-top:1px solid #dae3d8;margin-top:24px;padding-top:12px}dt{font-weight:600;margin-top:18px}dd{margin:8px 0;white-space:pre-wrap}.notice{background:#f4f2e6;padding:14px;border-radius:10px}</style>
