<template>
  <div class="ft-surface ft-site">
    <a class="ft-skip" href="#fundthred-main">Skip to content</a>
    <header class="ft-site-header ft-wrap" @keydown.esc="menuOpen=false"><router-link to="/fundthred" aria-label="FundThred home"><FundThredBrand/></router-link><button class="ft-menu-toggle" :aria-expanded="menuOpen" aria-controls="ft-site-nav" @click="menuOpen=!menuOpen">{{ menuOpen?'Close':'Menu' }} <span aria-hidden="true">{{ menuOpen?'×':'☰' }}</span></button><nav id="ft-site-nav" :class="{open:menuOpen}" aria-label="FundThred navigation"><router-link v-for="page in navigation" :key="page" :to="pagePath(page)" :aria-current="section===page?'page':undefined">{{ capitalize(page) }}</router-link><div class="ft-nav-actions"><router-link to="/fundthred/app">Sign in</router-link><router-link class="ft-button" to="/fundthred/start">Book a demo <span aria-hidden="true">→</span></router-link></div></nav></header>
    <main id="fundthred-main" tabindex="-1">
      <template v-if="section==='home'||section==='product'||section==='solutions'">
        <section class="ft-thread ft-hero-band"><div class="ft-wrap ft-hero"><div class="ft-hero-copy"><p class="ft-eyebrow">{{ hero.kicker }}</p><h1>{{ hero.title }}<br><em>{{ hero.accent }}</em></h1><p class="ft-hero-description">{{ hero.body }}</p><div class="ft-actions"><a class="ft-button" href="#explore">See it in action <span aria-hidden="true">→</span></a><router-link class="ft-button ft-button--outline" to="/fundthred/start">Book a demo</router-link></div><ul class="ft-assurances"><li>Built for your mission</li><li>One connected workspace</li><li>Part of PlotTwistCo</li></ul></div><div class="ft-hero-preview"><FundThredPreview :initial="section==='solutions'?'reports':'overview'"/></div></div><div class="ft-leaf-note"><span>Money<br>with <em>meaning.</em></span><p>From your funding<br>to a brighter tomorrow.</p></div></section>
        <section v-if="section==='solutions'" class="ft-audience-strip ft-wrap"><article v-for="audience in fundthredAudiences" :key="audience.name"><FundThredIcon :name="audience.icon" :tone="audience.tone"/><div><h3>{{ audience.name }}</h3><p>{{ audience.body }}</p></div></article></section>
        <section v-else class="ft-module-band"><div class="ft-wrap ft-module-strip"><router-link v-for="item in fundthredModules" :key="item.id" :to="{path:'/fundthred/product',hash:'#'+item.id}"><FundThredIcon :name="item.icon" :tone="item.tone"/><h3>{{ item.title }}</h3><p>{{ item.body }}</p></router-link></div></section>
        <section id="flow" class="ft-wrap ft-section ft-flow-section"><div><p class="ft-eyebrow">From funding to impact</p><h2>A connected thread<br>from <em>source to story.</em></h2><p>Follow every dollar from the moment it’s received to the report that shows what it supported.</p><router-link class="ft-text-link" to="/fundthred/resources">Explore the guides →</router-link></div><FundThredFlow/></section>
        <section id="explore" class="ft-example-section"><div class="ft-wrap ft-section"><div class="ft-section-heading"><div><p class="ft-eyebrow">A closer look</p><h2>Simple tools.<br><em>Meaningful work.</em></h2></div><p>Explore an illustrative workspace. Select a section to see how funding, requests, documents, and reporting fit together.</p></div><div class="ft-example-tabs" role="group" aria-label="Choose a product example"><button v-for="[id,label] in exampleTabs" :key="id" :aria-pressed="example===id" @click="example=id">{{ label }}</button></div><div class="ft-example-stage"><div><FundThredIcon :name="activeExample.icon" :tone="activeExample.tone" :size="27"/><h3>{{ activeExample.title }}</h3><p>{{ activeExample.detail }}</p><router-link class="ft-text-link" to="/fundthred/start">Walk through your workflow →</router-link></div><FundThredPreview :initial="example"/></div></div></section>
        <section v-if="section!=='home'" class="ft-wrap ft-section"><div class="ft-section-heading"><div><p class="ft-eyebrow">{{ section==='solutions'?'Tailored to your work':'The FundThred platform' }}</p><h2>{{ section==='solutions'?'Choose the path that':'Everything you need to' }}<br><em>{{ section==='solutions'?'fits your mission.':'follow the flow of funds.' }}</em></h2></div><p>Connected operational tools, with organization access and finance responsibilities kept clear.</p></div><div class="ft-detail-grid"><article v-for="item in fundthredModules" :id="item.id" :key="item.id"><FundThredIcon :name="item.icon" :tone="item.tone"/><h3>{{ item.title }}</h3><p>{{ item.detail }}</p><router-link class="ft-text-link" :to="{path:'/fundthred/start',query:{interest:item.id}}">Talk through this workflow →</router-link></article></div></section>
        <section class="ft-wrap ft-section ft-accounting"><div class="ft-accounting-mark"><FundThredIcon name="bank" tone="teal" :size="35"/></div><div><p class="ft-eyebrow">A clear handoff to accounting</p><h2>Keep the proof.<br><em>Connect the bigger picture.</em></h2><p>FundThred organizes funding decisions, approvals, evidence, and program spending. Use operational exports with your accountant while your accounting software keeps the ledger and financial statements.</p><router-link class="ft-text-link" to="/fundthred/resources#accounting">Understand the accounting handoff →</router-link></div><ul><li>Recorded expenses and payment references</li><li>Program budget and grant utilization exports</li><li>Documents connected to the work</li><li>Optional bank evidence for reconciliation</li></ul></section>
        <section class="ft-wrap ft-section ft-ecosystem"><div class="ft-section-heading"><div><p class="ft-eyebrow">A product of Plot Twist Co.</p><h2>A home of its own.<br><em>A world of connections.</em></h2></div><p>Use FundThred for your finances. Add the products that fit your organization. PlotTwistHQ brings your enabled products together.</p></div><div class="ft-bundle-grid"><article v-for="product in fundthredBundles" :key="product.id"><h3>{{ product.name }}</h3><p>{{ product.description }}</p><a class="ft-text-link" :href="product.href">Explore {{ product.name }} ↗</a></article></div><div class="ft-actions"><router-link class="ft-button" to="/fundthred/pricing">Explore plans & bundles →</router-link></div></section>
      </template>
      <template v-else-if="section==='pricing'">
        <section class="ft-thread"><div class="ft-wrap ft-pricing-hero"><div><p class="ft-eyebrow">Pricing</p><h1>A simpler way to plan<br>for <em>greater impact.</em></h1><p class="ft-hero-description">Choose the starting point that fits your organization. Every plan brings funding, budgets, requests, approvals, and proof into one connected workspace.</p></div><aside><FundThredIcon name="grants" :size="32"/><h2>Built around<br>your mission.</h2><ul><li>Start with one organization</li><li>Bring growing programs together</li><li>Add products as your needs change</li><li>Confirm your setup with our team</li></ul></aside></div></section>
        <section class="ft-wrap ft-section"><FundThredPricing/></section>
        <section class="ft-wrap ft-section ft-comparison"><p class="ft-eyebrow">The core stays connected</p><h2>One financial journey.<br><em>Room to grow.</em></h2><div><table><caption class="ft-sr-only">FundThred plan comparison</caption><thead><tr><th scope="col">Included workflow</th><th scope="col">Essentials</th><th scope="col">Growth</th><th scope="col">Enterprise</th><th scope="col">Custom</th></tr></thead><tbody><tr><th scope="row">Organizations</th><td>1</td><td>Up to 3</td><td>Up to 10</td><td>Agreed together</td></tr><tr v-for="feature in ['Funds, grants & budgets','Expense requests & approvals','Documents & operational exports','Organization-specific permissions']" :key="feature"><th scope="row">{{ feature }}</th><td v-for="n in 4" :key="n"><span aria-label="Included">✓</span></td></tr><tr><th scope="row">Product bundles & setup</th><td colspan="4">Scoped with your organization before activation</td></tr></tbody></table></div></section>
      </template>
      <template v-else-if="section==='resources'">
        <section class="ft-thread"><div class="ft-wrap ft-resource-hero"><div><p class="ft-eyebrow">Tools for thoughtful stewardship</p><h1>A little clarity.<br><em>A stronger mission.</em></h1><p class="ft-hero-description">Practical guides for keeping funding, spending, and the evidence behind it connected.</p></div><FundThredFlow/></div></section>
        <section class="ft-wrap ft-section ft-guides"><article v-for="guide in fundthredGuides" :id="guide.id" :key="guide.id"><p class="ft-eyebrow">{{ guide.label }}</p><h2>{{ guide.title }}</h2><p>{{ guide.intro }}</p><ol><li v-for="step in guide.steps" :key="step">{{ step }}</li></ol><button class="ft-button ft-button--outline" @click="downloadGuide(guide)">Download checklist ↓</button></article></section>
        <section id="accounting" class="ft-wrap ft-section ft-accounting-guide"><p class="ft-eyebrow">Working with your accountant</p><h2>The operating story.<br><em>The accounting record.</em></h2><p>FundThred currently supports the financial work around your programs: budgets, requests, approvals, recorded payments, documents, and operational CSV exports. Keep your accounting software for double-entry bookkeeping, bank reconciliation, financial statements, and period closing.</p><p>Automatic QuickBooks or Xero synchronization and a replacement accounting ledger are not included in this release. Discuss integration requirements with our team before selecting an accounting transition.</p><router-link class="ft-button" to="/fundthred/start">Discuss your accounting setup →</router-link></section>
      </template>
      <section v-else-if="section==='start'" class="ft-thread"><div class="ft-wrap ft-start"><div><p class="ft-eyebrow">Your next thread starts here</p><h1>Your purpose.<br><em>Our starting point.</em></h1><p class="ft-hero-description">Tell us about your organization, your funding, and the work you want to make easier. We’ll help you find the right FundThred setup.</p><ol><li><span>01</span><div><h3>Share your mission</h3><p>Your programs, your people, and your financial workflow.</p></div></li><li><span>02</span><div><h3>See your path</h3><p>Walk through funding, approvals, reporting, and possible bundles.</p></div></li><li><span>03</span><div><h3>Start with clarity</h3><p>Agree on your plan, permissions, pricing, and implementation.</p></div></li></ol><p class="ft-small">Already part of the team? <router-link to="/fundthred/app">Sign in to FundThred →</router-link></p></div><FundThredLeadForm/></div></section>
      <section v-if="['pricing','resources'].includes(section)" class="ft-wrap ft-section ft-faq"><p class="ft-eyebrow">A little more clarity</p><h2>Your questions, answered.</h2><details v-for="[question,answer] in fundthredFaqs" :key="question"><summary>{{ question }} <span aria-hidden="true">+</span></summary><p>{{ answer }}</p></details></section>
      <section v-if="section!=='start'" class="ft-closing"><div class="ft-wrap"><div><p class="ft-eyebrow">Purpose in. Progress out.</p><h2>Follow the thread<br>of <em>every dollar.</em></h2><p>A clearer financial journey for the work that matters.</p></div><div class="ft-actions"><router-link class="ft-button ft-button--light" to="/fundthred/start">Book a demo →</router-link><router-link class="ft-button ft-closing-secondary" to="/fundthred/app">Sign in to FundThred</router-link></div></div></section>
    </main>
    <footer class="ft-wrap ft-site-footer"><div><router-link to="/fundthred" aria-label="FundThred home"><FundThredBrand/></router-link><p>Money with meaning.<br>A Plot Twist Co. product.</p></div><nav aria-label="Explore FundThred"><strong>Explore</strong><router-link v-for="page in navigation" :key="page" :to="pagePath(page)">{{ capitalize(page) }}</router-link></nav><nav aria-label="Connect"><strong>Your next step</strong><router-link to="/fundthred/start">Book a demo</router-link><router-link to="/fundthred/app">Sign in</router-link><a href="https://plottwistco.com/products">The product family ↗</a><a href="https://plottwisthq.com">PlotTwistHQ ↗</a></nav><div class="ft-footer-bottom"><span>© {{ new Date().getFullYear() }} Plot Twist Co.</span><div><a href="/privacypolicy">Privacy</a><a href="/terms">Terms</a><router-link to="/fundthred/start">Contact</router-link></div></div></footer>
  </div>
</template>
<script setup>
import {computed,ref,watch,onBeforeUnmount} from 'vue';
import {useRoute} from 'vue-router';
import FundThredBrand from '../../components/fundthred/FundThredBrand.vue';
import FundThredIcon from '../../components/fundthred/FundThredIcon.vue';
import FundThredFlow from '../../components/fundthred/FundThredFlow.vue';
import FundThredPreview from '../../components/fundthred/FundThredPreview.vue';
import FundThredPricing from '../../components/fundthred/FundThredPricing.vue';
import FundThredLeadForm from '../../components/fundthred/FundThredLeadForm.vue';
import {fundthredPages,fundthredModules,fundthredAudiences,fundthredGuides,fundthredFaqs} from '../../content/fundthredWebsite';
import {fundthredBundles} from '../../config/fundthredProduct';
import {useFundThredBranding} from '../../composables/useFundThredBranding';
import '../../styles/fundthred.css';
import '../../styles/fundthredWebsite.css';
const route=useRoute(),menuOpen=ref(false),example=ref('overview');
const section=computed(()=>Object.hasOwn(fundthredPages,String(route.params.section||''))?String(route.params.section):'home');
useFundThredBranding(()=>fundthredPages[section.value].title);
const navigation=['product','solutions','pricing','resources'],pagePath=page=>`/fundthred/${page}`,capitalize=value=>value[0].toUpperCase()+value.slice(1);
const heroes={home:{kicker:'Purpose-driven finance operations',title:'Follow the thread',accent:'of every dollar.',body:'Funding, budgets, approvals, spending, and proof. Give your nonprofit a clear view of how every dollar stays aligned with its purpose.'},product:{kicker:'The FundThred platform',title:'One workspace for funding,',accent:'spending, and proof.',body:'Connect the everyday work behind your mission. Manage budgets, review requests, record spending, and keep the evidence together.'},solutions:{kicker:'Different missions. A stronger thread.',title:'Built for organizations',accent:'making a difference.',body:'Nonprofits, community organizations, school programs, and fiscal sponsors. Keep the funding journey connected to the work it makes possible.'}};
const hero=computed(()=>heroes[section.value]||heroes.home);
const exampleTabs=[['overview','Overview'],['funds','Funding'],['expenses','Expense requests'],['documents','Documents'],['reports','Reporting']];
const activeExample=computed(()=>fundthredModules.find(item=>item.id===example.value)||{icon:'overview',tone:'teal',title:'Your mission, in view.',detail:'See received funding, approved budgets, paid expenses, and available spending. Keep next steps close to the numbers that matter.'});
const previousMeta=new Map();
function metadata(selector,attributes){let el=document.head.querySelector(selector);if(!el){el=document.createElement(selector.startsWith('link')?'link':'meta');document.head.appendChild(el);previousMeta.set(el,null);}else if(!previousMeta.has(el)){previousMeta.set(el,Array.from(el.attributes,attribute=>[attribute.name,attribute.value]));}for(const [key,value] of Object.entries(attributes))el.setAttribute(key,value);}
watch(section,()=>{menuOpen.value=false;example.value=section.value==='solutions'?'reports':'overview';const page=fundthredPages[section.value];document.title=page.title;metadata('meta[name="description"]',{name:'description',content:page.description});metadata('link[rel="canonical"]',{rel:'canonical',href:`https://plottwisthq.com/fundthred${section.value==='home'?'':'/'+section.value}`});metadata('meta[property="og:title"]',{property:'og:title',content:page.title});metadata('meta[property="og:description"]',{property:'og:description',content:page.description});},{immediate:true});
onBeforeUnmount(()=>previousMeta.forEach((attributes,el)=>{if(attributes===null)el.remove();else{for(const attribute of Array.from(el.attributes))el.removeAttribute(attribute.name);for(const [key,value] of attributes)el.setAttribute(key,value);}}));
function downloadGuide(guide){const text=`FundThred · ${guide.title}\n\n${guide.intro}\n\n${guide.steps.map((step,i)=>`${i+1}. ${step}`).join('\n')}\n\nFundThred by Plot Twist Co.\nhttps://plottwisthq.com/fundthred/resources\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`FundThred-${guide.id}-checklist.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
</script>
