<template>
 <div class="itsco-site" :class="{'itsco-fair-mode':section==='internship-fair'}">
  <a class="its-skip" href="#its-main">Skip to content</a>
  <header class="its-header"><router-link class="its-brand" to="/p/itsco" aria-label="ITSCO home"><img data-website-image="logo" :src="logoUrl" alt=""/><span class="its-wordmark"><strong>ITSCO</strong><span>In The School Counselors</span><small>Mental health. Brighter tomorrows.</small></span></router-link><button class="its-menu-button" :aria-expanded="menu" aria-controls="its-nav" @click="menu=!menu">{{menu?'Close ×':'Menu ☰'}}</button><nav id="its-nav" :class="{'is-open':menu}" aria-label="Main navigation" @keydown.esc="menu=false"><details class="its-join-menu"><summary>Join us <span aria-hidden="true">⌄</span></summary><div><router-link to="/join/itsco" @click="closeJoinMenu">Find care / enrollment</router-link><router-link :to="path('internships')" @click="closeJoinMenu">Practicum/Internships</router-link><router-link to="/careers/itsco" @click="closeJoinMenu">Careers</router-link></div></details><router-link v-for="[label,slug] in nav.filter(item => item[1] !== 'resources')" :key="slug" :to="path(slug)" :aria-current="section===slug?'page':undefined">{{label}}</router-link><router-link to="/careers/itsco">Careers</router-link><PublicResourcesMenu resources-path="/p/itsco/resources" /></nav><a class="its-button its-portal" :href="portalLoginUrl"><Icon name="people"/>Portal Login</a></header>
  <main id="its-main" tabindex="-1">
   <section v-if="error&&!hasData" class="its-wrap its-section"><h1 data-website-field="copy:let-s-reconnect">{{content("copy:let-s-reconnect","Let\u2019s reconnect.")}}</h1><p role="alert">{{error}}</p><button class="its-button" @click="load">Try again</button><a class="its-text-button" :href="portalLoginUrl">Open portal login →</a></section>
   <p v-if="error&&hasData" class="its-wrap its-soft" role="status">{{error}} <button class="its-text-button" @click="load">Try again</button></p>
   <ItscoInternships v-if="!(error&&!hasData)&&internshipSection" :loading="!hasData" :section="section" :data="data" :preview="preview" @saved="refreshData"/>
   <section v-else-if="!hero&&!(error&&!hasData)" class="its-wrap its-section"><h1 data-website-field="copy:page-not-found">{{content("copy:page-not-found","Page not found")}}</h1><router-link class="its-button" to="/p/itsco">Back to ITSCO</router-link></section>
   <template v-else-if="!(error&&!hasData)">
    <section :data-website-image="heroKey('image')" :data-website-image-url="safe(hero.imageUrl)||asset(hero.image)" class="its-hero" :class="{'its-hero-home':!section,'its-hero-compact':section==='providers'}" :style="{'--its-hero':`url(${safe(hero.imageUrl)||asset(hero.image)})`}"><div class="its-wrap"><div class="its-hero-copy"><p :data-website-field="heroKey('eyebrow')" class="its-eyebrow">{{hero.eyebrow}}</p><h1 :data-website-field="heroKey('title')">{{hero.title}}</h1><p :data-website-field="heroKey('body')" class="its-hero-subtitle">{{hero.body}}</p><p v-if="!section" class="its-hero-detail" data-website-field="home.detail">{{content('home.detail','Everyone deserves a safe, supportive space to feel heard, build skills, and thrive. Find a path forward with care that meets you where you are.')}}</p><div v-if="!['providers','contact'].includes(section)" class="its-actions"><router-link class="its-button" :to="hero.ctaHref||'/p/itsco/providers'">{{hero.cta||'Find your provider'}} <Icon name="arrow"/></router-link><router-link class="its-button its-outline" :to="!section?'/join/itsco/counseling':path('contact')">{{!section?'Enroll now':'Connect with us'}} →</router-link></div><div v-if="!section" class="its-hero-formats"><span><Icon name="pin"/>In office</span><span><Icon name="screen"/>Telehealth</span><span><Icon name="school"/>School-based support</span></div></div></div><p class="its-handwritten">People.<br/>Purpose.<br/>Brighter tomorrows.</p></section>

    <ItscoCareFinder v-if="!section" :offices="data.offices||[]" :insurances="data.insurances"/>
    <section v-if="!section||section==='services'" class="its-section its-wrap" :class="{'its-home-services':!section}"><div class="its-section-heading"><div><h2 data-website-field="home.services.title">{{content('home.services.title','Our Services')}}</h2><p data-website-field="home.services.subtitle">{{content('home.services.subtitle','Professional, personalized care for every stage of life.')}}</p></div><router-link v-if="!section" class="its-text-button" :to="path('services')">View all services →</router-link></div><div class="its-service-grid"><article v-for="s in services" :key="s.key" class="its-service-card"><Icon :name="s.icon"/><h3 :data-website-field="`service:${s.key}:title`">{{s.title}}</h3><p :data-website-field="`service:${s.key}:body`">{{s.body}}</p><img :data-website-image="`service:${s.key}:image`" :src="safe(s.photo)" alt="" loading="lazy"/><router-link :to="s.school?path('schools'):{path:path('providers'),query:s.query||{}}">{{s.school?'Explore schools':'Find support'}} →</router-link></article></div></section>

    <section v-if="!section||section==='schools'" class="its-why"><div class="its-wrap"><h2>{{section==='schools'?'Support that works with your school.':'Why choose ITSCO?'}}</h2><p data-website-field="copy:trusted-care-meaningful-connections-healthier-communities">{{content("copy:trusted-care-meaningful-connections-healthier-communities","Trusted care. Meaningful connections. Healthier communities.")}}</p><div class="its-four"><article v-for="[icon,title,body] in why" :key="title"><span class="its-icon-circle"><Icon :name="icon"/></span><div><h3>{{title}}</h3><p>{{body}}</p></div></article></div></div></section>

    <section v-if="!section&&data.providers.length" class="its-section its-wrap" aria-label="Featured providers" @mouseenter="rotationPaused=true" @mouseleave="rotationPaused=false" @focusin="rotationPaused=true" @focusout="rotationPaused=false"><div class="its-section-heading"><div><p class="its-eyebrow" data-website-field="copy:real-people-a-brighter-tomorrow">{{content("copy:real-people-a-brighter-tomorrow","Real people. A brighter tomorrow.")}}</p><h2 data-website-field="copy:our-providers">{{content("copy:our-providers","Our Providers")}}</h2><p data-website-field="copy:meet-some-of-the-caring-professionals-on-our-team">{{content("copy:meet-some-of-the-caring-professionals-on-our-team","Meet some of the caring professionals on our team.")}}</p></div><router-link class="its-text-button" :to="path('providers')">View all providers →</router-link></div><div class="its-featured-grid"><article v-for="p in featured" :key="p.id" :data-analytics-id="'provider-'+p.id" :data-analytics-label="p.displayName" class="its-featured-card"><img v-if="p.photoUrl" :src="p.photoUrl" :alt="p.displayName" loading="lazy"/><div v-else class="its-avatar">{{initials(p.displayName)}}</div><div><h3>{{p.displayName}}<template v-if="p.credential">, {{p.credential}}</template></h3><p class="its-small">{{p.title}}</p><div class="its-tags"><span v-for="tag in p.specialties.slice(0,3)" :key="tag">{{tag}}</span></div><p class="its-featured-bio">{{p.bio}}</p><router-link :to="providerProfilePath(p)" data-analytics-kind="profile_open">View profile →</router-link></div></article></div><div v-if="data.providers.length>3" class="its-carousel-controls"><button class="its-text-button" @click="rotationEnabled=!rotationEnabled">{{rotationEnabled?'Pause rotation':'Resume rotation'}}</button><button class="its-text-button" @click="offset=(offset+3)%data.providers.length">Meet more providers →</button></div></section>

    <section v-if="section==='providers'" class="its-section its-wrap"><ItscoProviderDirectory :providers="data.providers" :directory-loading="!hasData" :schools="schools" :offices="data.offices||[]" :agency-id="data.agency.id" :availability="availability" :availability-loading="availabilityLoading" :availability-error="availabilityError" @refresh="refreshData" @retry-availability="loadAvailability"/></section>

    <ItscoSchoolPartnershipGuide v-if="section==='schools'"/>
    <section v-if="section==='schools'" class="its-section its-wrap"><ItscoSchoolPartners :districts="data.districts"/></section>
    <ItscoServiceMap v-if="!section" :offices="data.offices||[]"/>
    <section v-if="!section" class="its-school-roots"><img data-website-image="asset:students-hero.png" :src="asset('students-hero.png')" alt="Students at school" loading="lazy"/><div><p class="its-eyebrow" data-website-field="copy:where-our-story-began">{{content("copy:where-our-story-began","Where our story began")}}</p><h2 data-website-field="copy:our-roots-in-school-based-mental-health">{{content("copy:our-roots-in-school-based-mental-health","Our roots in school-based mental health.")}}</h2><p data-website-field="copy:we-work-alongside-school-communities-to-bring-support-closer-to-studen">{{content("copy:we-work-alongside-school-communities-to-bring-support-closer-to-studen","We work alongside school communities to bring support closer to students and families. Explore our school partners and the providers who serve them.")}}</p><router-link class="its-button its-outline" :to="path('schools')">Learn about school services →</router-link></div><p class="its-handwritten">Healthy students.<br/>Stronger schools.<br/>Brighter futures.</p></section>

    <section v-if="section==='about'" class="its-section its-wrap"><div class="its-two its-story"><div><p class="its-eyebrow" data-website-field="copy:our-story">{{content("copy:our-story","Our story")}}</p><h2>A shared vision.<br/>A stronger community.</h2><p data-website-field="about:story">{{content('about:story',settings.story || 'ITSCO’s work is rooted in a commitment to students, families, and the people who care for them. Bringing support into schools helps connect mental health care with everyday life.')}}</p><p data-website-field="copy:as-our-network-grows-our-focus-stays-close-to-home-meaningful-relation">{{content("copy:as-our-network-grows-our-focus-stays-close-to-home-meaningful-relation","As our network grows, our focus stays close to home: meaningful relationships, accessible support, and care built around people.")}}</p><router-link class="its-button its-outline" :to="path('growth')">Explore our growth →</router-link></div><div class="its-four its-story-values"><article v-for="[icon,title,body] in principles" :key="title" class="its-soft"><Icon :name="icon"/><h3>{{title}}</h3><p>{{body}}</p></article></div></div><div class="its-two its-mission"><article class="its-soft"><Icon name="mountain"/><div><p class="its-eyebrow" data-website-field="copy:our-vision">{{content("copy:our-vision","Our vision")}}</p><h2 data-website-field="copy:mental-wellness-within-reach">{{content("copy:mental-wellness-within-reach","Mental wellness within reach.")}}</h2><p data-website-field="about:vision">{{content('about:vision',settings.vision || 'A future where children, teens, adults, and families can find support in the communities they call home.')}}</p></div></article><article class="its-soft"><Icon name="leaf"/><div><p class="its-eyebrow" data-website-field="copy:our-mission">{{content("copy:our-mission","Our mission")}}</p><h2 data-website-field="copy:accessible-care-stronger-communities">{{content("copy:accessible-care-stronger-communities","Accessible care. Stronger communities.")}}</h2><p data-website-field="about:mission">{{content('about:mission',settings.mission || 'Connect people with compassionate counseling and build relationships that support growth, resilience, and belonging.')}}</p></div></article></div><div class="its-section-heading"><div><p class="its-eyebrow" data-website-field="copy:our-values">{{content("copy:our-values","Our values")}}</p><h2 data-website-field="copy:what-guides-us">{{content("copy:what-guides-us","What guides us")}}</h2></div><router-link class="its-text-button" :to="path('team')">Meet the people behind our mission →</router-link></div><div class="its-value-grid"><article v-for="[icon,title,body] in values" :key="title"><span class="its-icon-circle"><Icon :name="icon"/></span><h3>{{title}}</h3><p>{{body}}</p></article></div></section>

    <section v-if="section==='growth'" class="its-section its-wrap"><div class="its-two its-story"><div><p class="its-eyebrow" data-website-field="copy:our-journey">{{content("copy:our-journey","Our journey")}}</p><h2>A vision that<br/>keeps growing.</h2><p data-website-field="about:growthStory">{{content('about:growthStory',settings.growthStory || 'What starts with a connection can become a community of support. Our growth follows the relationships we build with schools, families, and clinicians.')}}</p><p data-website-field="copy:our-public-directory-grows-with-our-network-new-school-partners-and-pr">{{content("copy:our-public-directory-grows-with-our-network-new-school-partners-and-pr","Our public directory grows with our network. New school partners and providers become part of the story as they join ITSCO.")}}</p><router-link class="its-button its-outline" :to="path('schools')">Explore our school partners →</router-link></div><div class="its-timeline"><article v-for="(step,i) in milestones" :key="i"><span class="its-timeline-number">{{step.year||String(i+1).padStart(2,'0')}}</span><h3>{{step.title}}</h3><p>{{step.body}}</p></article></div></div></section>

    <section v-if="hasData&&['schools','growth','impact'].includes(section)" class="its-section its-wrap"><div class="its-metrics"><article v-for="metric in metrics" :key="metric.label"><Icon :name="metric.icon"/><div><strong>{{metric.value.toLocaleString()}}</strong><span>{{metric.label}}</span></div></article></div><p class="its-small its-metric-note">School and district totals reflect current school portal partners. Team totals count each person once. <template v-if="data.metrics.studentsSupported!==null">Students connected includes our confirmed historical total plus new students linked to ITSCO schools since that update.</template></p></section>

    <section v-if="section==='impact'" class="its-section its-wrap"><div class="its-section-heading"><div><p class="its-eyebrow" data-website-field="copy:where-we-make-a-difference">{{content("copy:where-we-make-a-difference","Where we make a difference")}}</p><h2>Real change.<br/>In real ways.</h2></div><p data-website-field="copy:our-purpose-is-bigger-than-a-number-these-are-the-communities-at-the-c">{{content("copy:our-purpose-is-bigger-than-a-number-these-are-the-communities-at-the-c","Our purpose is bigger than a number. These are the communities at the center of our work.")}}</p></div><div class="its-four its-impact-grid"><article v-for="[title,body,image] in impactAreas" :key="title"><img :data-website-image="'asset:'+image" :src="asset(image)" alt="" loading="lazy"/><div><h3>{{title}}</h3><p>{{body}}</p></div></article></div><div class="its-two its-story its-soft"><div><p class="its-eyebrow" data-website-field="copy:our-reach">{{content("copy:our-reach","Our reach")}}</p><h2 data-website-field="copy:connected-through-our-schools">{{content("copy:connected-through-our-schools","Connected through our schools.")}}</h2><p data-website-field="copy:discover-the-districts-school-communities-and-people-who-are-part-of-i">{{content("copy:discover-the-districts-school-communities-and-people-who-are-part-of-i","Discover the districts, school communities, and people who are part of ITSCO today.")}}</p><router-link class="its-button" :to="path('schools')">Explore our partners →</router-link></div><ul class="its-reach-list"><li v-for="d in data.districts" :key="d.slug"><Icon name="school"/><strong>{{d.name}}</strong><span>{{d.schools.length}} {{d.schools.length===1?'school':'schools'}}</span></li></ul></div></section>

    <section v-if="section==='team'" class="its-section its-wrap"><div class="its-section-heading"><div><p class="its-eyebrow" data-website-field="copy:meet-our-support-team">{{content("copy:meet-our-support-team","Meet our support team")}}</p><h2 data-website-field="copy:different-roles-a-shared-mission">{{content("copy:different-roles-a-shared-mission","Different roles. A shared mission.")}}</h2><p data-website-field="copy:get-to-know-the-people-who-help-itsco-s-providers-schools-and-families">{{content("copy:get-to-know-the-people-who-help-itsco-s-providers-schools-and-families","Get to know the people who help ITSCO\u2019s providers, schools, and families move forward.")}}</p></div><router-link class="its-button its-outline" to="/careers/itsco">View open positions →</router-link></div><div class="its-team-filters" role="group" aria-label="Team departments"><button :aria-pressed="!department" @click="department=''">All team members</button><button v-for="d in departments" :key="d" :aria-pressed="department===d" @click="department=d">{{d}}</button></div><div class="its-team-grid"><article v-for="p in visibleTeam" :key="p.id" :data-analytics-id="'team-'+p.id" :data-analytics-label="p.displayName" class="its-team-card"><img v-if="p.photoUrl" :src="p.photoUrl" :alt="p.displayName" loading="lazy"/><div v-else class="its-avatar">{{initials(p.displayName)}}</div><div><h3>{{p.displayName}}</h3><p>{{p.title}}</p><details><summary data-analytics-kind="profile_open">Meet {{p.firstName}} <span aria-hidden="true">+</span></summary><p>{{p.bio||'Part of the ITSCO team, supporting our schools, providers, and families.'}}</p><router-link :to="path('contact')">Contact our team →</router-link><PublicProviderProfileEditor v-if="!preview" :provider="p" :agency-id="data.agency.id" @saved="refreshData"/></details></div></article></div><ItscoProfilePlaceholders v-if="!hasData"/><p v-else-if="!visibleTeam.length" class="its-soft">Team profiles are being updated. Our support team is available through the contact form.</p></section>

    <section v-if="['','services','insurance'].includes(section)" class="its-section its-insurance-section"><div class="its-wrap"><div class="its-section-heading"><div><p class="its-eyebrow" data-website-field="copy:insurance-friendly-support">{{content("copy:insurance-friendly-support","Insurance-friendly support")}}</p><h2 data-website-field="copy:let-s-find-your-path-to-care">{{content("copy:let-s-find-your-path-to-care","Let\u2019s find your path to care.")}}</h2><p data-website-field="copy:plans-shown-come-from-our-providers-profiles-and-credentialing-records">{{content("copy:plans-shown-come-from-our-providers-profiles-and-credentialing-records","Plans shown come from our providers\u2019 profiles and credentialing records. Coverage depends on your plan, provider, and service.")}}</p></div><router-link class="its-button its-outline" :to="path('providers')">Find a provider →</router-link></div><div v-if="data.insurances.length" class="its-insurance-ticker" :class="{paused:insurancePaused}"><div class="its-insurance-band"><div v-for="i in data.insurances" :key="i.name"><img v-if="i.logoUrl" :src="i.logoUrl" alt="" loading="lazy"/><span>{{i.name}}</span></div></div><button type="button" class="its-text-button" @click="insurancePaused=!insurancePaused">{{insurancePaused?'Resume insurance rotation':'Pause insurance rotation'}}</button></div><p v-else>Contact our support team to discuss insurance and payment options.</p></div></section>

    <section v-if="section==='contact'" class="its-section its-wrap"><ItscoSupportForm/></section>
    <section v-if="section==='resources'" class="its-section its-wrap"><div class="its-three"><article v-for="[title,body,href] in resources" :key="title" class="its-card"><h2>{{title}}</h2><p>{{body}}</p><a v-if="href==='/itsco/login'" class="its-button its-outline" :href="portalLoginUrl">Open portal login →</a><router-link v-else class="its-button its-outline" :to="href">Get started →</router-link></article></div></section>

    <section v-if="section!=='contact'" class="its-final"><div class="its-wrap"><p class="its-eyebrow" data-website-field="copy:be-part-of-a-brighter-tomorrow">{{content("copy:be-part-of-a-brighter-tomorrow","Be part of a brighter tomorrow")}}</p><h2>{{section==='team'?'Join a team that believes in better.':'Ready to take the next step?'}}</h2><p>{{section==='team'?'Bring your purpose to work with people who care.':'Find support for yourself, your family, or your school community.'}}</p><div class="its-actions"><router-link class="its-button its-white" :to="section==='team'?'/careers/itsco':'/join/itsco/counseling'">{{section==='team'?'View open positions':'Start enrollment'}} →</router-link><router-link class="its-button its-light-outline" :to="section==='schools'?'/itsco/school-referral':path('contact')">{{section==='schools'?'School referrals':'Contact our team'}} →</router-link></div></div></section>
   </template>
  </main>
  <footer class="its-footer"><div class="its-wrap"><div class="its-footer-top"><router-link to="/p/itsco"><img data-website-image="logo" :src="logoUrl" alt="ITSCO — In The School Counselors"/></router-link><nav aria-label="Explore ITSCO"><router-link v-for="[label,slug] in [...nav,['Explore our growth','growth'],['Our impact','impact'],['Our team','team'],['Insurance','insurance'],['Practicum/Internships','internships'],['Our founders','founders'],['Supervisors & mentors','supervisors'],['Internship fair','internship-fair']]" :key="slug" :to="path(slug)">{{label}}</router-link></nav><nav aria-label="Quick links"><a :href="portalLoginUrl">Portal Login</a><router-link to="/careers/itsco">Careers / join our team</router-link><router-link to="/join/itsco/counseling">Start enrollment</router-link><router-link to="/itsco/school-referral">School referrals</router-link></nav><p class="its-handwritten">People.<br/>Purpose.<br/>Stronger communities.</p></div><div class="its-footer-bottom"><small>© {{new Date().getFullYear()}} ITSCO. All rights reserved.</small><nav aria-label="Policies"><router-link to="/itsco/privacypolicy">Privacy</router-link><router-link to="/itsco/terms">Terms</router-link><router-link :to="path('contact')">Accessibility help</router-link><router-link to="/community-standards">Community Standards &amp; communication privacy</router-link></nav></div></div></footer>
  <router-link v-if="!['contact','internship-fair'].includes(section)" class="its-support-launcher" :to="path('contact')"><Icon name="chat"/>Message our team</router-link>
 </div>
</template>
<script setup>
import {websiteContent} from '../../composables/usePublicWebsiteEditor';
import ItscoCareFinder from '../../components/itsco/ItscoCareFinder.vue';
import ItscoServiceMap from '../../components/itsco/ItscoServiceMap.vue';
import {providerProfilePath} from '../../utils/providerProfileLinks';
import ItscoInternships from '../../components/itsco/ItscoInternships.vue';
import PublicResourcesMenu from "../../components/public/PublicResourcesMenu.vue";
import {computed,ref,watch,onMounted,onUnmounted} from 'vue';
import {useRoute} from 'vue-router';
import api from '../../services/api';
import {readPublicWebsite,getCachedPublicWebsite} from '../../services/publicWebsiteRead';
import ItscoProfilePlaceholders from '../../components/itsco/ItscoProfilePlaceholders.vue';
import Icon from '../../components/rise/RiseIcon.vue';
import ItscoProviderDirectory from '../../components/itsco/ItscoProviderDirectory.vue';
import ItscoSchoolPartnershipGuide from '../../components/itsco/ItscoSchoolPartnershipGuide.vue';
import ItscoSchoolPartners from '../../components/itsco/ItscoSchoolPartners.vue';
import ItscoSupportForm from '../../components/itsco/ItscoSupportForm.vue';
import PublicProviderProfileEditor from '../../components/publicServices/PublicProviderProfileEditor.vue';
import {publicWebsiteUrl as safe} from '../../composables/useStandalonePublicWebsite';
import {portalLoginUrlForPublicSite} from '../../utils/publicPortalUrl.js';
const portalLoginUrl=portalLoginUrlForPublicSite('itsco');
const cachedWebsite=getCachedPublicWebsite('/public/marketing-pages/itsco/website-data');
const emptyWebsite={agency:{id:0},providers:[],districts:[],team:[],supervisors:[],insurances:[],offices:[],metrics:{studentsSupported:null},settings:{}};
const hasData=ref(Boolean(cachedWebsite));
const route=useRoute(),data=ref(cachedWebsite||emptyWebsite),error=ref(''),menu=ref(false),department=ref(''),offset=ref(0),rotationEnabled=ref(true),rotationPaused=ref(false);
const insurancePaused=ref(false);
const availability=ref({}),availabilityLoading=ref(false),availabilityError=ref('');let generation=0,availabilityGeneration=0,rotationTimer;
const section=computed(()=>({ 'school-services':'schools','for-schools':'schools','our-impact':'impact','explore-our-growth':'growth','support-team':'team','for-families':'services' }[route.params.section]||String(route.params.section||'')));
const internshipSection=computed(()=>['internships','founders','supervisors','internship-fair'].includes(section.value));
function closeJoinMenu(event){menu.value=false;const details=event.target.closest('details');if(details)details.open=false;}
const preview=window.parent!==window&&route.query.marketingPreview==='1';
const previewPage=ref(null);
const logoUrl=computed(()=>safe(content('logo',previewPage.value?.branding?.logoUrl ?? data.value?.content?.logoUrl))||safe(data.value?.agency?.logoUrl)||asset('logo.png'));
function receivePreview(e){
 if(!preview||e.source!==window.parent||e.origin!==window.location.origin||e.data?.type!=='marketing-preview'||e.data.page?.slug!=='itsco')return;
 previewPage.value=e.data.page;
}
const settings=computed(()=>previewPage.value?.branding?.itscoWebsite||data.value?.settings||{}),schools=computed(()=>data.value?.districts.flatMap(d=>d.schools)||[]);
const path=slug=>`/p/itsco${slug?'/'+slug:''}`,asset=name=>safe(content('asset:'+name,`/assets/itsco/${name}`))||`/assets/itsco/${name}`;
const content=(key,fallback)=>websiteContent(key,fallback,settings.value);
const heroKey=field=>`page:${section.value||'home'}:${field}`;
const nav=[['Services','services'],['Our Providers','providers'],['For Schools','schools'],['About','about'],['Resources','resources'],['Contact','contact']];
const heroes={
 '':['Support today. Brighter tomorrows.','Therapy That Meets You Where You Are','Compassionate mental health care for children, teens, adults, and families — in our offices, online, and in schools.','counseling-hero.png'],
 providers:['Our providers','Real People. A Brighter Tomorrow.','Find your fit. Explore specialties, locations, and openings.','mountains.png'],
 schools:['School-based services','Stronger Students. Healthier Communities.','We partner with school communities to bring mental health support closer to students and families.','counseling-hero.png','Explore our school partners','#school-partners'],
 about:['About ITSCO','Built in Schools. Growing for Communities.','Support for children, teens, adults, and families — brighter tomorrows, together.','students-hero.png','Meet our team','/p/itsco/team'],
 growth:['Explore our growth','From a Shared Vision to a Brighter Tomorrow.','Growing our connections with schools, families, and communities.','students-hero.png','See our impact','/p/itsco/impact'],
 impact:['Our impact','Stronger Students. Healthier Communities.','Real people. Real connections. A brighter tomorrow.','students-hero.png','Explore our growth','/p/itsco/growth'],
 team:['Our team','The People Behind the Progress.','Dedicated professionals. A shared purpose. Support for the clinicians, schools, and families who make up our community.','students-hero.png','Join our team','/careers/itsco'],
 services:['Our services','Support for Every Chapter.','Find a provider who understands your needs, whether you’re looking for yourself, your child, or your family.','counseling-hero.png'],
 insurance:['Insurance & care','A Clearer Path to Support.','Explore provider insurance information and connect with our team about your next steps.','counseling-hero.png'],
 contact:['We’re here to help','Let’s Find Your Next Step.','Questions about care, schools, insurance, or joining our team? Send us a message below.','counseling-hero.png'],
 resources:['Resources','A Little Guidance. A Stronger Start.','Find the right place to get started, connect with your care team, or explore school support.','students-hero.png']};
const hero=computed(()=>{const h=heroes[section.value];if(!h)return null;const original=!section.value?(previewPage.value||data.value?.content||{}):{};return {eyebrow:content(heroKey('eyebrow'),h[0]),title:content(heroKey('title'),original.heroTitle||h[1]),body:content(heroKey('body'),original.heroSubtitle||h[2]),imageUrl:content(heroKey('image'),safe(original.heroImageUrl)||asset(h[3])),image:h[3],cta:h[4],ctaHref:h[5]};});
const baseServices=[{icon:'leaf',title:'Individual Therapy',body:'Space to work through life’s challenges and build on your strengths.',image:'teen-counseling.png'},{icon:'people',title:'Child & Teen Therapy',body:'Support for young people as they grow, learn, and connect.',image:'student-learning.png'},{icon:'people',title:'Family Therapy',body:'Stronger communication and support for your family’s next chapter.',image:'students-hero.png'},{icon:'heart',title:'Couples Therapy',body:'Work toward greater understanding and connection.',image:'counseling-hero.png'},{icon:'screen',title:'Telehealth',body:'Explore virtual options with our providers.',image:'teen-counseling.png'},{icon:'school',title:'School-Based Therapy',body:'Bringing mental health support directly to school communities.',image:'students-hero.png',school:true}];
const services=computed(()=>baseServices.map((s,i)=>({...s,key:i,title:content(`service:${i}:title`,s.title),body:content(`service:${i}:body`,s.body),photo:content(`service:${i}:image`,asset(s.image))})));
const why=[['pin','Flexible care options','In office, online, or at school — find care that fits your life.'],['heart','Child & family support','Care built around your family’s needs and strengths.'],['school','School collaboration','Working with families and school teams to support students.'],['shield','Insurance guidance','Find provider insurance information and help with next steps.']];
const principles=[['people','People at the center','Guided by the needs of clients and the people who care for them.'],['school','Care where students are','Connecting mental health support with everyday school life.'],['leaf','Room to grow','Relationships that create space for learning and possibility.'],['chart','Growing together','Building connections while staying close to our purpose.']];
const values=[['shield','Good judgment','Do what’s right.'],['chat','Communication','Listen. Share. Build trust.'],['target','Impact','Create meaningful change.'],['leaf','Curiosity','Keep learning. Stay open.'],['chart','Innovation','Find better ways.'],['heart','Honesty','Be real. Be transparent.'],['people','Selflessness','Put people first.']];
const milestones=computed(()=>Array.isArray(settings.value.milestones)&&settings.value.milestones.length?settings.value.milestones:[{title:'A shared purpose',body:'Support students and families where they are.'},{title:'School connections',body:'Build relationships with school communities.'},{title:'A wider circle of care',body:'Connect people with providers and resources.'},{title:'Brighter tomorrows',body:'Keep listening, learning, and growing together.'}]);
const metrics=computed(()=>data.value?[...(data.value.metrics.studentsSupported!==null?[{icon:'people',label:'Students connected',value:data.value.metrics.studentsSupported}]:[]),{icon:'school',label:'School partners',value:data.value.metrics.schools},{icon:'pin',label:'School districts',value:data.value.metrics.districts},{icon:'heart',label:'Providers & team',value:data.value.metrics.teamMembers}]:[]);
const impactAreas=[['Students','A place to feel supported and build skills for everyday life.','student-learning.png'],['Schools','Connections between school communities and mental health support.','students-hero.png'],['Families','Help navigating care and building a stronger support network.','counseling-hero.png'],['Communities','Relationships that bring people and resources together.','teen-counseling.png']];
const resources=[['Portal Login','Already connected with ITSCO? Sign in to your care portal.','/itsco/login'],['School enrollment','Find your school and explore the referral process.','/itsco/school-referral'],['Find your provider','Learn about our team and explore current openings.','/p/itsco/providers']];
const featured=computed(()=>{const p=data.value?.providers||[];return p.length?Array.from({length:Math.min(3,p.length)},(_,i)=>p[(offset.value+i)%p.length]):[];});
const departments=computed(()=>[...new Set((data.value?.team||[]).map(p=>p.department).filter(Boolean))].sort());
const visibleTeam=computed(()=>(data.value?.team||[]).filter(p=>!department.value||p.department===department.value));
function initials(name){return name.split(' ').map(s=>s[0]).slice(0,2).join('');}
async function load(){await refreshData(false);}
async function refreshData(force=true){const id=++generation;error.value='';try{const res=await readPublicWebsite('/public/marketing-pages/itsco/website-data',{force});if(id!==generation)return;data.value=res.data;hasData.value=true;loadAvailability();}catch(e){if(id===generation&&e.response?.status===404){hasData.value=false;data.value=emptyWebsite;}if(id===generation)error.value=e.response?.status===429?`Please wait ${Number(e.response?.headers?.['retry-after'])||60} seconds before trying again.`:e.response?.status===404?'ITSCO’s website is not published yet. The client portal is still available.':'We couldn’t load the directory. Please try again.';}}
async function loadAvailability(){const id=++availabilityGeneration;availability.value={};availabilityError.value='';if(section.value!=='providers'||!data.value?.providers?.length)return;availabilityLoading.value=true;try{const results=await Promise.allSettled(['IN_PERSON','VIRTUAL'].map(programType=>api.get('/public/agency-services/itsco/counselors',{params:{programType,view:'availability',day:route.query.day||undefined,timeFrom:route.query.timeFrom||undefined,timeTo:route.query.timeTo||undefined,officeId:route.query.officeId||undefined},skipAuthRedirect:true,skipGlobalLoading:true,timeout:60000})));if(id!==availabilityGeneration)return;const map={};for(const r of results){if(r.status==='rejected'){availabilityError.value='Some online appointment times could not be checked.';continue;}for(const p of r.value.data.providers||[]){const key=p.id||p.providerId;const at=p.availability?.nextAvailableAt;map[key]??={timeZone:p.availability?.timeZone||'America/Denver'};map[key][results.indexOf(r)===0?'inPerson':'virtual']={hasPublishedOpenings:Boolean(p.availability?.hasPublishedOpenings||at),nextAvailableAt:at||null,slots:p.availability?.upcomingSlots?.length?p.availability.upcomingSlots:p.availability?.slots||[]};map[key].hasPublishedOpenings=Boolean(map[key].hasPublishedOpenings||p.availability?.hasPublishedOpenings||at);if(at&&(!map[key]?.nextAvailableAt||at<map[key].nextAvailableAt))map[key].nextAvailableAt=at;}}availability.value=map;}catch{if(id===availabilityGeneration)availabilityError.value='Online appointment times could not be checked.';}finally{if(id===availabilityGeneration)availabilityLoading.value=false;}}
watch(()=>route.fullPath,()=>{menu.value=false;});
watch(()=>[route.query.officeId,route.query.day,route.query.timeFrom,route.query.timeTo],(next,previous)=>{if(next.some((value,i)=>value!==previous?.[i])&&section.value==='providers'&&data.value)loadAvailability();});
watch(section,(value,previous)=>{if(value==='providers'&&previous!=='providers'&&data.value)loadAvailability();});
onMounted(()=>{window.addEventListener('message',receivePreview);if(preview)window.parent.postMessage({type:'marketing-preview-ready'},window.location.origin);load();rotationEnabled.value=!window.matchMedia('(prefers-reduced-motion: reduce)').matches;rotationTimer=setInterval(()=>{if(rotationEnabled.value&&!rotationPaused.value&&!document.hidden&&data.value?.providers.length>3)offset.value=(offset.value+3)%data.value.providers.length;},10000);});
onUnmounted(()=>{window.removeEventListener('message',receivePreview);generation++;availabilityGeneration++;clearInterval(rotationTimer);});
</script>
<style src="../../styles/itsco-public.css"></style>
