<template>
 <div class="range-site">
  <a class="range-skip" href="#range-main">Skip to content</a>
  <header class="range-header" @keydown.esc="closeMenu"><Brand :logo="safe(page?.branding?.logoUrl)"/><button class="range-menu" :aria-expanded="menuOpen" aria-controls="range-nav" @click="menuOpen=!menuOpen">{{menuOpen?'Close ×':'Menu ☰'}}</button><nav id="range-nav" :class="{'is-open':menuOpen}" aria-label="Primary"><router-link v-for="[label,slug] in nav" :key="slug" :to="path(slug)" :aria-current="section===slug?'page':undefined">{{label}}</router-link></nav><router-link class="range-button range-header-cta" :to="path('involved')">Partner with us →</router-link></header>
  <main id="range-main" tabindex="-1">
   <div v-if="loading" class="range-state" role="status">Loading Mental Range Collective…</div>
   <div v-else-if="error" class="range-state"><h1>Let’s try that again.</h1><p role="alert">{{error}}</p><button class="range-button" @click="load">Retry</button></div>
   <div v-else-if="!hero" class="range-state"><h1>Page not found</h1><router-link class="range-button" :to="path('')">Return home</router-link></div>
   <template v-else>
    <section class="range-hero" :class="{'range-hero-home':!section,'range-hero-finder':section==='providers'}" :style="{'--range-hero':`url(${JSON.stringify(heroImage)})`}"><div class="range-wrap"><p class="range-eyebrow">{{hero[0]}}</p><h1>{{!section?homeTitle:hero[1]}}<em v-if="section?hero[2]:homeAccent">{{!section?homeAccent:hero[2]}}</em></h1><p class="range-hero-intro">{{!section&&page.heroSubtitle?page.heroSubtitle:hero[3]}}</p><div v-if="!section" class="range-actions"><router-link class="range-button range-button-bright" :to="path('providers')">Find your support <Icon name="arrow"/></router-link><router-link class="range-outline range-outline-white" :to="path('network')">Explore our network</router-link></div><p v-if="section!=='providers'" class="range-hero-note">Stronger together<span/></p></div></section>
    <div v-if="section==='providers'" class="range-wrap range-section"><Finder :preview="preview"/></div>
    <template v-else>
     <section v-if="!section||section==='network'||section==='about'" class="range-section range-network" :class="{'range-network-home':!section}"><div class="range-wrap">
      <div class="range-heading-grid"><div><p class="range-eyebrow">Our network</p><h2>Different strengths.<br/><em>One shared mission.</em></h2><p>Independent organizations, each with their own expertise and identity. Together, we create more paths to support for individuals, families, schools, and communities.</p></div><aside v-if="section==='network'" class="range-soft-card"><Icon name="people"/><h3>Looking for a provider?</h3><p>Explore services, specialties, and published openings across our partner organizations.</p><router-link class="range-button" :to="path('providers')">Browse providers →</router-link></aside><div v-else class="range-partner-intro"><p>Discover the organizations that make up our network.</p><router-link class="range-outline" :to="path('network')">Meet our partner organizations →</router-link></div></div>
      <div v-if="section==='network'" class="range-filters" aria-label="Filter partners"><button v-for="[key,label] in categories" :key="key" :aria-pressed="category===key" @click="category=key">{{label}}</button></div>
      <p v-if="partnersLoading" role="status">Loading partner organizations…</p><div v-else-if="partnersError" role="alert"><p>Partner information is temporarily unavailable.</p><button class="range-outline" @click="loadPartners">Try again</button></div>
      <div v-else-if="filteredPartners.length" class="range-partner-grid" :class="{'range-partner-grid-compact':section!=='network'}"><article v-for="p in filteredPartners" :key="p.id" class="range-partner-card"><div class="range-partner-identity"><img v-if="safe(p.logoUrl)" :src="safe(p.logoUrl)" :alt="p.name" loading="lazy" @error="$event.target.style.display='none'"/><Icon v-else name="mountain"/><h3>{{p.name}}</h3></div><p v-if="p.description">{{p.description}}</p><div class="range-tags"><span v-for="s in p.services" :key="s">{{categories.find(c=>c[0]===s)?.[1]||s}}</span></div><dl v-if="section==='network'"><template v-if="p.audience"><dt>Who they support</dt><dd>{{p.audience}}</dd></template><template v-if="p.focus"><dt>Areas of focus</dt><dd>{{p.focus}}</dd></template><template v-if="p.location"><dt>Location</dt><dd>{{p.location}}</dd></template></dl><div class="range-actions"><a v-if="safe(p.websiteUrl)" class="range-button" :href="safe(p.websiteUrl)" @click="guardPreview">Visit website ↗</a><a v-if="safe(p.contactUrl)" class="range-outline" :href="safe(p.contactUrl)" @click="guardPreview">Contact →</a><router-link v-if="p.services.some(s=>['counseling','tutoring','coaching'].includes(s))" class="range-text-link" :to="{path:path('providers'),query:{agency:String(p.id)}}">Find support →</router-link><span v-if="!p.websiteUrl&&!p.contactUrl&&!p.services.length" class="range-muted">More information coming soon</span></div></article></div>
      <p v-else class="range-empty">{{partners.length?'No organizations in this category yet.':'Partner listings are being prepared. Please check back soon.'}}</p>
     </div></section>
     <section v-if="!section||section==='about'" class="range-section range-values"><div class="range-wrap"><div class="range-heading-row"><div><p class="range-eyebrow">Our values</p><h2>What guides us</h2></div><p>Collaboration over competition.<br/>People at the center.</p></div><div class="range-five"><article v-for="[icon,title,body] in values" :key="title"><Icon :name="icon"/><h3>{{title}}</h3><p>{{body}}</p></article></div></div></section>
     <section v-if="section==='about'" class="range-section range-soft"><div class="range-wrap range-two"><div><p class="range-eyebrow">Our story</p><h2>More organizations.<br/><em>A stronger tomorrow.</em></h2><p>No single organization can meet every need. A shared network helps people find a starting point, and gives organizations a place to connect around their strengths.</p><p>Each partner operates independently. The collective brings them together around a common purpose: more accessible support and stronger communities.</p></div><div class="range-mission"><Icon name="mountain"/><h2>Expand access.<br/>Build connection.<br/><em>Make room for possibility.</em></h2></div></div></section>
     <section v-if="!section||section==='impact'" class="range-impact-band" :style="bannerStyle"><div class="range-wrap range-heading-row"><div><p class="range-eyebrow">Our shared purpose</p><h2>Greater reach.<br/><em>Real connection.</em></h2></div><div class="range-real-count"><strong>{{partnersLoading||partnersError?'—':partners.length}}</strong><span>Published partner organizations</span></div><p>Different strengths.<br/>A commitment to stronger communities.</p><router-link class="range-outline range-outline-white" :to="path(section==='impact'?'network':'impact')">{{section==='impact'?'See our network':'Explore our purpose'}} →</router-link></div></section>
     <section v-if="section==='impact'" class="range-section"><div class="range-wrap"><p class="range-eyebrow">Beyond numbers</p><h2>Opportunity looks different<br/><em>in every community.</em></h2><div class="range-three range-story-cards"><article v-for="[image,title,body] in stories" :key="title"><img :src="asset(image)" alt="" loading="lazy"/><div><h3>{{title}}</h3><p>{{body}}</p></div></article></div><div class="range-soft-card"><h3>Building a clearer picture of our impact</h3><p>Verified outcomes and community stories will be shared as reporting becomes available. Our current partner count reflects the organizations published in this directory.</p></div></div></section>
     <section v-if="section==='resources'" class="range-section"><div class="range-wrap"><p class="range-eyebrow">A thoughtful starting point</p><h2>Find your next step.</h2><div class="range-three"><article v-for="[title,body,items] in resources" :key="title" class="range-soft-card"><Icon name="leaf"/><h3>{{title}}</h3><p>{{body}}</p><ul><li v-for="i in items" :key="i">{{i}}</li></ul></article></div><router-link class="range-button" :to="path('providers')">Explore providers →</router-link></div></section>
     <section v-if="!section||['involved','contact'].includes(section)" class="range-section"><div class="range-wrap"><div class="range-heading-row"><div><p class="range-eyebrow">Get involved</p><h2>Be part of the difference.</h2></div><p>Organizations. Providers. Community partners.<br/>A shared possibility for a brighter tomorrow.</p></div><div class="range-three"><article v-for="[icon,title,body,field] in involvement" :key="title" class="range-soft-card"><Icon :name="icon"/><h3>{{title}}</h3><p>{{body}}</p><router-link v-if="field==='providers'" class="range-outline" :to="path('providers')">Find support →</router-link><a v-else-if="safe(settings[field])" class="range-button" :href="safe(settings[field])" @click="guardPreview">Connect with us →</a><router-link v-else-if="!section" class="range-outline" :to="path('involved')">Learn more →</router-link><p v-else class="range-badge">{{title==='Partner'?'Partnership inquiries':'Contact options'}} coming soon</p></article></div></div></section>
     <section v-if="section&&!['impact','providers'].includes(section)" class="range-final" :style="bannerStyle"><div class="range-wrap range-heading-row"><h2>Together, we<br/><em>go further.</em></h2><p>Explore the people and organizations<br/>helping create brighter possibilities.</p><router-link class="range-outline range-outline-white" :to="path('providers')">Find support →</router-link></div></section>
    </template><p v-if="previewNotice" class="range-wrap" role="status">{{previewNotice}}</p>
   </template>
  </main>
  <footer class="range-footer" :style="bannerStyle"><div class="range-wrap"><div class="range-footer-top"><Brand :logo="safe(settings.footerLogoUrl)"/><nav aria-label="Footer"><router-link v-for="[label,slug] in nav" :key="slug" :to="path(slug)">{{label}}</router-link></nav><router-link class="range-outline range-outline-white" :to="path('contact')">Contact us →</router-link></div><div class="range-footer-bottom"><small>© {{new Date().getFullYear()}} Mental Range Collective.</small><small>Stronger communities. Brighter tomorrows.</small></div></div></footer>
 </div>
</template>
<script setup>
import {computed,ref,watch} from 'vue';
import api from '../../services/api';
import Brand from '../../components/range/RangeBrand.vue';
import Icon from '../../components/rise/RiseIcon.vue';
import Finder from '../../components/range/RangeProviderFinder.vue';
import {useStandalonePublicWebsite,publicWebsiteUrl as safe} from '../../composables/useStandalonePublicWebsite';
const {page,loading,error,menuOpen,section,settings,path,load,preview,previewNotice,guardPreview,closeMenu}=useStandalonePublicWebsite('range','Mental Range Collective | Stronger Together');
const nav=[['Home',''],['About','about'],['Our network','network'],['Find support','providers'],['Our impact','impact'],['Resources','resources']];
const asset=name=>`/assets/range/${name}.webp`;
const heroes={
 '':['A network for a brighter tomorrow','Expanding\nMental Health','Together.','A network of purpose-driven organizations working together to make mental health care, tutoring, and life coaching more accessible across our communities.','home'],
 about:['About us','A shared mission.','A greater reach.','Independent organizations. Shared values. A collaborative approach to helping people find the support they need.','about'],
 network:['Our network','Different strengths.','One shared mission.','Meet the organizations that connect, support, and strengthen our communities. Explore their services and find your starting point.','about'],
 impact:['Our impact','Real people.','Brighter possibilities.','Through collaboration and a shared purpose, we work toward stronger schools, healthier families, and more connected communities.','impact'],
 providers:['Our network','Find the right support.','','Explore mental health care, tutoring, and life coaching from published providers across our partner organizations.','mountains'],
 resources:['Resources','A little clarity.','A meaningful next step.','Practical questions to help you explore the network and prepare for a conversation.','mountains'],
 involved:['Get involved','Be part of','something bigger.','Connect people with support, explore a partnership, or help build a more connected community.','home'],
 contact:['Connect with us','A shared purpose.','An open conversation.','Explore the ways to connect with the collective and our independent partner organizations.','about']};
const hero=computed(()=>heroes[section.value]);
const homeTitle=computed(()=>{const lines=page.value?.heroTitle?.split('\n');return lines?.length>1?lines.slice(0,-1).join('\n'):lines?.[0]||heroes[''][1];});
const homeAccent=computed(()=>page.value?.heroTitle?(page.value.heroTitle.includes('\n')?page.value.heroTitle.split('\n').at(-1):''):heroes[''][2]);
const heroImage=computed(()=>safe(!section.value?page.value?.heroImageUrl:page.value?.branding?.contentPages?.find(p=>p.slug===section.value)?.heroImageUrl)||asset(hero.value?.[4]||'home'));
const bannerStyle=computed(()=>({'--range-banner':`url(${JSON.stringify(safe(settings.value.ctaImageUrl)||asset('banner'))})`}));
const partners=ref([]),partnersLoading=ref(true),partnersError=ref(false),category=ref('');
const categories=[['','All partners'],['counseling','Mental health'],['tutoring','Tutoring'],['coaching','Life coaching'],['skills','Skills programs'],['youth','Youth programs'],['operations','Management support']];
const filteredPartners=computed(()=>partners.value.filter(p=>!category.value||p.services.includes(category.value)));
async function loadPartners(){partnersLoading.value=true;partnersError.value=false;try{const{data}=await api.get('/public/mental-range/partners',{skipAuthRedirect:true,skipGlobalLoading:true});partners.value=data.partners||[];}catch{partnersError.value=true;}finally{partnersLoading.value=false;}}
watch(page,p=>{if(p)loadPartners();});
const values=[['people','Collaboration','We are stronger together.'],['heart','Accessibility','Support should be within reach.'],['leaf','Community','We invest in people and the places they grow.'],['mountain','Impact','Meaningful change starts with connection.'],['target','Possibility','New ideas can create new paths forward.']];
const stories=[['student','Stronger schools','More ways for students and families to connect with support where they learn and grow.'],['family','Healthier families','A network that helps families explore resources and find their next step.'],['provider','Connected providers','Shared knowledge and connections that help professionals serve their communities.']];
const involvement=[['people','Refer','Help someone explore mental health support, tutoring, or life coaching.','providers'],['mountain','Partner','Connect your organization with a network built around shared purpose.','partnerUrl'],['heart','Support','Explore ways to help expand access and opportunity in your community.','contactUrl']];
const resources=[['Finding your fit','A few questions can make an initial conversation easier.',['What kind of support am I looking for?','Does this provider work with my age group and needs?','Which format and location work for me?']],['Planning your first conversation','You can ask about the process before agreeing to services.',['Ask about fees and insurance coverage.','Confirm scheduling and cancellation policies.','Share accessibility or communication needs.']],['Understanding the network','Our partners operate independently.',['Choose an organization or published provider.','Continue to that organization for enrollment or booking.','The organization confirms your appointment and services.']]];
</script>
<style src="../../styles/mentalRangeWebsite.css"></style>
