<template>
 <div class="mh-site">
  <a class="mh-skip" href="#mh-main">Skip to content</a>
  <header class="mh-header" @keydown.esc="closeHeader"><router-link :to="path('')" aria-label="MH4Kidz home"><img :src="safe(page?.branding?.logoUrl)||asset('logo')" alt="MH4Kidz — Stronger kids. Brighter tomorrows."/></router-link><button class="mh-menu" :aria-expanded="menuOpen" aria-controls="mh-nav" @click="menuOpen=!menuOpen">{{menuOpen?'Close ×':'Menu ☰'}}</button><nav id="mh-nav" :class="{'is-open':menuOpen}" aria-label="Primary"><router-link v-for="[label,slug] in nav" :key="slug" :to="path(slug)" :aria-current="section===slug?'page':undefined">{{label}}</router-link><PublicWebsiteProviderLinks :directories="page?.providerDirectories || []" hub-slug="mh4kidz" /></nav><button ref="searchButton" class="mh-search-button" aria-label="Search MH4Kidz" :aria-expanded="searchOpen" aria-controls="mh-site-search" @click="toggleSearch"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></svg></button><router-link aria-label="Donate" class="mh-button mh-header-donate" :to="path('donate')">♥ <span>Donate</span></router-link>
    <section v-if="searchOpen" id="mh-site-search" class="mh-site-search" aria-label="Website search">
      <label for="mh-search-input">Find a program or page</label><input id="mh-search-input" ref="searchInput" v-model="searchQuery" type="search" placeholder="Try Unplugged, programs, or volunteering"/>
      <ul v-if="searchResults.length"><li v-for="result in searchResults" :key="result.href"><router-link :to="result.href" @click="searchOpen=false">{{result.title}} <span aria-hidden="true">→</span></router-link></li></ul>
      <p v-else role="status">No matches. Try a different word.</p>
    </section>
  </header>
  <main id="mh-main" tabindex="-1">
   <div v-if="loading" class="mh-state" role="status">Loading MH4Kidz…</div><div v-else-if="error" class="mh-state"><h1>Let’s try that again.</h1><p role="alert">{{error}}</p><button class="mh-button" @click="load">Retry</button></div><div v-else-if="!hero" class="mh-state"><h1>Page not found</h1><router-link class="mh-button" :to="path('')">Go home</router-link></div>
   <template v-else>
    <section class="mh-hero" :class="{'mh-home-hero':!section}" :style="heroStyle"><div class="mh-wrap"><p v-if="section" class="mh-breadcrumb"><router-link :to="path('')">Home</router-link> › {{hero[0]}}</p><div class="mh-hero-copy"><h1>{{hero[1]}}</h1><h2 v-if="hero[2]">{{hero[2]}}</h2><p>{{hero[3]}}</p><router-link v-if="!section" class="mh-button" :to="path('involved')">Support our mission <Icon name="arrow"/></router-link><p class="mh-scribble">{{section==='programs'?'Explore. Connect. Grow. Belong.':'Less screens. More life.'}}<span/></p></div></div></section>
    <section v-if="customBody" class="mh-section"><article class="mh-wrap mh-editor-content" v-html="customBody" @click="guardPreview"/></section>
    <section v-else-if="['privacy','terms'].includes(section)" class="mh-section"><div class="mh-wrap mh-pending" role="status"><h2>Coming soon</h2><p>{{section==='privacy'?'MH4Kidz’s privacy information':'MH4Kidz’s terms'}} will be published here when available.</p></div></section>
    <section v-if="!section||section==='about'" class="mh-section"><div class="mh-wrap mh-pillars" :class="{'mh-mission-band':section==='about'}"><article v-for="([icon,title,body],i) in section==='about'?mission:pillars" :key="title"><span class="mh-icon-circle" :class="'mh-color-'+i"><Icon :name="icon"/></span><h3>{{title}}</h3><p>{{body}}</p></article></div></section>
    <section v-if="['','about','unplugged','impact'].includes(section)" class="mh-section mh-story"><div class="mh-wrap mh-story-grid"><img :src="asset('unplugged')" alt="Children with backpacks exploring a sunlit forest trail" width="1448" height="1086" loading="lazy"/><div><p class="mh-eyebrow">{{section==='about'?'Our story':section==='impact'?'Lasting possibilities':'Our signature program'}}</p><h2>{{section==='about'?'A brighter path starts here.':section==='impact'?'More than numbers.':'The Unplugged Series'}}</h2><p>{{section==='about'?'Kids deserve to feel seen, supported, and connected. MH4Kidz brings a focus on real-world experiences, meaningful relationships, and opportunities to grow.':section==='impact'?'Our purpose is bigger than a number. We want to help kids find stronger connections, more confidence, and a sense of belonging in their communities.':'Nature-based and experiential group programs that help kids practice emotional regulation, teamwork, confidence, and mindfulness — with room to connect beyond their screens.'}}</p><ul class="mh-checklist"><li v-for="item in ['Outdoor adventures','Hands-on activities','Social and emotional skills','Healthy peer connections','Fun, screen-free experiences']" :key="item"><Icon name="leaf"/>{{item}}</li></ul><router-link class="mh-button" :to="path(section==='unplugged'?'join':'unplugged')">{{section==='unplugged'?'Enrollment information':'Explore Unplugged'}} →</router-link></div><aside class="mh-story-note">Real adventures.<br/>Real connections.<br/>Room to grow.<span/></aside></div></section>
    <section v-if="section==='unplugged'" class="mh-section"><div class="mh-wrap"><div class="mh-centered"><p class="mh-eyebrow">Room to explore</p><h2>More connection. Real-life skills.</h2><p>Experiences that make space for curiosity, teamwork, and time together.</p></div><div class="mh-unplugged-experiences"><article v-for="p in programs.slice(0,3)" :key="p.id"><img :src="asset(p.image)" :alt="p.alt" loading="lazy" width="1448" height="1086"/><div><h3>{{p.id==='unplugged'?'Explore the outdoors':p.id==='group-connections'?'Connect with others':'Try something new'}}</h3><p>{{p.body}}</p></div></article></div><div class="mh-pending"><h3>Before your child joins</h3><p>Confirmed age groups, schedules, locations, supervision, costs, and any participation requirements will be shared with enrollment. {{safe(settings.enrollmentUrl)?'See enrollment information for current program options.':'Registration is coming soon until a program is ready to welcome families.'}}</p><router-link class="mh-text-link" :to="path('join')">View enrollment information →</router-link></div></div></section>
    <section v-if="section==='programs'" class="mh-section"><div class="mh-wrap"><div class="mh-centered"><p class="mh-eyebrow">Our program areas</p><h2>Different paths. A brighter tomorrow.</h2><p>Real experiences. Practical skills. Meaningful connections.</p></div><div class="mh-program-grid"><article v-for="(p,i) in programs" :key="p.id"><img :src="asset(p.image)" :alt="p.alt" width="1448" height="1086" loading="lazy"/><span class="mh-icon-circle" :class="'mh-color-'+i"><Icon :name="p.icon"/></span><div><h3>{{p.title}}</h3><p>{{p.body}}</p><a :href="`#${p.id}`" class="mh-text-link">Learn more →</a></div></article></div><div class="mh-program-details"><article v-for="p in programs" :id="p.id" :key="p.id"><Icon :name="p.icon"/><div><h2>{{p.title}}</h2><p>{{p.detail}}</p><router-link class="mh-text-link" :to="path(p.id==='unplugged'?'unplugged':'join')">{{p.id==='unplugged'?'Explore the series':'Check enrollment information'}} →</router-link></div></article></div></div></section>
    <section v-if="!section||section==='impact'" class="mh-impact"><div class="mh-wrap mh-centered"><p class="mh-eyebrow">Our purpose</p><h2>Kids thrive when they’re supported.</h2><div class="mh-four"><article v-for="[icon,title,body] in outcomes" :key="title"><Icon :name="icon"/><h3>{{title}}</h3><p>{{body}}</p></article></div><router-link v-if="!section" class="mh-text-link" :to="path('impact')">Explore our purpose →</router-link><div v-else class="mh-report-note"><h3>Our impact story is taking shape.</h3><p>Verified program outcomes, partner counts, and community stories will be published here as they become available.</p></div></div></section>
    <section v-if="section==='about'" class="mh-section mh-community"><div class="mh-wrap mh-centered"><p class="mh-eyebrow">Who we serve</p><h2>Kids. Families. Schools. Communities.</h2><div class="mh-four"><article v-for="[icon,title,body] in audiences" :key="title"><Icon :name="icon"/><h3>{{title}}</h3><p>{{body}}</p></article></div></div></section>
    <section v-if="section==='resources'" class="mh-section"><div class="mh-wrap"><div class="mh-centered"><p class="mh-eyebrow">Start with a little curiosity</p><h2>Questions worth asking.</h2></div><div class="mh-resource-grid"><article v-for="[title,body] in resources" :key="title"><Icon name="chat"/><h3>{{title}}</h3><p>{{body}}</p></article></div><router-link class="mh-button" :to="path('programs')">Explore our programs →</router-link></div></section>
    <section v-if="['donate','join','involved','contact'].includes(section)" class="mh-section"><div class="mh-wrap mh-next-grid"><article v-for="choice in choices" :key="choice.title" class="mh-next-card"><Icon :name="choice.icon"/><h2>{{choice.title}}</h2><p>{{choice.body}}</p><a v-if="safe(settings[choice.field])" class="mh-button" :href="safe(settings[choice.field])" @click="guardPreview">{{choice.action}} →</a><div v-else class="mh-pending" role="status"><span/>Coming soon<p>{{choice.pending}}</p></div></article></div><p v-if="previewNotice" class="mh-wrap" role="status">{{previewNotice}}</p></section>
    <section v-if="!['donate','join','contact'].includes(section)" class="mh-section"><div class="mh-wrap mh-two"><article class="mh-involvement" :style="{'--mh-image':`url(${asset('impact')})`}"><div><h2>Be part of<br/>something bigger.</h2><p>Help create more opportunities for kids to connect and grow.</p><router-link class="mh-button" :to="path('donate')">Support our mission →</router-link></div></article><article class="mh-involvement" :style="{'--mh-image':`url(${asset('teamwork')})`}"><div><h2>Join the movement.</h2><p>Volunteer, partner, or help share the mission.</p><router-link class="mh-button mh-outline" :to="path('involved')">Get involved →</router-link></div></article></div></section>
    <section v-if="section||safe(settings.ctaImageUrl)" class="mh-final" :style="{'--mh-banner':`url(${JSON.stringify(safe(settings.ctaImageUrl)||asset('about'))})`}"><div class="mh-wrap"><h2>Stronger kids. Brighter tomorrows.</h2><p>More connection. More opportunity. A place to belong.</p><router-link class="mh-button" :to="path('programs')">Explore our programs →</router-link></div></section>
   </template>
  </main>
  <footer class="mh-footer"><div class="mh-wrap"><div class="mh-footer-top"><router-link :to="path('')"><img :src="safe(settings.footerLogoUrl)||asset('logo-white')" alt="MH4Kidz"/></router-link><nav aria-label="Footer"><router-link v-for="[label,slug] in nav" :key="slug" :to="path(slug)">{{label}}</router-link></nav><p class="mh-scribble">Kids today.<br/>Brighter tomorrows.</p></div><div class="mh-footer-bottom"><small>© {{new Date().getFullYear()}} MH4Kidz.</small><nav aria-label="Legal"><router-link :to="path('privacy')">Privacy</router-link><router-link :to="path('terms')">Terms</router-link><router-link :to="path('contact')">Contact</router-link></nav></div></div></footer>
 </div>
</template>
<script setup>
import PublicWebsiteProviderLinks from "../../components/public/PublicWebsiteProviderLinks.vue";
import DOMPurify from 'dompurify';
import {marked} from 'marked';
import {computed,ref,nextTick,watch} from 'vue';
import Icon from '../../components/rise/RiseIcon.vue';
import {useStandalonePublicWebsite,publicWebsiteUrl as safe} from '../../composables/useStandalonePublicWebsite';
const {page,loading,error,menuOpen,section,settings,path,load,previewNotice,guardPreview,closeMenu}=useStandalonePublicWebsite('mh4kidz','MH4Kidz | Stronger kids. Brighter tomorrows.');
const nav=[['Home',''],['About','about'],['Our programs','programs'],['Get involved','involved'],['Impact','impact'],['Resources','resources'],['Contact','contact']];
const asset=name=>`/assets/mh4kidz/${name}.webp`;
const heroes={
 '':['Home','Real connections.\nBrighter paths.','','Experiential and group-oriented programs that help kids build skills, confidence, resilience, and meaningful connections.','home'],
 about:['About','About MH4Kidz','Real experiences. Lasting possibilities.','Helping kids build skills, confidence, and resilience through experiences that get them out, engaged, and connected.','about'],
 programs:['Our programs','Our programs','Real experiences. Real skills.','Experiential and group-based programs that help kids grow in real life, with real people, in real environments.','home'],
 unplugged:['The Unplugged Series','The Unplugged Series','Explore. Connect. Grow. Belong.','Nature-based experiences and practical life skills, with time to connect beyond the screen.','home'],
 impact:['Impact','Our impact','Real kids. Real opportunities. A brighter tomorrow.','We believe every child deserves opportunities to connect, build confidence, and explore their potential. Our mission centers on expanding access to meaningful support.','impact'],
 involved:['Get involved','Join the movement.','','Families, schools, and community partners can help create brighter possibilities for kids.','about'],
 donate:['Support our mission','Invest in kids.','Strengthen communities.','Your interest in supporting kids and families matters. Find the latest donation information below.','impact'],
 join:['Enrollment','A new adventure awaits.','','Explore the next steps for joining a program. Enrollment and schedules will be shared when they are ready.','home'],
 resources:['Resources','Room to grow.','','A starting point for families exploring experiential and group programs.','about'],
 contact:['Contact','Let’s connect.','','Find the available ways to reach MH4Kidz and get involved with our mission.','about']};
heroes.privacy=['Privacy','Privacy information','','Information for our community.','about'];
heroes.terms=['Terms','Terms & information','','Details for visiting and using this website.','about'];
const customPage=computed(()=>page.value?.branding?.contentPages?.find(p=>p.slug===section.value));
const hero=computed(()=>{
 const base=heroes[section.value]||(customPage.value?.title?[customPage.value.title,customPage.value.title,'','','about']:null);
 if(!base)return null;
 const custom=section.value?customPage.value:page.value;
 return [base[0],custom?.heroTitle||base[1],base[2],custom?.heroSubtitle||base[3],base[4]];
});
const heroImage=computed(()=>safe(!section.value?page.value?.heroImageUrl:customPage.value?.heroImageUrl)||asset(hero.value?.[4]||'home'));
const imagePosition=value=>/^\d{1,3}(?:\.\d+)?% \d{1,3}(?:\.\d+)?%$/.test(String(value||''))&&String(value).split(' ').every(n=>parseFloat(n)<=100)?value:undefined;
const heroStyle=computed(()=>({'--mh-desktop-position':imagePosition(customPage.value?.heroPosition),'--mh-mobile-position':imagePosition(customPage.value?.heroMobilePosition),'--mh-hero':`url(${JSON.stringify(heroImage.value)})`,'--mh-mobile-hero':`url(${JSON.stringify(!section.value&&safe(settings.value.homeMobileImageUrl)||heroImage.value)})`}));
const customBody=computed(()=>{const raw=String(customPage.value?.body||'').trim();return raw?DOMPurify.sanitize(marked.parse(raw,{async:false}),{FORBID_TAGS:['form','input','button','textarea','select','style','iframe']}):'';});
const searchOpen=ref(false),searchQuery=ref(''),searchInput=ref(null),searchButton=ref(null);
const searchResults=computed(()=>{
 const entries=[...nav.map(([title,slug])=>({title,href:path(slug)})),{title:'The Unplugged Series',href:path('unplugged')},{title:'Enrollment',href:path('join')},{title:'Donations',href:path('donate')},...programs.map(p=>({title:p.title,href:`${path('programs')}#${p.id}`})),...(page.value?.branding?.contentPages||[]).filter(p=>p.title&&p.slug).map(p=>({title:p.title,href:path(p.slug)}))];
 const q=searchQuery.value.trim().toLowerCase();return [...new Map(entries.map(e=>[e.href,e])).values()].filter(e=>!q||e.title.toLowerCase().includes(q)).slice(0,10);
});
async function toggleSearch(){searchOpen.value=!searchOpen.value;if(searchOpen.value){menuOpen.value=false;await nextTick();searchInput.value?.focus();}}
function closeHeader(e){if(searchOpen.value){searchOpen.value=false;searchButton.value?.focus();}else closeMenu(e);}
watch(section,()=>searchOpen.value=false);

const pillars=[['people','Experiential learning','Real-world experiences that build practical skills.'],['people','Group support','Connection, belonging, and growth together.'],['leaf','Screen-free focus','Activities that encourage presence and purpose.'],['heart','Greater access','A mission to create more opportunities for support.'],['mountain','Stronger futures','Helping kids build resilience for tomorrow.']];
const mission=[['target','Our mission','Empower kids to grow, connect, and thrive through experiential and group-oriented programs.'],['leaf','Our vision','A community where kids can access support and opportunities to reach their potential.'],['people','Our purpose','Build real-life skills and meaningful connections beyond the screen.'],['heart','Our values','Inclusion. Connection. Experiential learning. Equity. Community. Hope.']];
const programs=[
 {id:'unplugged',title:'The Unplugged Series',image:'unplugged',icon:'mountain',alt:'Children hiking together on a forest trail',body:'Nature-based group experiences that make room for connection beyond electronics.',detail:'Outdoor adventures, hands-on activities, peer connection, and practical skills. Program dates, age groups, locations, and enrollment details will be confirmed when registration opens.'},
 {id:'group-connections',title:'Group Connections',image:'groups',icon:'people',alt:'Children and a facilitator gathered outdoors',body:'Group experiences focused on emotional skills, confidence, and belonging.',detail:'Opportunities to practice communication and connection in a supportive group. Specific groups, facilitators, and eligibility will be shared when enrollment opens.'},
 {id:'skill-builders',title:'Skill Builders',image:'skills',icon:'target',alt:'A child wearing a helmet on a climbing wall',body:'Hands-on experiences that encourage problem-solving, teamwork, and resilience.',detail:'Practical activities that give kids room to try, learn, and build confidence. Activities and participation requirements will be described with each program.'},
 {id:'healthy-habits',title:'Healthy Habits',image:'habits',icon:'heart',alt:'Children playing together in a grassy field',body:'Movement, mindfulness, and activities that support everyday well-being.',detail:'Experiences designed around movement, reflection, and everyday habits. Confirm the available activities and any accommodations with the program team.'},
 {id:'community-events',title:'Community Events',image:'events',icon:'mountain',alt:'A group gathered around a campfire at sunset',body:'Shared adventures and community experiences that bring kids together.',detail:'Upcoming events and their locations, schedules, registration requirements, and supervision details will be published when they are ready.'}
];
const outcomes=[['people','Stronger connections','Room for friendships and belonging.'],['heart','Growing confidence','Opportunities to try, learn, and grow.'],['leaf','Practical skills','Experiences that carry into everyday life.'],['mountain','Brighter possibilities','A shared commitment to kids and communities.']];
const audiences=[['people','Children & teens','Building skills for today and tomorrow.'],['heart','Families','Stronger support systems.'],['mountain','Schools','Partners in access and opportunity.'],['people','Communities','Growing connection, together.']];
const resources=[['What will my child do?','Ask about the activities, group size, age range, supervision, and goals of a specific program.'],['What should we bring?','Follow the program’s confirmed instructions for clothing, supplies, transportation, and arrival.'],['Is a program a good fit?','Share your child’s needs and ask about accommodations, eligibility, and what participation involves.'],['When can we enroll?','Program schedules and enrollment details will be published when registration is ready.']];
const choices=computed(()=>{
 const all=[{title:'Support our mission',icon:'heart',field:'donationUrl',action:'Continue to donations',body:'Help make space for meaningful experiences and greater access to support.',pending:'Online donations are not open yet. No payment information is collected here.'},{title:'Join a program',icon:'mountain',field:'enrollmentUrl',action:'Begin enrollment',body:'Find opportunities for kids to explore, connect, and grow.',pending:'Registration, program schedules, and eligibility details will be shared when enrollment opens.'},{title:'Partner or volunteer',icon:'people',field:'partnerUrl',action:'Explore getting involved',body:'Bring your community, time, or ideas to a shared mission.',pending:'Partnership and volunteer inquiries will open here.'},{title:'Contact MH4Kidz',icon:'chat',field:'contactUrl',action:'Contact the team',body:'Connect with the team about our mission and programs.',pending:'Contact options will be published when they are ready.'}];
 return section.value==='donate'?[all[0]]:section.value==='join'?[all[1]]:section.value==='contact'?[all[3]]:all;
});
</script>
<style src="../../styles/mh4kidzWebsite.css"></style>
