<template>
 <div class="mh-site">
  <a class="mh-skip" href="#mh-main">Skip to content</a>
  <header class="mh-header" @keydown.esc="closeMenu"><router-link :to="path('')" aria-label="MH4Kidz home"><img :src="safe(page?.branding?.logoUrl)||asset('logo')" alt="MH4Kidz — Stronger kids. Brighter tomorrows."/></router-link><button class="mh-menu" :aria-expanded="menuOpen" aria-controls="mh-nav" @click="menuOpen=!menuOpen">{{menuOpen?'Close ×':'Menu ☰'}}</button><nav id="mh-nav" :class="{'is-open':menuOpen}" aria-label="Primary"><router-link v-for="[label,slug] in nav" :key="slug" :to="path(slug)" :aria-current="section===slug?'page':undefined">{{label}}</router-link></nav><router-link aria-label="Donate" class="mh-button mh-header-donate" :to="path('donate')">♥ <span>Donate</span></router-link></header>
  <main id="mh-main" tabindex="-1">
   <div v-if="loading" class="mh-state" role="status">Loading MH4Kidz…</div><div v-else-if="error" class="mh-state"><h1>Let’s try that again.</h1><p role="alert">{{error}}</p><button class="mh-button" @click="load">Retry</button></div><div v-else-if="!hero" class="mh-state"><h1>Page not found</h1><router-link class="mh-button" :to="path('')">Go home</router-link></div>
   <template v-else>
    <section class="mh-hero" :class="{'mh-home-hero':!section}" :style="{'--mh-hero':`url(${JSON.stringify(heroImage)})`}"><div class="mh-wrap"><p v-if="section" class="mh-breadcrumb"><router-link :to="path('')">Home</router-link> › {{hero[0]}}</p><div class="mh-hero-copy"><h1>{{!section&&page.heroTitle?page.heroTitle:hero[1]}}</h1><h2 v-if="hero[2]">{{hero[2]}}</h2><p>{{!section&&page.heroSubtitle?page.heroSubtitle:hero[3]}}</p><router-link v-if="!section" class="mh-button" :to="path('involved')">Support our mission <Icon name="arrow"/></router-link><p class="mh-scribble">{{section==='programs'?'Explore. Connect. Grow. Belong.':'Less screens. More life.'}}<span/></p></div></div></section>
    <section v-if="!section||section==='about'" class="mh-section"><div class="mh-wrap mh-pillars" :class="{'mh-mission-band':section==='about'}"><article v-for="([icon,title,body],i) in section==='about'?mission:pillars" :key="title"><span class="mh-icon-circle" :class="'mh-color-'+i"><Icon :name="icon"/></span><h3>{{title}}</h3><p>{{body}}</p></article></div></section>
    <section v-if="['','about','unplugged','impact'].includes(section)" class="mh-section mh-story"><div class="mh-wrap mh-story-grid"><img :src="asset('unplugged')" alt="Children with backpacks exploring a sunlit forest trail" width="1448" height="1086" loading="lazy"/><div><p class="mh-eyebrow">{{section==='about'?'Our story':section==='impact'?'Lasting possibilities':'Our signature program'}}</p><h2>{{section==='about'?'A brighter path starts here.':section==='impact'?'More than numbers.':'The Unplugged Series'}}</h2><p>{{section==='about'?'Kids deserve to feel seen, supported, and connected. MH4Kidz brings a focus on real-world experiences, meaningful relationships, and opportunities to grow.':section==='impact'?'Our purpose is bigger than a number. We want to help kids find stronger connections, more confidence, and a sense of belonging in their communities.':'Nature-based and experiential group programs that help kids practice emotional regulation, teamwork, confidence, and mindfulness — with room to connect beyond their screens.'}}</p><ul class="mh-checklist"><li v-for="item in ['Outdoor adventures','Hands-on activities','Social and emotional skills','Healthy peer connections','Fun, screen-free experiences']" :key="item"><Icon name="leaf"/>{{item}}</li></ul><router-link class="mh-button" :to="path(section==='unplugged'?'join':'unplugged')">{{section==='unplugged'?'Enrollment information':'Explore Unplugged'}} →</router-link></div><aside class="mh-story-note">Real adventures.<br/>Real connections.<br/>Room to grow.<span/></aside></div></section>
    <section v-if="section==='programs'" class="mh-section"><div class="mh-wrap"><div class="mh-centered"><p class="mh-eyebrow">Our program areas</p><h2>Different paths. A brighter tomorrow.</h2><p>Real experiences. Practical skills. Meaningful connections.</p></div><div class="mh-program-grid"><article v-for="(p,i) in programs" :key="p.id"><img :src="asset(p.image)" :alt="p.alt" width="1448" height="1086" loading="lazy"/><span class="mh-icon-circle" :class="'mh-color-'+i"><Icon :name="p.icon"/></span><div><h3>{{p.title}}</h3><p>{{p.body}}</p><a :href="`#${p.id}`" class="mh-text-link">Learn more →</a></div></article></div><div class="mh-program-details"><article v-for="p in programs" :id="p.id" :key="p.id"><Icon :name="p.icon"/><div><h2>{{p.title}}</h2><p>{{p.detail}}</p><router-link class="mh-text-link" :to="path(p.id==='unplugged'?'unplugged':'join')">{{p.id==='unplugged'?'Explore the series':'Check enrollment information'}} →</router-link></div></article></div></div></section>
    <section v-if="!section||section==='impact'" class="mh-impact"><div class="mh-wrap mh-centered"><p class="mh-eyebrow">Our purpose</p><h2>Kids thrive when they’re supported.</h2><div class="mh-four"><article v-for="[icon,title,body] in outcomes" :key="title"><Icon :name="icon"/><h3>{{title}}</h3><p>{{body}}</p></article></div><router-link v-if="!section" class="mh-text-link" :to="path('impact')">Explore our purpose →</router-link><div v-else class="mh-report-note"><h3>Our impact story is taking shape.</h3><p>Verified program outcomes, partner counts, and community stories will be published here as they become available.</p></div></div></section>
    <section v-if="section==='about'" class="mh-section mh-community"><div class="mh-wrap mh-centered"><p class="mh-eyebrow">Who we serve</p><h2>Kids. Families. Schools. Communities.</h2><div class="mh-four"><article v-for="[icon,title,body] in audiences" :key="title"><Icon :name="icon"/><h3>{{title}}</h3><p>{{body}}</p></article></div></div></section>
    <section v-if="section==='resources'" class="mh-section"><div class="mh-wrap"><div class="mh-centered"><p class="mh-eyebrow">Start with a little curiosity</p><h2>Questions worth asking.</h2></div><div class="mh-resource-grid"><article v-for="[title,body] in resources" :key="title"><Icon name="chat"/><h3>{{title}}</h3><p>{{body}}</p></article></div><router-link class="mh-button" :to="path('programs')">Explore our programs →</router-link></div></section>
    <section v-if="['donate','join','involved','contact'].includes(section)" class="mh-section"><div class="mh-wrap mh-next-grid"><article v-for="choice in choices" :key="choice.title" class="mh-next-card"><Icon :name="choice.icon"/><h2>{{choice.title}}</h2><p>{{choice.body}}</p><a v-if="safe(settings[choice.field])" class="mh-button" :href="safe(settings[choice.field])" @click="guardPreview">{{choice.action}} →</a><div v-else class="mh-pending" role="status"><span/>Coming soon<p>{{choice.pending}}</p></div></article></div><p v-if="previewNotice" class="mh-wrap" role="status">{{previewNotice}}</p></section>
    <section v-if="!['donate','join','contact'].includes(section)" class="mh-section"><div class="mh-wrap mh-two"><article class="mh-involvement" :style="{'--mh-image':`url(${asset('impact')})`}"><div><h2>Be part of<br/>something bigger.</h2><p>Help create more opportunities for kids to connect and grow.</p><router-link class="mh-button" :to="path('donate')">Support our mission →</router-link></div></article><article class="mh-involvement" :style="{'--mh-image':`url(${asset('teamwork')})`}"><div><h2>Join the movement.</h2><p>Volunteer, partner, or help share the mission.</p><router-link class="mh-button mh-outline" :to="path('involved')">Get involved →</router-link></div></article></div></section>
    <section v-if="section" class="mh-final" :style="{'--mh-banner':`url(${JSON.stringify(safe(settings.ctaImageUrl)||asset('about'))})`}"><div class="mh-wrap"><h2>Stronger kids. Brighter tomorrows.</h2><p>More connection. More opportunity. A place to belong.</p><router-link class="mh-button" :to="path('programs')">Explore our programs →</router-link></div></section>
   </template>
  </main>
  <footer class="mh-footer"><div class="mh-wrap"><div class="mh-footer-top"><router-link :to="path('')"><img :src="asset('logo-white')" alt="MH4Kidz"/></router-link><nav aria-label="Footer"><router-link v-for="[label,slug] in nav" :key="slug" :to="path(slug)">{{label}}</router-link></nav><p class="mh-scribble">Kids today.<br/>Brighter tomorrows.</p></div><div class="mh-footer-bottom"><small>© {{new Date().getFullYear()}} MH4Kidz.</small><router-link :to="path('contact')">Contact</router-link></div></div></footer>
 </div>
</template>
<script setup>
import {computed} from 'vue';
import Icon from '../../components/rise/RiseIcon.vue';
import {useStandalonePublicWebsite,publicWebsiteUrl as safe} from '../../composables/useStandalonePublicWebsite';
const {page,loading,error,menuOpen,section,settings,path,load,previewNotice,guardPreview,closeMenu}=useStandalonePublicWebsite('mh4kidz','MH4Kidz | Stronger kids. Brighter tomorrows.');
const nav=[['Home',''],['About','about'],['Our programs','programs'],['Get involved','involved'],['Impact','impact'],['Resources','resources'],['Contact','contact']];
const asset=name=>`/assets/mh4kidz/${name}.webp`;
const heroes={
 '':['Home','Real connections.\nBrighter paths.','','Experiential and group-oriented programs that help kids build skills, confidence, resilience, and meaningful connections.','home'],
 about:['About','About MH4Kidz','Real experiences. Lasting possibilities.','Helping kids build skills, confidence, and resilience through experiences that get them out, engaged, and connected.','about'],
 programs:['Our programs','Our programs','Real experiences. Real skills.','Experiential and group-based programs that help kids grow in real life, with real people, in real environments.','home'],
 unplugged:['The Unplugged Series','The Unplugged Series','Explore. Connect. Grow. Belong.','Nature-based experiences and practical life skills, with time to connect beyond the screen.','home'],
 impact:['Impact','Our impact','Real kids. Real opportunities. A brighter tomorrow.','We believe every child deserves opportunities to connect, build confidence, and explore their potential. Our mission centers on expanding access to meaningful support.','impact'],
 involved:['Get involved','Join the movement.','','Families, schools, and community partners can help create brighter possibilities for kids.','about'],
 donate:['Support our mission','Invest in kids.','Strengthen communities.','Your interest in supporting kids and families matters. Find the latest donation information below.','impact'],
 join:['Enrollment','A new adventure awaits.','','Explore the next steps for joining a program. Enrollment and schedules will be shared when they are ready.','home'],
 resources:['Resources','Room to grow.','','A starting point for families exploring experiential and group programs.','about'],
 contact:['Contact','Let’s connect.','','Find the available ways to reach MH4Kidz and get involved with our mission.','about']};
const hero=computed(()=>heroes[section.value]);
const heroImage=computed(()=>safe(!section.value?page.value?.heroImageUrl:page.value?.branding?.contentPages?.find(p=>p.slug===section.value)?.heroImageUrl)||asset(hero.value?.[4]||'home'));
const pillars=[['people','Experiential learning','Real-world experiences that build practical skills.'],['people','Group support','Connection, belonging, and growth together.'],['leaf','Screen-free focus','Activities that encourage presence and purpose.'],['heart','Greater access','A mission to create more opportunities for support.'],['mountain','Stronger futures','Helping kids build resilience for tomorrow.']];
const mission=[['target','Our mission','Empower kids to grow, connect, and thrive through experiential and group-oriented programs.'],['leaf','Our vision','A community where kids can access support and opportunities to reach their potential.'],['people','Our purpose','Build real-life skills and meaningful connections beyond the screen.'],['heart','Our values','Inclusion. Connection. Experiential learning. Equity. Community. Hope.']];
const programs=[
 {id:'unplugged',title:'The Unplugged Series',image:'unplugged',icon:'mountain',alt:'Children hiking together on a forest trail',body:'Nature-based group experiences that make room for connection beyond electronics.',detail:'Outdoor adventures, hands-on activities, peer connection, and practical skills. Program dates, age groups, locations, and enrollment details will be confirmed when registration opens.'},
 {id:'group-connections',title:'Group Connections',image:'groups',icon:'people',alt:'Children and a facilitator gathered outdoors',body:'Group experiences focused on emotional skills, confidence, and belonging.',detail:'Opportunities to practice communication and connection in a supportive group. Specific groups, facilitators, and eligibility will be shared when enrollment opens.'},
 {id:'skill-builders',title:'Skill Builders',image:'skills',icon:'target',alt:'A child wearing a helmet on a climbing wall',body:'Hands-on experiences that encourage problem-solving, teamwork, and resilience.',detail:'Practical activities that give kids room to try, learn, and build confidence. Activities and participation requirements will be described with each program.'},
 {id:'healthy-habits',title:'Healthy Habits',image:'habits',icon:'heart',alt:'Children playing together in a grassy field',body:'Movement, mindfulness, and activities that support everyday well-being.',detail:'Experiences designed around movement, reflection, and everyday habits. Confirm the available activities and any accommodations with the program team.'},
 {id:'community-events',title:'Community Events',image:'events',icon:'mountain',alt:'A group gathered around a campfire at sunset',body:'Shared adventures and community experiences that bring kids together.',detail:'Upcoming events and their locations, schedules, registration requirements, and supervision details will be published when they are ready.'}
];
const outcomes=[['people','Stronger connections','Room for friendships and belonging.'],['heart','Growing confidence','Opportunities to try, learn, and grow.'],['leaf','Practical skills','Experiences that carry into everyday life.'],['mountain','Brighter possibilities','A shared commitment to kids and communities.']];
const audiences=[['people','Children & teens','Building skills for today and tomorrow.'],['heart','Families','Stronger support systems.'],['mountain','Schools','Partners in access and opportunity.'],['people','Communities','Growing connection, together.']];
const resources=[['What will my child do?','Ask about the activities, group size, age range, supervision, and goals of a specific program.'],['What should we bring?','Follow the program’s confirmed instructions for clothing, supplies, transportation, and arrival.'],['Is a program a good fit?','Share your child’s needs and ask about accommodations, eligibility, and what participation involves.'],['When can we enroll?','Program schedules and enrollment details will be published when registration is ready.']];
const choices=computed(()=>{
 const all=[{title:'Support our mission',icon:'heart',field:'donationUrl',action:'Continue to donations',body:'Help make space for meaningful experiences and greater access to support.',pending:'Online donations are not open yet. No payment information is collected here.'},{title:'Join a program',icon:'mountain',field:'enrollmentUrl',action:'Begin enrollment',body:'Find opportunities for kids to explore, connect, and grow.',pending:'Registration, program schedules, and eligibility details will be shared when enrollment opens.'},{title:'Partner or volunteer',icon:'people',field:'partnerUrl',action:'Explore getting involved',body:'Bring your community, time, or ideas to a shared mission.',pending:'Partnership and volunteer inquiries will open here.'},{title:'Contact MH4Kidz',icon:'chat',field:'contactUrl',action:'Contact the team',body:'Connect with the team about our mission and programs.',pending:'Contact options will be published when they are ready.'}];
 return section.value==='donate'?[all[0]]:section.value==='join'?[all[1]]:section.value==='contact'?[all[3]]:all;
});
</script>
<style src="../../styles/mh4kidzWebsite.css"></style>
