<template>
 <div class="nlu-site" @click="previewClick">
  <a class="nlu-skip" href="#nlu-main">Skip to content</a>
  <header ref="header" class="nlu-header" @keydown.esc="closeNavigation" @focusout="leaveHeader">
   <router-link class="nlu-brand" to="/p/nlu" aria-label="Next Level Up home"><img :src="safe(page?.branding?.logoUrl)||asset('logo.png')" alt="Next Level Up — Learning and Counseling Centers"/></router-link>
   <button ref="menuButton" class="nlu-menu" :aria-expanded="menuOpen" aria-controls="nlu-nav" @click="menuOpen=!menuOpen">{{menuOpen?'Close ×':'Menu ☰'}}</button>
   <nav id="nlu-nav" :class="{'is-open':menuOpen}" aria-label="Primary">
    <router-link v-for="[label,to] in nav" :key="to" :to="path(to)" :aria-current="section===to?'page':undefined">{{label}}</router-link>
    <div class="nlu-families" @mouseenter="hoverFamilies" @mouseleave="leaveFamilies"><button ref="familiesButton" :aria-expanded="familiesOpen" aria-controls="nlu-families-menu" @click="familiesOpen=!familiesOpen">For Families <span aria-hidden="true">⌄</span></button>
     <div v-if="familiesOpen" id="nlu-families-menu" class="nlu-mega">
      <div v-for="[title,body,icon,links] in nluFamilies" :key="title" class="nlu-mega-column"><Icon :name="icon"/><h2>{{title}}</h2><p>{{body}}</p><router-link v-for="[label,to] in links" :key="to" :to="to.startsWith('/')?to:path(to)" @click="familiesOpen=false">{{label}} <span aria-hidden="true">›</span></router-link></div>
      <div class="nlu-mega-feature"><img :src="asset('family.png')" alt="A family talking with a counselor"/><h2>Not sure where to start?</h2><p>We’ll listen, answer your questions, and help you find the right path.</p><router-link class="nlu-button" :to="path('get-started')">Compare services →</router-link><router-link class="nlu-button nlu-light" :to="path('contact')">Talk with our team →</router-link></div>
      <div class="nlu-mega-bottom">Personalized support <span>Family-centered care</span><span>Qualified providers</span><span>Flexible options</span></div>
     </div>
    </div>
    <router-link :to="path('about')" :aria-current="section==='about'?'page':undefined">About</router-link>
    <PublicResourcesMenu :resources-path="path('resources')"/>
   </nav>
   <router-link class="nlu-button nlu-header-cta" :to="path('get-started')">Get started →</router-link>
  </header>
  <main id="nlu-main">
   <div v-if="loading" class="nlu-wrap nlu-status" role="status">Loading Next Level Up…</div>
   <div v-else-if="error" class="nlu-wrap nlu-status" role="alert"><p>{{error}}</p><button class="nlu-button" @click="load">Try again</button></div>
   <div v-else-if="!hero" class="nlu-wrap nlu-status"><h1>Page not found</h1><router-link class="nlu-button" to="/p/nlu">Back to Next Level Up →</router-link></div>
   <template v-else>
    <section class="nlu-hero" data-analytics-id="hero" :class="{'nlu-hero-home':section==='home'}" :style="heroStyle"><div class="nlu-wrap"><div class="nlu-hero-copy"><p class="nlu-eyebrow">{{hero.eyebrow}}</p><h1>{{hero.title}}</h1><h2>{{hero.subtitle}}</h2><p>{{hero.body}}</p><span v-if="section==='academic-acceleration'" class="nlu-badge">Coming soon</span><div class="nlu-actions"><router-link class="nlu-button" :to="section==='get-started'?path('get-started#start'):section==='academic-acceleration'?path('contact'):path('get-started')">{{section==='academic-acceleration'?'Request program information':'Get started'}} →</router-link><router-link class="nlu-button nlu-outline" :to="section==='therapy-tutoring'?path('how-it-works'):section==='home'?path('contact'):path('providers')">{{section==='therapy-tutoring'?'How the program works':section==='home'?'Talk with our team':'Find the right provider'}} →</router-link></div></div><p class="nlu-script">Small steps.<br/>Big possibilities.</p></div></section>
    <section class="nlu-trust nlu-wrap" data-analytics-id="care-values"><div v-for="[icon,title,body] in trust" :key="title"><Icon :name="icon"/><div><strong>{{title}}</strong><small>{{body}}</small></div></div></section>

    <section v-if="['home','about','get-started','therapy-tutoring'].includes(section)" class="nlu-section nlu-wash" data-analytics-id="service-paths"><div class="nlu-wrap"><div class="nlu-section-heading"><p class="nlu-eyebrow">Three ways we support students</p><h2>{{section==='therapy-tutoring'?'Bridging the Gap for a Brighter Future':'Choose the Right Path'}}</h2><p>Different needs. Personalized support. One student at the center.</p></div><div class="nlu-three"><article v-for="service in nluServices" :key="service.slug" class="nlu-card nlu-service" :class="{'nlu-signature':service.slug==='therapy-tutoring'}" :data-analytics-id="service.slug"><img v-if="service.slug==='therapy-tutoring'" class="nlu-symbol" :src="asset('icon.png')" alt=""/><Icon v-else :name="service.icon"/><span v-if="service.slug==='therapy-tutoring'" class="nlu-badge">Our integrated approach</span><h3>{{service.title}}</h3><strong>{{service.subtitle}}</strong><p>{{service.body}}</p><ul><li v-for="item in service.items" :key="item">{{item}}</li></ul><router-link class="nlu-button" :to="path(service.slug)">Learn more →</router-link></article></div></div></section>

    <section v-if="section==='about'" class="nlu-wrap nlu-section" data-analytics-id="mission-story"><div class="nlu-two"><article class="nlu-card"><Icon name="target"/><h2>Our Mission</h2><h3>Help students thrive — in school and in life.</h3><p>We provide individualized learning and counseling support that considers both academic goals and the emotional, behavioral, or executive-functioning barriers that can affect school success.</p></article><article class="nlu-card"><Icon name="mountain"/><h2>Our Story</h2><h3>More than one type of support.</h3><p>Next Level Up brings together educational and mental health support around a simple belief: some students need more than one path forward. We work with families to connect the right people, skills, and services.</p></article></div><div class="nlu-section-heading"><h2>Every Student’s Path Is Unique</h2><p>Meet students where they are. Build on strengths. Adjust support as they grow.</p></div><div class="nlu-three"><article v-for="[title,body] in studentPaths" :key="title" class="nlu-card"><h3>{{title}}</h3><p>{{body}}</p></article></div></section>

    <section v-if="['home','tutoring'].includes(section)" class="nlu-wrap nlu-section" data-analytics-id="featured-academic-program"><div class="nlu-two nlu-feature"><div class="nlu-card"><p class="nlu-eyebrow">Featured program · coming soon</p><h2>Next Level Academic Acceleration Program</h2><strong>Eight weeks. Sixteen focused sessions. One individualized path forward.</strong><p>An intensive reading and math pathway with a clear learning plan, targeted instruction, repeated practice, and progress monitoring.</p><router-link class="nlu-button" :to="path('academic-acceleration')">Explore the program →</router-link></div><div class="nlu-mountain-card" :style="bannerStyle"><div v-for="[icon,number,label] in [['calendar','8','Weeks'],['people','16','Individual sessions'],['school','Reading + Math','Tailored to the learner']]" :key="label"><Icon :name="icon"/><strong>{{number}}</strong><span>{{label}}</span></div><p>Real support. Real skills.<br/>A path forward.</p></div></div></section>

    <section v-if="section==='tutoring'" class="nlu-wrap nlu-section" data-analytics-id="tutoring-approach"><div class="nlu-section-heading"><h2>More Than Just Homework Help</h2><p>Understand how your student learns, identify gaps, and practice strategies for long-term progress.</p></div><div class="nlu-six"><article v-for="[icon,title] in tutoringValues" :key="title" class="nlu-card nlu-mini"><Icon :name="icon"/><h3>{{title}}</h3></article></div><div class="nlu-two nlu-space"><div><h2>Who Is Tutoring For?</h2><p>Students who need help in a particular subject, want to strengthen foundational skills, or benefit from a structured plan and an encouraging learning partner.</p></div><div><h2>Flexible Support</h2><ul><li>Ongoing individual tutoring</li><li>Subject-specific instruction and homework support</li><li>Study skills and executive-functioning support</li><li>Preparation for the next grade or learning goal</li></ul></div></div></section>

    <section v-if="['tutoring','academic-acceleration'].includes(section)" class="nlu-wrap nlu-section" data-analytics-id="academic-skills"><h2>Subjects We Support</h2><p>Instruction is tailored to the student’s current skills and goals.</p><div class="nlu-two"><article v-for="([title,icon,items],i) in nluSkills" :key="title" class="nlu-card nlu-skill-card"><img :src="asset(i?'learning.png':'student.png')" alt="Student working on a learning activity" loading="lazy"/><div><Icon :name="icon"/><h3>{{title}}</h3><ul><li v-for="item in items" :key="item">{{item}}</li></ul></div></article></div></section>

    <section v-if="section==='academic-acceleration'" class="nlu-wrap nlu-section" data-analytics-id="academic-program-details"><div class="nlu-two"><article class="nlu-card nlu-navy"><h2>This Is More Than Tutoring</h2><p>Start with what the student knows, where the gaps are, and which skills can make the greatest difference.</p><p>The planned program combines evaluation, individualized planning, targeted instruction, repeated practice, and family communication.</p><p>The aim is a stronger, more capable, and more confident learner.</p></article><div><h2>Every Student Starts With a Plan</h2><p>An Individualized Learning Plan connects the starting point to meaningful goals.</p><ol class="nlu-plan"><li v-for="item in ['Understand current skills','Identify learning gaps','Prioritize goals','Choose ways to measure progress','Plan next steps']" :key="item">{{item}}</li></ol><h3>Developed with licensed teachers</h3><p>Teacher input helps guide instructional priorities, learning goals, strategies, and progress reviews.</p></div></div></section>

    <section v-if="section==='counseling'" class="nlu-wrap nlu-section" data-analytics-id="counseling-support"><div class="nlu-section-heading"><p class="nlu-eyebrow">What counseling can help with</p><h2>More Than Just Talking.</h2><p>A supportive space to build understanding, practice skills, and work toward your student’s goals.</p></div><div class="nlu-three"><article v-for="[icon,title,items] in counselingAreas" :key="title" class="nlu-card"><Icon :name="icon"/><h3>{{title}}</h3><ul><li v-for="item in items" :key="item">{{item}}</li></ul></article></div><div class="nlu-two nlu-space"><img class="nlu-rounded" :src="asset('learning.png')" alt="A student looking ahead with confidence" loading="lazy"/><div><h2>When the Barrier to Learning Is More Than the Lesson.</h2><p>Some students benefit from counseling alone. Others also need academic support. Our integrated approach connects the services that fit your student’s needs.</p><router-link class="nlu-button" :to="path('therapy-tutoring')">Explore our integrated approach →</router-link></div></div></section>

    <section v-if="section==='therapy-tutoring'" class="nlu-wrap nlu-section" data-analytics-id="learning-barriers"><div class="nlu-section-heading"><h2>Understand the Barrier. Build the Skill.</h2><p>Academic and emotional challenges can show up together. A coordinated plan helps us address what is getting in the way.</p></div><div class="nlu-three"><article class="nlu-card"><Icon name="heart"/><h3>Common barriers</h3><ul><li v-for="item in ['Stress and worry','Attention and organization','Emotional regulation','Confidence and self-esteem','School avoidance','Frustration and persistence']" :key="item">{{item}}</li></ul></article><article class="nlu-card nlu-signature"><img class="nlu-symbol" :src="asset('icon.png')" alt=""/><h3>Connect the support</h3><p>Build academic skills while practicing coping, emotional regulation, and strategies for daily learning.</p><router-link class="nlu-button" :to="path('how-it-works')">How the program works →</router-link></article><article class="nlu-card"><Icon name="school"/><h3>In school and everyday life</h3><ul><li v-for="item in ['Starting and completing tasks','Managing frustration','Following routines','Staying organized','Asking for support','Building independence']" :key="item">{{item}}</li></ul></article></div><div class="nlu-note">Services are matched to the student’s needs and each provider’s training, qualifications, and scope of practice.</div><h2 class="nlu-space">Different Providers. A Shared Plan.</h2><div class="nlu-three"><article v-for="[title,body] in providerRoles" :key="title" class="nlu-card"><Icon name="people"/><h3>{{title}}</h3><p>{{body}}</p></article></div></section>

    <section v-if="['home','how-it-works','get-started','counseling'].includes(section)" class="nlu-section nlu-wash" data-analytics-id="process"><div class="nlu-wrap"><div class="nlu-section-heading"><h2>{{section==='counseling'?'How Counseling Works':'A Simple Path to Meaningful Progress'}}</h2><p>We’re with you every step of the way.</p></div><div class="nlu-steps"><article v-for="([title,body,icon],i) in nluSteps" :key="title" class="nlu-card"><span class="nlu-step-number">{{i+1}}</span><Icon :name="icon"/><h3>{{title}}</h3><p>{{body}}</p></article></div></div></section>

    <section v-if="section==='how-it-works'" class="nlu-wrap nlu-section" data-analytics-id="program-services"><h2>What Services May Be Included?</h2><p>Every plan is tailored to the learner. Services depend on the student’s needs and the provider’s qualifications.</p><div class="nlu-three"><article v-for="service in nluServices" :key="service.slug" class="nlu-card"><Icon :name="service.icon"/><h3>{{service.title}}</h3><ul><li v-for="item in service.items" :key="item">{{item}}</li></ul></article></div><div class="nlu-two nlu-space"><article class="nlu-card"><h2>Insurance & Payment Options</h2><p>Our team can help you understand which services may be covered by your plan and which use self-pay. Coverage, eligibility, and fees are confirmed before services begin.</p><router-link :to="path('contact')">Ask about coverage and rates →</router-link></article><article class="nlu-card"><h2>Your Family Is Part of the Process</h2><p>We discuss goals, review progress, and adjust support together. Academic support and clinical services are delivered within each provider’s qualifications and scope.</p></article></div></section>

    <section v-if="section==='learning-center'" class="nlu-wrap nlu-section" data-analytics-id="learning-center-programs"><div class="nlu-section-heading"><h2>What Would You Like to Learn?</h2><p>K–12 individual tutoring is available now. Additional programs are coming soon.</p></div><div class="nlu-four"><article v-for="[title,icon,body,items,to,available] in nluLearning" :key="title" class="nlu-card" :class="{'nlu-signature':available}"><Icon :name="icon"/><span class="nlu-badge" :class="{'nlu-available':available}">{{available?'Available now':'Coming soon'}}</span><h3>{{title}}</h3><p>{{body}}</p><ul><li v-for="item in items" :key="item">{{item}}</li></ul><router-link :to="path(to)">{{available?'Find the right tutor':to==='contact'?'Ask about future programs':'Explore the program'}} →</router-link></article></div><div class="nlu-two nlu-space nlu-card"><img class="nlu-rounded" :src="asset('student.png')" alt="Student practicing reading and writing" loading="lazy"/><div><p class="nlu-eyebrow">What’s available now?</p><h2>K–12 Individual Tutoring</h2><p>Personalized support for your student’s current learning goals, with room to grow.</p><router-link class="nlu-button" to="/nlu/find-tutor">Find the right tutor →</router-link><h3 class="nlu-space">Not sure what they need?</h3><p>We can help you understand the starting point and explore the next step.</p><router-link :to="path('contact')">Talk about a learning evaluation →</router-link></div></div></section>

    <section v-if="['home','counseling','providers','about','tutoring'].includes(section)" class="nlu-wrap nlu-section" data-analytics-id="providers"><div class="nlu-heading-row"><div><p class="nlu-eyebrow">Our providers</p><h2>A Team That Cares</h2></div><router-link v-if="section!=='providers'" :to="path('providers')">Meet our providers →</router-link></div><div class="nlu-provider-controls"><label>Service<select v-model="providerType" aria-label="Service"><option value="counseling">Counseling</option><option value="tutoring">Tutoring</option></select></label><label v-if="section==='providers'">Search providers<input v-model="search" type="search" placeholder="Search by name, specialty, or subject"/></label><router-link :to="`/nlu/find-${providerType==='tutoring'?'tutor':'counselor'}`">Full directory & availability →</router-link></div><p v-if="providersLoading" role="status">Loading providers…</p><p v-else-if="providersError" role="alert">Provider information is temporarily unavailable. <button @click="loadProviders">Try again</button></p><div v-else-if="visibleProviders.length" class="nlu-provider-grid"><article v-for="p in visibleProviders" :key="p.id" class="nlu-card nlu-provider" :data-analytics-id="'provider-'+providerType+'-'+p.id"><img v-if="safe(p.profilePhotoUrl)" :src="safe(p.profilePhotoUrl)" :alt="p.displayName" loading="lazy"/><div v-else class="nlu-avatar" aria-hidden="true"><Icon name="people"/></div><h3>{{p.displayName}}</h3><p>{{p.title}}</p><p class="nlu-provider-bio">{{p.profile?.publicBlurb||p.tutoringProfile?.bio||''}}</p><div class="nlu-tags"><span v-for="tag in providerTags(p)" :key="tag">{{tag}}</span></div><router-link class="nlu-button" :to="`/nlu/provider/${p.id}?serviceType=${providerType}`">View profile →</router-link></article></div><p v-else>Our provider profiles are being updated. <router-link :to="path('contact')">Contact our team for help finding support.</router-link></p></section>

    <section v-if="section==='get-started'" id="start" class="nlu-wrap nlu-section" data-analytics-id="enrollment"><div class="nlu-section-heading"><h2>Tell Us Where You’d Like to Start</h2><p>Choose a service to open its enrollment options. If you’re unsure, our team can help.</p></div><div class="nlu-three"><article class="nlu-card"><Icon name="school"/><h3>Start tutoring</h3><p>Share your student’s learning needs and goals.</p><router-link class="nlu-button" to="/join/nlu/tutoring">Tutoring enrollment →</router-link></article><article class="nlu-card"><Icon name="heart"/><h3>Start counseling</h3><p>Explore counseling and complete your intake.</p><router-link class="nlu-button" to="/join/nlu/counseling">Counseling enrollment →</router-link></article><article class="nlu-card"><Icon name="chat"/><h3>Explore combined support</h3><p>Talk about academic and emotional needs together.</p><router-link class="nlu-button" :to="path('contact')">Talk with our team →</router-link></article></div></section>

    <section v-if="['get-started','resources'].includes(section)" class="nlu-wrap nlu-section" data-analytics-id="family-resources"><h2>What Families May Need Before Starting</h2><div class="nlu-four"><router-link v-for="[title,to,icon] in resourceLinks" :key="title" class="nlu-card nlu-resource" :to="to"><Icon :name="icon"/><h3>{{title}}</h3><span aria-hidden="true">→</span></router-link></div><div id="insurance" class="nlu-note"><h3>Insurance & Billing</h3><p>Check the provider’s profile and ask our team about coverage, costs, and self-pay options. Insurance coverage for counseling does not automatically include tutoring.</p><router-link :to="path('contact')">Ask our team →</router-link></div><h2 id="faqs" class="nlu-space">Parent FAQs</h2><details v-for="[question,answer] in nluFaqs" :key="question" class="nlu-faq"><summary>{{question}} <span aria-hidden="true">+</span></summary><p>{{answer}}</p></details></section>

    <section v-if="section==='contact'" class="nlu-wrap nlu-section nlu-contact" data-analytics-id="contact"><h2>Message Our Team</h2><p>Our support team can help with service questions and next steps.</p><PublicAgencySupportForm v-if="!preview" agency-slug="nlu" join-path="/p/nlu/get-started" login-path="/nlu/login" accent="#087f8c"/><p v-else class="nlu-note">Open the published website to send a message.</p></section>

    <section v-if="section!=='contact'" class="nlu-final" :style="bannerStyle" data-analytics-id="footer-cta"><div class="nlu-wrap"><div><p class="nlu-eyebrow">Higher potential. Brighter tomorrows.</p><h2>{{section==='learning-center'?'Start With the Learner. Build the Path.':'Help Your Student Reach the Next Level.'}}</h2><p>Academic support. Emotional support. A path forward.</p><div class="nlu-actions"><router-link class="nlu-button" :to="path('get-started')">Get started →</router-link><router-link class="nlu-button nlu-outline" :to="path('contact')">Talk with our team →</router-link></div></div><p class="nlu-script">Higher potential<br/>starts here.</p></div></section>
   </template>
  </main>
  <footer class="nlu-footer"><div class="nlu-wrap"><router-link to="/p/nlu"><img :src="asset('logo.png')" alt="Next Level Up"/></router-link><nav aria-label="Footer"><router-link v-for="[label,to] in footerNav" :key="to" :to="to.startsWith('/')?to:path(to)">{{label}}</router-link></nav><small>© {{new Date().getFullYear()}} Next Level Up Learning and Counseling Centers.</small></div></footer>
  <router-link v-if="section!=='contact'" class="nlu-support" :to="path('contact')"><Icon name="chat"/>Talk with our team</router-link>
  <p v-if="previewNotice" class="nlu-preview-notice" role="status">{{previewNotice}}</p>
 </div>
</template>
<script setup>
import { computed,ref,watch,onMounted,onUnmounted } from 'vue';
import api from '../../services/api';
import Icon from '../../components/rise/RiseIcon.vue';
import PublicResourcesMenu from '../../components/public/PublicResourcesMenu.vue';
import PublicAgencySupportForm from '../../components/public/PublicAgencySupportForm.vue';
import {useStandalonePublicWebsite,publicWebsiteUrl as safe} from '../../composables/useStandalonePublicWebsite';
import {nluHeroes,nluServices,nluSteps,nluLearning,nluSkills,nluFaqs,nluFamilies} from '../../constants/nluWebsite';
const {route,page,loading,error,menuOpen,settings,path,load,preview,previewNotice,guardPreview}=useStandalonePublicWebsite('nlu','Next Level Up | Learning and Counseling Centers');
const aliases={'':'home','therapy-plus-tutoring':'therapy-tutoring','cognitive-emotional-enrichment':'therapy-tutoring','programs':'learning-center','next-level-learning-center':'learning-center','academic-acceleration-program':'academic-acceleration','for-families':'resources','join':'get-started'};
const section=computed(()=>aliases[String(route.params.section||'')]||String(route.params.section));
const asset=name=>'/assets/nlu/'+name;
const hero=computed(()=>{const h=nluHeroes[section.value];if(!h)return null;const custom=settings.value.pages?.[section.value]||{};return{eyebrow:custom.eyebrow||h[0],title:custom.title||(section.value==='home'?page.value?.heroTitle:null)||h[1],subtitle:custom.subtitle||h[2],body:custom.body||(section.value==='home'?page.value?.heroSubtitle:null)||h[3],image:safe(custom.imageUrl)||(section.value==='home'?safe(page.value?.heroImageUrl):'')||asset(h[4])};});
const heroStyle=computed(()=>({'--nlu-hero':`url(${JSON.stringify(hero.value?.image||'')})`}));
const bannerStyle=computed(()=>({'--nlu-banner':`url("${safe(settings.value.ctaImageUrl)||asset('mountains.png')}")`}));
const nav=[['Home',''],['Tutoring','tutoring'],['Counseling','counseling'],['Therapy + Tutoring','therapy-tutoring'],['Programs','learning-center'],['Providers','providers']];
const footerNav=[...nav,['About','about'],['How it works','how-it-works'],['Get started','get-started'],['Contact','contact'],['Careers','/careers/nlu'],['Client portal','/nlu/login'],['Privacy','/nlu/privacypolicy'],['Terms','/nlu/terms']];
const trust=[['people','Individualized support','Tailored to the student'],['heart','Family-centered care','We’re in this together'],['shield','Qualified providers','Support matched to your needs'],['screen','Flexible options','In-person and virtual care']];
const tutoringValues=[['target','Targeted instruction'],['leaf','Skill development'],['calendar','Repeated practice'],['chart','Strategy building'],['shield','Progress monitoring'],['people','Parent communication']];
const counselingAreas=[['heart','Emotional Support',['Stress and worry','Mood concerns','Confidence and self-esteem','Coping with overwhelm']],['target','Behavior & Regulation',['Emotional regulation','Frustration tolerance','Coping skills','Behavior challenges']],['school','School & Life Challenges',['School stress','Social skills','Life transitions','Family changes']]];
const studentPaths=[['Mostly tutoring','A student who needs help with reading, math, or study skills may work with a tutor on academic goals.'],['Coordinated support','A student facing both academic and emotional challenges may benefit from an integrated plan.'],['Mostly counseling','A student navigating stress or life changes may begin with counseling and add academic support as needed.']];
const providerRoles=[['Academic & skills specialists','Academic instruction, study strategies, organization, and learning support.'],['Behavioral health providers','Skill development and behavioral support within their qualifications and supervision requirements.'],['Counselors & therapists','Clinical support delivered by appropriately qualified professionals, with supervision when required.']];
const resourceLinks=[['New family information',path('get-started'),'people'],['Forms & enrollment',path('get-started#start'),'calendar'],['Find a provider',path('providers'),'target'],['Client portal','/nlu/login','screen']];
const header=ref(),menuButton=ref(),familiesButton=ref(),familiesOpen=ref(false);
function hoverFamilies(){if(window.innerWidth>1100&&window.matchMedia('(hover: hover)').matches)familiesOpen.value=true;}
function closeNavigation(){familiesOpen.value=false;menuOpen.value=false;(window.innerWidth<=1100?menuButton:familiesButton).value?.focus();}
function leaveFamilies(e){if(!e.currentTarget.contains(document.activeElement))familiesOpen.value=false;}
function leaveHeader(e){if(!header.value?.contains(e.relatedTarget))familiesOpen.value=false;}
function outside(e){if(!header.value?.contains(e.target))familiesOpen.value=false;}
function previewClick(e){if(preview&&e.target.closest('a')&&!e.target.closest('a').getAttribute('href')?.startsWith('/p/nlu'))guardPreview(e);}
const providerType=ref('counseling'),providers=ref([]),providersLoading=ref(false),providersError=ref(false),search=ref('');let providerGeneration=0;
const providerTags=p=>[...new Set(providerType.value==='tutoring'?(p.tutoringProfile?.subjectAreas||[]):p.specialties||[])].slice(0,3);
const visibleProviders=computed(()=>{const q=search.value.toLowerCase().trim();const list=providers.value.filter(p=>!q||`${p.displayName} ${p.title} ${providerTags(p).join(' ')}`.toLowerCase().includes(q));return section.value==='providers'?list:list.slice(0,4);});
async function loadProviders(){const id=++providerGeneration;providers.value=[];providersLoading.value=true;providersError.value=false;try{const{data}=await api.get(`/public/agency-services/nlu/${providerType.value==='tutoring'?'tutors':'counselors'}`,{skipAuthRedirect:true,skipGlobalLoading:true});if(id===providerGeneration)providers.value=data.providers||[];}catch{if(id===providerGeneration)providersError.value=true;}finally{if(id===providerGeneration)providersLoading.value=false;}}
watch(providerType,loadProviders);
watch(section,()=>{familiesOpen.value=false;menuOpen.value=false;search.value='';providerType.value=section.value==='tutoring'?'tutoring':'counseling';});
watch([section,loading],()=>{if(!loading.value&&!error.value&&['home','providers','about','counseling','tutoring'].includes(section.value))loadProviders();},{immediate:true});
onMounted(()=>document.addEventListener('pointerdown',outside));onUnmounted(()=>{providerGeneration++;document.removeEventListener('pointerdown',outside);});
</script>
<style src="../../styles/nluWebsite.css"></style>
