<template>
  <div class="plotline-surface pl-site">
    <a class="pl-skip" href="#plotline-main">Skip to content</a>
    <header class="pl-site-header">
      <router-link :to="pageUrl()" class="pl-logo" aria-label="Plotline by PlotTwistCo home"><img :src="asset('brand/logos/plotline-primary-transparent.webp')" alt="Plotline by PlotTwistCo" width="170" height="68"></router-link>
      <button class="pl-menu-toggle" :aria-expanded="menuOpen" aria-controls="pl-main-nav" @click="menuOpen=!menuOpen">{{ menuOpen ? 'Close' : 'Menu' }} <span aria-hidden="true">{{ menuOpen ? '×' : '☰' }}</span></button>
      <nav id="pl-main-nav" :class="{open:menuOpen}" aria-label="Plotline main navigation">
        <router-link v-for="item in navigation" :key="item" :to="pageUrl(item)" :aria-current="section===item?'page':undefined">{{ titleCase(item) }}</router-link>
        <div class="pl-nav-actions"><a :href="signIn" class="pl-button pl-button--secondary">Sign in</a><router-link :to="pageUrl('start')" class="pl-button">Get started <span aria-hidden="true">→</span></router-link></div>
      </nav>
    </header>
    <main id="plotline-main" tabindex="-1">
      <template v-if="section==='home'">
        <section class="pl-home-hero pl-wide">
          <div class="pl-hero-copy"><p class="pl-eyebrow">People operations, reimagined</p><h1>People have<br>a journey.<br><em>Plotline brings<br>it to life.</em></h1><p class="pl-lead">From the first application to what’s next. Bring hiring, onboarding, training, and people growth into one thoughtful workspace.</p><div class="pl-actions"><router-link :to="pageUrl('product')" class="pl-button">See the platform →</router-link><router-link :to="pageUrl('start')" class="pl-button pl-button--secondary">Request a demo</router-link></div><ul class="pl-assurances"><li>One connected journey</li><li>Your people, front and center</li></ul></div>
          <div class="pl-hero-art"><img class="pl-hero-person" :src="asset('photos/reference/home-hero-portrait-reference.jpg')" alt="A woman looking toward the mountains in warm evening light" fetchpriority="high" width="358" height="393"><img class="pl-hero-line" :src="asset('brand/motifs/plotline-journey-line.svg')" alt=""><PlotlineProductExample class="pl-hero-dashboard" screen="hiring" title="Hiring dashboard" eager/><div class="pl-art-note"><span class="pl-sparkle" aria-hidden="true">✦</span><span>Every person.<br>Every possibility.</span></div></div>
        </section>
        <section class="pl-principles pl-wide" aria-label="The Plotline approach"><span class="pl-eyebrow">Made for the people<br>behind your mission</span><p>From <strong>first hello</strong></p><span class="pl-principles-line" aria-hidden="true"></span><p>To <strong>what’s next</strong></p><span class="pl-principles-end">One people operations workspace.</span></section>
        <section class="pl-wide pl-section"><div class="pl-section-heading"><div><p class="pl-eyebrow">One journey. Every next step.</p><h2>Everything your team<br>needs to <em>grow.</em></h2></div><p>Great work starts with supported people. Bring the pieces of their journey together, so your team can keep moving forward.</p></div><div class="pl-pillar-grid"><article v-for="item in solutions.slice(0,5)" :key="item.id" class="pl-pillar"><img class="pl-pillar-photo" :src="`/assets/plotline/examples/${item.screen}.jpg`" alt="" loading="lazy" width="180" height="83"><span class="pl-icon"><img :src="icon(item.icon)" alt=""></span><h3>{{ item.short }}</h3><p>{{ item.body }}</p><router-link :to="solutionUrl(item.id)" class="pl-text-link">Explore {{ item.short.toLowerCase() }} →</router-link></article></div></section>
        <section class="pl-partner pl-wide"><div><p class="pl-eyebrow">A better way for people operations</p><h2>More than software.<br>A partner in <em>what’s next.</em></h2><p>Plotline is a product of PlotTwistCo, built around the work of supporting people. It brings your people operations into focus—with a home of its own and room to connect.</p><router-link :to="pageUrl('about')" class="pl-button">Meet Plotline →</router-link></div><img :src="asset('photos/reference/people-collaboration.jpg')" alt="Colleagues sharing a conversation" loading="lazy" width="1400" height="1105"></section>
        <section class="pl-wide pl-section pl-brand-first"><div><p class="pl-eyebrow">Your organization. Your story.</p><h2>A careers experience<br>that feels like <em>you.</em></h2><p>Your name, your logo, your opportunities. Give applicants a welcoming place to meet your organization, with subtle Plotline support from application to onboarding.</p><router-link :to="solutionUrl('recruiting')" class="pl-text-link">Meet your next great teammate →</router-link></div><PlotlineProductExample screen="careers" title="Company careers page"/></section>
      </template>
      <template v-else-if="section==='product'">
        <section class="pl-wide pl-page-hero"><div><p class="pl-eyebrow">The Plotline platform</p><h1>Every stage.<br>Every person.<br><em>One plotline.</em></h1><p class="pl-lead">Bring the people journey into view—from the first application to the next opportunity to grow.</p><div class="pl-actions"><router-link :to="pageUrl('start')" class="pl-button">Request a walkthrough →</router-link><router-link :to="pageUrl('pricing')" class="pl-button pl-button--secondary">Explore pricing</router-link></div></div><div class="pl-suite"><p class="pl-eyebrow">A connected people workspace</p><h2>The tools behind<br><em>a better journey.</em></h2><div class="pl-suite-grid"><router-link v-for="item in suite" :key="item.name" :to="solutionUrl(item.id)"><span class="pl-icon"><img :src="icon(item.icon)" alt=""></span><strong>{{ item.name }}</strong><small>{{ item.body }}</small></router-link></div></div></section>
        <section class="pl-product-stage pl-wide"><div><p class="pl-eyebrow">Plotline in view</p><h2>One platform.<br>A more <em>human</em><br>workplace.</h2><p>A thoughtful home for the everyday work of helping people do their best.</p></div><PlotlineProductExample screen="hiring" title="Hiring dashboard"/></section>
        <section class="pl-wide pl-section"><div class="pl-section-heading"><div><p class="pl-eyebrow">From potential to progress</p><h2>Less scattered.<br><em>More connected.</em></h2></div><p>Follow the journey through hiring, onboarding, learning, people records, and development.</p></div><div class="pl-feature-grid"><article v-for="item in solutions.slice(0,5)" :key="item.id"><PlotlineProductExample :screen="item.screen" :title="item.screenTitle"/><h3>{{ item.title }}</h3><p>{{ item.body }}</p><router-link :to="solutionUrl(item.id)" class="pl-text-link">Explore this chapter →</router-link></article></div><p class="pl-caption">These examples are captured from the actual application using fictional records.</p></section>
        <section class="pl-ecosystem pl-wide"><p class="pl-eyebrow">Part of something connected</p><h2>Choose Plotline.<br>Connect <em>what you need.</em></h2><p>Start with people operations on its own. When your organization uses other eligible PlotTwistCo products, ask us about a connected setup and savings on your Plotline subscription.</p><div class="pl-ecosystem-grid"><article v-for="item in products" :key="item.name"><h3>{{ item.name }}</h3><p>{{ item.body }}</p></article></div><router-link :to="pageUrl('pricing')" class="pl-button">See bundle savings →</router-link><small>Product access and cross-product setup are confirmed for your organization during implementation.</small></section>
      </template>
      <template v-else-if="section==='solutions'">
        <section class="pl-wide pl-page-hero"><div><p class="pl-eyebrow">Solutions for your team</p><h1>People operations<br>for <em>real-world<br>organizations.</em></h1><p class="pl-lead">A single organization or a growing network. A new hire or a new chapter. Find the support your people need along the way.</p><a href="#solutions" class="pl-button">Find your solution ↓</a></div><PlotlineProductExample class="pl-solutions-hero" screen="organizations" title="Multi-organization hiring pipeline" eager/></section>
        <section id="solutions" class="pl-wide pl-section"><div class="pl-filter" role="group" aria-label="Filter people operations solutions"><button :aria-pressed="selectedSolution==='all'" @click="selectSolution('all')">All solutions</button><button v-for="item in solutions" :key="item.id" :aria-pressed="selectedSolution===item.id" @click="selectSolution(item.id)">{{ item.title }}</button></div><div class="pl-section-heading"><div><p class="pl-eyebrow">Your people, supported</p><h2>A connected<br><em>people operations suite.</em></h2></div><p>Keep your organization’s identity at the heart of every step.</p></div><p class="pl-sr-only" aria-live="polite">{{ filteredSolutions.length }} solutions shown</p><article v-for="item in filteredSolutions" :key="item.id" class="pl-solution-row"><div><span class="pl-icon"><img :src="icon(item.icon)" alt=""></span><p class="pl-eyebrow">{{ item.title }}</p><h3>{{ item.line }}</h3><p>{{ item.body }}</p><ul class="pl-checklist"><li v-for="point in item.points" :key="point">{{ point }}</li></ul><router-link :to="pageUrl('start')" class="pl-text-link">Talk through your workflow →</router-link></div><PlotlineProductExample :screen="item.screen" :title="item.screenTitle"/></article></section>
      </template>
      <template v-else-if="section==='pricing'">
        <section class="pl-wide pl-page-hero pl-pricing-hero"><div><p class="pl-eyebrow">Pricing with room to grow</p><h1>Simple pricing.<br><em>People first.</em></h1><p class="pl-lead">One people operations product. Three ways to bring it into your organization. Start on its own or save when you connect more of your work.</p><p class="pl-price-note">Monthly pricing in USD · 25 active employees included</p></div><div class="pl-pricing-picture"><img :src="asset('photos/reference/portrait-warm.jpg')" alt="A person looking toward new possibilities" width="1400" height="1105"><span>Every person<br>has a plotline. <b aria-hidden="true">✦</b></span></div></section>
        <section class="pl-wide pl-pricing-section" aria-label="Plotline plans and estimate"><PlotlinePricing :start-path="pageUrl('start')"/></section>
        <section class="pl-wide pl-section"><p class="pl-eyebrow">The same people tools. A different way to connect.</p><h2>Find your fit.</h2><div class="pl-comparison"><table><caption class="pl-sr-only">Compare Plotline standalone and bundle plans</caption><thead><tr><th scope="col">What’s included</th><th scope="col">Standalone</th><th scope="col">Connected</th><th scope="col">Suite</th></tr></thead><tbody><tr v-for="feature in comparison" :key="feature"><th scope="row">{{ feature }}</th><td v-for="n in 3" :key="n"><span aria-label="Included">✓</span></td></tr><tr><th scope="row">Other eligible paid products required</th><td>None</td><td>1</td><td>2 or more</td></tr><tr><th scope="row">Monthly Plotline bundle credit</th><td>—</td><td>$50</td><td>$70</td></tr></tbody></table></div></section>
        <section class="pl-wide pl-section pl-pricing-extras"><div><p class="pl-eyebrow">A little extra support</p><h2>Make the start<br><em>your own.</em></h2><p>Need help organizing records, setting up several organizations, or building training content? We’ll scope that work with you.</p><router-link :to="pageUrl('start')" class="pl-text-link">Discuss your setup →</router-link></div><div><article v-for="item in extras" :key="item.title"><img :src="icon(item.icon)" alt=""><div><h3>{{ item.title }}</h3><p>{{ item.body }}</p><small>Quoted separately</small></div></article></div></section>
        <section class="pl-wide pl-section pl-faq"><p class="pl-eyebrow">A little more clarity</p><h2>Your questions, answered.</h2><details v-for="[question,answer] in faqs" :key="question"><summary>{{ question }}<span aria-hidden="true">+</span></summary><p>{{ answer }}</p></details></section>
      </template>
      <template v-else-if="section==='resources'">
        <section class="pl-wide pl-page-hero pl-resource-hero"><div><p class="pl-eyebrow">The next chapter, thoughtfully</p><h1>A little guidance.<br><em>A lot of possibility.</em></h1><p class="pl-lead">Practical starting points for a more thoughtful people journey. Use these guides with your team and make them your own.</p></div><img :src="asset('photos/reference/plant-detail.jpg')" alt="New leaves reaching toward the light" width="1400" height="1379"></section>
        <section class="pl-wide pl-section pl-guides"><article v-for="(guide,i) in guides" :key="guide.id"><span class="pl-guide-number">0{{ i+1 }}</span><div><p class="pl-eyebrow">{{ guide.label }}</p><h2>{{ guide.title }}</h2><p>{{ guide.intro }}</p><details><summary>Read the checklist <span aria-hidden="true">+</span></summary><ol><li v-for="step in guide.steps" :key="step">{{ step }}</li></ol><button class="pl-text-link" @click="downloadGuide(guide)">Download checklist ↓</button></details></div></article></section>
      </template>
      <template v-else-if="section==='about'">
        <section class="pl-wide pl-page-hero"><div><p class="pl-eyebrow">Plotline, by PlotTwistCo</p><h1>People make<br><em>the plot.</em></h1><p class="pl-lead">Behind every organization is a collection of people, possibilities, and next chapters. We believe the tools that support them should feel connected, clear, and human.</p><router-link :to="pageUrl('start')" class="pl-button">Let’s meet →</router-link></div><img class="pl-about-photo" :src="asset('photos/reference/people-collaboration.jpg')" alt="A team connecting in conversation" width="1400" height="1105"></section>
        <section class="pl-wide pl-section pl-about-story"><p class="pl-eyebrow">Every person has a plotline</p><h2>Built around the journey.<br><em>Grounded in the everyday.</em></h2><p>Hiring is a beginning. Onboarding is an introduction. Training opens a door. The everyday work of supporting people connects all of it.</p><p>Plotline brings those chapters into one people operations workspace. It is a PlotTwistCo product with its own identity—ready for organizations that want a focused people platform, and for teams connecting it to more of their work.</p></section>
        <section class="pl-wide pl-values"><article v-for="value in values" :key="value.title"><span class="pl-sparkle" aria-hidden="true">✦</span><h3>{{ value.title }}</h3><p>{{ value.body }}</p></article></section>
        <section class="pl-wide pl-section pl-about-parent"><div><p class="pl-eyebrow">Part of PlotTwistCo</p><h2>A bigger picture.<br>A thoughtful next step.</h2></div><div><p>PlotTwistCo brings products and operational support together for organizations building meaningful work. Plotline is its people operations product, part of Workforce Operations. Strategic Operations supports branding, design, outreach, and content.</p><a href="https://plottwistco.com" class="pl-text-link">Get to know PlotTwistCo ↗</a></div></section>
      </template>
      <section v-else-if="section==='start'" class="pl-wide pl-section pl-start"><div><p class="pl-eyebrow">Your next chapter starts here</p><h1>Let’s build<br><em>what’s next.</em></h1><p class="pl-lead">A better hiring journey. A warmer welcome. More room for people to grow. Tell us where you’d like to begin.</p><ol class="pl-next-steps"><li v-for="(step,i) in nextSteps" :key="step.title"><span>0{{ i+1 }}</span><div><h3>{{ step.title }}</h3><p>{{ step.body }}</p></div></li></ol><p class="pl-small">Already part of the team? <a :href="signIn">Sign in to your workspace →</a></p></div><PlotlineLeadForm/></section>
      <section v-if="section!=='start'" class="pl-closing pl-wide"><img :src="asset('photos/reference/mountain-journey.jpg')" alt="" loading="lazy"><div><p class="pl-eyebrow">Built for meaningful work</p><h2>People make <em>the plot.</em><br>Let’s write what comes next.</h2><p>A great place for people starts with a thoughtful next step.</p><div class="pl-actions"><router-link :to="pageUrl('start')" class="pl-button pl-button--cream">Get started →</router-link><router-link :to="pageUrl('pricing')" class="pl-button pl-button--outline-light">Explore pricing</router-link></div></div><span class="pl-closing-note">A place to begin.<br>A place to belong.<br>A place to grow.</span></section>
    </main>
    <footer class="pl-site-footer pl-wide"><div class="pl-footer-top"><div><router-link :to="pageUrl()" class="pl-logo"><img :src="asset('brand/logos/plotline-primary-transparent.webp')" alt="Plotline by PlotTwistCo" width="170" height="68"></router-link><p>People have a journey.<br>Plotline brings it to life.</p></div><nav aria-label="Explore Plotline"><strong>Explore</strong><router-link v-for="item in navigation" :key="item" :to="pageUrl(item)">{{ titleCase(item) }}</router-link></nav><nav aria-label="Connect with Plotline"><strong>What’s next</strong><router-link :to="pageUrl('start')">Request a demo</router-link><a :href="signIn">Sign in</a><a href="https://plottwistco.com">Meet PlotTwistCo ↗</a></nav><div class="pl-footer-message"><span aria-hidden="true">✦</span><p>Every person<br>has a <em>plotline.</em></p></div></div><div class="pl-footer-bottom"><span>© {{ year }} PlotTwistCo. People operations with possibility.</span><div><a href="https://plottwisthq.com/privacypolicy">Privacy</a><a href="https://plottwisthq.com/terms">Terms</a><router-link :to="pageUrl('start')">Contact</router-link></div></div></footer>
  </div>
</template>
<script setup>
import { computed, ref, watch, nextTick } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import PlotlineProductExample from '../../components/plotline/PlotlineProductExample.vue';
import PlotlinePricing from '../../components/plotline/PlotlinePricing.vue';
import PlotlineLeadForm from '../../components/plotline/PlotlineLeadForm.vue';
import { plotlinePages, plotlineSolutions as solutions, plotlineGuides as guides, plotlineFaqs as faqs } from '../../content/plotlineWebsite';
import { PLOTLINE_WEBSITE_URL, isPlotlineHost } from '../../utils/plotline';
import '../../styles/plotline.css';
import '../../styles/plotlineWebsite.css';
const route=useRoute(),router=useRouter(),menuOpen=ref(false);
const navigation=['product','solutions','resources','about','pricing'];
const section=computed(()=>plotlinePages[route.params.section] ? route.params.section : 'home');
const year=new Date().getFullYear(),asset=path=>`/assets/plotline/website/${path}`,icon=name=>asset(`brand/icons/${name}.svg`);
const titleCase=text=>text.charAt(0).toUpperCase()+text.slice(1),pageUrl=(page='')=>`/plottline${page ? '/'+page : ''}`;
const solutionUrl=id=>({path:pageUrl('solutions'),query:{focus:id},hash:'#solutions'});
const signIn=isPlotlineHost(window.location.hostname) ? '/app' : 'https://app.plottwistco.com/login';
const selectedSolution=computed(()=>solutions.some(s=>s.id===route.query.focus)?route.query.focus:'all');
const filteredSolutions=computed(()=>selectedSolution.value==='all'?solutions:solutions.filter(s=>s.id===selectedSolution.value));
function selectSolution(id){router.replace({path:route.path,query:id==='all'?{}:{focus:id},hash:'#solutions'});}
const suite=[{name:'Careers',icon:'careers',id:'recruiting',body:'Share your story'},{name:'Applicants',icon:'applicants',id:'recruiting',body:'Meet your next teammate'},{name:'Hiring',icon:'hiring',id:'recruiting',body:'Connect the next steps'},{name:'Onboarding',icon:'onboarding',id:'onboarding',body:'Welcome with intention'},{name:'Training',icon:'training',id:'training',body:'Build confidence'},{name:'People',icon:'people',id:'people',body:'Support your team'},{name:'Growth',icon:'growth',id:'growth',body:'Make room for more'},{name:'Documents',icon:'documents',id:'documents',body:'Keep work organized'},{name:'Organizations',icon:'multi-entity',id:'organizations',body:'Stay in context'}];
const products=[{name:'AuricWell',body:'Clinical workflows for the care your organization delivers.'},{name:'SchoolCareBridge',body:'A school-centered connection between schools and care teams.'},{name:'Conversa',body:'Communication tools for the conversations that keep work moving.'}];
const comparison=['Company-branded careers & applications','Hiring & interview workflows','Onboarding & employee documents','Training & learning progress','People records & evaluations','25 active employees per organization','$4 per additional active employee / month'];
const extras=[{icon:'support',title:'Implementation support',body:'Plan your setup, responsibilities, and first steps.'},{icon:'training',title:'Custom training content',body:'Build learning around your organization’s processes.'},{icon:'multi-entity',title:'Organization setup',body:'Map your organization structure and authorized access.'}];
const values=[{title:'Human, from the start.',body:'The person comes first. Thoughtful tools make room for clear communication and a warmer experience.'},{title:'Your story stays yours.',body:'Your organization’s identity leads. Plotline supports the journey quietly and consistently.'},{title:'Connected by design.',body:'Keep the chapters of people operations together, with room to connect more as your organization grows.'}];
const nextSteps=[{title:'Start with your people.',body:'Tell us about your organization and the work you want to simplify.'},{title:'See your possibilities.',body:'Explore the workflows and setup that fit your team.'},{title:'Agree on the next step.',body:'Confirm scope and pricing before activation. No charges here.'}];
watch(()=>route.path,async()=>{menuOpen.value=false;const page=plotlinePages[section.value];document.title=`${section.value==='home'?'Plotline by PlotTwistCo':titleCase(section.value)+' | Plotline'} — ${page.title}`;let meta=document.querySelector('meta[name="description"]');if(!meta){meta=document.createElement('meta');meta.name='description';document.head.append(meta);}meta.content=page.description;let canonical=document.querySelector('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical);}canonical.href=PLOTLINE_WEBSITE_URL+(section.value==='home'?'':'/'+section.value);await nextTick();},{immediate:true});
function downloadGuide(guide){const text=`${guide.title}\nPlotline by PlotTwistCo\n\n${guide.intro}\n\n${guide.steps.map((step,i)=>`${i+1}. [ ] ${step}`).join('\n\n')}\n\n${PLOTLINE_WEBSITE_URL}/resources\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`plotline-${guide.id}-checklist.txt`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
</script>
