<template>
  <div class="ptco-site">
    <a class="ptco-skip" href="#ptco-main">Skip to content</a>
    <header class="ptco-header" @keydown.esc="menuOpen=false"><router-link class="ptco-brand" to="/p/ptco"><img :src="logo" alt=""><span>Plot Twist Co.<small>Businesses for a brighter tomorrow</small></span></router-link>
      <button class="ptco-menu" type="button" :aria-expanded="menuOpen" aria-controls="ptco-nav" @click="menuOpen=!menuOpen">Menu <span aria-hidden="true">☰</span></button>
      <nav id="ptco-nav" :class="{'is-open':menuOpen}" aria-label="Primary" @keydown.esc="menuOpen=false"><router-link v-for="[label,slug] in ptcoNav" :key="slug" :to="`/p/ptco${slug?'/'+slug:''}`" :aria-current="section===slug?'page':undefined" @click="menuOpen=false">{{ label }}</router-link></nav>
      <router-link class="ptco-button ptco-header-cta" to="/p/ptco/start">Let’s talk <PtcoIcon name="arrow"/></router-link>
    </header>
    <main id="ptco-main" tabindex="-1">
      <div v-if="loading" class="ptco-loading" role="status">Loading Plot Twist Co.…</div>
      <div v-else-if="error" class="ptco-loading"><h1>We couldn’t load this page.</h1><p role="alert">{{ error }}</p><button class="ptco-button" @click="load">Try again</button></div>
      <div v-else-if="!knownSection" class="ptco-loading"><h1>Page not found</h1><router-link to="/p/ptco">Return to Plot Twist Co.</router-link></div>
      <template v-else>
        <section class="ptco-hero" :class="`ptco-hero-${section||'home'}`" :style="{'--ptco-hero':`url(${JSON.stringify(hero.image)})`}">
          <div class="ptco-wrap"><div class="ptco-hero-copy"><p class="ptco-eyebrow">{{ hero.kicker }}</p><h1>{{ hero.title }} <em>{{ hero.accent }}</em></h1><p class="ptco-hero-intro">{{ hero.body }}</p><p v-if="hero.note" class="ptco-hero-note">{{ hero.note }}</p><div class="ptco-actions"><router-link class="ptco-button" :to="section==='start'?'#business-intake':'/p/ptco/start'" @click="section==='start'&&scrollToIntake($event)">{{ section==='start'?'Begin intake':section==='about'?'Partner with us':'Get started' }} <PtcoIcon name="arrow"/></router-link><router-link v-if="section!== 'start'" class="ptco-button ptco-button-outline" :to="section==='about'?'/p/ptco/about#partnership':section==='hq'?'/p/ptco/hq#hq-walkthrough':'/p/ptco/hq'">{{ section==='about'?'See our model':section==='hq'?'See the walkthrough':'Explore Plot Twist HQ' }}</router-link></div>
          <div class="ptco-hero-values"><span><PtcoIcon name="people"/>Expert support<br>from setup to scale</span><span><PtcoIcon name="heart"/>A healthier tomorrow<br>for your business</span><span><PtcoIcon name="chart"/>People. Operations.<br>Possibility.</span></div></div></div>
          <small v-if="!section||section==='hq'" class="ptco-preview-label">Illustrative platform preview</small>
        </section>

        <template v-if="!section">
          <section class="ptco-band"><div class="ptco-wrap"><div class="ptco-centered"><p class="ptco-eyebrow">End-to-end business support</p><h2>Everything you need to run and grow</h2><p>From initial setup to long-term growth, we handle the operational details so you can focus on what you do best.</p></div><div class="ptco-services"><router-link v-for="service in ptcoServices" :key="service.id" :to="`/p/ptco/services#${service.id}`" class="ptco-card"><PtcoIcon :name="service.icon"/><h3>{{ service.title }}</h3><p>{{ service.body }}</p></router-link></div></div></section>
          <section class="ptco-band ptco-soft"><div class="ptco-wrap ptco-suite"><div><p class="ptco-eyebrow">Plot Twist HQ</p><h2>The all-in-one<br>management suite</h2><p>Bring your people, workflows, and services together in a workspace that reflects your business.</p><router-link class="ptco-button" to="/p/ptco/hq">Explore Plot Twist HQ →</router-link></div><ul class="ptco-checklist"><li v-for="text in ['Client & guardian workflows','Scheduling & programs','People operations & onboarding','Billing & payment workflows','Public websites & intake','Tenant branding & access']" :key="text"><PtcoIcon name="check"/>{{ text }}</li></ul><blockquote>Less chaos.<br>More clarity.<br>A bigger impact.<small>Tools today.<br>Greater tomorrows.</small></blockquote></div></section>
          <section class="ptco-band"><div class="ptco-wrap"><div class="ptco-centered"><p class="ptco-eyebrow">A longer journey. A brighter tomorrow.</p><h2>We’re with you at every stage</h2><p>From your first step to your next big chapter — and beyond.</p></div><ol class="ptco-timeline"><li v-for="(stage,i) in stages" :key="stage[0]"><span>{{ i+1 }}</span><h3>{{ stage[0] }}</h3><p>{{ stage[1] }}</p></li></ol></div></section>
        </template>

        <template v-if="section==='about'">
          <section class="ptco-band"><div class="ptco-wrap"><div class="ptco-centered"><p class="ptco-eyebrow">A better way for service-based businesses</p><h2>Why Plot Twist Co. exists</h2><p>Your mission deserves support that strengthens what makes your business unique.</p></div><div class="ptco-three"><article v-for="item in principles" :key="item.title" class="ptco-card ptco-horizontal"><PtcoIcon :name="item.icon"/><div><h3>{{ item.title }}</h3><p>{{ item.body }}</p></div></article></div></div></section>
          <section id="partnership" class="ptco-band ptco-soft"><div class="ptco-wrap ptco-model"><div><p class="ptco-eyebrow">Aligned incentives. Real growth.</p><h2>How our partnership model works</h2><p>We start with your goals, agree on the support you need, and build a plan for working together. Scope, responsibilities, and pricing are discussed before a partnership begins.</p><router-link class="ptco-button" to="/p/ptco/start">Let’s discuss your business →</router-link></div><div><div class="ptco-four"><article v-for="[icon,title] in [['chart','Your growth guides the work.'],['people','Your team stays at the center.'],['settings','Systems support your purpose.'],['heart','Your business remains yours.']]" :key="title"><PtcoIcon :name="icon"/><h3>{{ title }}</h3></article></div><div class="ptco-model-flow"><span>Your vision</span><b>→</b><span>Our shared plan</span><b>→</b><span>A stronger business</span></div></div></div></section>
          <section class="ptco-band"><div class="ptco-wrap ptco-model"><div><p class="ptco-eyebrow">Smarter systems. Stronger businesses.</p><h2>Thoughtful technology.<br>Human partnership.</h2><p>Use automation and AI where they help reduce repetitive work. Keep people responsible for the decisions that affect your business and clients.</p></div><div><h3 class="ptco-editorial">AI where it helps. Human partnership where it matters most.</h3><div class="ptco-services"><router-link v-for="s in ptcoServices" :key="s.id" class="ptco-card" :to="`/p/ptco/services#${s.id}`"><PtcoIcon :name="s.icon"/><h3>{{ s.title }}</h3></router-link></div></div></div></section>
        </template>

        <section v-if="section==='services'" class="ptco-band"><div class="ptco-wrap"><div class="ptco-centered"><p class="ptco-eyebrow">Support that fits your business</p><h2>Build a clearer way to work.</h2><p>Start with the support you need today. Plan for the business you want to become.</p></div><div class="ptco-service-details"><article v-for="service in ptcoServices" :id="service.id" :key="service.id" class="ptco-card"><PtcoIcon :name="service.icon"/><h2>{{ service.title }}</h2><p>{{ service.detail }}</p><router-link :to="`/p/ptco/start?service=${service.id}`">Discuss this support →</router-link></article></div></div></section>

        <section v-if="section==='hq'" id="hq-walkthrough" class="ptco-band"><div class="ptco-wrap"><div class="ptco-centered"><p class="ptco-eyebrow">Explore your next workspace</p><h2>Connected work. A clearer picture.</h2><p>Explore the workflows available in Plot Twist HQ. Your setup depends on your services and enabled features.</p></div><div class="ptco-product"><div class="ptco-product-nav" role="group" aria-label="Explore platform areas"><button v-for="feature in ptcoHqFeatures" :key="feature.id" :aria-pressed="activeFeature===feature.id" @click="activeFeature=feature.id"><PtcoIcon :name="feature.icon"/>{{ feature.title }}</button></div><article class="ptco-product-panel" aria-live="polite"><p class="ptco-eyebrow">Workflow walkthrough</p><h2>{{ feature.title }}</h2><p>{{ feature.body }}</p><ol class="ptco-workflow"><li v-for="(step,i) in feature.steps" :key="step"><span>{{ i+1 }}</span>{{ step }}</li></ol><ul class="ptco-checklist"><li v-for="bullet in feature.bullets" :key="bullet"><PtcoIcon name="check"/>{{ bullet }}</li></ul><router-link class="ptco-button" to="/p/ptco/start?path=hq">Request your workspace →</router-link></article></div><div class="ptco-three ptco-product-notes"><article><PtcoIcon name="people"/><h3>Your company has its own workspace</h3><p>Company identity, team access, and service settings belong to the tenant.</p></article><article><PtcoIcon name="shield"/><h3>Access follows responsibility</h3><p>Client, guardian, staff, and administrator experiences are shaped by assigned permissions.</p></article><article><PtcoIcon name="settings"/><h3>Schools are affiliations</h3><p>Connect schools and programs to the company that serves them, with explicit access.</p></article></div><p class="ptco-small">This walkthrough explains workflows; it does not connect to client records or display live business metrics.</p></div></section>

        <section v-if="['','about','industries'].includes(section)" class="ptco-band ptco-soft"><div class="ptco-wrap"><div class="ptco-section-heading"><div><p class="ptco-eyebrow">Industries we serve</p><h2>Different businesses. A shared purpose.</h2></div><p>We support purpose-driven professionals and organizations making a difference in their communities.</p></div><div class="ptco-industries" :class="{'ptco-industries-expanded':section==='industries'}"><router-link v-for="item in ptcoIndustries" :key="item.id" :to="`/p/ptco/start?industry=${item.id}`"><div class="ptco-industry-photo"><img :src="item.image" :alt="`${item.title} collaborating in a workspace`" loading="lazy" width="1536" height="1024"><h3>{{ item.title }}</h3></div><p v-if="section==='industries'">{{ item.body }}</p></router-link></div></div></section>

        <section v-if="section==='resources'" class="ptco-band"><div class="ptco-wrap"><div class="ptco-centered"><p class="ptco-eyebrow">A useful place to start</p><h2>Clarity for your next step</h2><p>Practical guides to prepare for a conversation about your business.</p></div><div class="ptco-three"><article v-for="resource in ptcoResources" :id="resource.id" :key="resource.id" class="ptco-card ptco-resource"><PtcoIcon name="document"/><h2>{{ resource.title }}</h2><p>{{ resource.intro }}</p><ol><li v-for="item in resource.items" :key="item">{{ item }}</li></ol><router-link class="ptco-text-link" to="/p/ptco/start">Talk through your next steps →</router-link></article></div></div></section>

        <template v-if="section==='start'">
          <section class="ptco-band"><div class="ptco-wrap"><div class="ptco-centered"><p class="ptco-eyebrow">Find the right starting point</p><h2>Choose your path</h2><p>Every business is different. Tell us what you need, and we’ll help you take the next step.</p></div><div class="ptco-four ptco-paths"><button v-for="path in ptcoPaths" :key="path.id" class="ptco-card" :aria-pressed="selectedPath===path.id" @click="choosePath(path.id)"><PtcoIcon :name="path.icon"/><h3>{{ path.title }}</h3><p>{{ path.body }}</p><span class="ptco-path-select">{{ selectedPath===path.id?'Selected':'Select →' }}</span></button></div></div></section>
          <div class="ptco-wrap"><PtcoBusinessIntake :preview="previewMode" :path="selectedPath" :industry="String(route.query.industry||'')" :service="String(route.query.service||'')"/></div>
          <section class="ptco-band"><div class="ptco-wrap"><p class="ptco-eyebrow">Common questions</p><h2>You have questions. We have answers.</h2><div class="ptco-three ptco-faq"><details v-for="[q,a] in faqs" :key="q"><summary>{{ q }}</summary><p>{{ a }}</p></details></div></div></section>
        </template>

        <section v-if="!section" class="ptco-band"><div class="ptco-wrap ptco-values"><div><p class="ptco-eyebrow">More than a service</p><h2>A true partnership.</h2></div><article v-for="[icon,title,body] in values" :key="title"><PtcoIcon :name="icon"/><h3>{{ title }}</h3><p>{{ body }}</p></article></div></section>
        <section class="ptco-final"><div class="ptco-wrap"><div><p class="ptco-eyebrow">Your next chapter starts here.</p><h2>Let’s build a brighter tomorrow — together.</h2><p>Get support, useful tools, and a partner who understands your purpose.</p></div><router-link class="ptco-button ptco-button-light" to="/p/ptco/start">Let’s talk →</router-link><span class="ptco-motto">People.<br>Purpose.<br>Possibility.</span></div></section>
      </template>
    </main>
    <footer class="ptco-footer"><div class="ptco-wrap ptco-footer-grid"><router-link class="ptco-brand" to="/p/ptco"><img src="/assets/ptco/logo.webp" alt=""><span>Plot Twist Co.<small>Businesses for a brighter tomorrow</small></span></router-link><nav aria-label="Footer"><h3>Quick links</h3><router-link v-for="[label,slug] in ptcoNav" :key="slug" :to="`/p/ptco${slug?'/'+slug:''}`">{{ label }}</router-link></nav><div><h3>Your next step</h3><router-link to="/p/ptco/start">Contact our team</router-link><router-link to="/p/ptco/hq">Explore Plot Twist HQ</router-link><router-link to="/login">Client & team login</router-link></div><div><h3>Start a conversation</h3><p>Tell us where you are today<br>and where you want to go.</p><router-link class="ptco-button" to="/p/ptco/start">Begin intake →</router-link></div></div><div class="ptco-wrap ptco-footer-bottom"><small>© {{ new Date().getFullYear() }} Plot Twist Co. All rights reserved.</small><small>Different support. A brighter tomorrow.</small></div></footer>
  </div>
</template>
<script setup>
import {computed,onMounted,onUnmounted,ref,watch,nextTick} from 'vue';
import {useRoute} from 'vue-router';
import api from '../../services/api';
import PtcoIcon from '../../components/ptco/PtcoIcon.vue';
import PtcoBusinessIntake from '../../components/ptco/PtcoBusinessIntake.vue';
import {ptcoNav,ptcoServices,ptcoIndustries,ptcoPaths,ptcoHqFeatures,ptcoResources} from '../../constants/ptcoWebsite';
import {safeMarketingHref} from '../../utils/marketingPageQuality';
const route=useRoute(),menuOpen=ref(false),page=ref(null),loading=ref(true),error=ref('');
const section=computed(()=>String(route.params.section||''));
const knownSection=computed(()=>['','about','services','hq','industries','resources','start'].includes(section.value));
const logo=computed(()=>safeMarketingHref(page.value?.branding?.logoUrl)||'/assets/ptco/logo-flat.webp');
const selectedPath=ref('starting');
watch(()=>route.query.path,p=>{if(ptcoPaths.some(x=>x.id===p))selectedPath.value=p;},{immediate:true});
watch(section,()=>{menuOpen.value=false;document.title=`${ptcoNav.find(([,s])=>s===section.value)?.[0]||'Get started'} | Plot Twist Co.`;});
function scrollToIntake(event){event?.preventDefault();document.getElementById('business-intake')?.scrollIntoView({behavior:'smooth',block:'start'});}
function choosePath(path){selectedPath.value=path;scrollToIntake();}
const activeFeature=ref('clients');const feature=computed(()=>ptcoHqFeatures.find(f=>f.id===activeFeature.value));
const heroes={
 '':{kicker:'People. Operations. Possibility.',title:'Build. Manage. Scale.',accent:'Your Next Chapter.',body:'Plot Twist Co. helps service-based businesses — especially mental health agencies — go from idea to impact with expert support and our management app, Plot Twist HQ.',image:'/assets/ptco/home-hero.webp'},
 about:{kicker:'Same purpose. A brighter tomorrow.',title:'Built to Support Your Vision',accent:'— Not Replace It.',body:'We partner with service-based businesses to help them build, manage, and grow without losing ownership of their purpose or identity.',note:'Your business stays yours. We bring the support, systems, and expertise to help it thrive.',image:'/assets/ptco/about-hero.webp'},
 start:{kicker:'Same purpose. A brighter tomorrow.',title:'Let’s Get Your',accent:'Business Moving.',body:'Expert support and a connected workspace for your next chapter. Tell us where you are today and what you need.',note:'From initial setup to long-term operations, we’re with you every step of the way.',image:'/assets/ptco/start-hero.webp'},
 services:{kicker:'Support from setup to scale.',title:'Your Purpose.',accent:'A Stronger Foundation.',body:'Bring clarity to the work behind your business, with support built around your goals, your team, and the people you serve.',image:'/assets/ptco/about-hero.webp'},
 hq:{kicker:'Welcome to Plot Twist HQ',title:'Your Business.',accent:'Connected.',body:'Bring client workflows, people operations, scheduling, and billing into one workspace. Explore how the parts fit together.',image:'/assets/ptco/home-hero.webp'},
 industries:{kicker:'Different businesses. A shared purpose.',title:'For the People',accent:'Who Help People.',body:'Support for mental health agencies, consultants, coaches, tutors, and other purpose-driven service businesses.',image:'/assets/ptco/about-hero.webp'},
 resources:{kicker:'A little clarity goes a long way.',title:'Prepare for Your',accent:'Next Chapter.',body:'Practical starting points for launching a business, improving operations, and planning your move to a connected workspace.',image:'/assets/ptco/start-hero.webp'}
};
const hero=computed(()=>{const h={...(heroes[section.value]||heroes[''])};const custom=section.value ? page.value?.branding?.contentPages?.find(p=>p.slug===section.value) : page.value; if(custom?.heroImageUrl)h.image=safeMarketingHref(custom.heroImageUrl)||h.image;if(custom?.heroTitle){h.title=custom.heroTitle;h.accent='';if(h.title.endsWith('Your Next Chapter.')){h.title=h.title.slice(0,-18).trim();h.accent='Your Next Chapter.';}}if(custom?.heroSubtitle)h.body=custom.heroSubtitle;return h;});
const previewMode=window.parent!==window&&route.query.marketingPreview==='1';
let loadId=0;
async function load(){const id=++loadId;loading.value=true;error.value='';try{const {data}=await api.get('/public/marketing-pages/ptco',{skipAuthRedirect:true,skipGlobalLoading:true});if(id===loadId)page.value=data.page;}catch{if(id===loadId)error.value='The site is temporarily unavailable. Please try again.';}finally{if(id===loadId)loading.value=false;}}
function receive(event){if(previewMode&&event.origin===location.origin&&event.source===window.parent&&event.data?.type==='marketing-preview'&&event.data.page?.slug==='ptco'){page.value=event.data.page;loading.value=false;}}
onMounted(async()=>{document.title='Plot Twist Co. | Your Next Chapter';window.addEventListener('message',receive);if(previewMode)window.parent.postMessage({type:'marketing-preview-ready'},location.origin);else await load();await nextTick();if(route.hash&&!route.hash.startsWith('#invite='))document.getElementById(route.hash.slice(1))?.scrollIntoView();});
onUnmounted(()=>{loadId++;window.removeEventListener('message',receive);});
const stages=[['Start your business','Set up with expert guidance and a strong foundation.'],['Build operations','Put systems, people, and processes in place.'],['Manage growth','Streamline, optimize, and adapt as you grow.'],['Scale smarter','Expand your impact with strategic support.'],['Prepare for the future','Build for long-term opportunities.']];
const principles=[{icon:'shield',title:'Support without takeover',body:'Your purpose, culture, and business identity belong to you. Our role is to strengthen them.'},{icon:'settings',title:'Systems that serve your vision',body:'Build practical processes around your mission and the way your team works.'},{icon:'people',title:'A partner, not a replacement',body:'Stay in control with a partner who brings support, perspective, and shared commitment.'}];
const values=[['clock','Greater efficiency','Reduce repetitive work.'],['bulb','More clarity','Understand your next steps.'],['shield','Clear responsibilities','Know who owns each process.'],['chart','Better organization','Keep your work connected.'],['heart','Ongoing support','A team in your corner.']];
const faqs=[['Who does Plot Twist Co. support?','We work with service-based businesses, especially mental health agencies, as well as consultants, coaches, tutors, and other purpose-driven organizations.'],['Is Plot Twist HQ included?','We will discuss whether Plot Twist HQ fits your needs, which features you need, and the scope and pricing before you commit.'],['Can you help an established business?','Yes. Tell us what is working, where the friction is, and what you would like to improve. We can discuss a transition or a focused support plan.']];
</script>
<style src="../../styles/ptcoWebsite.css"></style>
