<template>
  <div class="scb-site scb-complete-site" :class="`scb-page-${section||'home'}`">
    <a class="scb-skip" href="#scb-main">Skip to content</a>
    <header class="scb-header">
      <SchoolCareBridgeBrand :logo="safe(page?.branding?.logoUrl)"/>
      <button class="scb-menu" :aria-expanded="menuOpen" aria-controls="scb-nav" @click="menuOpen=!menuOpen">Menu</button>
      <nav id="scb-nav" :class="{'scb-open':menuOpen}" aria-label="Main navigation" @keydown.esc="menuOpen=false"><router-link v-for="[label,slug] in nav" :key="slug" :to="path(slug)" :aria-current="section===slug?'page':undefined">{{label}}</router-link></nav>
      <a class="scb-button scb-outline" :href="demoUrl">Try the portal</a><router-link class="scb-button" :to="schoolCareBridgePath()">Portal sign in →</router-link>
    </header>
    <main id="scb-main">
      <p v-if="loading" class="scb-status" role="status">Loading SchoolCareBridge…</p>
      <div v-else-if="error" class="scb-status" role="alert">{{error}} <button @click="load">Try again</button></div>
      <div v-else-if="!content" class="scb-status"><h1>Page not found</h1><router-link :to="path('')">SchoolCareBridge home</router-link></div>
      <template v-else>
        <section class="scb-editorial-hero" :class="{'scb-hero-with-preview':['','for-agencies'].includes(section)}">
          <div class="scb-editorial-copy"><p class="scb-eyebrow">{{content.eyebrow}}</p><h1>{{custom?.heroTitle||custom?.title||(section===''&&page?.heroTitle)||content.title}}</h1><p class="scb-lead">{{custom?.heroSubtitle||(section===''&&page?.heroSubtitle)||content.description}}</p>
            <ul v-if="!section" class="scb-hero-checklist"><li>Branded school portals</li><li>School and agency coordination</li><li>Enrollment forms and packets</li><li>Access scoped to your role</li></ul>
            <div class="scb-actions"><a v-if="contactUrl" class="scb-button" :href="contactUrl" @click="guardPreview">{{section==='resources'?'Contact the MH4Kidz team':'Request a conversation'}} →</a><router-link v-else class="scb-button" :to="schoolCareBridgePath()">Find your portal →</router-link><router-link v-if="!['how-it-works','partners'].includes(section)" class="scb-button scb-outline" :to="path('how-it-works')">See how it works</router-link><router-link v-else class="scb-button scb-outline" :to="path('for-schools')">For your school</router-link></div><p class="scb-byline">A Plot Twist Co. product · Program operated by MH4Kidz</p>
          </div>
          <div class="scb-editorial-art"><img :src="heroImage" :alt="heroAlt"/><div v-if="['','for-agencies'].includes(section)" class="scb-hero-product"><SchoolCareBridgePortalPreview :agency="section==='for-agencies'"/></div><p v-else class="scb-image-message">{{imageMessage}}</p></div>
        </section>
        <div v-if="custom?.body" class="scb-prose scb-section" v-html="customHtml"></div>

        <template v-if="section==='programs'"><SchoolCareBridgeProgramCatalog/></template>
        <template v-else-if="section==='partners'">
          <section class="scb-section scb-partners-section"><p class="scb-eyebrow">Our partner agencies</p><h2>Care starts with the people who show up.</h2><p class="scb-section-intro">Meet the agencies using SchoolCareBridge to connect with their school communities. Select your agency’s logo to enter its workspace.</p><p v-if="partnersLoading" role="status">Loading our partners…</p><p v-else-if="partnersError" role="alert">We couldn’t load the partner directory. <button @click="loadPartners">Try again</button></p><div v-else class="scb-partner-cards"><article v-for="partner in partners" :key="partner.id"><router-link class="scb-partner-brand-link" :to="schoolCareBridgePartnerPath(partner.slug)" :aria-label="`${partner.name} SchoolCareBridge workspace`"><img v-if="partnerLogo(partner)" :src="partnerLogo(partner)" :alt="partner.name" @error="$event.target.style.display='none'"/><strong v-else>{{partner.name}}</strong></router-link><p class="scb-eyebrow">SchoolCareBridge partner</p><h3>{{partner.name}}</h3><p>{{partner.description||'Connecting school staff and care providers through a shared school-centered workspace.'}}</p><router-link class="scb-button" :to="schoolCareBridgePartnerPath(partner.slug)">{{partner.name}} SchoolCareBridge →</router-link></article><p v-if="!partners.length">Partner listings are being prepared.</p></div></section>
          <section class="scb-split-section scb-section"><div><p class="scb-eyebrow">Join the program</p><h2>Your agency. Your schools.<br/>A shared place to connect.</h2><p>Keep your agency identity while making school coordination easier. New partners can start with a focused workspace for school portals, clients, providers and everyday settings.</p></div><div class="scb-soft-panel"><h3>What a partnership includes</h3><ul class="scb-check-list"><li>Your agency logo and branded entry</li><li>School-specific portals and care-team attribution</li><li>A concise operations workspace</li><li>Existing role and student-information permissions</li></ul><router-link :to="path('for-agencies')">Explore the agency experience →</router-link></div></section>
        </template>

        <template v-else-if="section==='how-it-works'">
          <section class="scb-section"><p class="scb-eyebrow">From setup to ongoing support</p><h2>A simple, guided workflow.</h2><div class="scb-process-grid"><article v-for="(step,i) in process" :key="step[0]"><span>{{i+1}}</span><h3>{{step[0]}}</h3><p>{{step[1]}}</p></article></div></section>
          <section class="scb-split-section scb-section scb-soft-band"><div><p class="scb-eyebrow">For school staff</p><h2>A familiar front door.</h2><p>Enter your email and continue to your school’s branded login. If your account serves more than one school, choose the one you need.</p><router-link class="scb-button scb-outline" :to="schoolCareBridgePath()">Open your school portal →</router-link></div><SchoolCareBridgePortalPreview/></section>
          <section class="scb-split-section scb-section"><SchoolCareBridgePortalPreview agency/><div><p class="scb-eyebrow">For agencies</p><h2>One overview.<br/>Your connected schools.</h2><p>Start with school portals, clients and providers. Open a school for enrollment, schedules and communication. Existing connected agencies can also return to their full agency workspace.</p><router-link :to="path('partners')">Find your agency →</router-link></div></section>
        </template>

        <template v-else-if="section==='about'">
          <section class="scb-section scb-mission-grid"><article><p class="scb-eyebrow">Our mission</p><h2>Make school-based support easier to coordinate.</h2><p>School staff and care providers need a shared place to work. SchoolCareBridge brings the practical steps—finding providers, organizing enrollment and keeping in touch—into a school-centered experience.</p></article><article><p class="scb-eyebrow">Our vision</p><h2>Stronger connections around every student.</h2><p>We want schools and agencies to spend less time finding the next step and more time supporting their communities. The experience begins with the tools teams already use.</p></article></section>
          <section class="scb-split-section scb-section scb-soft-band"><div><p class="scb-eyebrow">A program of MH4Kidz</p><h2>A community mission.<br/>A practical place to begin.</h2><p>MH4Kidz operates SchoolCareBridge and receives program revenue. Agency partners bring their school relationships and care teams. SchoolCareBridge is a Plot Twist Co. product. Plot Twist Co provides the underlying platform.</p><a class="scb-button scb-outline" href="https://mh4kidz.org">Meet MH4Kidz ↗</a></div><div class="scb-mission-brand"><img src="/assets/mh4kidz/logo.png" alt="MH4Kidz"/><p>Stronger kids. Brighter tomorrows.</p></div></section>
          <section class="scb-section"><p class="scb-eyebrow">What guides the experience</p><div class="scb-value-grid"><article v-for="[title,body] in values" :key="title"><span aria-hidden="true">✦</span><h3>{{title}}</h3><p>{{body}}</p></article></div></section>
        </template>

        <template v-else-if="section==='resources'"><SchoolCareBridgeProgramCatalog/>
          <section class="scb-section"><p class="scb-eyebrow">Tools for your next step</p><h2>Find what you need, where you need it.</h2><div class="scb-resource-grid"><router-link v-for="[symbol,title,body] in resources" :key="title" :to="schoolCareBridgePath()"><span class="scb-resource-icon" aria-hidden="true">{{symbol}}</span><div><h3>{{title}}</h3><p>{{body}}</p><strong>Find your school portal →</strong></div></router-link></div></section>
          <section class="scb-split-section scb-section scb-soft-band"><img class="scb-section-photo" src="/assets/mh4kidz/groups.webp" alt="A group activity bringing children together"/><div><p class="scb-eyebrow">Beyond the portal</p><h2>Explore MH4Kidz’s<br/>community programs.</h2><p>Visit MH4Kidz for its published programs and resources. For a school or agency conversation, use the program’s configured contact destination below.</p><a class="scb-button" href="https://mh4kidz.org">Visit MH4Kidz ↗</a><p v-if="!contactUrl" class="scb-pending">A SchoolCareBridge contact destination has not been configured yet.</p><a v-else :href="contactUrl" @click="guardPreview">Contact the program team →</a></div></section>
          <section class="scb-section"><h2>Getting started with your portal</h2><div class="scb-faq"><details v-for="[question,answer] in resourceFaq" :key="question"><summary>{{question}}</summary><p>{{answer}}</p></details></div></section>
        </template>

        <template v-else-if="section==='security'">
          <section class="scb-section"><p class="scb-eyebrow">Built around authorized access</p><h2>Your school address is a starting point.</h2><p class="scb-section-intro">Your signed-in account determines the information and tools you can use. Choosing a different school address does not change your permissions.</p><div class="scb-security-grid"><article v-for="[title,body] in securityPractices" :key="title"><span aria-hidden="true">✓</span><h3>{{title}}</h3><p>{{body}}</p></article></div></section>
          <section class="scb-split-section scb-section scb-soft-band"><div><p class="scb-eyebrow">Clear roles</p><h2>Each person sees<br/>what their work requires.</h2><p>Existing membership, role and release-of-information controls continue to govern access in SchoolCareBridge. Agency listings and logos are for identification.</p></div><div class="scb-role-stack"><article v-for="[role,body] in accessRoles" :key="role"><span aria-hidden="true">▣</span><div><h3>{{role}}</h3><p>{{body}}</p></div></article></div></section>
          <section class="scb-section"><h2>Recognize your portal. Protect your account.</h2><div class="scb-cards"><article class="scb-card"><h3>Check the school and agency</h3><p>Your school’s identity and affiliated agencies appear on the login page. Use your established account.</p></article><article class="scb-card"><h3>Keep your account yours</h3><p>Use the configured sign-in and recovery process, follow account security prompts, and sign out on shared devices.</p></article><article class="scb-card"><h3>Ask for access changes</h3><p>Contact your school or agency administrator when staff roles or school relationships change.</p></article></div></section>
        </template>

        <template v-else>
          <section class="scb-section"><p class="scb-eyebrow">{{content.label}}</p><h2>{{content.heading}}</h2><div class="scb-capability-grid"><article v-for="(card,i) in content.cards" :key="card[0]"><span :class="`scb-icon-tone-${i%4}`" aria-hidden="true">{{['⌂','◎','▤','↗'][i%4]}}</span><h3>{{card[0]}}</h3><p>{{card[1]}}</p></article></div></section>
          <section v-if="section==='for-schools'" class="scb-split-section scb-section scb-soft-band"><div><p class="scb-eyebrow">Built for school staff</p><h2>Everything starts<br/>with your school.</h2><p>A SchoolCareBridge workspace keeps your school and care partners visible. Open the tools you need without searching across separate agency workspaces.</p><ul class="scb-check-list"><li>Provider cards and school schedules</li><li>Student rosters and school staff access</li><li>Digital forms, printable forms and packet uploads</li><li>Messages and configured school documents</li></ul><router-link class="scb-button" :to="schoolCareBridgePath()">Find your school →</router-link></div><SchoolCareBridgePortalPreview/></section>
          <section v-else-if="section==='for-agencies'" class="scb-split-section scb-section scb-soft-band"><div><p class="scb-eyebrow">A focused operations workspace</p><h2>School partnerships,<br/>without the extra layers.</h2><p>Start with the essentials: school portals, clients, providers and a few settings. Your agency identity stays visible in the directory and in the schools you serve.</p><ul class="scb-check-list"><li>Your agency’s branded SchoolCareBridge entry</li><li>Authorized school portals in one overview</li><li>School rosters, providers and shared workflows</li><li>Additional features by future agreement</li></ul><router-link class="scb-button" :to="path('partners')">Meet our partners →</router-link></div><SchoolCareBridgePortalPreview agency/></section>
          <template v-else><section class="scb-home-paths scb-section"><article><img src="/assets/itsco/students-hero.png" alt="Students at school"/><div><p class="scb-eyebrow">For schools</p><h2>More connection.<br/>A clearer next step.</h2><p>A familiar school portal for providers, schedules, enrollment and communication.</p><router-link :to="path('for-schools')">Explore the school experience →</router-link></div></article><article><img src="/assets/itsco/counseling-hero.png" alt="A supportive counseling conversation"/><div><p class="scb-eyebrow">For agencies</p><h2>Your partnerships.<br/>Working together.</h2><p>Bring your schools and care teams into a focused coordination workspace.</p><router-link :to="path('for-agencies')">Explore the agency experience →</router-link></div></article></section><section class="scb-section scb-compact-process"><div><p class="scb-eyebrow">How it works</p><h2>A connected path.</h2><router-link :to="path('how-it-works')">Follow the process →</router-link></div><article v-for="(step,i) in process.slice(0,4)" :key="step[0]"><span>{{i+1}}</span><h3>{{step[0]}}</h3><p>{{step[1]}}</p></article></section></template>
        </template>
        <section v-if="section!=='partners'&&partners.length" class="scb-partner-ribbon scb-section"><div><p class="scb-eyebrow">Partner agencies</p><h2>Connected through care.</h2></div><router-link v-for="partner in partners" :key="partner.id" :to="schoolCareBridgePartnerPath(partner.slug)" :aria-label="`${partner.name} SchoolCareBridge workspace`"><img v-if="partnerLogo(partner)" :src="partnerLogo(partner)" :alt="partner.name" @error="$event.target.style.display='none'"/><strong v-else>{{partner.name}}</strong></router-link><router-link :to="path('partners')">Meet our partners →</router-link></section>
        <section v-if="!section" class="scb-section"><p class="scb-eyebrow">Explore the working product</p><h2>The portal your school actually uses.</h2><p class="scb-section-intro">Open a provider’s full profile, browse the roster, and move through the school schedule. These examples run the real school interface with fictional providers and seeded students.</p><SchoolCareBridgePortalPreview/><p><a :href="demoUrl+'?view=overview'">Explore the actual agency school overview →</a></p></section>
        <section class="scb-closing"><div><p class="scb-eyebrow">SchoolCareBridge · A program of MH4Kidz</p><h2>Stronger schools.<br/>Connected care. Brighter possibilities.</h2><p>Bring your school community and care partners into one familiar place.</p></div><div><router-link class="scb-button" :to="schoolCareBridgePath()">Open your portal →</router-link><a v-if="contactUrl" :href="contactUrl" @click="guardPreview">Or contact our team</a><p v-else class="scb-closing-note">Program inquiries: contact destination not yet configured.</p></div></section>
      </template>
      <p v-if="previewNotice" class="scb-status" role="status">{{previewNotice}}</p>
    </main>
    <ServiceUseNotice school-portal />
    <footer class="scb-footer"><SchoolCareBridgeBrand/><div><strong>Connecting schools. Supporting students.</strong><p>A Plot Twist Co. product · Program operated by MH4Kidz.</p></div><nav aria-label="Footer"><router-link :to="path('partners')">Partners</router-link><router-link :to="path('security')">Access & privacy</router-link><a href="https://plottwistco.com/products#schoolcarebridge">Plot Twist Co. products ↗</a><a href="https://mh4kidz.org">MH4Kidz ↗</a></nav></footer>
  </div>
</template>
<script setup>
import { computed, onMounted, ref } from 'vue';
import api from '../../services/api';
import DOMPurify from 'dompurify';
import { marked } from 'marked';
import { schoolCareBridgePath, schoolCareBridgeExternalPath } from '../../utils/schoolCareBridge';
import { schoolCareBridgePartnerPath } from '../../utils/schoolCareBridgeTenant';
import { toUploadsUrl } from '../../utils/uploadsUrl';
import SchoolCareBridgePortalPreview from '../../components/schoolcarebridge/SchoolCareBridgePortalPreview.vue';
import SchoolCareBridgeProgramCatalog from '../../components/schoolcarebridge/SchoolCareBridgeProgramCatalog.vue';
import SchoolCareBridgeBrand from '../../components/schoolcarebridge/SchoolCareBridgeBrand.vue';
import ServiceUseNotice from '../../components/legal/ServiceUseNotice.vue';
import { useStandalonePublicWebsite, publicWebsiteUrl as safe } from '../../composables/useStandalonePublicWebsite';
import '../../styles/schoolCareBridge.css';
import '../../styles/schoolCareBridgeWebsite.css';
const {page,loading,error,menuOpen,section,load,guardPreview,previewNotice}=useStandalonePublicWebsite('schoolcarebridge','SchoolCareBridge | A Plot Twist Co. product');
const demoUrl=schoolCareBridgeExternalPath('/schoolcarebridge/demo');
const path=slug=>`/schoolcarebridge${slug?'/'+slug:''}`;
const nav=[['For Schools','for-schools'],['For Agencies','for-agencies'],['How It Works','how-it-works'],['About','about'],['Partners','partners'],['Programs','programs'],['Resources','resources'],['Security','security']];
const settings=computed(()=>page.value?.branding?.schoolcarebridgeWebsite||{});
const mh4Contact=ref('');
const contactUrl=computed(()=>safe(settings.value.demoUrl||settings.value.contactUrl||settings.value.partnerUrl||mh4Contact.value));
onMounted(async()=>{try{const {data}=await api.get('/public/marketing-pages/mh4kidz',{skipAuthRedirect:true,skipGlobalLoading:true});mh4Contact.value=data?.page?.branding?.mh4kidzWebsite?.contactUrl||'';}catch{/* Configured destinations are optional. */}});
const custom=computed(()=>page.value?.branding?.contentPages?.find(p=>p.slug===section.value));
const customHtml=computed(()=>DOMPurify.sanitize(marked.parse(custom.value?.body||''),{FORBID_TAGS:['form','input','button','textarea','select','style','iframe']}));
const pages={
 programs:{eyebrow:'Programs & workshops',title:'More support for your school community.',description:'Discover original, partner, managed and sponsored programs. Connect with presenters in your region and arrange the support your school needs.',cards:[]},
 partners:{eyebrow:'Our partners',title:'Agencies and schools. Connected by care.',description:'Meet the agency partners bringing SchoolCareBridge to their school communities.',label:'Our partners',heading:'Care starts with connection.',cards:[]},
 '':{eyebrow:'Connecting schools. Supporting students.',title:'A bridge between schools and the care students need.',description:'Coordinate school-based mental health services with trusted agency partners through one school-centered experience.',label:'Built around your school',heading:'Less searching. More working together.',cards:[['Your school’s portal','A familiar home with your school’s name, colors, and affiliated agencies.'],['Connected care teams','Find providers, view schedules, and communicate with the people supporting your school.'],['Enrollment in one place','Use digital forms or upload completed packets through existing school workflows.'],['Access that fits your role','Work with the information and tools your account is authorized to use.']]},
 'for-schools':{eyebrow:'For schools',title:'A simpler way to coordinate school-based support.',description:'Give school staff one place to find providers, coordinate paperwork, and keep services organized.',label:'Built for school staff',heading:'Your school’s next steps, together.',cards:[['Find your providers','See the agency partners and providers serving your school.'],['Coordinate enrollment','Send digital forms, find printable documents, and upload completed packets.'],['Stay organized','Review schedules, rosters, messages, and pending school workflows.'],['Keep your school identity','Your school’s branding stays prominent alongside SchoolCareBridge and MH4Kidz.']]},
 'for-agencies':{eyebrow:'For mental health agencies',title:'Stronger school partnerships. A shared place to coordinate.',description:'A focused school-operations workspace for school portals, clients and providers, with your agency’s identity at the center.',label:'Working across schools',heading:'Stay connected to each school community.',cards:[['School partnerships','Open the school portals your account is authorized to access.'],['Clear agency identity','Your logo appears with affiliated schools and your agency remains identified in relevant workflows.'],['Shared workflows','Continue using existing forms, documents, schedules, and communication.'],['Your operational workspace','Reach your agency’s existing tools when you need deeper management functionality.']]},
 'how-it-works':{eyebrow:'How it works',title:'From your first sign-in to everyday coordination.',description:'Existing accounts and school workflows come together in a school-branded experience.',label:'A familiar process',heading:'Start with your school. Continue with your team.',cards:[['Enter your email','School staff are directed to their school, or choose among their school memberships.'],['Sign in securely','Use your existing email and password, following your organization’s account security requirements.'],['Open your school portal','See your school’s identity and the agencies affiliated with it.'],['Coordinate support','Use the schedules, roster, forms, and messaging available to your role.']]},
 about:{eyebrow:'About SchoolCareBridge',title:'Connected schools. Supported communities.',description:'SchoolCareBridge is a Plot Twist Co. product that helps schools and care teams coordinate school-based services. MH4Kidz operates the program.',label:'Our connection',heading:'A school-centered experience, supported by MH4Kidz.',cards:[['MH4Kidz','Operates the SchoolCareBridge program and its public experience.'],['Schools','Bring their communities, staff, and school-specific coordination needs.'],['Affiliated agencies','Provide and coordinate services through their authorized school relationships.'],['Plot Twist Co.','Creates SchoolCareBridge, alongside Plot Twist HQ and AuricWell, and provides the shared platform.']]},
 resources:{eyebrow:'Resources',title:'Find the next step for your school community.',description:'Start with the resources already available in your school portal and explore MH4Kidz’s public programs.',label:'Useful starting points',heading:'Support for everyday coordination.',cards:[['School documents','Sign in to find the documents and links configured for your school.'],['Enrollment support','Find digital forms, printable packets, and upload tools in your portal.'],['Your care partners','Use your portal to connect with authorized agency staff and providers.'],['MH4Kidz programs','Visit MH4Kidz to explore published programs and community resources.']]},
 security:{eyebrow:'Access and privacy',title:'The right access for your role.',description:'SchoolCareBridge uses the existing platform’s authentication and school access controls. A school address identifies the portal; it does not grant permission to view its information.',label:'A shared responsibility',heading:'School coordination with scoped access.',cards:[['Existing identity','Use your established account and organization’s configured sign-in policies.'],['School membership','Your authenticated access is checked when opening a school portal.'],['Scoped information','Existing role and release-of-information controls continue to govern student information.'],['Recognizable destinations','School-specific branding helps you recognize the portal you are entering.']]}
};
const content=computed(()=>pages[section.value]||(custom.value?{...pages.about,eyebrow:'SchoolCareBridge',title:custom.value.title,cards:[]}:null));

const partners=ref([]),partnersLoading=ref(true),partnersError=ref(false);
async function loadPartners(){partnersLoading.value=true;partnersError.value=false;try{const {data}=await api.get('/schoolcarebridge/partners',{skipAuthRedirect:true,skipGlobalLoading:true});partners.value=data.partners||[];}catch{partnersError.value=true;}finally{partnersLoading.value=false;}}
const partnerLogo=partner=>{const value=partner.logoUrl||(partner.slug==='itsco'?'/assets/itsco/logo.png':'');return value.startsWith('/assets/')?value:toUploadsUrl(value);};
const images={'':'/assets/itsco/students-hero.png','for-schools':'/assets/itsco/student-learning.png','for-agencies':'/assets/itsco/counseling-hero.png','how-it-works':'/assets/mh4kidz/teamwork.webp',about:'/assets/mh4kidz/about.webp',resources:'/assets/mh4kidz/groups.webp',security:'/assets/mh4kidz/mountains.webp',partners:'/assets/mh4kidz/teamwork.webp'};
const heroImage=computed(()=>safe(custom.value?.heroImageUrl)||(section.value===''?safe(page.value?.heroImageUrl):'')||images[section.value]||images['']);
const heroAlt=computed(()=>section.value==='security'?'A mountain landscape':'School communities and care teams connecting');
const imageMessage=computed(()=>({'for-schools':'Healthier students. Stronger schools.','how-it-works':'Simple steps. Shared support.',about:'Stronger communities start together.',resources:'More support for your school community.',security:'Recognizable portals. Authorized access.',partners:'Real people. Shared purpose.'}[section.value]||'Connected care.'));
const process=[['Connect your agency','Set up a focused workspace and identify your school partners.'],['Brand your schools','Use each school’s name, logo, colors and imagery.'],['Manage enrollment','Use digital forms or upload completed school packets.'],['Coordinate providers','Open the authorized provider and scheduling tools.'],['Stay in touch','Share messages with the care team and school staff.'],['Continue support','Return to school rosters and ongoing workflows.']];
const values=[['Student-centered','Keep school communities and student support at the center.'],['Collaborative','Make everyday coordination easier for school and agency teams.'],['Clear access','Respect existing permissions and authorized information sharing.'],['Practical progress','Start with useful tools and grow with participating communities.']];
const resources=[['▤','Enrollment forms','Find digital enrollment forms configured for your school.'],['↥','Packets & documents','Use printable forms and upload completed packets.'],['◎','Your care team','Find providers and affiliated agency contacts.'],['▦','School schedules','Open schedules and coordination tools available to your role.']];
const resourceFaq=[['How do I find my school?','Start at Portal sign in and enter your email. School staff continue to their school or choose among their school memberships.'],['What if I do not have an account?','Contact your school or agency administrator. A school address or partner listing does not create account access.'],['Can families complete enrollment?','Continue using the school’s configured enrollment links and forms. This release keeps the existing family enrollment experience.']];
const securityPractices=[['Existing accounts','Your established account and sign-in policies remain in use.'],['School access checks','School access is checked before opening the private portal.'],['Role-based information','Existing role and release-of-information restrictions remain in place.'],['Session controls','Existing account security, session expiry and logout controls continue to apply.']];
const accessRoles=[['School staff','School information authorized for their role and membership.'],['Agency providers','Schools and client information they are authorized to access.'],['Agency administrators','Agency school coordination and the settings assigned to their account.']];
onMounted(loadPartners);

</script>
