import { GoogleAuth } from 'google-auth-library';
import config from '../../config/config.js';
import { parseGoogleWorkspaceServiceAccountFromEnv } from '../googleWorkspaceAuth.service.js';
import { getToolSchemasForUser } from './toolRegistry.service.js';

function sanitizeText(v, { maxLen }) {
  const s = String(v ?? '')
    .replace(/\u0000/g, '')
    .trim();
  if (!maxLen) return s;
  return s.length > maxLen ? s.slice(0, maxLen) : s;
}

async function getAccessToken() {
  const scopes = ['https://www.googleapis.com/auth/cloud-platform'];
  const authSource = String(process.env.VERTEX_AUTH_SOURCE || '').trim().toLowerCase(); // 'workspace_service_account' | ''
  const workspaceSa =
    authSource === 'workspace_service_account' ? parseGoogleWorkspaceServiceAccountFromEnv() : null;

  const auth = workspaceSa
    ? new GoogleAuth({ credentials: workspaceSa, scopes })
    : new GoogleAuth({ scopes });

  const client = await auth.getClient();
  const tokenResponse = await client.getAccessToken();
  const token = typeof tokenResponse === 'string' ? tokenResponse : tokenResponse?.token;
  if (!token) {
    const err = new Error('Failed to acquire Google Cloud access token');
    err.status = 503;
    throw err;
  }
  return token;
}

function buildSystemPrompt({ includeSearch, agentConfig, user }) {
  const cfg = agentConfig && typeof agentConfig === 'object' ? agentConfig : null;
  const tools = getToolSchemasForUser(user, cfg);
  const agentSystemPrompt = cfg?.systemPrompt == null ? null : String(cfg.systemPrompt).slice(0, 6000);
  const todayYmd = new Date().toISOString().slice(0, 10);

  return [
    `You are the in-app assistant for a clinical/business web application. Today is ${todayYmd}.`,
    '',
    agentSystemPrompt ? `Additional instructions from the operator:\n${agentSystemPrompt}\n` : '',
    '',
    'Return ONLY this JSON shape (no markdown, no fences, no commentary):',
    '{ "assistantText": string, "uiCommands": [], "toolCalls": [ { "name": string, "args": object } ] }',
    '',
    '=== THE CORE CONTRACT (read this twice) ===',
    'You have exactly TWO valid response modes. They must not be mixed.',
    '',
    'MODE 1 — TOOL MODE (preferred):',
    '  Use this for ANY question that touches the database, a list of users/schools/events,',
    '  navigation to a page, payroll, intake openings, RSVPs, office hours, etc.',
    '  Requirements:',
    '    - toolCalls is non-empty and contains ONLY tools from the allowed list below.',
    '    - assistantText is EMPTY ("") or a single short action phrase like "Looking that up".',
    '    - You MUST NOT include any answer text. The server runs the tools and writes the answer.',
    '',
    'MODE 2 — TALK MODE:',
    '  Only used when the user is asking a generic question that no available tool can answer',
    '  (e.g. "how do I add a new client", "what does this page do", "explain RSVP modes").',
    '  Requirements:',
    '    - toolCalls is [].',
    '    - assistantText explains using only general product knowledge.',
    '    - You MUST NEVER claim "Found N results" or invent names/counts in this mode.',
    '',
    '=== HARD BANS (any of these = a failed turn) ===',
    '  - Do NOT write phrases like "Found 2 schools", "I see 3 events", "There are N…" UNLESS the',
    '    server already ran a search this turn. If you have not called a tool this turn, you have',
    '    not searched — you do not know how many results there are.',
    '  - Do NOT echo or paraphrase example sentences from this prompt as if they were real answers.',
    '  - Do NOT respond with "Searching…", "Looking…", or "One moment" plus empty toolCalls.',
    '  - Do NOT include uiCommands; navigation is generated by tool results, never by you.',
    '  - Do NOT wrap the JSON in markdown fences.',
    '',
    '=== TOOL SELECTION GUIDE ===',
    'Map the user\'s intent to ONE tool by what they\'re asking for:',
    '  - Wants to navigate to a page  → navigateTo({ routeName })',
    '  - Names a school / portal      → searchSchools({ query })',
    '  - Names an event / program     → searchEvents({ query })',
    '  - Names a person to look up    → searchUsers({ query })  (if allowed)',
    '  - Asks about own payroll / pay → getMyPayrollSummary({})',
    '  - Asks about own activity log  → listMyRecentActivity({ limit?, since?, actionType? })',
    '  - Asks about agency audit log  → searchAgencyActivity({...}) or getAgencyActivityStats({...})',
    '  - "who has an intake opening"  → findIntakeOpenings({ dateYmd?, modality? })',
    '  - "who rsvp\'d / responded"     → getEventResponses({ eventId?, eventQuery?, dateYmd?, responseKey? })',
    '  - "what offices are open"      → getOfficeSchedule({ dateYmd?, locationQuery? })',
    '  - "find providers who use X"   → searchProviders({ agencyId, filters: [{fieldKey, op, value}] })',
    '  - Refer-out / pediatrics / psychiatry → searchReferralDirectory({ query })',
    '  - Tutoring / standards lookup  → lookupStandardCrosswalk({...})',
    '  - "create a task / assign training" → createTask({ taskType, title, ... })',
    '  - "add hiring candidate"       → createHiringCandidate({...})',
    '  - "add a note to <candidate>"  → addHiringNote({...})',
    '  - "move <candidate> to <stage>" → setHiringStage({...})',
    '  - "start a meeting with X" / "video chat with X" / "1:1 with X" → searchUsers({ query: "X" })',
    '    (the server resolves the user, then surfaces a startMeeting confirmation card)',
    '  - "open my workspace" / "what\'s active right now" → openTodaysWorkspace({ activeOnly?: true })',
    '  - "who uses CBT" / "who does EMDR" / "find a trauma therapist" → findProvidersByApproach({ approach: "CBT" })',
    '  - handbook / PTO / vacation / sick leave / company policy / dress code / remote work → searchTrainingKnowledgeBase({ query })',
    '  - "cancel my next meeting" / "cancel my meeting" → findNextMeeting({})',
    '    (the server resolves which meeting, then surfaces a cancelMeeting confirmation card)',
    '  - "cancel the meeting with X" → findMyMeetings({ withName: "X" })',
    '    (the server resolves the meeting, then surfaces a cancelMeeting confirmation card)',
    '  - "cancel the rest of my day" / "cancel all my remaining meetings today" → cancelTodaysRemainingMeetings({ reason?: string })',
    '  - "move my 3pm to 4pm" / "reschedule my 9am meeting to 10am" → findMyMeetings({ atTimeHm: "15:00" })',
    '    (the server resolves the meeting, then surfaces a rescheduleMeeting confirmation card)',
    '  - "push everything 30 minutes" / "delay all my meetings 15 min" → pushTodaysRemainingMeetings({ shiftMinutes: 30, reason?: string })',
    '',
    'WRITE actions (createTask, createHiringCandidate, addHiringNote, setHiringStage, startMeeting,',
    'cancelMeeting, cancelTodaysRemainingMeetings, rescheduleMeeting, pushTodaysRemainingMeetings)',
    'are ALWAYS safe to return as toolCalls — the server intercepts them and asks the user to',
    'confirm via a button before anything is written. You should still return them in TOOL MODE',
    'with empty assistantText; do not write your own confirmation prompt.',
    '',
    'Date parameters: convert natural-language dates to YYYY-MM-DD using today as anchor.',
    `  Today is ${todayYmd}. "today" = ${todayYmd}. "tomorrow" = next day. "this Friday" = the upcoming Friday (or today if today is Friday). "next Tuesday" = the Tuesday of next week.`,
    '',
    '=== DISAMBIGUATION ===',
    '  - If a search returns ONE result you may also call the appropriate openEntity to open it.',
    '  - If a search returns MORE THAN ONE, only return the search call; the UI shows pickable cards.',
    '  - If the user replied with a name after a multi-result search, search again with ONLY the',
    '    distinctive token (e.g. drop "school" / "elementary" so the LIKE will still match).',
    '',
    '=== ALLOWED TOOLS FOR THIS USER ===',
    JSON.stringify(tools, null, 2),
    '',
    includeSearch
      ? 'You may use Google Search grounding if available in your environment.'
      : 'Do not rely on Google Search. Answer using provided context only.'
  ].filter(Boolean).join('\n');
}

async function callVertexModelJson({ token, projectId, location, modelId, systemPrompt, userPrompt, timeoutMs }) {
  const url = `https://${encodeURIComponent(location)}-aiplatform.googleapis.com/v1/projects/${encodeURIComponent(
    projectId
  )}/locations/${encodeURIComponent(location)}/publishers/google/models/${encodeURIComponent(modelId)}:generateContent`;

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const body = {
      contents: [{ role: 'user', parts: [{ text: userPrompt }] }],
      systemInstruction: { parts: [{ text: systemPrompt }] },
      generationConfig: {
        temperature: 0.1,
        topP: 0.8,
        maxOutputTokens: 1400
      }
    };

    const resp = await fetch(url, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json; charset=utf-8'
      },
      signal: controller.signal,
      body: JSON.stringify(body)
    });

    if (!resp.ok) {
      const t = String(await resp.text()).slice(0, 2000);
      const err = new Error('Vertex AI request failed');
      err.status = resp.status >= 400 && resp.status < 600 ? resp.status : 502;
      err.details = t;
      throw err;
    }

    const data = await resp.json();
    const parts = data?.candidates?.[0]?.content?.parts;
    const text = Array.isArray(parts) ? parts.map((p) => p?.text || '').filter(Boolean).join('') : '';
    if (!text) {
      const err = new Error('Model returned empty response');
      err.status = 502;
      throw err;
    }
    return text;
  } finally {
    clearTimeout(timeout);
  }
}

async function callReasoningEngineStreamQuerySse({ token, projectId, location, reasoningEngineId, payload, timeoutMs }) {
  const url = `https://${encodeURIComponent(location)}-aiplatform.googleapis.com/v1/projects/${encodeURIComponent(
    projectId
  )}/locations/${encodeURIComponent(location)}/reasoningEngines/${encodeURIComponent(reasoningEngineId)}:streamQuery?alt=sse`;

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const resp = await fetch(url, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${token}`,
        'Content-Type': 'application/json; charset=utf-8'
      },
      signal: controller.signal,
      body: JSON.stringify(payload)
    });

    if (!resp.ok) {
      const t = String(await resp.text()).slice(0, 2000);
      const err = new Error('Agent Engine request failed');
      err.status = resp.status >= 400 && resp.status < 600 ? resp.status : 502;
      err.details = t;
      throw err;
    }

    // Parse SSE stream; collect last JSON event with text.
    const reader = resp.body?.getReader?.();
    if (!reader) {
      const err = new Error('Streaming response not supported');
      err.status = 502;
      throw err;
    }

    const decoder = new TextDecoder('utf-8');
    let buf = '';
    let lastText = '';

    while (true) {
      const { value, done } = await reader.read();
      if (done) break;
      buf += decoder.decode(value, { stream: true });

      // SSE events are separated by double newline.
      const chunks = buf.split('\n\n');
      buf = chunks.pop() || '';
      for (const chunk of chunks) {
        const lines = chunk.split('\n');
        for (const line of lines) {
          const trimmed = line.trim();
          if (!trimmed.startsWith('data:')) continue;
          const jsonStr = trimmed.slice('data:'.length).trim();
          if (!jsonStr || jsonStr === '[DONE]') continue;
          try {
            const evt = JSON.parse(jsonStr);
            const parts = evt?.content?.parts;
            const text = Array.isArray(parts) ? parts.map((p) => p?.text || '').filter(Boolean).join('') : '';
            if (text) lastText = text;
          } catch {
            // ignore malformed event
          }
        }
      }
    }

    if (!lastText) {
      const err = new Error('Agent returned empty response');
      err.status = 502;
      throw err;
    }
    return lastText;
  } finally {
    clearTimeout(timeout);
  }
}

async function callAdkService({ url, prompt, context, userId, allowSearch, timeoutMs, user }) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const resp = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
      signal: controller.signal,
      body: JSON.stringify({
        prompt,
        context:
          context && typeof context === 'object'
            ? { ...context, userRole: user?.role || null }
            : { userRole: user?.role || null },
        userId: userId || null,
        userRole: user?.role || null,
        allowSearch: !!allowSearch
      })
    });

    if (!resp.ok) {
      const t = String(await resp.text()).slice(0, 2000);
      const err = new Error('ADK agent service request failed');
      err.status = resp.status >= 400 && resp.status < 600 ? resp.status : 502;
      err.details = t;
      throw err;
    }

    const data = await resp.json().catch(() => null);
    if (data && typeof data === 'object') {
      // Accept either a raw JSON string, or the parsed object itself.
      if (typeof data.rawText === 'string') return data.rawText;
      return JSON.stringify(data);
    }

    const t = String(await resp.text()).trim();
    if (!t) {
      const err = new Error('ADK agent returned empty response');
      err.status = 502;
      throw err;
    }
    return t;
  } finally {
    clearTimeout(timeout);
  }
}

export async function runAgentAssist({ userId, prompt, context, agentConfig, allowSearch, user, history }) {
  const cleanedPrompt = sanitizeText(prompt, { maxLen: 8000 });
  const ctx = context && typeof context === 'object' ? context : {};

  const systemPrompt = buildSystemPrompt({ includeSearch: !!allowSearch, agentConfig, user });

  // Build a compact conversation history block so the model has turn context.
  const historyBlock = (() => {
    const turns = Array.isArray(history) ? history : [];
    if (!turns.length) return '';
    const lines = turns.slice(-8).map((t) => {
      const role = String(t?.role || 'user').trim() === 'assistant' ? 'ASSISTANT' : 'USER';
      const text = sanitizeText(t?.text || '', { maxLen: 400 });
      return `${role}: ${text}`;
    });
    return `Conversation so far:\n${lines.join('\n')}\n`;
  })();

  const userPrompt = [
    `UserId: ${String(userId || '')}`,
    `UserRole: ${String(user?.role || '')}`,
    `RouteName: ${String(ctx.routeName || '')}`,
    `AgencyId: ${String(ctx.agencyId || '')}`,
    '',
    historyBlock,
    'Current user message:',
    cleanedPrompt
  ].filter(Boolean).join('\n');

  const projectId = process.env.GCP_PROJECT_ID || process.env.GCS_PROJECT_ID || '';
  const location = String(process.env.VERTEX_AI_LOCATION || 'us-central1').trim() || 'us-central1';
  const timeoutMs = Math.min(
    Math.max(parseInt(process.env.VERTEX_AI_AGENT_TIMEOUT_MS || '45000', 10) || 45000, 5000),
    120000
  );

  // Optional: delegate to an external Python ADK service (Cloud Run) if configured.
  // This is useful if you prefer programming agents in Python with google.adk.
  const adkUrl = String(process.env.ADK_AGENT_URL || '').trim();
  if (adkUrl) {
    const txt = await callAdkService({
      url: adkUrl,
      prompt: [systemPrompt, '', userPrompt].join('\n'),
      context: ctx,
      userId,
      user,
      allowSearch,
      timeoutMs
    });
    return { rawText: txt, runtime: 'adk_service' };
  }

  if (!projectId) {
    const err = new Error('GCP_PROJECT_ID (or GCS_PROJECT_ID) is not configured');
    err.status = 503;
    throw err;
  }

  const token = await getAccessToken();

  // Primary: Reasoning Engine (Agent Engine / Agent Builder) if configured.
  const reasoningEngineId = String(process.env.VERTEX_AGENT_ENGINE_ID || '').trim();
  if (reasoningEngineId) {
    const payload = {
      class_method: 'async_stream_query',
      input: {
        user_id: String(userId || 'user'),
        // session_id optional: if omitted, Agent Engine will create one automatically (per docs).
        message: [systemPrompt, '', userPrompt].join('\n')
      }
    };
    const txt = await callReasoningEngineStreamQuerySse({
      token,
      projectId,
      location,
      reasoningEngineId,
      payload,
      timeoutMs
    });
    return { rawText: txt, runtime: 'vertex_agent_engine' };
  }

  // Fallback: Vertex model direct call (still Google-hosted, but not Agent Engine).
  const modelId = String(process.env.VERTEX_AI_AGENT_MODEL || 'gemini-2.0-flash').trim() || 'gemini-2.0-flash';
  const txt = await callVertexModelJson({
    token,
    projectId,
    location,
    modelId,
    systemPrompt,
    userPrompt,
    timeoutMs
  });
  return { rawText: txt, runtime: 'vertex_model' };
}

export function safeParseAgentJson(rawText) {
  const t = String(rawText || '').trim();
  try {
    return JSON.parse(t);
  } catch (e) {
    // Common failure: extra text around JSON. Best-effort extraction.
    const first = t.indexOf('{');
    const last = t.lastIndexOf('}');
    if (first >= 0 && last > first) {
      try {
        return JSON.parse(t.slice(first, last + 1));
      } catch {
        // ignore
      }
    }
    const err = new Error('Agent response was not valid JSON');
    err.status = 502;
    if (config.nodeEnv === 'development') err.details = String(t).slice(0, 2000);
    throw err;
  }
}

