<template><section class="session-record"><h2>Saved session content</h2><p v-if="error" role="alert">{{ error }}</p><p v-else-if="!artifacts.length">No shared content saved.</p><article v-for="a in visibleArtifacts" :key="a.id"><strong>{{ a.payload.title || labels[a.type] || a.type }}</strong><small>{{ a.role }} · {{ new Date(a.createdAt).toLocaleString() }}</small><p v-if="a.payload.text">{{ a.payload.text }}</p><p v-for="(answer,i) in a.payload.answers || []" :key="i">{{ answer }}</p><p v-if="a.type==='rating'">Progress: {{ a.payload.value }} / 10</p><a v-if="a.payload.document" :href="a.payload.document" :download="`${a.payload.title || 'attachment'}.pdf`" @click.prevent="download(a)">Download PDF</a><a v-if="a.payload.url" :href="a.payload.url" target="_blank" rel="noopener noreferrer">Open resource</a><svg v-if="a.type==='drawing'" viewBox="0 0 1000 700" aria-label="Saved drawing"><polyline v-for="stroke in artifacts.filter(item=>item.type==='drawing'&&item.payload.shareId===a.payload.shareId)" :key="stroke.id" :points="stroke.payload.points.map(p=>p.join(',')).join(' ')" :stroke="stroke.payload.color" fill="none" stroke-width="4" /></svg></article></section></template>
<script setup>
import {computed,ref,onMounted} from 'vue';
const props=defineProps({request:{type:Function,required:true}});
const artifacts=ref([]),error=ref('');
const visibleArtifacts=computed(()=>artifacts.value.filter(a=>a.type!=='drawing'||!artifacts.value.some(other=>other.type==='drawing'&&other.payload.shareId===a.payload.shareId&&other.id>a.id)));
async function download(a){try{await props.request('/download',{method:'POST',body:{artifactId:a.id}});const link=document.createElement('a');link.href=a.payload.document;link.download=`${a.payload.title||'attachment'}.pdf`;link.click();}catch(e){error.value=e.response?.data?.error?.message||e.message;}}
const labels={chat:'Chat',response:'Completed responses',drawing:'Drawing',rating:'Treatment plan rating',viewed:'Viewed resource',share:'Shared tool'};
onMounted(async()=>{try{let afterId=0,more=true;while(more){const data=await props.request(`?afterId=${afterId}`,{method:'GET'});artifacts.value.push(...data.artifacts);afterId=data.nextCursor;more=!!data.hasMore;}}catch(e){error.value=e.response?.data?.error?.message||e.message;}});
</script>
<style scoped>.session-record{text-align:left;padding:20px;background:white;border:1px solid #dce8e2;border-radius:16px;max-width:960px;margin:20px auto}.session-record article{border-bottom:1px solid #e3eaf0;padding:16px 0}.session-record small{display:block;color:#66788a;margin:6px 0}.session-record svg{display:block;max-width:500px;border:1px solid #e3eaf0}.session-record p{white-space:pre-wrap;overflow-wrap:anywhere}</style>
