import {it,expect,vi} from 'vitest';
import {patientFromDemographics,selfSubscriberPolicy} from '../clientInsurance.service.js';
import {officeAvailabilityWindows} from '../officeAvailabilityWindow.service.js';
import {plannedBillingServices} from '../plannedBillingServices.service.js';
it('maps available demographics without inventing unsupported claim sex',()=>{expect(patientFromDemographics({full_name:'Patient, Test',date_of_birth:'1996-10-01',address_street:'Synthetic',gender:'nonbinary'})).toMatchObject({firstName:'Test',lastName:'Patient',dateOfBirth:'1996-10-01',addressLine1:'Synthetic',sex:''});});
it('copies self-subscriber identity but preserves dependent policy and legacy intake details',()=>{const policy={relationshipToSubscriber:'self',subscriberFirstName:'Existing'};expect(selfSubscriberPolicy(policy,{})).toEqual(policy);expect(selfSubscriberPolicy(policy,{firstName:'Updated',dateOfBirth:'2000-01-01'})).toMatchObject({subscriberFirstName:'Updated',subscriberDob:'2000-01-01'});expect(selfSubscriberPolicy({...policy,relationshipToSubscriber:'child'},{firstName:'Child'}).subscriberFirstName).toBe('Existing');});
it('checks local office times as UTC including minute precision',()=>{expect(officeAvailabilityWindows('2026-10-01T15:15:00','2026-10-01T16:00:00','ONCE',1,'America/Denver')).toEqual([{dateYmd:'2026-10-01',startAt:'2026-10-01 21:15:00',endAt:'2026-10-01 22:00:00'}]);});
it('preserves the office wall time when recurring availability crosses DST',()=>{const rows=officeAvailabilityWindows('2026-10-29T15:00:00','2026-10-29T16:00:00','WEEKLY',2,'America/Denver');expect(rows.map(r=>r.startAt)).toEqual(['2026-10-29 21:00:00','2026-11-05 22:00:00']);expect(officeAvailabilityWindows('2026-10-01T21:00:00Z','2026-10-01T22:00:00Z','ONCE',1,'America/Denver')[0].startAt).toBe('2026-10-01 21:00:00');});
it('shows scheduled appointments without creating claims and deduplicates persistent encounter links',async()=>{
 const clinical={execute:vi.fn(async sql=>sql.startsWith('SELECT s.id AS sessionId,s.appointment_id AS appointmentId,s.client_id')?[[{sessionId:1,clientId:9,officeEventId:30,serviceCode:'90837',serviceDate:'2026-10-01'}]]:[[{sessionId:1,clientId:9,officeEventId:30,hasClaim:0},{sessionId:2,clientId:10,officeEventId:31,hasClaim:1}]])};
 const main={execute:vi.fn(async()=>[[{appointmentId:1,sessionId:1,officeEventId:30,clientId:9},{appointmentId:2,sessionId:2,clientId:10},{appointmentId:3,clientId:11,serviceCode:'90837',startAt:'2026-10-02 02:00:00',timeZone:'America/Denver'}]])};
 const result=await plannedBillingServices(377,{main,clinical});expect(result.items).toHaveLength(2);expect(result.items.find(i=>i.appointmentId===3).serviceDate).toBe('2026-10-01');expect(result.items.some(i=>i.clientId===10)).toBe(false);for(const [sql,params] of [...main.execute.mock.calls,...clinical.execute.mock.calls]){expect(sql).not.toMatch(/INSERT|UPDATE/);expect(params[0]).toBe(377);}
});
