import {beforeEach, afterEach, it, expect, vi} from 'vitest';
const m=vi.hoisted(()=>({prefs:vi.fn(),send:vi.fn(),channel:vi.fn(),gate:vi.fn()}));
vi.mock('../../models/User.model.js',()=>({default:{findById:vi.fn(async()=>({id:7,role:'provider',personal_phone:'+17195550100'})),normalizePhone:v=>v}}));
vi.mock('../../models/UserPreferences.model.js',()=>({default:{findByUserId:m.prefs}}));
vi.mock('../../models/Notification.model.js',()=>({default:{}}));
vi.mock('../../models/Agency.model.js',()=>({default:{findById:vi.fn(async()=>({id:2,slug:'itsco'}))}}));
vi.mock('../../models/AgencyNotificationPreferences.model.js',()=>({default:{getByAgencyId:vi.fn(async()=>null)}}));
vi.mock('../../models/NotificationSmsLog.model.js',()=>({default:{create:vi.fn(async()=>({id:1})),updateStatus:vi.fn()}}));
vi.mock('../smsCompliance.service.js',()=>({resolveRegisteredSmsSender:vi.fn(async()=>'+17195550200')}));
vi.mock('../pushNotification.service.js',()=>({}));
vi.mock('../notificationGatekeeper.service.js',()=>({default:{decideChannels:m.gate}}));
vi.mock('../notificationPreferences.service.js',()=>({isNotificationChannelEnabled:m.channel}));
vi.mock('../vonage.service.js',()=>({default:{sendSms:m.send}}));
vi.mock('../smsProfileAudit.service.js',()=>({recordSmsProfileAudit:vi.fn()}));
import Dispatcher from '../notificationDispatcher.service.js';
const notification={id:9,type:'client_exchange_match',user_id:7,agency_id:2};
beforeEach(()=>{vi.clearAllMocks();m.prefs.mockResolvedValue({notification_categories:{staff_communications_2:{choices:{exchangeMatches:true}}}});m.channel.mockResolvedValue(true);m.gate.mockResolvedValue({sms:true});m.send.mockResolvedValue({sid:'mock'});vi.stubEnv('CLIENT_EXCHANGE_CLINICAL_SMS_AGENCY_IDS','');});
afterEach(()=>vi.unstubAllEnvs());
it('requires signed exchange consent even when the general SMS switch is enabled',async()=>{m.prefs.mockResolvedValue({notification_categories:{}});expect(await Dispatcher.dispatchForNotification(notification)).toMatchObject({reason:'exchange_sms_not_consented'});expect(m.send).not.toHaveBeenCalled();});
it('respects per-type opt-out and contact hours',async()=>{m.channel.mockResolvedValue(false);await Dispatcher.dispatchForNotification(notification);expect(m.send).not.toHaveBeenCalled();m.channel.mockResolvedValue(true);m.gate.mockResolvedValue({sms:false});await Dispatcher.dispatchForNotification(notification);expect(m.send).not.toHaveBeenCalled();});
it('keeps clinical details out of ordinary SMS and links to the secure exchange',async()=>{await Dispatcher.dispatchForNotification(notification,{context:{exchangeSummary:'Age: 9 · Diagnosis: F41.1'}});expect(m.send).toHaveBeenCalledWith(expect.objectContaining({staffNotificationKind:'exchangeMatches',body:expect.stringContaining('New client added to the exchange.')}));expect(m.send.mock.calls[0][0].body).toContain('/client-exchange');expect(m.send.mock.calls[0][0].body).not.toContain('F41.1');});
it('allows a brief summary only for the explicitly enabled healthcare agency',async()=>{vi.stubEnv('CLIENT_EXCHANGE_CLINICAL_SMS_AGENCY_IDS','3');await Dispatcher.dispatchForNotification(notification,{context:{exchangeSummary:'Age: 9 · Individual therapy'}});expect(m.send.mock.calls[0][0].body).not.toContain('Age: 9');vi.stubEnv('CLIENT_EXCHANGE_CLINICAL_SMS_AGENCY_IDS','2');await Dispatcher.dispatchForNotification(notification,{context:{exchangeSummary:'Age: 9 · Individual therapy'}});expect(m.send.mock.calls[1][0].body).toContain('Age: 9 · Individual therapy');});
