import {beforeEach, afterEach, it, expect, vi} from 'vitest';
const m=vi.hoisted(()=>({prefs:vi.fn(),send:vi.fn(),channel:vi.fn(),gate:vi.fn(),sender:vi.fn(),agency:vi.fn()}));
vi.mock('../../models/User.model.js',()=>({default:{findById:vi.fn(async()=>({id:7,role:'provider',personal_phone:'+17195550100'})),normalizePhone:v=>v}}));
vi.mock('../../models/UserPreferences.model.js',()=>({default:{findByUserId:m.prefs}}));
vi.mock('../../models/Notification.model.js',()=>({default:{}}));
vi.mock('../../models/Agency.model.js',()=>({default:{findById:m.agency}}));
vi.mock('../../models/AgencyNotificationPreferences.model.js',()=>({default:{getByAgencyId:vi.fn(async()=>null)}}));
vi.mock('../../models/NotificationSmsLog.model.js',()=>({default:{create:vi.fn(async()=>({id:1})),updateStatus:vi.fn()}}));
vi.mock('../smsCompliance.service.js',()=>({resolveRegisteredSmsSender:m.sender}));
vi.mock('../pushNotification.service.js',()=>({}));
vi.mock('../notificationGatekeeper.service.js',()=>({default:{decideChannels:m.gate}}));
vi.mock('../notificationPreferences.service.js',()=>({isNotificationChannelEnabled:m.channel}));
vi.mock('../vonage.service.js',()=>({default:{sendSms:m.send}}));
vi.mock('../smsProfileAudit.service.js',()=>({recordSmsProfileAudit:vi.fn()}));
import Dispatcher from '../notificationDispatcher.service.js';
const notification={id:9,type:'client_exchange_match',user_id:7,agency_id:2};
beforeEach(()=>{vi.clearAllMocks();m.sender.mockResolvedValue('+17197163884');m.agency.mockResolvedValue({id:2,slug:'itsco',feature_flags:{companyEventsSenderNumberId:3}});m.prefs.mockResolvedValue({notification_categories:{staff_communications_2:{choices:{exchangeMatches:true}}}});m.channel.mockResolvedValue(true);m.gate.mockResolvedValue({sms:true});m.send.mockResolvedValue({sid:'mock'});vi.stubEnv('CLIENT_EXCHANGE_CLINICAL_SMS_AGENCY_IDS','');});
afterEach(()=>vi.unstubAllEnvs());
it('requires signed exchange consent even when the general SMS switch is enabled',async()=>{m.prefs.mockResolvedValue({notification_categories:{}});expect(await Dispatcher.dispatchForNotification(notification)).toMatchObject({reason:'exchange_sms_not_consented'});expect(m.send).not.toHaveBeenCalled();});
it('respects per-type opt-out and contact hours',async()=>{m.channel.mockResolvedValue(false);await Dispatcher.dispatchForNotification(notification);expect(m.send).not.toHaveBeenCalled();m.channel.mockResolvedValue(true);m.gate.mockResolvedValue({sms:false});await Dispatcher.dispatchForNotification(notification);expect(m.send).not.toHaveBeenCalled();});
it('keeps clinical details out of ordinary SMS and links to the secure exchange',async()=>{await Dispatcher.dispatchForNotification(notification,{context:{exchangeSummary:'Age: 9 · Diagnosis: F41.1'}});expect(m.send).toHaveBeenCalledWith(expect.objectContaining({staffNotificationKind:'exchangeMatches',body:expect.stringContaining('New client added to the exchange.')}));expect(m.send.mock.calls[0][0].body).toContain('/client-exchange');expect(m.send.mock.calls[0][0].body).not.toContain('F41.1');});
it('uses the configured staff campaign and ignores the old clinical-summary override',async()=>{
 vi.stubEnv('CLIENT_EXCHANGE_CLINICAL_SMS_AGENCY_IDS','2');
 await Dispatcher.dispatchForNotification({...notification,related_entity_type:'client_exchange_listing',related_entity_id:881},{context:{exchangeSummary:'Age: 9 · Diagnosis: F41.1'}});
 expect(m.sender).toHaveBeenCalledWith({agencyId:2,purpose:'workforce',numberId:3,requiredPurpose:'polling'});
 const text=m.send.mock.calls[0][0];expect(text.from).toBe('+17197163884');
 expect(text.body).not.toMatch(/Age:|F41|881|listingId/);
});
it('does not fall back to another number when the configured staff sender is unavailable',async()=>{
 m.sender.mockResolvedValue(null);expect(await Dispatcher.dispatchForNotification(notification)).toMatchObject({reason:'missing_from_number'});
 expect(m.sender).toHaveBeenCalledTimes(1);expect(m.send).not.toHaveBeenCalled();
});
