import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

test('management handoff: transactional referral, encrypted packet, tenant scope and live debt', { skip: process.env.COLLECTION_HANDOFF_MYSQL_TEST !== '1' }, async () => {
  assert.equal(process.env.DB_HOST, '127.0.0.1');
  assert.equal(process.env.DB_PORT, '33318');
  assert.equal(process.env.DB_NAME, 'collections_test');
  assert.equal(process.env.DB_PASSWORD, 'collections_test_only');
  const { default: mysql } = await import('mysql2/promise');
  const setup = await mysql.createConnection({ host: '127.0.0.1', port: 33318, user: 'root', password: 'collections_test_only', multipleStatements: true });
  try {
    await setup.query(`DROP DATABASE IF EXISTS collections_test;
      CREATE DATABASE collections_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
      USE collections_test;
      CREATE TABLE agencies(id INT PRIMARY KEY,name VARCHAR(255));
      CREATE TABLE users(id INT PRIMARY KEY,first_name VARCHAR(100),last_name VARCHAR(100),email VARCHAR(255),phone_number VARCHAR(100));
      CREATE TABLE user_agencies(user_id INT,agency_id INT,has_billing_access TINYINT);
      CREATE TABLE clients(id INT PRIMARY KEY,agency_id INT,full_name VARCHAR(255),date_of_birth DATE,billing_insurance_payload JSON);
      CREATE TABLE client_guardians(client_id INT,guardian_user_id INT,relationship_type VARCHAR(30),access_enabled TINYINT,permissions_json JSON);
      CREATE TABLE client_billing_payers(agency_id INT,client_id INT,guardian_user_id INT,status VARCHAR(30));
      CREATE TABLE family_billing_audit(id BIGINT PRIMARY KEY AUTO_INCREMENT,agency_id INT,actor_user_id INT,client_id INT,action VARCHAR(80),object_id BIGINT);
      INSERT INTO agencies VALUES(1,'Origin'),(2,'Management'),(3,'Unrelated');
      INSERT INTO users VALUES(20,'Synthetic','Payer','payer@example.test','5550100'),(99,'Origin','Staff',NULL,NULL),(98,'Management','Staff',NULL,NULL),(97,'Other','Staff',NULL,NULL);
      INSERT INTO user_agencies VALUES(99,1,1),(98,2,1),(97,3,1);
      INSERT INTO clients VALUES(10,1,'Synthetic Client','2017-01-01',NULL);
      INSERT INTO client_guardians VALUES(10,20,'guardian',1,NULL);
      INSERT INTO client_billing_payers VALUES(1,10,20,'active');`);
    const dir = new URL('../../../../database/migrations/', import.meta.url);
    const { readdir } = await import('node:fs/promises');
    const migrationName = (await readdir(dir)).find(name => name.startsWith('1414_'));
    await setup.query(await readFile(new URL(migrationName, dir), 'utf8'));
    await setup.query(await readFile(new URL('1494_management_collections.sql', dir), 'utf8'));
    await setup.query(`INSERT INTO family_collection_agreements(id,agency_id,managing_agency_id,active,agreement_reference) VALUES(1,1,2,1,'Synthetic signed agreement');
      INSERT INTO family_collection_permissions VALUES(1,99,'view'),(1,99,'escalate'),(2,98,'manage'),(2,98,'financial'),(3,97,'view');
      INSERT INTO family_receivables(id,agency_id,client_id,source_type,source_key,service_domain,service_date,amount_cents,due_date,status)
      VALUES(101,1,10,'staff_charge','copay-one','coaching','2026-01-01',5000,'2026-01-01','open'),
      (102,1,10,'staff_charge','copay-two','coaching','2026-01-02',5000,'2026-01-02','open');
      INSERT INTO family_receivable_allocations(id,agency_id,receivable_id,payer_user_id,amount_cents) VALUES(1,1,101,20,5000),(2,1,102,20,5000);`);
  } finally { await setup.end(); }
  const { default: pool } = await import('../../config/database.js');
  const { default: clinicalPool } = await import('../../config/clinicalDatabase.js');
  const { transferToCollections, collectionCaseDetail, handoffWorkspace, externallyManaged } = await import('../familyLedger/collectionHandoff.js');
  const { encryptFamilyBilling } = await import('../familyBillingEncryption.service.js');
  const { payAllocation } = await import('../familyLedger/payments.js');
  const user = { id: 99, role: 'admin' }, manager = { id: 98, role: 'admin' }, unrelated = { id: 97, role: 'admin' };
  const input = { user, agencyId: 1, agreementId: 1, allocationIds: [1,2], expectedAmountCents: 10000, idempotencyKey: 'handoff-test-one', mailingAddress: 'Synthetic Payer\n123 Test Street\nTest City CO 80000' };
  try {
    const notice = encryptFamilyBilling({ balances: [{ allocationId: 1, amountCents: 5000, dueDate: '2026-01-01' }, { allocationId: 999, clientId: 999, amountCents: 99999 }] }, 'collections:1:20');
    await pool.execute("INSERT INTO family_collections_notices(agency_id,payer_user_id,notice_kind,snapshot_encrypted,idempotency_key,created_by_user_id) VALUES(1,20,'past_due',?,'notice-test-one',99)", [notice]);
    await assert.rejects(transferToCollections({ ...input, user: manager }), e => e.status === 403);
    await assert.rejects(transferToCollections({ ...input, user: { ...user, role: 'provider' } }), e => e.status === 403);
    await assert.rejects(transferToCollections({ ...input, expectedAmountCents: 9999 }), e => e.status === 409);
    await pool.execute('UPDATE family_receivables SET due_date=CURRENT_DATE WHERE id=102');
    await assert.rejects(transferToCollections(input), /escalation age/);
    await pool.execute("UPDATE family_receivables SET due_date='2026-01-02' WHERE id=102");
    await pool.execute("INSERT INTO family_ledger_payments(agency_id,allocation_id,payer_user_id,processor,amount_cents,idempotency_key,snapshot_encrypted) VALUES(1,1,20,'STRIPE',5000,'pending-test-one','{}')");
    await assert.rejects(transferToCollections(input), /pending payments/);
    await pool.execute("UPDATE family_ledger_payments SET status='failed'");
    const [first, retry] = await Promise.all([transferToCollections(input), transferToCollections(input)]);
    assert.equal(first.caseId, retry.caseId);
    assert.equal(await externallyManaged(1), true);
    process.env.FAMILY_COLLECTIONS_ENABLED = 'false';
    assert.equal(await externallyManaged(1), true, 'Disabling new handoffs must not resume agency collection');
    process.env.FAMILY_COLLECTIONS_ENABLED = 'true';
    const [[counts]] = await pool.execute('SELECT COUNT(*) AS n FROM family_collection_cases');
    assert.equal(counts.n, 1);
    const [[source]] = await pool.execute('SELECT amount_cents,status FROM family_receivables WHERE id=101');
    assert.equal(source.amount_cents, 5000); assert.equal(source.status, 'open');
    const [[stored]] = await pool.execute('SELECT transfer_snapshot_encrypted FROM family_collection_cases');
    assert.ok(!stored.transfer_snapshot_encrypted.includes('Synthetic'));
    const detail = await collectionCaseDetail({ user: manager, agencyId: 2, caseId: first.caseId });
    assert.equal(detail.outstandingCents, 10000); assert.equal(detail.packet.serviceItems.length, 2);
    assert.equal(detail.packet.communications[0].lines.length, 1);
    assert.equal(JSON.stringify(detail).includes('99999'), false);
    assert.equal(detail.feeBasisPoints, 2500);
    assert.equal((await collectionCaseDetail({ user, agencyId: 1, caseId: first.caseId })).feeBasisPoints, undefined);
    await assert.rejects(collectionCaseDetail({ user: unrelated, agencyId: 3, caseId: first.caseId }), e => e.status === 404);
    await assert.rejects(transferToCollections({ ...input, idempotencyKey: 'duplicate-referral' }), /already belongs/);
    await assert.rejects(transferToCollections({ ...input, allocationIds: [1] }), /different handoff/);
    await assert.rejects(payAllocation({ agencyId: 1, userId: 20, allocationId: 1, amountCents: 5000, idempotencyKey: 'automatic-after-handoff', automatic: true }), /managed by collections/);
    await pool.execute("INSERT INTO family_ledger_payments(agency_id,allocation_id,payer_user_id,processor,amount_cents,status,idempotency_key,snapshot_encrypted,received_at) VALUES(1,1,20,'CASH',4000,'succeeded','confirmed-test-one','{}',CURRENT_TIMESTAMP)");
    await pool.execute('UPDATE family_receivable_allocations SET paid_cents=4000 WHERE id=1');
    const paid = await collectionCaseDetail({ user: manager, agencyId: 2, caseId: first.caseId });
    assert.equal(paid.outstandingCents, 6000); assert.equal(paid.transferredAmountCents, 10000);
    assert.equal(paid.currentHistory.payments.length, 2);
    await pool.execute("UPDATE family_receivables SET disputed_at=CURRENT_TIMESTAMP WHERE id=101");
    assert.equal((await collectionCaseDetail({ user: manager, agencyId: 2, caseId: first.caseId })).collectionBlocked, true);
    assert.equal((await handoffWorkspace({ user: manager, agencyId: 2 })).cases.length, 1);
    assert.equal((await handoffWorkspace({ user: unrelated, agencyId: 3 })).cases.length, 0);
    await pool.execute("INSERT INTO family_ledger_payments(agency_id,allocation_id,payer_user_id,processor,amount_cents,status,idempotency_key,snapshot_encrypted) VALUES(1,2,20,'STRIPE',5000,'requires_action','pending-after-handoff','{}')");
    const pendingDetail = await collectionCaseDetail({ user: manager, agencyId: 2, caseId: first.caseId });
    assert.match(pendingDetail.currentItems.find(item => item.allocationId === 2).issue, /confirmation is pending/);
    const [[confirmed]] = await pool.execute("SELECT id FROM family_ledger_payments WHERE idempotency_key='confirmed-test-one'");
    await assert.rejects(pool.execute('INSERT INTO family_collection_recoveries(case_id,payment_id,gross_recovery_cents,collection_fee_cents,agency_share_cents,received_at) VALUES(?,?,4000,1000,4000,CURRENT_TIMESTAMP)', [first.caseId, confirmed.id]), e => e.code === 'ER_CHECK_CONSTRAINT_VIOLATED');
    const [recovery] = await pool.execute('INSERT INTO family_collection_recoveries(case_id,payment_id,gross_recovery_cents,collection_fee_cents,agency_share_cents,received_at) VALUES(?,?,4000,1000,3000,CURRENT_TIMESTAMP)', [first.caseId, confirmed.id]);
    await assert.rejects(pool.execute('INSERT INTO family_collection_recoveries(case_id,payment_id,gross_recovery_cents,collection_fee_cents,agency_share_cents,received_at) VALUES(?,?,4000,1000,3000,CURRENT_TIMESTAMP)', [first.caseId, confirmed.id]), e => e.code === 'ER_DUP_ENTRY');
    await pool.execute("INSERT INTO family_collection_settlements(id,agency_id,managing_agency_id,period_start,period_end,gross_recovery_cents,collection_fee_cents,net_amount_cents) VALUES(1,1,2,'2026-09-01','2026-09-30',4000,1000,3000),(2,1,2,'2026-09-01','2026-09-30',4000,1000,3000)");
    await pool.execute('INSERT INTO family_collection_settlement_items VALUES(1,?)', [recovery.insertId]);
    await assert.rejects(pool.execute('INSERT INTO family_collection_settlement_items VALUES(2,?)', [recovery.insertId]), e => e.code === 'ER_DUP_ENTRY');
  } finally { await pool.end(); await clinicalPool.end(); }
});
