import {it,expect,vi} from 'vitest';
vi.mock('../../config/database.js',()=>({default:{execute:vi.fn()}}));
import {renderAmendment,commonAmendmentClauses} from '../../content/itscoOctober2026Drafts.js';
import {highestEligibleSickRate} from '../sickLeaveRate.service.js';
import {profileWithDatedAddition} from '../conditionalAdditionPolicy.service.js';
import {applyPaySystemToBreakdown,resolveUserPaySystemStatus} from '../paySystem.service.js';
import {itscoSuggestedTopicEdits} from '../../content/itscoOctober2026SuggestedEdits.js';
const profile={category:2,level:3,creditRate:44,creditRateProbation:38,hcodeRate:32,hcodeRateProbation:25,indirectRate:22,supportActivityRate:18,compensationPolicyVersion:'itsco-2026-10-service-credit-v3',tierBonusFfs:{1:0,2:0,3:2},tierBonusHcode:{1:0,2:0,3:0},spanishBonus:{3:2}};
const data={employee:{name:'Example',originalAgreementDate:'2024-01-01'},leaveChoice:'sick',schedule:{...profile,supportRate:18,ptoRate:44,category:2,level:3,levelDescription:'Assigned level',creditRateProbation:38,hcodeRateProbation:25,indirectRateProbation:22,supportRateProbation:18,probationWaived:true,tier3LevelBonus:2},commonClausesHtml:commonAmendmentClauses('sick')};
it('personalizes every amendment pay explanation and shows the earned Tier 3 total prominently',()=>{const html=renderAmendment(data);expect(html).not.toMatch(/Category 1|Category 3|Categories 2|probation/i);expect(html).toContain('Annual paid event-work commitment');expect(html).toContain('January 1–December 31');expect(html).not.toContain('hours per week');expect(html).toContain('50 qualifying session credits');expect(html).toContain('$46.00');expect(html).toContain('Minimum-workload rate');expect(html).toContain('60 calendar days');expect(html).not.toContain('or a higher rate required by law');expect(html).toContain('reclassify activity types prospectively');});
it('removes the conditional addition when the configured amount is zero',()=>{const html=renderAmendment({...data,schedule:{...data.schedule,tier3LevelBonus:0}});expect(html).not.toContain('Conditional Tier 3 addition</th>');expect(html).not.toContain('$46.00');expect(html).not.toMatch(/Conditional level-chart addition|Your Tier 3 example|Conditional Tier 3 addition<\/th>/i);});
it('sick leave uses current clinical base rates and excludes Tier 3 bonuses',()=>{expect(highestEligibleSickRate({rateProfile:profile,status:{tierLevel:1,currentTierLevel:1}})).toBe(44);expect(highestEligibleSickRate({rateProfile:profile,status:{tierLevel:0,currentTierLevel:0,useReducedRates:true}})).toBe(38);expect(highestEligibleSickRate({rateProfile:profile,status:{tierLevel:3,currentTierLevel:3,spanishBonusEligible:true}})).toBe(44);expect(highestEligibleSickRate({rateProfile:profile,status:{tierLevel:3,currentTierLevel:2}})).toBe(44);expect(highestEligibleSickRate({rateProfile:profile,clinicalEligible:false,status:{tierLevel:1}})).toBe(32);});
it('preserves an earned addition before its removal date, including a split payroll period',()=>{const p={...profile,conditionalAdditionMode:'dated_handbook',conditionalAdditionHistory:[{id:1,effective_on:'2026-10-10',clinical_addition:2,hcode_addition:0},{id:2,effective_on:'2026-11-01',clinical_addition:0,hcode_addition:0}]};expect(profileWithDatedAddition(p,'2026-10-31').tierBonusFfs[3]).toBe(2);expect(profileWithDatedAddition(p,'2026-11-01').tierBonusFfs[3]).toBe(0);
 const assignment={compensation_policy_version:p.compensationPolicyVersion,compensation_agreement_effective_on:'2026-10-10',waive_probation:1};const args={assignment,periodEnd:'2026-11-06',providerStartDate:'2024-01-01',benefitTierLevel:3,displayTierLevel:3};const status={...resolveUserPaySystemStatus(args),agreementBoundary:'2026-10-10',agreementStatusArgs:args,agreementLegacyAssignment:assignment,agreementPriorRateProfile:profile};const result=applyPaySystemToBreakdown({breakdown:{'90837':{units:2,finalizedUnits:2,category:'direct'}},rateProfile:p,status,datedUnitsByCode:new Map([['90837',[{serviceDate:'2026-10-31',units:1},{serviceDate:'2026-11-01',units:1}]]])});expect(result.bonuses.tierBonusAmount).toBe(2);
});
it('restores the practical card-printing steps with both QR destinations',()=>{const html=itscoSuggestedTopicEdits.business_cards.body;for(const word of ['Brother','right drawer','one sheet at a time','Matte Photo Paper','Print Quality to Great','blank-backed','fronts only','provider profile'])expect(html).toContain(word);});

it('shows the 50-session pretax example only for eligible levels',()=>{expect(renderAmendment(data)).toContain('50 × $46.00 = $2300.00');expect(renderAmendment({...data,schedule:{...data.schedule,tier3LevelBonus:0}})).not.toContain('Your Tier 3 example');});

it('uses the greater current direct base rate, never supervision, support or indirect allowances',()=>{expect(highestEligibleSickRate({rateProfile:{...profile,hcodeRate:50,indirectRate:65,supportActivityRate:100},status:{tierLevel:3,currentTierLevel:3}})).toBe(50);expect(renderAmendment(data)).toContain('Tier 3 additions, bonuses, pay differentials, supervision rates and indirect allowances are excluded');});
