import test from 'node:test';
import assert from 'node:assert/strict';
test('shared ledger: integer splits, private receipts, cash/card retries, refunds, plans, migration tasks and privacy grants', {skip:process.env.FAMILY_BILLING_MYSQL_TEST!=='1'},async()=>{
 assert.equal(process.env.DB_HOST,'127.0.0.1');assert.equal(process.env.DB_PORT,'33316');assert.equal(process.env.DB_NAME,'family_billing_test');
 const {default:pool}=await import('../../config/database.js');
 const {createReceivable,allocationsFor,setBillingRule}=await import('../familyLedger/receivables.js');
 const {payAllocation,recordCash,finalizePayment}=await import('../familyLedger/payments.js');
 const {refundPayment}=await import('../familyLedger/refunds.js');
 const {acceptPayer,assignCard}=await import('../familyBilling.service.js');
 const {BILLING_TERMS_VERSION}=await import('../familyBillingPolicy.service.js');
 const {default:Cards}=await import('../../models/GuardianPaymentCard.model.js');
 const {default:Stripe}=await import('../stripePayments.service.js');
 const {writeClientInsurance}=await import('../clientInsurance.service.js');
 const {receiptFor}=await import('../familyLedger/views.js');
 const {createPaymentTask,getPaymentTask,authorizePaymentTask,completePaymentTask}=await import('../familyLedger/tasks.js');
 const {proposePlan,acceptPlan,runDuePlans,PLAN_TERMS_VERSION}=await import('../familyLedger/plans.js');
 const {setStatementSharing}=await import('../familyLedger/sharing.js');
 const {clinicalAccess,setClinicalGrant,revokeClinicalGrant}=await import('../guardianClinicalAccess.service.js');
 const consent={accepted:true,version:BILLING_TERMS_VERSION,signatureName:'Synthetic Parent',waiverAccepted:true};
 try{
  for(const table of ['family_plan_installments','family_payment_plans','family_payment_refunds','family_ledger_payments','family_fulfillment_jobs','family_split_requests','family_receivable_allocations','family_receivables','family_billing_rules','family_statement_shares','family_billing_tasks','guardian_clinical_access_events','guardian_clinical_grants'])await pool.execute(`DELETE FROM ${table}`);
  await pool.execute("UPDATE clients SET date_of_birth='2017-01-01'");
  await pool.execute('UPDATE clients SET billing_insurance_payload=NULL');
  await acceptPayer({agencyId:1,clientId:102,userId:20,consent});
  const c10=await Cards.create({guardianUserId:10,agencyId:1,stripeCustomerId:'cus_ledger10',stripePaymentMethodId:'pm_ledger10',connectedAccountId:'acct_fixture',setupIntentId:'seti_ledger10',cardBrand:'visa',cardLast4:'1010'});
  const c20=await Cards.create({guardianUserId:20,agencyId:1,stripeCustomerId:'cus_ledger20',stripePaymentMethodId:'pm_ledger20',connectedAccountId:'acct_fixture',setupIntentId:'seti_ledger20',cardBrand:'visa',cardLast4:'2020'});
  for(const id of [101,102])for(const [userId,cardId] of [[10,c10],[20,c20]])await assignCard({agencyId:1,clientId:id,userId,cardId,recurring:false});
  await setBillingRule({agencyId:1,clientId:101,kind:'split',shares:[{payerUserId:10,basisPoints:5000},{payerUserId:20,basisPoints:5000}],actorUserId:99,reason:'Both guardians signed 50/50'});
  const r=await createReceivable({agencyId:1,clientId:101,sourceType:'staff_charge',sourceKey:'test:split',serviceDomain:'tutoring',amountCents:10001,actorUserId:99});
  const shares=await allocationsFor(r.id);assert.deepEqual(shares.map(a=>Number(a.amount_cents)),[5001,5000]);
  assert.equal((await createReceivable({agencyId:1,clientId:101,sourceType:'staff_charge',sourceKey:'test:split',serviceDomain:'tutoring',amountCents:10001})).id,r.id);
  await assert.rejects(payAllocation({agencyId:1,userId:20,allocationId:shares[0].id,amountCents:5001,idempotencyKey:'other-payer-attempt'}),e=>e.status===403);
  let charges=0;const intents=new Map();Stripe.chargePaymentMethod=async args=>{charges++;const intent={id:`pi_ledger_${charges}`,status:'succeeded',amount:args.amountCents,amount_received:args.amountCents,currency:args.currency,customer:args.customerId,metadata:args.metadata};intents.set(intent.id,intent);return intent;};Stripe.retrievePaymentIntent=async id=>intents.get(id);
  const card=await payAllocation({agencyId:1,userId:10,allocationId:shares[0].id,amountCents:5001,idempotencyKey:'split-card-attempt'});assert.equal(card.paid,true);
  assert.equal((await payAllocation({agencyId:1,userId:10,allocationId:shares[0].id,amountCents:5001,idempotencyKey:'split-card-attempt'})).alreadyPaid,true);assert.equal(charges,1);
  const [cash1,cash2]=await Promise.all([1,2].map(()=>recordCash({agencyId:1,allocationId:shares[1].id,payerUserId:20,amountCents:5000,idempotencyKey:'cash-receipt-one',actorUserId:99,note:'Cash received in office'})));assert.equal(cash1.paymentId,cash2.paymentId);
  const [[paid]]=await pool.execute('SELECT status FROM family_receivables WHERE id=?',[r.id]);assert.equal(paid.status,'paid');
  await assert.rejects(receiptFor({agencyId:1,paymentId:card.paymentId,userId:20}),e=>e.status===403);
  await assert.rejects(receiptFor({agencyId:2,paymentId:card.paymentId,userId:10}),e=>e.status===404);
  await setStatementSharing({agencyId:1,clientId:101,guardianUserId:20,active:true,actorUserId:99,reason:'Both parents consented to shared statements'});
  assert.equal((await receiptFor({agencyId:1,paymentId:card.paymentId,userId:20})).method,undefined);
  assert.equal((await receiptFor({agencyId:1,paymentId:card.paymentId,userId:30})).method,undefined);
  await assert.rejects(finalizePayment(card.paymentId,1,{...intents.get('pi_ledger_1'),amount_received:5000},'acct_fixture'),e=>e.status===409);
  const refund=await refundPayment({agencyId:1,paymentId:cash1.paymentId,amountCents:1000,idempotencyKey:'cash-refund-one',actorUserId:99,reason:'Cancelled service cash returned'});assert.equal(refund.refunded,true);
  const [[held]]=await pool.execute('SELECT status,hold_reason FROM family_receivables WHERE id=?',[r.id]);assert.equal(held.hold_reason,'refund_review');
  await assert.rejects(recordCash({agencyId:1,allocationId:shares[1].id,payerUserId:20,amountCents:1000,idempotencyKey:'cash-after-refund',actorUserId:99,note:'Do not collect held money'}),e=>e.status===409);
  const planBalance=await createReceivable({agencyId:1,clientId:102,sourceType:'staff_charge',sourceKey:'test:plan',serviceDomain:'coaching',amountCents:6000,shares:[{payerUserId:20,basisPoints:10000}]});const [allocation]=await allocationsFor(planBalance.id);
  const today=new Date().toISOString().slice(0,10),future=new Date(Date.now()+31*86400000).toISOString().slice(0,10);
  const plan=await proposePlan({agencyId:1,allocationId:allocation.id,installments:[{amountCents:3000,dueDate:today},{amountCents:3000,dueDate:future}],actorUserId:99});
  await assert.rejects(acceptPlan({agencyId:1,planId:plan.planId,userId:10,autoPay:true,consent:{...consent,version:PLAN_TERMS_VERSION}}),e=>e.status===403);
  await acceptPlan({agencyId:1,planId:plan.planId,userId:20,autoPay:true,consent:{...consent,version:PLAN_TERMS_VERSION}});
  const due=await runDuePlans({agencyId:1});assert.equal(due[0].paid,true,JSON.stringify(due));await runDuePlans({agencyId:1});assert.equal(charges,2);
  const task=await createPaymentTask({agencyId:1,guardianUserId:10,clientIds:[101,102],actorUserId:99,waiverText:'Approved synthetic migration terms'});
  await assert.rejects(getPaymentTask({userId:20,token:task.token}),e=>e.status===404);
  const opened=await getPaymentTask({userId:10,token:task.token});assert.equal(opened.waiver.additionalTerms,'Approved synthetic migration terms');
  await authorizePaymentTask({userId:10,token:task.token,consent});
  await assert.rejects(completePaymentTask({userId:10,token:task.token,cardId:c20,consent}),e=>e.status===409);
  assert.equal((await completePaymentTask({userId:10,token:task.token,cardId:c10,consent})).completed,true);
  assert.equal((await completePaymentTask({userId:10,token:task.token,cardId:c10,consent})).alreadyCompleted,true);
  const [[raw]]=await pool.execute('SELECT * FROM family_billing_tasks WHERE id=?',[task.taskId]);assert.ok(!raw.signed_evidence_encrypted.includes('Synthetic Parent'));assert.notEqual(raw.token_hash,task.token);
  await writeClientInsurance({agencyId:1,clientId:101,primary:{insurerName:'Health First Colorado',memberId:'MEDICAID-FIXTURE',isMedicaid:true}});
  await assert.rejects(createPaymentTask({agencyId:1,guardianUserId:10,clientIds:[101],actorUserId:99}),e=>e.status===409);
  const protectedBalance=await createReceivable({agencyId:1,clientId:101,sourceType:'claim_responsibility',sourceKey:'synthetic:claim',serviceDomain:'mental_health',amountCents:1000,insuranceReviewed:true});assert.equal(protectedBalance.status,'review');
  assert.equal((await clinicalAccess({agencyId:1,clientId:101,userId:10})).scopes.length,0);
  await setClinicalGrant({agencyId:1,clientId:101,guardianUserId:10,accessLevel:'full',medicalRightsVerified:true,consentBasis:'legal_representative',reviewDueDate:'2030-01-01',reason:'Verified synthetic guardianship',actorUserId:99});
  assert.ok((await clinicalAccess({agencyId:1,clientId:101,userId:10})).scopes.includes('treatment_plan'));
  await pool.execute("UPDATE clients SET date_of_birth='2013-01-01' WHERE id=101");
  await revokeClinicalGrant({agencyId:1,clientId:101,guardianUserId:10,userId:30,reason:'Restrict goals only',scopes:['treatment_plan','approve_goals']});
  const restricted=await clinicalAccess({agencyId:1,clientId:101,userId:10});assert.equal(restricted.level,'restricted');assert.equal(restricted.scopes.includes('treatment_plan'),false);assert.equal(restricted.scopes.includes('safety_plan'),true);
  await revokeClinicalGrant({agencyId:1,clientId:101,guardianUserId:10,userId:30,reason:'Request privacy'});assert.equal((await clinicalAccess({agencyId:1,clientId:101,userId:10})).scopes.length,0);
 }finally{await pool.end();}
});
