import {beforeEach,describe,it,expect,vi} from 'vitest';
const m=vi.hoisted(()=>({execute:vi.fn(),commit:vi.fn(),rollback:vi.fn(),pdf:vi.fn(),member:vi.fn()}));
vi.mock('../../config/database.js',()=>({default:{execute:m.execute,getConnection:async()=>({execute:m.execute,beginTransaction:async()=>{},commit:m.commit,rollback:m.rollback,release:()=>{}})}}));
vi.mock('../meetingJoinPolicy.service.js',()=>({hasActiveMeetingMembership:m.member}));
vi.mock('../recordingAgreementDocument.service.js',async original=>({...await original(),saveRecordingAgreementPdf:m.pdf}));
import {documentHash} from '../recordingAgreementDocument.service.js';
import {signSupervisionAgreement} from '../supervisionAgreement.service.js';
let row;
const input=()=>({documentHash:row.document_hash,accepted:true,typedName:'Test signer'});
beforeEach(()=>{vi.clearAllMocks();process.env.GUARDIAN_INTAKE_ENCRYPTION_KEY_BASE64=Buffer.alloc(32,1).toString('base64');const doc={agencyName:'Example',version:1,text:'Test agreement',parties:[{name:'Supervisor'},{name:'Supervisee'}]};row={id:1,agency_id:2,assignment_id:4,supervisor_user_id:7,supervisee_user_id:8,version:1,document_json:doc,document_hash:documentHash(doc)};m.member.mockResolvedValue(true);m.pdf.mockResolvedValue({path:'private/signed.pdf',hash:'pdfhash'});m.execute.mockImplementation(async sql=>{if(sql.includes('SELECT * FROM supervision_agreements'))return [[row]];if(sql.includes('SELECT id FROM supervisor_assignments'))return [[{id:4}]];return [{insertId:22}];});});
describe('two-party supervision agreement signatures',()=>{
 it('saves the exact document with each signature and files two signed copies only when both sign',async()=>{const first=await signSupervisionAgreement({agreementId:1,userId:7,input:input()});expect(first.complete).toBe(false);expect(m.execute.mock.calls.filter(([q])=>q.includes('INSERT INTO signed_documents'))).toHaveLength(0);const second=await signSupervisionAgreement({agreementId:1,userId:8,input:input()});expect(second.complete).toBe(true);expect(m.execute.mock.calls.filter(([q])=>q.includes('INSERT INTO signed_documents'))).toHaveLength(2);expect(m.pdf.mock.calls[1][1]).toHaveLength(2);expect(row.supervisor_signature_json).not.toContain('Test signer');});
 it('rejects a different user, stale document, and supervisor signatures through a candidate portal',async()=>{await expect(signSupervisionAgreement({agreementId:1,userId:999,input:input()})).rejects.toMatchObject({status:403});await expect(signSupervisionAgreement({agreementId:1,userId:8,input:{...input(),documentHash:'wrong'}})).rejects.toMatchObject({status:409});await expect(signSupervisionAgreement({agreementId:1,userId:7,input:input(),portal:true})).rejects.toMatchObject({status:403});expect(m.pdf).not.toHaveBeenCalled();});
 it('does not reuse an agreement after a supervisor assignment changes',async()=>{m.execute.mockImplementation(async sql=>sql.includes('SELECT * FROM supervision_agreements')?[[row]]:[[]]);await expect(signSupervisionAgreement({agreementId:1,userId:8,input:input()})).rejects.toMatchObject({status:409});expect(m.pdf).not.toHaveBeenCalled();});
 it('rolls back the signature if the signed PDF cannot be saved',async()=>{m.pdf.mockRejectedValue(new Error('Storage unavailable'));await expect(signSupervisionAgreement({agreementId:1,userId:8,input:input()})).rejects.toThrow('Storage unavailable');expect(m.rollback).toHaveBeenCalled();expect(m.commit).not.toHaveBeenCalled();expect(m.execute.mock.calls.some(([q])=>q.includes('UPDATE supervision_agreements'))).toBe(false);});
});
