import {describe,it,expect,vi,beforeEach} from 'vitest';
vi.mock('../../config/database.js',()=>({default:{execute:vi.fn(),getConnection:vi.fn()}}));
import pool from '../../config/database.js';
import {deliverPollResults,pollResultsMessage,getPollResultPreference,setPollResultPreference} from '../companyEventPollResults.service.js';
beforeEach(()=>vi.resetAllMocks());
const event={id:12,title:'Staff date poll'},summary=[{key:'1',label:'Tuesday',total:8}];
function connection(prior=[]){return {execute:vi.fn().mockResolvedValueOnce([[{acquired:1}]]).mockResolvedValueOnce([prior]).mockResolvedValueOnce([{insertId:99}]).mockResolvedValue([{}]),release:vi.fn()};}
it('defaults result texts off and stores only an explicit boolean without replacing other preferences',async()=>{pool.execute.mockResolvedValue([[]]);expect(await getPollResultPreference(12,3)).toBe(false);await expect(setPollResultPreference(12,3,'yes')).rejects.toMatchObject({status:400});await setPollResultPreference(12,3,true);expect(pool.execute.mock.lastCall[0]).toContain('JSON_SET(COALESCE(notification_categories');expect(pool.execute.mock.lastCall[1]).toContain('true');});
it('never sends to someone who has not requested results or has no phone',async()=>{const send=vi.fn(),db={getConnection:vi.fn()};const result=await deliverPollResults({event,summary,recipients:[{id:3,phone:'123'},{id:4}],send,optedIn:async()=>false,db});expect(result.skipped).toBe(2);expect(send).not.toHaveBeenCalled();expect(db.getConnection).not.toHaveBeenCalled();});
it('sends aggregate totals once and records delivery',async()=>{const conn=connection(),send=vi.fn();const result=await deliverPollResults({event,summary,recipients:[{id:3,phone:'123'}],send,optedIn:async()=>true,db:{getConnection:async()=>conn}});expect(result.sent).toBe(1);expect(send.mock.calls[0][0].body).toContain('Tuesday: 8');expect(conn.execute.mock.calls.some(([sql])=>sql.includes("status = 'sent'"))).toBe(true);expect(conn.release).toHaveBeenCalled();});
it('does not resend a previously attempted result text',async()=>{const send=vi.fn();const result=await deliverPollResults({event,summary,recipients:[{id:3,phone:'123'}],send,optedIn:async()=>true,db:{getConnection:async()=>connection([{id:5}])}});expect(result.skipped).toBe(1);expect(send).not.toHaveBeenCalled();});
it('honors a preference withdrawal after acquiring the delivery lock',async()=>{const send=vi.fn(),optedIn=vi.fn().mockResolvedValueOnce(true).mockResolvedValueOnce(false);await deliverPollResults({event,summary,recipients:[{id:3,phone:'123'}],send,optedIn,db:{getConnection:async()=>connection()}});expect(send).not.toHaveBeenCalled();});
it('records consent suppression or send failure without bypassing transport',async()=>{const conn=connection();const result=await deliverPollResults({event,summary,recipients:[{id:3,phone:'123'}],send:async()=>{throw Object.assign(Error(),{code:'SMS_OPTED_OUT'});},optedIn:async()=>true,db:{getConnection:async()=>conn}});expect(result.failed).toBe(1);expect(conn.execute.mock.calls.some(([sql,args])=>sql.includes("status = 'failed'")&&args[0]==='SMS_OPTED_OUT')).toBe(true);});
it('uses an app notice for long totals and does not expose individual choices',()=>{expect(pollResultsMessage(event,[{label:'X'.repeat(500),total:1,userName:'Private'}])).toContain('View the final totals in the app');expect(pollResultsMessage(event,summary)).not.toContain('Private');});
