import { redactSmsCampaignSettings } from '../../utils/smsCampaignPublicRedaction.js';
import { beforeEach, describe, it, expect, vi } from 'vitest';
vi.mock('../../config/database.js',()=>({default:{execute:vi.fn(),getConnection:vi.fn()}}));
vi.mock('../../utils/publicPortalUrl.js',()=>({buildPublicPortalBaseUrl:a=>`https://portal.example.org/${a.slug}`}));
import pool from '../../config/database.js';
import { normalizeCampaignProfile, campaignProfileErrors, buildCampaignPacket, campaignPublicContent, campaignPacketMarkdown } from '../../utils/smsCampaignPacket.js';
import { getAgencyCampaignPacket, getPublicCampaignPacket, saveAgencyCampaignPacket } from '../smsCampaignPacket.service.js';
const profile=normalizeCampaignProfile({legalName:'Example Coaching LLC',brandName:'Example Coaching',supportContact:'support@example.org',website:'https://example.org',portalUrl:'https://portal.example.org/coaching',organizationPrivacyUrl:'https://example.org/privacy',ownership:'own',volume:'low'});
const options={agencyId:72,program:'polling',origin:'https://portal.example.org'};
const packet=()=>buildCampaignPacket(profile,options);
beforeEach(()=>vi.resetAllMocks());
describe('agency campaign packet generation',()=>{
 it('generates a staff and polling low volume request without marking approval',()=>{const p=packet();expect(p.steps[0].fields['Use case']).toBe('Low Volume Mixed');expect(p.steps[0].fields['Sub-use cases']).toBe('POLLING_VOTING, ACCOUNT_NOTIFICATION');expect(p.registration).toMatchObject({approved:false,numberLinked:false,campaignId:'',purposes:['polling','workforce']});expect(p.missing).toEqual([]);expect(campaignPacketMarkdown(p)).toContain('7. Activate after approval');});
 it('keeps coaching identity and staff consent separate from clinical brands',()=>{const p=campaignPublicContent(packet());expect(p.consent.disclosure.brandName).toBe('Example Coaching');expect(p.consent.disclosure.purposes.map(p=>p.purpose)).toEqual(['polling','workforce']);expect(p.consent.disclosure.text).not.toContain('AuricWell');expect(p.consent.example).toBe(true);expect(()=>campaignPublicContent(packet(),'client')).toThrow('staff');});
 it('separates agencies and rejects unknown or inherited program names',()=>{expect(packet().links.termsUrl).toContain('/72/polling/');expect(buildCampaignPacket(profile,{...options,agencyId:73}).links.termsUrl).toContain('/73/polling/');expect(()=>buildCampaignPacket(profile,{...options,program:'__proto__'})).toThrow();expect(()=>buildCampaignPacket(profile,{...options,program:'constructor'})).toThrow();});
 it('requires real identity and rejects unsafe URLs without accepting secrets',()=>{expect(campaignProfileErrors(normalizeCampaignProfile({}))).toContain('legalName is required');expect(()=>normalizeCampaignProfile({...profile,website:'javascript:alert(1)'})).toThrow();expect(()=>normalizeCampaignProfile({...profile,website:'https://user:secret@example.org'})).toThrow();expect(normalizeCampaignProfile({...profile,ein:'private',apiSecret:'private'})).not.toHaveProperty('ein');expect(campaignProfileErrors({...profile,ownership:'reseller',resellerId:'R000000'}).join(' ')).toContain('not reseller');});
 it('keeps control messages within carrier field limits for allowed identity sizes',()=>{const p=buildCampaignPacket({...profile,brandName:'B'.repeat(60),supportContact:'a'.repeat(80)+'@example.org'},options);for(const [key,value] of Object.entries(p.steps[3].fields))if(key.endsWith('message'))expect(value.length).toBeLessThanOrEqual(320);});
 it('generates marketing separately and staff examples omit client choices',()=>{const m=buildCampaignPacket(profile,{...options,program:'marketing'});expect(m.registration.purposes).toEqual(['marketing']);const o=buildCampaignPacket(profile,{...options,program:'operations'});expect(campaignPublicContent(o,'staff').consent.disclosure.purposes.map(p=>p.purpose)).toEqual(['workforce']);});
});
describe('draft and public isolation',()=>{
 const agency=(flags={})=>({id:72,slug:'coaching',name:'Example Coaching',official_name:'Example Coaching LLC',tax_id:'NEVER PUBLIC',feature_flags:flags});
 it('will not expose an unpublished program',async()=>{pool.execute.mockResolvedValue([[agency({smsCampaignPackets:{polling:{draft:{profile}}}})]]);await expect(getPublicCampaignPacket(72,'polling')).rejects.toMatchObject({status:404});});
 it('serves the published snapshot even while another draft is edited',async()=>{pool.execute.mockResolvedValue([[agency({smsCampaignPackets:{polling:{draft:{profile:{...profile,brandName:'Unpublished'}},published:{profile,at:'2026-10-06T12:00:00Z',by:999}}}})]]);const publicPage=await getPublicCampaignPacket(72,'polling');expect(publicPage.brandName).toBe('Example Coaching');expect(JSON.stringify(publicPage)).not.toMatch(/NEVER PUBLIC|Unpublished|"by"|999/);const draft=await getAgencyCampaignPacket(72,'polling');expect(draft.published).toBe(false);expect(draft.hasPublished).toBe(true);});
 it('reuses the agency identity for a new program without a new code change',async()=>{pool.execute.mockResolvedValue([[agency({smsCampaignProfile:profile})]]);const p=await getAgencyCampaignPacket(72,'workforce');expect(p.profile).toEqual(profile);expect(p.registration.purposes).toEqual(['workforce']);expect(p.published).toBe(false);});
 it('requires explicit review before publishing',async()=>{pool.execute.mockResolvedValue([[agency()]]);await expect(saveAgencyCampaignPacket({agencyId:72,program:'polling',input:{profile,publish:true},actorUserId:3})).rejects.toThrow('Confirm');expect(pool.getConnection).not.toHaveBeenCalled();});
 it('changes only the selected program and retains its publication when saving a draft',async()=>{const existing={draft:{profile},published:{profile,at:'2026-10-06',by:1}};pool.execute.mockResolvedValue([[agency({smsCampaignPackets:{polling:existing}})]]);const conn={beginTransaction:vi.fn(),execute:vi.fn().mockResolvedValueOnce([[agency({smsCampaignPackets:{polling:existing}})]]).mockResolvedValue([{}]),commit:vi.fn(),rollback:vi.fn(),release:vi.fn()};pool.getConnection.mockResolvedValue(conn);await saveAgencyCampaignPacket({agencyId:72,program:'polling',input:{profile:{...profile,brandName:'Draft edit'}},actorUserId:3});const params=conn.execute.mock.calls[1][1];expect(JSON.parse(params[0]).polling.published).toEqual(existing.published);expect(JSON.parse(params[1]).brandName).toBe('Draft edit');expect(conn.commit).toHaveBeenCalled();});
});

it('keeps packet drafts out of public branding responses without mutating stored data',()=>{const agency={id:2,feature_flags:JSON.stringify({smsCampaignPackets:{polling:{draft:{profile}}},smsCampaignProfile:profile,smsNumbersEnabled:true}),nested:{featureFlags:{smsCampaignProfile:profile,other:true}}};const redacted=redactSmsCampaignSettings(agency);expect(JSON.parse(redacted.feature_flags)).toEqual({smsNumbersEnabled:true});expect(redacted.nested.featureFlags).toEqual({other:true});expect(agency.feature_flags).toContain('smsCampaignPackets');});
