import {beforeAll,afterAll,beforeEach,describe,it,expect,vi} from 'vitest';
import express from 'express';
const f=vi.hoisted(()=>({execute:vi.fn(),send:vi.fn(),calls:[],member:null,session:false}));
vi.mock('../../config/database.js',()=>({default:{execute:(...a)=>f.execute(...a),getConnection:async()=>({execute:(...a)=>f.execute(...a),beginTransaction:async()=>{},commit:async()=>{},rollback:async()=>{},release:()=>{}})}}));
vi.mock('../../middleware/auth.middleware.js',()=>({authenticate:(req,res,next)=>{if(!req.get('X-Test-Platform-User'))return res.status(401).json({error:'platform session required'});req.user={id:44,role:'admin'};next();}}));
vi.mock('../../middleware/rateLimiter.middleware.js',()=>{const pass=(req,res,next)=>next();return {signupLimiter:pass,authLimiter:pass,recoveryLimiter:pass,publicMarketingPageMetricsLimiter:pass};});
vi.mock('../email.service.js',()=>({default:{sendEmail:(...a)=>f.send(...a)}}));
vi.mock('../storage.service.js',()=>({default:{}}));
vi.mock('bcrypt',()=>({default:{hash:async()=>'$hashed',compare:async()=>true}}));
import router from '../../routes/providerDirectory.routes.js';
import {cleanProfile} from '../providerDirectoryProfile.service.js';
let server,origin;
const portal={id:1,slug:'latinx',agency_id:2,name:'Latinx Therapist Project CO',public_origin:'https://plottwisthq.com',heritage_required:1,is_active:1};
const profile=cleanProfile({name:'Synthetic Provider',credentials:'LPC',bio:'This synthetic profile has a biography suitable for testing only.',publicEmail:'public@example.com',virtual:true,languages:['Spanish'],specialties:['Anxiety'],licenses:[{state:'CO',type:'LPC',number:'PRIVATE123',expires:'2099-01-01'}]});
const member=()=>({id:7,portal_id:1,member_role:'provider',is_active:1,email_verified:1,opt_in:1,heritage:'Latina',status:'pending',draft_json:profile,published_json:null,revision:2,email:'private@example.com',username:'synthetic'});
async function request(path,{method='GET',body,session=true,platform=false}={}){const r=await fetch(`${origin}${path}`,{method,headers:{'Content-Type':'application/json',...(session?{'X-Directory-Session':'a'.repeat(64)}:{}),...(platform?{'X-Test-Platform-User':'44'}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};}
beforeAll(async()=>{const app=express();app.use(express.json());app.use(router);server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});origin=`http://127.0.0.1:${server.address().port}`;});
afterAll(async()=>{await new Promise(resolve=>server.close(resolve));});
beforeEach(()=>{f.member=member();f.session=true;f.calls=[];f.send.mockResolvedValue({success:true});f.execute.mockImplementation(async(sql,args=[])=>{f.calls.push({sql,args});
 if(sql.includes('FROM provider_directory_portals'))return [[portal]];
 if(sql.includes('FROM provider_directory_sessions s'))return [f.session&&args[1]===1?[f.member]:[]];
 if(sql.includes('FROM user_agencies'))return [[]];
 if(sql.includes('SELECT id,role,is_active,status FROM users'))return [[{id:44,role:'super_admin',is_active:1,status:'ACTIVE_EMPLOYEE'}]];
 if(sql.includes('SELECT * FROM provider_directory_members'))return [[f.member]];
 if(sql.includes('SELECT COUNT(*) AS total'))return [[{total:1}]];
 if(sql.includes('SELECT id,published_json'))return [[{id:7,published_json:{...profile,secret:'not public'}}]];
 return [{affectedRows:1,insertId:7}];
 });});
describe('directory account and tenant boundaries',()=>{
 it('does not accept a directory session as a platform administrator login',async()=>{expect((await request('/latinx/admin-session',{method:'POST'})).status).toBe(401);});
 it('prevents a platform admin of another agency opening this tenant dashboard',async()=>{expect((await request('/latinx/admin-session',{method:'POST',platform:true})).status).toBe(403);});
 it('requires a valid directory session and portal binding',async()=>{f.session=false;expect((await request('/latinx/me')).status).toBe(401);expect(f.calls.find(c=>c.sql.includes('FROM provider_directory_sessions s')).args[1]).toBe(portal.id);});
 it('prevents provider sessions from reading the admin queue',async()=>{expect((await request('/latinx/review')).status).toBe(403);});
 it('ignores role and publication injections at registration',async()=>{const r=await request('/latinx/register',{method:'POST',session:false,body:{email:'new@example.com',username:'newprovider',password:'long-test-password',member_role:'admin',user_id:44,status:'approved',published_json:profile}});expect(r.status).toBe(201);const insert=f.calls.find(c=>c.sql.startsWith('INSERT INTO provider_directory_members'));expect(insert.sql).not.toMatch(/member_role|user_id|published_json|status/);expect(insert.args).toContain('$hashed');});
 it('returns only public approved fields from search',async()=>{const r=await request('/latinx/providers',{session:false});expect(r.status).toBe(200);expect(JSON.stringify(r.body)).not.toMatch(/PRIVATE123|private@example|secret/);const q=f.calls.find(c=>c.sql.includes('SELECT id,published_json'));expect(q.sql).toContain('portal_id=?');expect(q.sql).toContain('opt_in=1');expect(q.sql).toContain('email_verified=1');});
 it('rejects stale review and requires a submitted profile',async()=>{f.member={...member(),member_role:'admin',user_id:44};const target={...member(),status:'draft'};const prior=f.execute.getMockImplementation();f.execute.mockImplementation((sql,args)=>sql.includes('FOR UPDATE')?Promise.resolve([[target]]):prior(sql,args));
 expect((await request('/latinx/review/7',{method:'POST',body:{action:'approved',revision:1}})).status).toBe(409);
 expect((await request('/latinx/review/7',{method:'POST',body:{action:'approved',revision:2}})).status).toBe(409);
 expect(f.calls.some(c=>c.sql.startsWith('UPDATE provider_directory_members SET status='))).toBe(false);
 });
 it('will not publish without email verification and consent even if an admin approves',async()=>{f.member={...member(),member_role:'admin',user_id:44};const target={...member(),email_verified:0,opt_in:0};const prior=f.execute.getMockImplementation();f.execute.mockImplementation((sql,args)=>sql.includes('FOR UPDATE')?Promise.resolve([[target]]):prior(sql,args));const r=await request('/latinx/review/7',{method:'POST',body:{action:'approved',revision:2}});expect(r.status).toBe(400);expect(r.body.error.message).toMatch(/Verify/);});
 it('records a submission without publishing the draft',async()=>{const r=await request('/latinx/me/submit',{method:'POST',body:{status:'approved'}});expect(r.status).toBe(200);const updates=f.calls.filter(c=>c.sql.startsWith('UPDATE provider_directory_members'));expect(updates).toHaveLength(1);expect(updates[0].sql).toContain("status='pending'");expect(updates[0].sql).not.toContain('published_json');});
 it('keeps concurrent draft changes from being overwritten',async()=>{const prior=f.execute.getMockImplementation();f.execute.mockImplementation((sql,args)=>sql.startsWith('UPDATE provider_directory_members SET draft_json')?Promise.resolve([{affectedRows:0}]):prior(sql,args));expect((await request('/latinx/me',{method:'PUT',body:{revision:1,profile}})).status).toBe(409);});
});
