import {describe,it,expect,vi,beforeAll,afterAll} from 'vitest';
import mysql from 'mysql2/promise';
import fs from 'node:fs/promises';
import express from 'express';
const fixture=vi.hoisted(()=>({pool:null,emails:[]}));
vi.mock('../../config/database.js',()=>({default:{execute:(...args)=>fixture.pool.execute(...args),getConnection:()=>fixture.pool.getConnection()}}));
vi.mock('../../middleware/auth.middleware.js',()=>({authenticate:(req,res,next)=>{if(req.get('X-Test-Platform-User')!=='44')return res.sendStatus(401);req.user={id:44,role:'admin'};next();}}));
vi.mock('../../middleware/rateLimiter.middleware.js',()=>{const pass=(req,res,next)=>next();return {signupLimiter:pass,authLimiter:pass,recoveryLimiter:pass,publicMarketingPageMetricsLimiter:pass};});
vi.mock('../email.service.js',()=>({default:{sendEmail:async data=>{fixture.emails.push(data);return {success:true};}}}));
vi.mock('../storage.service.js',()=>({default:{}}));
import router from '../../routes/providerDirectory.routes.js';
const socket=process.env.PROVIDER_DIRECTORY_TEST_SOCKET;
describe.skipIf(!socket)('directory workflow with isolated MySQL',()=>{
 let connection,server,origin,migration;
 beforeAll(async()=>{
  if(socket!=='/private/tmp/latinx-directory-test.sock')throw new Error('Only the dedicated disposable test socket is allowed.');
  connection=await mysql.createConnection({socketPath:socket,user:'root',multipleStatements:true});
  await connection.query('CREATE DATABASE provider_directory_test');
  await connection.query('USE provider_directory_test');
  await connection.query(`CREATE TABLE agencies(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255),slug VARCHAR(100) UNIQUE,is_active BOOLEAN);
   CREATE TABLE users(id INT PRIMARY KEY,email VARCHAR(255),username VARCHAR(100),first_name VARCHAR(100),last_name VARCHAR(100),role VARCHAR(50),status VARCHAR(50),is_active BOOLEAN,has_provider_access BOOLEAN);
   CREATE TABLE user_agencies(user_id INT,agency_id INT);
   INSERT INTO users VALUES(44,'admin@example.com','admin','Test','Admin','admin','ACTIVE_EMPLOYEE',1,0);`);
  migration=await fs.readFile(new URL('../../../../database/migrations/1482_provider_directory_enrollment.sql',import.meta.url),'utf8');
  await connection.query(migration);await connection.query(migration);
  fixture.pool=mysql.createPool({socketPath:socket,user:'root',database:'provider_directory_test',connectionLimit:3});
  const app=express();app.use(express.json());app.use(router);server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});origin=`http://127.0.0.1:${server.address().port}`;
 });
 afterAll(async()=>{if(server)await new Promise(resolve=>server.close(resolve));if(fixture.pool)await fixture.pool.end();if(connection){await connection.query('DROP DATABASE IF EXISTS provider_directory_test');await connection.end();}});
 it('preserves tenant seed and enforces registration, review snapshots, revisions, withdrawal and reset',async()=>{
  const request=async(path,method='GET',body,token,platform=false)=>{const r=await fetch(origin+path,{method,headers:{'Content-Type':'application/json',...(token?{'X-Directory-Session':token}:{}),...(platform?{'X-Test-Platform-User':'44'}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};
  const [[count]]=await connection.query('SELECT COUNT(*) AS n FROM agencies');expect(count.n).toBe(1);
  const [[portal]]=await connection.query("SELECT * FROM provider_directory_portals WHERE slug='latinx'");
  expect(portal.name).toBe('Latinx Therapist Project CO');
  expect((await request('/latinx/admin-session','POST',{},null,true)).status).toBe(403);
  await connection.execute('INSERT INTO user_agencies VALUES(44,?)',[portal.agency_id]);
  const admin=await request('/latinx/admin-session','POST',{},null,true);expect(admin.status).toBe(200);const adminToken=admin.data.token;
  const registration=await request('/latinx/register','POST',{email:'synthetic@example.com',username:'synthetic',password:'A-long-test-password',member_role:'admin'});
  expect(registration.status).toBe(201);expect(registration.data.member.role).toBe('provider');const providerToken=registration.data.token;let member=registration.data.member;
  expect((await request('/latinx/review','GET',null,providerToken)).status).toBe(403);
  const verify=new URL(fixture.emails[0].linkUrl).searchParams.get('verify');
  expect((await request('/latinx/token','POST',{purpose:'verify',token:verify})).status).toBe(200);
  expect((await request('/latinx/token','POST',{purpose:'verify',token:verify})).status).toBe(400);
  const profile={name:'Test Provider',credentials:'LPC',bio:'A synthetic provider biography to exercise complete directory enrollment.',virtual:true,publicEmail:'public@example.com',specialties:['Anxiety'],languages:['Spanish'],licenses:[{state:'CO',type:'LPC',number:'PRIVATE123',expires:'2099-12-31'}]};
  member=(await request('/latinx/me','PUT',{profile,heritage:'Latina',optIn:true,revision:member.revision},providerToken)).data;
  expect(member.profile.name).toBe('Test Provider');expect((await request('/latinx/providers')).data.total).toBe(0);
  member=(await request('/latinx/me/submit','POST',{},providerToken)).data;expect(member.status).toBe('pending');
  expect((await request(`/latinx/review/${member.id}`,'POST',{action:'approved',revision:member.revision},adminToken)).status).toBe(200);
  let result=await request('/latinx/providers');expect(result.data.total).toBe(1);expect((await request('/latinx/providers?state=CO&care=virtual&language=Spanish&specialty=Anxiety')).data.total).toBe(1);expect((await request('/latinx/providers?state=NY')).data.total).toBe(0);expect((await request('/latinx/providers?search=Test')).data.total).toBe(1);expect(JSON.stringify(result.data)).not.toMatch(/PRIVATE123|synthetic@example|Latina/);
  member=(await request('/latinx/me','GET',null,providerToken)).data;
  const oldRevision=member.revision;
  member=(await request('/latinx/me','PUT',{profile:{...profile,name:'Unapproved edit'},heritage:'Latina',optIn:true,revision:member.revision},providerToken)).data;
  result=await request('/latinx/providers');expect(result.data.providers[0].name).toBe('Test Provider');
  expect((await request(`/latinx/review/${member.id}`,'POST',{action:'approved',revision:oldRevision},adminToken)).status).toBe(409);
  member=(await request('/latinx/me/submit','POST',{},providerToken)).data;
  expect((await request(`/latinx/review/${member.id}`,'POST',{action:'approved',revision:member.revision},adminToken)).status).toBe(200);
  expect((await request('/latinx/providers')).data.providers[0].name).toBe('Unapproved edit');
  member=(await request('/latinx/me','GET',null,providerToken)).data;
  expect((await request('/latinx/me','PUT',{profile:member.profile,heritage:'Latina',optIn:false,revision:member.revision},providerToken)).status).toBe(200);
  expect((await request('/latinx/providers')).data.total).toBe(0);
  await connection.execute("INSERT INTO provider_directory_portals(slug,agency_id,name) VALUES('other',?,'Other')",[portal.agency_id]);
  expect((await request('/other/me','GET',null,providerToken)).status).toBe(401);
  await request('/latinx/recover','POST',{email:'synthetic@example.com'});
  const reset=new URL(fixture.emails.at(-1).linkUrl).searchParams.get('reset');
  expect((await request('/latinx/token','POST',{purpose:'reset',token:reset,password:'A-new-long-password'})).status).toBe(200);
  expect((await request('/latinx/me','GET',null,providerToken)).status).toBe(401);
  expect((await request('/latinx/login','POST',{username:'synthetic',password:'A-new-long-password'})).status).toBe(200);
  const [[users]]=await connection.query('SELECT COUNT(*) AS n FROM users');expect(users.n).toBe(1);
 });
});
