import {describe,it,expect,vi} from 'vitest';
vi.mock('../../config/database.js',()=>({default:{}}));
import {planWeeklyEdit,editAvailabilityPublication} from '../availabilityPublicationEdit.service.js';
import {availabilityOccursOn} from '../../utils/availabilityRecurrence.js';
import {slotAllowsCare} from '../../utils/availabilityCareTypes.js';
import {parseAvailabilitySearch,slotMatchesSearch} from '../agents/availabilitySearch.service.js';
import {withoutQuickProviderSelection,allowsProviderPreference,stripIneligibleProviderPreference} from '../../utils/intakeProviderPreference.js';
const base={id:1,day_of_week:'Monday',start_date:'2026-09-28',end_date:null,start_time:'16:00:00',end_time:'17:00:00',frequency:'WEEKLY',purpose:'ONGOING',available_for_intake:1,available_for_session:0,care_types_json:['COUPLES'],excluded_dates_json:[]};
describe('published availability occurrence changes',()=>{
 it('removes one occurrence without changing the series cadence',()=>{const p=planWeeklyEdit(base,{action:'delete',scope:'single',occurrenceDate:'2026-10-05'});expect(p.endDate).toBe(null);expect(p.excludedDates).toEqual(['2026-10-05']);expect(availabilityOccursOn({...base,excludedDates:p.excludedDates},'2026-10-12')).toBe(true);});
 it.each(['WEEKLY','BIWEEKLY','EVERY_4_WEEKS'])('moves a %s occurrence independently',frequency=>{const p=planWeeklyEdit({...base,frequency},{action:'move',scope:'single',occurrenceDate:'2026-10-26',startDate:'2026-10-28',startTime:'15:30',endTime:'16:30'});expect(p.replacement).toMatchObject({frequency:'ONCE',start_date:'2026-10-28',end_date:'2026-10-28',day_of_week:'Wednesday',care_types_json:['COUPLES']});expect(p.excludedDates).toContain('2026-10-26');});
 it.each([['WEEKLY','2026-11-04'],['BIWEEKLY','2026-11-11'],['EVERY_4_WEEKS','2026-11-25']])('realigns all future %s dates to the new weekday', (frequency,next)=>{const p=planWeeklyEdit({...base,frequency},{action:'move',scope:'future',occurrenceDate:'2026-10-26',startDate:'2026-10-28',startTime:'16:00',endTime:'17:00'});expect(p.endDate).toBe('2026-10-25');expect(p.replacement.frequency).toBe(frequency);expect(availabilityOccursOn(p.replacement,next)).toBe(true);expect(availabilityOccursOn(p.replacement,'2026-10-26')).toBe(false);});
 it('ends future availability without deleting past dates',()=>{expect(planWeeklyEdit(base,{action:'delete',scope:'future',occurrenceDate:'2026-10-05'})).toMatchObject({endDate:'2026-10-04',removeOriginal:false,replacement:null});});
 it('does not treat a skipped or off-cycle date as an occurrence',()=>{for(const row of [{...base,frequency:'EVERY_4_WEEKS'},{...base,excluded_dates_json:['2026-10-05']}])expect(()=>planWeeklyEdit(row,{action:'delete',scope:'single',occurrenceDate:'2026-10-05'})).toThrow('not an occurrence');});
 it('deletes one-time rows directly',()=>expect(planWeeklyEdit({...base,frequency:'ONCE'},{action:'delete',scope:'single',occurrenceDate:'2026-09-28'}).removeOriginal).toBe(true));
 it('rolls back and keeps reservations untouched on invalid move',async()=>{const db={beginTransaction:vi.fn(),execute:vi.fn(async()=>[[base]]),commit:vi.fn(),rollback:vi.fn(),release:vi.fn()};await expect(editAvailabilityPublication({agencyId:2,providerId:9,id:1,kind:'weekly',action:'move',scope:'single',occurrenceDate:'2026-09-28',startDate:'bad'}, {getConnection:async()=>db})).rejects.toThrow();expect(db.rollback).toHaveBeenCalled();expect(db.commit).not.toHaveBeenCalled();expect(db.execute).toHaveBeenCalledTimes(1);});
});
describe('care-specific openings and full enrollment preferences',()=>{
 it('preserves Monday at 4 PM while narrowing a follow-up to couples',()=>{const {filters}=parseAvailabilitySearch({query:'Which of those see couples?',previousQueries:['Who has availability Mondays at 4 PM?'],now:new Date('2026-09-28T15:00:00Z')});expect(filters).toMatchObject({care:'COUPLES',exactTime:'16:00',dateFrom:'2026-09-28'});const slot={startAt:'2026-09-28T22:00:00Z',endAt:'2026-09-28T23:00:00Z',careTypes:['INDIVIDUAL']};expect(slotMatchesSearch(slot,filters,'America/Denver')).toBe(false);expect(slotMatchesSearch({...slot,careTypes:['COUPLES','FAMILY']},filters,'America/Denver')).toBe(true);});
 it('supports all selected care types and restricts a family-only opening',()=>{expect(slotAllowsCare({careTypes:['FAMILY']},'Couples')).toBe(false);expect(slotAllowsCare({careTypes:['FAMILY']},'Families')).toBe(true);expect(slotAllowsCare({careTypes:['INDIVIDUAL','FAMILY','COUPLES']},'Individuals')).toBe(true);});
 it.each(['smart_registration','quick_intake','interest_request'])('strips provider selection from %s',form_type=>{const link={scope_type:'agency',form_type},data={responses:{submission:{preferred_office_provider_ids:['494'],requested_opening_preference:{providerId:494},preferredTime:'afternoon'}}};expect(allowsProviderPreference(link)).toBe(false);stripIneligibleProviderPreference(link,data);expect(data.responses.submission).toEqual({preferredTime:'afternoon'});});
 it('keeps provider preferences for full office enrollment',()=>expect(allowsProviderPreference({scope_type:'agency',form_type:'intake',inherits_office_master:1})).toBe(true));
});

it('ignores direct and nested provider/hold injection in quick signup',()=>{const clean=withoutQuickProviderSelection({whoFor:'couple',providerHoldToken:'secret',preferredProviderUserId:494,preferences:{preferredProviderUserId:494,preferredDays:['Monday']}});expect(clean).toEqual({whoFor:'couple',preferences:{preferredDays:['Monday']}});});
