import {describe,it,expect,vi} from 'vitest';
vi.mock('../../config/database.js',()=>({default:{}}));
vi.mock('../stripePayments.service.js',()=>({default:{},isStripeConfigured:()=>true,getStripePublishableKey:()=>''}));
import {commercialDefaults,normalizeCommercialTerms,requireCompleteTerms,bookingAmounts,usageLines} from '../schoolCareBridgeCommercialPolicy.js';
import {contractDocuments} from '../schoolCareBridgeContractTemplates.js';
import {verifyPayment,invoiceAccess,activateTerms,saveTerms} from '../schoolCareBridgeCommerce.service.js';
import {normalizeProgram,bookingWindow,publicProgram} from '../schoolCareBridgePrograms.service.js';
describe('proposed commercial schedule and calendar billing',()=>{
 it('uses a twelve-month development period starting March 31',()=>{const t=normalizeCommercialTerms({rolloutDate:'2027-03-31',developmentEndDate:'2099-01-01'});expect(t.developmentEndDate).toBe('2028-03-30');expect(t.developmentBps).toBe(5000);expect(t.ongoingBps).toBe(2500);});
 it('prorates March 31, excludes pre-launch use, and does not subtract customer freebies',()=>{const rows=[{usage_date:'2027-03-30',partner_agency_id:2,school_count:500,provider_count:500,admin_count:500},{usage_date:'2027-03-31',partner_agency_id:2,school_count:1,provider_count:1,admin_count:1,customerPaidCents:0}];const lines=usageLines(rows,commercialDefaults,'2027-03');expect(lines.map(l=>l.amountCents)).toEqual([40,16,8]);});
 it('changes percentage exactly on the development anniversary',()=>{const lines=usageLines(['2028-03-30','2028-03-31'].map(date=>({usage_date:date,partner_agency_id:2,school_count:1,provider_count:0,admin_count:0})),commercialDefaults,'2028-03');expect(lines.map(l=>l.percentageBps)).toEqual([5000,2500]);});
 it('rounds monthly unit totals once rather than rounding each day',()=>{const rows=Array.from({length:31},(_,i)=>({usage_date:`2027-05-${String(i+1).padStart(2,'0')}`,partner_agency_id:2,school_count:1,provider_count:1,admin_count:1}));expect(usageLines(rows,commercialDefaults,'2027-05').map(l=>l.amountCents)).toEqual([1250,500,250]);});
 it('keeps travel outside shares and preserves payable fees when school pays zero',()=>{expect(bookingAmounts({serviceCents:50000,travelCents:5000,schoolCents:0,platformBps:1000,operatorBps:2000})).toMatchObject({platformCents:5000,operatorCents:10000,presenterCents:40000,fundingCents:55000});});
 it('rejects negative, fractional, excessive and incomplete amounts',()=>{for(const n of [-1,1.5,null,Infinity])expect(()=>bookingAmounts({serviceCents:n,schoolCents:0,platformBps:1000,operatorBps:2000})).toThrow();expect(()=>normalizeCommercialTerms({bookingPlatformBps:9000,bookingOperatorBps:2000})).toThrow();expect(()=>requireCompleteTerms(commercialDefaults)).toThrow(/Complete the parties/);});
 it('rejects changing or activating an agreement without platform administrator rights',async()=>{await expect(saveTerms({role:'admin'},{})).rejects.toThrow(/Platform administrator/);await expect(activateTerms({role:'admin'},{})).rejects.toThrow(/Platform administrator/);});
});
describe('invoice and receipt integrity',()=>{
 const invoice={id:8,stripe_payment_intent_id:'pi_8',stripe_account_id:'acct_mh4',currency:'usd',total_cents:50000};
 const pi={id:'pi_8',metadata:{source:'schoolcarebridge_invoice',scb_invoice_id:'8'},status:'succeeded',amount:50000,amount_received:50000,currency:'usd'};
 it('accepts only the expected successful payment on the expected merchant',()=>{expect(()=>verifyPayment(invoice,pi,'acct_mh4')).not.toThrow();for(const changed of [{amount_received:49999},{currency:'eur'},{id:'pi_other'},{status:'processing'},{metadata:{source:'other'}}])expect(()=>verifyPayment(invoice,{...pi,...changed},'acct_mh4')).toThrow();expect(()=>verifyPayment(invoice,pi,null)).toThrow();});
 it('does not expose MH4Kidz platform invoices to the school requester',async()=>{const db={execute:vi.fn().mockResolvedValue([[{...invoice,kind:'platform_usage',requester_user_id:22}]])};await expect(invoiceAccess({id:22,role:'school_staff'},8,{},db)).rejects.toThrow(/access/);});
 it('permits the requesting school to retrieve its own school invoice only',async()=>{const db={execute:vi.fn().mockResolvedValue([[{...invoice,kind:'booking',requester_user_id:22}]])};await expect(invoiceAccess({id:22,role:'school_staff'},8,{},db)).resolves.toMatchObject({id:8});await expect(invoiceAccess({id:23,role:'school_staff'},8,{},db)).rejects.toThrow(/access/);});
});
describe('program boundaries and printable documents',()=>{
 const program={title:'Parent workshop',programType:'sponsored',ownerName:'Partner Org',audience:'parents',description:'Parent skills',deliveryMode:'in_person',regions:['Denver'],presenterName:'Presenter',sponsorName:'MH4Kidz',durationMinutes:60,capacity:30,fundingMode:'grant',travelAvailable:true};
 it('keeps sponsor, actual owner and presenter separate',()=>{const p=normalizeProgram(program);expect(publicProgram(p)).toMatchObject({typeLabel:'MH4Kidz Sponsored',ownerName:'Partner Org',presenterName:'Presenter',sponsorName:'MH4Kidz'});expect(()=>normalizeProgram({...program,sponsorName:''})).toThrow(/sponsor/);});
 it('does not allow both class and event registration bindings',()=>expect(()=>normalizeProgram({...program,registrationClassId:1,registrationEventId:2})).toThrow(/class or an event/));
 it('rejects ambiguous wall times, unsupported timezones and past dates',()=>{expect(()=>bookingWindow({start:'2030-01-01T10:00',end:'2030-01-01T11:00',timezone:'America/Denver'})).toThrow(/offset/);expect(()=>bookingWindow({start:'2030-01-01T10:00Z',end:'2030-01-01T11:00Z',timezone:'Bad/Zone'})).toThrow(/timezone/);});
 it('prints three distinct drafts, escapes user text and includes BAA duties',()=>{const docs=contractDocuments({...commercialDefaults,operatorLegalName:'<script>alert(1)</script>'});expect(docs).toHaveLength(3);for(const d of docs){expect(d.html).not.toContain('<script>');expect(d.html).toContain('Signature:');expect(d.html).toContain('Draft for legal');}const baa=docs.find(d=>d.key==='baa').html;for(const required of ['164.410','164.524','164.526','164.528','Subcontractors','Secretary','Return, destruction','72 hours'])expect(baa).toContain(required);expect(docs[0].html).toContain('Free and discounted offers do not waive');});
});
