import {it,expect,vi,beforeEach} from 'vitest';
const m=vi.hoisted(()=>({execute:vi.fn(),beginTransaction:vi.fn(),commit:vi.fn(),rollback:vi.fn(),release:vi.fn(),rate:vi.fn(),context:vi.fn()}));
vi.mock('../../config/database.js',()=>({default:{getConnection:async()=>m,execute:(...args)=>m.execute(...args)}}));
vi.mock('../sickLeaveRate.service.js',()=>({currentEligibleSickRate:m.rate}));
vi.mock('../paySystem.service.js',()=>({loadUserPaySystemContext:m.context}));
import {approveLeaveAtomically} from '../payrollLeaveApproval.service.js';
import {postSupplementalLeave,confirmTrainingHandoff} from '../supplementalLeave.service.js';
import {sharedLeaveBasis,supplementalEarn,validateLeaveItems} from '../../utils/supplementalLeave.js';
let request,account,failPay,posted;
const policy={sharedLeaveAccrualEnabled:true,trainingPtoEnabled:true,schoolSupportEnabled:true,schoolSupportHourlyRate:18,schoolSupportAccrualAfter:'2026-10-02',trainingMaxBalance:20};
beforeEach(()=>{vi.clearAllMocks();failPay=false;posted=false;request={id:1,agency_id:2,user_id:7,status:'submitted',request_type:'school_support',training_description:'CE course',proof_file_path:'private/proof'};account={sick_balance_hours:10,training_balance_hours:10,school_support_balance_hours:10,pto_pay_rate:44,training_adp_through_date:'2026-10-02',training_adp_confirmed_at:new Date()};m.rate.mockResolvedValue(44);m.context.mockResolvedValue({enabled:false});
 m.execute.mockImplementation(async(sql)=>{
  if(sql.startsWith('SELECT * FROM payroll_pto_requests'))return [[request]];
  if(sql.startsWith('SELECT * FROM payroll_pto_accounts'))return [[account]];
  if(sql.startsWith('SELECT * FROM payroll_pto_request_items'))return [[{request_date:'2026-10-09',hours:2}]];
  if(sql.startsWith('SELECT id,status FROM payroll_periods'))return [[{id:10,status:'ran'}]];
  if(sql.startsWith('SELECT * FROM payroll_adjustments'))return [[{sick_pto_hours:1,training_pto_hours:0,pto_rate:40}]];
  if(sql.startsWith('SELECT psa.id'))return [[{id:1}]];
  if(sql.startsWith('SELECT 1 FROM payroll_leave_basis_postings'))return [posted?[{exists:1}]:[]];
  if(sql.startsWith('INSERT INTO payroll_leave_basis_postings'))posted=true;
  if(failPay&&sql.startsWith('UPDATE payroll_adjustments'))throw Error('Payment failed');
  return [{affectedRows:1}];
 });
});
const args={agencyId:2,requestId:1,actorId:9,policy,defaultPayRate:0};
it('pays school leave at support rate with a separate deduction and taxable pay, not sick pay',async()=>{await approveLeaveAtomically(args);expect(m.execute).toHaveBeenCalledWith(expect.stringContaining('other_taxable_amount=COALESCE'),[36,9,10,7]);expect(m.execute).toHaveBeenCalledWith(expect.stringContaining('school_support_balance_hours=school_support_balance_hours-?'),[2,9,2,7]);expect(m.commit).toHaveBeenCalledOnce();});
it('training uses the same current sick-leave rate, with an accurate combined PTO rate',async()=>{request.request_type='training';await approveLeaveAtomically(args);expect(m.rate).toHaveBeenCalledWith(expect.objectContaining({asOfDate:'2026-10-09',userId:7}));const call=m.execute.mock.calls.find(([sql])=>sql.startsWith('UPDATE payroll_adjustments SET training_pto_hours'));expect(call[1][2]).toBeCloseTo(128/3);});
it('rolls back the whole approval if pay application fails',async()=>{failPay=true;await expect(approveLeaveAtomically(args)).rejects.toThrow('Payment failed');expect(m.rollback).toHaveBeenCalledOnce();expect(m.commit).not.toHaveBeenCalled();expect(m.execute.mock.calls.some(([sql])=>sql.startsWith('UPDATE payroll_pto_accounts'))).toBe(false);});
it('locks the request and account; rejects duplicate approval',async()=>{request.status='approved';await expect(approveLeaveAtomically(args)).rejects.toThrow('not pending');expect(m.execute.mock.calls[0][0]).toContain('FOR UPDATE');expect(m.commit).not.toHaveBeenCalled();});
it('rechecks the current locked balance before approval',async()=>{account.school_support_balance_hours=1;await expect(approveLeaveAtomically(args)).rejects.toThrow('Insufficient');expect(m.commit).not.toHaveBeenCalled();});
it('will not approve training without documentation',async()=>{request.request_type='training';request.proof_file_path=null;await expect(approveLeaveAtomically(args)).rejects.toThrow('documentation');});
it('both buckets stop earning at 20 without reducing existing balances',()=>{for(const bucket of ['training','school_support']){expect(supplementalEarn({basisHours:300,bucket,balance:19.9})).toBeCloseTo(.1);expect(supplementalEarn({basisHours:300,bucket,balance:22})).toBe(0);}expect(supplementalEarn({basisHours:30,bucket:'training'})).toBe(.25);expect(supplementalEarn({basisHours:30,bucket:'school_support'})).toBe(2.4);});
it('modern clinical equivalents and actual-hours reconciliation feed both buckets',()=>{const summaryRow={direct_hours:25,breakdown:{__paySystem:{lines:[{compensationPolicyVersion:'itsco-2026-10-service-credit-v3',hourEquivalent:25}],leaveBasis:{direct:25,indirect:5,support:0}}}};expect(sharedLeaveBasis({summaryRow,policy,employmentType:'fee_for_service'})).toBe(30);expect(sharedLeaveBasis({summaryRow:{...summaryRow,actual_worked_hours:33},policy,employmentType:'fee_for_service'})).toBe(33);});
it('all paid sick-eligible time counts, excluding flat reimbursements',()=>{expect(sharedLeaveBasis({summaryRow:{direct_hours:10,indirect_hours:3,breakdown:{otherPaidTimeHours:2}},policy,employmentType:'hourly'})).toBe(15);});
it('rejects impossible dates and invalid hours, including database Date values',()=>{expect(validateLeaveItems([{request_date:new Date('2026-10-09T00:00:00Z'),hours:2}])[0].date).toBe('2026-10-09');expect(()=>validateLeaveItems([{date:'2026-02-30',hours:2}])).toThrow();expect(()=>validateLeaveItems([{date:'2026-10-09',hours:NaN}])).toThrow();});
it('training waits for a confirmed handoff, without losing school accrual',async()=>{account.training_adp_confirmed_at=null;const warnings=await postSupplementalLeave({agencyId:2,userId:7,payrollPeriodId:10,period:{status:'posted',period_start:'2026-10-03',period_end:'2026-10-16'},summaryRow:{direct_hours:25},employmentType:'hourly',policy,actorId:9});expect(warnings[0].bucket).toBe('training');expect(m.execute).toHaveBeenCalledWith(expect.stringContaining('INSERT INTO payroll_leave_basis_postings'),[2,7,10,'school_support',25,2]);});
it('does not accrue a posted source twice',async()=>{posted=true;await postSupplementalLeave({agencyId:2,userId:7,payrollPeriodId:10,period:{status:'posted',period_start:'2026-10-03',period_end:'2026-10-16'},summaryRow:{direct_hours:25},employmentType:'hourly',policy,actorId:9});expect(m.execute.mock.calls.some(([sql])=>sql.startsWith('INSERT'))).toBe(false);});
it('flags an opening balance in the middle of a period instead of double-crediting',async()=>{account.training_adp_through_date='2026-10-08';const warnings=await postSupplementalLeave({agencyId:2,userId:7,payrollPeriodId:10,period:{status:'posted',period_start:'2026-10-03',period_end:'2026-10-16'},summaryRow:{direct_hours:25},employmentType:'hourly',policy,actorId:9});expect(warnings[0].message).toContain('partial period');});

it('never accrues a draft period',async()=>{await expect(postSupplementalLeave({policy,period:{status:'draft'}})).rejects.toThrow('posted payroll');expect(m.commit).not.toHaveBeenCalled();});
