import {mount,flushPromises} from '@vue/test-utils';
import {it,expect,vi,beforeEach} from 'vitest';
import {buildPagesFromSections,PROVIDER_UPDATE_SECTIONS} from '../../../utils/providerUpdate.js';
vi.mock('vue-router',()=>({useRoute:()=>({params:{organizationSlug:'itsco'}})}));
vi.mock('../../../services/api',()=>({default:{get:vi.fn(),put:vi.fn(async()=>({data:{sections:[]}}))}}));
import api from '../../../services/api';
import Panel from '../ProviderUpdateSectionPanel.vue';
const recipient={providerUserId:465,agencyId:2};
const globals={stubs:{WorkHoursEditor:true,WorkplaceHandbookReader:true,ProviderUpdateOfficeSchedule:true,ProviderUpdateAdminUpdateEmbed:true}};
beforeEach(()=>vi.clearAllMocks());
it('gives texting exactly one standalone page and uses Quick View instead of kiosk setup',()=>{const pages=buildPagesFromSections(PROVIDER_UPDATE_SECTIONS.map(s=>({key:s.key,meta:s})));expect(pages.find(p=>p.key==='texting_choices').alone).toBe(true);expect(pages.filter(p=>p.sections.some(s=>s.key==='notification_prefs'))).toHaveLength(1);expect(PROVIDER_UPDATE_SECTIONS.find(s=>s.key==='pin').title).toContain('Six-digit');});
it('shows missing Quick View setup without reading or modifying the logged-in administrator’s PIN',async()=>{const w=mount(Panel,{props:{mode:'token',token:'sample',recipient,section:{key:'pin',data:{quickView:{hasPasscode:false,isLocked:false}}}},global:globals});await flushPromises();expect(w.text()).toContain('six-digit');expect(w.text()).not.toContain('kiosk');expect(w.get('button.primary').element.disabled).toBe(true);expect(w.get('a').attributes('href')).toContain('my=preferences');expect(w.find('input[type=password]').exists()).toBe(true);expect(api.get).not.toHaveBeenCalled();expect(api.put).not.toHaveBeenCalled();w.unmount();});
it('confirms an existing Quick View code through the intended recipient token without collecting the code',async()=>{const w=mount(Panel,{props:{mode:'token',token:'recipient-token',recipient,section:{key:'pin',data:{quickView:{hasPasscode:true,isLocked:false}}}},global:globals});await w.get('button.primary').trigger('click');expect(api.put).toHaveBeenCalledWith('/public/provider-update/recipient-token/sections/pin',expect.objectContaining({data:expect.objectContaining({quickViewConfirmed:true})}));expect(api.put.mock.calls[0][1].data).not.toHaveProperty('pin');w.unmount();});
it('loads typical profile availability instead of a separate work-hours editor',async()=>{const w=mount(Panel,{props:{mode:'token',token:'recipient-token',recipient,section:{key:'work_hours',data:{typicalAvailability:['Monday mornings']}}},global:globals});await flushPromises();expect(w.text()).toContain('Typical in-office availability');expect(w.get('input[aria-label="Monday mornings"]').element.checked).toBe(true);expect(w.find('work-hours-editor-stub').exists()).toBe(false);w.unmount();});
it('blocks preview saves even if a submit event is triggered programmatically',async()=>{const w=mount(Panel,{props:{mode:'token',token:'preview-token',recipient:{...recipient,previewOnly:true},section:{key:'pin',data:{quickView:{hasPasscode:true,isLocked:false}}}},global:globals});await w.get('button.primary').trigger('click');expect(api.put).not.toHaveBeenCalled();expect(w.get('fieldset').element.disabled).toBe(true);w.unmount();});

it('prefills contact, credential, blurb and saved checkbox selections',async()=>{
 for(const [key,data,selector,value] of [['contact_info',{contact:{phone:'7195550100',street:'Saved address'}},'input[autocomplete=tel]','7195550100'],['profile_blurb',{blurb:'My existing introduction'},'textarea','My existing introduction'],['credential_display',{credential:'LPCC'},'input','LPCC']]){const w=mount(Panel,{props:{recipient,section:{key,data}},global:globals});await flushPromises();expect(w.get(selector).element.value).toBe(value);w.unmount();}
 const w=mount(Panel,{props:{recipient,section:{key:'specialties',data:{specialtyGroups:[{key:'groups',label:'Populations',options:['Families','Adults']}],specialties:{groups:['Families']}}}},global:globals});await flushPromises();expect(w.findAll('input').map(x=>x.element.checked)).toEqual([true,false]);w.unmount();
});
it('shows an unsigned amendment as required rather than allowing a completion checkbox',()=>{const w=mount(Panel,{props:{recipient,section:{key:'amendments',data:{}}},global:globals});expect(w.get('button.primary').element.disabled).toBe(true);w.unmount();});
