import {beforeEach,it,expect,vi} from 'vitest';
import {mount,flushPromises} from '@vue/test-utils';
import ProviderUpdateOfficeSchedule from '../ProviderUpdateOfficeSchedule.vue';
import api from '../../../services/api';
import {createProviderProfileQr} from '../../../utils/providerProfileQr';
vi.mock('../../../services/api',()=>({default:{get:vi.fn(),post:vi.fn()}}));
vi.mock('../../../utils/providerProfileQr',()=>({createProviderProfileQr:vi.fn(async()=> 'data:image/png;base64,qr')}));
const calendar={weekStart:'2026-10-12',weekEnd:'2026-10-19',today:'2026-10-07',timeZone:'America/Denver',canEdit:true,agency:{slug:'itsco',portal_url:null,name:'ITSCO'},provider:{id:465,first_name:'Test',last_name:'Provider'},preferences:{acceptingNewClients:true,inPerson:true,virtual:true},assignments:[{id:10,when:'Monday 9 AM',inPerson:false,virtual:false}],officeReservations:[{id:20,assignmentId:10,startAt:'2026-10-12T15:00:00Z',endAt:'2026-10-12T16:00:00Z',roomAvailable:true,buildingName:'Office'}],busyBlocks:[],weekly:[],inPersonSlots:[],virtualSlots:[]};
const button=(w,label)=>w.findAll('button').find(b=>b.text()===label);
const render=props=>mount(ProviderUpdateOfficeSchedule,{props:{agencyId:2,mode:'token',token:'private-invitation',...props},global:{stubs:{ProviderContactHours:true}}});
beforeEach(()=>{vi.clearAllMocks();api.get.mockResolvedValue({data:structuredClone(calendar)});api.post.mockResolvedValue({data:{ok:true}});});
it('keeps the profile link in its dedicated read-only review step without sending or publishing',async()=>{const w=render({readonly:true,view:'profile'});await flushPromises();const link=w.get('a.primary').attributes('href');expect(link).toBe('https://www.itsco.health/providers/test-provider-465');expect(link).not.toContain('private-invitation');expect(button(w,'Confirm public profile review').attributes('disabled')).toBeDefined();await button(w,'Create profile QR code').trigger('click');await flushPromises();await vi.waitFor(()=>expect(w.find('a[download="provider-465-profile.png"]').exists()).toBe(true));expect(createProviderProfileQr).toHaveBeenCalledWith(link,calendar.agency);expect(api.post).not.toHaveBeenCalled();w.unmount();});
it('lets a read-only preview browse weeks without sharing links in the calendar step',async()=>{const w=render({readonly:true});await flushPromises();expect(w.text()).toContain('Mon, Oct 12');expect(w.text()).toContain('Kept private');expect(w.find('.profile-share').exists()).toBe(false);await w.get('[aria-label="Next week"]').trigger('click');await flushPromises();expect(api.get).toHaveBeenLastCalledWith('/public/provider-update/private-invitation/availability-calendar',expect.objectContaining({params:{agencyId:2,weekStart:'2026-10-19'}}));expect(button(w,'Publish virtual opening')).toBeUndefined();expect(api.post).not.toHaveBeenCalled();w.unmount();});
it('publishes both modalities for a reserved office assignment without cancellation or meeting actions',async()=>{const w=render();await flushPromises();await w.get('.calendar-event').trigger('click');await flushPromises();await w.get('.edit-panel select').setValue('both');await button(w,'Save this availability').trigger('click');await flushPromises();expect(api.post).toHaveBeenCalledWith('/public/provider-update/private-invitation/availability-calendar/office',{agencyId:2,eventId:20,frequency:'WEEKLY',inPerson:true,virtual:true},{timeout:60000});expect(w.text()).not.toContain('Cancel all office');expect(w.find('a[href*="my-schedule"]').exists()).toBe(false);w.unmount();});
it('adds a one-hour virtual opening and refreshes the week without sending messages',async()=>{const w=render();await flushPromises();await w.get('.day-add').trigger('click');await flushPromises();await button(w,'Open virtual appointments').trigger('click');await flushPromises();await button(w,'Publish virtual opening').trigger('click');await flushPromises();expect(api.post).toHaveBeenCalledWith('/public/provider-update/private-invitation/availability-calendar/virtual',{agencyId:2,date:'2026-10-12',startTime:'09:00',frequency:'WEEKLY',enableVirtualOpen:true},{timeout:60000});expect(api.post).toHaveBeenCalledTimes(1);expect(api.get).toHaveBeenCalledTimes(2);w.unmount();});
it('never silently converts booked time into an opening',async()=>{api.get.mockResolvedValue({data:{...calendar,officeReservations:[{...calendar.officeReservations[0],hasAppointment:true}]}});const w=render();await flushPromises();await w.get('.calendar-event').trigger('click');expect(w.text()).toContain('This time is blocked');expect(button(w,'Save this availability')).toBeUndefined();expect(api.post).not.toHaveBeenCalled();w.unmount();});

it.each(['waitlist','unavailable'])('requires an explicit new-opening choice before opening a %s virtual profile',async status=>{
 api.get.mockResolvedValue({data:{...calendar,preferences:{...calendar.preferences,intakeStatusByFormat:{IN_PERSON:'accepting',VIRTUAL:status}}}});const w=render();await flushPromises();expect(w.find('.day-add').exists()).toBe(true);expect(button(w,'Publish virtual opening')).toBeUndefined();await w.get('.calendar-event').trigger('click');expect(w.find('option[value="virtual"]').exists()).toBe(false);expect(w.find('option[value="ONCE"]').exists()).toBe(false);w.unmount();
});
it('auto-saves separate format statuses and keeps Closed listed',async()=>{const w=render({view:'settings'});await flushPromises();expect(w.find('.profile-share').exists()).toBe(false);await w.findAll('select')[0].setValue('waitlist');await flushPromises();expect(api.post).toHaveBeenCalledWith(expect.stringContaining('/settings'),{agencyId:2,inPersonStatus:'waitlist',virtualStatus:'accepting'},{timeout:60000});expect(w.text()).toContain('Your profile stays listed');w.unmount();});
it('scrolls to the virtual editor and selects the clicked calendar hour',async()=>{const scroll=vi.fn();Element.prototype.scrollIntoView=scroll;const w=render();await flushPromises();await w.get('.day-column .day-body').trigger('click',{clientY:304});await flushPromises();await button(w,'Open virtual appointments').trigger('click');await flushPromises();expect(w.get('input[type="time"]').element.value).toBe('11:00');expect(scroll).toHaveBeenCalledWith({behavior:'smooth',block:'start'});expect(w.find('option[value="ONCE"]').exists()).toBe(false);w.unmount();});
it('refreshes removed reservations when returning to the updater and never recreates them',async()=>{const w=render();await flushPromises();expect(w.findAll('.calendar-event')).toHaveLength(1);api.get.mockResolvedValue({data:{...calendar,officeReservations:[]}});window.dispatchEvent(new Event('focus'));await flushPromises();expect(w.findAll('.calendar-event')).toHaveLength(0);expect(api.post).not.toHaveBeenCalled();w.unmount();});
it('shares an NLU public-site profile instead of the current app or invitation origin',async()=>{api.get.mockResolvedValue({data:{...calendar,agency:{name:'Next Level Up',slug:'nlu'},profileServices:['counseling']}});const w=render({view:'profile',readonly:true});await flushPromises();expect(w.get('a.primary').attributes('href')).toBe('https://nextleveluplcc.com/nlu/provider/465?serviceType=counseling');w.unmount();});

it('lets a preview explore an empty hour but cannot publish or request a room',async()=>{const w=render({readonly:true});await flushPromises();await w.get('.day-column .day-body').trigger('click',{clientY:304});await flushPromises();await button(w,'Open virtual appointments').trigger('click');await flushPromises();expect(w.get('input[type="time"]').element.value).toBe('11:00');await w.get('input[type="time"]').setValue('12:00');expect(button(w,'Publish virtual opening').element.disabled).toBe(true);await button(w,'Publish virtual opening').trigger('click');expect(api.post).not.toHaveBeenCalled();w.unmount();});
it('lets an existing office holder request a room without permission to publish client openings',async()=>{
 api.get.mockResolvedValue({data:{...calendar,canEdit:false,canRequestRooms:true}});const w=render();await flushPromises();
 await w.get('.day-add').trigger('click');await flushPromises();expect(button(w,'Open virtual appointments')).toBeUndefined();
 await button(w,'Request a recurring room').trigger('click');await flushPromises();expect(button(w,'Find available rooms').element.disabled).toBe(false);expect(button(w,'Publish virtual opening')).toBeUndefined();w.unmount();
});

it('opens the next occurrence when a past weekday is clicked instead of silently ignoring it',async()=>{api.get.mockResolvedValue({data:{...calendar,today:'2026-10-16'}});const w=render();await flushPromises();await w.get('.day-column .day-body').trigger('click',{clientY:304});await flushPromises();expect(w.text()).toContain('Your recurring request will start on 2026-10-19');await button(w,'Request a recurring room').trigger('click');await flushPromises();expect(w.findAll('input[type=date]').some(i=>i.element.value==='2026-10-19')).toBe(true);expect(api.post).not.toHaveBeenCalled();w.unmount();});
