import {mount,flushPromises} from '@vue/test-utils';
import {it,expect,vi,beforeEach} from 'vitest';
import {buildPagesFromSections,PROVIDER_UPDATE_SECTIONS} from '../../../utils/providerUpdate.js';
vi.mock('vue-router',()=>({useRoute:()=>({params:{organizationSlug:'itsco'}})}));
vi.mock('../../../services/api',()=>({default:{post:vi.fn(async()=>({data:{passcode:'123456'}})),get:vi.fn(),put:vi.fn(async()=>({data:{sections:[]}}))}}));
import api from '../../../services/api';
import Panel from '../ProviderUpdateSectionPanel.vue';
const recipient={providerUserId:465,agencyId:2};
const globals={stubs:{WorkHoursEditor:true,WorkplaceHandbookReader:true,ProviderUpdateOfficeSchedule:true,ProviderUpdateAdminUpdateEmbed:true}};
beforeEach(()=>vi.clearAllMocks());
it('gives texting exactly one standalone page and uses Quick View instead of kiosk setup',()=>{const pages=buildPagesFromSections(PROVIDER_UPDATE_SECTIONS.map(s=>({key:s.key,meta:s})));expect(pages.find(p=>p.key==='texting_choices').alone).toBe(true);expect(pages.filter(p=>p.sections.some(s=>s.key==='notification_prefs'))).toHaveLength(1);expect(PROVIDER_UPDATE_SECTIONS.find(s=>s.key==='pin').title).toContain('Six-digit');});
it('creates the invited recipient’s missing Quick View code without collecting a password',async()=>{const w=mount(Panel,{props:{mode:'token',token:'sample',recipient,section:{key:'pin',data:{quickView:{hasPasscode:false}}}},global:globals});await flushPromises();expect(w.find('input[type=password]').exists()).toBe(false);await w.get('button.primary').trigger('click');await flushPromises();expect(api.post).toHaveBeenCalledWith('/public/provider-update/sample/quick-view-setup',expect.any(Object));expect(w.text()).toContain('123456');expect(api.put).not.toHaveBeenCalled();await w.get('button.primary').trigger('click');expect(w.emitted('saved')).toBeTruthy();w.unmount();});
it('loads typical profile availability instead of a separate work-hours editor',async()=>{const w=mount(Panel,{props:{mode:'token',token:'recipient-token',recipient,section:{key:'work_hours',data:{typicalAvailability:['Monday mornings']}}},global:globals});await flushPromises();expect(w.text()).toContain('Typical in-office availability');expect(w.get('input[aria-label="Monday mornings"]').element.checked).toBe(true);expect(w.find('work-hours-editor-stub').exists()).toBe(false);w.unmount();});
it('blocks preview saves even if a submit event is triggered programmatically',async()=>{const w=mount(Panel,{props:{mode:'token',token:'preview-token',recipient:{...recipient,previewOnly:true},section:{key:'pin',data:{quickView:{hasPasscode:true,isLocked:false}}}},global:globals});await w.get('button.primary').trigger('click');expect(api.put).not.toHaveBeenCalled();expect(api.post).not.toHaveBeenCalled();expect(w.get('fieldset').element.disabled).toBe(true);w.unmount();});

it('prefills contact, credential, blurb and saved checkbox selections',async()=>{
 for(const [key,data,selector,value] of [['contact_info',{contact:{phone:'7195550100',street:'Saved address'}},'input[autocomplete=tel]','7195550100'],['profile_blurb',{blurb:'My existing introduction'},'textarea','My existing introduction'],['credential_display',{credential:'LPCC'},'input','LPCC']]){const w=mount(Panel,{props:{recipient,section:{key,data}},global:globals});await flushPromises();expect(w.get(selector).element.value).toBe(value);w.unmount();}
 const w=mount(Panel,{props:{recipient,section:{key:'specialties',data:{focusGroups:[{key:'populations',label:'Populations',options:['Families','Veterans']}],clinicalFocus:{top:{populations:['Families']},excluded:{populations:['Veterans']}}}}},global:globals});await flushPromises();expect(w.findAll('input').map(x=>x.element.checked)).toEqual([true,true,false,false]);w.unmount();
});
it('shows an unsigned amendment as required rather than allowing a completion checkbox',()=>{const w=mount(Panel,{props:{recipient,section:{key:'amendments',data:{}}},global:globals});expect(w.get('button.primary').element.disabled).toBe(true);w.unmount();});

it('opens the stored license using a direct link even in a read-only preview',async()=>{const w=mount(Panel,{props:{mode:'token',token:'preview-token',agencyId:2,recipient:{...recipient,previewOnly:true},section:{key:'license',data:{license:{hasUpload:true,number:'TEST'}}}},global:globals});await flushPromises();const a=w.get('a');expect(a.attributes('href')).toBe('/api/public/provider-update/preview-token/assets/license?open=1&agencyId=2');expect(a.attributes('target')).toBe('_blank');expect(w.get('fieldset').element.disabled).toBe(true);w.unmount();});
