import {it,expect,vi,beforeEach} from 'vitest';
vi.mock('../providerUpdateReview.controller.js',()=>({reviewRecipient:vi.fn(),requireSection:vi.fn()}));
vi.mock('../../services/providerUpdateTraining.service.js',()=>({resolveSectionTraining:vi.fn()}));
import {reviewRecipient,requireSection} from '../providerUpdateReview.controller.js';
import {resolveSectionTraining} from '../../services/providerUpdateTraining.service.js';
import {sectionTraining} from '../providerUpdateTraining.controller.js';
beforeEach(()=>{vi.resetAllMocks();reviewRecipient.mockResolvedValue({agency_id:2,section_config_json:{pin:true}});resolveSectionTraining.mockResolvedValue([{id:'g',html:'<img>'}]);});
it('uses the scoped recipient agency, not a caller-supplied agency, and disables caching',async()=>{const req={params:{token:'preview',sectionKey:'pin'},query:{agencyId:99}},res={set:vi.fn(),json:vi.fn()},next=vi.fn();await sectionTraining(req,res,next);expect(requireSection).toHaveBeenCalledWith({agency_id:2,section_config_json:{pin:true}},'pin');expect(resolveSectionTraining).toHaveBeenCalledWith({pin:true},'pin',2);expect(res.set).toHaveBeenCalledWith('Cache-Control','no-store');expect(next).not.toHaveBeenCalled();});
it('does not resolve private files for a disabled or out-of-audience section',async()=>{const error=Object.assign(new Error('Not enabled'),{status:403});requireSection.mockImplementation(()=>{throw error});const next=vi.fn();await sectionTraining({params:{sectionKey:'license'}},{},next);expect(next).toHaveBeenCalledWith(error);expect(resolveSectionTraining).not.toHaveBeenCalled();});
it('does not resolve files when the token/session is expired',async()=>{reviewRecipient.mockRejectedValue(new Error('Expired'));const next=vi.fn();await sectionTraining({params:{sectionKey:'pin'}},{},next);expect(next).toHaveBeenCalled();expect(resolveSectionTraining).not.toHaveBeenCalled();});

const db=vi.hoisted(()=>({execute:vi.fn()}));
vi.mock('../../config/database.js',()=>({default:db}));
vi.mock('../../services/providerUpdate.service.js',()=>({recipientSeesSection:(_key,audience,id)=>!audience.only||audience.only.includes(id)}));
import {savedInstructions} from '../providerUpdateTraining.controller.js';
it('allows assigned instructions after completion without using expired or locked update tokens',async()=>{db.execute.mockResolvedValue([[{provider_user_id:22,agency_id:2,title:'October',section_config_json:{pin:true},section_audience_json:{}}]]);const res={set:vi.fn(),json:vi.fn()},next=vi.fn();await savedInstructions({params:{pushId:2,sectionKey:'pin'},user:{id:22}},res,next);expect(next).not.toHaveBeenCalled();expect(resolveSectionTraining).toHaveBeenCalledWith({pin:true},'pin',2);const [sql,args]=db.execute.mock.calls.at(-1);expect(args).toEqual([2,22,'pin']);expect(sql).toContain('user_agencies');expect(sql).not.toContain('locked_at IS NULL');expect(res.json.mock.calls[0][0].agencyId).toBe(2);});
it('denies instructions to someone without that assigned update',async()=>{db.execute.mockResolvedValue([[]]);const next=vi.fn();await savedInstructions({params:{pushId:2,sectionKey:'pin'},user:{id:99}},{},next);expect(next.mock.calls[0][0].status).toBe(403);expect(resolveSectionTraining).not.toHaveBeenCalled();});
it('denies disabled or removed-audience sections even for an existing recipient',async()=>{db.execute.mockResolvedValue([[{provider_user_id:22,agency_id:2,section_config_json:{pin:true},section_audience_json:{only:[33]}}]]);const next=vi.fn();await savedInstructions({params:{pushId:2,sectionKey:'pin'},user:{id:22}},{},next);expect(next.mock.calls[0][0].status).toBe(403);expect(resolveSectionTraining).not.toHaveBeenCalled();});
