<template>
<div class="finance-shell" :style="brandStyle">
  <header class="finance-top"><div class="finance-brand"><img v-if="organization?.logo_url" class="finance-brand-mark" :src="organization.logo_url" :alt="organization.name" /><span v-else class="finance-brand-mark">{{ initials(organization?.name||'Finance Operations') }}</span><div><strong>{{ organization?.name || 'Finance Operations' }}</strong><small>{{ organization?.manager_name ? `Managed by ${organization.manager_name}` : 'Funding, spending, and oversight' }}</small></div></div><nav aria-label="Workspace navigation"><router-link :to="orgPath('/dashboard')">My Dashboard</router-link><router-link v-if="['admin','super_admin'].includes(auth.user?.role)" :to="orgPath('/admin-dashboard')">Admin</router-link><router-link :to="orgPath('/finance-operations')" @click="section='hub'">Finance Operations</router-link></nav></header>
  <div v-if="organization?.is_demo" class="finance-demo">DEMO · Fictional nonprofit, grants, people, bank activity, and payments. No real money moves.</div>
  <div class="finance-scope"><label>Organization scope<select v-model="selectedId" aria-label="Organization scope"><option value="all">Portfolio · All authorized organizations</option><option v-for="o in organizations" :key="o.agency_id" :value="String(o.agency_id)">{{ o.name }}</option></select></label><span v-if="organization">{{ organization.mode==='sponsored'?'Managed organization':'Self-managed organization' }} · {{ portal?'Program portal':'Finance administration' }}</span><label v-if="data?.role==='manager'" class="check"><input v-model="previewPortal" type="checkbox" /> Preview sponsored organization view</label><button :disabled="loading" @click="refresh">{{ loading?'Refreshing…':'Refresh' }}</button></div>
  <div v-if="auth.user?.role==='super_admin'" class="finance-actions finance-admin-actions"><button @click="setupOpen=true">Enable organization</button><span v-if="selectedId==='all'">Live portfolio totals exclude demo organizations.</span></div>
  <p v-if="error" class="finance-error" role="alert">{{ error }}</p><p v-if="notice" class="finance-callout" role="status">{{ notice }}</p>
  <div v-if="!organizations.length&&!loading" class="finance-panel finance-empty"><h1>Finance Operations</h1><p>No enabled organizations are available with your finance permissions.</p><button v-if="auth.user?.role==='super_admin'" @click="createDemo">Create Rocky Mountain Mentors demo</button></div>
  <main v-else-if="section==='hub'" class="finance-hub"><header><h1>Finance Operations</h1><p>Budgets, grants, expenses, payments, and fiscal oversight—organized in one place.</p></header><div class="finance-orbit"><div class="finance-orbit-ring"/><div class="finance-orbit-center"><span>▥</span><h2>Finance<br/>Operations</h2><p>Funding, spending,<br/>and oversight—connected.</p><small>{{ hubAreas.length }} areas</small></div><button v-for="(area,i) in hubAreas" :key="area.section" class="finance-orbit-node" :class="`orbit-${i}`" :style="{'--node-color':area.color}" @click="go(area.section)"><span class="finance-node-icon">{{ area.icon }}</span><strong>{{ area.title }}</strong><small>{{ area.description }}</small><span class="finance-node-link">Explore →</span></button></div><p class="finance-hub-hint">Select an area to review its records and next actions.</p></main>
  <div v-else class="finance-layout"><aside class="finance-nav"><button v-for="item in navigation" :key="item.key" :class="{active:section===item.key}" :aria-current="section===item.key?'page':undefined" @click="go(item.key)"><span>{{ item.icon }}</span>{{ item.label }}</button><div class="finance-nav-footer"><strong>{{ portal?'Your programs. Clear finances.':'One financial workspace.' }}</strong><p>{{ portal?'Submit requests, follow approvals, and see what is available.':'Manage funding and spending while QuickBooks remains your accounting system.' }}</p><button @click="section='hub'">Operations hub ↗</button></div></aside>
  <main class="finance-main">
    <header class="finance-page-header"><div><span class="finance-eyebrow">{{ portal?'PROGRAM FINANCES':selectedId==='all'?'MANAGEMENT PORTFOLIO':'FINANCE OPERATIONS' }}</span><h1>{{ pageTitle }}</h1><p>{{ pageDescription }}</p></div><div class="finance-actions"><button v-if="canCreate" class="primary" @click="formKind=section==='support'?'requests':section">＋ {{ section==='expenses'?'Expense request':`Add ${singular[section]||'record'}` }}</button><button v-if="section==='documents'&&data?.role!=='viewer'" class="primary" @click="uploadExpenseId=0">＋ Upload document</button><button v-if="section==='reports'&&data" @click="exportExpenses">Export expenses CSV</button></div></header>
    <template v-if="selectedId==='all'">
      <section class="finance-metrics"><article v-for="m in portfolioMetrics" :key="m.label"><small>{{ m.label }}</small><strong>{{ m.value }}</strong></article></section>
      <section class="finance-panel"><header><div><h2>Organization overview</h2><p>Choose an organization to work with its funds, programs, requests, and reports.</p></div><input v-model="search" placeholder="Search organizations…" aria-label="Search organizations" /></header><div class="finance-table-wrap"><table><thead><tr><th>Organization</th><th>Experience</th><th>Approved budget</th><th>Committed</th><th>Paid</th><th>Pending requests</th><th/></tr></thead><tbody><tr v-for="o in organizations.filter(o=>matchesSearch(o.name))" :key="o.agency_id"><td><strong>{{ o.name }}</strong><small v-if="o.is_demo">Fictional demo</small></td><td>{{ label(o.mode) }}</td><td>{{ money(o.summary?.budget) }}</td><td>{{ money(o.summary?.committed) }}</td><td>{{ money(o.summary?.paid) }}</td><td>{{ money(o.summary?.pending) }}</td><td><button @click="selectedId=String(o.agency_id);section='overview'">Open organization →</button></td></tr></tbody></table></div></section>
      <button v-if="auth.user?.role==='super_admin'" :disabled="loading" @click="createDemo">Open / create Rocky Mountain Mentors demo</button>
    </template>
    <template v-else-if="data">
      <section v-if="['overview','budgets','allocations','funds','grants','expenses','approvals','payments','reports'].includes(section)" class="finance-metrics"><article v-for="m in metrics" :key="m.label"><small>{{ m.label }}</small><strong :class="{negative:m.amount<0}">{{ money(m.amount) }}</strong><span>{{ m.hint }}</span></article></section>
      <template v-if="['overview','reports','budgets'].includes(section)"><div class="finance-two-col"><section class="finance-panel"><header><h2>Program budget vs. spending</h2><span class="finance-legend">● Paid <span>● Committed</span></span></header><div v-for="p in programSummary" :key="p.id" class="finance-program-bar"><div><strong>{{ p.name }}</strong><small>{{ money(p.paid) }} paid · {{ money(p.committed) }} committed / {{ money(p.budget) }}</small></div><div class="finance-progress"><i :style="{width:percent(p.paid,p.budget)+'%'}"/><i class="committed" :style="{width:percent(p.committed,p.budget)+'%'}"/></div><small>{{ money(p.budget-p.paid-p.committed) }} available</small></div><p v-if="!programSummary.length" class="finance-empty">Create programs and budgets to see spending here.</p></section><section class="finance-panel"><h2>{{ portal?'Your next steps':'Needs attention' }}</h2><button class="finance-next" @click="go('expenses')"><span>Expense requests awaiting review</span><b>{{ pendingExpenses.length }}</b></button><button class="finance-next" @click="go('reports')"><span>Open reporting requirements</span><b>{{ reporting.length }}</b></button><button class="finance-next" @click="go('payments')"><span>Approved / scheduled payments</span><b>{{ payableExpenses.length }}</b></button><p class="finance-callout">Available to spend subtracts both paid expenses and outstanding approved commitments. Awarded funding and received cash are tracked separately.</p><button v-if="data.role!=='viewer'" class="primary" @click="formKind='expenses'">Submit an expense request</button></section></div></template>
      <section v-if="section==='overview'" class="finance-panel"><header><h2>Recent activity</h2><button @click="go('expenses')">View requests →</button></header><div v-for="e in data.expenses.slice(0,6)" :key="e.id" class="finance-activity"><span class="finance-activity-icon">▤</span><div><button class="link" @click="selectedExpense=e">{{ e.title }}</button><small>{{ programName(e.program_id) }} · {{ day(e.expense_date) }}</small></div><strong>{{ money(e.amount_cents) }}</strong><span class="finance-badge" :class="e.status">{{ label(e.status) }}</span></div><p v-if="!data.expenses.length" class="finance-empty">No expense activity yet.</p></section>
      <section v-if="['funds','grants','budgets','allocations','programs','events','partners'].includes(section)" class="finance-panel"><header><h2>{{ pageTitle }}</h2><div class="finance-actions"><input v-model="search" :placeholder="`Search ${section}…`" :aria-label="`Search ${section}`"/><button v-if="section==='funds'&&!portal" @click="formKind='receipts'">Record funds received</button></div></header><div class="finance-table-wrap"><table><thead><tr><th v-for="c in columns" :key="c.key">{{ c.label }}</th><th>Details</th></tr></thead><tbody><tr v-for="row in collection" :key="row.id" @click="selectedRecord={kind:section,row}"><td v-for="c in columns" :key="c.key">{{ display(row,c) }}</td><td><button @click.stop="selectedRecord={kind:section,row}">View →</button></td></tr></tbody></table></div><p v-if="!collection.length" class="finance-empty">No {{ section }} match this view.</p></section>
      <section v-if="['expenses','approvals','payments'].includes(section)" class="finance-panel"><header><h2>{{ section==='payments'?'Payments & reimbursements':'Expense requests' }}</h2><input v-model="search" placeholder="Search expenses…" aria-label="Search expenses" /></header><div class="finance-actions finance-filters"><select v-model="statusFilter" aria-label="Expense status"><option value="">All statuses</option><option v-for="s in statuses" :key="s" :value="s">{{ label(s) }}</option></select><select v-model="programFilter" aria-label="Filter program"><option value="">All programs</option><option v-for="p in data.programs" :key="p.id" :value="String(p.id)">{{ p.name }}</option></select></div><p v-if="section==='payments'" class="finance-callout">Approval reserves budget. Paid means an authorized manager recorded a completed external payment. This workspace does not initiate bank transfers.</p><div class="finance-table-wrap"><table><thead><tr><th>Date</th><th>Description</th><th>Program</th><th>Kind</th><th>Amount</th><th>Status</th><th>Evidence</th><th/></tr></thead><tbody><tr v-for="e in expenseRows" :key="e.id"><td>{{ day(e.expense_date) }}</td><td><button class="link" @click="selectedExpense=e">{{ e.title }}</button></td><td>{{ programName(e.program_id) }}</td><td>{{ label(e.kind) }}</td><td>{{ money(e.amount_cents) }}</td><td><span class="finance-badge" :class="e.status">{{ label(e.status) }}</span></td><td>{{ data.documents.filter(d=>d.expense_id===e.id).length }} files</td><td><button @click="selectedExpense=e">Review →</button></td></tr></tbody></table></div><p v-if="!expenseRows.length" class="finance-empty">No requests match this view.</p></section>
      <template v-if="section==='reports'"><section class="finance-panel"><header><h2>Grant & program reporting</h2><button v-if="data.role!=='viewer'" @click="formKind='requests'">Add reporting requirement</button></header><div class="finance-table-wrap"><table><thead><tr><th>Report / request</th><th>Due</th><th>Status</th><th>Documents</th><th/></tr></thead><tbody><tr v-for="r in data.requests.filter(r=>r.kind==='report')" :key="r.id"><td>{{ r.title }}</td><td>{{ day(r.due_date) }}</td><td>{{ label(r.status) }}</td><td>{{ visibleDocuments.filter(d=>d.request_id===r.id).length }}</td><td><button @click="selectedRequest=r">Open →</button></td></tr></tbody></table></div></section><section class="finance-panel"><h2>Operational reports</h2><p>Program budget comparisons, spending by status, and expense exports use the same approved records shown throughout this workspace. Use QuickBooks for the organization’s accounting statements and final accounting reconciliation.</p><div class="finance-actions"><button @click="exportExpenses()">Download expenses</button><button @click="exportExpenses('program-budgets')">Download program budgets</button><button v-if="!portal" @click="exportExpenses('grant-utilization')">Download grant utilization</button></div><p>Reports include all recorded periods. Grant awards are not cash receipts; these are operational reports, not accounting statements.</p></section></template>
      <section v-if="section==='documents'" class="finance-panel"><header><h2>Financial documents</h2><input v-model="search" placeholder="Search documents…" aria-label="Search documents" /></header><div class="finance-table-wrap"><table><thead><tr><th>Document</th><th>Type</th><th>Related record</th><th>Visibility</th><th/></tr></thead><tbody><tr v-for="d in visibleDocuments.filter(d=>matchesSearch(d.name))" :key="d.id"><td>{{ d.name }}<small>{{ Math.ceil(d.size_bytes/1024) }} KB · {{ day(d.created_at) }}</small></td><td>{{ label(d.kind) }}</td><td>{{ d.expense_id?`Expense #${d.expense_id}`:d.grant_id?`Grant #${d.grant_id}`:d.request_id?`Request #${d.request_id}`:'Organization' }}</td><td>{{ d.visibility==='internal'?'Finance team only':'Organization' }}</td><td><button @click="downloadDocument(d)">Download</button></td></tr></tbody></table></div><p v-if="!visibleDocuments.length" class="finance-empty">Upload receipts, grant agreements, reports, and supporting documents.</p></section>
      <section v-if="section==='support'" class="finance-panel"><h2>Requests to the finance team</h2><div v-for="r in data.requests.filter(r=>r.kind!=='report')" :key="r.id" class="finance-activity"><div><button class="link" @click="selectedRequest=r">{{ r.title }}</button><small>{{ label(r.kind) }}</small></div><span class="finance-badge">{{ label(r.status) }}</span></div><p v-if="!data.requests.length" class="finance-empty">Submit a budget-change or support request to begin.</p></section>
      <FinanceBankPanel v-if="section==='bank'&&!portal" :key="`bank-${selectedId}`" :agency-id="Number(selectedId)" :agency-name="organization.name" :is-demo="!!organization.is_demo" :expenses="data.expenses" />
      <section v-if="section==='settings'&&!portal" class="finance-panel"><h2>Organization finance settings</h2><form @submit.prevent="saveSettings"><label>Fiscal year starts<select v-model.number="settingsDraft.fiscalStartMonth"><option v-for="(month,i) in months" :key="month" :value="i+1">{{ month }}</option></select></label><label class="check"><input v-model="settingsDraft.bankEnabled" type="checkbox" :disabled="!!organization.is_demo" /> Allow broader bank imports for this organization’s Finance Operations</label><label v-if="settingsDraft.bankEnabled" class="check"><input v-model="settingsDraft.bankConsentConfirmed" type="checkbox" required /> The organization authorizes transaction review for budgets, expenses, and reconciliation.</label><p>Pausing imports does not revoke Stripe’s connection. Use Bank & Reconciliation → Disconnect to revoke access. Owner authorization is still required when linking each account.</p><button class="primary" :disabled="loading">Save settings</button></form><h3>Finance access</h3><p>Finance permissions are separate from medical billing and clinical supervision. Sponsored organizations receive a simplified portal unless explicitly granted finance-manager access.</p><form class="finance-actions" @submit.prevent="saveAccess"><label>Organization member<select v-model.number="accessDraft.userId" required><option value="">Select a member</option><option v-for="member in data.staff||[]" :key="member.id" :value="member.id">{{ member.name }}</option></select></label><label>Finance role<select v-model="accessDraft.role"><option value="viewer">Viewer</option><option value="requester">Requester</option><option value="manager">Finance manager</option><option value="none">Remove delegated access</option></select></label><button :disabled="loading">Save access</button></form><p>Organization admins retain their base access; this control manages delegated finance roles.</p></section>
    </template><p v-else-if="loading" class="finance-empty" role="status">Loading this organization’s financial workspace…</p>
  </main></div>
  <FinanceSetupForm v-if="setupOpen" :managers="organizations" @close="setupOpen=false" @saved="setupOpen=false;refresh()" />
  <FinanceRecordForm v-if="formKind&&data" :key="`${selectedId}-${formKind}`" :agency-id="Number(selectedId)" :kind="formKind" :data="data" @close="formKind=''" @saved="changed" />
  <FinanceExpenseDrawer v-if="selectedExpense&&data" :key="`${selectedId}-${selectedExpense.id}-${selectedExpense.revision}`" :agency-id="Number(selectedId)" :expense="selectedExpense" :data="data" :role="portal&&data.role==='manager'?'requester':data.role" :user-id="auth.user?.id" @close="selectedExpense=null" @saved="changed" @upload="uploadRequestId=null;uploadExpenseId=$event;selectedExpense=null" @download="downloadDocument" />
  <FinanceDocumentForm v-if="uploadExpenseId!==null&&data" :key="`upload-${selectedId}`" :agency-id="Number(selectedId)" :expense-id="uploadExpenseId||null" :request-id="uploadRequestId" :role="portal?'requester':data.role" :data="data" @close="uploadExpenseId=null;uploadRequestId=null" @saved="changed" />
  <div v-if="selectedRecord" class="finance-modal" @click.self="selectedRecord=null"><section class="finance-dialog" role="dialog" aria-modal="true" aria-label="Financial record details"><header><h2>{{ selectedRecord.row.name }}</h2><button @click="selectedRecord=null" aria-label="Close details">×</button></header><dl class="finance-details"><div v-for="c in columnsFor(selectedRecord.kind)" :key="c.key"><dt>{{ c.label }}</dt><dd>{{ display(selectedRecord.row,c) }}</dd></div></dl><p v-if="selectedRecord.row.restrictions" class="finance-callout">{{ selectedRecord.row.restrictions }}</p><p>{{ selectedRecord.row.description||selectedRecord.row.notes }}</p><template v-if="selectedRecord.kind==='programs'"><h3>Program activities</h3><p v-for="e in data.events.filter(e=>e.program_id===selectedRecord.row.id)" :key="e.id">{{ e.name }} · {{ day(e.start_date) }} · {{ e.planned_participants }} planned participants</p></template><form v-if="!portal&&['budgets','allocations'].includes(selectedRecord.kind)" @submit.prevent="amendAuthority"><h3>Amend spending authority</h3><label>New approved amount (USD)<input v-model="amendDraft.amount" type="number" min="0" step="0.01" required /></label><label>Reason<textarea v-model="amendDraft.reason" required maxlength="5000" /></label><p>Changes preserve the audit history and cannot remove funding already paid or committed.</p><button :disabled="loading">Save amendment</button></form><section v-if="!portal"><h3>Recent audit history</h3><p v-for="a in (data.audit||[]).filter(a=>a.object_type===selectedRecord.kind&&a.object_id===selectedRecord.row.id)" :key="a.created_at+a.action">{{ label(a.action) }} · {{ a.actor_name||'System' }} · {{ day(a.created_at) }}<small v-if="auditReason(a)">{{ auditReason(a) }}</small></p></section><button @click="selectedRecord=null">Close</button></section></div>
  <div v-if="selectedRequest" class="finance-modal" @click.self="selectedRequest=null"><section class="finance-dialog" role="dialog" aria-modal="true" aria-label="Finance request"><header><h2>{{ selectedRequest.title }}</h2><button @click="selectedRequest=null" aria-label="Close request">×</button></header><p>{{ selectedRequest.description }}</p><p>Status: {{ label(selectedRequest.status) }} · Due {{ day(selectedRequest.due_date) }}</p><p v-if="selectedRequest.response" class="finance-callout">{{ selectedRequest.response }}</p><div v-for="d in visibleDocuments.filter(d=>d.request_id===selectedRequest.id)" :key="d.id"><button @click="downloadDocument(d)">{{ d.name }}</button></div><button v-if="data.role!=='viewer'" @click="uploadRequestId=selectedRequest.id;selectedRequest=null;uploadExpenseId=0">Upload supporting report</button><form v-if="!portal&&data.role==='manager'" @submit.prevent="respondRequest"><label>Response<textarea v-model="requestResponse" required maxlength="5000" /></label><label>Status<select v-model="requestStatus"><option v-for="s in ['open','in_review','needs_info','completed']" :key="s" :value="s">{{ label(s) }}</option></select></label><button class="primary">Save response</button></form></section></div>
</div>
</template>
<script setup>
import {ref,computed,watch,onBeforeUnmount} from 'vue';import {useRoute,useRouter} from 'vue-router';import {useAuthStore} from '../store/auth';import api from '../services/api';
import FinanceSetupForm from '../components/finance/FinanceSetupForm.vue';
import FinanceRecordForm from '../components/finance/FinanceRecordForm.vue';import FinanceExpenseDrawer from '../components/finance/FinanceExpenseDrawer.vue';import FinanceDocumentForm from '../components/finance/FinanceDocumentForm.vue';import FinanceBankPanel from '../components/finance/FinanceBankPanel.vue';import {money,day,label,dollarCents} from '../components/finance/financeForms';
import '../components/finance/finance.css';
const setupOpen=ref(false);
const auth=useAuthStore(),route=useRoute(),router=useRouter(),organizations=ref([]),selectedId=ref('all'),data=ref(null),section=ref(String(route.query.area||'hub')),loading=ref(false),error=ref(''),notice=ref(''),search=ref(''),statusFilter=ref(''),programFilter=ref(''),previewPortal=ref(false),formKind=ref(''),selectedExpense=ref(null),uploadRequestId=ref(null),uploadExpenseId=ref(null),selectedRecord=ref(null),selectedRequest=ref(null),requestResponse=ref(''),requestStatus=ref('in_review'),amendDraft=ref({amount:'',reason:''}),settingsDraft=ref({}),accessDraft=ref({userId:'',role:'requester'});let generation=0,alive=true;
onBeforeUnmount(()=>{alive=false;generation++;});
const organization=computed(()=>organizations.value.find(o=>String(o.agency_id)===selectedId.value)),portal=computed(()=>!!data.value&&(data.value.role!=='manager'||previewPortal.value));
const brandStyle=computed(()=>{let colors=organization.value?.color_palette||{};try{if(typeof colors==='string')colors=JSON.parse(colors);}catch{colors={};}const primary=/^#[\da-f]{6}$/i.test(colors.primary||'')?colors.primary:'#167c75';return {'--finance-brand':primary};});
const initials=s=>s.split(/\s+/).slice(0,2).map(s=>s[0]).join('');const orgPath=p=>`${route.params.organizationSlug?'/'+route.params.organizationSlug:''}${p}`;
const fullNav=[['overview','Overview','⌂'],['funds','Funds','▥'],['budgets','Budgets','▤'],['allocations','Allocations','⇄'],['grants','Grants','◇'],['programs','Programs','◈'],['events','Events & Trips','▦'],['expenses','Expenses','▣'],['approvals','Approvals','✓'],['payments','Payments','▰'],['bank','Bank & Reconciliation','↔'],['reports','Reports','▥'],['partners','People & Partners','♧'],['documents','Documents','▱'],['support','Support & Requests','○'],['settings','Settings','⚙']];
const portalKeys=['overview','budgets','expenses','payments','reports','documents','support'];
const navigation=computed(()=>fullNav.filter(([key])=>!portal.value||portalKeys.includes(key)).map(([key,title,icon])=>({key,label:portal.value?({budgets:'Program Budgets',expenses:'Expense Requests'}[key]||title):selectedId.value==='all'&&key==='overview'?'Portfolio Overview':title,icon})));
const hubAreas=computed(()=>[{section:'budgets',title:'Budgets & Planning',description:'Program budgets, commitments, and available spending.',icon:'▥',color:'#608beb'},{section:portal.value?'budgets':'funds',title:portal.value?'Program Funding':'Funds & Allocations',description:'Funding purpose, restrictions, and program support.',icon:'▤',color:'#18a6b4'},{section:'expenses',title:'Expense Requests',description:'Receipts, reimbursements, scholarship requests, and review.',icon:'▱',color:'#ed9861'},{section:'payments',title:'Payments & Disbursements',description:'Approved requests, recorded payments, and reconciliation.',icon:'▰',color:'#9b70d8'},{section:'reports',title:'Reports & Statements',description:'Spending summaries, grant reports, and shared documents.',icon:'▥',color:'#47ad82'},{section:portal.value?'support':'grants',title:portal.value?'Finance Team Support':'Grants & Fiscal Sponsorship',description:portal.value?'Budget changes, questions, and program reporting.':'Sponsored organizations, grant funding, and deadlines.',icon:'◇',color:'#2bb7cd'}]);
const pageTitle=computed(()=>navigation.value.find(n=>n.key===section.value)?.label||'Finance Operations');
const descriptions={overview:'See funding, commitments, spending, and the next action for each program.',funds:'Track money received, restrictions, and funding purpose.',budgets:'Approved program budgets and spending capacity.',allocations:'Assign budget authority to specific program purposes.',grants:'Track awards, restrictions, periods, and reporting obligations.',programs:'Connect financial support to the programs that deliver the work.',events:'Training, gatherings, mentoring, trips, and experience awards.',expenses:'Submit, document, review, and follow expense requests.',approvals:'Review submitted expenses and supporting evidence.',payments:'Follow reimbursements, vendor payments, and scholarship disbursements.',reports:'Compare approved budgets, commitments, and paid expenses.',partners:'Grantors, vendors, collaborators, and financial contacts.',documents:'Keep financial evidence attached to the records it supports.',support:'Ask the finance team for help or request a budget change.',bank:'Review bank activity without duplicating accounting entries.',settings:'Organization consent, fiscal periods, and delegated finance access.'};
const pageDescription=computed(()=>selectedId.value==='all'?'Manage only the organizations you are authorized to support.':descriptions[section.value]);
const singular={programs:'program',events:'activity',funds:'fund',grants:'grant',budgets:'budget',allocations:'allocation',partners:'partner',support:'request'};
const canCreate=computed(()=>data.value&&data.value.role!=='viewer'&&(['expenses','support'].includes(section.value)||(!portal.value&&Object.keys(singular).includes(section.value))));
const metrics=computed(()=>{const t=data.value?.totals||{};if(section.value==='funds'||section.value==='grants')return [{label:'Grant awards',amount:t.awarded,hint:'Awarded, not cash received'},{label:'Funds received',amount:t.received,hint:'Recorded receipts'},{label:'Paid expenses',amount:t.paid,hint:'Completed external payments'},{label:'Uncommitted funds',amount:t.fundAvailable,hint:'Received less paid and commitments'}];return [{label:'Approved budgets',amount:t.budget,hint:'Program spending authority'},{label:'Paid to date',amount:t.paid,hint:'Recorded completed payments'},{label:'Committed',amount:t.committed,hint:'Approved or scheduled, unpaid'},{label:'Available to spend',amount:t.available,hint:'Budget less paid and committed'}];});
const liveOrganizations=computed(()=>organizations.value.filter(o=>!o.is_demo));
const portfolioMetrics=computed(()=>[{label:'Live organizations',value:liveOrganizations.value.length},{label:'Approved budgets',value:money(liveOrganizations.value.reduce((n,o)=>n+Number(o.summary?.budget||0),0))},{label:'Committed',value:money(liveOrganizations.value.reduce((n,o)=>n+Number(o.summary?.committed||0),0))},{label:'Paid',value:money(liveOrganizations.value.reduce((n,o)=>n+Number(o.summary?.paid||0),0))}]);
const programSummary=computed(()=>data.value?.programs.map(p=>({...p,budget:data.value.budgets.filter(b=>b.program_id===p.id).reduce((n,b)=>n+Number(b.amount_cents),0),paid:data.value.expenses.filter(e=>e.program_id===p.id&&e.status==='paid').reduce((n,e)=>n+Number(e.amount_cents),0),committed:data.value.expenses.filter(e=>e.program_id===p.id&&['approved','scheduled'].includes(e.status)).reduce((n,e)=>n+Number(e.amount_cents),0)}))||[]);
const percent=(n,d)=>d?Math.min(100,Math.max(0,n/d*100)):0;const programName=id=>data.value?.programs.find(p=>p.id===id)?.name||'—';
const pendingExpenses=computed(()=>data.value?.expenses.filter(e=>['submitted','in_review','needs_info'].includes(e.status))||[]),payableExpenses=computed(()=>data.value?.expenses.filter(e=>['approved','scheduled'].includes(e.status))||[]),reporting=computed(()=>data.value?.requests.filter(r=>r.kind==='report'&&r.status!=='completed')||[]);
const statuses=['draft','submitted','in_review','needs_info','approved','scheduled','paid','rejected','void'];
function matchesSearch(value){return String(value).toLowerCase().includes(search.value.toLowerCase());}
const expenseRows=computed(()=>(data.value?.expenses||[]).filter(e=>matchesSearch(e.title)&&(!statusFilter.value||e.status===statusFilter.value)&&(!programFilter.value||e.program_id===Number(programFilter.value))&&(section.value!=='approvals'||['submitted','in_review','needs_info'].includes(e.status))&&(section.value!=='payments'||['approved','scheduled','paid'].includes(e.status))));
const visibleDocuments=computed(()=>(data.value?.documents||[]).filter(d=>!portal.value||d.visibility==='organization'));
const col=(key,title,type)=>({key,label:title,type});
function columnsFor(kind){return ({funds:[col('name','Fund'),col('kind','Type','label'),col('received','Received','money'),col('restrictions','Restrictions')],grants:[col('name','Grant'),col('award_cents','Award','money'),col('fund_id','Fund','funds'),col('end_date','Ends','date'),col('report_due','Report due','date')],budgets:[col('name','Budget'),col('program_id','Program','programs'),col('amount_cents','Approved','money'),col('start_date','Starts','date'),col('end_date','Ends','date')],allocations:[col('name','Allocation'),col('budget_id','Budget','budgets'),col('amount_cents','Allocated','money')],programs:[col('name','Program'),col('description','Purpose'),col('status','Status','label')],events:[col('name','Activity'),col('program_id','Program','programs'),col('kind','Type','label'),col('start_date','Starts','date'),col('planned_participants','Planned participants')],partners:[col('name','Partner'),col('kind','Type','label'),col('contact','Contact')]})[kind]||[];}
const columns=computed(()=>columnsFor(section.value));const collection=computed(()=>(data.value?.[section.value]||[]).filter(r=>matchesSearch(r.name)));
function display(row,c){if(c.key==='received')return money((data.value.receipts||[]).filter(r=>r.fund_id===row.id).reduce((n,r)=>n+Number(r.amount_cents),0));if(c.type==='money')return money(row[c.key]);if(c.type==='date')return day(row[c.key]);if(c.type==='label')return label(row[c.key]);if(['programs','funds','budgets'].includes(c.type))return data.value[c.type]?.find(r=>r.id===row[c.key])?.name||'—';return row[c.key]||'—';}
function auditReason(a){try{const d=typeof a.detail_json==='string'?JSON.parse(a.detail_json):a.detail_json;return d?.reason||'';}catch{return '';}}
const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
function resetPanels(){formKind.value='';selectedExpense.value=null;uploadExpenseId.value=null;uploadRequestId.value=null;selectedRecord.value=null;selectedRequest.value=null;search.value='';statusFilter.value='';programFilter.value='';}
function go(area){section.value=area;resetPanels();router.replace({query:{...route.query,area}});}
async function loadOrganizations(){const r=await api.get('/finance-operations/organizations');if(alive)organizations.value=r.data.organizations||[];}
async function loadScope(){const v=++generation;data.value=null;loading.value=true;error.value='';resetPanels();try{if(selectedId.value==='all')return;const r=await api.get(`/finance-operations/${selectedId.value}/workspace`);if(v!==generation)return;data.value=r.data;settingsDraft.value={revision:r.data.organization.revision,fiscalStartMonth:r.data.organization.fiscal_start_month,bankEnabled:!!r.data.organization.bank_enabled,bankConsentConfirmed:false};}catch(e){if(v===generation)error.value=e.response?.data?.error?.message||'This financial workspace is unavailable';}finally{if(v===generation)loading.value=false;}}
async function refresh(){loading.value=true;error.value='';data.value=null;organizations.value=[];try{await loadOrganizations();if(alive)await loadScope();}catch(e){if(alive){error.value=e.response?.data?.error?.message||'Finance Operations is unavailable. Check module setup and access.';loading.value=false;}}}
async function changed(){resetPanels();await refresh();}
async function createDemo(){loading.value=true;error.value='';try{const r=await api.post('/finance-operations/demo',{});if(!alive)return;await loadOrganizations();selectedId.value=String(r.data.agencyId);section.value='overview';await loadScope();}catch(e){if(alive)error.value=e.response?.data?.error?.message||'Demo setup could not complete';}finally{if(alive)loading.value=false;}}
async function downloadDocument(doc){const v=generation;try{const r=await api.get(`/finance-operations/${selectedId.value}/documents/${doc.id}`,{responseType:'blob'});if(v===generation)download(r.data,doc.name);}catch(e){if(v===generation)error.value='Document is unavailable or access changed';}}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function exportExpenses(kind='expenses'){const v=generation;try{const r=await api.get(`/finance-operations/${selectedId.value}/reports/${kind}.csv`,{responseType:'blob'});if(v===generation)download(r.data,`${organization.value.is_demo?'DEMO-':''}finance-${kind}.csv`);}catch{if(v===generation)error.value='Report could not be exported';}}
async function amendAuthority(){try{const r=selectedRecord.value;const amount=amendDraft.value.amount!==''&&Number(amendDraft.value.amount)===0?0:dollarCents(amendDraft.value.amount);await mutate(`authority/${r.kind}/${r.row.id}`,{amountCents:amount,previousAmountCents:Number(r.row.amount_cents),revision:r.row.revision,reason:amendDraft.value.reason});}catch(e){error.value=e.message;}}
async function saveSettings(){await mutate('settings',settingsDraft.value);}
async function saveAccess(){await mutate('access',accessDraft.value);}
async function respondRequest(){await mutate(`requests/${selectedRequest.value.id}`,{revision:selectedRequest.value.revision,status:requestStatus.value,response:requestResponse.value});}
async function mutate(path,body){const v=generation;error.value='';loading.value=true;try{await api.put(`/finance-operations/${selectedId.value}/${path}`,body);if(v===generation){notice.value='Saved.';await refresh();}}catch(e){if(v===generation)error.value=e.response?.data?.error?.message||'Could not save changes';}finally{if(v===generation)loading.value=false;}}
watch(selectedRecord,()=>{amendDraft.value={amount:'',reason:''};});
watch(()=>route.query.area,area=>{section.value=String(area||'hub');resetPanels();});
watch(selectedId,()=>{previewPortal.value=false;notice.value='';loadScope();});watch(portal,value=>{if(value&&!portalKeys.includes(section.value)&&section.value!=='hub')go('overview');});watch(section,()=>{search.value='';statusFilter.value='';programFilter.value='';});
(async()=>{loading.value=true;try{await loadOrganizations();if(!alive)return;const scoped=route.params.organizationSlug&&organizations.value.find(o=>o.slug===route.params.organizationSlug);if(scoped)selectedId.value=String(scoped.agency_id);else if(organizations.value.length===1)selectedId.value=String(organizations.value[0].agency_id);else loading.value=false;}catch{if(alive){error.value='Finance Operations needs setup or finance access.';loading.value=false;}}})();
</script>
