<template><div class="ft-surface ft-entry"><header class="ft-wrap"><router-link to="/fundthred" aria-label="FundThred home"><FundThredBrand/></router-link><a href="/dashboard">PlotTwistHQ ↗</a></header><main class="ft-wrap"><p class="ft-eyebrow">Welcome to FundThred</p><h1>Your mission.<br><em>Your financial workspace.</em></h1><template v-if="!auth.isAuthenticated"><p>Sign in with your existing account to open your organization’s finance workspace.</p><router-link class="ft-button" :to="fundthredLoginLocation()">Sign in to FundThred →</router-link><p class="ft-small ft-entry-help">New to FundThred? <router-link to="/fundthred/start">Let’s talk about your organization.</router-link></p></template><template v-else><p>Choose an organization to continue. These are the workspaces available with your finance permissions.</p><p v-if="loading" role="status">Loading your organizations…</p><div v-else-if="error" class="ft-entry-error"><p role="alert">{{ error }}</p><button class="ft-button ft-button--outline" @click="load">Try again</button></div><template v-else><div v-if="organizations.length" class="ft-entry-organizations"><router-link v-for="organization in organizations" :key="organization.agency_id" :to="fundthredWorkspacePath(organization.slug)"><img v-if="organization.logo_url" :src="organization.logo_url" :alt="organization.name"><FundThredIcon v-else name="programs"/><div><h2>{{ organization.name }}</h2><p>{{ organization.role==='manager'?'Finance administration':'Program portal' }}<span v-if="organization.is_demo"> · Fictional demo</span></p><small v-if="organization.manager_name">Managed by {{ organization.manager_name }}</small></div><span aria-hidden="true">→</span></router-link></div><div v-else class="ft-entry-empty"><FundThredIcon name="shield" tone="teal"/><h2>Your account is ready.</h2><p>No finance organizations are enabled for your account yet. Ask your organization’s administrator to review your finance access.</p><router-link v-if="auth.user?.role==='super_admin'" class="ft-button" to="/finance-operations">Set up an organization →</router-link></div><router-link v-if="organizations.length>1" class="ft-button ft-button--outline" to="/finance-operations">View authorized portfolio →</router-link></template></template><section class="ft-entry-connected"><h2>Part of your bigger picture.</h2><p>FundThred is your finance entrance. Your other enabled products are available through PlotTwistHQ.</p><div class="ft-actions"><a class="ft-text-link" href="/dashboard">Open PlotTwistHQ →</a><router-link class="ft-text-link" to="/fundthred/pricing">Explore bundles →</router-link></div></section></main><footer class="ft-wrap">FundThred · Finance operations by Plot Twist Co.</footer></div></template>
<script setup>
import {ref,watch,onBeforeUnmount} from 'vue';
import {useAuthStore} from '../store/auth';
import api from '../services/api';
import {fundthredLoginLocation,fundthredWorkspacePath} from '../utils/fundthred';
import {useFundThredBranding} from '../composables/useFundThredBranding';
import FundThredBrand from '../components/fundthred/FundThredBrand.vue';
import FundThredIcon from '../components/fundthred/FundThredIcon.vue';
import '../styles/fundthred.css';
const auth=useAuthStore(),organizations=ref([]),loading=ref(false),error=ref('');let generation=0;
useFundThredBranding('Your organizations | FundThred');
async function load(){const current=++generation;organizations.value=[];error.value='';if(!auth.isAuthenticated){loading.value=false;return;}loading.value=true;try{const response=await api.get('/finance-operations/organizations');if(current===generation)organizations.value=response.data.organizations||[];}catch(e){if(current===generation)error.value=e.response?.data?.error?.message||'We could not load your financial workspaces. Please try again.';}finally{if(current===generation)loading.value=false;}}
watch(()=>auth.user?.id,load,{immediate:true});onBeforeUnmount(()=>generation++);
</script>
<style scoped>
.ft-entry{min-height:100vh;background:radial-gradient(ellipse at 95% 10%,#e4f3ef,transparent 50%),#fafcfd}.ft-entry>header{display:flex;justify-content:space-between;align-items:center;min-height:110px}.ft-entry>header>a:last-child{font-size:12px;text-decoration:none}.ft-entry>main{padding-block:50px;max-width:1040px}.ft-entry>main>p{max-width:650px}.ft-entry-organizations{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin:30px 0}.ft-entry-organizations>a{display:flex;align-items:center;gap:18px;text-decoration:none;padding:25px;background:#fff;border:1px solid #d9e7ef;border-radius:13px}.ft-entry-organizations>a:hover{border-color:#55a895;box-shadow:0 6px 25px #194b5210}.ft-entry-organizations img{width:48px;height:48px;object-fit:contain}.ft-entry-organizations h2{font-size:20px;margin:0 0 8px}.ft-entry-organizations p{font-size:12px;margin:0}.ft-entry-organizations small{font-size:11px;color:#698293}.ft-entry-organizations>a>span:last-child{margin-left:auto}.ft-entry-empty{padding:32px;border:1px solid #dce7ee;border-radius:15px;background:#fff;max-width:650px;margin:30px 0}.ft-entry-empty h2{font-size:26px;margin-top:20px}.ft-entry-help{margin-top:20px!important}.ft-entry-connected{border-top:1px solid #dce7ee;margin-top:55px;padding-top:30px}.ft-entry-connected h2{font-size:25px}.ft-entry-connected p{max-width:650px;font-size:14px}.ft-entry>footer{font-size:11px;color:#637d91;padding-block:25px}.ft-entry-error{margin-block:25px}.ft-entry-error [role=alert]{color:#96382f}@media(max-width:650px){.ft-entry>main{padding-top:25px}.ft-entry-organizations{grid-template-columns:1fr}.ft-entry-organizations>a{padding:20px}.ft-entry>header .ft-brand{width:150px}}
</style>
