<template><main class="staff-text-assistant"><h1>Your text request</h1><p>Your text started this request. Account information is shown after sign-in. Review the request below and send it to the app assistant when ready. No action was taken from the text alone.</p><p v-if="error" role="alert">{{ error }}</p><p v-else-if="!request">Loading your request…</p><template v-else><p>Received {{ new Date(request.createdAt).toLocaleString() }}</p><AskAssistantPanel :key="request.id" open variant="embedded" :context-agency-id="Number(request.agencyId)" :seed-prompt="request.prompt" placement-key="staff_sms_handoff" @compose-message="composeDraft=$event" /><section v-if="composeDraft"><h2>Review your message draft</h2><textarea :value="composeDraft.draft||''" readonly rows="5" /><p>Copy this draft, then open the recipient’s conversation to review and send it. No message has been sent.</p><button @click="copyDraft">Copy draft</button><button @click="openMessages">Open recipient in Messages</button><p role="status">{{ copyStatus }}</p></section></template></main></template>
<script setup>
import {ref,watch} from 'vue';import {useRoute,useRouter} from 'vue-router';import api from '../services/api';import AskAssistantPanel from '../components/assistant/AskAssistantPanel.vue';
const route=useRoute(),router=useRouter(),request=ref(null),error=ref(''),composeDraft=ref(null),copyStatus=ref('');let seq=0;
async function copyDraft(){try{await navigator.clipboard.writeText(composeDraft.value?.draft||'');copyStatus.value='Copied. Review it in Messages before sending.';}catch{copyStatus.value='Select and copy the draft above.';}}
function openMessages(){router.push({path:'/messages',query:{openChatWith:String(composeDraft.value.userId),agencyId:String(composeDraft.value.agencyId||request.value.agencyId)}});}

watch(()=>route.params.requestId,async id=>{const key=++seq;request.value=null;composeDraft.value=null;copyStatus.value='';error.value='';try{const {data}=await api.get(`/me/sms-assistant-requests/${encodeURIComponent(id)}`);if(key===seq)request.value=data;}catch{if(key===seq)error.value='This request is unavailable, belongs to another account, or has expired. Sign in to your staff account or text a new request.';}},{immediate:true});
</script>
<style scoped>.staff-text-assistant{max-width:1100px;margin:24px auto;padding:24px;color:#21394e}.staff-text-assistant>p{line-height:1.6}.staff-text-assistant :deep(.aap-root){min-height:650px}[role=alert]{color:#a72121}</style>
