export const pages = {
  '': {title: 'Fitness groups. Team challenges. Shared progress.', description: 'Bring your fitness club or community group together with Summit Stats Team Challenge. Organize seasons, log workouts, follow leaderboards, and celebrate progress.'},
  features: {title: 'Everything your next challenge needs', description: 'Explore clubs, teams, seasons, workout logging, scoring, weekly challenges, leaderboards, and recognition in the Summit Stats web application.'},
  'how-it-works': {title: 'From a group idea to your first season', description: 'See how organizers create a club, set up a season, invite participants, and run a fitness competition with Summit Stats Team Challenge.'},
  groups: {title: 'Built for the people who move together', description: 'Fitness clubs and community groups can organize shared activity and friendly competition. Explore uses for running groups, coaches, and voluntary workplace groups.'},
  tour: {title: 'Picture your next challenge', description: 'Explore an illustrative Summit Stats season: team standings, workout logging, and weekly challenges. All examples use fictional data.'},
  pricing: {title: 'Start your club. Try it together.', description: 'New Summit Stats clubs start with three months of free, unlimited access. No credit card required. Use the existing club-manager signup to get started.'},
  faq: {title: 'A few things worth knowing', description: 'Answers about starting a club, joining a group, challenge scoring, supported activity tracking, the free trial, and participant privacy.'},
  about: {title: 'Shared effort deserves a shared home', description: 'Summit Stats Team Challenge is a Plot Twist Co. web application for fitness groups and competitions. Learn what it does and who it serves.'},
  contact: {title: 'Let’s get your group moving', description: 'Ask the Summit Stats team about club setup, fitness competitions, current pricing, or an existing account. Send a message through the support system.'}
};
export const features = [
  {number:'01', title:'A home for your club', body:'Keep your group’s seasons, announcements, and participation together. Club managers guide setup and member access.', detail:'Public club pages and join requests give people a place to find your group; visibility follows your club’s configuration.'},
  {number:'02', title:'Seasons with a finish line', body:'Give each competition its own dates, teams, and rules. Make a fresh start each season without losing the identity of your club.', detail:'Set activity categories, scoring weights, and submission deadlines for the season you want to run.'},
  {number:'03', title:'Workouts that count', body:'Participants log activities and the details that matter to their challenge, such as distance, duration, or calories.', detail:'Manual entry and screenshot uploads are available. Strava imports are available where enabled and connected; review entries before submitting.'},
  {number:'04', title:'Standings worth following', body:'Keep team competition visible with leaderboards and season progress. Scores reflect the rules your organizer configures.', detail:'Distance-based and calorie-based competition options support different challenge formats. Explain your scoring before the season starts.'},
  {number:'05', title:'Reasons to keep showing up', body:'Use weekly challenges, recognition, and club conversation to make the experience about more than the final result.', detail:'Announcements, team messages, activity discussion, and awards help organizers keep the group connected.'},
  {number:'06', title:'Tools for the organizer', body:'Manage teams, participant requests, season participation, workout review, and the details behind a well-run competition.', detail:'Club managers, captains, and participants have different responsibilities and access. Team drafting is available for supported season setups.'}
];
export const steps = [
  ['Start with an organizer account', 'Choose Start My Club, create your account, and verify your email. Follow the existing setup and review steps; an account alone is not a published club.'],
  ['Give your club a home', 'Set up the group identity and decide who can join. Review member access and any public club information before you invite people.'],
  ['Design a season people understand', 'Choose dates, teams, activity categories, scoring, and deadlines. Tell participants what counts and how submissions will be reviewed.'],
  ['Invite your people and get moving', 'Share the club’s invitation or join instructions. Participants use their own accounts, join the appropriate club and season, and log their activities.'],
  ['Follow progress. Celebrate. Repeat.', 'Check standings, run weekly challenges, recognize contributions, and keep the conversation going. Use what you learn to shape the next season.']
];
export const faqs = [
  ['What is Summit Stats Team Challenge?', 'It is a web application for organizing fitness groups and team competitions. Clubs bring people together; seasons define a competition; teams, workouts, leaderboards, weekly challenges, and recognition keep the experience moving.'],
  ['Am I starting a club or joining one?', 'Use Start My Club if you will organize a new group. If someone invited you to an existing group, use that invitation and its instructions. You can also browse public clubs or log in to an existing account. You do not need to create a new club to participate.'],
  ['What is the current price?', 'The published club-manager signup offers new clubs three months of free, unlimited access with no credit card required. The trial starts when the club is created. Paid rates after that period are not currently published in the signup flow; contact the team for current details before making a longer-term commitment.'],
  ['Does signup immediately activate my club?', 'Create the club-manager account and verify your email, then complete the setup and review steps shown in the app. Account creation, club setup, and participant access are separate steps.'],
  ['Which activities can a group track?', 'The app supports activity entries such as running, rucking, walking, cycling, and workouts. Available activity categories, required information, and scoring depend on the season’s configuration. Ask your organizer what counts for your challenge.'],
  ['Do participants need a specific watch or device?', 'No specific fitness watch is required for manual activity entry. Screenshot uploads are also available. Strava imports require a connected account and an enabled integration. Direct Garmin integration is not currently available.'],
  ['How do points and leaderboards work?', 'The organizer chooses the season format and scoring configuration. Activity entries contribute according to those rules; weekly challenges can add another way to participate. Review the rules and submission deadlines before your first workout.'],
  ['Is the information in the website tour real?', 'No. The tour is an illustration of the workflow using fictional teams and sample scores. It is not a live club, an actual account, or a place to submit a workout.'],
  ['Who can see participant information?', 'Visibility depends on club settings, roles, and the information participants share. Some club information may be public, while member and manager areas require appropriate access. Organizers should review settings and explain them to participants before inviting the group.'],
  ['Can youth groups use it?', 'An adult organizer should first review the platform terms, eligibility requirements, applicable consent needs, and club visibility settings. Contact the team about your group before enrolling minors; the marketing site does not establish eligibility or collect children’s information.'],
  ['Is this medical care or an individualized training plan?', 'No. Summit Stats organizes activity and competition; it does not provide medical care or replace qualified training advice. Organizers should set appropriate participation expectations and avoid pressuring members to overtrain or share sensitive health information.'],
  ['Where do existing members get help?', 'Use the app’s Summit Stats support page for account or integration help. For club rules, scoring questions, or membership decisions, start with your club organizer. Do not include passwords, payment-card details, or sensitive health information in a support message.']
];
